/-
# Kahn Kalai
Category: Frontier Math
Target: Math2.kahn_kalai
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

/-!
# Kahn Kalai
Category: Frontier Math
Target: Math2.kahn_kalai
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)

## Contents

This file sets up the finite-probability framework in which the Kahn–Kalai conjecture
(a theorem of Park and Pham) is stated: for a finite ground set `X`, `mu X p F` is the
probability that the `p`-random subset of `X` belongs to the family `F`, `upClosure X H`
is the increasing family generated by `H`, and `IsSmall q H` says that `H` is `q`-small
in the sense of Kahn and Kalai (it admits a cover of `q`-cost at most `1/2`).
`expThreshold H` is the resulting expectation threshold and `critProb X F` the critical
probability.

## Scope of what is proved

* `Math2.expThreshold_le_critProb`: for **arbitrary** families, `expThreshold H ≤ critProb`.
  This is the easy half of the comparison; it rests on the exact computation of the
  probability that the `p`-random set contains a fixed set (`Math2.sum_supersets`) together
  with a union bound (`Math2.mu_le_sum_of_covers`).
* `Math2.critProb_le_two_mul_expThreshold`: for families of **pairwise disjoint**
  generators, `critProb ≤ 2 * expThreshold`; here no logarithmic factor is needed.  This uses
  the exact product formula `Math2.mu_upClosure_disjoint`, which is proved from a
  factorisation of the product measure over disjoint blocks (`Math2.mu_split`).
* `Math2.kahn_kalai` packages the two bounds in the Kahn–Kalai shape
  `critProb ≤ K * expThreshold * log₂ (2ℓ)` with the universal constant `K = 2`.
* `Math2.kahn_kalai_one_bounded`: the two-sided comparison for all `1`-bounded families,
  with no further hypotheses.

The general Kahn–Kalai conjecture (the theorem of Park and Pham), i.e. the upper bound
`critProb ≤ K * expThreshold * log₂ (2ℓ)` for arbitrary `ℓ`-bounded families, is **not**
formalised here; it is recorded as a comment at the end of the file.
-/

open Finset

namespace Math2

variable {α : Type} [DecidableEq α]

/-! ## Basic definitions -/

/-- `mu X p F` is the probability that the `p`-random subset of the finite ground set `X`
(each element of `X` included independently with probability `p`) lies in the family `F`. -/

theorem critProb_le_two_mul_expThreshold (X : Finset α) (H : Finset (Finset α))
    (hsub : ∀ h ∈ H, h ⊆ X) (hdisj : (H : Set (Finset α)).PairwiseDisjoint id) :
    critProb X (upClosure X H) ≤ 2 * expThreshold H := by
  by_cases hne : {p : ℝ | 0 ≤ p ∧ p ≤ 1 ∧ mu X p (upClosure X H) ≤ 1 / 2}.Nonempty
  · refine csSup_le hne ?_
    intro p hp
    by_contra hcon
    push_neg at hcon
    have hp0 : 0 ≤ p := hp.1
    have hp1 : p ≤ 1 := hp.2.1
    have hq0 : 0 ≤ p / 2 := by linarith
    have hq1 : p / 2 ≤ 1 := by linarith
    have hexp : 0 ≤ expThreshold H := expThreshold_nonneg H
    have hnot : IsSmall (p / 2) H → False := by
      intro hs
      have : p / 2 ≤ expThreshold H := le_csSup (bddAbove_smallSet H) ⟨hq0, hq1, hs⟩
      linarith
    have hgt := mu_gt_half_of_not_isSmall_disjoint X H (p / 2) p hsub hdisj hq0 hp1
      (by linarith) hnot
    linarith [hp.2.2]
  · rw [Set.not_nonempty_iff_eq_empty] at hne
    rw [critProb, hne, Real.sSup_empty]
    have := expThreshold_nonneg H
    linarith

/-! ## Main statement -/

/-- **Kahn–Kalai: the expectation threshold and the critical probability agree up to a
logarithmic factor.**

Here `mu X p F` is the probability that the `p`-random subset of the finite ground set `X`
belongs to the family `F`, `upClosure X H` is the increasing family generated by `H`,
`IsSmall q H` is the Kahn–Kalai notion of `q`-smallness, `expThreshold H` is the resulting
expectation threshold and `critProb X F` the critical probability.  The parameter `ℓ` is a
bound on the size of the generators; the hypothesis `∀ h ∈ H, h.card ≤ ℓ` is part of the
Kahn–Kalai formulation (it is what the logarithmic factor refers to) and is retained even
though the proof below does not need it.

The first inequality is proved for arbitrary families of generators.  The second
(the difficult direction, the Kahn–Kalai conjecture proved in general by Park and Pham) is
established here for families of **pairwise disjoint** generators, where in fact the sharper
bound `critProb ≤ 2 * expThreshold` holds, see `critProb_le_two_mul_expThreshold`; the
logarithmic factor `log₂ (2ℓ) ≥ 1` is then absorbed. -/
