/-
# Kahn Kalai
Category: Frontier Math
Target: Math2.kahn_kalai
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

/-!
# Kahn Kalai
Category: Frontier Math
Target: Math2.kahn_kalai
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)

## Contents

This file sets up the finite-probability framework in which the Kahn–Kalai conjecture
(a theorem of Park and Pham) is stated: for a finite ground set `X`, `mu X p F` is the
probability that the `p`-random subset of `X` belongs to the family `F`, `upClosure X H`
is the increasing family generated by `H`, and `IsSmall q H` says that `H` is `q`-small
in the sense of Kahn and Kalai (it admits a cover of `q`-cost at most `1/2`).
`expThreshold H` is the resulting expectation threshold and `critProb X F` the critical
probability.

## Scope of what is proved

* `Math2.expThreshold_le_critProb`: for **arbitrary** families, `expThreshold H ≤ critProb`.
  This is the easy half of the comparison; it rests on the exact computation of the
  probability that the `p`-random set contains a fixed set (`Math2.sum_supersets`) together
  with a union bound (`Math2.mu_le_sum_of_covers`).
* `Math2.critProb_le_two_mul_expThreshold`: for families of **pairwise disjoint**
  generators, `critProb ≤ 2 * expThreshold`; here no logarithmic factor is needed.  This uses
  the exact product formula `Math2.mu_upClosure_disjoint`, which is proved from a
  factorisation of the product measure over disjoint blocks (`Math2.mu_split`).
* `Math2.kahn_kalai` packages the two bounds in the Kahn–Kalai shape
  `critProb ≤ K * expThreshold * log₂ (2ℓ)` with the universal constant `K = 2`.
* `Math2.kahn_kalai_one_bounded`: the two-sided comparison for all `1`-bounded families,
  with no further hypotheses.

The general Kahn–Kalai conjecture (the theorem of Park and Pham), i.e. the upper bound
`critProb ≤ K * expThreshold * log₂ (2ℓ)` for arbitrary `ℓ`-bounded families, is **not**
formalised here; it is recorded as a comment at the end of the file.
-/

open Finset

namespace Math2

variable {α : Type} [DecidableEq α]

/-! ## Basic definitions -/

/-- `mu X p F` is the probability that the `p`-random subset of the finite ground set `X`
(each element of `X` included independently with probability `p`) lies in the family `F`. -/

theorem expThreshold_le_critProb (X : Finset α) (H : Finset (Finset α)) :
    expThreshold H ≤ critProb X (upClosure X H) := by
  by_cases hne : {q : ℝ | 0 ≤ q ∧ q ≤ 1 ∧ IsSmall q H}.Nonempty
  · refine csSup_le hne ?_
    intro q hq
    exact le_csSup (bddAbove_critSet _ _)
      ⟨hq.1, hq.2.1, mu_le_half_of_isSmall hq.1 le_rfl hq.2.1 X H hq.2.2⟩
  · rw [Set.not_nonempty_iff_eq_empty] at hne
    rw [expThreshold, hne, Real.sSup_empty]
    exact critProb_nonneg _ _

/-- **Converse bound for pairwise disjoint generators**: the critical probability is at most
twice the expectation threshold. -/
