/-
# Kahn Kalai
Category: Frontier Math
Target: Math2.kahn_kalai
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

/-!
# Kahn Kalai
Category: Frontier Math
Target: Math2.kahn_kalai
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)

## Contents

This file sets up the finite-probability framework in which the Kahn–Kalai conjecture
(a theorem of Park and Pham) is stated: for a finite ground set `X`, `mu X p F` is the
probability that the `p`-random subset of `X` belongs to the family `F`, `upClosure X H`
is the increasing family generated by `H`, and `IsSmall q H` says that `H` is `q`-small
in the sense of Kahn and Kalai (it admits a cover of `q`-cost at most `1/2`).
`expThreshold H` is the resulting expectation threshold and `critProb X F` the critical
probability.

## Scope of what is proved

* `Math2.expThreshold_le_critProb`: for **arbitrary** families, `expThreshold H ≤ critProb`.
  This is the easy half of the comparison; it rests on the exact computation of the
  probability that the `p`-random set contains a fixed set (`Math2.sum_supersets`) together
  with a union bound (`Math2.mu_le_sum_of_covers`).
* `Math2.critProb_le_two_mul_expThreshold`: for families of **pairwise disjoint**
  generators, `critProb ≤ 2 * expThreshold`; here no logarithmic factor is needed.  This uses
  the exact product formula `Math2.mu_upClosure_disjoint`, which is proved from a
  factorisation of the product measure over disjoint blocks (`Math2.mu_split`).
* `Math2.kahn_kalai` packages the two bounds in the Kahn–Kalai shape
  `critProb ≤ K * expThreshold * log₂ (2ℓ)` with the universal constant `K = 2`.
* `Math2.kahn_kalai_one_bounded`: the two-sided comparison for all `1`-bounded families,
  with no further hypotheses.

The general Kahn–Kalai conjecture (the theorem of Park and Pham), i.e. the upper bound
`critProb ≤ K * expThreshold * log₂ (2ℓ)` for arbitrary `ℓ`-bounded families, is **not**
formalised here; it is recorded as a comment at the end of the file.
-/

open Finset

namespace Math2

variable {α : Type} [DecidableEq α]

/-! ## Basic definitions -/

/-- `mu X p F` is the probability that the `p`-random subset of the finite ground set `X`
(each element of `X` included independently with probability `p`) lies in the family `F`. -/

theorem mu_gt_half_of_not_isSmall_disjoint (X : Finset α) (H : Finset (Finset α)) (q p : ℝ)
    (hsub : ∀ h ∈ H, h ⊆ X) (hdisj : (H : Set (Finset α)).PairwiseDisjoint id)
    (hq : 0 ≤ q) (hp1 : p ≤ 1) (hpq : 2 * q ≤ p) (hnot : IsSmall q H → False) :
    1 / 2 < mu X p (upClosure X H) := by
  classical
  have hp0 : 0 ≤ p := le_trans (by linarith) hpq
  -- non-smallness applied to the cover `H` itself
  have hcost : 1 / 2 < ∑ h ∈ H, q ^ h.card := by
    by_contra hcon
    push_neg at hcon
    exact hnot ⟨H, fun h hh => ⟨h, hh, subset_refl h⟩, hcon⟩
  rw [mu_upClosure_disjoint X H p hsub hdisj]
  have hfac : ∀ h ∈ H, (0:ℝ) ≤ 1 - p ^ h.card := by
    intro h _
    have : p ^ h.card ≤ 1 := pow_le_one₀ hp0 hp1
    linarith
  by_cases hemp : ∅ ∈ H
  · have : ∏ h ∈ H, (1 - p ^ h.card) = 0 :=
      Finset.prod_eq_zero hemp (by simp)
    rw [this]; norm_num
  · -- every member of `H` is nonempty, so `p ^ |h| ≥ 2 q ^ |h|`
    have hcard1 : ∀ h ∈ H, 1 ≤ h.card := by
      intro h hh
      rcases Nat.eq_zero_or_pos h.card with h0 | h1
      · exact absurd (Finset.card_eq_zero.mp h0 ▸ hh) hemp
      · exact h1
    have hsum : 1 < ∑ h ∈ H, p ^ h.card := by
      have hstep : ∀ h ∈ H, 2 * q ^ h.card ≤ p ^ h.card := by
        intro h hh
        have h1 := hcard1 h hh
        calc 2 * q ^ h.card ≤ 2 ^ h.card * q ^ h.card := by
              have : (2:ℝ) ≤ 2 ^ h.card := by
                calc (2:ℝ) = 2 ^ 1 := by norm_num
                _ ≤ 2 ^ h.card := by
                      apply pow_le_pow_right₀ (by norm_num) h1
              nlinarith [pow_nonneg hq h.card]
          _ = (2 * q) ^ h.card := by rw [mul_pow]
          _ ≤ p ^ h.card := pow_le_pow_left₀ (by linarith) hpq _
      have : 2 * ∑ h ∈ H, q ^ h.card ≤ ∑ h ∈ H, p ^ h.card := by
        rw [Finset.mul_sum]
        exact Finset.sum_le_sum hstep
      linarith
    have hexp : Real.exp (-∑ h ∈ H, p ^ h.card) = ∏ h ∈ H, Real.exp (-(p ^ h.card)) := by
      rw [← Real.exp_sum]
      congr 1
      simp
    have hprod : ∏ h ∈ H, (1 - p ^ h.card) ≤ Real.exp (-∑ h ∈ H, p ^ h.card) := by
      rw [hexp]
      refine Finset.prod_le_prod hfac ?_
      intro h _
      have := Real.add_one_le_exp (-(p ^ h.card))
      linarith
    have hlast : Real.exp (-∑ h ∈ H, p ^ h.card) < 1 / 2 := by
      have h1 : Real.exp (-∑ h ∈ H, p ^ h.card) ≤ Real.exp (-1) :=
        Real.exp_le_exp.mpr (by linarith)
      have h2 : Real.exp (-1 : ℝ) < 1 / 2 := by
        rw [Real.exp_neg, inv_eq_one_div,
          div_lt_div_iff₀ (Real.exp_pos 1) (by norm_num : (0:ℝ) < 2)]
        have := Real.exp_one_gt_d9
        linarith
      linarith
    linarith

/-! ## Thresholds -/

/-- The **expectation threshold** of `H`: the largest `q` for which `H` is `q`-small. -/
