/-
# Kahn Kalai
Category: Frontier Math
Target: Math2.kahn_kalai
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

/-!
# Kahn Kalai
Category: Frontier Math
Target: Math2.kahn_kalai
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)

## Contents

This file sets up the finite-probability framework in which the Kahn–Kalai conjecture
(a theorem of Park and Pham) is stated: for a finite ground set `X`, `mu X p F` is the
probability that the `p`-random subset of `X` belongs to the family `F`, `upClosure X H`
is the increasing family generated by `H`, and `IsSmall q H` says that `H` is `q`-small
in the sense of Kahn and Kalai (it admits a cover of `q`-cost at most `1/2`).
`expThreshold H` is the resulting expectation threshold and `critProb X F` the critical
probability.

## Scope of what is proved

* `Math2.expThreshold_le_critProb`: for **arbitrary** families, `expThreshold H ≤ critProb`.
  This is the easy half of the comparison; it rests on the exact computation of the
  probability that the `p`-random set contains a fixed set (`Math2.sum_supersets`) together
  with a union bound (`Math2.mu_le_sum_of_covers`).
* `Math2.critProb_le_two_mul_expThreshold`: for families of **pairwise disjoint**
  generators, `critProb ≤ 2 * expThreshold`; here no logarithmic factor is needed.  This uses
  the exact product formula `Math2.mu_upClosure_disjoint`, which is proved from a
  factorisation of the product measure over disjoint blocks (`Math2.mu_split`).
* `Math2.kahn_kalai` packages the two bounds in the Kahn–Kalai shape
  `critProb ≤ K * expThreshold * log₂ (2ℓ)` with the universal constant `K = 2`.
* `Math2.kahn_kalai_one_bounded`: the two-sided comparison for all `1`-bounded families,
  with no further hypotheses.

The general Kahn–Kalai conjecture (the theorem of Park and Pham), i.e. the upper bound
`critProb ≤ K * expThreshold * log₂ (2ℓ)` for arbitrary `ℓ`-bounded families, is **not**
formalised here; it is recorded as a comment at the end of the file.
-/

open Finset

namespace Math2

variable {α : Type} [DecidableEq α]

/-! ## Basic definitions -/

/-- `mu X p F` is the probability that the `p`-random subset of the finite ground set `X`
(each element of `X` included independently with probability `p`) lies in the family `F`. -/

theorem mu_split (X A : Finset α) (hA : A ⊆ X) (p : ℝ)
    (P Q : Finset α → Prop) [DecidablePred P] [DecidablePred Q] :
    ∑ S ∈ X.powerset.filter (fun S => P (S ∩ A) ∧ Q (S \ A)),
        p ^ S.card * (1 - p) ^ (X.card - S.card)
      = (∑ U ∈ A.powerset.filter P, p ^ U.card * (1 - p) ^ (A.card - U.card)) *
        (∑ V ∈ (X \ A).powerset.filter Q, p ^ V.card * (1 - p) ^ ((X \ A).card - V.card)) := by
  have key : ∀ U V : Finset α, U ⊆ A → V ⊆ X \ A → ((U ∪ V) ∩ A = U ∧ (U ∪ V) \ A = V) := by
    intro U V hU hV
    have hVA : Disjoint V A := Finset.disjoint_left.mpr fun x hx hxA =>
      (Finset.mem_sdiff.mp (hV hx)).2 hxA
    constructor
    · ext x; simp only [Finset.mem_inter, Finset.mem_union]
      constructor
      · rintro ⟨h1 | h1, h2⟩
        · exact h1
        · exact absurd h2 (Finset.disjoint_left.mp hVA h1)
      · intro h; exact ⟨Or.inl h, hU h⟩
    · ext x; simp only [Finset.mem_sdiff, Finset.mem_union]
      constructor
      · rintro ⟨h1 | h1, h3⟩
        · exact absurd (hU h1) h3
        · exact h1
      · intro h; exact ⟨Or.inr h, fun hA' => Finset.disjoint_left.mp hVA h hA'⟩
  rw [Finset.sum_mul_sum, ← Finset.sum_product']
  refine Finset.sum_nbij' (fun S => (S ∩ A, S \ A)) (fun UV => UV.1 ∪ UV.2) ?_ ?_ ?_ ?_ ?_
  · intro S hS
    simp only [Finset.mem_filter, Finset.mem_powerset] at hS
    simp only [Finset.mem_product, Finset.mem_filter, Finset.mem_powerset]
    exact ⟨⟨Finset.inter_subset_right, hS.2.1⟩,
      Finset.sdiff_subset_sdiff hS.1 (le_refl A), hS.2.2⟩
  · rintro ⟨U, V⟩ hUV
    simp only [Finset.mem_product, Finset.mem_filter, Finset.mem_powerset] at hUV
    obtain ⟨⟨hU, hPU⟩, hV, hQV⟩ := hUV
    obtain ⟨h1, h2⟩ := key U V hU hV
    simp only [Finset.mem_filter, Finset.mem_powerset, h1, h2]
    exact ⟨Finset.union_subset (hU.trans hA) (hV.trans Finset.sdiff_subset), hPU, hQV⟩
  · intro S _
    ext x
    simp only [Finset.mem_union, Finset.mem_inter, Finset.mem_sdiff]
    tauto
  · rintro ⟨U, V⟩ hUV
    simp only [Finset.mem_product, Finset.mem_filter, Finset.mem_powerset] at hUV
    obtain ⟨⟨hU, _⟩, hV, _⟩ := hUV
    obtain ⟨h1, h2⟩ := key U V hU hV
    simp [h1, h2]
  · intro S hS
    simp only [Finset.mem_filter, Finset.mem_powerset] at hS
    have hSX := hS.1
    have hcard : S.card = (S ∩ A).card + (S \ A).card := by
      rw [← Finset.card_union_of_disjoint (Finset.disjoint_sdiff_inter S A).symm]
      congr 1
      ext x; simp only [Finset.mem_union, Finset.mem_inter, Finset.mem_sdiff]; tauto
    have hAX : A.card ≤ X.card := Finset.card_le_card hA
    have hUA : (S ∩ A).card ≤ A.card := Finset.card_le_card Finset.inter_subset_right
    have hVXA : (S \ A).card ≤ (X \ A).card :=
      Finset.card_le_card (Finset.sdiff_subset_sdiff hSX (le_refl A))
    have hXA : (X \ A).card = X.card - A.card := Finset.card_sdiff_of_subset hA
    rw [hcard, pow_add,
      show X.card - ((S ∩ A).card + (S \ A).card)
        = (A.card - (S ∩ A).card) + ((X \ A).card - (S \ A).card) by omega, pow_add]
    ring

/-- The family of subsets of `X` containing no member of `H`. -/
