/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 857e33a2-b300-4e10-bc08-3e5b2fcd4456

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Matrix

open Finset Matrix SimpleGraph Real

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- Laplacian matrix L = D - A -/
abbrev L (G : SimpleGraph V) : Matrix V V ℝ := G.lapMatrix ℝ

/-- Matrix PSD ordering: M ⪯ N iff N - M is PSD -/

def SelfLeverageBoundStatement (G : SimpleGraph V) : Prop :=
  ∀ (T : Finset V),
    ∑ t ∈ T, leverageScoreSet G {t} T ≤ 2 * ((T.card : ℝ) - 1)

/-
Lemma 2.4: If A, B are PSD, δ > 0, and a specific condition involving traces holds, then the barrier function of A + B at u + δ is bounded by the barrier function of A at u.
-/
/--
**LEMMA 2.4: Barrier Function Decrease**

If A, B are PSD, δ > 0, M = (u+δ)I - A, Φ_σ^u(A) < ∞, and
  Tr_σ(M^{-2}B) / (Φ_σ^u(A) - Φ_σ^{u+δ}(A)) + Tr_σ(M^{-1}B) < 1
then Φ_σ^{u+δ}(A + B) ≤ Φ_σ^u(A)
-/
