import Mathlib
/-!
# Lieb Robinson
Category: Frontier Physics
Target: Frontier.lieb_robinson
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

section Basic

variable {A : Type*} [NormedRing A] [NormedAlgebra ℝ A]

/-- The inner derivation (adjoint action) `ad H x = H * x - x * H`. -/

def ad (H : A) (x : A) : A := H * x - x * H

/-- Heisenberg time evolution generated by `H`, defined as the exponential of the
derivation `ad H`:  `tau H t a = exp (t • ad H) a = ∑' n, (tⁿ / n !) • (ad H)^[n] a`.
(For a spin system with Hamiltonian `Ĥ` one takes `H = i Ĥ`, so that `tau H t a`
is the usual Heisenberg evolved observable `e^{i t Ĥ} a e^{-i t Ĥ}`.) -/
