import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

/-!
# Lieb–Robinson bound: an effective light cone for local spin dynamics

We work in an arbitrary C\*-algebra `A` (e.g. the algebra of observables of a finite
spin system, `Matrix (Fin n) (Fin n) ℂ`).  Given a self-adjoint Hamiltonian `H : A`,
the Heisenberg dynamics is `τ_t(a) = e^{itH} a e^{-itH}`.

The base case of the Lieb–Robinson estimate is the linear-in-time bound

`‖⁅τ_t a, b⁆‖ ≤ ‖⁅a, b⁆‖ + 2 |t| ‖a‖ ‖⁅H, b⁆‖`,

which is the first step of the standard iteration producing the light cone: if `a` and
`b` are supported on disjoint regions then `⁅a, b⁆ = 0`, and only those terms of a local
Hamiltonian `H` that overlap the support of `b` contribute to `⁅H, b⁆`.  Hence the
commutator of `b` with the evolved observable can only grow at a rate set by the local
interaction strength — an effective light cone.
-/

namespace Frontier

open NormedSpace

variable {A : Type*} [CStarAlgebra A]

/-- `NormedSpace.exp` lemmas in Mathlib are phrased over `ℚ`-normed algebras; every complex
normed algebra is one by restriction of scalars. -/
noncomputable local instance normedAlgebraRatOfCStarAlgebra (A : Type*) [CStarAlgebra A] :
    NormedAlgebra ℚ A := .restrictScalars ℚ ℂ A

/-- The one-parameter unitary group `t ↦ e^{i t H}` generated by `H`. -/

lemma hasDerivAt_heisenberg (H : A) (b : A) (t : ℝ) :
    HasDerivAt (fun s : ℝ => heisenberg H s b)
      (uGroup H t * (Complex.I • ⁅H, b⁆) * uGroup H (-t)) t := by
  have h1 : HasDerivAt (fun s : ℝ => uGroup H s * b)
      (uGroup H t * (Complex.I • H) * b) t := (hasDerivAt_uGroup H t).mul_const b
  have h2 : HasDerivAt (fun s : ℝ => uGroup H (-s))
      (-(uGroup H (-t) * (Complex.I • H))) t := by
    have := (hasDerivAt_uGroup H (-t)).scomp t (hasDerivAt_neg t)
    simpa using this
  have h3 := h1.mul h2
  convert h3 using 1
  have hc : uGroup H (-t) * (Complex.I • H) = (Complex.I • H) * uGroup H (-t) :=
    commute_uGroup_gen H (-t)
  rw [Ring.lie_def, smul_sub, mul_sub, sub_mul]
  rw [mul_neg, hc]
  simp only [mul_assoc, smul_mul_assoc, mul_smul_comm]
  ring_nf
  rw [sub_eq_add_neg]

/-- Base bound: the observable `b` moves at most linearly in time, at a rate given by
`‖⁅H, b⁆‖`. -/
