import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

/-!
# Lieb–Robinson bound: an effective light cone for local spin dynamics

We work in an arbitrary C\*-algebra `A` (e.g. the algebra of observables of a finite
spin system, `Matrix (Fin n) (Fin n) ℂ`).  Given a self-adjoint Hamiltonian `H : A`,
the Heisenberg dynamics is `τ_t(a) = e^{itH} a e^{-itH}`.

The base case of the Lieb–Robinson estimate is the linear-in-time bound

`‖⁅τ_t a, b⁆‖ ≤ ‖⁅a, b⁆‖ + 2 |t| ‖a‖ ‖⁅H, b⁆‖`,

which is the first step of the standard iteration producing the light cone: if `a` and
`b` are supported on disjoint regions then `⁅a, b⁆ = 0`, and only those terms of a local
Hamiltonian `H` that overlap the support of `b` contribute to `⁅H, b⁆`.  Hence the
commutator of `b` with the evolved observable can only grow at a rate set by the local
interaction strength — an effective light cone.
-/

namespace Frontier

open NormedSpace

variable {A : Type*} [CStarAlgebra A]

/-- `NormedSpace.exp` lemmas in Mathlib are phrased over `ℚ`-normed algebras; every complex
normed algebra is one by restriction of scalars. -/
noncomputable local instance normedAlgebraRatOfCStarAlgebra (A : Type*) [CStarAlgebra A] :
    NormedAlgebra ℚ A := .restrictScalars ℚ ℂ A

/-- The one-parameter unitary group `t ↦ e^{i t H}` generated by `H`. -/

theorem lieb_robinson_local {ι : Type*} {H : A} (hH : IsSelfAdjoint H) (a b : A) (t : ℝ)
    (S N : Finset ι) (h : ι → A) (hHsum : H = ∑ z ∈ S, h z)
    (hab : ⁅a, b⁆ = 0) (hloc : ∀ z ∈ S, z ∉ N → ⁅h z, b⁆ = 0) :
    ‖⁅heisenberg H t a, b⁆‖ ≤ 4 * |t| * ‖a‖ * ‖b‖ * ∑ z ∈ S ∩ N, ‖h z‖ := by
  have hmain := lieb_robinson hH a b t
  rw [hab, norm_zero, zero_add] at hmain
  have hHb : ‖⁅H, b⁆‖ ≤ 2 * ‖b‖ * ∑ z ∈ S ∩ N, ‖h z‖ := by
    rw [hHsum]; exact norm_lie_sum_le S N h b hloc
  have hc : (0:ℝ) ≤ 2 * |t| * ‖a‖ := by positivity
  calc ‖⁅heisenberg H t a, b⁆‖ ≤ 2 * |t| * ‖a‖ * ‖⁅H, b⁆‖ := hmain
    _ ≤ 2 * |t| * ‖a‖ * (2 * ‖b‖ * ∑ z ∈ S ∩ N, ‖h z‖) := mul_le_mul_of_nonneg_left hHb hc
    _ = 4 * |t| * ‖a‖ * ‖b‖ * ∑ z ∈ S ∩ N, ‖h z‖ := by ring

/-- **Strict light cone.** If `b` commutes with `a` and with the Hamiltonian, then it
commutes with the evolved observable at all times. -/
