/-
# Lieb Robinson
Category: Frontier Physics
Target: Frontier.lieb_robinson
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

-- (Lean requires `import` to precede any module docstring, so the header above is a
-- plain block comment; the same header is repeated as a module docstring below.)

import Mathlib

/-!
# Lieb Robinson
Category: Frontier Physics
Target: Frontier.lieb_robinson
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

/-!
## Setting

We work in a unital C*-algebra `A` (the algebra of observables of a quantum spin system).
For a self-adjoint Hamiltonian `H` the Heisenberg dynamics is
`τ_t(a) = exp(i t H) * a * exp(-i t H)`.

The Lieb–Robinson bound asserts that if `a` and `b` are observables supported in
regions that are not coupled by the "free" part `H₀` of the Hamiltonian, then the
commutator `⁅τ_t(a), b⁆` stays small for small times: it is controlled by the strength
of the coupling term `V` times the elapsed time.  This is exactly the base case
(first order in `t`) of the Lieb–Robinson series which produces the exponential
light cone `e^{v|t| - d}`.
-/

namespace Frontier

open NormedSpace

variable {A : Type*} [CStarAlgebra A] [Nontrivial A]

noncomputable local instance ratAlg : NormedAlgebra ℚ A := .restrictScalars ℚ ℂ A

/-- The Heisenberg time evolution of the observable `a` generated by the Hamiltonian `H`:
`τ_t(a) = exp(i t H) * a * exp(-i t H)`. -/

theorem norm_exp_sub_exp_le {X Y : A} (hX : X ∈ skewAdjoint A) (hY : Y ∈ skewAdjoint A)
    (t : ℝ) : ‖exp (t • X) - exp (t • Y)‖ ≤ |t| * ‖X - Y‖ := by
  have hnegX : -X ∈ skewAdjoint A := neg_mem hX
  set g : ℝ → A := fun s => exp (t • X) * (exp (s • (-X)) * exp (s • Y)) with hg
  have hderiv : ∀ s : ℝ, HasDerivAt g
      (exp (t • X) * (exp (s • (-X)) * (Y - X) * exp (s • Y))) s := by
    intro s
    have h1 : HasDerivAt (fun s : ℝ => exp (s • (-X))) (exp (s • (-X)) * (-X)) s :=
      hasDerivAt_exp_smul_const (𝕂 := ℝ) (-X) s
    have h2 : HasDerivAt (fun s : ℝ => exp (s • Y)) (Y * exp (s • Y)) s :=
      hasDerivAt_exp_smul_const' (𝕂 := ℝ) Y s
    have h3 := (h1.mul h2).const_mul (exp (t • X))
    convert h3 using 1
    noncomm_ring
  have key : ‖g t - g 0‖ ≤ ‖X - Y‖ * ‖t - 0‖ := by
    apply Convex.norm_image_sub_le_of_norm_hasDerivWithin_le
      (fun s _ => (hderiv s).hasDerivWithinAt) _ (convex_uIcc 0 t)
      Set.left_mem_uIcc Set.right_mem_uIcc
    intro s _
    have e1 : ‖exp (t • X)‖ = 1 := norm_exp_of_mem_skewAdjoint (smul_mem_skewAdjoint hX t)
    have e2 : ‖exp (s • (-X))‖ = 1 := norm_exp_of_mem_skewAdjoint (smul_mem_skewAdjoint hnegX s)
    have e3 : ‖exp (s • Y)‖ = 1 := norm_exp_of_mem_skewAdjoint (smul_mem_skewAdjoint hY s)
    calc ‖exp (t • X) * (exp (s • (-X)) * (Y - X) * exp (s • Y))‖
        ≤ ‖exp (t • X)‖ * ‖exp (s • (-X)) * (Y - X) * exp (s • Y)‖ := norm_mul_le _ _
      _ ≤ ‖exp (t • X)‖ * (‖exp (s • (-X)) * (Y - X)‖ * ‖exp (s • Y)‖) := by
          gcongr; exact norm_mul_le _ _
      _ ≤ ‖exp (t • X)‖ * ((‖exp (s • (-X))‖ * ‖Y - X‖) * ‖exp (s • Y)‖) := by
          gcongr; exact norm_mul_le _ _
      _ = ‖Y - X‖ := by rw [e1, e2, e3]; ring
      _ = ‖X - Y‖ := norm_sub_rev _ _
  have hgt : g t = exp (t • Y) := by
    have hinv : exp (t • X) * exp (t • (-X)) = 1 := by
      rw [← exp_add_of_commute (by simp [Commute, SemiconjBy])]
      simp
    rw [hg]
    simp only [← mul_assoc, hinv, one_mul]
  have hg0 : g 0 = exp (t • X) := by simp [hg]
  rw [hgt, hg0] at key
  calc ‖exp (t • X) - exp (t • Y)‖ = ‖exp (t • Y) - exp (t • X)‖ := norm_sub_rev _ _
    _ ≤ ‖X - Y‖ * |t| := by simpa [Real.norm_eq_abs] using key
    _ = |t| * ‖X - Y‖ := mul_comm _ _

omit [Nontrivial A] in
/-- The commutator of an observable with `b` is bounded by `2 ‖x‖ ‖b‖`. -/
