import Mathlib
/-!
# Lieb Robinson
Category: Frontier Physics
Target: Frontier.lieb_robinson
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

section Basic

variable {A : Type*} [NormedRing A] [NormedAlgebra ℝ A]

/-- The inner derivation (adjoint action) `ad H x = H * x - x * H`. -/

lemma tsum_exp_tail_le {x : ℝ} (hx : 0 ≤ x) (d : ℕ) :
    ∑' k : ℕ, x ^ (k + d) / ((k + d)! : ℝ) ≤ (x ^ d / (d ! : ℝ)) * Real.exp x := by
  have hbase : Summable (fun n : ℕ => x ^ n / (n ! : ℝ)) := Real.summable_pow_div_factorial x
  have hL : Summable (fun k : ℕ => x ^ (k + d) / ((k + d)! : ℝ)) :=
    (summable_nat_add_iff d).2 hbase
  have hR : Summable (fun k : ℕ => (x ^ d / (d ! : ℝ)) * (x ^ k / (k ! : ℝ))) :=
    hbase.mul_left _
  have hterm : ∀ k : ℕ,
      x ^ (k + d) / ((k + d)! : ℝ) ≤ (x ^ d / (d ! : ℝ)) * (x ^ k / (k ! : ℝ)) := by
    intro k
    have hfac : (k ! : ℝ) * (d ! : ℝ) ≤ ((k + d)! : ℝ) := by
      have h2 : k ! * d ! ≤ (k + d)! :=
        Nat.le_of_dvd (Nat.factorial_pos _) (Nat.factorial_mul_factorial_dvd_factorial_add k d)
      exact_mod_cast h2
    have hpos : (0:ℝ) < (k ! : ℝ) * (d ! : ℝ) := by positivity
    have hle : x ^ (k + d) / ((k + d)! : ℝ) ≤ x ^ (k + d) / ((k ! : ℝ) * (d ! : ℝ)) :=
      div_le_div_of_nonneg_left (by positivity) hpos hfac
    refine hle.trans_eq ?_
    rw [pow_add]
    field_simp
  calc ∑' k : ℕ, x ^ (k + d) / ((k + d)! : ℝ)
      ≤ ∑' k : ℕ, (x ^ d / (d ! : ℝ)) * (x ^ k / (k ! : ℝ)) := hL.tsum_le_tsum hterm hR
    _ = (x ^ d / (d ! : ℝ)) * Real.exp x := by
        rw [hbase.tsum_mul_left, Real.exp_eq_exp_ℝ, NormedSpace.exp_eq_tsum_div]

section Locality

variable {A : Type*} [NormedRing A] [NormedAlgebra ℝ A]

variable (loc : ℤ → ℤ → A → Prop)

omit [NormedAlgebra ℝ A] in
/-- One step of support growth: the derivation `ad H` generated by a nearest–neighbour
Hamiltonian enlarges the support of a local observable by one site on each side. -/
