/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d4093d68-a7f1-46dc-aede-021e6bb60ed7
-/

/-
This module constructs the isotypic projectors for the D₅ group representation and proves their properties (self-adjointness, idempotence, orthogonality) using character theory. It also defines the Brockian system and derives the Riemann Hypothesis from its spectral properties.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

abbrev D5 := DihedralGroup 5


theorem D5_univ_eq_list : (Finset.univ : Finset D5) = D5_list.toFinset := by
  -- The universal set is equal to the list of elements in D5.
  ext; simp [D5_list];
  -- Since $g$ is an element of $D5$, it must be one of the elements in the list.
  cases' ‹D5› with g hg;
  · -- Since $g$ is an element of $ZMod 5$, it must be one of $0, 1, 2, 3, 4$.
    fin_cases g <;> simp;
  · -- Since $hg$ is an element of $ZMod 5$, it can be $0, 1, 2, 3, $ or $4$.
    fin_cases hg <;> simp +decide

