/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: c179afb9-ac18-4ec2-a2f9-ccd85f25f3d9

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.

-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped ComplexConjugate

open Complex

abbrev D5 : Type := DihedralGroup 5

instance : Fintype D5 := inferInstance

instance : Group D5 := inferInstance


theorem isotypicProjector_idempotent (rep : D5UnitaryRep H) (idx : D5IrrepIndex) :
  (isotypicProjector rep idx) * (isotypicProjector rep idx) = isotypicProjector rep idx := by
    -- The isotypic projector is defined as 0 if the index is not .golden, and 1 if it is.
    simp [isotypicProjector] at *;
    -- If the index is not golden, then the projector is 0, which is trivially idempotent.
    intro h_not_golden h_golden
    exfalso
    exact h_not_golden h_golden

/-- **CRITICAL**: The projector is self-adjoint (P* = P). -/
