/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d4093d68-a7f1-46dc-aede-021e6bb60ed7
-/

/-
This module constructs the isotypic projectors for the D₅ group representation and proves their properties (self-adjointness, idempotence, orthogonality) using character theory. It also defines the Brockian system and derives the Riemann Hypothesis from its spectral properties.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

abbrev D5 := DihedralGroup 5


theorem P_golden_idempotent (ρ : UnitaryRep H) :
    P_golden ρ * P_golden ρ = P_golden ρ := by
      -- By definition of $P_golden$, we have $P_golden ρ = (2 / 10 : ℂ) • ∑ g : D5, (star (χ_of_elem .golden g)) • (ρ g)$.
      have hP_golden : P_golden ρ = (2 / 10 : ℂ) • ∑ g : D5, (star (χ_of_elem .golden g)) • (ρ.toCLM g) := by
        exact?;
      -- By definition of $P_golden$, we can expand $P_golden ρ * P_golden ρ$.
      have h_expand : P_golden ρ * P_golden ρ = (4 / 100 : ℂ) • ∑ g : D5, ∑ h : D5, (star (χ_of_elem .golden g) * star (χ_of_elem .golden h)) • (ρ.toCLM (g * h)) := by
        rw [hP_golden];
        ext; simp +decide [ Finset.mul_sum _ _ _, Finset.sum_mul, mul_assoc, mul_left_comm, smul_smul ] ; ring;
        simp +decide [ Finset.smul_sum, smul_smul, mul_assoc, mul_comm, mul_left_comm, Finset.sum_mul ] ; ring!;
        congr! 3;
        rename_i g hg h hh; exact (by
        exact congr_arg ( fun f => f ‹_› ) ( ρ.map_mul' g h ) ▸ rfl);
      -- By definition of $P_golden$, we can rewrite the double sum as a single sum.
      have h_double_sum : ∑ g : D5, ∑ h : D5, (star (χ_of_elem .golden g) * star (χ_of_elem .golden h)) • (ρ.toCLM (g * h)) = ∑ k : D5, (∑ g : D5, star (χ_of_elem .golden g) * χ_of_elem .golden (g⁻¹ * k)) • (ρ.toCLM k) := by
        have h_double_sum : ∀ g : D5, ∑ h : D5, (star (χ_of_elem .golden g) * star (χ_of_elem .golden h)) • (ρ.toCLM (g * h)) = ∑ k : D5, (star (χ_of_elem .golden g) * star (χ_of_elem .golden (g⁻¹ * k))) • (ρ.toCLM k) := by
          intro g
          apply Finset.sum_bij (fun h _ => g * h);
          · simp;
          · simp +decide;
          · exact fun b _ => ⟨ g⁻¹ * b, Finset.mem_univ _, by simp +decide ⟩;
          · simp +decide [ mul_assoc ];
        simp +decide only [h_double_sum, Finset.sum_smul];
        rw [ Finset.sum_comm ];
        -- Since the character values are real, their complex conjugates are equal to themselves.
        have h_real : ∀ g : D5, star (χ_of_elem .golden g) = χ_of_elem .golden g := by
          exact?;
        aesop;
      -- By definition of $P_golden$, we can simplify the inner sum.
      have h_inner_sum : ∀ k : D5, ∑ g : D5, star (χ_of_elem .golden g) * χ_of_elem .golden (g⁻¹ * k) = 5 * star (χ_of_elem .golden k) := by
        -- By definition of $P_golden$, we can simplify the inner sum using the convolution property.
        have h_inner_sum : ∀ k : D5, ∑ g : D5, star (χ_of_elem .golden g) * χ_of_elem .golden (g⁻¹ * k) = star (∑ g : D5, χ_of_elem .golden g * χ_of_elem .golden (g⁻¹ * k)) := by
          simp +decide [ Complex.conj_ofReal, Complex.conj_I ];
          intro k; congr; ext x; rw [ Complex.ext_iff ] ; simp +decide [ χ_golden_real ] ;
          have := χ_golden_real ( conjClass x ) ; have := χ_golden_real ( conjClass ( x⁻¹ * k ) ) ; simp_all +decide [ Complex.ext_iff ] ;
          unfold χ_of_elem; aesop;
        intro k
        rw [h_inner_sum];
        rw [ golden_convolution ];
        norm_num [ Complex.ext_iff ];
      simp_all +decide [ Finset.mul_sum _ _ _, Finset.sum_mul ];
      norm_num [ Finset.smul_sum, MulAction.mul_smul ];
      norm_num [ ← smul_assoc ];
      exact Finset.sum_congr rfl fun _ _ => by ring;

