/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 9e0f623f-c2aa-4007-b021-1d2701b47405

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real ComplexConjugate TensorProduct
open Complex Finset MeasureTheory

inductive BZFC.BrockRay
  | E  -- Ray E: 0 mod 5
  | A  -- Ray A: 1 mod 5
  | B  -- Ray B: 2 mod 5
  | C  -- Ray C: 3 mod 5
  | D  -- Ray D: 4 mod 5
  deriving DecidableEq, Repr


def BrockianSystem.IsPrime (sys : BrockianSystem) (σ : sys.SB) : Prop := σ ∈ sys.prime

class B12 (sys : BrockianSystem) : Prop where
  rank_pos : 1 ≤ sys.rank

class B3 (sys : BrockianSystem) : Prop where
  dim_ge_rank : sys.rank ≤ sys.dimH0

class B4 (sys : BrockianSystem) : Prop where
  dim_eq_one : sys.dimH0 = 1

class B0 (sys : BrockianSystem) : Prop where
  unitIso_of_rank_one : sys.rank = 1 → sys.unitIso
  equiv_of_unitIso : sys.unitIso → sys.transformEquiv
  multiplicity_one_of_unitIso : sys.unitIso → 
    ∀ σ ∈ sys.prime, sys.multiplicity σ = 1

