import Mathlib

/-!
# Ratner
Category: Frontier Math
Target: Math2.ratner
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Math2

/-- The homogeneous space `X = G / Γ` for `G = ℝ²` and the lattice `Γ = ℤ²`, i.e. the
two-dimensional torus. -/
abbrev Torus2 : Type := AddCircle (1 : ℝ) × AddCircle (1 : ℝ)

/-- The projection `G = ℝ² → X = ℝ²/ℤ²`. -/

lemma irrational_ratio (v : ℝ × ℝ)
    (h : ∀ a b : ℤ, (a : ℝ) * v.1 + (b : ℝ) * v.2 = 0 → a = 0 ∧ b = 0) :
    v.1 ≠ 0 ∧ Irrational (v.2 / v.1) := by
  have hv1 : v.1 ≠ 0 := by
    intro h0
    have h1 := h 1 0 (by rw [h0]; push_cast; ring)
    simpa using h1.1
  refine ⟨hv1, ?_⟩
  rintro ⟨q, hq⟩
  have hden : ((q.den : ℝ)) ≠ 0 := by
    exact_mod_cast (Nat.cast_ne_zero (R := ℝ)).mpr q.den_nz
  have hv2 : v.2 = (q : ℝ) * v.1 := by rw [hq, div_mul_cancel₀ _ hv1]
  have hqval : (q : ℝ) * q.den = q.num := by rw [Rat.cast_def]; field_simp
  have hrel : ((q.num : ℤ) : ℝ) * v.1 + ((-(q.den : ℤ) : ℤ) : ℝ) * v.2 = 0 := by
    rw [hv2]; push_cast; rw [← hqval]; ring
  have hcon := (h q.num (-(q.den : ℤ)) hrel).2
  simp at hcon

/-- The subgroup of `ℝ²` generated by the line `ℝ v` and the lattice `ℤ²`. -/
