/-
# Ratner
Category: Frontier Math
Target: Math2.ratner
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

/-!
# Ratner
Category: Frontier Math
Target: Math2.ratner
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)

(The header above is repeated as a plain comment at the very top of the file, since Lean 4
requires `import` commands to precede every other command, including module docstrings.)

## Ratner's orbit-closure theorem, commutative case

Ratner's orbit-closure theorem states that if `U` is a subgroup of a Lie group `G` generated by
one-parameter unipotent subgroups, `Γ ≤ G` is a lattice and `x ∈ G ⧸ Γ`, then the closure of the
orbit `U • x` is `L • x` for some closed subgroup `L` with `U ≤ L`, and this orbit `L • x` is
closed (it carries a finite `L`-invariant measure, which is the associated measure-classification
statement).

Here we formalize and prove the statement in the commutative case, i.e. for an arbitrary
commutative topological group `G` and an arbitrary subgroup `Γ` (no lattice or Lie hypotheses are
needed).  In a commutative group every element is unipotent in the relevant sense, so the
hypothesis on `U` is vacuous and one may take `U` to be *any* subgroup.  The conclusion is the
full homogeneity statement: the orbit closure is the orbit of a closed subgroup `L` containing
both `U` and `Γ`, and that orbit is closed.
-/

open Pointwise

namespace Math2

/-- **Ratner's orbit-closure theorem (commutative case).**

Let `G` be a commutative topological group, `Γ` a subgroup of `G`, `U` a subgroup of `G` (in a
commutative group every one-parameter subgroup is unipotent, so no further hypothesis on `U` is
required), and `x` a point of the homogeneous space `G ⧸ Γ`.

Then there is a *closed* subgroup `L ≤ G` containing `U` (and `Γ`) such that the closure of the
orbit `U • x` is exactly the orbit `L • x`, and this orbit is closed in `G ⧸ Γ`.  In other words,
orbit closures for the translation action are homogeneous. -/
@[to_additive ratner_additive]

theorem ratner_irrational_rotation {α : ℝ} (h : Irrational α) (x : AddCircle (1 : ℝ)) :
    closure ((fun g : ℝ => g +ᵥ x) '' (AddSubgroup.zmultiples α : Set ℝ)) = Set.univ := by
  have hdense : DenseRange (fun n : ℤ => n • (α : AddCircle (1 : ℝ))) :=
    AddCircle.denseRange_zsmul_coe_iff.2 (by simpa using h)
  have hshift : DenseRange (fun y : AddCircle (1 : ℝ) => y + x) :=
    (Equiv.addRight x).surjective.denseRange
  have hdense2 : Dense (Set.range (fun n : ℤ => n • (α : AddCircle (1 : ℝ)) + x)) :=
    hshift.comp hdense (continuous_add_right x)
  have hsub : Set.range (fun n : ℤ => n • (α : AddCircle (1 : ℝ)) + x)
      ⊆ (fun g : ℝ => g +ᵥ x) '' (AddSubgroup.zmultiples α : Set ℝ) := by
    rintro y ⟨n, rfl⟩
    refine ⟨n • α, ⟨n, rfl⟩, ?_⟩
    show ((n • α : ℝ) : AddCircle (1 : ℝ)) + x = _
    congr 1
  exact (hdense2.mono hsub).closure_eq

end Math2

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

