import Mathlib
/-!
# Margulis Superrigidity
Category: Frontier Abel
Target: Frontier.margulis_superrigidity
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

/-
NOTE ON THE FILE HEADER.  Lean 4 requires `import` to be the very first command of a
module, so the requested `/-! ... -/` module docstring is placed immediately after the
single `import Mathlib` line rather than before it; its text is otherwise verbatim.
-/

open scoped BigOperators

namespace Frontier

/-! ## The superrigidity extension property

Margulis superrigidity says, for `G` a semisimple Lie group of real rank `≥ 2`, `Γ ≤ G` an
irreducible lattice and `π : Γ → H` a homomorphism into a simple algebraic group with
unbounded Zariski-dense image, that `π` is the restriction of a *continuous* homomorphism
`G → H`.  The predicate below isolates the conclusion of that theorem: a homomorphism
defined on the lattice extends to a continuous homomorphism of the ambient group.
-/

/-- The conclusion of a superrigidity statement, in additive notation: a homomorphism `π`
defined on a lattice `L` (mapped into the ambient group `G` by the inclusion `ι`) is the
restriction along `ι` of a continuous homomorphism `G → H`. -/

theorem extendsToContinuousHom_comp {L G H K : Type*} [AddGroup L] [AddGroup G] [AddGroup H]
    [AddGroup K] [TopologicalSpace G] [TopologicalSpace H] [TopologicalSpace K]
    {ι : L →+ G} {π : L →+ H} (h : ExtendsToContinuousHom ι π) (φ : H →+ K)
    (hφ : Continuous φ) : ExtendsToContinuousHom ι (φ.comp π) := by
  obtain ⟨ρ, hρ, hext⟩ := h
  exact ⟨φ.comp ρ, hφ.comp hρ, fun v => by simp [hext v]⟩

end Frontier

import RequestProject.MargulisSuperrigidity

/-!
# `SL(n, ℤ)` is generated by elementary matrices

This file proves that the special linear group over `ℤ` is generated by the elementary
(transvection) matrices `1 + a·Eᵢⱼ`, by formalizing Gaussian elimination over the Euclidean
domain `ℤ`.  Combined with the commutator identity of `RequestProject.MargulisSuperrigidity`
this shows that `SL(n, ℤ)` is perfect for `n ≥ 3`, which makes the abelian-target case of
Margulis superrigidity for the lattice `SL(n, ℤ) ⊂ SL(n, ℝ)` unconditional.
-/

open Matrix

namespace Frontier

variable {n : ℕ}

/-- The subgroup of `SL(n, ℤ)` generated by the elementary matrices. -/
abbrev ESub (n : ℕ) : Subgroup (Matrix.SpecialLinearGroup (Fin n) ℤ) :=
  Subgroup.closure (elemSet n)

