import Mathlib
/-!
# Margulis Superrigidity
Category: Frontier Abel
Target: Frontier.margulis_superrigidity
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

/-
NOTE ON THE FILE HEADER.  Lean 4 requires `import` to be the very first command of a
module, so the requested `/-! ... -/` module docstring is placed immediately after the
single `import Mathlib` line rather than before it; its text is otherwise verbatim.
-/

open scoped BigOperators

namespace Frontier

/-! ## The superrigidity extension property

Margulis superrigidity says, for `G` a semisimple Lie group of real rank `≥ 2`, `Γ ≤ G` an
irreducible lattice and `π : Γ → H` a homomorphism into a simple algebraic group with
unbounded Zariski-dense image, that `π` is the restriction of a *continuous* homomorphism
`G → H`.  The predicate below isolates the conclusion of that theorem: a homomorphism
defined on the lattice extends to a continuous homomorphism of the ambient group.
-/

/-- The conclusion of a superrigidity statement, in additive notation: a homomorphism `π`
defined on a lattice `L` (mapped into the ambient group `G` by the inclusion `ι`) is the
restriction along `ι` of a continuous homomorphism `G → H`. -/

lemma mem_ESub_of_partialId (k : ℕ) : ∀ m : ℕ, n ≤ m + k →
    ∀ A : Matrix.SpecialLinearGroup (Fin n) ℤ, PartialId m (A : Matrix (Fin n) (Fin n) ℤ) →
      A ∈ ESub n := by
  induction k with
  | zero =>
      intro m hmk A hA
      rw [eq_one_of_partialId_ge A (by omega) hA]
      exact one_mem _
  | succ k ih =>
      intro m hmk A hA
      by_cases hmn : n ≤ m
      · rw [eq_one_of_partialId_ge A hmn hA]
        exact one_mem _
      push_neg at hmn
      by_cases hm1 : m + 1 = n
      · rw [eq_one_of_partialId_succ A hm1 hA]
        exact one_mem _
      have hm2 : m + 1 < n := by omega
      obtain ⟨g, hg, hgp, hgcol⟩ :=
        exists_reduce_column hmn hm2 (colMeasure m hmn (A : Matrix (Fin n) (Fin n) ℤ)) A hA le_rfl
      obtain ⟨h, hh, hhp, hhcol, hhrow⟩ := exists_clear_row hmn
        (Finset.univ.filter fun j : Fin n => m < (j : ℕ)) (by simp) (g * A) hgp hgcol
      have hnew : PartialId (m + 1)
          ((g * A * h : Matrix.SpecialLinearGroup (Fin n) ℤ) : Matrix (Fin n) (Fin n) ℤ) := by
        intro i j hij
        by_cases hi : (i : ℕ) < m
        · exact hhp i j (Or.inl hi)
        by_cases hj : (j : ℕ) < m
        · exact hhp i j (Or.inr hj)
        push_neg at hi hj
        have hmval : ((⟨m, hmn⟩ : Fin n) : ℕ) = m := rfl
        by_cases hjc : j = (⟨m, hmn⟩ : Fin n)
        · rw [hjc, hhcol i]
        · have hjm : m < (j : ℕ) := by
            rcases lt_or_eq_of_le hj with hlt | heq
            · exact hlt
            · exact absurd (Fin.ext (by rw [hmval]; omega)) hjc
          have hic : i = (⟨m, hmn⟩ : Fin n) := by
            rcases hij with hlt | hlt
            · exact Fin.ext (by rw [hmval]; omega)
            · exact absurd (Fin.ext (by rw [hmval]; omega) : j = (⟨m, hmn⟩ : Fin n)) hjc
          rw [hic, hhrow j (by simp [hjm])]
          have : (⟨m, hmn⟩ : Fin n) ≠ j := fun hcj => hjc hcj.symm
          simp [this]
      have hmem : g * A * h ∈ ESub n := ih (m + 1) (by omega) _ hnew
      have hAeq : A = g⁻¹ * (g * A * h) * h⁻¹ := by group
      rw [hAeq]
      exact mul_mem (mul_mem (inv_mem hg) hmem) (inv_mem hh)

/-- **`SL(n, ℤ)` is generated by elementary matrices.** -/
