import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

/-!
# A special case of the Baker–Campbell–Hausdorff formula

If the commutator `C = A * B - B * A` commutes with both `A` and `B` (i.e. `[A, B]` is central
for the subalgebra generated by `A` and `B`), then in a Banach algebra

`exp A * exp B = exp (A + B + (1/2) • (A * B - B * A))`.
-/

namespace QPhys

open NormedSpace

section BanachAlgebra

variable {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸] [CompleteSpace 𝔸]

/-- The scalar tower `ℚ → ℝ → 𝔸` makes any real Banach algebra a rational one; this is what
Mathlib's exponential API is phrased over. -/
noncomputable local instance ratNormedAlgebra : NormedAlgebra ℚ 𝔸 :=
  NormedAlgebra.restrictScalars ℚ ℝ 𝔸

/-- `exp (t • X)` and `exp (-t • X)` are mutually inverse. -/

lemma exp_conj_eq (A B : 𝔸) (hCB : Commute (A * B - B * A) B) (t : ℝ) :
    exp (t • B) * A * exp ((-t) • B) = A - t • (A * B - B * A) := by
  have key : ∀ s : ℝ,
      HasDerivAt (fun r : ℝ => exp (r • B) * A * exp ((-r) • B) + r • (A * B - B * A)) 0 s := by
    intro s
    have hu : HasDerivAt (fun r : ℝ => exp (r • B)) (B * exp (s • B)) s :=
      hasDerivAt_exp_smul_const' B s
    have hneg : HasDerivAt (fun r : ℝ => -r) (-1 : ℝ) s := by
      simpa using (hasDerivAt_id s).neg
    have hw : HasDerivAt (fun r : ℝ => exp ((-r) • B)) ((-1 : ℝ) • (exp ((-s) • B) * B)) s :=
      (hasDerivAt_exp_smul_const B (-s)).scomp s hneg
    have hsm : HasDerivAt (fun r : ℝ => r • (A * B - B * A)) (A * B - B * A) s := by
      simpa using (hasDerivAt_id s).smul_const (A * B - B * A)
    have hprod := ((hu.mul_const A).mul hw).add hsm
    convert hprod using 1
    symm
    have h1 : B * exp (s • B) = exp (s • B) * B := ((Commute.refl B).smul_right s).exp_right
    have h2 : exp ((-s) • B) * B = B * exp ((-s) • B) :=
      (((Commute.refl B).smul_right (-s)).exp_right).symm.eq
    have h3 : (A * B - B * A) * exp (s • B) = exp (s • B) * (A * B - B * A) :=
      (hCB.smul_right s).exp_right
    have h4 : exp (s • B) * exp ((-s) • B) = 1 := exp_smul_mul_exp_neg_smul B s
    rw [neg_one_smul, h1, h2]
    calc exp (s • B) * B * A * exp ((-s) • B)
          + exp (s • B) * A * -(B * exp ((-s) • B)) + (A * B - B * A)
        = -((A * B - B * A) * exp (s • B) * exp ((-s) • B)) + (A * B - B * A) := by
          rw [h3]; noncomm_ring
      _ = 0 := by rw [mul_assoc, h4]; noncomm_ring
  have hconst := is_const_of_deriv_eq_zero (f := fun r : ℝ =>
      exp (r • B) * A * exp ((-r) • B) + r • (A * B - B * A))
    (fun r => (key r).differentiableAt) (fun r => (key r).deriv) t 0
  simp only [zero_smul, neg_zero, exp_zero, one_mul, mul_one, add_zero] at hconst
  rw [eq_sub_iff_add_eq]
  exact hconst

/-- Moving `A` through `exp (t • B)` produces the shift `A ↦ A + t • [A, B]`. -/
