import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

/-!
# A special case of the Baker–Campbell–Hausdorff formula

If the commutator `C = A * B - B * A` commutes with both `A` and `B` (i.e. `[A, B]` is central
for the subalgebra generated by `A` and `B`), then in a Banach algebra

`exp A * exp B = exp (A + B + (1/2) • (A * B - B * A))`.
-/

namespace QPhys

open NormedSpace

section BanachAlgebra

variable {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸] [CompleteSpace 𝔸]

/-- The scalar tower `ℚ → ℝ → 𝔸` makes any real Banach algebra a rational one; this is what
Mathlib's exponential API is phrased over. -/
noncomputable local instance ratNormedAlgebra : NormedAlgebra ℚ 𝔸 :=
  NormedAlgebra.restrictScalars ℚ ℝ 𝔸

/-- `exp (t • X)` and `exp (-t • X)` are mutually inverse. -/

lemma exp_smul_mul_exp_neg_smul (X : 𝔸) (t : ℝ) : exp (t • X) * exp ((-t) • X) = 1 := by
  rw [← exp_add_of_commute (((Commute.refl X).smul_left t).smul_right (-t))]
  simp

/-- If the commutator `[A, B]` commutes with `B`, then conjugating `A` by `exp (t • B)`
shifts it by `-t • [A, B]`. -/
