/-
# Noether Conservation
Category: Frontier Physics
Target: Frontier.noether_conservation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

namespace Frontier

/-- Expansion of a continuous linear functional on `ℝ × ℝ` in the standard basis. -/

lemma dL_apply_generator_eq_zero
    (L : ℝ × ℝ → ℝ) (dL : ℝ × ℝ → (ℝ × ℝ →L[ℝ] ℝ)) (X X' : ℝ → ℝ)
    (hL : ∀ z, HasFDerivAt L (dL z) z)
    (hinv : ∀ z : ℝ × ℝ,
      HasDerivAt (fun e : ℝ => L (z.1 + e * X z.1, z.2 + e * (X' z.1 * z.2))) 0 0)
    (z : ℝ × ℝ) : dL z (X z.1, X' z.1 * z.2) = 0 := by
  set w : ℝ × ℝ := (X z.1, X' z.1 * z.2) with hw
  have hc : HasDerivAt (fun e : ℝ => (z.1 + e * X z.1, z.2 + e * (X' z.1 * z.2))) w 0 := by
    have h1 : HasDerivAt (fun e : ℝ => z.1 + e * X z.1) (X z.1) 0 := by
      simpa using ((hasDerivAt_id (0 : ℝ)).mul_const (X z.1)).const_add z.1
    have h2 : HasDerivAt (fun e : ℝ => z.2 + e * (X' z.1 * z.2)) (X' z.1 * z.2) 0 := by
      simpa using ((hasDerivAt_id (0 : ℝ)).mul_const (X' z.1 * z.2)).const_add z.2
    exact h1.prodMk h2
  have hcomp : HasDerivAt
      (fun e : ℝ => L (z.1 + e * X z.1, z.2 + e * (X' z.1 * z.2))) (dL z w) 0 := by
    have := (hL ((fun e : ℝ => (z.1 + e * X z.1, z.2 + e * (X' z.1 * z.2))) 0)).comp_hasDerivAt 0 hc
    simpa using this
  exact hcomp.unique (hinv z)

/-- **Noether's theorem, one-dimensional case.**

For a Lagrangian `L : ℝ × ℝ → ℝ` (arguments: position and velocity) with derivative `dL`,
a path `q` with velocity `v`, and a smooth symmetry generator `X` (with derivative `X'`):

* `hEL` is the Euler–Lagrange equation: the time derivative of the conjugate momentum
  `p t = ∂L/∂v (q t, v t) = dL (q t, v t) (0,1)` equals `∂L/∂q (q t, v t) = dL (q t, v t) (1,0)`;
* `hinv` says the Lagrangian is invariant to first order under the flow generated by
  `x ↦ X x` on positions and its lift `u ↦ X' x * u` on velocities.

Then the Noether current `J t = p t * X (q t)` is conserved. -/
