/-
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Chem

open MulAction

-- The action of the symmetry group `G` of a molecular skeleton `S` on the set of
-- substitution patterns `S → C` (assignments of substituents from `C` to the sites of `S`),
-- given by `(g • F) s = F (g⁻¹ • s)`.
attribute [local instance] arrowAction

variable {G S C : Type*} [Group G] [MulAction G S]

/-- The number of cycles of the skeleton symmetry `g` acting on the site set `S`,
i.e. the number of orbits of the cyclic group generated by `g`. -/

theorem cycleCount_translation {A : Type*} [AddCommGroup A] (k : A) :
    cycleCount A (Multiplicative.ofAdd k) = (AddSubgroup.zmultiples k).index := by
  rw [cycleCount, AddSubgroup.index_eq_card]
  refine Nat.card_congr (Quotient.congr (Equiv.refl A) ?_)
  intro a b
  simp only [Equiv.refl_apply, QuotientAddGroup.leftRel_apply, MulAction.orbitRel_apply,
    MulAction.mem_orbit_iff, AddSubgroup.mem_zmultiples_iff]
  constructor
  · rintro ⟨⟨m, z, rfl⟩, hm⟩
    have hm' : (Multiplicative.ofAdd k) ^ z • b = a := hm
    rw [← ofAdd_zsmul] at hm'
    have h2 : z • k + b = a := hm'
    exact ⟨-z, by rw [neg_zsmul, ← h2]; abel⟩
  · rintro ⟨z, hz⟩
    refine ⟨⟨(Multiplicative.ofAdd k) ^ (-z), ⟨-z, rfl⟩⟩, ?_⟩
    show (Multiplicative.ofAdd k) ^ (-z) • b = a
    rw [← ofAdd_zsmul]
    show (-z) • k + b = a
    rw [neg_zsmul, hz]
    abel

/-- The subgroup of `ZMod n` generated by `k` has index `gcd n k`. -/
