/-
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Chem

open MulAction

-- The action of the symmetry group `G` of a molecular skeleton `S` on the set of
-- substitution patterns `S → C` (assignments of substituents from `C` to the sites of `S`),
-- given by `(g • F) s = F (g⁻¹ • s)`.
attribute [local instance] arrowAction

variable {G S C : Type*} [Group G] [MulAction G S]

/-- The number of cycles of the skeleton symmetry `g` acting on the site set `S`,
i.e. the number of orbits of the cyclic group generated by `g`. -/

theorem cycleCount_eq_card_image [Fintype S] [DecidableEq S] (g : G) (m : ℕ) (hm : 0 < m)
    (hgm : g ^ m = 1) :
    cycleCount S g
      = (Finset.image (fun s : S => Finset.image (fun i : Fin m => g ^ (i : ℕ) • s) Finset.univ)
          Finset.univ).card := by
  set f : S → Finset S :=
    fun s => Finset.image (fun i : Fin m => g ^ (i : ℕ) • s) Finset.univ with hf
  have hmem : ∀ (s x : S), x ∈ f s ↔ x ∈ orbit (Subgroup.zpowers g) s := by
    intro s x
    constructor
    · intro hx
      rw [hf] at hx
      simp only [Finset.mem_image, Finset.mem_univ, true_and] at hx
      obtain ⟨i, rfl⟩ := hx
      exact ⟨⟨g ^ (i : ℕ), ⟨(i : ℕ), by simp⟩⟩, rfl⟩
    · rintro ⟨⟨y, z, rfl⟩, hy⟩
      have hyx : g ^ z • s = x := hy
      rw [zpow_eq_pow_toNat_emod hm hgm z] at hyx
      have hlt : (z % m).toNat < m := by
        have h0 : 0 ≤ z % m := Int.emod_nonneg z (by exact_mod_cast hm.ne')
        have h1 : z % m < m := Int.emod_lt_of_pos z (by exact_mod_cast hm)
        omega
      rw [hf]
      simp only [Finset.mem_image, Finset.mem_univ, true_and]
      exact ⟨⟨(z % m).toNat, hlt⟩, hyx⟩
  have hfeq : ∀ s t : S, f s = f t ↔ orbitRel (Subgroup.zpowers g) S s t := by
    intro s t
    constructor
    · intro h
      have hs : s ∈ f s := by rw [hmem]; exact mem_orbit_self s
      rw [h, hmem] at hs
      exact hs
    · intro h
      have horb : orbit (Subgroup.zpowers g) s = orbit (Subgroup.zpowers g) t := by
        rw [orbit_eq_iff]; exact h
      ext x
      rw [hmem, hmem, horb]
  have hwd : ∀ s t : S, orbitRel (Subgroup.zpowers g) S s t → f s = f t := fun s t h =>
    (hfeq s t).2 h
  rw [cycleCount]
  have hcard : Nat.card (orbitRel.Quotient (Subgroup.zpowers g) S)
      = Nat.card {x // x ∈ Finset.image f Finset.univ} := by
    refine Nat.card_congr (Equiv.ofBijective (fun q => ⟨Quotient.liftOn q f hwd, ?_⟩) ⟨?_, ?_⟩)
    · induction q using Quotient.inductionOn with
      | h s => exact Finset.mem_image_of_mem f (Finset.mem_univ s)
    · intro q1 q2 h
      induction q1 using Quotient.inductionOn with
      | h s =>
        induction q2 using Quotient.inductionOn with
        | h t =>
          have hst : f s = f t := congrArg Subtype.val h
          exact Quotient.sound ((hfeq s t).1 hst)
    · rintro ⟨x, hx⟩
      simp only [Finset.mem_image, Finset.mem_univ, true_and] at hx
      obtain ⟨s, rfl⟩ := hx
      exact ⟨Quotient.mk _ s, rfl⟩
  rw [hcard, Nat.card_eq_fintype_card, Fintype.card_coe]

end Computation

section DihedralSkeleton

/-- The full symmetry group of a regular `n`-gon acting on its `n` vertices `ZMod n`:
the rotation `r i` sends the vertex `x` to `x + i`, the reflection `sr i` sends `x` to `-i - x`. -/
instance dihedralSMul (n : ℕ) : SMul (DihedralGroup n) (ZMod n) where
  smul g x := match g with
    | DihedralGroup.r i => x + i
    | DihedralGroup.sr i => -i - x

instance dihedralMulAction (n : ℕ) : MulAction (DihedralGroup n) (ZMod n) where
  one_smul x := by show x + 0 = x; ring
  mul_smul g h x := by
    cases g with
    | r i =>
      cases h with
      | r j => show x + (i + j) = (x + j) + i; ring
      | sr j => show -(j - i) - x = (-j - x) + i; ring
    | sr i =>
      cases h with
      | r j => show -(i + j) - x = -i - (x + j); ring
      | sr j => show x + (j - i) = -i - (-j - x); ring

/-- **Substitution isomers of benzene.**  The six ring positions of benzene are labelled by
`ZMod 6` and carry the action of the full symmetry group of the hexagon (the dihedral group of
order 12, i.e. rotations together with reflections).  With two possible substituents at each
position (`Bool`, e.g. `H` and `Cl`), there are exactly `13` distinct substitution isomers,
in agreement with the classical count `1 + 1 + 3 + 3 + 3 + 1 + 1` of
C₆H₆, C₆H₅X, the three C₆H₄X₂, the three C₆H₃X₃, the three C₆H₂X₄, C₆HX₅ and C₆X₆. -/
