/-
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Chem

open MulAction

-- The action of the symmetry group `G` of a molecular skeleton `S` on the set of
-- substitution patterns `S → C` (assignments of substituents from `C` to the sites of `S`),
-- given by `(g • F) s = F (g⁻¹ • s)`.
attribute [local instance] arrowAction

variable {G S C : Type*} [Group G] [MulAction G S]

/-- The number of cycles of the skeleton symmetry `g` acting on the site set `S`,
i.e. the number of orbits of the cyclic group generated by `g`. -/

noncomputable def fixedByArrowEquiv (g : G) :
    (fixedBy (S → C) g) ≃ (orbitRel.Quotient (Subgroup.zpowers g) S → C) where
  toFun := fun F => Quotient.lift (fun s => (F : S → C) s) (by
    rintro a b ⟨⟨x, hx⟩, hxa⟩
    obtain ⟨n, rfl⟩ := hx
    have hF : ∀ s, (F : S → C) (g • s) = (F : S → C) s := by
      intro s
      have h : (g • (F : S → C)) = (F : S → C) := F.2
      have h2 : (F : S → C) (g⁻¹ • (g • s)) = (F : S → C) (g • s) := congrFun h (g • s)
      rw [smul_smul, inv_mul_cancel, one_smul] at h2
      exact h2.symm
    have hb : g ^ n • b = a := hxa
    show (F : S → C) a = (F : S → C) b
    rw [← hb, invariant_zpow_smul hF])
  invFun := fun Φ => ⟨fun s => Φ (Quotient.mk _ s), by
    show (g • fun s => Φ (Quotient.mk _ s)) = fun s => Φ (Quotient.mk _ s)
    funext s
    show Φ (Quotient.mk _ (g⁻¹ • s)) = Φ (Quotient.mk _ s)
    congr 1
    apply Quotient.sound
    exact ⟨⟨g⁻¹, Subgroup.mem_zpowers_iff.2 ⟨-1, by simp⟩⟩, rfl⟩⟩
  left_inv := by intro F; ext s; rfl
  right_inv := by
    intro Φ
    funext q
    induction q using Quotient.inductionOn with
    | h s => rfl

/-- The number of substitution patterns fixed by `g` is `|C|` to the power of the number of
cycles of `g`. -/
