/-
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Chem

open MulAction

-- The action of the symmetry group `G` of a molecular skeleton `S` on the set of
-- substitution patterns `S → C` (assignments of substituents from `C` to the sites of `S`),
-- given by `(g • F) s = F (g⁻¹ • s)`.
attribute [local instance] arrowAction

variable {G S C : Type*} [Group G] [MulAction G S]

/-- The number of cycles of the skeleton symmetry `g` acting on the site set `S`,
i.e. the number of orbits of the cyclic group generated by `g`. -/

theorem invariant_zpow_smul {g : G} {F : S → C} (hF : ∀ s, F (g • s) = F s) (n : ℤ) (s : S) :
    F (g ^ n • s) = F s := by
  have hinv : ∀ s : S, F (g⁻¹ • s) = F s := by
    intro s
    have h := hF (g⁻¹ • s)
    rw [smul_smul, mul_inv_cancel, one_smul] at h
    exact h.symm
  induction n using Int.induction_on generalizing s with
  | zero => simp
  | succ k ih =>
      have : g ^ ((k : ℤ) + 1) • s = g ^ (k : ℤ) • (g • s) := by
        rw [zpow_add_one, mul_smul]
      rw [this, ih (g • s), hF]
  | pred k ih =>
      have : g ^ (-(k : ℤ) - 1) • s = g ^ (-(k : ℤ)) • (g⁻¹ • s) := by
        rw [zpow_sub_one, mul_smul]
      rw [this, ih (g⁻¹ • s), hinv]

/-- Substitution patterns fixed by `g` correspond exactly to arbitrary assignments of
substituents to the cycles of `g`. -/
