/-
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Chem

open MulAction

-- The action of the symmetry group `G` of a molecular skeleton `S` on the set of
-- substitution patterns `S → C` (assignments of substituents from `C` to the sites of `S`),
-- given by `(g • F) s = F (g⁻¹ • s)`.
attribute [local instance] arrowAction

variable {G S C : Type*} [Group G] [MulAction G S]

/-- The number of cycles of the skeleton symmetry `g` acting on the site set `S`,
i.e. the number of orbits of the cyclic group generated by `g`. -/

theorem isomer_count_of_trivial_group [Unique G] [Finite S] [Finite C] :
    Nat.card (orbitRel.Quotient G (S → C)) = Nat.card C ^ Nat.card S := by
  have h := polya_isomer_count (G := G) (S := S) (C := C)
  simp only [Finset.univ_unique, Finset.sum_singleton, Nat.card_unique, mul_one,
    Unique.eq_default] at h
  rw [h]
  congr 1
  rw [show (default : G) = 1 from Subsingleton.elim _ _, cycleCount_one]

/-! ### A worked chemical example: the rotational isomer count of a six-membered ring -/

section CyclicSkeleton

/-- For the rotation action of a cyclic (translation) group on itself, the number of cycles of
the rotation by `k` is the index of the subgroup generated by `k`. -/
