/-
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Chem

open MulAction

-- The action of the symmetry group `G` of a molecular skeleton `S` on the set of
-- substitution patterns `S → C` (assignments of substituents from `C` to the sites of `S`),
-- given by `(g • F) s = F (g⁻¹ • s)`.
attribute [local instance] arrowAction

variable {G S C : Type*} [Group G] [MulAction G S]

/-- The number of cycles of the skeleton symmetry `g` acting on the site set `S`,
i.e. the number of orbits of the cyclic group generated by `g`. -/

theorem polya_isomer_count_average [Fintype G] [Nonempty G] [Finite S] [Finite C] :
    (Nat.card (orbitRel.Quotient G (S → C)) : ℚ)
      = (∑ g : G, (Nat.card C : ℚ) ^ cycleCount S g) / (Nat.card G : ℚ) := by
  have hG : (Nat.card G : ℚ) ≠ 0 := by
    simp [Nat.card_eq_fintype_card, Fintype.card_ne_zero]
  rw [eq_div_iff hG]
  exact_mod_cast congrArg (fun n : ℕ => (n : ℚ)) (polya_isomer_count (G := G) (S := S) (C := C))

/-- The identity symmetry has exactly one cycle per site. -/
