/-
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Chem

open MulAction

-- The action of the symmetry group `G` of a molecular skeleton `S` on the set of
-- substitution patterns `S → C` (assignments of substituents from `C` to the sites of `S`),
-- given by `(g • F) s = F (g⁻¹ • s)`.
attribute [local instance] arrowAction

variable {G S C : Type*} [Group G] [MulAction G S]

/-- The number of cycles of the skeleton symmetry `g` acting on the site set `S`,
i.e. the number of orbits of the cyclic group generated by `g`. -/

theorem zpow_eq_pow_toNat_emod {g : G} {m : ℕ} (hm : 0 < m) (hgm : g ^ m = 1) (z : ℤ) :
    g ^ z = g ^ ((z % m).toNat) := by
  have hmz : (m : ℤ) ≠ 0 := by exact_mod_cast hm.ne'
  have h1 : (m : ℤ) * (z / m) + z % m = z := Int.mul_ediv_add_emod z m
  have hnn : 0 ≤ z % m := Int.emod_nonneg z hmz
  calc g ^ z = g ^ ((m : ℤ) * (z / m) + z % m) := by rw [h1]
    _ = (g ^ (m : ℤ)) ^ (z / m) * g ^ (z % m) := by rw [zpow_add, zpow_mul]
    _ = g ^ (z % m) := by rw [zpow_natCast, hgm, one_zpow, one_mul]
    _ = g ^ ((z % m).toNat) := by rw [← zpow_natCast, Int.toNat_of_nonneg hnn]

/-- A computable description of the cycle count: the number of distinct orbit sets
`{g ^ i • s : i < m}`, for any exponent `m > 0` with `g ^ m = 1`. -/
