/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: b9fd0108-621a-414a-9617-1cd08f2412c8

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Real Complex Finset Matrix MeasureTheory

/-- The golden ratio φ = (1 + √5)/2 ≈ 1.618033988749... -/
def φ : ℝ := (1 + sqrt 5) / 2

/-- The golden conjugate φ̄ = (1 - √5)/2 ≈ -0.618033988749... -/
def φ_bar : ℝ := (1 - sqrt 5) / 2

/-- √5 is greater than 1 -/

lemma A_ae_memLp (f : Vertices →ₘ[μ] ℂ) (hf : f ∈ Lp ℂ 2 μ) : A_ae f ∈ Lp ℂ 2 μ := by
  -- Since $A_ae$ is a bounded operator, the composition of $A_ae$ with any $L^2$ function is also in $L^2$.
  have h_bounded : ∀ f : Vertices →ₘ[μ] ℂ, f ∈ MeasureTheory.Lp ℂ 2 μ → A_ae f ∈ MeasureTheory.Lp ℂ 2 μ := by
    intro f hf;
    -- Since $A_{\text{raw}}$ is bounded, the composition of $A_{\text{raw}}$ with any $L^2$ function is also in $L^2$.
    have h_bounded : ∀ f : Vertices → ℂ, MeasureTheory.MemLp f 2 μ → MeasureTheory.MemLp (A_raw f) 2 μ := by
      intro f hf;
      have h_bounded : MeasureTheory.eLpNorm (A_raw f) 2 μ ≤ 10 * MeasureTheory.eLpNorm f 2 μ := by
        exact?;
      constructor;
      · exact?;
      · exact lt_of_le_of_lt h_bounded ( ENNReal.mul_lt_top ( by norm_num ) ( hf.eLpNorm_lt_top ) );
    obtain ⟨ g, hg ⟩ := f;
    rw [ MeasureTheory.Lp.mem_Lp_iff_eLpNorm_lt_top ] at *;
    obtain ⟨ g', hg' ⟩ := h_bounded g ( by
      constructor <;> aesop );
    convert hg' using 1;
    erw [ MeasureTheory.eLpNorm_congr_ae ( MeasureTheory.AEEqFun.coeFn_mk _ _ ) ];
  exact h_bounded f hf

/-- The adjacency operator as a bounded linear map on ℓ² -/
