/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: b9fd0108-621a-414a-9617-1cd08f2412c8

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Real Complex Finset Matrix MeasureTheory

/-- The golden ratio φ = (1 + √5)/2 ≈ 1.618033988749... -/
def φ : ℝ := (1 + sqrt 5) / 2

/-- The golden conjugate φ̄ = (1 - √5)/2 ≈ -0.618033988749... -/
def φ_bar : ℝ := (1 - sqrt 5) / 2

/-- √5 is greater than 1 -/

lemma ae_eq_of_count {f g : Vertices → ℂ} (h : f =ᵐ[μ] g) : f = g := by
  -- Since μ is the counting measure, if f equals g almost everywhere, then for every vertex u, f(u) must equal g(u).
  have h_eq : ∀ u : Vertices, f u = g u := by
    contrapose! h;
    obtain ⟨ u, hu ⟩ := h;
    refine' ne_of_gt ( lt_of_lt_of_le _ ( MeasureTheory.measure_mono ( Set.singleton_subset_iff.mpr hu ) ) );
    -- Since μ is the counting measure, the measure of a singleton set is 1.
    simp [μ];
  exact funext h_eq

/-- Penrose tiling vertices are countable -/
instance : Countable Vertices := by
  have h_range : (Set.range proj_para).Countable := Set.countable_range proj_para
  have h_subset : Vertices ⊆ Set.range proj_para := by
    rintro z ⟨n, rfl, _⟩
    exact Set.mem_range_self n
  exact Set.Countable.to_subtype (Set.Countable.mono h_subset h_range)

#check measurable_of_countable

-- Adjacency on AEEqFun with proper quotient structure
