/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7aa1b75c-1878-4cfa-ada6-5ae50a9f33bd

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Classical
open Real Complex Finset Matrix
open scoped ComplexConjugate

/-- The golden ratio φ = (1 + √5)/2 ≈ 1.618... -/
def φ : ℝ := (1 + sqrt 5) / 2

/-- The golden conjugate φ̄ = (1 - √5)/2 ≈ -0.618... -/
def φ_bar : ℝ := (1 - sqrt 5) / 2


theorem sum_neighbors_in_L2 [PenroseSpectralAxioms] (f : L2Penrose) :
  Summable (fun p => (∑ q ∈ neighbors p, f.val q)^2) := by
  obtain ⟨D, hD⟩ := PenroseSpectralAxioms.degree_bounded
  -- Since $f \in \ell^2$, we have $\sum_p f(p)^2 < \infty$.
  have h_sum_f_sq : Summable (fun p => (f.val p) ^ 2) := by
    exact f.2;
  -- By the Cauchy-Schwarz inequality, we have $(\sum_{q \in N(p)} f(q))^2 \leq |N(p)| \sum_{q \in N(p)} f(q)^2$.
  have h_cauchy_schwarz : ∀ p : PenrosePoint, (∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset, (f.val q)) ^ 2 ≤ (D : ℝ) * ∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset, (f.val q) ^ 2 := by
    intro p
    have h_cauchy_schwarz_step : (∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset, (f.val q)) ^ 2 ≤ ((‹PenroseSpectralAxioms›.neighbors_finite p).toFinset.card : ℝ) * ∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset, (f.val q) ^ 2 := by
      exact?
    generalize_proofs at *;
    exact h_cauchy_schwarz_step.trans ( mul_le_mul_of_nonneg_right ( mod_cast hD p ) ( Finset.sum_nonneg fun _ _ => sq_nonneg _ ) );
  -- By Fubini's theorem, we can interchange the order of summation.
  have h_fubini : Summable (fun p => ∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset, (f.val q) ^ 2) := by
    refine' summable_of_sum_le _ _;
    exact ∑' p : PenrosePoint, ( f.val p ) ^ 2 * D;
    · exact fun p => Finset.sum_nonneg fun _ _ => sq_nonneg _;
    · intro u
      have h_sum_le : ∑ x ∈ u, ∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite x).toFinset, (f.val q) ^ 2 ≤ ∑ q ∈ Finset.biUnion u (fun p => (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset), (f.val q) ^ 2 * D := by
        have h_sum_le : ∀ q ∈ Finset.biUnion u (fun p => (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset), ∑ x ∈ u, (if q ∈ (‹PenroseSpectralAxioms›.neighbors_finite x).toFinset then (f.val q) ^ 2 else 0) ≤ (f.val q) ^ 2 * D := by
          simp +contextual [ Finset.sum_ite ];
          intro a ha x hx hxu hx'; rw [ mul_comm ] ; gcongr;
          refine' le_trans _ ( hD ⟨ a, ha ⟩ );
          refine' Finset.card_le_card _;
          simp +contextual [ Finset.subset_iff, neighbors_set ];
          exact?;
        refine' le_trans _ ( Finset.sum_le_sum h_sum_le );
        rw [ Finset.sum_comm ];
        exact Finset.sum_le_sum fun p hp => by rw [ ← Finset.sum_filter ] ; exact Finset.sum_le_sum_of_subset_of_nonneg ( fun q hq => by aesop ) fun _ _ _ => sq_nonneg _;
      exact h_sum_le.trans ( Summable.sum_le_tsum _ ( fun _ _ => mul_nonneg ( sq_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( h_sum_f_sq.mul_right _ ) );
  exact Summable.of_nonneg_of_le ( fun p => sq_nonneg _ ) ( fun p => h_cauchy_schwarz p ) ( h_fubini.mul_left _ )

