/-
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace QPhys

open Matrix

variable {n : ℕ}

/-- The time-evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`
(represented as an `n × n` complex matrix), with reduced Planck constant `hbar`. -/

theorem conjTranspose_generator (hbar : ℝ) {H : Matrix (Fin n) (Fin n) ℂ}
    (hH : H.IsHermitian) (t : ℝ) :
    (-(Complex.I * (t / hbar)) • H)ᴴ = -(-(Complex.I * (t / hbar)) • H) := by
  simp [hH.eq]

/-- **Unitary time evolution.** For a self-adjoint Hamiltonian `H`, the operator
`U(t) = exp(-i H t / ℏ)` is unitary for every real time `t`. -/
