/-
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

namespace QPhys

open Matrix NormedSpace

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- The time-evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`. -/

theorem conjTranspose_timeEvolution_mul_self (H : Matrix n n ℂ) (hH : H.IsHermitian)
    (hbar t : ℝ) : (timeEvolution H hbar t)ᴴ * timeEvolution H hbar t = 1 :=
  (unitary_time_evolution H hH hbar t).1

/-- Explicit form of unitarity: `U(t) * U(t)ᴴ = 1`. -/
