import Mathlib

/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open NormedSpace Complex

namespace QPhys

section StarAlgebra

variable {A : Type*} [NormedRing A] [NormedAlgebra ℂ A] [StarRing A] [ContinuousStar A]
  [CompleteSpace A] [StarModule ℂ A]

/-- The time-evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`
(an element of a complex Banach star-algebra, e.g. a bounded operator on a Hilbert space). -/

theorem evolution_mul_star_self {H : A} (hH : IsSelfAdjoint H) (hbar t : ℝ) :
    evolution hbar H t * star (evolution hbar H t) = 1 :=
  (Unitary.mem_iff.mp (unitary_time_evolution hH hbar t)).2

end StarAlgebra

section Hilbert

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E] [CompleteSpace E]

/-- Concrete form on a complex Hilbert space: the time evolution generated by a self-adjoint
bounded operator `H` is a unitary operator. -/
