import Mathlib

/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open NormedSpace Complex

namespace QPhys

section StarAlgebra

variable {A : Type*} [NormedRing A] [NormedAlgebra ℂ A] [StarRing A] [ContinuousStar A]
  [CompleteSpace A] [StarModule ℂ A]

/-- The time-evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`
(an element of a complex Banach star-algebra, e.g. a bounded operator on a Hilbert space). -/

noncomputable def evolution (hbar : ℝ) (H : A) (t : ℝ) : A :=
  exp ((-(Complex.I * (t : ℂ) / (hbar : ℂ))) • H)

omit [ContinuousStar A] [CompleteSpace A] in
/-- For self-adjoint `H` and real `t`, the element `-i H t / ℏ` is skew-adjoint. -/
