/-
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace QPhys

open NormedSpace

section OperatorAlgebra

variable {A : Type*} [NormedRing A] [NormedAlgebra ℂ A] [StarRing A] [ContinuousStar A]
  [CompleteSpace A] [StarModule ℂ A]

/-- The time evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`. -/

theorem inner_timeEvolution_timeEvolution {H : E →L[ℂ] E} (hH : IsSelfAdjoint H) (hbar t : ℝ)
    (x y : E) :
    inner ℂ (timeEvolution hbar H t x) (timeEvolution hbar H t y) = inner ℂ x y := by
  have h := star_timeEvolution_mul_self hH hbar t
  have : inner ℂ (timeEvolution hbar H t x) (timeEvolution hbar H t y)
      = inner ℂ x ((star (timeEvolution hbar H t) * timeEvolution hbar H t) y) := by
    simp [ContinuousLinearMap.star_eq_adjoint, ContinuousLinearMap.adjoint_inner_right]
  rw [this, h]
  simp

/-- Time evolution generated by a self-adjoint Hamiltonian preserves norms (conservation of
probability). -/
