import Mathlib

/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open NormedSpace Complex

namespace QPhys

section StarAlgebra

variable {A : Type*} [NormedRing A] [NormedAlgebra ℂ A] [StarRing A] [ContinuousStar A]
  [CompleteSpace A] [StarModule ℂ A]

/-- The time-evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`
(an element of a complex Banach star-algebra, e.g. a bounded operator on a Hilbert space). -/

theorem norm_evolution_apply {H : E →L[ℂ] E} (hH : IsSelfAdjoint H) (hbar t : ℝ) (x : E) :
    ‖evolution hbar H t x‖ = ‖x‖ := by
  have h := inner_evolution_evolution hH hbar t x x
  have h1 : ‖evolution hbar H t x‖ ^ 2 = ‖x‖ ^ 2 := by
    have hx := inner_self_eq_norm_sq (𝕜 := ℂ) (evolution hbar H t x)
    have hy := inner_self_eq_norm_sq (𝕜 := ℂ) x
    have h2 := congrArg (RCLike.re (K := ℂ)) h
    rw [hx, hy] at h2
    exact h2
  rw [← Real.sqrt_sq (norm_nonneg (evolution hbar H t x)), ← Real.sqrt_sq (norm_nonneg x), h1]

end Hilbert

end QPhys

-- Axiom audit for the target theorem.
#print axioms QPhys.unitary_time_evolution

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

