/-
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Unitary time evolution

For a self-adjoint (Hermitian) Hamiltonian `H` acting on a finite-dimensional complex
Hilbert space, the time-evolution operator

  `U t = exp (-(I * t / ℏ) • H)`

is unitary for every real time `t`.  The proof observes that `-(I * t / ℏ) • H` is a
skew-adjoint element of the (Banach) star algebra of matrices, and that the exponential
of a skew-adjoint element is unitary.

We also record the two defining identities `U(t)ᴴ * U(t) = 1`, `U(t) * U(t)ᴴ = 1`, together
with the one-parameter group law `U(s + t) = U(s) * U(t)` and `U 0 = 1`.
-/

namespace QPhys

open scoped Matrix

attribute [local instance] Matrix.linftyOpNormedRing Matrix.linftyOpNormedAlgebra

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- The time-evolution operator `U t = exp (-i H t / ℏ)` generated by a Hamiltonian `H`
(with reduced Planck constant `ℏ`). -/

lemma smul_mem_skewAdjoint {H : Matrix n n ℂ} (hH : H.IsHermitian) (hbar t : ℝ) :
    (-(Complex.I * ((t : ℂ) / hbar))) • H ∈ skewAdjoint (Matrix n n ℂ) := by
  rw [skewAdjoint.mem_iff, star_smul, Matrix.star_eq_conjTranspose, hH.eq, ← neg_smul]
  congr 1
  simp

/-- **Unitary time evolution.**  For a self-adjoint Hamiltonian `H`, the operator
`U t = exp (-i H t / ℏ)` is unitary for every real time `t`. -/
