import Mathlib

/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open NormedSpace Complex

namespace QPhys

section StarAlgebra

variable {A : Type*} [NormedRing A] [NormedAlgebra ℂ A] [StarRing A] [ContinuousStar A]
  [CompleteSpace A] [StarModule ℂ A]

/-- The time-evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`
(an element of a complex Banach star-algebra, e.g. a bounded operator on a Hilbert space). -/

theorem star_evolution_mul_self {H : A} (hH : IsSelfAdjoint H) (hbar t : ℝ) :
    star (evolution hbar H t) * evolution hbar H t = 1 :=
  (Unitary.mem_iff.mp (unitary_time_evolution hH hbar t)).1

/-- `U(t) U(t)⋆ = 1`. -/
