/-
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace QPhys

open NormedSpace

section OperatorAlgebra

variable {A : Type*} [NormedRing A] [NormedAlgebra ℂ A] [StarRing A] [ContinuousStar A]
  [CompleteSpace A] [StarModule ℂ A]

/-- The time evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`. -/

theorem timeEvolution_mul_star {H : A} (hH : IsSelfAdjoint H) (hbar t : ℝ) :
    timeEvolution hbar H t * star (timeEvolution hbar H t) = 1 :=
  (Unitary.mem_iff.mp (unitary_time_evolution hH hbar t)).2

end OperatorAlgebra

section Hilbert

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E] [CompleteSpace E]

/-- On a complex Hilbert space, time evolution generated by a self-adjoint Hamiltonian preserves
the inner product: `⟪U(t) x, U(t) y⟫ = ⟪x, y⟫`. -/
