/-
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace QPhys

open Matrix

variable {n : ℕ}

/-- The time-evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`
(represented as an `n × n` complex matrix), with reduced Planck constant `hbar`. -/

noncomputable def timeEvolutionCLM (hbar : ℝ) (H : E →L[ℂ] E) (t : ℝ) : E →L[ℂ] E :=
  exp (-(Complex.I * (t / hbar)) • H)

/-- **Unitary time evolution on a Hilbert space.** For a bounded self-adjoint Hamiltonian `H`
on a complex Hilbert space, `U(t) = exp(-i H t / ℏ)` is unitary for every real time `t`. -/
