-- Header (Lean requires `import` to precede any module docstring):
/-
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib
/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace QPhys

open NormedSpace Complex

section Algebra

variable {A : Type*} [NormedRing A] [NormedAlgebra ℂ A] [StarRing A] [ContinuousStar A]
  [CompleteSpace A] [StarModule ℂ A]

/-- The time-evolution operator `U t = exp (-i H t / ℏ)` generated by a Hamiltonian `H`. -/

theorem unitary_time_evolution_hilbert (H : E →L[ℂ] E) (hH : IsSelfAdjoint H) (hbar t : ℝ) :
    timeEvolution H hbar t ∈ unitary (E →L[ℂ] E) :=
  unitary_time_evolution H hH hbar t

/-- Time evolution preserves inner products: `⟪U t x, U t y⟫ = ⟪x, y⟫`. -/
