/-
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace QPhys

open Matrix

variable {n : ℕ}

/-- The time-evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`
(represented as an `n × n` complex matrix), with reduced Planck constant `hbar`. -/

theorem unitary_time_evolution_hilbert (hbar : ℝ) {H : E →L[ℂ] E} (hH : IsSelfAdjoint H)
    (t : ℝ) : timeEvolutionCLM hbar H t ∈ unitary (E →L[ℂ] E) := by
  letI : NormedAlgebra ℚ (E →L[ℂ] E) := .restrictScalars ℚ ℂ _
  apply exp_mem_unitary_of_mem_skewAdjoint
  rw [skewAdjoint.mem_iff, star_smul, hH.star_eq]
  simp [Complex.conj_ofReal]

/-- Unitary time evolution preserves the norm of every state, i.e. probability is conserved. -/
