/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 9f82e799-b6d7-4aa5-96d7-fe1e45c2e36c
-/

/-
GeometricArithmetic.lean

A Tier-I (and partially Tier-II scaffold) Lean 4 / mathlib formalization for the white-paper:

  "Geometric Arithmetic and Spectral Stability on ℕ"

Focus of this file:
  • Rays as ZMod p fibers (canonical ray partition)
  • The finite “polygon geometry” on ray-labels (cycle adjacency)
  • The universal (p-2) admissible nonzero transition count (fully proved)
  • A clean Tier-labeling discipline (Tier I proved; Tier II stated as conjectures)

Notes:
  • We attach Dₚ symmetry to the *cycle geometry on labels* (ZMod p), not to automorphisms of (ℕ,+).
  • The “golden signature” and RH “stability” pieces are left as Tier II stubs: they require substantial analytic/spectral libraries.

Tested assumptions:
  • This is written to be mathlib-friendly and “compiles in spirit”; if your local mathlib snapshot differs,
    you may need minor import/lemma-name tweaks.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators

open Finset

/-- The `p`-ray indexed by `i : ZMod p` as a subset of `ℕ`. -/

lemma card_univ_erase_zero {p : ℕ} [Fact p.Prime] :
    (univ.erase (0 : ZMod p)).card = p - 1 := by
  classical
  have h0 : (0 : ZMod p) ∈ (univ : Finset (ZMod p)) := by simp
  -- card(erase) = card - 1
  simpa [card_zmod] using (card_erase_of_mem h0)

/-- Universal (p-2) law on admissible labels for a nonzero gap `g`. -/
