import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Brockian

/-! ## Goldbach representations on the `K = 2` wheel

The `K = 2` wheel is the wheel generated by the first two primes, so its modulus is
`2 * 3 = 6` and its spokes are the residues `1` and `5` modulo `6`.

`GoldbachWheelK2 m` says that every even number `n` with `10 ≤ n ≤ m` is a sum of two
primes **both of which lie on the wheel**, i.e. both are coprime to `6` (equivalently,
both are at least `5`). The lower bound `10` is sharp for this strengthened form: `6`
and `8` are sums of two primes only by using the off-wheel prime `3`.

The family is indexed by the bound `m`; this file adds the new member `m = 1051`.
-/

/-- The modulus of the `K = 2` wheel: the product of the first two primes. -/
def wheelK2Modulus : ℕ := 6

/-- Every even `n` with `10 ≤ n ≤ m` is a sum of two primes that both lie on the
`K = 2` wheel (i.e. both are coprime to `6`). -/
def GoldbachWheelK2 (m : ℕ) : Prop :=
  ∀ n : ℕ, 10 ≤ n → n ≤ m → 2 ∣ n →
    ∃ p q : ℕ, Nat.Prime p ∧ Nat.Prime q ∧
      Nat.Coprime p wheelK2Modulus ∧ Nat.Coprime q wheelK2Modulus ∧ p + q = n

/-! ### A kernel-friendly primality test for numbers up to `1051` -/

/-- The primes below `√1051`. -/
private def smallDivs : List ℕ := [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]

/-- Trial division by all primes `≤ 31`; a correct primality test for `n ≤ 1051`. -/
private def primeB (n : ℕ) : Bool :=
  decide (2 ≤ n) && smallDivs.all (fun d => d == n || !(n % d == 0))

private theorem primeB_spec {n : ℕ} (hn : n ≤ 1051) (h : primeB n = true) : Nat.Prime n := by
  unfold primeB at h
  simp [smallDivs] at h
  obtain ⟨h2, hd⟩ := h
  by_contra hp
  have h0 : 0 < n := by omega
  have hsq := Nat.minFac_sq_le_self h0 hp
  have hple : n.minFac ≤ 32 := by nlinarith
  have hpr : (n.minFac).Prime := Nat.minFac_prime (by omega)
  have hdvd : n.minFac ∣ n := Nat.minFac_dvd n
  have h2' : 2 ≤ n.minFac := hpr.two_le
  interval_cases h : n.minFac <;> simp_all [Nat.dvd_iff_mod_eq_zero] <;> omega

/-- A prime `≥ 5` lies on the `K = 2` wheel. -/
private theorem coprime_wheelK2 {p : ℕ} (hp : Nat.Prime p) (h5 : 5 ≤ p) :
    Nat.Coprime p wheelK2Modulus := by
  rw [Nat.Prime.coprime_iff_not_dvd hp]
  intro hdvd
  have h6 : p ≤ 6 := by
    simpa [wheelK2Modulus] using Nat.le_of_dvd (by norm_num [wheelK2Modulus]) hdvd
  revert hdvd
  interval_cases p
  · decide
  · exact absurd hp (by decide)

/-- Candidate small summands: the wheel primes below `80`. -/
private def wheelWitnesses : List ℕ :=
  [5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73]

set_option maxRecDepth 100000 in
/-- The finite verification: every even `n` in `[10, 1051]` admits a witness from
`wheelWitnesses` whose complement is again a wheel prime. -/
private theorem wheel_search : ∀ n ∈ List.range' 10 1042, n % 2 = 0 →
    ∃ p ∈ wheelWitnesses, primeB p = true ∧ primeB (n - p) = true ∧ 5 ≤ n - p := by
  decide

/-- **Goldbach on the `K = 2` wheel, modulus `1051`.**
Every even `n` with `10 ≤ n ≤ 1051` is the sum of two primes both coprime to `6`. -/
theorem GoldbachWheelK2_1051 : GoldbachWheelK2 1051 := by
  intro n h10 h1051 heven
  have hmem : n ∈ List.range' 10 1042 := by
    rw [List.mem_range'_1]; omega
  obtain ⟨p, hpmem, hp, hq, h5q⟩ := wheel_search n hmem (by omega)
  have hpb : 5 ≤ p ∧ p ≤ 73 := by
    simp only [wheelWitnesses, List.mem_cons, List.not_mem_nil, or_false] at hpmem
    rcases hpmem with h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h <;>
      omega
  obtain ⟨hp5, hple⟩ := hpb
  have hpp : Nat.Prime p := primeB_spec (by omega) hp
  have hqp : Nat.Prime (n - p) := primeB_spec (by omega) hq
  refine ⟨p, n - p, hpp, hqp, coprime_wheelK2 hpp hp5, coprime_wheelK2 hqp h5q, ?_⟩
  omega

end Brockian

