/-
Enumeration data for `Brockian.GoldbachWheelK2_1327`.

For every `n` with `2 ≤ n ≤ 1327` we exhibit an explicit pair of primes summing
to the even number `2 * n`, i.e. Goldbach's conjecture is verified for all even
numbers up to twice the wheel modulus `1327`.
-/
import Mathlib

set_option maxRecDepth 10000

namespace Brockian

/-- `GoldbachRep n` states that `n` is a sum of two primes. -/

theorem goldbachRep_two_mul (n : ℕ) (h1 : 2 ≤ n) (h2 : n ≤ 1327) :
    GoldbachRep (2 * n) := by
  interval_cases n
  · exact ⟨2, 2, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 3, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 5, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 7, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 7, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 11, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 13, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 13, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 17, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 19, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 19, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 23, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 23, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 23, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 29, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 31, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 31, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 31, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 37, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 37, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 41, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 43, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 43, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 47, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 47, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 47, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 53, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 53, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 53, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 59, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 61, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 61, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 61, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 67, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 67, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 71, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 73, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 73, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 73, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 79, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 79, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 83, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 83, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 83, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 89, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 89, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 89, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 79, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 97, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 97, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 101, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 107, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 127, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 127, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 131, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 131, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 131, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 137, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 139, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 139, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 139, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 137, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 139, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 149, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 151, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 151, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 151, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 157, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 157, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 157, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 163, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 163, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 167, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 167, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 167, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 173, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 173, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 173, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 191, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 193, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 193, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 197, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 197, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 197, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 223, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 223, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 227, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 229, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 229, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 233, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 233, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 233, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 239, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 241, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 241, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 241, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 239, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 241, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 257, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 257, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 257, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 263, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 263, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 263, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 269, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 271, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 271, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 271, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 277, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 277, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 281, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 281, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 277, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 307, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 307, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 311, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 313, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 313, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 313, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 313, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 331, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 331, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 331, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 337, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 337, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 337, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨29, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 337, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 347, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 349, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 349, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 353, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 353, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 353, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 359, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 359, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 359, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 349, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 379, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 379, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 383, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 383, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 383, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 379, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 397, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 397, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 401, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 401, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 401, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 397, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 401, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 419, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 421, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 421, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 421, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 419, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 421, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 431, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 433, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 433, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 433, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 439, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 439, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 443, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 443, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 443, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 449, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 449, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 449, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 439, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 457, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 457, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 461, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 463, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 463, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 463, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 479, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 479, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 479, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 457, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 487, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 487, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 491, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 491, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 491, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 487, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 541, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 541, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 541, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 547, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 547, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 547, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨47, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 547, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 563, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 563, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 563, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 569, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 571, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 571, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 571, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 577, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 577, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 577, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 569, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 577, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 587, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 587, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 587, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 599, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 601, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 601, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 601, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 607, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 607, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 607, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 613, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 613, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 617, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 617, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 631, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 631, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 631, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 617, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 631, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 641, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 643, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 643, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 647, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 647, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 647, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 653, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 653, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 653, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 659, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 661, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 661, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 661, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 659, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 661, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 661, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 673, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 673, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 677, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 677, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 677, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 683, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 683, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 683, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 673, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 691, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 691, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 691, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 683, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 691, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 701, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 701, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 701, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 691, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 701, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 719, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 719, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 719, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 727, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 727, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 727, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 733, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 733, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 733, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 739, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 739, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 743, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 743, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 743, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 739, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 751, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 751, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 751, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 757, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 757, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 761, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 761, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 761, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 757, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 769, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 769, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 773, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 773, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 773, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 769, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 773, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 773, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 769, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 773, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 797, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 797, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 797, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 797, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 797, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 809, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 809, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 821, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 823, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 823, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 827, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 829, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 829, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 829, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 827, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 829, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 839, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 839, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 839, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 829, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 839, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 839, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 823, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 853, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 853, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 857, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 859, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 859, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 863, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 863, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 863, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 859, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 863, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 863, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 859, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 877, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 877, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 881, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 883, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 883, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 883, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 883, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 877, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 907, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 907, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 911, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 911, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 911, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 907, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 911, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 929, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 929, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 929, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 937, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 937, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 941, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 941, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 941, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 947, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 947, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 947, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 953, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 953, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 953, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨43, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 953, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 953, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 937, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 967, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 967, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 971, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 971, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 971, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 977, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 977, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 977, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 983, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 983, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 983, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨73, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 991, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 991, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 991, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 997, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 997, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 997, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 983, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 997, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 997, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1009, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1009, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1013, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1013, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1013, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1019, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1021, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1021, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1021, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1019, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1021, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1031, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1033, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1033, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1033, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1031, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1049, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1051, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1051, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1051, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1049, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1051, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1061, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1063, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1063, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1063, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1061, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1061, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1087, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1087, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1091, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1093, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1093, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1097, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1097, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1097, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 1087, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1117, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1117, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1117, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1123, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1123, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1123, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨29, 1109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨41, 1103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨41, 1109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1151, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1153, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1153, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1153, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1151, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1153, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1163, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1163, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1163, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1153, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1171, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1171, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1171, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1163, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1171, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1187, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1187, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1187, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1193, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1193, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1193, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 1171, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1201, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1201, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1201, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1193, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1201, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1201, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1213, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1213, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1217, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1217, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1217, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1223, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1223, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1223, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1229, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1231, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1231, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1231, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1237, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1237, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1237, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1229, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1237, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1237, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1249, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1249, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1249, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨29, 1229, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1249, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1259, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1259, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1259, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1249, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1259, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1259, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨37, 1237, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1259, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1259, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1277, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1279, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1279, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1289, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1291, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1291, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1291, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1297, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1297, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1301, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1303, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1303, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1307, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1307, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1307, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1303, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1307, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1307, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1319, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1321, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1321, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1321, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1327, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1327, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1327, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1319, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1327, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1327, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1319, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1327, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1327, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨29, 1319, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1327, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 1321, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨47, 1307, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨29, 1327, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 1327, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨41, 1319, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨41, 1321, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1361, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1361, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1361, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨61, 1321, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1381, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1381, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1381, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1381, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1381, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1381, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1381, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1399, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1399, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1399, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨41, 1367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1399, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1399, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨43, 1381, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1423, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1423, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1427, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1429, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1429, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1433, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1433, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1433, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1439, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1439, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1439, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1429, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1447, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1447, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1451, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1453, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1453, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1453, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1459, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1459, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1459, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1451, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1459, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1459, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1471, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1471, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1471, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨29, 1451, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1471, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1481, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1483, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1483, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1487, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1489, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1489, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1493, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1493, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1493, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1489, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1511, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1511, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1511, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 1489, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1511, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1511, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨43, 1489, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1531, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1531, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1531, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1531, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1531, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1543, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1543, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1543, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1549, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1549, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1553, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1553, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1553, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1559, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1559, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1559, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1549, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1567, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1567, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1571, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1571, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1571, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1567, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1579, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1579, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1583, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1583, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1583, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1579, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1583, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1583, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1579, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1597, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1597, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1601, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1601, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1601, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1607, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1609, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1609, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1613, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1613, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1613, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1621, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1621, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1621, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1627, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1627, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1627, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1627, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1637, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1637, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1637, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1627, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1637, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1637, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 1621, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1637, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1637, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 1627, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1657, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1657, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1657, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1663, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1663, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1667, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1669, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1669, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1669, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1667, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1669, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1669, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1667, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1669, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1669, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1667, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1669, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 1663, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1693, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1693, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1697, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1699, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1699, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1699, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1697, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1699, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1699, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1721, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1723, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1723, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1723, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1721, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1723, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1733, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1733, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1733, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1723, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1741, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1741, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1741, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1747, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1747, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1747, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1753, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1753, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1753, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1759, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1759, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1759, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨47, 1721, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1759, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1759, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨41, 1733, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1759, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1759, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1777, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1777, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1777, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1783, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1783, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1789, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1789, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1789, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1789, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1789, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1801, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1801, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1801, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1801, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1801, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1823, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1823, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1823, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 1801, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1831, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1831, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1831, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1823, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1831, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1831, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1823, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1831, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1847, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1847, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1847, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨67, 1789, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1847, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1847, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 1831, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1861, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1861, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1861, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1867, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1867, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1871, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1873, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1873, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1877, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1879, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1879, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1879, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1877, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1879, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1889, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1889, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1889, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1879, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1889, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1889, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1901, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1901, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1901, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1907, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1907, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1907, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1913, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1913, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1913, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨43, 1879, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1913, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1913, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨61, 1867, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1913, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1913, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1931, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1933, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1933, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1933, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1931, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1933, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1933, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1931, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1933, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1949, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1951, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1951, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1951, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1949, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1951, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1951, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1949, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1951, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1951, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1949, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1951, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1973, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1973, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1973, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1979, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1979, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1979, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨37, 1951, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1987, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1987, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1987, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1993, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1993, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1997, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1999, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1999, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2003, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2003, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2003, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1999, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2011, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2011, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2011, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2017, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2017, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2017, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 2003, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2017, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2027, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2029, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2029, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2029, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2027, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2029, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2029, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨37, 2017, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2053, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2053, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2053, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 2039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2053, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2063, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2063, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2063, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨61, 2017, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2081, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2083, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2083, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2087, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2089, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2089, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2089, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2087, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2089, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2099, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2099, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2099, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2089, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2099, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2099, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2111, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2111, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2111, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2131, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2131, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2131, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2137, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2137, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2141, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2143, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2143, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2143, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2141, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2143, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2153, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2153, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2153, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2143, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2161, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2161, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2161, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2153, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2161, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2161, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 2153, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2161, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2161, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨47, 2141, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨41, 2153, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨47, 2153, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 2179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨43, 2161, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2203, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2203, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2207, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2207, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2207, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2213, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2213, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2213, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2203, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2221, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2221, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2221, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2213, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2221, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2221, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 2213, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2221, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2237, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2239, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2239, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2243, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2243, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2243, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2239, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2243, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 2243, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2267, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2269, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2269, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2273, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2273, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2273, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2269, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2281, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2281, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2281, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2287, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2287, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2287, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2297, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2297, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2297, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2297, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2297, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2309, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2311, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2311, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2311, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2309, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2311, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2311, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2309, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2311, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2311, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 2309, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 2311, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2333, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2333, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2333, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2339, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2341, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2341, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2341, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2347, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2347, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2351, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2351, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2351, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2357, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2357, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2357, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2347, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2357, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2357, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 2341, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2371, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2371, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2371, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2377, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2377, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2381, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2383, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2383, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2383, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2393, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2393, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2393, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2399, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2399, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2399, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2399, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2399, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2411, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2411, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2411, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2417, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2417, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2417, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2423, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2423, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2423, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨43, 2389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2423, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2423, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨61, 2377, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2437, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2437, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2441, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2441, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2441, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2447, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2447, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2447, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2437, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2447, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2447, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2459, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2459, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2459, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 2437, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2473, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2473, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2477, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2477, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2477, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2473, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2477, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2477, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2473, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2477, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2477, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 2467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 2477, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨29, 2473, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 2473, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨53, 2459, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨41, 2477, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨53, 2477, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2531, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2531, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2531, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2539, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2539, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2543, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2543, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2543, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2549, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2551, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2551, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2551, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2549, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 2549, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 2557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨29, 2549, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 2557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2579, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2579, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2579, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 2557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2579, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2579, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2591, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2591, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2591, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 2593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2609, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2609, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2609, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨61, 2557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2617, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2617, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2621, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2621, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2621, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2617, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2621, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2621, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2633, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2633, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2633, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨103, 2539, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 2633, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 2633, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 2617, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 2647, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 2647, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 2647, by norm_num, by norm_num, by norm_num⟩

end Brockian

/-
# Goldbach Wheel K 2 1327
Category: Brockian Corpus
Target: Brockian.GoldbachWheelK2_1327
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib
import RequestProject.GoldbachWheelK2_1327Data

/-!
# Goldbach Wheel K 2 1327
Category: Brockian Corpus
Target: Brockian.GoldbachWheelK2_1327
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Brockian

/-- The `K = 2` Goldbach wheel: the residues modulo `2 * 3 = 6` that are coprime
to `6`, i.e. the residues in which every prime `> 3` must lie. -/
