/-!
# Hironaka Resolution
Category: Frontier Math
Target: Math2.hironaka_resolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

/-
## Toric principalization in two variables

Hironaka's theorem on resolution of singularities in characteristic zero contains, as its
combinatorial core, the *principalization* statement: after a finite tree of blowups an ideal
becomes locally principal, i.e. generated by a single monomial in every chart of every leaf of
the tree.

Here we formalize and prove this statement in the toric setting of monomial ideals in two
variables.  A monomial ideal is recorded by the finite list of exponent vectors of its monomial
generators (the monomial `x ^ a * y ^ b` is recorded by `(a, b)`), and the two standard charts of
the blowup of the origin act on exponent vectors by

* `chart1 (a, b) = (a + b, b)`   (the substitution `x = x'`, `y = x' * y'`),
* `chart2 (a, b) = (a, a + b)`   (the substitution `x = x' * y'`, `y = y'`).

`Principalizable` is the inductive predicate "some finite blowup tree principalizes", where a
node may be declared resolved as soon as one of its monomials divides all the others, and
otherwise must be resolved in *both* charts of the blowup.  The main theorem
`Math2.hironaka_resolution` states that every nonempty monomial ideal in two variables is
principalizable.  The proof is by strong induction on an explicit obstruction `mu`, the sum over
all pairs of generators of the `ℓ¹`-distance between incomparable exponent vectors; this measure
drops strictly in both charts of a blowup as long as the ideal is not already principal.

The development is self-contained: it uses only the Lean 4 core library.
-/

namespace Math2

/-- Exponent vector of a monomial `x ^ a * y ^ b` in two variables. -/
abbrev Exp : Type := Nat × Nat

/-- Divisibility of monomials, read off from exponent vectors. -/
abbrev Divides (p q : Exp) : Prop := p.1 ≤ q.1 ∧ p.2 ≤ q.2

/-- First blowup chart, acting on exponents: it records the substitution `x = x'`,
`y = x' * y'`, under which `x ^ a * y ^ b` becomes `x' ^ (a + b) * y' ^ b`. -/
def chart1 (p : Exp) : Exp := (p.1 + p.2, p.2)

/-- Second blowup chart, acting on exponents: it records the substitution `x = x' * y'`,
`y = y'`, under which `x ^ a * y ^ b` becomes `x' ^ a * y' ^ (a + b)`. -/
def chart2 (p : Exp) : Exp := (p.1, p.1 + p.2)

/-- A monomial ideal, given by the list `l` of exponent vectors of its generators, is *principal*
when one of its monomials divides all the others. -/
def IsPrincipal (l : List Exp) : Prop := ∃ p ∈ l, ∀ q ∈ l, Divides p q

/-- `Principalizable l` holds when a finite tree of blowups of the origin makes the monomial
ideal recorded by `l` principal in every chart of every leaf of the tree. -/
inductive Principalizable : List Exp → Prop
  | base {l : List Exp} : IsPrincipal l → Principalizable l
  | blowup {l : List Exp} :
      Principalizable (l.map chart1) → Principalizable (l.map chart2) → Principalizable l

/-! ### The obstruction measure -/

/-- Sum of a list of natural numbers. -/
def sumL : List Nat → Nat
  | [] => 0
  | x :: xs => x + sumL xs

/-- Weight of an ordered pair of exponent vectors: it vanishes on comparable pairs (which pose no
obstruction to principality) and equals the `ℓ¹`-distance on incomparable pairs. -/
def w (p q : Exp) : Nat :=
  if Divides p q ∨ Divides q p then 0
  else ((p.1 - q.1) + (q.1 - p.1)) + ((p.2 - q.2) + (q.2 - p.2))

/-- Total obstruction of a monomial ideal: the sum of all pair weights. -/
def mu (l : List Exp) : Nat := sumL (l.map (fun p => sumL (l.map (fun q => w p q))))

/-! ### Elementary facts about `sumL` -/

theorem sumL_map_le {α : Type} (f g : α → Nat) (l : List α) (h : ∀ x ∈ l, f x ≤ g x) :
    sumL (l.map f) ≤ sumL (l.map g) := by
  induction l with
  | nil => simp [sumL]
  | cons a t ih =>
    simp only [List.map_cons, sumL]
    have h1 := h a (by simp)
    have h2 := ih fun x hx => h x (by simp [hx])
    omega

theorem sumL_map_lt {α : Type} (f g : α → Nat) (l : List α) (h : ∀ x ∈ l, f x ≤ g x)
    {a : α} (ha : a ∈ l) (hlt : f a < g a) : sumL (l.map f) < sumL (l.map g) := by
  induction l with
  | nil => simp at ha
  | cons b t ih =>
    simp only [List.map_cons, sumL]
    rcases List.mem_cons.1 ha with rfl | hat
    · have h2 := sumL_map_le f g t fun x hx => h x (by simp [hx])
      omega
    · have h1 := h b (by simp)
      have h2 := ih (fun x hx => h x (by simp [hx])) hat
      omega

/-! ### Behaviour of the weight under the two charts -/

theorem w_chart1_le (p q : Exp) : w (chart1 p) (chart1 q) ≤ w p q := by
  obtain ⟨a, b⟩ := p; obtain ⟨c, d⟩ := q
  simp only [w, chart1, Divides]
  split <;> split <;> omega

theorem w_chart2_le (p q : Exp) : w (chart2 p) (chart2 q) ≤ w p q := by
  obtain ⟨a, b⟩ := p; obtain ⟨c, d⟩ := q
  simp only [w, chart2, Divides]
  split <;> split <;> omega

theorem w_chart1_lt {p q : Exp} (h : ¬ (Divides p q ∨ Divides q p)) :
    w (chart1 p) (chart1 q) < w p q := by
  obtain ⟨a, b⟩ := p; obtain ⟨c, d⟩ := q
  simp only [w, chart1, Divides] at h ⊢
  split <;> omega

theorem w_chart2_lt {p q : Exp} (h : ¬ (Divides p q ∨ Divides q p)) :
    w (chart2 p) (chart2 q) < w p q := by
  obtain ⟨a, b⟩ := p; obtain ⟨c, d⟩ := q
  simp only [w, chart2, Divides] at h ⊢
  split <;> omega

/-! ### The measure drops strictly in both charts -/

theorem mu_map_chart1_lt {l : List Exp}
    (h : ∃ p ∈ l, ∃ q ∈ l, ¬ (Divides p q ∨ Divides q p)) : mu (l.map chart1) < mu l := by
  obtain ⟨p₀, hp₀, q₀, hq₀, hpq⟩ := h
  have hsum : mu (l.map chart1)
      = sumL (l.map (fun p => sumL (l.map (fun q => w (chart1 p) (chart1 q))))) := by
    simp only [mu, List.map_map, Function.comp_def]
  rw [hsum]
  refine sumL_map_lt _ _ l (fun p _ => sumL_map_le _ _ l fun q _ => w_chart1_le p q) hp₀ ?_
  exact sumL_map_lt _ _ l (fun q _ => w_chart1_le p₀ q) hq₀ (w_chart1_lt hpq)

theorem mu_map_chart2_lt {l : List Exp}
    (h : ∃ p ∈ l, ∃ q ∈ l, ¬ (Divides p q ∨ Divides q p)) : mu (l.map chart2) < mu l := by
  obtain ⟨p₀, hp₀, q₀, hq₀, hpq⟩ := h
  have hsum : mu (l.map chart2)
      = sumL (l.map (fun p => sumL (l.map (fun q => w (chart2 p) (chart2 q))))) := by
    simp only [mu, List.map_map, Function.comp_def]
  rw [hsum]
  refine sumL_map_lt _ _ l (fun p _ => sumL_map_le _ _ l fun q _ => w_chart2_le p q) hp₀ ?_
  exact sumL_map_lt _ _ l (fun q _ => w_chart2_le p₀ q) hq₀ (w_chart2_lt hpq)

/-! ### A nonempty ideal with no incomparable pair is principal -/

theorem exists_min_weight (l : List Exp) (hl : l ≠ []) :
    ∃ p ∈ l, ∀ q ∈ l, p.1 + p.2 ≤ q.1 + q.2 := by
  induction l with
  | nil => exact absurd rfl hl
  | cons a t ih =>
    rcases List.eq_nil_or_concat t with rfl | ht
    · exact ⟨a, by simp, by intro q hq; simp at hq; subst hq; omega⟩
    · have htne : t ≠ [] := by
        obtain ⟨u, x, rfl⟩ := ht
        simp
      obtain ⟨p, hp, hmin⟩ := ih htne
      by_cases hle : a.1 + a.2 ≤ p.1 + p.2
      · refine ⟨a, by simp, ?_⟩
        intro q hq
        rcases List.mem_cons.1 hq with rfl | hqt
        · omega
        · have := hmin q hqt
          omega
      · refine ⟨p, by simp [hp], ?_⟩
        intro q hq
        rcases List.mem_cons.1 hq with rfl | hqt
        · omega
        · exact hmin q hqt

theorem exists_incomparable_of_not_isPrincipal {l : List Exp} (hl : l ≠ [])
    (h : ¬ IsPrincipal l) : ∃ p ∈ l, ∃ q ∈ l, ¬ (Divides p q ∨ Divides q p) := by
  by_cases hex : ∃ p ∈ l, ∃ q ∈ l, ¬ (Divides p q ∨ Divides q p)
  · exact hex
  · exfalso
    have hcon : ∀ p ∈ l, ∀ q ∈ l, Divides p q ∨ Divides q p := by
      intro p hp q hq
      by_cases hc : Divides p q ∨ Divides q p
      · exact hc
      · exact absurd ⟨p, hp, q, hq, hc⟩ hex
    obtain ⟨p, hp, hmin⟩ := exists_min_weight l hl
    refine h ⟨p, hp, fun q hq => ?_⟩
    rcases hcon p hp q hq with hle | hle
    · exact hle
    · have hs := hmin q hq
      exact ⟨by omega, by omega⟩

/-! ### The main theorem -/

/-- **Toric principalization in two variables**: the combinatorial core of Hironaka's theorem on
resolution of singularities in characteristic zero.

For every nonempty monomial ideal in two variables — recorded by the list `l` of exponent vectors
of its monomial generators — there is a finite tree of blowups of the origin such that, in every
chart of every leaf of the tree, the transformed ideal is principal, i.e. generated by a single
monomial. -/
theorem hironaka_resolution (l : List Exp) (hl : l ≠ []) : Principalizable l := by
  suffices H : ∀ n : Nat, ∀ l : List Exp, l ≠ [] → mu l ≤ n → Principalizable l from
    H (mu l) l hl (Nat.le_refl _)
  intro n
  induction n with
  | zero =>
    intro l hl hmu
    by_cases hp : IsPrincipal l
    · exact Principalizable.base hp
    · exfalso
      obtain ⟨p₁, hp₁, q₁, hq₁, hpq⟩ := exists_incomparable_of_not_isPrincipal hl hp
      have := mu_map_chart1_lt (l := l) ⟨p₁, hp₁, q₁, hq₁, hpq⟩
      omega
  | succ n ih =>
    intro l hl hmu
    by_cases hp : IsPrincipal l
    · exact Principalizable.base hp
    · obtain ⟨p, hpl, q, hql, hpq⟩ := exists_incomparable_of_not_isPrincipal hl hp
      have h1 := mu_map_chart1_lt (l := l) ⟨p, hpl, q, hql, hpq⟩
      have h2 := mu_map_chart2_lt (l := l) ⟨p, hpl, q, hql, hpq⟩
      have hne1 : l.map chart1 ≠ [] := by
        intro hc
        exact hl (List.map_eq_nil_iff.1 hc)
      have hne2 : l.map chart2 ≠ [] := by
        intro hc
        exact hl (List.map_eq_nil_iff.1 hc)
      exact Principalizable.blowup (ih _ hne1 (by omega)) (ih _ hne2 (by omega))

/-! ### Nontriviality

The maximal ideal `(x, y)` is not principal, so the theorem above really does produce a nonempty
blowup tree in general. -/

theorem not_isPrincipal_maximal_ideal : ¬ IsPrincipal [(1, 0), (0, 1)] := by
  rintro ⟨p, hp, h⟩
  rcases List.mem_cons.1 hp with rfl | hp'
  · have h1 := (h (0, 1) (by simp)).1
    omega
  · rcases List.mem_cons.1 hp' with rfl | hp''
    · have h1 := (h (1, 0) (by simp)).2
      omega
    · simp at hp''

-- The maximal ideal `(x, y)` is nevertheless principalizable.
example : Principalizable [(1, 0), (0, 1)] :=
  hironaka_resolution _ (by simp)

end Math2

