/-
# Goldbach Wheel K 2 727
Category: Brockian Corpus
Target: Brockian.GoldbachWheelK2_727
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib
/-!
# Goldbach Wheel K 2 727
Category: Brockian Corpus
Target: Brockian.GoldbachWheelK2_727
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

set_option maxHeartbeats 4000000

namespace Brockian

/-- `GoldbachK2 n` says that `n` is a sum of two primes (the `K = 2` Goldbach property). -/
def GoldbachK2 (n : ℕ) : Prop := ∃ p q : ℕ, Nat.Prime p ∧ Nat.Prime q ∧ n = p + q

/-- **Goldbach wheel, K = 2, modulus 727.**
Every even natural number `n` with `4 ≤ n ≤ 727` is a sum of two primes.
(The odd endpoint 727 is the wheel modulus; the largest even number covered is 726.) -/
theorem GoldbachWheelK2_727 (n : ℕ) (heven : Even n) (hlow : 4 ≤ n) (hhigh : n ≤ 727) :
    ∃ p q : ℕ, Nat.Prime p ∧ Nat.Prime q ∧ n = p + q := by
  obtain ⟨k, rfl⟩ := heven
  have hk1 : 2 ≤ k := by omega
  have hk2 : k ≤ 363 := by omega
  clear hlow hhigh
  interval_cases k
  exacts [
    ⟨2, 2, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 3, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 5, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 7, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 7, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 11, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 13, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 13, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 17, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 19, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 19, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 23, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 23, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 23, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 29, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 31, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 31, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 31, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 37, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 37, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 41, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 43, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 43, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 47, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 47, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 47, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 53, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 53, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 53, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 59, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 61, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 61, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 61, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 67, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 67, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 71, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 73, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 73, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 73, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 79, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 79, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 83, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 83, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 83, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 89, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 89, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 89, by norm_num, by norm_num, by norm_num⟩,
    ⟨19, 79, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 97, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 97, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 101, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 103, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 103, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 107, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 109, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 109, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 113, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 113, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 113, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 109, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 113, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 113, by norm_num, by norm_num, by norm_num⟩,
    ⟨19, 109, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 127, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 127, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 131, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 131, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 131, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 137, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 139, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 139, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 139, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 137, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 139, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 149, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 151, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 151, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 151, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 157, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 157, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 157, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 163, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 163, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 167, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 167, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 167, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 173, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 173, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 173, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 179, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 181, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 181, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 181, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 179, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 181, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 191, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 193, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 193, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 197, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 199, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 199, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 199, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 197, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 199, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 199, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 211, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 211, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 211, by norm_num, by norm_num, by norm_num⟩,
    ⟨23, 197, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 211, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 211, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 223, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 223, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 227, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 229, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 229, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 233, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 233, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 233, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 239, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 241, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 241, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 241, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 239, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 241, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 251, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 251, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 251, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 257, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 257, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 257, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 263, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 263, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 263, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 269, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 271, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 271, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 271, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 277, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 277, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 281, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 283, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 283, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 283, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 281, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 283, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 293, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 293, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 293, by norm_num, by norm_num, by norm_num⟩,
    ⟨19, 283, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 293, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 293, by norm_num, by norm_num, by norm_num⟩,
    ⟨31, 277, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 307, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 307, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 311, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 313, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 313, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 317, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 317, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 317, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 313, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 317, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 317, by norm_num, by norm_num, by norm_num⟩,
    ⟨19, 313, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 331, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 331, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 331, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 337, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 337, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 337, by norm_num, by norm_num, by norm_num⟩,
    ⟨29, 317, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 337, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 347, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 349, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 349, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 353, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 353, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 353, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 359, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 359, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 359, by norm_num, by norm_num, by norm_num⟩,
    ⟨19, 349, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 367, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 367, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 367, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 373, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 373, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 373, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 379, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 379, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 383, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 383, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 383, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 389, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 389, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 389, by norm_num, by norm_num, by norm_num⟩,
    ⟨19, 379, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 397, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 397, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 401, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 401, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 401, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 397, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 409, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 409, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 409, by norm_num, by norm_num, by norm_num⟩,
    ⟨17, 401, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 409, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 419, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 421, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 421, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 421, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 419, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 421, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 431, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 433, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 433, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 433, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 439, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 439, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 443, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 443, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 443, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 449, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 449, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 449, by norm_num, by norm_num, by norm_num⟩,
    ⟨19, 439, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 457, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 457, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 461, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 463, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 463, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 467, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 467, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 467, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 463, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 467, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 467, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 479, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 479, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 479, by norm_num, by norm_num, by norm_num⟩,
    ⟨31, 457, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 487, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 487, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 491, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 491, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 491, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 487, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 499, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 499, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 503, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 503, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 503, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 509, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 509, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 509, by norm_num, by norm_num, by norm_num⟩,
    ⟨19, 499, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 509, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 509, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 521, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 523, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 523, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 523, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 521, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 523, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 523, by norm_num, by norm_num, by norm_num⟩,
    ⟨17, 521, by norm_num, by norm_num, by norm_num⟩,
    ⟨17, 523, by norm_num, by norm_num, by norm_num⟩,
    ⟨19, 523, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 541, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 541, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 541, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 547, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 547, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 547, by norm_num, by norm_num, by norm_num⟩,
    ⟨47, 509, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 547, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 557, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 557, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 557, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 563, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 563, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 563, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 569, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 571, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 571, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 571, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 577, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 577, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 577, by norm_num, by norm_num, by norm_num⟩,
    ⟨17, 569, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 577, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 587, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 587, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 587, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 593, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 593, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 593, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 599, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 601, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 601, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 601, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 607, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 607, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 607, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 613, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 613, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 617, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 619, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 619, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 619, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 617, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 619, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 619, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 631, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 631, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 631, by norm_num, by norm_num, by norm_num⟩,
    ⟨23, 617, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 631, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 641, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 643, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 643, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 647, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 647, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 647, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 653, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 653, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 653, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 659, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 661, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 661, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 661, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 659, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 661, by norm_num, by norm_num, by norm_num⟩,
    ⟨13, 661, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 673, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 673, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 677, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 677, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 677, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 683, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 683, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 683, by norm_num, by norm_num, by norm_num⟩,
    ⟨19, 673, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 691, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 691, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 691, by norm_num, by norm_num, by norm_num⟩,
    ⟨17, 683, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 691, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 701, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 701, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 701, by norm_num, by norm_num, by norm_num⟩,
    ⟨19, 691, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 709, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 709, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 709, by norm_num, by norm_num, by norm_num⟩,
    ⟨17, 701, by norm_num, by norm_num, by norm_num⟩,
    ⟨11, 709, by norm_num, by norm_num, by norm_num⟩,
    ⟨3, 719, by norm_num, by norm_num, by norm_num⟩,
    ⟨5, 719, by norm_num, by norm_num, by norm_num⟩,
    ⟨7, 719, by norm_num, by norm_num, by norm_num⟩]


/-- The wheel form of the statement: the `K = 2` Goldbach property holds for every even
number in the wheel window `[4, 727]` determined by the modulus 727. -/
theorem goldbachK2_of_le_727 (n : ℕ) (heven : Even n) (hlow : 4 ≤ n) (hhigh : n ≤ 727) :
    GoldbachK2 n :=
  GoldbachWheelK2_727 n heven hlow hhigh

end Brockian

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

