import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open MulAction

namespace Chem

attribute [local instance] arrowAction

variable {G P C : Type*} [Group G] [MulAction G P]

/-- The subgroup of symmetries that leave a given substitution pattern (colouring) `f`
unchanged pointwise, i.e. `f (h • p) = f p` for all positions `p`. -/
def invariance (f : P → C) : Subgroup G where
  carrier := {h : G | ∀ p : P, f (h • p) = f p}
  mul_mem' := by
    intro a b ha hb p
    simp only [Set.mem_setOf_eq] at ha hb
    rw [mul_smul, ha, hb]
  one_mem' := by intro p; simp
  inv_mem' := by
    intro a ha p
    simp only [Set.mem_setOf_eq] at ha ⊢
    have := ha (a⁻¹ • p)
    rw [smul_inv_smul] at this
    exact this.symm

lemma mem_invariance_iff (f : P → C) (h : G) :
    h ∈ (invariance f : Subgroup G) ↔ ∀ p : P, f (h • p) = f p := Iff.rfl

/-- The number of cycles (orbits of the cyclic group generated by `g`) of a symmetry `g`
acting on the skeleton positions `P`.  This is the exponent occurring in the cycle index. -/
noncomputable def cycleCount (P : Type*) [MulAction G P] (g : G) : ℕ :=
  Nat.card (orbitRel.Quotient (Subgroup.zpowers g) P)

/-- The identity symmetry has exactly one cycle per position. -/
lemma cycleCount_one : cycleCount P (1 : G) = Nat.card P := by
  refine Nat.card_congr ?_
  refine Equiv.ofBijective (Quotient.lift id ?_) ⟨?_, ?_⟩
  · intro a b hab
    obtain ⟨h, rfl⟩ := hab
    obtain ⟨k, hk⟩ := h.2
    have hh : (h : G) = 1 := by simpa using hk.symm
    show (h : G) • b = b
    rw [hh, one_smul]
  · intro x y hxy
    induction x using Quotient.inductionOn with
    | h a =>
      induction y using Quotient.inductionOn with
      | h b =>
        have hab : a = b := hxy
        rw [hab]
  · intro p
    exact ⟨Quotient.mk _ p, rfl⟩

/-- Substitution patterns fixed by a symmetry `g` are exactly the colourings that are constant
on the cycles of `g`, so they correspond to functions on the set of cycles. -/
noncomputable def fixedByEquivCycleFunctions (g : G) :
    (fixedBy (P → C) g) ≃ (orbitRel.Quotient (Subgroup.zpowers g) P → C) where
  toFun := fun f => by
    refine Quotient.lift f.1 ?_
    intro p q hpq
    obtain ⟨h, rfl⟩ := (orbitRel_apply.mp hpq)
    have hg : g ∈ (invariance f.1 : Subgroup G) := by
      intro p
      have h1 : f.1 (g⁻¹ • (g • p)) = f.1 (g • p) := congrFun f.2 (g • p)
      rw [inv_smul_smul] at h1
      exact h1.symm
    have : (h : G) ∈ (invariance f.1 : Subgroup G) := by
      have hle : Subgroup.zpowers g ≤ invariance f.1 := by
        rw [Subgroup.zpowers_le]
        exact hg
      exact hle h.2
    exact this q
  invFun := fun F => by
    refine ⟨fun p => F (Quotient.mk _ p), ?_⟩
    funext p
    show F (Quotient.mk _ (g⁻¹ • p)) = F (Quotient.mk _ p)
    have hq : (Quotient.mk _ (g⁻¹ • p) : orbitRel.Quotient (Subgroup.zpowers g) P)
        = Quotient.mk _ p := by
      apply Quotient.sound
      show g⁻¹ • p ∈ orbit (Subgroup.zpowers g) p
      exact ⟨⟨g⁻¹, inv_mem (Subgroup.mem_zpowers g)⟩, rfl⟩
    exact congrArg F hq
  left_inv := by intro f; ext p; rfl
  right_inv := by
    intro F
    funext x
    induction x using Quotient.inductionOn with
    | h p => rfl

lemma card_fixedBy_colorings (g : G) [Finite P] :
    Nat.card (fixedBy (P → C) g) = Nat.card C ^ cycleCount P g := by
  rw [Nat.card_congr (fixedByEquivCycleFunctions (C := C) g), cycleCount, Nat.card_fun]

/-- **Pólya / Burnside isomer count.**

For a finite symmetry group `G` acting on the positions `P` of a molecular skeleton, the number
of distinct substitution isomers, i.e. the number of orbits of `G` on the colourings `P → C`
(assigning a substituent from `C` to each position), multiplied by the order of `G`, equals the
sum over the symmetries `g ∈ G` of `|C| ^ (number of cycles of g)`.

Equivalently, the isomer count is the cycle-index average
`(1 / |G|) * ∑_{g ∈ G} |C| ^ c(g)`.

The proof is Burnside's lemma, `MulAction.sum_card_fixedBy_eq_card_orbits_mul_card_group`,
combined with the identification of the colourings fixed by `g` with the functions on the
cycles of `g`. -/
theorem polya_isomer_count [Fintype G] [Finite P] [Finite C] :
    Nat.card (orbitRel.Quotient G (P → C)) * Nat.card G
      = ∑ g : G, Nat.card C ^ cycleCount P g := by
  classical
  have hfin : ∀ g : G, Fintype (fixedBy (P → C) g) := fun g => Fintype.ofFinite _
  letI := hfin
  letI : Fintype (orbitRel.Quotient G (P → C)) := Fintype.ofFinite _
  have burnside := MulAction.sum_card_fixedBy_eq_card_orbits_mul_card_group G (P → C)
  rw [Nat.card_eq_fintype_card (α := orbitRel.Quotient G (P → C)),
    Nat.card_eq_fintype_card (α := G), ← burnside]
  refine Finset.sum_congr rfl ?_
  intro g _
  rw [← Nat.card_eq_fintype_card, card_fixedBy_colorings]

/-- The cycle-index (Burnside average) form of the isomer count: the number of substitution
isomers is the average, over the symmetry group, of `|C| ^ (number of cycles)`. -/
theorem polya_isomer_count_eq_average [Fintype G] [Finite P] [Finite C] :
    Nat.card (orbitRel.Quotient G (P → C))
      = (∑ g : G, Nat.card C ^ cycleCount P g) / Nat.card G := by
  have hG : 0 < Nat.card G := Nat.card_pos
  rw [← polya_isomer_count (P := P) (C := C), Nat.mul_div_cancel _ hG]

end Chem

