/-
# Iit Phi Partition
Category: Frontier Mind
Target: Frontier.iit_phi_partition
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Iit Phi Partition
Category: Frontier Mind
Target: Frontier.iit_phi_partition
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- A discrete (binary-node) dynamical system in the style of Integrated Information
Theory: a finite set `V` of nodes, each node `v` carrying a stochastic mechanism
`k v s : Bool → ℝ` giving the probability distribution of its next state given the
current global state `s : V → Bool`. -/
structure IITSystem (V : Type*) [Fintype V] where
  /-- `k v s b` is the probability that node `v` takes value `b` at the next step,
  given the current global state `s`. -/
  k : V → (V → Bool) → Bool → ℝ
  k_nonneg : ∀ v s b, 0 ≤ k v s b
  k_sum : ∀ v s, k v s true + k v s false = 1

/-- The transition probability matrix of the system: nodes update independently
(conditionally on the current global state), so the probability of moving from state
`s` to state `t` is the product of the individual node probabilities. -/
def tpm (S : IITSystem V) (s t : V → Bool) : ℝ := ∏ v : V, S.k v s (t v)

/-- The state that agrees with `s` on `A` and with the "noise" state `t` off `A`.
This implements the IIT operation of injecting independent noise on the connections
that cross a partition. -/
def noiseOutside (A : Finset V) (s t : V → Bool) : V → Bool :=
  fun u => if u ∈ A then s u else t u

/-- The mechanism of node `v` after all its incoming connections from outside `A` have
been cut, i.e. replaced by uniform independent noise: one averages the mechanism over
all states of the nodes outside `A`. -/
noncomputable def cutKernel (S : IITSystem V) (A : Finset V) (v : V) (s : V → Bool) (b : Bool) : ℝ :=
  (∑ t : V → Bool, S.k v (noiseOutside A s t) b) / (Fintype.card (V → Bool) : ℝ)

/-- The transition probability matrix of the system cut along the bipartition
`(A, Aᶜ)`: each node only "sees" the current state of its own part, the other part
being replaced by noise. -/
noncomputable def cutTpm (S : IITSystem V) (A : Finset V) (s t : V → Bool) : ℝ :=
  ∏ v : V, if v ∈ A then cutKernel S A v s (t v) else cutKernel S Aᶜ v s (t v)

/-- The effective information generated by the system in state `s` relative to the
bipartition `(A, Aᶜ)`: the distance (here the `L¹` / total-variation-type distance)
between the actual next-state repertoire and the repertoire of the cut system. -/
noncomputable def effectiveInformation (S : IITSystem V) (A : Finset V) (s : V → Bool) : ℝ :=
  ∑ t : V → Bool, |tpm S s t - cutTpm S A s t|

/-- Integrated information `Φ`: the effective information minimized over all
bipartitions of the system. -/
noncomputable def Phi (S : IITSystem V) (s : V → Bool) : ℝ :=
  sInf {x : ℝ | ∃ A : Finset V, A.Nonempty ∧ A ≠ Finset.univ ∧
    x = effectiveInformation S A s}

/-- The system is disconnected along the bipartition `(A, Aᶜ)`: the mechanism of a node
inside `A` depends only on the current state of `A`, and the mechanism of a node outside
`A` depends only on the current state of `Aᶜ`. -/
def Disconnected (S : IITSystem V) (A : Finset V) : Prop :=
  (∀ v ∈ A, ∀ s s' : V → Bool, (∀ u ∈ A, s u = s' u) → ∀ b, S.k v s b = S.k v s' b) ∧
  (∀ v ∉ A, ∀ s s' : V → Bool, (∀ u ∉ A, s u = s' u) → ∀ b, S.k v s b = S.k v s' b)

section Lemmas

variable {S : IITSystem V} {A : Finset V}

lemma card_state_pos : 0 < (Fintype.card (V → Bool) : ℝ) := by
  exact_mod_cast Fintype.card_pos

/-- Cutting the connections coming from outside `A` does not change the mechanism of a
node `v ∈ A` whose mechanism only depends on `A`. -/
lemma cutKernel_eq_of_indep (v : V)
    (hv : ∀ s s' : V → Bool, (∀ u ∈ A, s u = s' u) → ∀ b, S.k v s b = S.k v s' b)
    (s : V → Bool) (b : Bool) : cutKernel S A v s b = S.k v s b := by
  have hconst : ∀ t : V → Bool, S.k v (noiseOutside A s t) b = S.k v s b := by
    intro t
    refine hv _ _ ?_ b
    intro u hu
    simp [noiseOutside, hu]
  unfold cutKernel
  rw [Finset.sum_congr rfl (fun t _ => hconst t), Finset.sum_const, Finset.card_univ,
    nsmul_eq_mul]
  field_simp

/-- The complementary statement: cutting the connections coming from `A` does not change
the mechanism of a node `v ∉ A` whose mechanism only depends on `Aᶜ`. -/
lemma cutKernel_compl_eq_of_indep (v : V)
    (hv : ∀ s s' : V → Bool, (∀ u ∉ A, s u = s' u) → ∀ b, S.k v s b = S.k v s' b)
    (s : V → Bool) (b : Bool) : cutKernel S Aᶜ v s b = S.k v s b := by
  refine cutKernel_eq_of_indep (A := Aᶜ) v ?_ s b
  intro s₁ s₂ h b'
  exact hv s₁ s₂ (fun u hu => h u (by simpa using hu)) b'

/-- For a system disconnected along `(A, Aᶜ)`, the cut transition matrix coincides with
the actual transition matrix. -/
lemma cutTpm_eq_tpm (h : Disconnected S A) (s t : V → Bool) :
    cutTpm S A s t = tpm S s t := by
  unfold cutTpm tpm
  refine Finset.prod_congr rfl ?_
  intro v _
  by_cases hv : v ∈ A
  · simp only [if_pos hv]
    exact cutKernel_eq_of_indep v (h.1 v hv) s (t v)
  · simp only [if_neg hv]
    exact cutKernel_compl_eq_of_indep v (h.2 v hv) s (t v)

/-- Effective information is nonnegative. -/
lemma effectiveInformation_nonneg (S : IITSystem V) (A : Finset V) (s : V → Bool) :
    0 ≤ effectiveInformation S A s :=
  Finset.sum_nonneg fun _ _ => abs_nonneg _

/-- A disconnected bipartition carries zero effective information. -/
lemma effectiveInformation_eq_zero_of_disconnected (h : Disconnected S A) (s : V → Bool) :
    effectiveInformation S A s = 0 := by
  unfold effectiveInformation
  refine Finset.sum_eq_zero ?_
  intro t _
  rw [cutTpm_eq_tpm h s t, sub_self, abs_zero]

end Lemmas

/-- **Integrated information vanishes for a disconnected system.**

Given a finite binary-node stochastic system `S` and a bipartition `(A, Aᶜ)` into two
nonempty parts such that no node's mechanism depends on the other part, the integrated
information `Φ` (effective information minimized over all bipartitions) is zero. -/
theorem iit_phi_partition (S : IITSystem V) (A : Finset V)
    (hA : A.Nonempty) (hA' : A ≠ Finset.univ) (hdisc : Disconnected S A)
    (s : V → Bool) : Phi S s = 0 := by
  set T : Set ℝ := {x : ℝ | ∃ B : Finset V, B.Nonempty ∧ B ≠ Finset.univ ∧
    x = effectiveInformation S B s} with hT
  have hmem : (0 : ℝ) ∈ T := by
    refine ⟨A, hA, hA', ?_⟩
    exact (effectiveInformation_eq_zero_of_disconnected hdisc s).symm
  have hlb : ∀ x ∈ T, (0 : ℝ) ≤ x := by
    rintro x ⟨B, -, -, rfl⟩
    exact effectiveInformation_nonneg S B s
  refine le_antisymm ?_ ?_
  · exact csInf_le ⟨0, fun x hx => hlb x hx⟩ hmem
  · exact le_csInf ⟨0, hmem⟩ hlb

/-- Sanity check: the hypotheses of `iit_phi_partition` are satisfiable, so the theorem
is not vacuous. Take two nodes (indexed by `Bool`), each of which deterministically
copies its own current state; this system is disconnected along the bipartition
`({true}, {false})`. -/
example : ∃ (S : IITSystem Bool) (A : Finset Bool),
    A.Nonempty ∧ A ≠ Finset.univ ∧ Disconnected S A := by
  refine ⟨⟨fun v s b => if b = s v then 1 else 0, ?_, ?_⟩, {true}, ⟨true, by simp⟩, ?_, ?_, ?_⟩
  · intro v s b; positivity
  · intro v s; cases h : s v <;> simp [h]
  · intro hcontra
    have : (false : Bool) ∈ ({true} : Finset Bool) := by rw [hcontra]; simp
    simp at this
  · intro v hv s s' hs b
    simp only [Finset.mem_singleton] at hv
    simp only [hs v (by simp [hv])]
  · intro v hv s s' hs b
    simp only [hs v hv]

end Frontier

