/-
# Higgs Mass Toy
Category: Frontier Physics
Target: Frontier.higgs_mass_toy
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Higgs Mass Toy
Category: Frontier Physics
Target: Frontier.higgs_mass_toy
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Frontier

/-- The (real, radial) Higgs potential of the abelian Higgs toy model:
`V(φ) = -μ² φ² + λ φ⁴`, with quartic coupling `lam > 0`. -/
noncomputable def higgsPotential (mu2 lam φ : ℝ) : ℝ := -mu2 * φ ^ 2 + lam * φ ^ 4

/-- The vacuum expectation value of the radial Higgs field: `√(μ²/(2λ))` in the broken
phase `μ² > 0`, and `0` in the symmetric phase `μ² ≤ 0`. -/
noncomputable def vev (mu2 lam : ℝ) : ℝ :=
  if 0 < mu2 then Real.sqrt (mu2 / (2 * lam)) else 0

/-- The gauge boson mass generated by the Higgs mechanism: `m_A = g · v`. -/
noncomputable def gaugeMass (g mu2 lam : ℝ) : ℝ := g * vev mu2 lam

lemma vev_nonneg (mu2 lam : ℝ) : 0 ≤ vev mu2 lam := by
  unfold vev
  split
  · exact Real.sqrt_nonneg _
  · exact le_rfl

lemma vev_sq (mu2 lam : ℝ) (hlam : 0 < lam) (hmu : 0 < mu2) :
    vev mu2 lam ^ 2 = mu2 / (2 * lam) := by
  unfold vev
  rw [if_pos hmu, Real.sq_sqrt]
  positivity

/-- In the symmetric phase the vev vanishes. -/
lemma vev_of_nonpos (mu2 lam : ℝ) (hmu : mu2 ≤ 0) : vev mu2 lam = 0 := by
  unfold vev
  rw [if_neg (not_lt.mpr hmu)]

/-- The vev minimises the Higgs potential, in both phases. -/
lemma higgsPotential_vev_le (mu2 lam : ℝ) (hlam : 0 < lam) (φ : ℝ) :
    higgsPotential mu2 lam (vev mu2 lam) ≤ higgsPotential mu2 lam φ := by
  rcases le_or_gt mu2 0 with hmu | hmu
  · rw [vev_of_nonpos mu2 lam hmu]
    unfold higgsPotential
    nlinarith [sq_nonneg φ, sq_nonneg (φ ^ 2), mul_nonneg (neg_nonneg.mpr hmu) (sq_nonneg φ)]
  · have hv : vev mu2 lam ^ 2 = mu2 / (2 * lam) := vev_sq mu2 lam hlam hmu
    have hmu2 : mu2 = 2 * lam * vev mu2 lam ^ 2 := by
      rw [hv]; field_simp
    unfold higgsPotential
    nlinarith [sq_nonneg (φ ^ 2 - vev mu2 lam ^ 2), hlam.le]

/-- In the broken phase the gauge boson mass squared is `m_A² = g² μ² / (2λ)`. -/
lemma gaugeMass_sq_of_pos (g mu2 lam : ℝ) (hlam : 0 < lam) (hmu : 0 < mu2) :
    gaugeMass g mu2 lam ^ 2 = g ^ 2 * mu2 / (2 * lam) := by
  rw [gaugeMass, mul_pow, vev_sq mu2 lam hlam hmu]
  ring

/-- **Abelian Higgs toy model.** For positive gauge coupling `g` and quartic coupling `λ`:

* the vacuum expectation value minimises the Higgs potential in either phase,
* the gauge boson acquires a strictly positive mass exactly when the symmetry is
  spontaneously broken, i.e. when `μ² > 0`; in the symmetric phase `μ² ≤ 0` it stays massless,
* and in the broken phase that mass is given by `m_A² = g² μ² / (2λ)`.
-/
theorem higgs_mass_toy (g mu2 lam : ℝ) (hg : 0 < g) (hlam : 0 < lam) :
    (∀ φ : ℝ, higgsPotential mu2 lam (vev mu2 lam) ≤ higgsPotential mu2 lam φ) ∧
      (0 < gaugeMass g mu2 lam ↔ 0 < mu2) ∧
      (mu2 ≤ 0 → gaugeMass g mu2 lam = 0) ∧
      (0 < mu2 → gaugeMass g mu2 lam ^ 2 = g ^ 2 * mu2 / (2 * lam)) := by
  refine ⟨higgsPotential_vev_le mu2 lam hlam, ⟨?_, ?_⟩, ?_, fun hmu =>
    gaugeMass_sq_of_pos g mu2 lam hlam hmu⟩
  · intro h
    by_contra hmu
    rw [not_lt] at hmu
    rw [gaugeMass, vev_of_nonpos mu2 lam hmu, mul_zero] at h
    exact lt_irrefl 0 h
  · intro hmu
    have hv : 0 < vev mu2 lam := by
      unfold vev
      rw [if_pos hmu]
      apply Real.sqrt_pos.mpr
      positivity
    exact mul_pos hg hv
  · intro hmu
    rw [gaugeMass, vev_of_nonpos mu2 lam hmu, mul_zero]

end Frontier

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

