import Mathlib

/-!
# Mod-2 Milnor K-theory of a field

We define, for a field `F` and `n : ℕ`, the group `k^M_n(F) = K^M_n(F)/2`, the `n`-th mod-2
Milnor K-theory group, as the quotient of the free `𝔽₂`-vector space on `n`-tuples of units of
`F` by the submodule generated by

* multiplicativity in each slot: `{…, ab, …} = {…, a, …} + {…, b, …}`, and
* the Steinberg relation: `{a₁, …, aₙ} = 0` whenever `aᵢ + aⱼ = 1` for some `i ≠ j`.

Since the coefficients are `𝔽₂`, this is exactly `K^M_n(F) ⊗ 𝔽₂ = K^M_n(F)/2`.
-/

open scoped Classical

namespace Frontier

universe u

variable (F : Type u) [Field F]

/-- The set of defining relations for mod-2 Milnor K-theory in degree `n`. -/
def MilnorRel (n : ℕ) : Set ((Fin n → Fˣ) →₀ ZMod 2) :=
  {x | ∃ (i : Fin n) (a b : Fˣ) (t : Fin n → Fˣ),
      x = Finsupp.single (Function.update t i (a * b)) 1
            - Finsupp.single (Function.update t i a) 1
            - Finsupp.single (Function.update t i b) 1} ∪
  {x | ∃ (i j : Fin n) (t : Fin n → Fˣ), i ≠ j ∧ ((t i : F) + (t j : F) = 1) ∧
      x = Finsupp.single t 1}

/-- The submodule of relations for mod-2 Milnor K-theory in degree `n`. -/
def milnorRelations (n : ℕ) : Submodule (ZMod 2) ((Fin n → Fˣ) →₀ ZMod 2) :=
  Submodule.span (ZMod 2) (MilnorRel F n)

/-- Mod-2 Milnor K-theory `k^M_n(F) = K^M_n(F)/2` of the field `F` in degree `n`. -/
abbrev MilnorK2 (n : ℕ) := ((Fin n → Fˣ) →₀ ZMod 2) ⧸ milnorRelations F n

variable {F}

/-- The symbol `{a₁, …, aₙ} ∈ k^M_n(F)` attached to an `n`-tuple of units. -/
noncomputable def symbol {n : ℕ} (t : Fin n → Fˣ) : MilnorK2 F n :=
  Submodule.Quotient.mk (Finsupp.single t 1)

/-- Multiplicativity of symbols in each slot. -/
theorem symbol_update_mul {n : ℕ} (i : Fin n) (a b : Fˣ) (t : Fin n → Fˣ) :
    symbol (F := F) (Function.update t i (a * b))
      = symbol (Function.update t i a) + symbol (Function.update t i b) := by
  have hmem : (Finsupp.single (Function.update t i (a * b)) 1
      - Finsupp.single (Function.update t i a) 1
      - Finsupp.single (Function.update t i b) (1 : ZMod 2)) ∈ milnorRelations F n :=
    Submodule.subset_span (Or.inl ⟨i, a, b, t, rfl⟩)
  have := (Submodule.Quotient.mk_eq_zero (milnorRelations F n)).2 hmem
  simp only [symbol]
  have h : (Submodule.Quotient.mk (Finsupp.single (Function.update t i (a * b)) (1 : ZMod 2))
      - Submodule.Quotient.mk (Finsupp.single (Function.update t i a) (1 : ZMod 2))
      - Submodule.Quotient.mk (Finsupp.single (Function.update t i b) (1 : ZMod 2))
      : MilnorK2 F n) = 0 := by
    rw [← Submodule.Quotient.mk_sub, ← Submodule.Quotient.mk_sub]; exact this
  linear_combination (norm := module) h

/-- The Steinberg relation. -/
theorem symbol_steinberg {n : ℕ} (i j : Fin n) (t : Fin n → Fˣ) (hij : i ≠ j)
    (h : (t i : F) + (t j : F) = 1) : symbol (F := F) t = 0 :=
  (Submodule.Quotient.mk_eq_zero _).2 (Submodule.subset_span (Or.inr ⟨i, j, t, hij, h, rfl⟩))

section Degree1

/-- The degree-one symbol `{a} ∈ k^M_1(F)`. -/
noncomputable def symbol₁ (a : Fˣ) : MilnorK2 F 1 := symbol (fun _ => a)

theorem symbol₁_mul (a b : Fˣ) : symbol₁ (F := F) (a * b) = symbol₁ a + symbol₁ b := by
  have h := symbol_update_mul (F := F) (0 : Fin 1) a b (fun _ => a)
  have e : ∀ c : Fˣ, Function.update (fun _ : Fin 1 => a) 0 c = fun _ => c := by
    intro c; funext k; fin_cases k; simp
  simpa [symbol₁, e] using h

theorem symbol₁_one : symbol₁ (F := F) 1 = 0 := by
  have := symbol₁_mul (F := F) 1 1
  simpa using this.symm

theorem add_self_eq_zero_of_mod2 {n : ℕ} (x : MilnorK2 F n) : x + x = 0 := by
  have h : ((2 : ℕ) : ZMod 2) • x = (2 : ℕ) • x := Nat.cast_smul_eq_nsmul _ _ _
  have h0 : ((2 : ℕ) : ZMod 2) = 0 := by decide
  rw [h0, zero_smul, two_nsmul] at h
  exact h.symm

theorem symbol₁_sq (a : Fˣ) : symbol₁ (F := F) (a * a) = 0 := by
  rw [symbol₁_mul]
  exact add_self_eq_zero_of_mod2 _

/-- Every element of `k^M_1(F)` is a symbol. -/
theorem exists_symbol₁ (x : MilnorK2 F 1) : ∃ a : Fˣ, x = symbol₁ a := by
  induction x using Submodule.Quotient.induction_on with
  | H v =>
    classical
    induction v using Finsupp.induction_linear with
    | zero => exact ⟨1, by rw [symbol₁_one]; simp⟩
    | add f g hf hg =>
      obtain ⟨a, ha⟩ := hf
      obtain ⟨b, hb⟩ := hg
      refine ⟨a * b, ?_⟩
      rw [symbol₁_mul, ← ha, ← hb, ← Submodule.Quotient.mk_add]
    | single t c =>
      refine ⟨if c = 0 then 1 else t 0, ?_⟩
      have h2 : c = 0 ∨ c = 1 := by
        revert c; decide
      rcases h2 with rfl | rfl
      · simp [symbol₁_one]
      · have ht : t = fun _ => t 0 := by funext k; fin_cases k; rfl
        simp only [if_neg (one_ne_zero : (1 : ZMod 2) ≠ 0)]
        rw [symbol₁, symbol, ← ht]
end Degree1

end Frontier

import RequestProject.GaloisCohomology
import RequestProject.MilnorK

/-!
# Kummer theory: the degree-one norm residue isomorphism

For a field `F` with `2 ≠ 0` we construct the Kummer character `χ_a : G_F → ℤ/2` attached to a
unit `a` of `F`: it sends `σ` to `0` or `1` according to whether `σ` fixes a chosen square root
of `a` in the separable closure. We show that `a ↦ χ_a` induces an isomorphism

`k^M_1(F) = F^×/(F^×)² ≅ H^1(F, ℤ/2)`,

which is the degree-one case of the Milnor conjecture (the norm residue isomorphism).
-/

open scoped Classical

namespace Frontier

universe u

variable {F : Type u} [Field F]

/-- A chosen square root in the separable closure of (the image of) a unit of `F`;
it is a genuine square root as soon as `2 ≠ 0` in `F`, see `sqrtSep_sq`. -/
noncomputable def sqrtSep (a : Fˣ) : SeparableClosure F :=
  if h : ∃ s : SeparableClosure F, s ^ 2 = algebraMap F (SeparableClosure F) a then h.choose else 0

theorem exists_sqrtSep (hF : (2 : F) ≠ 0) (a : Fˣ) :
    ∃ s : SeparableClosure F, s ^ 2 = algebraMap F (SeparableClosure F) a := by
  have h2 : ((2 : ℕ) : SeparableClosure F) ≠ 0 := by
    intro h
    apply hF
    have h' : algebraMap F (SeparableClosure F) 2 = 0 := by
      rw [map_ofNat]; simpa using h
    exact (map_eq_zero_iff _ (FaithfulSMul.algebraMap_injective F _)).1 h'
  haveI : NeZero ((2 : ℕ) : SeparableClosure F) := ⟨h2⟩
  exact IsSepClosed.exists_pow_nat_eq _ 2

theorem sqrtSep_sq (hF : (2 : F) ≠ 0) (a : Fˣ) :
    (sqrtSep a) ^ 2 = algebraMap F (SeparableClosure F) a := by
  rw [sqrtSep, dif_pos (exists_sqrtSep hF a)]
  exact (exists_sqrtSep hF a).choose_spec

/-- The Kummer character attached to a unit `a` of `F`. -/
noncomputable def kummerChar (a : Fˣ) (σ : GaloisGroup F) : ZMod 2 :=
  if σ (sqrtSep a) = sqrtSep a then 0 else 1

/-- Two square roots of the same element differ by a sign. -/
theorem eq_or_eq_neg_of_sq_eq_sq {L : Type*} [Field L] {s t : L} (h : s ^ 2 = t ^ 2) :
    s = t ∨ s = -t := by
  have : (s - t) * (s + t) = 0 := by ring_nf; linear_combination h
  rcases mul_eq_zero.1 this with h1 | h1
  · exact Or.inl (sub_eq_zero.1 h1)
  · exact Or.inr (by linear_combination h1)

/-- `2 ≠ 0` in the separable closure. -/
theorem two_ne_zero_sep (hF : (2 : F) ≠ 0) : (2 : SeparableClosure F) ≠ 0 := by
  intro h
  apply hF
  have h' : algebraMap F (SeparableClosure F) 2 = 0 := by rw [map_ofNat]; exact h
  exact (map_eq_zero_iff _ (FaithfulSMul.algebraMap_injective F _)).1 h'

theorem neg_ne_self_sep (hF : (2 : F) ≠ 0) {x : SeparableClosure F} (hx : x ≠ 0) : -x ≠ x := by
  intro h
  apply hx
  have h2 : (2 : SeparableClosure F) * x = 0 := by linear_combination -h
  rcases mul_eq_zero.1 h2 with h1 | h1
  · exact absurd h1 (two_ne_zero_sep hF)
  · exact h1

theorem sqrtSep_ne_zero (hF : (2 : F) ≠ 0) (a : Fˣ) : sqrtSep (F := F) a ≠ 0 := by
  intro h
  have hh := sqrtSep_sq hF a
  rw [h] at hh
  have h0 : algebraMap F (SeparableClosure F) (a : F) = 0 := by rw [← hh]; ring
  exact a.ne_zero ((map_eq_zero_iff _ (FaithfulSMul.algebraMap_injective F _)).1 h0)

/-- A Galois automorphism fixes a square root up to sign. -/
theorem map_sqrtSep (hF : (2 : F) ≠ 0) (a : Fˣ) (σ : GaloisGroup F) :
    σ (sqrtSep a) = sqrtSep a ∨ σ (sqrtSep a) = -sqrtSep a :=
  eq_or_eq_neg_of_sq_eq_sq (by rw [← map_pow, sqrtSep_sq hF, AlgEquiv.commutes])

/-- The Kummer character can be computed with any square root of `a`. -/
theorem kummerChar_eq_of_sq (hF : (2 : F) ≠ 0) (a : Fˣ) (s : SeparableClosure F)
    (hs : s ^ 2 = algebraMap F (SeparableClosure F) a) (σ : GaloisGroup F) :
    kummerChar a σ = if σ s = s then 0 else 1 := by
  have hsq : sqrtSep a ^ 2 = s ^ 2 := by rw [sqrtSep_sq hF, hs]
  rcases eq_or_eq_neg_of_sq_eq_sq hsq with h1 | h1
  · rw [kummerChar, h1]
  · simp only [kummerChar, h1, map_neg, neg_inj]

/-- The stabiliser of an element of the separable closure is open. -/
theorem isOpen_stabilizer (s : SeparableClosure F) :
    IsOpen {σ : GaloisGroup F | σ s = s} := by
  have hint : IsIntegral F s := Algebra.IsIntegral.isIntegral s
  haveI : FiniteDimensional F
      (IntermediateField.adjoin F {s} : IntermediateField F (SeparableClosure F)) :=
    IntermediateField.adjoin.finiteDimensional hint
  have hopen : IsOpen ((IntermediateField.adjoin F {s} :
      IntermediateField F (SeparableClosure F)).fixingSubgroup : Set (GaloisGroup F)) :=
    IntermediateField.fixingSubgroup_isOpen _
  have hle : (IntermediateField.adjoin F {s} :
      IntermediateField F (SeparableClosure F)).fixingSubgroup ≤
      MulAction.stabilizer (GaloisGroup F) s := by
    intro σ hσ
    exact (IntermediateField.mem_fixingSubgroup_iff _ σ).1 hσ s
      (IntermediateField.mem_adjoin_simple_self F s)
  exact Subgroup.isOpen_mono hle hopen

/-- The stabiliser of an element of the separable closure is closed. -/
theorem isClosed_stabilizer (s : SeparableClosure F) :
    IsClosed {σ : GaloisGroup F | σ s = s} :=
  Subgroup.isClosed_of_isOpen (MulAction.stabilizer (GaloisGroup F) s) (isOpen_stabilizer s)

theorem kummerChar_isLocallyConstant (a : Fˣ) : IsLocallyConstant (kummerChar (F := F) a) := by
  rw [IsLocallyConstant.iff_isOpen_fiber]
  intro y
  have hy : y = 0 ∨ y = 1 := by revert y; decide
  rcases hy with rfl | rfl
  · have h : (kummerChar (F := F) a) ⁻¹' {0}
        = {σ : GaloisGroup F | σ (sqrtSep a) = sqrtSep a} := by
      ext σ
      simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_setOf_eq, kummerChar]
      by_cases h : σ (sqrtSep a) = sqrtSep a <;> simp [h]
    rw [h]; exact isOpen_stabilizer _
  · have h : (kummerChar (F := F) a) ⁻¹' {1}
        = {σ : GaloisGroup F | σ (sqrtSep a) = sqrtSep a}ᶜ := by
      ext σ
      simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_compl_iff,
        Set.mem_setOf_eq, kummerChar]
      by_cases h : σ (sqrtSep a) = sqrtSep a <;> simp [h]
    rw [h]; exact (isClosed_stabilizer _).isOpen_compl

/-- The Kummer character as a continuous `1`-cochain. -/
noncomputable def kummerCochain (a : Fˣ) : Cochain (GaloisGroup F) 1 :=
  ⟨fun g => kummerChar a (g 0),
    (kummerChar_isLocallyConstant a).comp_continuous (continuous_apply 0)⟩

theorem kummerCochain_apply (a : Fˣ) (g : Fin 1 → GaloisGroup F) :
    kummerCochain a g = kummerChar a (g 0) := rfl

/-- The Kummer character is a homomorphism. -/
theorem kummerChar_hom (hF : (2 : F) ≠ 0) (a : Fˣ) (σ τ : GaloisGroup F) :
    kummerChar a (σ * τ) = kummerChar a σ + kummerChar a τ := by
  have hmul : (σ * τ) (sqrtSep a) = σ (τ (sqrtSep a)) := rfl
  rcases map_sqrtSep hF a σ with ha | ha <;> rcases map_sqrtSep hF a τ with hb | hb <;>
    simp only [kummerChar, hmul, hb, ha, map_neg]
  · simp
  · rw [if_neg (fun h => neg_ne_self_sep hF (sqrtSep_ne_zero hF a) (by linear_combination h))]
    simp
  · simp
  · rw [if_pos (neg_neg _)]
    simp [if_neg (neg_ne_self_sep hF (sqrtSep_ne_zero hF a))]
    decide

/-- The Kummer cochain of a unit is a `1`-cocycle. -/
theorem kummerCochain_mem_ker (hF : (2 : F) ≠ 0) (a : Fˣ) :
    kummerCochain a ∈ LinearMap.ker (dCochain (GaloisGroup F) 1) :=
  (mem_ker_dCochain_one_iff _).2 fun σ τ => kummerChar_hom hF a σ τ

/-- Multiplicativity of the Kummer character in `a`. -/
theorem kummerChar_mul (hF : (2 : F) ≠ 0) (a b : Fˣ) (σ : GaloisGroup F) :
    kummerChar (a * b) σ = kummerChar a σ + kummerChar b σ := by
  have hst : (sqrtSep (F := F) a * sqrtSep b) ^ 2
      = algebraMap F (SeparableClosure F) ((a * b : Fˣ) : F) := by
    rw [mul_pow, sqrtSep_sq hF, sqrtSep_sq hF, Units.val_mul, map_mul]
  have hne : sqrtSep (F := F) a * sqrtSep b ≠ 0 :=
    mul_ne_zero (sqrtSep_ne_zero hF a) (sqrtSep_ne_zero hF b)
  rw [kummerChar_eq_of_sq hF _ _ hst]
  rcases map_sqrtSep hF a σ with ha | ha <;> rcases map_sqrtSep hF b σ with hb | hb <;>
    simp only [kummerChar, map_mul, ha, hb]
  · simp
  · rw [if_neg (fun h => neg_ne_self_sep hF hne (by linear_combination h))]
    simp [if_neg (neg_ne_self_sep hF (sqrtSep_ne_zero hF b))]
  · rw [if_neg (fun h => neg_ne_self_sep hF hne (by linear_combination h))]
    simp [if_neg (neg_ne_self_sep hF (sqrtSep_ne_zero hF a))]
  · rw [if_pos (by rw [neg_mul_neg])]
    simp [if_neg (neg_ne_self_sep hF (sqrtSep_ne_zero hF a)),
      if_neg (neg_ne_self_sep hF (sqrtSep_ne_zero hF b))]
    decide

/-- The Kummer character of `a` is trivial exactly when `a` is a square in `F`. -/
theorem kummerChar_eq_zero_iff (hF : (2 : F) ≠ 0) (a : Fˣ) :
    (∀ σ : GaloisGroup F, kummerChar a σ = 0) ↔ ∃ c : Fˣ, a = c * c := by
  constructor
  · intro h
    have hfix : ∀ σ : GaloisGroup F, σ (sqrtSep a) = sqrtSep a := by
      intro σ
      by_contra hc
      have hz := h σ
      rw [kummerChar, if_neg hc] at hz
      exact one_ne_zero hz
    obtain ⟨c, hc⟩ : sqrtSep (F := F) a ∈ Set.range (algebraMap F (SeparableClosure F)) :=
      (InfiniteGalois.mem_range_algebraMap_iff_fixed _).2 hfix
    have hc2 : algebraMap F (SeparableClosure F) (c ^ 2)
        = algebraMap F (SeparableClosure F) a := by
      rw [map_pow, hc, sqrtSep_sq hF]
    have hc3 : c ^ 2 = (a : F) := FaithfulSMul.algebraMap_injective F _ hc2
    have hcne : c ≠ 0 := by
      intro h0
      rw [h0] at hc3
      simp at hc3
      exact a.ne_zero hc3.symm
    refine ⟨Units.mk0 c hcne, ?_⟩
    ext
    simp [← hc3]
    ring
  · rintro ⟨c, rfl⟩ σ
    have hs : (algebraMap F (SeparableClosure F) (c : F)) ^ 2
        = algebraMap F (SeparableClosure F) ((c * c : Fˣ) : F) := by
      rw [← map_pow, Units.val_mul]; ring_nf
    rw [kummerChar_eq_of_sq hF _ _ hs, if_pos (AlgEquiv.commutes σ _)]

/-- Surjectivity of the Kummer map: every continuous homomorphism `G_F → ℤ/2` is a Kummer
character. -/
theorem exists_kummerChar_eq (hF : (2 : F) ≠ 0) (f : Cochain (GaloisGroup F) 1)
    (hf : f ∈ LinearMap.ker (dCochain (GaloisGroup F) 1)) :
    ∃ a : Fˣ, kummerCochain a = f := by
  set chi : GaloisGroup F → ZMod 2 := fun σ => f (fun _ => σ) with hchi
  have hhom : ∀ σ τ, chi (σ * τ) = chi σ + chi τ := (mem_ker_dCochain_one_iff f).1 hf
  have hone : chi 1 = 0 := by
    have h := hhom 1 1
    rw [mul_one] at h
    have h2 : ∀ x : ZMod 2, x = x + x → x = 0 := by decide
    exact h2 _ h
  have hinv : ∀ σ, chi σ⁻¹ = chi σ := by
    intro σ
    have h := hhom σ σ⁻¹
    rw [mul_inv_cancel, hone] at h
    have h2 : ∀ x y : ZMod 2, 0 = x + y → y = x := by decide
    exact h2 _ _ h
  have hone_of_ne : ∀ x : ZMod 2, x ≠ 0 → x = 1 := by decide
  have hred : ∀ a : Fˣ, (∀ σ, kummerChar a σ = chi σ) → kummerCochain a = f := by
    intro a ha
    ext g
    have hg : (fun _ => g 0) = g := by funext k; fin_cases k; rfl
    rw [kummerCochain_apply, ha (g 0), hchi]
    exact congrArg f hg
  by_cases hzero : ∀ σ : GaloisGroup F, chi σ = 0
  · refine ⟨1, hred 1 ?_⟩
    intro σ
    rw [(kummerChar_eq_zero_iff hF 1).2 ⟨1, (one_mul 1).symm⟩ σ, hzero σ]
  · push_neg at hzero
    obtain ⟨σ₀, hσ₀⟩ := hzero
    have hσ₀' : chi σ₀ = 1 := hone_of_ne _ hσ₀
    let H : Subgroup (GaloisGroup F) :=
      { carrier := {σ | chi σ = 0}
        mul_mem' := by
          intro x y hx hy
          simp only [Set.mem_setOf_eq] at *
          rw [hhom, hx, hy, add_zero]
        one_mem' := hone
        inv_mem' := by
          intro x hx
          simp only [Set.mem_setOf_eq] at *
          rw [hinv, hx] }
    have hHmem : ∀ σ, σ ∈ H ↔ chi σ = 0 := fun _ => Iff.rfl
    have hopen : IsOpen (H : Set (GaloisGroup F)) := by
      have hlc : IsLocallyConstant chi :=
        f.isLocallyConstant.comp_continuous (continuous_pi fun _ => continuous_id)
      exact hlc.isOpen_fiber 0
    have hclosed : IsClosed (H : Set (GaloisGroup F)) := Subgroup.isClosed_of_isOpen H hopen
    have hfix : (IntermediateField.fixedField H).fixingSubgroup = H :=
      InfiniteGalois.fixingSubgroup_fixedField ⟨H, hclosed⟩
    have hex : ∃ x : SeparableClosure F, x ∈ IntermediateField.fixedField H ∧ σ₀ x ≠ x := by
      by_contra hc
      push_neg at hc
      have hmem : σ₀ ∈ (IntermediateField.fixedField H).fixingSubgroup :=
        (IntermediateField.mem_fixingSubgroup_iff _ _).2 fun x hx => hc x hx
      rw [hfix] at hmem
      exact hσ₀ ((hHmem σ₀).1 hmem)
    obtain ⟨x, hxE, hxne⟩ := hex
    have hxfix : ∀ h ∈ H, h x = x := (IntermediateField.mem_fixedField_iff H x).1 hxE
    set y : SeparableClosure F := x - σ₀ x with hy
    have hyne : y ≠ 0 := sub_ne_zero.2 (Ne.symm hxne)
    have hσ₀x : ∀ h ∈ H, h (σ₀ x) = σ₀ x := by
      intro h hh
      have hconj : σ₀⁻¹ * h * σ₀ ∈ H := by
        rw [hHmem] at *
        rw [hhom, hhom, hinv, hh, hσ₀']
        decide
      have hgroup : (h * σ₀) x = (σ₀ * (σ₀⁻¹ * h * σ₀)) x := by group
      calc h (σ₀ x) = (h * σ₀) x := rfl
        _ = (σ₀ * (σ₀⁻¹ * h * σ₀)) x := hgroup
        _ = σ₀ ((σ₀⁻¹ * h * σ₀) x) := rfl
        _ = σ₀ x := by rw [hxfix _ hconj]
    have hHy : ∀ h ∈ H, h y = y := by
      intro h hh
      rw [hy, map_sub, hxfix h hh, hσ₀x h hh]
    have hsq₀ : σ₀ * σ₀ ∈ H := by
      rw [hHmem, hhom, hσ₀']
      decide
    have hσ₀y : σ₀ y = -y := by
      have h1 : (σ₀ * σ₀) x = x := hxfix _ hsq₀
      have h2 : σ₀ y = σ₀ x - (σ₀ * σ₀) x := by rw [hy, map_sub]; rfl
      rw [h2, h1, hy]
      ring
    have hall : ∀ τ : GaloisGroup F, τ y = if chi τ = 0 then y else -y := by
      intro τ
      by_cases h : chi τ = 0
      · rw [if_pos h]
        exact hHy τ ((hHmem τ).2 h)
      · rw [if_neg h]
        have hτ : chi τ = 1 := hone_of_ne _ h
        have hmem : σ₀⁻¹ * τ ∈ H := by
          rw [hHmem, hhom, hinv, hσ₀', hτ]
          decide
        have hcompose : τ y = σ₀ ((σ₀⁻¹ * τ) y) := by
          have h3 : (σ₀ * (σ₀⁻¹ * τ)) y = σ₀ ((σ₀⁻¹ * τ) y) := rfl
          rw [← h3]
          congr 1
          group
        rw [hcompose, hHy _ hmem, hσ₀y]
    have hyfix : ∀ τ : GaloisGroup F, τ (y ^ 2) = y ^ 2 := by
      intro τ
      rw [map_pow, hall τ]
      by_cases h : chi τ = 0 <;> simp [h]
    obtain ⟨c, hc⟩ : y ^ 2 ∈ Set.range (algebraMap F (SeparableClosure F)) :=
      (InfiniteGalois.mem_range_algebraMap_iff_fixed _).2 hyfix
    have hcne : c ≠ 0 := by
      intro h0
      rw [h0, map_zero] at hc
      exact (pow_ne_zero 2 hyne) hc.symm
    refine ⟨Units.mk0 c hcne, hred _ ?_⟩
    intro τ
    have hroot : y ^ 2 = algebraMap F (SeparableClosure F) ((Units.mk0 c hcne : Fˣ) : F) := hc.symm
    rw [kummerChar_eq_of_sq hF _ _ hroot]
    by_cases h : chi τ = 0
    · rw [if_pos (by rw [hall τ, if_pos h]), h]
    · rw [if_neg (by rw [hall τ, if_neg h]; exact neg_ne_self_sep hF hyne),
        hone_of_ne _ h]

end Frontier

import Mathlib
import RequestProject.MilnorK
import RequestProject.GaloisCohomology
import RequestProject.Kummer

/-!
# Voevodsky Milnor
Category: Frontier — Fields Medal Work
Target: Frontier.voevodsky_milnor
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

/-!
## Overview

The Milnor conjecture, proved by Voevodsky, asserts that for a field `F` of characteristic `≠ 2`
the *norm residue map*

`k^M_n(F) = K^M_n(F)/2 ⟶ H^n(F, ℤ/2)`,  `{a₁, …, aₙ} ↦ χ_{a₁} ∪ ⋯ ∪ χ_{aₙ}`

is an isomorphism for every `n`, where `χ_a ∈ H^1(F, ℤ/2)` is the Kummer character of `a` and
`H^*(F, ℤ/2)` denotes continuous (Galois) cohomology of the absolute Galois group with trivial
`ℤ/2`-coefficients.

This file formalizes that statement (`Frontier.NormResidueIso`, `Frontier.MilnorConjecture`) in
terms of

* `Frontier.MilnorK2 F n`, mod-2 Milnor K-theory, defined by generators and relations
  (`RequestProject/MilnorK.lean`), and
* `Frontier.GaloisCohomologyMod2 F n`, continuous mod-2 cochain cohomology of `Gal(F^sep/F)`
  (`RequestProject/GaloisCohomology.lean`),

the cup product of Kummer characters being written out explicitly at the level of inhomogeneous
cochains as `Frontier.symbolCochain`.

The main theorem `Frontier.voevodsky_milnor` proves the base cases `n = 0` and `n = 1` of this
statement for every field with `2 ≠ 0`; the degree-one case is Kummer theory, i.e. the norm
residue isomorphism `F^×/(F^×)² ≅ H^1(F, ℤ/2)`.
-/

open scoped Classical

set_option maxHeartbeats 1000000
set_option synthInstance.maxHeartbeats 400000

namespace Frontier

universe u

variable {F : Type u} [Field F]

/-- The Kummer character of a unit, as a locally constant function on the absolute Galois
group. -/
noncomputable def kummerLC (a : Fˣ) : LocallyConstant (GaloisGroup F) (ZMod 2) :=
  ⟨kummerChar a, kummerChar_isLocallyConstant a⟩

/-- The inhomogeneous `n`-cochain representing the cup product
`χ_{a₁} ∪ ⋯ ∪ χ_{aₙ}` of the Kummer characters of an `n`-tuple of units. -/
noncomputable def symbolCochain {n : ℕ} (t : Fin n → Fˣ) : Cochain (GaloisGroup F) n :=
  ∏ i : Fin n, LocallyConstant.comap ⟨fun g => g i, continuous_apply i⟩ (kummerLC (t i))

theorem symbolCochain_apply {n : ℕ} (t : Fin n → Fˣ) (g : Fin n → GaloisGroup F) :
    symbolCochain t g = ∏ i : Fin n, kummerChar (t i) (g i) := by
  rw [symbolCochain]
  exact map_prod (LocallyConstant.evalRingHom g) _ Finset.univ

/-- **The Milnor conjecture in degree `n` for the field `F`** (Voevodsky's theorem): there is a
map from mod-2 Milnor K-theory to mod-2 Galois cohomology sending a symbol `{a₁, …, aₙ}` to the
cup product `χ_{a₁} ∪ ⋯ ∪ χ_{aₙ}` of the corresponding Kummer classes, and it is bijective. -/
def NormResidueIso (F : Type u) [Field F] (n : ℕ) : Prop :=
  ∃ nr : MilnorK2 F n →ₗ[ZMod 2] GaloisCohomologyMod2 F n,
    Function.Bijective nr ∧
      ∀ t : Fin n → Fˣ, ∃ h : symbolCochain t ∈ LinearMap.ker (dCochain (GaloisGroup F) n),
        nr (symbol t) = Submodule.Quotient.mk ⟨symbolCochain t, h⟩

/-- **The Milnor conjecture** (Voevodsky's theorem): for every field of characteristic different
from `2` the norm residue map `k^M_n(F) → H^n(F, ℤ/2)` is an isomorphism in every degree. -/
def MilnorConjecture : Prop :=
  ∀ (F : Type u) [Field F], (2 : F) ≠ 0 → ∀ n : ℕ, NormResidueIso F n

/-! ### The norm residue map in degrees `0` and `1` -/

/-- The constant cochain `1` is a `0`-cocycle. -/
theorem one_mem_ker_dCochain_zero :
    (1 : Cochain (GaloisGroup F) 0) ∈ LinearMap.ker (dCochain (GaloisGroup F) 0) := by
  rw [ker_dCochain_zero]; trivial

/-- The degree-zero norm residue map, at the level of cochains. -/
noncomputable def normResidueCochain₀ (F : Type u) [Field F] :
    ((Fin 0 → Fˣ) →₀ ZMod 2) →ₗ[ZMod 2] LinearMap.ker (dCochain (GaloisGroup F) 0) :=
  Finsupp.linearCombination (ZMod 2)
    (fun _ : Fin 0 → Fˣ => (⟨1, one_mem_ker_dCochain_zero⟩ :
      LinearMap.ker (dCochain (GaloisGroup F) 0)))

/-- The degree-zero norm residue map `k^M_0(F) → H^0(F, ℤ/2)`. -/
noncomputable def normResidue₀ (F : Type u) [Field F] :
    MilnorK2 F 0 →ₗ[ZMod 2] GaloisCohomologyMod2 F 0 :=
  (Submodule.mkQ _).comp
    (Submodule.liftQ _ (normResidueCochain₀ F)
      (by
        rw [milnorRelations, Submodule.span_le]
        rintro x (⟨i, -⟩ | ⟨i, -⟩) <;> exact i.elim0))

/-- The degree-one norm residue map, at the level of cochains. -/
noncomputable def normResidueCochain₁ (hF : (2 : F) ≠ 0) :
    ((Fin 1 → Fˣ) →₀ ZMod 2) →ₗ[ZMod 2] LinearMap.ker (dCochain (GaloisGroup F) 1) :=
  Finsupp.linearCombination (ZMod 2)
    (fun t : Fin 1 → Fˣ => (⟨kummerCochain (t 0), kummerCochain_mem_ker hF (t 0)⟩ :
      LinearMap.ker (dCochain (GaloisGroup F) 1)))

theorem milnorRelations_le_ker_normResidueCochain₁ (hF : (2 : F) ≠ 0) :
    milnorRelations F 1 ≤ LinearMap.ker (normResidueCochain₁ hF) := by
  rw [milnorRelations, Submodule.span_le]
  rintro x (⟨i, a, b, t, rfl⟩ | ⟨i, j, t, hij, -, rfl⟩)
  · simp only [SetLike.mem_coe, LinearMap.mem_ker, map_sub]
    have hi : i = 0 := Subsingleton.elim _ _
    subst hi
    simp only [normResidueCochain₁, Finsupp.linearCombination_single, one_smul,
      Function.update_self]
    ext g
    simp only [AddSubgroupClass.coe_sub, ZeroMemClass.coe_zero, LocallyConstant.sub_apply,
      LocallyConstant.zero_apply, kummerCochain_apply]
    rw [kummerChar_mul hF a b (g 0)]
    ring_nf
  · exact absurd (Subsingleton.elim i j) hij

/-- The degree-one norm residue map `k^M_1(F) → H^1(F, ℤ/2)`. -/
noncomputable def normResidue₁ (hF : (2 : F) ≠ 0) :
    MilnorK2 F 1 →ₗ[ZMod 2] GaloisCohomologyMod2 F 1 :=
  (Submodule.mkQ _).comp
    (Submodule.liftQ _ (normResidueCochain₁ hF) (milnorRelations_le_ker_normResidueCochain₁ hF))

/-! ### Computation of the norm residue maps on symbols -/

theorem normResidue₀_apply_symbol (t : Fin 0 → Fˣ) :
    normResidue₀ F (symbol t) = Submodule.Quotient.mk ⟨1, one_mem_ker_dCochain_zero⟩ := by
  simp [normResidue₀, symbol, normResidueCochain₀]

theorem normResidue₁_apply_symbol (hF : (2 : F) ≠ 0) (t : Fin 1 → Fˣ) :
    normResidue₁ hF (symbol t)
      = Submodule.Quotient.mk ⟨kummerCochain (t 0), kummerCochain_mem_ker hF (t 0)⟩ := by
  simp [normResidue₁, symbol, normResidueCochain₁]

/-! ### There are no coboundaries in degrees `0` and `1` -/

theorem comap_coboundaries_zero_eq_bot :
    Submodule.comap (LinearMap.ker (dCochain (GaloisGroup F) 0)).subtype
      (coboundaries (GaloisGroup F) 0) = ⊥ := by
  rw [show coboundaries (GaloisGroup F) 0 = ⊥ from rfl, Submodule.comap_bot,
    Submodule.ker_subtype]

theorem comap_coboundaries_one_eq_bot :
    Submodule.comap (LinearMap.ker (dCochain (GaloisGroup F) 1)).subtype
      (coboundaries (GaloisGroup F) 1) = ⊥ := by
  rw [coboundaries_one_eq_bot, Submodule.comap_bot, Submodule.ker_subtype]

/-! ### Bijectivity -/

theorem normResidue₀_bijective (F : Type u) [Field F] : Function.Bijective (normResidue₀ F) := by
  let t₀ : Fin 0 → Fˣ := fun i => i.elim0
  let g₀ : Fin 0 → GaloisGroup F := fun i => i.elim0
  have hsub : ∀ v : ((Fin 0 → Fˣ) →₀ ZMod 2), v = Finsupp.single t₀ (v t₀) := by
    intro v
    refine Finsupp.ext fun t => ?_
    have ht : t = t₀ := Subsingleton.elim _ _
    subst ht
    simp
  have key : ∀ c : ZMod 2, normResidue₀ F (Submodule.Quotient.mk (Finsupp.single t₀ c))
      = Submodule.Quotient.mk (c •
          (⟨1, one_mem_ker_dCochain_zero⟩ : LinearMap.ker (dCochain (GaloisGroup F) 0))) := by
    intro c
    simp [normResidue₀, normResidueCochain₀]
  constructor
  · rw [injective_iff_map_eq_zero]
    intro x hx
    induction x using Submodule.Quotient.induction_on with
    | H v =>
      have hv := hsub v
      rw [show Submodule.Quotient.mk v
          = Submodule.Quotient.mk (Finsupp.single t₀ (v t₀)) from congrArg _ hv, key] at hx
      have h2 := (Submodule.Quotient.mk_eq_zero _).1 hx
      rw [comap_coboundaries_zero_eq_bot, Submodule.mem_bot] at h2
      have h3 : v t₀ = 0 := by
        have h4 := congrArg
          (fun u : LinearMap.ker (dCochain (GaloisGroup F) 0) =>
            (u : Cochain (GaloisGroup F) 0) g₀) h2
        simpa using h4
      have hv0 : v = 0 := by
        conv_lhs => rw [hv]
        rw [h3, Finsupp.single_zero]
      rw [hv0]
      simp
  · intro z
    induction z using Submodule.Quotient.induction_on with
    | H w =>
      obtain ⟨f, hf⟩ := w
      refine ⟨Submodule.Quotient.mk (Finsupp.single t₀ (f g₀)), ?_⟩
      rw [key]
      refine congrArg _ (Subtype.ext ?_)
      ext g
      have hg : g = g₀ := Subsingleton.elim _ _
      simp [hg]

theorem normResidue₁_bijective (hF : (2 : F) ≠ 0) : Function.Bijective (normResidue₁ hF) := by
  constructor
  · rw [injective_iff_map_eq_zero]
    intro x hx
    obtain ⟨a, rfl⟩ := exists_symbol₁ x
    rw [symbol₁, normResidue₁_apply_symbol hF] at hx
    have h2 := (Submodule.Quotient.mk_eq_zero _).1 hx
    rw [comap_coboundaries_one_eq_bot, Submodule.mem_bot] at h2
    have hchar : ∀ σ : GaloisGroup F, kummerChar a σ = 0 := by
      intro σ
      have h3 := congrArg
        (fun u : LinearMap.ker (dCochain (GaloisGroup F) 1) => (u : Cochain (GaloisGroup F) 1)
          (fun _ => σ)) h2
      simpa [kummerCochain_apply] using h3
    obtain ⟨c, rfl⟩ := (kummerChar_eq_zero_iff hF a).1 hchar
    exact symbol₁_sq c
  · intro z
    induction z using Submodule.Quotient.induction_on with
    | H w =>
      obtain ⟨f, hf⟩ := w
      obtain ⟨a, ha⟩ := exists_kummerChar_eq hF f hf
      refine ⟨symbol₁ a, ?_⟩
      rw [symbol₁, normResidue₁_apply_symbol hF]
      exact congrArg _ (Subtype.ext ha)

/-! ### The norm residue maps send symbols to cup products of Kummer classes -/

theorem symbolCochain_zero (t : Fin 0 → Fˣ) :
    symbolCochain t = (1 : Cochain (GaloisGroup F) 0) := by
  simp [symbolCochain]

theorem symbolCochain_one (t : Fin 1 → Fˣ) :
    symbolCochain t = kummerCochain (t 0) := by
  ext g
  rw [symbolCochain_apply, kummerCochain_apply]
  simp

theorem normResidue₀_symbol (t : Fin 0 → Fˣ) :
    ∃ h : symbolCochain t ∈ LinearMap.ker (dCochain (GaloisGroup F) 0),
      normResidue₀ F (symbol t) = Submodule.Quotient.mk ⟨symbolCochain t, h⟩ := by
  refine ⟨by rw [symbolCochain_zero]; exact one_mem_ker_dCochain_zero, ?_⟩
  rw [normResidue₀_apply_symbol]
  exact congrArg _ (Subtype.ext (symbolCochain_zero t).symm)

theorem normResidue₁_symbol (hF : (2 : F) ≠ 0) (t : Fin 1 → Fˣ) :
    ∃ h : symbolCochain t ∈ LinearMap.ker (dCochain (GaloisGroup F) 1),
      normResidue₁ hF (symbol t) = Submodule.Quotient.mk ⟨symbolCochain t, h⟩ := by
  refine ⟨by rw [symbolCochain_one]; exact kummerCochain_mem_ker hF (t 0), ?_⟩
  rw [normResidue₁_apply_symbol hF]
  exact congrArg _ (Subtype.ext (symbolCochain_one t).symm)

/-- **The base cases of the Milnor conjecture.** For every field `F` in which `2 ≠ 0`, the norm
residue map `k^M_n(F) → H^n(F, ℤ/2)` is an isomorphism in degrees `n = 0` and `n = 1`. The
degree-one statement is Kummer theory: `F^×/(F^×)² ≅ H^1(F, ℤ/2)`. -/
theorem voevodsky_milnor (F : Type u) [Field F] (hF : (2 : F) ≠ 0) :
    NormResidueIso F 0 ∧ NormResidueIso F 1 :=
  ⟨⟨normResidue₀ F, normResidue₀_bijective F, normResidue₀_symbol⟩,
   ⟨normResidue₁ hF, normResidue₁_bijective hF, normResidue₁_symbol hF⟩⟩

end Frontier

import Mathlib

/-!
# Continuous mod-2 cohomology of a topological group, and mod-2 Galois cohomology

For a topological group `G` we define continuous cochain cohomology `H^n(G, ℤ/2)` with trivial
coefficients: `n`-cochains are the locally constant (equivalently, continuous for the discrete
topology on `ℤ/2`) functions `Gⁿ → ℤ/2`, with the usual inhomogeneous differential

`(d f)(g₀, …, gₙ) = f(g₁, …, gₙ) + Σᵢ f(g₀, …, gᵢgᵢ₊₁, …, gₙ) + f(g₀, …, gₙ₋₁)`

(the signs of the alternating sum are irrelevant modulo `2`), and `H^n` is the subquotient
`ker dⁿ / im dⁿ⁻¹`.

Applying this to the absolute Galois group `G_F = Gal(F^sep/F)` of a field `F`, equipped with the
Krull topology, gives mod-2 Galois cohomology `H^n(F, ℤ/2)`.
-/

open scoped Classical

namespace Frontier

universe u

section TopologicalGroup

variable (G : Type*) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- Continuous (equivalently, locally constant) `n`-cochains of a topological group `G` with
values in the trivial module `ℤ/2`. -/
abbrev Cochain (n : ℕ) := LocallyConstant (Fin n → G) (ZMod 2)

variable {G}

/-- The face map dropping the first coordinate. -/
def faceTail (n : ℕ) : C(Fin (n + 1) → G, Fin n → G) :=
  ⟨fun g => Fin.tail g, continuous_pi fun _ => continuous_apply _⟩

/-- The face map dropping the last coordinate. -/
def faceInit (n : ℕ) : C(Fin (n + 1) → G, Fin n → G) :=
  ⟨fun g => Fin.init g, continuous_pi fun _ => continuous_apply _⟩

/-- The face map multiplying the `i`-th and the `(i+1)`-st coordinates. -/
def faceMul {n : ℕ} (i : Fin n) : C(Fin (n + 1) → G, Fin n → G) :=
  ⟨fun g j => if (j : ℕ) < (i : ℕ) then g j.castSucc
      else if (j : ℕ) = (i : ℕ) then g i.castSucc * g i.succ else g j.succ,
    continuous_pi fun j => by
      by_cases h1 : (j : ℕ) < (i : ℕ)
      · simp only [if_pos h1]; exact continuous_apply _
      · by_cases h2 : (j : ℕ) = (i : ℕ)
        · simp only [if_neg h1, if_pos h2]
          exact (continuous_apply _).mul (continuous_apply _)
        · simp only [if_neg h1, if_neg h2]; exact continuous_apply _⟩

variable (G)

/-- The differential on continuous cochains, `d : Cⁿ → Cⁿ⁺¹`. -/
noncomputable def dCochain (n : ℕ) : Cochain G n →ₗ[ZMod 2] Cochain G (n + 1) :=
  LocallyConstant.comapₗ (ZMod 2) (faceTail n) +
    (∑ i : Fin n, LocallyConstant.comapₗ (ZMod 2) (faceMul i)) +
    LocallyConstant.comapₗ (ZMod 2) (faceInit n)

/-- The submodule of continuous `n`-coboundaries. -/
noncomputable def coboundaries : (n : ℕ) → Submodule (ZMod 2) (Cochain G n)
  | 0 => ⊥
  | (n + 1) => LinearMap.range (dCochain G n)

/-- Continuous mod-2 cohomology `H^n(G, ℤ/2)` with trivial coefficients, defined as the
subquotient `ker dⁿ / im dⁿ⁻¹` of the complex of continuous cochains. -/
abbrev ContCohomologyMod2 (n : ℕ) :=
  (LinearMap.ker (dCochain G n)) ⧸
    (Submodule.comap (LinearMap.ker (dCochain G n)).subtype (coboundaries G n))

variable {G}

theorem dCochain_apply {n : ℕ} (f : Cochain G n) (g : Fin (n + 1) → G) :
    dCochain G n f g = f (Fin.tail g) + (∑ i : Fin n, f (faceMul i g)) + f (Fin.init g) := by
  have h : dCochain G n f = LocallyConstant.comapₗ (ZMod 2) (faceTail n) f
      + (∑ i : Fin n, LocallyConstant.comapₗ (ZMod 2) (faceMul i) f)
      + LocallyConstant.comapₗ (ZMod 2) (faceInit n) f := by
    simp [dCochain, LinearMap.sum_apply]
  rw [h]
  have hsum : (∑ i : Fin n, LocallyConstant.comapₗ (ZMod 2) (faceMul i) f) g
      = ∑ i : Fin n, (LocallyConstant.comapₗ (ZMod 2) (faceMul i) f) g :=
    map_sum (LocallyConstant.evalₗ (ZMod 2) g) _ Finset.univ
  simp only [LocallyConstant.add_apply, hsum]
  rfl

variable (G)

/-- In degree `0` the differential vanishes: the coefficients are trivial and `1 + 1 = 0`. -/
theorem dCochain_zero_eq_zero : dCochain G 0 = 0 := by
  ext f g
  rw [dCochain_apply]
  have h : Fin.tail g = Fin.init g := Subsingleton.elim _ _
  simp only [Finset.univ_eq_empty, Finset.sum_empty, add_zero, h]
  have : ∀ x : ZMod 2, x + x = 0 := by decide
  exact this _

/-- There are no nonzero mod-2 coboundaries in degree one (the coefficients are trivial). -/
theorem coboundaries_one_eq_bot : coboundaries G 1 = ⊥ := by
  rw [coboundaries, dCochain_zero_eq_zero, LinearMap.range_eq_bot.2 rfl]

/-- The degree-zero differential having trivial kernel condition: every `0`-cochain is a cocycle. -/
theorem ker_dCochain_zero : LinearMap.ker (dCochain G 0) = ⊤ := by
  rw [dCochain_zero_eq_zero]; exact LinearMap.ker_zero

variable {G}

/-- Degree-one cocycles are exactly the continuous homomorphisms `G → ℤ/2`. -/
theorem mem_ker_dCochain_one_iff (f : Cochain G 1) :
    f ∈ LinearMap.ker (dCochain G 1) ↔
      ∀ σ τ : G, f (fun _ => σ * τ) = f (fun _ => σ) + f (fun _ => τ) := by
  constructor
  · intro hf σ τ
    simp only [LinearMap.mem_ker] at hf
    have h2 : dCochain G 1 f ![σ, τ] = 0 := by rw [hf]; rfl
    rw [dCochain_apply] at h2
    have e1 : Fin.tail (![σ, τ] : Fin 2 → G) = fun _ => τ := by
      funext k; fin_cases k; rfl
    have e2 : Fin.init (![σ, τ] : Fin 2 → G) = fun _ => σ := by
      funext k; fin_cases k; rfl
    have e3 : faceMul (0 : Fin 1) (![σ, τ] : Fin 2 → G) = fun _ => σ * τ := by
      funext k; fin_cases k; simp [faceMul]
    rw [e1, e2] at h2
    simp only [Finset.univ_unique, Finset.sum_singleton] at h2
    rw [show (default : Fin 1) = 0 from rfl, e3] at h2
    have hchar : ∀ x y z : ZMod 2, x + y + z = 0 → y = z + x := by decide
    exact hchar _ _ _ h2
  · intro hf
    rw [LinearMap.mem_ker]
    ext g
    rw [dCochain_apply]
    have e1 : Fin.tail g = fun _ => g 1 := by funext k; fin_cases k; rfl
    have e2 : Fin.init g = fun _ => g 0 := by funext k; fin_cases k; rfl
    have e3 : faceMul (0 : Fin 1) g = fun _ => g 0 * g 1 := by
      funext k; fin_cases k; simp [faceMul]
    rw [e1, e2]
    simp only [Finset.univ_unique, Finset.sum_singleton]
    rw [show (default : Fin 1) = 0 from rfl, e3, hf (g 0) (g 1)]
    have : ∀ x y : ZMod 2, y + (x + y) + x = 0 := by decide
    exact this _ _

end TopologicalGroup

section Galois

variable (F : Type u) [Field F]

/-- The absolute Galois group `Gal(F^sep/F)` of a field `F`, with the Krull topology. -/
abbrev GaloisGroup := (SeparableClosure F) ≃ₐ[F] (SeparableClosure F)

/-- Mod-2 Galois cohomology `H^n(F, ℤ/2) = H^n(Gal(F^sep/F), ℤ/2)`, defined by continuous
cochains. -/
abbrev GaloisCohomologyMod2 (n : ℕ) := ContCohomologyMod2 (GaloisGroup F) n

end Galois

end Frontier

