/-
# Lieb Robinson
Category: Frontier Physics
Target: Frontier.lieb_robinson
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

-- (Lean requires `import` to precede any module docstring, so the header above is a
-- plain block comment; the same header is repeated as a module docstring below.)

import Mathlib

/-!
# Lieb Robinson
Category: Frontier Physics
Target: Frontier.lieb_robinson
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

/-!
## Setting

We work in a unital C*-algebra `A` (the algebra of observables of a quantum spin system).
For a self-adjoint Hamiltonian `H` the Heisenberg dynamics is
`τ_t(a) = exp(i t H) * a * exp(-i t H)`.

The Lieb–Robinson bound asserts that if `a` and `b` are observables supported in
regions that are not coupled by the "free" part `H₀` of the Hamiltonian, then the
commutator `⁅τ_t(a), b⁆` stays small for small times: it is controlled by the strength
of the coupling term `V` times the elapsed time.  This is exactly the base case
(first order in `t`) of the Lieb–Robinson series which produces the exponential
light cone `e^{v|t| - d}`.
-/

namespace Frontier

open NormedSpace

variable {A : Type*} [CStarAlgebra A] [Nontrivial A]

noncomputable local instance ratAlg : NormedAlgebra ℚ A := .restrictScalars ℚ ℂ A

/-- The Heisenberg time evolution of the observable `a` generated by the Hamiltonian `H`:
`τ_t(a) = exp(i t H) * a * exp(-i t H)`. -/
noncomputable def heisenberg (H : A) (t : ℝ) (a : A) : A :=
  exp (t • (Complex.I • H)) * a * exp (-(t • (Complex.I • H)))

section Auxiliary

/-- The exponential of a skew-adjoint element of a unital C*-algebra is unitary,
hence has norm one. -/
theorem norm_exp_of_mem_skewAdjoint {X : A} (h : X ∈ skewAdjoint A) : ‖exp X‖ = 1 :=
  CStarRing.norm_of_mem_unitary (exp_mem_unitary_of_mem_skewAdjoint h)

omit [Nontrivial A] in
/-- Real multiples of skew-adjoint elements are skew-adjoint. -/
theorem smul_mem_skewAdjoint {X : A} (h : X ∈ skewAdjoint A) (s : ℝ) :
    s • X ∈ skewAdjoint A := by
  simpa [skewAdjoint.mem_iff, star_smul] using
    congrArg (fun z : A => s • z) (skewAdjoint.mem_iff.mp h)

omit [Nontrivial A] in
/-- If `H` is self-adjoint then `i H` is skew-adjoint. -/
theorem I_smul_mem_skewAdjoint {H : A} (h : IsSelfAdjoint H) :
    Complex.I • H ∈ skewAdjoint A := by
  simp [skewAdjoint.mem_iff, star_smul, h.star_eq, Complex.conj_I]

/-- **Duhamel estimate** (the key intermediate lemma).  For skew-adjoint generators `X`
and `Y`, the two unitary groups they generate stay `|t| ‖X - Y‖`-close:
`‖exp (t • X) - exp (t • Y)‖ ≤ |t| * ‖X - Y‖`. -/
theorem norm_exp_sub_exp_le {X Y : A} (hX : X ∈ skewAdjoint A) (hY : Y ∈ skewAdjoint A)
    (t : ℝ) : ‖exp (t • X) - exp (t • Y)‖ ≤ |t| * ‖X - Y‖ := by
  have hnegX : -X ∈ skewAdjoint A := neg_mem hX
  set g : ℝ → A := fun s => exp (t • X) * (exp (s • (-X)) * exp (s • Y)) with hg
  have hderiv : ∀ s : ℝ, HasDerivAt g
      (exp (t • X) * (exp (s • (-X)) * (Y - X) * exp (s • Y))) s := by
    intro s
    have h1 : HasDerivAt (fun s : ℝ => exp (s • (-X))) (exp (s • (-X)) * (-X)) s :=
      hasDerivAt_exp_smul_const (𝕂 := ℝ) (-X) s
    have h2 : HasDerivAt (fun s : ℝ => exp (s • Y)) (Y * exp (s • Y)) s :=
      hasDerivAt_exp_smul_const' (𝕂 := ℝ) Y s
    have h3 := (h1.mul h2).const_mul (exp (t • X))
    convert h3 using 1
    noncomm_ring
  have key : ‖g t - g 0‖ ≤ ‖X - Y‖ * ‖t - 0‖ := by
    apply Convex.norm_image_sub_le_of_norm_hasDerivWithin_le
      (fun s _ => (hderiv s).hasDerivWithinAt) _ (convex_uIcc 0 t)
      Set.left_mem_uIcc Set.right_mem_uIcc
    intro s _
    have e1 : ‖exp (t • X)‖ = 1 := norm_exp_of_mem_skewAdjoint (smul_mem_skewAdjoint hX t)
    have e2 : ‖exp (s • (-X))‖ = 1 := norm_exp_of_mem_skewAdjoint (smul_mem_skewAdjoint hnegX s)
    have e3 : ‖exp (s • Y)‖ = 1 := norm_exp_of_mem_skewAdjoint (smul_mem_skewAdjoint hY s)
    calc ‖exp (t • X) * (exp (s • (-X)) * (Y - X) * exp (s • Y))‖
        ≤ ‖exp (t • X)‖ * ‖exp (s • (-X)) * (Y - X) * exp (s • Y)‖ := norm_mul_le _ _
      _ ≤ ‖exp (t • X)‖ * (‖exp (s • (-X)) * (Y - X)‖ * ‖exp (s • Y)‖) := by
          gcongr; exact norm_mul_le _ _
      _ ≤ ‖exp (t • X)‖ * ((‖exp (s • (-X))‖ * ‖Y - X‖) * ‖exp (s • Y)‖) := by
          gcongr; exact norm_mul_le _ _
      _ = ‖Y - X‖ := by rw [e1, e2, e3]; ring
      _ = ‖X - Y‖ := norm_sub_rev _ _
  have hgt : g t = exp (t • Y) := by
    have hinv : exp (t • X) * exp (t • (-X)) = 1 := by
      rw [← exp_add_of_commute (by simp [Commute, SemiconjBy])]
      simp
    rw [hg]
    simp only [← mul_assoc, hinv, one_mul]
  have hg0 : g 0 = exp (t • X) := by simp [hg]
  rw [hgt, hg0] at key
  calc ‖exp (t • X) - exp (t • Y)‖ = ‖exp (t • Y) - exp (t • X)‖ := norm_sub_rev _ _
    _ ≤ ‖X - Y‖ * |t| := by simpa [Real.norm_eq_abs] using key
    _ = |t| * ‖X - Y‖ := mul_comm _ _

omit [Nontrivial A] in
/-- The commutator of an observable with `b` is bounded by `2 ‖x‖ ‖b‖`. -/
theorem norm_commutator_le (x b : A) : ‖⁅x, b⁆‖ ≤ 2 * ‖x‖ * ‖b‖ := by
  calc ‖⁅x, b⁆‖ = ‖x * b - b * x‖ := by rw [Ring.lie_def]
    _ ≤ ‖x * b‖ + ‖b * x‖ := norm_sub_le _ _
    _ ≤ ‖x‖ * ‖b‖ + ‖b‖ * ‖x‖ := by gcongr <;> exact norm_mul_le _ _
    _ = 2 * ‖x‖ * ‖b‖ := by ring

omit [Nontrivial A] in
/-- If the generator commutes with `b`, then the corresponding evolution of `a`
commutes with `b` as soon as `a` does: the decoupled dynamics does not spread
the support of `a` towards `b`. -/
theorem commute_conj_of_commute {X a b : A} (hXb : Commute X b) (hab : Commute a b) (t : ℝ) :
    ⁅exp (t • X) * a * exp (-(t • X)), b⁆ = 0 := by
  have h1 : Commute (exp (t • X)) b := ((hXb.smul_left t).exp_left)
  have h2 : Commute (exp (-(t • X))) b := (((hXb.smul_left t).neg_left).exp_left)
  have : Commute (exp (t • X) * a * exp (-(t • X))) b :=
    (h1.mul_left hab).mul_left h2
  rw [Ring.lie_def, this.eq, sub_self]

end Auxiliary

/-- **Lieb–Robinson bound (base case).**

Let `A` be a unital C*-algebra of observables, and let the Hamiltonian split as
`H = H₀ + V`, with `H₀` and `V` self-adjoint.  Let `a` and `b` be observables such that

* `a` and `b` commute (their supports are disjoint), and
* `H₀` commutes with `b` (the free part of the dynamics does not couple the region of
  `b` to that of `a`),

so that the only mechanism transporting information from `a` to `b` is the coupling
term `V`.  Then the Heisenberg-evolved observable `τ_t(a)` almost commutes with `b`,
with an error growing at most linearly in time:

`‖⁅τ_t(a), b⁆‖ ≤ 4 |t| ‖V‖ ‖a‖ ‖b‖`.

This is the effective light cone at first order: the commutator is negligible for
`|t| ≪ 1 / ‖V‖`, i.e. information propagates with a finite speed proportional to the
strength of the coupling. -/
theorem lieb_robinson {H₀ V a b : A} (hH₀ : IsSelfAdjoint H₀) (hV : IsSelfAdjoint V)
    (hH₀b : Commute H₀ b) (hab : Commute a b) (t : ℝ) :
    ‖⁅heisenberg (H₀ + V) t a, b⁆‖ ≤ 4 * |t| * ‖V‖ * ‖a‖ * ‖b‖ := by
  set X : A := Complex.I • (H₀ + V) with hX
  set Y : A := Complex.I • H₀ with hY
  have hXskew : X ∈ skewAdjoint A := I_smul_mem_skewAdjoint (hH₀.add hV)
  have hYskew : Y ∈ skewAdjoint A := I_smul_mem_skewAdjoint hH₀
  have hXY : X - Y = Complex.I • V := by
    rw [hX, hY, smul_add]; abel
  have hnormXY : ‖X - Y‖ = ‖V‖ := by
    rw [hXY, norm_smul]
    simp
  -- the decoupled dynamics keeps `a` commuting with `b`
  have hfree : ⁅exp (t • Y) * a * exp (-(t • Y)), b⁆ = 0 := by
    refine commute_conj_of_commute ?_ hab t
    exact (hH₀b.smul_left Complex.I)
  -- the two evolutions differ by at most `2 |t| ‖V‖ ‖a‖`
  have hu : ‖exp (t • X) - exp (t • Y)‖ ≤ |t| * ‖V‖ := by
    simpa [hnormXY] using norm_exp_sub_exp_le hXskew hYskew t
  have hustar : ‖exp (-(t • X)) - exp (-(t • Y))‖ ≤ |t| * ‖V‖ := by
    have h := norm_exp_sub_exp_le (neg_mem hXskew) (neg_mem hYskew) t
    have e1 : t • (-X) = -(t • X) := by module
    have e2 : t • (-Y) = -(t • Y) := by module
    have e3 : ‖(-X) - (-Y)‖ = ‖V‖ := by
      rw [show (-X) - (-Y) = -(X - Y) by abel, norm_neg, hnormXY]
    rw [e1, e2, e3] at h
    exact h
  have hnu : ‖exp (-(t • X))‖ = 1 :=
    norm_exp_of_mem_skewAdjoint (by
      simpa using smul_mem_skewAdjoint (neg_mem hXskew) t)
  have hnw : ‖exp (t • Y)‖ = 1 := norm_exp_of_mem_skewAdjoint (smul_mem_skewAdjoint hYskew t)
  have hdiff : ‖exp (t • X) * a * exp (-(t • X)) - exp (t • Y) * a * exp (-(t • Y))‖
      ≤ 2 * (|t| * ‖V‖) * ‖a‖ := by
    have hsplit : exp (t • X) * a * exp (-(t • X)) - exp (t • Y) * a * exp (-(t • Y))
        = (exp (t • X) - exp (t • Y)) * a * exp (-(t • X))
          + exp (t • Y) * a * (exp (-(t • X)) - exp (-(t • Y))) := by
      noncomm_ring
    rw [hsplit]
    have b1 : ‖(exp (t • X) - exp (t • Y)) * a * exp (-(t • X))‖ ≤ (|t| * ‖V‖) * ‖a‖ := by
      calc ‖(exp (t • X) - exp (t • Y)) * a * exp (-(t • X))‖
          ≤ ‖(exp (t • X) - exp (t • Y)) * a‖ * ‖exp (-(t • X))‖ := norm_mul_le _ _
        _ ≤ (‖exp (t • X) - exp (t • Y)‖ * ‖a‖) * ‖exp (-(t • X))‖ := by
            gcongr; exact norm_mul_le _ _
        _ = ‖exp (t • X) - exp (t • Y)‖ * ‖a‖ := by rw [hnu]; ring
        _ ≤ (|t| * ‖V‖) * ‖a‖ := by gcongr
    have b2 : ‖exp (t • Y) * a * (exp (-(t • X)) - exp (-(t • Y)))‖ ≤ (|t| * ‖V‖) * ‖a‖ := by
      calc ‖exp (t • Y) * a * (exp (-(t • X)) - exp (-(t • Y)))‖
          ≤ ‖exp (t • Y) * a‖ * ‖exp (-(t • X)) - exp (-(t • Y))‖ := norm_mul_le _ _
        _ ≤ (‖exp (t • Y)‖ * ‖a‖) * ‖exp (-(t • X)) - exp (-(t • Y))‖ := by
            gcongr; exact norm_mul_le _ _
        _ = ‖a‖ * ‖exp (-(t • X)) - exp (-(t • Y))‖ := by rw [hnw]; ring
        _ ≤ ‖a‖ * (|t| * ‖V‖) := by gcongr
        _ = (|t| * ‖V‖) * ‖a‖ := mul_comm _ _
    calc ‖(exp (t • X) - exp (t • Y)) * a * exp (-(t • X))
            + exp (t • Y) * a * (exp (-(t • X)) - exp (-(t • Y)))‖
        ≤ ‖(exp (t • X) - exp (t • Y)) * a * exp (-(t • X))‖
          + ‖exp (t • Y) * a * (exp (-(t • X)) - exp (-(t • Y)))‖ := norm_add_le _ _
      _ ≤ (|t| * ‖V‖) * ‖a‖ + (|t| * ‖V‖) * ‖a‖ := by gcongr
      _ = 2 * (|t| * ‖V‖) * ‖a‖ := by ring
  have hcomm_eq : ⁅heisenberg (H₀ + V) t a, b⁆
      = ⁅exp (t • X) * a * exp (-(t • X)) - exp (t • Y) * a * exp (-(t • Y)), b⁆ := by
    rw [sub_lie, hfree, sub_zero]
    rfl
  rw [hcomm_eq]
  calc ‖⁅exp (t • X) * a * exp (-(t • X)) - exp (t • Y) * a * exp (-(t • Y)), b⁆‖
      ≤ 2 * ‖exp (t • X) * a * exp (-(t • X)) - exp (t • Y) * a * exp (-(t • Y))‖ * ‖b‖ :=
        norm_commutator_le _ _
    _ ≤ 2 * (2 * (|t| * ‖V‖) * ‖a‖) * ‖b‖ := by gcongr
    _ = 4 * |t| * ‖V‖ * ‖a‖ * ‖b‖ := by ring

/-- **Effective light cone.**  Under the hypotheses of `Frontier.lieb_robinson`, for every
tolerance `ε > 0` there is a time `δ > 0` such that for all times `|t| < δ` the observable
`b` cannot detect the evolved observable `τ_t(a)` up to accuracy `ε`.  Equivalently, the
signal from the region of `a` needs a positive time to reach the region of `b`: this is the
finite propagation speed expressed by the Lieb–Robinson bound. -/
theorem lieb_robinson_light_cone {H₀ V a b : A} (hH₀ : IsSelfAdjoint H₀) (hV : IsSelfAdjoint V)
    (hH₀b : Commute H₀ b) (hab : Commute a b) {ε : ℝ} (hε : 0 < ε) :
    ∃ δ > 0, ∀ t : ℝ, |t| < δ → ‖⁅heisenberg (H₀ + V) t a, b⁆‖ ≤ ε := by
  set C : ℝ := 4 * ‖V‖ * ‖a‖ * ‖b‖ with hC
  have hC0 : 0 ≤ C := by positivity
  refine ⟨ε / (C + 1), by positivity, fun t ht => ?_⟩
  have h1 : ‖⁅heisenberg (H₀ + V) t a, b⁆‖ ≤ |t| * C := by
    have := lieb_robinson hH₀ hV hH₀b hab t
    calc ‖⁅heisenberg (H₀ + V) t a, b⁆‖ ≤ 4 * |t| * ‖V‖ * ‖a‖ * ‖b‖ := this
      _ = |t| * C := by rw [hC]; ring
  have h2 : |t| * C ≤ (ε / (C + 1)) * C := by
    have : (0:ℝ) ≤ C := hC0
    nlinarith [abs_nonneg t]
  have h3 : (ε / (C + 1)) * C ≤ ε := by
    rw [div_mul_eq_mul_div, div_le_iff₀ (by positivity)]
    nlinarith
  linarith

end Frontier

#print axioms Frontier.lieb_robinson
#print axioms Frontier.lieb_robinson_light_cone

