import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

/-!
# Isotypic decomposition of the vertex representation of a regular `n`-gon

The dihedral group `D_n` acts on the vertices of a regular `n`-gon, hence on the space
`ZMod n → ℂ` of complex functions on the vertices.  The action is generated by the rotation
`rotOp n` (`f ↦ f (· + 1)`) and by the reflection `reflOp n` (`f ↦ f (-·)`).

For every "frequency" `k : ZMod n`, the character `chi n k : j ↦ e(k * j)` is an eigenvector of
the rotation, and the reflection interchanges `chi n k` and `chi n (-k)`.  Consequently the plane
`isotypic n k = span {chi n k, chi n (-k)}` is invariant under the whole dihedral action; it is
a line exactly when `k = -k`, and a genuine plane otherwise.  These isotypic pieces together span
the whole vertex space.

This generalises to arbitrary `n` the familiar pentagon (`n = 5`) picture, in which the
`5`-dimensional vertex representation of `D_5` splits as the trivial line `k = 0` plus the two
planes `k ∈ {1,4}` and `k ∈ {2,3}`.
-/

namespace Brockian

open ZMod Complex

variable (n : ℕ)

/-- The rotation of the regular `n`-gon acting on complex functions on the vertices,
`(rotOp n f) j = f (j + 1)`. -/
def rotOp : (ZMod n → ℂ) →ₗ[ℂ] (ZMod n → ℂ) where
  toFun f := fun j => f (j + 1)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- The reflection of the regular `n`-gon acting on complex functions on the vertices,
`(reflOp n f) j = f (-j)`. -/
def reflOp : (ZMod n → ℂ) →ₗ[ℂ] (ZMod n → ℂ) where
  toFun f := fun j => f (-j)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

@[simp] lemma rotOp_apply (f : ZMod n → ℂ) (j : ZMod n) : rotOp n f j = f (j + 1) := rfl

@[simp] lemma reflOp_apply (f : ZMod n → ℂ) (j : ZMod n) : reflOp n f j = f (-j) := rfl

variable [NeZero n]

/-- The `k`-th character of the vertex set of the regular `n`-gon,
`chi n k j = exp (2 * π * I * k * j / n)`. -/
noncomputable def chi (k : ZMod n) : ZMod n → ℂ := fun j => stdAddChar (k * j)

/-- The `k`-th isotypic plane: the span of `chi n k` and `chi n (-k)`. -/
noncomputable def isotypic (k : ZMod n) : Submodule ℂ (ZMod n → ℂ) :=
  Submodule.span ℂ {chi n k, chi n (-k)}

@[simp] lemma chi_apply (k j : ZMod n) : chi n k j = stdAddChar (k * j) := rfl

/-- Explicit formula for the characters: `chi n k j = exp (2 π i (k j mod n) / n)`. -/
lemma chi_eq_exp (k j : ZMod n) :
    chi n k j = Complex.exp (2 * Real.pi * I * ((k * j).val : ℕ) / n) := by
  have h : ((((k * j).val : ℕ) : ℤ) : ZMod n) = k * j := by push_cast; simp
  rw [chi_apply]
  conv_lhs => rw [← h]
  rw [stdAddChar_coe]
  push_cast
  ring_nf

lemma chi_zero_eq_one (k : ZMod n) : chi n k 0 = 1 := by
  simp [chi, AddChar.map_zero_eq_one]

lemma chi_ne_zero (k : ZMod n) : chi n k ≠ 0 := by
  intro h
  have := congrFun h 0
  rw [chi_zero_eq_one] at this
  exact one_ne_zero this

/-- The characters are eigenvectors of the rotation. -/
lemma rotOp_chi (k : ZMod n) : rotOp n (chi n k) = stdAddChar k • chi n k := by
  funext j
  simp only [rotOp_apply, chi_apply, Pi.smul_apply, smul_eq_mul, mul_add, mul_one,
    AddChar.map_add_eq_mul]
  ring

/-- The reflection interchanges the characters of frequencies `k` and `-k`. -/
lemma reflOp_chi (k : ZMod n) : reflOp n (chi n k) = chi n (-k) := by
  funext j
  simp only [reflOp_apply, chi_apply, mul_neg, neg_mul]

lemma chi_mem_isotypic (k : ZMod n) : chi n k ∈ isotypic n k :=
  Submodule.subset_span (by simp)

lemma chi_neg_mem_isotypic (k : ZMod n) : chi n (-k) ∈ isotypic n k :=
  Submodule.subset_span (by simp)

/-- The family of all characters is linearly independent (Dedekind independence of characters). -/
lemma linearIndependent_chi : LinearIndependent ℂ (fun k : ZMod n => chi n k) := by
  have hli := linearIndependent_monoidHom (Multiplicative (ZMod n)) ℂ
  have hF : Function.Injective (fun k : ZMod n => (stdAddChar.mulShift k).toMonoidHom) := by
    intro a b hab
    have h1 : (stdAddChar.mulShift a) 1 = (stdAddChar.mulShift b) 1 := by
      have := congrArg (fun f => f (Multiplicative.ofAdd (1 : ZMod n))) hab
      simpa using this
    simp only [AddChar.mulShift_apply, mul_one] at h1
    exact injective_stdAddChar h1
  have := hli.comp _ hF
  exact this

/-- The characters span the whole vertex space. -/
lemma span_range_chi : Submodule.span ℂ (Set.range (fun k : ZMod n => chi n k)) = ⊤ := by
  have hcard : Fintype.card (ZMod n) = Module.finrank ℂ (ZMod n → ℂ) := by
    simp
  have := (basisOfLinearIndependentOfCardEqFinrank (linearIndependent_chi n) hcard).span_eq
  rwa [coe_basisOfLinearIndependentOfCardEqFinrank] at this

/-- Each isotypic piece is invariant under the rotation. -/
lemma isotypic_rot_invariant (k : ZMod n) : (isotypic n k).map (rotOp n) ≤ isotypic n k := by
  rw [isotypic, Submodule.map_span_le]
  rintro x hx
  rcases hx with rfl | rfl
  · rw [rotOp_chi]
    exact Submodule.smul_mem _ _ (chi_mem_isotypic n k)
  · rw [rotOp_chi]
    exact Submodule.smul_mem _ _ (chi_neg_mem_isotypic n k)

/-- Each isotypic piece is invariant under the reflection. -/
lemma isotypic_refl_invariant (k : ZMod n) : (isotypic n k).map (reflOp n) ≤ isotypic n k := by
  rw [isotypic, Submodule.map_span_le]
  rintro x hx
  rcases hx with rfl | rfl
  · rw [reflOp_chi]
    exact chi_neg_mem_isotypic n k
  · rw [reflOp_chi, neg_neg]
    exact chi_mem_isotypic n k

/-- The dimension of the `k`-th isotypic piece: a line if `k = -k`, a plane otherwise. -/
lemma finrank_isotypic (k : ZMod n) :
    Module.finrank ℂ (isotypic n k) = if k = -k then 1 else 2 := by
  by_cases hk : k = -k
  · rw [if_pos hk, isotypic, ← hk]
    have : ({chi n k, chi n k} : Set (ZMod n → ℂ)) = {chi n k} := by simp
    rw [this]
    exact finrank_span_singleton (chi_ne_zero n k)
  · rw [if_neg hk, isotypic]
    have hinj : Function.Injective (![k, -k] : Fin 2 → ZMod n) := by
      intro a b hab
      fin_cases a <;> fin_cases b <;> simp_all
    have hli : LinearIndependent ℂ (fun i : Fin 2 => chi n (![k, -k] i)) :=
      (linearIndependent_chi n).comp _ hinj
    have hrange : Set.range (fun i : Fin 2 => chi n (![k, -k] i))
        = ({chi n k, chi n (-k)} : Set (ZMod n → ℂ)) := by
      ext x
      constructor
      · rintro ⟨i, rfl⟩
        fin_cases i <;> simp
      · rintro (rfl | rfl)
        · exact ⟨0, by simp⟩
        · exact ⟨1, by simp⟩
    have := finrank_span_eq_card hli
    rw [hrange] at this
    simpa using this

/-- The isotypic pieces span the whole vertex space. -/
lemma iSup_isotypic : (⨆ k : ZMod n, isotypic n k) = ⊤ := by
  rw [eq_top_iff, ← span_range_chi n, Submodule.span_le]
  rintro x ⟨k, rfl⟩
  exact Submodule.mem_iSup_of_mem k (chi_mem_isotypic n k)

/-- **Isotypic decomposition of the vertex representation of the regular `n`-gon.**

For every `n ≥ 1` and every frequency `k : ZMod n`:
* the character `chi n k` is an eigenvector of the rotation with eigenvalue `e(k)`, and the
  reflection sends it to `chi n (-k)`;
* the subspace `isotypic n k` is invariant under both the rotation and the reflection, i.e. under
  the whole dihedral group of the `n`-gon;
* it has dimension `1` if `k = -k` and dimension `2` otherwise;
* the isotypic pieces span the whole `n`-dimensional vertex space.

For `n = 5` this is the classical decomposition of the pentagon representation of `D_5`. -/
theorem PentagonPentagonIsotypicHigherN (n : ℕ) [NeZero n] :
    (∀ k : ZMod n, rotOp n (chi n k) = stdAddChar k • chi n k) ∧
    (∀ k : ZMod n, reflOp n (chi n k) = chi n (-k)) ∧
    (∀ k : ZMod n, (isotypic n k).map (rotOp n) ≤ isotypic n k) ∧
    (∀ k : ZMod n, (isotypic n k).map (reflOp n) ≤ isotypic n k) ∧
    (∀ k : ZMod n, Module.finrank ℂ (isotypic n k) = if k = -k then 1 else 2) ∧
    (⨆ k : ZMod n, isotypic n k) = ⊤ :=
  ⟨rotOp_chi n, reflOp_chi n, isotypic_rot_invariant n, isotypic_refl_invariant n,
    finrank_isotypic n, iSup_isotypic n⟩

/-- The pentagon case `n = 5`: the vertex representation of `D_5` splits as the trivial line
`isotypic 5 0` together with the two invariant planes `isotypic 5 1` and `isotypic 5 2`. -/
theorem pentagon_isotypic :
    Module.finrank ℂ (isotypic 5 0) = 1 ∧
    Module.finrank ℂ (isotypic 5 1) = 2 ∧
    Module.finrank ℂ (isotypic 5 2) = 2 ∧
    (⨆ k : ZMod 5, isotypic 5 k) = ⊤ := by
  refine ⟨?_, ?_, ?_, iSup_isotypic 5⟩
  · rw [finrank_isotypic 5 0, if_pos (by simp)]
  · rw [finrank_isotypic 5 1, if_neg (by decide)]
  · rw [finrank_isotypic 5 2, if_neg (by decide)]

end Brockian

