import Mathlib
/-!
# Iit Phi Partition
Category: Frontier Mind
Target: Frontier.iit_phi_partition
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-!
## Setting

A *system* consists of a finite set `V` of binary nodes.  A (global) state of the
system is a function `s : V → Bool`.  The dynamics is given by a *mechanism*
`p : V → (V → Bool) → ℝ`, where `p v s` is the probability that node `v` is `true`
at the next time step, given that the current global state is `s`; the nodes are
updated independently of one another (conditionally on the current state).

Integrated information `Φ` at a state `s` is the minimum, over all bipartitions of
the system into two nonempty parts, of the *effective information* generated across
that partition: the Kullback–Leibler divergence between the true transition
distribution and the transition distribution obtained after *cutting* all the
connections that cross the partition (each cut input being replaced by independent
uniform noise).

The theorem `Frontier.iit_phi_partition` states that a *disconnected* system — one
admitting a bipartition into two nonempty parts that do not influence each other —
has `Φ = 0` in every state.
-/

variable {V : Type*}

/-- `nodeProb p v s b` is the probability that node `v` takes the boolean value `b`
at the next time step, given the current global state `s`. -/
noncomputable def nodeProb (p : V → (V → Bool) → ℝ) (v : V) (s : V → Bool) (b : Bool) : ℝ :=
  if b then p v s else 1 - p v s

/-- The joint transition probability of going from state `s` to state `t`: the nodes
are updated independently, conditionally on the current state `s`. -/
noncomputable def trans [Fintype V] (p : V → (V → Bool) → ℝ) (s t : V → Bool) : ℝ :=
  ∏ v : V, nodeProb p v s (t v)

/-- `mix A s u` is the state agreeing with `s` on `A` and with `u` off `A`. -/
def mix [DecidableEq V] (A : Finset V) (s u : V → Bool) : V → Bool :=
  fun v => if v ∈ A then s v else u v

/-- The mechanism of the system after cutting all connections crossing the bipartition
`(A, Aᶜ)`: a node inside `A` sees the true state of `A` but independent uniform noise
in place of the state of `Aᶜ`, and symmetrically for a node outside `A`. -/
noncomputable def cutProb [Fintype V] [DecidableEq V] (p : V → (V → Bool) → ℝ)
    (A : Finset V) (v : V) (s : V → Bool) : ℝ :=
  if v ∈ A then (∑ u : V → Bool, p v (mix A s u)) / (Fintype.card (V → Bool) : ℝ)
  else (∑ u : V → Bool, p v (mix Aᶜ s u)) / (Fintype.card (V → Bool) : ℝ)

/-- The effective information generated by the transition out of the state `s`
across the bipartition `(A, Aᶜ)`: the Kullback–Leibler divergence of the true
transition distribution from the cut one. -/
noncomputable def effInfo [Fintype V] [DecidableEq V] (p : V → (V → Bool) → ℝ)
    (A : Finset V) (s : V → Bool) : ℝ :=
  ∑ t : V → Bool, trans p s t * Real.log (trans p s t / trans (cutProb p A) s t)

/-- Integrated information `Φ` at the state `s`: the infimum of the effective
information over all bipartitions of the system into two nonempty parts. -/
noncomputable def Phi [Fintype V] [DecidableEq V] (p : V → (V → Bool) → ℝ)
    (s : V → Bool) : ℝ :=
  sInf {x : ℝ | ∃ A : Finset V, A.Nonempty ∧ Aᶜ.Nonempty ∧ x = effInfo p A s}

/-- A mechanism is *stochastic* (and nondegenerate) when every node fires with a
probability strictly between `0` and `1`. -/
def Stochastic (p : V → (V → Bool) → ℝ) : Prop :=
  ∀ (v : V) (s : V → Bool), 0 < p v s ∧ p v s < 1

/-- A system is *disconnected* when the node set splits into two nonempty parts
`A` and `Aᶜ` such that the mechanism of each node depends only on the current state
of the part containing it. -/
def Disconnected [Fintype V] [DecidableEq V] (p : V → (V → Bool) → ℝ) : Prop :=
  ∃ A : Finset V, A.Nonempty ∧ Aᶜ.Nonempty ∧
    (∀ v ∈ A, ∀ s s' : V → Bool, (∀ w ∈ A, s w = s' w) → p v s = p v s') ∧
    (∀ v ∉ A, ∀ s s' : V → Bool, (∀ w ∉ A, s w = s' w) → p v s = p v s')

/-! ## Basic facts -/

/-- Summing a product of one-node distributions over all states gives the product of
the one-node normalisations. -/
theorem sum_prod_bool [Fintype V] [DecidableEq V] (g : V → Bool → ℝ) :
    ∑ t : V → Bool, ∏ v : V, g v (t v) = ∏ v : V, (g v true + g v false) := by
  have h : ∀ v : V, (g v true + g v false) = ∑ b : Bool, g v b := by
    intro v; simp
  simp_rw [h]
  rw [Finset.prod_univ_sum]
  congr 1

/-- The transition kernel of any mechanism is normalised. -/
theorem sum_trans_eq_one [Fintype V] [DecidableEq V] (p : V → (V → Bool) → ℝ)
    (s : V → Bool) : ∑ t : V → Bool, trans p s t = 1 := by
  unfold trans
  rw [sum_prod_bool (fun v b => nodeProb p v s b)]
  simp [nodeProb]

/-- The cut probabilities of a stochastic mechanism are again strictly between `0`
and `1`. -/
theorem cutProb_mem_Ioo [Fintype V] [DecidableEq V] {p : V → (V → Bool) → ℝ}
    (hp : Stochastic p) (A : Finset V) (v : V) (s : V → Bool) :
    0 < cutProb p A v s ∧ cutProb p A v s < 1 := by
  have hcard : (0 : ℝ) < (Fintype.card (V → Bool) : ℝ) := by
    exact_mod_cast Fintype.card_pos
  have key : ∀ B : Finset V,
      0 < (∑ u : V → Bool, p v (mix B s u)) / (Fintype.card (V → Bool) : ℝ) ∧
      (∑ u : V → Bool, p v (mix B s u)) / (Fintype.card (V → Bool) : ℝ) < 1 := by
    intro B
    constructor
    · apply div_pos _ hcard
      apply Finset.sum_pos (fun u _ => (hp v (mix B s u)).1)
      exact Finset.univ_nonempty
    · rw [div_lt_one hcard]
      calc ∑ u : V → Bool, p v (mix B s u)
          < ∑ _u : V → Bool, (1 : ℝ) := by
            apply Finset.sum_lt_sum_of_nonempty Finset.univ_nonempty
            exact fun u _ => (hp v (mix B s u)).2
        _ = (Fintype.card (V → Bool) : ℝ) := by
            simp [Finset.card_univ]
  unfold cutProb
  split
  · exact key A
  · exact key Aᶜ

/-- The transition kernel of a stochastic mechanism is strictly positive. -/
theorem trans_pos [Fintype V] [DecidableEq V] {p : V → (V → Bool) → ℝ}
    (hp : Stochastic p) (s t : V → Bool) : 0 < trans p s t := by
  apply Finset.prod_pos
  intro v _
  unfold nodeProb
  split
  · exact (hp v s).1
  · linarith [(hp v s).2]

/-! ## Nonnegativity of effective information -/

/-- Effective information is nonnegative (Gibbs' inequality). -/
theorem effInfo_nonneg [Fintype V] [DecidableEq V] {p : V → (V → Bool) → ℝ}
    (hp : Stochastic p) (A : Finset V) (s : V → Bool) : 0 ≤ effInfo p A s := by
  have hq : Stochastic (cutProb p A) := fun v s => cutProb_mem_Ioo hp A v s
  have hsum1 : ∑ t : V → Bool, trans p s t = 1 := sum_trans_eq_one p s
  have hsum2 : ∑ t : V → Bool, trans (cutProb p A) s t = 1 := sum_trans_eq_one _ s
  have hpoint : ∀ t : V → Bool,
      trans p s t - trans (cutProb p A) s t
        ≤ trans p s t * Real.log (trans p s t / trans (cutProb p A) s t) := by
    intro t
    have h1 : 0 < trans p s t := trans_pos hp s t
    have h2 : 0 < trans (cutProb p A) s t := trans_pos hq s t
    have hlog : Real.log (trans (cutProb p A) s t / trans p s t)
        ≤ trans (cutProb p A) s t / trans p s t - 1 :=
      Real.log_le_sub_one_of_pos (div_pos h2 h1)
    have hneg : Real.log (trans (cutProb p A) s t / trans p s t)
        = -Real.log (trans p s t / trans (cutProb p A) s t) := by
      rw [← Real.log_inv]
      congr 1
      field_simp
    rw [hneg] at hlog
    have hmul : trans p s t * (1 - trans (cutProb p A) s t / trans p s t)
        ≤ trans p s t * Real.log (trans p s t / trans (cutProb p A) s t) := by
      apply mul_le_mul_of_nonneg_left _ h1.le
      linarith
    have : trans p s t * (1 - trans (cutProb p A) s t / trans p s t)
        = trans p s t - trans (cutProb p A) s t := by
      field_simp
    linarith [this ▸ hmul]
  have := Finset.sum_le_sum (fun (t : V → Bool) (_ : t ∈ Finset.univ) => hpoint t)
  rw [Finset.sum_sub_distrib, hsum1, hsum2] at this
  simpa [effInfo] using this

/-! ## Disconnected systems have vanishing effective information across the split -/

/-- Across the splitting bipartition of a disconnected system, cutting the (absent)
crossing connections changes nothing. -/
theorem cutProb_eq_of_disconnected [Fintype V] [DecidableEq V] {p : V → (V → Bool) → ℝ}
    {A : Finset V}
    (hA : ∀ v ∈ A, ∀ s s' : V → Bool, (∀ w ∈ A, s w = s' w) → p v s = p v s')
    (hAc : ∀ v ∉ A, ∀ s s' : V → Bool, (∀ w ∉ A, s w = s' w) → p v s = p v s')
    (v : V) (s : V → Bool) : cutProb p A v s = p v s := by
  have hcard : (0 : ℝ) < (Fintype.card (V → Bool) : ℝ) := by
    exact_mod_cast Fintype.card_pos
  unfold cutProb
  split
  · rename_i hv
    have : ∀ u : V → Bool, p v (mix A s u) = p v s := by
      intro u
      exact hA v hv _ _ (fun w hw => by simp [mix, hw])
    simp_rw [this]
    rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul]
    field_simp
  · rename_i hv
    have : ∀ u : V → Bool, p v (mix Aᶜ s u) = p v s := by
      intro u
      refine hAc v hv _ _ (fun w hw => by simp [mix, hw])
    simp_rw [this]
    rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul]
    field_simp

/-- The effective information across the splitting bipartition of a disconnected
system vanishes. -/
theorem effInfo_eq_zero_of_disconnected [Fintype V] [DecidableEq V]
    {p : V → (V → Bool) → ℝ} {A : Finset V}
    (hA : ∀ v ∈ A, ∀ s s' : V → Bool, (∀ w ∈ A, s w = s' w) → p v s = p v s')
    (hAc : ∀ v ∉ A, ∀ s s' : V → Bool, (∀ w ∉ A, s w = s' w) → p v s = p v s')
    (s : V → Bool) : effInfo p A s = 0 := by
  have hcut : cutProb p A = p := by
    funext v s'
    exact cutProb_eq_of_disconnected hA hAc v s'
  simp [effInfo, hcut]

/-! ## Main theorem -/

/-- **Integrated information of a disconnected system vanishes.**
For a finite system of binary nodes with a nondegenerate stochastic mechanism `p`,
if the system is disconnected — i.e. the nodes split into two nonempty groups
neither of which influences the other — then the integrated information `Φ`,
defined as the infimum over bipartitions of the effective information generated
across the partition, is `0` at every state. -/
theorem iit_phi_partition [Fintype V] [DecidableEq V] {p : V → (V → Bool) → ℝ}
    (hp : Stochastic p) (hdisc : Disconnected p) (s : V → Bool) : Phi p s = 0 := by
  obtain ⟨A, hAne, hAcne, hA, hAc⟩ := hdisc
  have hzero : effInfo p A s = 0 := effInfo_eq_zero_of_disconnected hA hAc s
  have hmem : (0 : ℝ) ∈ {x : ℝ | ∃ B : Finset V, B.Nonempty ∧ Bᶜ.Nonempty ∧ x = effInfo p B s} :=
    ⟨A, hAne, hAcne, hzero.symm⟩
  have hlb : ∀ x ∈ {x : ℝ | ∃ B : Finset V, B.Nonempty ∧ Bᶜ.Nonempty ∧ x = effInfo p B s},
      (0 : ℝ) ≤ x := by
    rintro x ⟨B, -, -, rfl⟩
    exact effInfo_nonneg hp B s
  refine le_antisymm ?_ ?_
  · exact csInf_le ⟨0, hlb⟩ hmem
  · exact le_csInf ⟨0, hmem⟩ hlb

/-! ## Non-vacuity: the hypotheses are satisfiable

The two-node system in which each node simply copies (noisily) its own previous
value is stochastic and disconnected, so the main theorem applies to it. -/

/-- A noisy two-node self-copy system. -/
noncomputable def twoNodeSelfCopy : Bool → (Bool → Bool) → ℝ :=
  fun v s => if s v then (0.9 : ℝ) else 0.2

theorem twoNodeSelfCopy_stochastic : Stochastic twoNodeSelfCopy := by
  intro v s
  constructor <;> · dsimp only [twoNodeSelfCopy]; split <;> norm_num

theorem twoNodeSelfCopy_disconnected : Disconnected twoNodeSelfCopy := by
  refine ⟨{true}, ⟨true, by simp⟩, ⟨false, by simp⟩, ?_, ?_⟩
  · intro v hv s s' h
    simp only [Finset.mem_singleton] at hv
    subst hv
    dsimp only [twoNodeSelfCopy]
    rw [h true (by simp)]
  · intro v hv s s' h
    dsimp only [twoNodeSelfCopy]
    rw [h v hv]

example (s : Bool → Bool) : Phi twoNodeSelfCopy s = 0 :=
  iit_phi_partition twoNodeSelfCopy_stochastic twoNodeSelfCopy_disconnected s

end Frontier

