/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-!
## Formalizing the restricted Burnside problem

The *restricted Burnside problem* for parameters `m n : ℕ` asks whether there is a uniform bound
on the order of the finite groups that are generated by `m` elements and have exponent dividing
`n`.  Zelmanov's theorem (Fields Medal 1994) says that the answer is positive for all `m` and `n`.

Below we

* formalize the statement, `Frontier.RestrictedBurnside`;
* build the relevant universal object, the free Burnside group `Frontier.BurnsideGroup m n`,
  and prove the standard reduction of the problem to a statement about the finite quotients of
  that single group (`Frontier.restrictedBurnside_iff_boundedBurnsideQuotients`);
* prove the elementary base cases `n ≤ 2`, `m ≤ 1`.

The full theorem of Zelmanov (all `m`, `n`) is *not* proved here; the target theorem
`Frontier.zelmanov_restricted_burnside` collects the reduction together with the base cases.
-/

/-- `G` is generated by (at most) `m` elements. -/
def IsGeneratedBy (m : ℕ) (G : Type) [Group G] : Prop :=
  ∃ s : Fin m → G, Subgroup.closure (Set.range s) = ⊤

/-- Every element of `G` satisfies `g ^ n = 1`, i.e. the exponent of `G` divides `n`. -/
def HasExponentDividing (n : ℕ) (G : Type) [Group G] : Prop :=
  ∀ g : G, g ^ n = 1

/-- **The restricted Burnside problem** for the pair `(m, n)`: there is a bound `B` such that
every finite group generated by `m` elements all of whose elements satisfy `g ^ n = 1` has order
at most `B`. -/
def RestrictedBurnside (m n : ℕ) : Prop :=
  ∃ B : ℕ, ∀ (G : Type) [Group G] [Finite G],
    IsGeneratedBy m G → HasExponentDividing n G → Nat.card G ≤ B

/-- The defining relations of the free Burnside group of rank `m` and exponent `n`: all `n`-th
powers in the free group on `m` generators. -/
def burnsideRels (m n : ℕ) : Set (FreeGroup (Fin m)) :=
  Set.range fun x : FreeGroup (Fin m) => x ^ n

/-- The free Burnside group `B(m, n)`: the free group on `m` generators modulo the normal closure
of all `n`-th powers. -/
abbrev BurnsideGroup (m n : ℕ) : Type := PresentedGroup (burnsideRels m n)

/-- Uniform bound on the finite quotients of the free Burnside group `B(m, n)`. -/
def BoundedBurnsideQuotients (m n : ℕ) : Prop :=
  ∃ B : ℕ, ∀ (G : Type) [Group G] [Finite G] (f : BurnsideGroup m n →* G),
    Function.Surjective f → Nat.card G ≤ B

/-! ### Basic properties of the free Burnside group -/

theorem burnsideGroup_hasExponentDividing (m n : ℕ) :
    HasExponentDividing n (BurnsideGroup m n) := by
  intro g
  obtain ⟨z, rfl⟩ := PresentedGroup.mk_surjective (burnsideRels m n) g
  rw [← map_pow]
  exact PresentedGroup.one_of_mem ⟨z, rfl⟩

theorem burnsideGroup_isGeneratedBy (m n : ℕ) : IsGeneratedBy m (BurnsideGroup m n) :=
  ⟨fun i => PresentedGroup.of i, PresentedGroup.closure_range_of _⟩

/-- The image of a generating set under a surjective homomorphism generates. -/
theorem isGeneratedBy_of_surjective {m : ℕ} {G H : Type} [Group G] [Group H] (f : G →* H)
    (hf : Function.Surjective f) (hG : IsGeneratedBy m G) : IsGeneratedBy m H := by
  obtain ⟨s, hs⟩ := hG
  refine ⟨fun i => f (s i), ?_⟩
  have hmap : Subgroup.map f (Subgroup.closure (Set.range s))
      = Subgroup.closure (Set.range fun i => f (s i)) := by
    rw [MonoidHom.map_closure, ← Set.range_comp]
    rfl
  rw [← hmap, hs, ← MonoidHom.range_eq_map, MonoidHom.range_eq_top]
  exact hf

theorem hasExponentDividing_of_surjective {n : ℕ} {G H : Type} [Group G] [Group H] (f : G →* H)
    (hf : Function.Surjective f) (hG : HasExponentDividing n G) : HasExponentDividing n H := by
  intro h
  obtain ⟨g, rfl⟩ := hf h
  rw [← map_pow, hG g, map_one]

/-- The universal property: every `m`-generated group of exponent dividing `n` is a quotient of
the free Burnside group `B(m, n)`. -/
theorem exists_surjective_hom_burnsideGroup (m n : ℕ) (G : Type) [Group G]
    (hgen : IsGeneratedBy m G) (hexp : HasExponentDividing n G) :
    ∃ f : BurnsideGroup m n →* G, Function.Surjective f := by
  obtain ⟨s, hs⟩ := hgen
  have hrel : ∀ r ∈ burnsideRels m n, FreeGroup.lift s r = 1 := by
    rintro r ⟨x, rfl⟩
    rw [map_pow]
    exact hexp _
  refine ⟨PresentedGroup.toGroup hrel, ?_⟩
  intro g
  have hle : Subgroup.closure (Set.range s) ≤ (PresentedGroup.toGroup hrel).range := by
    rw [Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    exact ⟨PresentedGroup.of i, PresentedGroup.toGroup.of hrel⟩
  have : g ∈ (PresentedGroup.toGroup hrel).range := by
    rw [hs] at hle
    exact hle (Subgroup.mem_top g)
  exact this

/-! ### The reduction to the free Burnside group -/

/-- **Reduction.** The restricted Burnside problem for `(m, n)` is equivalent to the existence of
a uniform bound on the orders of the *finite quotients of the single group* `B(m, n)`. -/
theorem restrictedBurnside_iff_boundedBurnsideQuotients (m n : ℕ) :
    RestrictedBurnside m n ↔ BoundedBurnsideQuotients m n := by
  constructor
  · rintro ⟨B, hB⟩
    refine ⟨B, fun G _ _ f hf => hB G ?_ ?_⟩
    · exact isGeneratedBy_of_surjective f hf (burnsideGroup_isGeneratedBy m n)
    · exact hasExponentDividing_of_surjective f hf (burnsideGroup_hasExponentDividing m n)
  · rintro ⟨B, hB⟩
    refine ⟨B, fun G _ _ hgen hexp => ?_⟩
    obtain ⟨f, hf⟩ := exists_surjective_hom_burnsideGroup m n G hgen hexp
    exact hB G f hf

/-! ### Base cases -/

/-- Groups of exponent dividing `1` are trivial. -/
theorem restrictedBurnside_exponent_one (m : ℕ) : RestrictedBurnside m 1 := by
  refine ⟨1, fun G _ _ _ hexp => ?_⟩
  rw [Nat.card_le_one_iff_subsingleton]
  exact ⟨fun a b => by rw [show a = 1 by simpa using hexp a, show b = 1 by simpa using hexp b]⟩

/-- Groups generated by the empty set are trivial. -/
theorem restrictedBurnside_rank_zero (n : ℕ) : RestrictedBurnside 0 n := by
  refine ⟨1, fun G _ _ hgen _ => ?_⟩
  obtain ⟨s, hs⟩ := hgen
  have hrange : Set.range s = (∅ : Set G) := Set.range_eq_empty s
  rw [hrange, Subgroup.closure_empty] at hs
  rw [Nat.card_le_one_iff_subsingleton]
  refine ⟨fun a b => ?_⟩
  have ha : a ∈ (⊥ : Subgroup G) := hs ▸ Subgroup.mem_top a
  have hb : b ∈ (⊥ : Subgroup G) := hs ▸ Subgroup.mem_top b
  rw [Subgroup.mem_bot] at ha hb
  rw [ha, hb]

/-- A cyclic group of exponent dividing `n` has order at most `n`. -/
theorem restrictedBurnside_rank_one {n : ℕ} (hn : 0 < n) : RestrictedBurnside 1 n := by
  refine ⟨n, fun G _ _ hgen hexp => ?_⟩
  obtain ⟨s, hs⟩ := hgen
  have hrange : Set.range s = {s 0} := by
    rw [Set.range_unique]
    rfl
  rw [hrange, ← Subgroup.zpowers_eq_closure] at hs
  have hcard : Nat.card G = orderOf (s 0) := by
    rw [← Nat.card_zpowers, hs, Subgroup.card_top]
  rw [hcard]
  exact Nat.le_of_dvd hn (orderOf_dvd_of_pow_eq_one (hexp (s 0)))

/-- In a group of exponent dividing `2` every element is its own inverse. -/
theorem inv_eq_self_of_sq (G : Type) [Group G] (h2 : HasExponentDividing 2 G) (g : G) :
    g⁻¹ = g := by
  have h := h2 g
  rw [pow_two] at h
  exact inv_eq_of_mul_eq_one_right h

/-- A group of exponent dividing `2` is commutative. -/
theorem mul_comm_of_sq (G : Type) [Group G] (h2 : HasExponentDividing 2 G) (a b : G) :
    a * b = b * a := by
  calc a * b = (a * b)⁻¹ := (inv_eq_self_of_sq G h2 _).symm
    _ = b⁻¹ * a⁻¹ := mul_inv_rev a b
    _ = b * a := by rw [inv_eq_self_of_sq G h2, inv_eq_self_of_sq G h2]

/-- A finite group of exponent dividing `2` generated by `m` elements has order at most `2 ^ m`:
the base case `n = 2` of the restricted Burnside problem. -/
theorem restrictedBurnside_exponent_two (m : ℕ) : RestrictedBurnside m 2 := by
  refine ⟨2 ^ m, fun G _ _ hgen hexp => ?_⟩
  obtain ⟨s, hs⟩ := hgen
  letI : CommGroup G :=
    { (inferInstance : Group G) with mul_comm := mul_comm_of_sq G hexp }
  classical
  have hsurj : Function.Surjective fun T : Finset (Fin m) => ∏ i ∈ T, s i := by
    intro g
    have hg : g ∈ Subgroup.closure (Set.range s) := hs ▸ Subgroup.mem_top g
    induction hg using Subgroup.closure_induction with
    | mem x hx =>
        obtain ⟨i, rfl⟩ := hx
        exact ⟨{i}, by simp⟩
    | one => exact ⟨∅, by simp⟩
    | mul x y _ _ hx hy =>
        obtain ⟨T, hT⟩ := hx
        obtain ⟨U, hU⟩ := hy
        refine ⟨T \ U ∪ U \ T, ?_⟩
        have hc : (∏ i ∈ T ∩ U, s i) * ∏ i ∈ T ∩ U, s i = 1 := by
          have := hexp (∏ i ∈ T ∩ U, s i)
          rwa [pow_two] at this
        simp only at hT hU ⊢
        rw [Finset.prod_union Finset.disjoint_sdiff_sdiff, ← hT, ← hU,
          ← Finset.prod_inter_mul_prod_diff T U s, ← Finset.prod_inter_mul_prod_diff U T s,
          Finset.inter_comm U T, mul_mul_mul_comm, hc, one_mul]
    | inv x _ hx =>
        obtain ⟨T, hT⟩ := hx
        exact ⟨T, by simp only at hT ⊢; rw [hT, inv_eq_self_of_sq G hexp]⟩
  calc Nat.card G ≤ Nat.card (Finset (Fin m)) := Nat.card_le_card_of_surjective _ hsurj
    _ = 2 ^ m := by simp [Nat.card_eq_fintype_card]

/-! ### The target statement -/

/-- **Restricted Burnside (Zelmanov), formalized statement together with a Lean-checked
reduction and the elementary base cases.**

The four components are:

1. the reduction of the restricted Burnside problem for `(m, n)` to a uniform bound on the finite
   quotients of the single free Burnside group `B(m, n)`;
2. the base case of exponent `1`;
3. the base case of rank `0` and the base case of rank `1` (cyclic groups);
4. the base case of exponent `2`, where the bound is `2 ^ m`.

Zelmanov's full theorem — `RestrictedBurnside m n` for *all* `m` and `n` — is not proved here. -/
theorem zelmanov_restricted_burnside :
    (∀ m n : ℕ, RestrictedBurnside m n ↔ BoundedBurnsideQuotients m n) ∧
    (∀ m : ℕ, RestrictedBurnside m 1) ∧
    (∀ n : ℕ, RestrictedBurnside 0 n) ∧
    (∀ n : ℕ, 0 < n → RestrictedBurnside 1 n) ∧
    (∀ m : ℕ, RestrictedBurnside m 2) :=
  ⟨restrictedBurnside_iff_boundedBurnsideQuotients, restrictedBurnside_exponent_one,
    restrictedBurnside_rank_zero, fun _ hn => restrictedBurnside_rank_one hn,
    restrictedBurnside_exponent_two⟩

end Frontier

