/-
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

namespace PCA.Cert

/-!
## An abstract model of Ed25519 signature verification

We model the group-theoretic core of Ed25519 (the part an isolation engine's
certificate checker relies upon):

* `G` is the prime-order subgroup generated by the base point `B`, written
  additively, and equipped with a scalar action of `ZMod L` (`L` being the group
  order, i.e. the order of the base point).
* A secret key is a scalar `s : ZMod L`; the corresponding public key is
  `A = s • B`.
* A signature on a message `m` with nonce `r` is the pair `(R, S)` where
  `R = r • B` and `S = r + H(R, A, m) * s`.
* Verification of `(R, S)` against `A` checks the standard equation
  `S • B = R + H(R, A, m) • A`.

The hash function `H` is left completely abstract (an arbitrary function), so no
property of SHA-512 is assumed anywhere.
-/

variable {L : ℕ} {G : Type*} {Msg : Type*}

/-- The public key associated with the secret scalar `s`. -/
def pubKey [AddCommGroup G] [Module (ZMod L) G] (B : G) (s : ZMod L) : G := s • B

/-- The Ed25519 verification equation for the signature `(R, S)` on message `m`
under public key `A`, with challenge hash `H`. -/
def Verify [AddCommGroup G] [Module (ZMod L) G] (B : G)
    (H : G → G → Msg → ZMod L) (A : G) (R : G) (S : ZMod L) (m : Msg) : Prop :=
  S • B = R + H R A m • A

/-- Honest signing: with nonce `r` and secret key `s`, the signature on `m` is
`(r • B, r + H(R, A, m) * s)`. -/
def sign [AddCommGroup G] [Module (ZMod L) G] (B : G)
    (H : G → G → Msg → ZMod L) (s r : ZMod L) (m : Msg) : G × ZMod L :=
  (r • B, r + H (r • B) (pubKey B s) m * s)

/-- **Soundness (and completeness) of Ed25519 verification.**

Assuming the base point `B` has order exactly `L` in the strong sense that
`x ↦ x • B` is injective on `ZMod L` (true for the prime-order subgroup
generated by the Ed25519 base point), a pair `(r • B, S)` passes the
verification equation against the public key `s • B` *if and only if* the
scalar `S` is exactly the one produced by honest signing with nonce `r` and
secret key `s`.

The `←` direction is completeness of the scheme; the `→` direction is
soundness: no other scalar `S` can be accepted for a given nonce commitment. -/
theorem ed25519_verify_sound [AddCommGroup G] [Module (ZMod L) G] {B : G}
    (hB : Function.Injective (fun x : ZMod L => x • B))
    (H : G → G → Msg → ZMod L) (s r S : ZMod L) (m : Msg) :
    Verify B H (pubKey B s) (r • B) S m ↔
      S = r + H (r • B) (pubKey B s) m * s := by
  unfold Verify pubKey
  rw [smul_smul, ← add_smul]
  exact hB.eq_iff

/-- Completeness: an honestly generated Ed25519 signature always verifies. -/
theorem ed25519_verify_complete [AddCommGroup G] [Module (ZMod L) G] {B : G}
    (H : G → G → Msg → ZMod L) (s r : ZMod L) (m : Msg) :
    Verify B H (pubKey B s) (sign B H s r m).1 (sign B H s r m).2 m := by
  unfold Verify sign pubKey
  simp [smul_smul, add_smul]

/-- Strict soundness restated: acceptance pins down the signature scalar
uniquely, hence two accepted signatures sharing a nonce commitment coincide. -/
theorem ed25519_verify_unique [AddCommGroup G] [Module (ZMod L) G] {B : G}
    (hB : Function.Injective (fun x : ZMod L => x • B))
    (H : G → G → Msg → ZMod L) (s r S S' : ZMod L) (m : Msg)
    (h : Verify B H (pubKey B s) (r • B) S m)
    (h' : Verify B H (pubKey B s) (r • B) S' m) :
    S = S' := by
  rw [ed25519_verify_sound hB] at h h'
  rw [h, h']

/-- Sanity check that the hypotheses above are satisfiable (the model is not
vacuous): in the cyclic group `ZMod L` with base point `1`, scalar
multiplication by the base point is injective. -/
example (L : ℕ) : Function.Injective (fun x : ZMod L => x • (1 : ZMod L)) := by
  intro x y h
  simpa using h

end PCA.Cert

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

