import Mathlib

/-!
# Goldbach Wheel K 2 631
Category: Brockian Corpus
Target: Brockian.GoldbachWheelK2_631
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option relaxedAutoImplicit false
set_option autoImplicit false

namespace Brockian

/-- **Goldbach wheel, K = 2, modulus 631.**
Every even natural number `n` with `4 ≤ n ≤ 631` is a sum of two primes.
(Since `n` is even, the bound `n ≤ 631` means `n ≤ 630`.)
The proof is an explicit finite verification: for each even `n` in range a
concrete pair of primes summing to `n` is exhibited. -/
theorem GoldbachWheelK2_631 (n : ℕ) (h4 : 4 ≤ n) (hn : n ≤ 631) (he : Even n) :
    ∃ p q : ℕ, Nat.Prime p ∧ Nat.Prime q ∧ n = p + q := by
  obtain ⟨k, rfl⟩ := he
  have hk1 : 2 ≤ k := by omega
  have hk2 : k ≤ 315 := by omega
  clear h4 hn
  interval_cases k
  · exact ⟨2, 2, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 3, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 5, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 7, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 7, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 11, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 13, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 13, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 17, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 19, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 19, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 23, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 23, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 23, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 29, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 31, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 31, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 31, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 37, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 37, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 41, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 43, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 43, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 47, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 47, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 47, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 53, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 53, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 53, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 59, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 61, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 61, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 61, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 67, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 67, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 71, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 73, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 73, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 73, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 79, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 79, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 83, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 83, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 83, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 89, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 89, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 89, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 79, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 97, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 97, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 101, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 107, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 127, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 127, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 131, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 131, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 131, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 137, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 139, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 139, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 139, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 137, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 139, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 149, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 151, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 151, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 151, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 157, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 157, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 157, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 163, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 163, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 167, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 167, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 167, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 173, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 173, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 173, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 191, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 193, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 193, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 197, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 197, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 197, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 223, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 223, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 227, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 229, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 229, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 233, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 233, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 233, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 239, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 241, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 241, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 241, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 239, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 241, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 257, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 257, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 257, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 263, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 263, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 263, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 269, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 271, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 271, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 271, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 277, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 277, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 281, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 281, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 277, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 307, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 307, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 311, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 313, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 313, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 313, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 313, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 331, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 331, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 331, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 337, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 337, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 337, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨29, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 337, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 347, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 349, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 349, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 353, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 353, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 353, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 359, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 359, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 359, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 349, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 379, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 379, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 383, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 383, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 383, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 379, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 397, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 397, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 401, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 401, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 401, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 397, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 401, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 419, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 421, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 421, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 421, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 419, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 421, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 431, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 433, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 433, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 433, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 439, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 439, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 443, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 443, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 443, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 449, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 449, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 449, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 439, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 457, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 457, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 461, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 463, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 463, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 463, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 479, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 479, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 479, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 457, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 487, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 487, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 491, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 491, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 491, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 487, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 541, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 541, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 541, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 547, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 547, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 547, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨47, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 547, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 563, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 563, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 563, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 569, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 571, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 571, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 571, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 577, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 577, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 577, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 569, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 577, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 587, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 587, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 587, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 599, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 601, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 601, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 601, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 607, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 607, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 607, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 613, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 613, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 617, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 617, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 619, by norm_num, by norm_num, by norm_num⟩

end Brockian

