import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

/-!
# Lieb–Robinson bound: an effective light cone for local spin dynamics

We work in an arbitrary C\*-algebra `A` (e.g. the algebra of observables of a finite
spin system, `Matrix (Fin n) (Fin n) ℂ`).  Given a self-adjoint Hamiltonian `H : A`,
the Heisenberg dynamics is `τ_t(a) = e^{itH} a e^{-itH}`.

The base case of the Lieb–Robinson estimate is the linear-in-time bound

`‖⁅τ_t a, b⁆‖ ≤ ‖⁅a, b⁆‖ + 2 |t| ‖a‖ ‖⁅H, b⁆‖`,

which is the first step of the standard iteration producing the light cone: if `a` and
`b` are supported on disjoint regions then `⁅a, b⁆ = 0`, and only those terms of a local
Hamiltonian `H` that overlap the support of `b` contribute to `⁅H, b⁆`.  Hence the
commutator of `b` with the evolved observable can only grow at a rate set by the local
interaction strength — an effective light cone.
-/

namespace Frontier

open NormedSpace

variable {A : Type*} [CStarAlgebra A]

/-- `NormedSpace.exp` lemmas in Mathlib are phrased over `ℚ`-normed algebras; every complex
normed algebra is one by restriction of scalars. -/
noncomputable local instance normedAlgebraRatOfCStarAlgebra (A : Type*) [CStarAlgebra A] :
    NormedAlgebra ℚ A := .restrictScalars ℚ ℂ A

/-- The one-parameter unitary group `t ↦ e^{i t H}` generated by `H`. -/
noncomputable def uGroup (H : A) (t : ℝ) : A := exp (t • (Complex.I • H))

/-- The Heisenberg evolution `τ_t(a) = e^{itH} a e^{-itH}` of the observable `a`. -/
noncomputable def heisenberg (H : A) (t : ℝ) (a : A) : A :=
  uGroup H t * a * uGroup H (-t)

@[simp] lemma uGroup_zero (H : A) : uGroup H 0 = 1 := by
  simp [uGroup]

@[simp] lemma heisenberg_zero (H a : A) : heisenberg H 0 a = a := by
  simp [heisenberg]

lemma uGroup_mul (H : A) (s t : ℝ) : uGroup H s * uGroup H t = uGroup H (s + t) := by
  rw [uGroup, uGroup, uGroup, ← exp_add_of_commute, add_smul]
  exact (Commute.refl _).smul_left _ |>.smul_right _

lemma uGroup_mul_neg (H : A) (t : ℝ) : uGroup H t * uGroup H (-t) = 1 := by
  rw [uGroup_mul]; simp

lemma uGroup_neg_mul (H : A) (t : ℝ) : uGroup H (-t) * uGroup H t = 1 := by
  rw [uGroup_mul]; simp

lemma uGroup_mem_unitary {H : A} (hH : IsSelfAdjoint H) (t : ℝ) : uGroup H t ∈ unitary A := by
  apply exp_mem_unitary_of_mem_skewAdjoint
  have h : star (Complex.I • H) = -(Complex.I • H) := hH.smul_mem_skewAdjoint Complex.conj_I
  rw [skewAdjoint.mem_iff, star_smul, star_trivial, h, smul_neg]

/-- Conjugation by the unitary group preserves the norm. -/
lemma norm_conj_uGroup {H : A} (hH : IsSelfAdjoint H) (t : ℝ) (x : A) :
    ‖uGroup H t * x * uGroup H (-t)‖ = ‖x‖ := by
  rw [CStarRing.norm_mul_mem_unitary _ (uGroup_mem_unitary hH (-t)),
    CStarRing.norm_mem_unitary_mul _ (uGroup_mem_unitary hH t)]

lemma hasDerivAt_uGroup (H : A) (t : ℝ) :
    HasDerivAt (uGroup H) (uGroup H t * (Complex.I • H)) t :=
  hasDerivAt_exp_smul_const (𝕂 := ℝ) (Complex.I • H) t

lemma commute_uGroup_gen (H : A) (t : ℝ) :
    uGroup H t * (Complex.I • H) = (Complex.I • H) * uGroup H t := by
  rw [uGroup]
  exact ((Commute.refl (Complex.I • H)).smul_left t).exp_left.eq

/-- The Heisenberg equation of motion: `d/dt τ_t(b) = τ_t(i ⁅H, b⁆)`. -/
lemma hasDerivAt_heisenberg (H : A) (b : A) (t : ℝ) :
    HasDerivAt (fun s : ℝ => heisenberg H s b)
      (uGroup H t * (Complex.I • ⁅H, b⁆) * uGroup H (-t)) t := by
  have h1 : HasDerivAt (fun s : ℝ => uGroup H s * b)
      (uGroup H t * (Complex.I • H) * b) t := (hasDerivAt_uGroup H t).mul_const b
  have h2 : HasDerivAt (fun s : ℝ => uGroup H (-s))
      (-(uGroup H (-t) * (Complex.I • H))) t := by
    have := (hasDerivAt_uGroup H (-t)).scomp t (hasDerivAt_neg t)
    simpa using this
  have h3 := h1.mul h2
  convert h3 using 1
  have hc : uGroup H (-t) * (Complex.I • H) = (Complex.I • H) * uGroup H (-t) :=
    commute_uGroup_gen H (-t)
  rw [Ring.lie_def, smul_sub, mul_sub, sub_mul]
  rw [mul_neg, hc]
  simp only [mul_assoc, smul_mul_assoc, mul_smul_comm]
  ring_nf
  rw [sub_eq_add_neg]

/-- Base bound: the observable `b` moves at most linearly in time, at a rate given by
`‖⁅H, b⁆‖`. -/
lemma norm_heisenberg_sub_le {H : A} (hH : IsSelfAdjoint H) (b : A) (t : ℝ) :
    ‖heisenberg H t b - b‖ ≤ |t| * ‖⁅H, b⁆‖ := by
  have hb : heisenberg H 0 b = b := heisenberg_zero H b
  have key : ‖(fun s : ℝ => heisenberg H s b) t - (fun s : ℝ => heisenberg H s b) 0‖
      ≤ ‖⁅H, b⁆‖ * ‖t - 0‖ := by
    apply Convex.norm_image_sub_le_of_norm_hasDerivWithin_le
      (f := fun s : ℝ => heisenberg H s b)
      (f' := fun s : ℝ => uGroup H s * (Complex.I • ⁅H, b⁆) * uGroup H (-s))
      (s := Set.univ)
    · intro s _
      exact ((hasDerivAt_heisenberg H b s).hasDerivWithinAt)
    · intro s _
      rw [norm_conj_uGroup hH, norm_smul]
      simp
    · exact convex_univ
    · trivial
    · trivial
  simp only [hb, sub_zero, Real.norm_eq_abs] at key
  linarith [key]

/-- The elementary bound on the norm of a commutator. -/
lemma norm_lie_le (x y : A) : ‖⁅x, y⁆‖ ≤ 2 * ‖x‖ * ‖y‖ := by
  rw [Ring.lie_def]
  calc ‖x * y - y * x‖ ≤ ‖x * y‖ + ‖y * x‖ := norm_sub_le _ _
    _ ≤ ‖x‖ * ‖y‖ + ‖y‖ * ‖x‖ := by gcongr <;> exact norm_mul_le _ _
    _ = 2 * ‖x‖ * ‖y‖ := by ring

/-- Conjugating the commutator: `⁅τ_t a, b⁆ = τ_t ⁅a, τ_{-t} b⁆`. -/
lemma lie_heisenberg_eq (H : A) (a b : A) (t : ℝ) :
    ⁅heisenberg H t a, b⁆
      = uGroup H t * ⁅a, heisenberg H (-t) b⁆ * uGroup H (-t) := by
  have h1 : uGroup H t * uGroup H (-t) = 1 := uGroup_mul_neg H t
  have h2 : uGroup H (-t) * uGroup H t = 1 := uGroup_neg_mul H t
  set u := uGroup H t
  set v := uGroup H (-t)
  simp only [heisenberg, Ring.lie_def, neg_neg]
  have expand : u * (a * (v * b * u) - v * b * u * a) * v
      = (u * a * v) * b * (u * v) - (u * v) * b * (u * a * v) := by
    noncomm_ring
  rw [expand, h1, one_mul, mul_one]

/-- **Lieb–Robinson bound (base case).**

Let `H` be a self-adjoint Hamiltonian in a C\*-algebra of observables and let
`τ_t(a) = e^{itH} a e^{-itH}` be the associated Heisenberg dynamics.  Then for all
observables `a`, `b` and all times `t`,

`‖⁅τ_t a, b⁆‖ ≤ ‖⁅a, b⁆‖ + 2 |t| ‖a‖ ‖⁅H, b⁆‖`.

If `a` and `b` are supported on disjoint regions, the first term vanishes, and for a
Hamiltonian built out of local interactions only the terms overlapping the support of
`b` contribute to `‖⁅H, b⁆‖`: the commutator can leak out of the support of `b` only at
a finite speed, an effective light cone. -/
theorem lieb_robinson {H : A} (hH : IsSelfAdjoint H) (a b : A) (t : ℝ) :
    ‖⁅heisenberg H t a, b⁆‖ ≤ ‖⁅a, b⁆‖ + 2 * |t| * ‖a‖ * ‖⁅H, b⁆‖ := by
  rw [lie_heisenberg_eq, norm_conj_uGroup hH]
  have hsplit : ⁅a, heisenberg H (-t) b⁆ = ⁅a, b⁆ + ⁅a, heisenberg H (-t) b - b⁆ := by
    rw [lie_sub]; abel
  have hnorm : ‖⁅a, heisenberg H (-t) b - b⁆‖ ≤ 2 * ‖a‖ * ‖heisenberg H (-t) b - b‖ :=
    norm_lie_le _ _
  have hmove : ‖heisenberg H (-t) b - b‖ ≤ |t| * ‖⁅H, b⁆‖ := by
    simpa using norm_heisenberg_sub_le hH b (-t)
  have ha : (0:ℝ) ≤ 2 * ‖a‖ := by positivity
  calc ‖⁅a, heisenberg H (-t) b⁆‖ ≤ ‖⁅a, b⁆‖ + ‖⁅a, heisenberg H (-t) b - b⁆‖ := by
        rw [hsplit]; exact norm_add_le _ _
    _ ≤ ‖⁅a, b⁆‖ + 2 * ‖a‖ * (|t| * ‖⁅H, b⁆‖) := by
        have := mul_le_mul_of_nonneg_left hmove ha
        linarith [hnorm]
    _ = ‖⁅a, b⁆‖ + 2 * |t| * ‖a‖ * ‖⁅H, b⁆‖ := by ring

/-- If the Hamiltonian is a sum of interaction terms `h z`, `z ∈ S`, and only the terms
indexed by `N` fail to commute with `b`, then `‖⁅H, b⁆‖` is controlled by the strength of
the interactions touching the support of `b`. -/
lemma norm_lie_sum_le {ι : Type*} (S N : Finset ι) (h : ι → A) (b : A)
    (hloc : ∀ z ∈ S, z ∉ N → ⁅h z, b⁆ = 0) :
    ‖⁅∑ z ∈ S, h z, b⁆‖ ≤ 2 * ‖b‖ * ∑ z ∈ S ∩ N, ‖h z‖ := by
  rw [sum_lie]
  have hres : ∑ z ∈ S, ⁅h z, b⁆ = ∑ z ∈ S ∩ N, ⁅h z, b⁆ := by
    refine (Finset.sum_subset Finset.inter_subset_left ?_).symm
    intro z hz hznot
    exact hloc z hz (fun hzN => hznot (Finset.mem_inter.mpr ⟨hz, hzN⟩))
  rw [hres]
  calc ‖∑ z ∈ S ∩ N, ⁅h z, b⁆‖ ≤ ∑ z ∈ S ∩ N, ‖⁅h z, b⁆‖ := norm_sum_le _ _
    _ ≤ ∑ z ∈ S ∩ N, 2 * ‖b‖ * ‖h z‖ := by
        refine Finset.sum_le_sum fun z _ => ?_
        have := norm_lie_le (h z) b
        linarith
    _ = 2 * ‖b‖ * ∑ z ∈ S ∩ N, ‖h z‖ := by rw [Finset.mul_sum]

/-- **Effective light cone for a local Hamiltonian.**

Let `H = ∑_{z ∈ S} h z` be a sum of interaction terms, let `a`, `b` be observables with
`⁅a, b⁆ = 0` (disjoint supports), and suppose that every interaction term outside the
neighbourhood `N` of the support of `b` commutes with `b`.  Then

`‖⁅τ_t a, b⁆‖ ≤ 4 |t| ‖a‖ ‖b‖ ∑_{z ∈ S ∩ N} ‖h z‖`,

so the commutator can become nonzero only after a time proportional to the distance
between the supports divided by the interaction strength: a linear light cone. -/
theorem lieb_robinson_local {ι : Type*} {H : A} (hH : IsSelfAdjoint H) (a b : A) (t : ℝ)
    (S N : Finset ι) (h : ι → A) (hHsum : H = ∑ z ∈ S, h z)
    (hab : ⁅a, b⁆ = 0) (hloc : ∀ z ∈ S, z ∉ N → ⁅h z, b⁆ = 0) :
    ‖⁅heisenberg H t a, b⁆‖ ≤ 4 * |t| * ‖a‖ * ‖b‖ * ∑ z ∈ S ∩ N, ‖h z‖ := by
  have hmain := lieb_robinson hH a b t
  rw [hab, norm_zero, zero_add] at hmain
  have hHb : ‖⁅H, b⁆‖ ≤ 2 * ‖b‖ * ∑ z ∈ S ∩ N, ‖h z‖ := by
    rw [hHsum]; exact norm_lie_sum_le S N h b hloc
  have hc : (0:ℝ) ≤ 2 * |t| * ‖a‖ := by positivity
  calc ‖⁅heisenberg H t a, b⁆‖ ≤ 2 * |t| * ‖a‖ * ‖⁅H, b⁆‖ := hmain
    _ ≤ 2 * |t| * ‖a‖ * (2 * ‖b‖ * ∑ z ∈ S ∩ N, ‖h z‖) := mul_le_mul_of_nonneg_left hHb hc
    _ = 4 * |t| * ‖a‖ * ‖b‖ * ∑ z ∈ S ∩ N, ‖h z‖ := by ring

/-- **Strict light cone.** If `b` commutes with `a` and with the Hamiltonian, then it
commutes with the evolved observable at all times. -/
theorem lie_heisenberg_eq_zero {H : A} (hH : IsSelfAdjoint H) {a b : A}
    (hab : ⁅a, b⁆ = 0) (hHb : ⁅H, b⁆ = 0) (t : ℝ) :
    ⁅heisenberg H t a, b⁆ = 0 := by
  have := lieb_robinson hH a b t
  rw [hab, hHb] at this
  simpa using norm_le_zero_iff.mp (by simpa using this)

/-- The setting is non-vacuous: the theorem applies verbatim to the observable algebra of a
finite spin system, i.e. to the bounded operators on a finite-dimensional Hilbert space. -/
example (n : ℕ) (H a b : EuclideanSpace ℂ (Fin n) →L[ℂ] EuclideanSpace ℂ (Fin n))
    (hH : IsSelfAdjoint H) (t : ℝ) :
    ‖⁅heisenberg H t a, b⁆‖ ≤ ‖⁅a, b⁆‖ + 2 * |t| * ‖a‖ * ‖⁅H, b⁆‖ :=
  lieb_robinson hH a b t

end Frontier

