/-
# Hironaka Resolution
Category: Frontier Math
Target: Math2.hironaka_resolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
-- (The header above uses `/-` rather than `/-!` only because Lean 4 does not permit a module
-- docstring to precede the `import` command; the same text is repeated as the module docstring
-- immediately after the imports below.)

import Mathlib

/-!
# Hironaka Resolution
Category: Frontier Math
Target: Math2.hironaka_resolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/


open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

universe u

namespace Math2

open Polynomial

/-!
## Resolution of singularities for monomial curve singularities

Full Hironaka resolution of singularities in characteristic zero is not formalized here (it is
not available in Mathlib in any form).  What is proved below is a genuine, complete special case
of it, in the classical dimension-one situation where resolution is achieved by normalization:

for coprime exponents `a, b ≥ 2` over a field `k` of characteristic zero, the affine monomial
curve `C_{a,b}` with coordinate ring `R = k[t^a, t^b] ⊆ k[t]` (the image of the parametrization
`t ↦ (t^a, t^b)`, i.e. the curve `y^a = x^b`) is singular, and the affine line `Spec k[t]`, which
is a *smooth* `k`-variety, together with the finite (hence proper) birational morphism
`Spec k[t] → C_{a,b}` dual to the inclusion `R ↪ k[t]`, is a resolution of its singularities.

The defining features of a resolution are recorded in `Math2.hironaka_resolution`:

* the resolving variety `Spec k[t]` is smooth over `k` (`Algebra.Smooth k k[X]`);
* the resolving morphism is finite, hence proper (`Module.Finite R k[X]`);
* it is birational: the subfield of `k(t)` generated by (the image of) `R` is all of `k(t)`;
* it is a nontrivial resolution: the curve really is singular.  This is witnessed both concretely
  (`t` is integral over `R` but does not lie in `R`) and abstractly: `R` is not integrally closed
  in its fraction field (`¬ IsIntegrallyClosed R`), i.e. the curve is not normal, hence not
  regular.

The characteristic zero hypothesis is part of the statement of Hironaka's theorem and is kept,
although this special case in fact holds over any field.
-/

/-- The coordinate ring `k[t^a, t^b] ⊆ k[t]` of the affine monomial curve `y^a = x^b`, i.e. the
image of the parametrization `t ↦ (t^a, t^b)`. -/
noncomputable def monomialCurveRing (k : Type u) [Field k] (a b : ℕ) : Subalgebra k k[X] :=
  Algebra.adjoin k {X ^ a, X ^ b}

/-- The polynomial ring is a smooth `k`-algebra: the affine line is a smooth variety. -/
theorem smooth_polynomial (k : Type u) [Field k] : Algebra.Smooth k k[X] :=
  ⟨Algebra.FormallySmooth.of_equiv (MvPolynomial.pUnitAlgEquiv.{u, u} k),
    Algebra.FinitePresentation.polynomial k k⟩

/-- `k[t]` is a finite module over `k[t^a, t^b]`: the resolving morphism is finite, hence
proper. -/
theorem finite_monomialCurveRing (k : Type u) [Field k] (a b : ℕ) (ha : 0 < a) :
    Module.Finite (monomialCurveRing k a b) k[X] := by
  classical
  refine ⟨⟨(Finset.range a).image (fun i => (X : k[X]) ^ i), ?_⟩⟩
  rw [eq_top_iff]
  rintro p -
  induction p using Polynomial.induction_on' with
  | add p q hp hq => exact Submodule.add_mem _ hp hq
  | monomial n c =>
      have hXa : (X : k[X]) ^ a ∈ monomialCurveRing k a b := Algebra.subset_adjoin (by simp)
      have hc : (C c : k[X]) ∈ monomialCurveRing k a b := Subalgebra.algebraMap_mem _ c
      have key : (monomial n c : k[X]) = (⟨C c * ((X : k[X]) ^ a) ^ (n / a),
          Subalgebra.mul_mem _ hc (Subalgebra.pow_mem _ hXa _)⟩ :
            monomialCurveRing k a b) • (X : k[X]) ^ (n % a) := by
        show _ = (C c * ((X : k[X]) ^ a) ^ (n / a)) * (X : k[X]) ^ (n % a)
        rw [mul_assoc, ← pow_mul, ← pow_add, Nat.div_add_mod, Polynomial.C_mul_X_pow_eq_monomial]
      rw [key]
      exact Submodule.smul_mem _ _ (Submodule.subset_span
        (Finset.mem_coe.2 (Finset.mem_image.2 ⟨n % a, Finset.mem_range.2 (Nat.mod_lt _ ha), rfl⟩)))

/-- The subalgebra of polynomials with vanishing linear coefficient. -/
def noLinearTerm (k : Type u) [Field k] : Subalgebra k k[X] where
  carrier := {p | p.coeff 1 = 0}
  mul_mem' := by
    intro p q hp hq
    simp only [Set.mem_setOf_eq] at *
    simp [Polynomial.coeff_mul, Finset.Nat.antidiagonal_succ, hp, hq]
  add_mem' := by
    intro p q hp hq
    simp only [Set.mem_setOf_eq] at *
    simp [hp, hq]
  algebraMap_mem' := by
    intro c
    simp [Set.mem_setOf_eq, Polynomial.algebraMap_eq]

/-- The coordinate `t` does not belong to `k[t^a, t^b]` when `a, b ≥ 2`. -/
theorem X_notMem_monomialCurveRing (k : Type u) [Field k] (a b : ℕ) (ha : 2 ≤ a) (hb : 2 ≤ b) :
    (X : k[X]) ∉ monomialCurveRing k a b := by
  intro h
  have hsub : monomialCurveRing k a b ≤ noLinearTerm k := by
    rw [monomialCurveRing]
    apply Algebra.adjoin_le
    rintro x (rfl | rfl) <;>
      simp [noLinearTerm, Set.mem_setOf_eq, Polynomial.coeff_X_pow] <;> omega
  have hmem := hsub h
  simp [noLinearTerm, Set.mem_setOf_eq] at hmem

/-- The coordinate `t` is integral over `k[t^a, t^b]`. -/
theorem X_isIntegral_monomialCurveRing (k : Type u) [Field k] (a b : ℕ) (ha : 0 < a) :
    IsIntegral (monomialCurveRing k a b) (X : k[X]) := by
  have hXa : (X : k[X]) ^ a ∈ monomialCurveRing k a b := Algebra.subset_adjoin (by simp)
  refine ⟨Polynomial.X ^ a - Polynomial.C ⟨(X : k[X]) ^ a, hXa⟩, ?_, ?_⟩
  · exact (Polynomial.monic_X_pow a).sub_of_left (by
      refine lt_of_le_of_lt Polynomial.degree_C_le ?_
      simpa using ha)
  · simp

/-- Bézout, in the form needed below: if `a` and `b` are coprime and `a > 0`, then
`a * u = 1 + b * w` for some natural numbers `u, w`. -/
theorem exists_bezout_nat (a b : ℕ) (ha : 0 < a) (hab : Nat.Coprime a b) :
    ∃ u w : ℕ, a * u = 1 + b * w := by
  rcases Nat.eq_zero_or_pos b with rfl | hb
  · exact ⟨1, 0, by simpa using (Nat.coprime_zero_right a).1 hab⟩
  · have hbez : (1 : ℤ) = a * Nat.gcdA a b + b * Nat.gcdB a b := by
      have h := Nat.gcd_eq_gcd_ab a b
      rw [hab] at h
      exact_mod_cast h
    set s := Nat.gcdA a b
    set t := Nat.gcdB a b
    set N : ℤ := |s| + |t| + 1 with hN
    have hb' : (1 : ℤ) ≤ b := by exact_mod_cast hb
    have ha' : (1 : ℤ) ≤ a := by exact_mod_cast ha
    have hu : 0 ≤ s + b * N := by
      nlinarith [abs_nonneg s, abs_nonneg t, le_abs_self s, neg_abs_le s]
    have hw : 0 ≤ a * N - t := by
      nlinarith [abs_nonneg s, abs_nonneg t, le_abs_self t, neg_abs_le t]
    refine ⟨(s + b * N).toNat, (a * N - t).toNat, ?_⟩
    have hmain : (a : ℤ) * (s + b * N) = 1 + b * (a * N - t) := by ring_nf; linarith [hbez]
    zify [hu, hw]
    simpa [Int.toNat_of_nonneg hu, Int.toNat_of_nonneg hw] using hmain

/-- Birationality: the subfield of `k(t)` generated by `t^a` and `t^b` is all of `k(t)` when
`a` and `b` are coprime. -/
theorem adjoin_pow_eq_top (k : Type u) [Field k] (a b : ℕ) (ha : 0 < a) (hab : Nat.Coprime a b) :
    IntermediateField.adjoin k {(RatFunc.X : RatFunc k) ^ a, (RatFunc.X : RatFunc k) ^ b} = ⊤ := by
  obtain ⟨u, w, huw⟩ := exists_bezout_nat a b ha hab
  set F := IntermediateField.adjoin k {(RatFunc.X : RatFunc k) ^ a, (RatFunc.X : RatFunc k) ^ b}
    with hF
  have hXa : (RatFunc.X : RatFunc k) ^ a ∈ F := IntermediateField.subset_adjoin _ _ (by simp)
  have hXb : (RatFunc.X : RatFunc k) ^ b ∈ F := IntermediateField.subset_adjoin _ _ (by simp)
  have hX0 : (RatFunc.X : RatFunc k) ≠ 0 := RatFunc.X_ne_zero
  have hXmem : (RatFunc.X : RatFunc k) ∈ F := by
    have h1 : ((RatFunc.X : RatFunc k) ^ a) ^ u
        = RatFunc.X * ((RatFunc.X : RatFunc k) ^ b) ^ w := by
      rw [← pow_mul, ← pow_mul, huw, pow_add, pow_one]
    have h2 : ((RatFunc.X : RatFunc k) ^ b) ^ w ≠ 0 := pow_ne_zero _ (pow_ne_zero _ hX0)
    have h3 : (RatFunc.X : RatFunc k)
        = ((RatFunc.X : RatFunc k) ^ a) ^ u * (((RatFunc.X : RatFunc k) ^ b) ^ w)⁻¹ := by
      field_simp
      exact h1.symm
    rw [h3]
    exact F.mul_mem (F.pow_mem hXa u) (F.inv_mem (F.pow_mem hXb w))
  have hpoly : ∀ p : k[X], algebraMap k[X] (RatFunc k) p ∈ F := by
    intro p
    have hle : Algebra.adjoin k {(Polynomial.X : k[X])} ≤ Subalgebra.comap
        (IsScalarTower.toAlgHom k k[X] (RatFunc k)) F.toSubalgebra := by
      apply Algebra.adjoin_le
      rintro x rfl
      simpa [Subalgebra.mem_comap] using hXmem
    have hp : p ∈ Algebra.adjoin k {(Polynomial.X : k[X])} := by
      rw [Polynomial.adjoin_X]; trivial
    simpa [Subalgebra.mem_comap] using hle hp
  rw [eq_top_iff]
  rintro f -
  obtain ⟨x, y, -, rfl⟩ := IsFractionRing.div_surjective (A := k[X]) (K := RatFunc k) f
  exact F.div_mem (hpoly x) (hpoly y)

set_option synthInstance.maxHeartbeats 400000 in
/-- The coordinate ring `k[t^a, t^b]` of the monomial curve is **not** integrally closed in its
fraction field, when `a, b ≥ 2` are coprime: the element corresponding to `t` is integral over it
but does not belong to it.  Hence the curve `C_{a,b}` is not normal, and in particular (being a
one-dimensional variety) it is singular. -/
theorem not_isIntegrallyClosed_monomialCurveRing (k : Type u) [Field k] (a b : ℕ)
    (ha : 2 ≤ a) (hb : 2 ≤ b) (hab : Nat.Coprime a b) :
    ¬ IsIntegrallyClosed (monomialCurveRing k a b) := by
  have ha0 : 0 < a := lt_of_lt_of_le (by norm_num) ha
  obtain ⟨u, w, huw⟩ := exists_bezout_nat a b ha0 hab
  have hXnot := X_notMem_monomialCurveRing k a b ha hb
  intro hIC
  have hc : (X : k[X]) ^ a ∈ monomialCurveRing k a b := Algebra.subset_adjoin (by simp)
  have hd : (X : k[X]) ^ b ∈ monomialCurveRing k a b := Algebra.subset_adjoin (by simp)
  set c : monomialCurveRing k a b := ⟨(X : k[X]) ^ a, hc⟩ with hcdef
  set d : monomialCurveRing k a b := ⟨(X : k[X]) ^ b, hd⟩ with hddef
  have hinj : Function.Injective
      (algebraMap (monomialCurveRing k a b) (FractionRing (monomialCurveRing k a b))) :=
    IsFractionRing.injective _ _
  have hd0 : d ≠ 0 := fun h0 =>
    (pow_ne_zero b (Polynomial.X_ne_zero (R := k))) (congrArg Subtype.val h0)
  have hdw0 : algebraMap (monomialCurveRing k a b) (FractionRing (monomialCurveRing k a b))
      (d ^ w) ≠ 0 := (map_ne_zero_iff _ hinj).2 (pow_ne_zero w hd0)
  have hrel : (c ^ u) ^ a = c * (d ^ w) ^ a := by
    apply Subtype.ext
    push_cast
    rw [← pow_mul, ← pow_mul, ← pow_mul, ← pow_mul, ← pow_add, ← mul_assoc, ← mul_assoc, huw]
    ring
  set z : FractionRing (monomialCurveRing k a b) :=
    algebraMap (monomialCurveRing k a b) (FractionRing (monomialCurveRing k a b)) (c ^ u) /
      algebraMap (monomialCurveRing k a b) (FractionRing (monomialCurveRing k a b)) (d ^ w)
    with hz
  have hza : z ^ a
      = algebraMap (monomialCurveRing k a b) (FractionRing (monomialCurveRing k a b)) c := by
    have h1 : z ^ a * (algebraMap (monomialCurveRing k a b)
          (FractionRing (monomialCurveRing k a b)) (d ^ w)) ^ a
        = algebraMap (monomialCurveRing k a b) (FractionRing (monomialCurveRing k a b)) c
          * (algebraMap (monomialCurveRing k a b)
              (FractionRing (monomialCurveRing k a b)) (d ^ w)) ^ a := by
      rw [hz, div_pow, div_mul_cancel₀ _ (pow_ne_zero a hdw0), ← map_pow, hrel, map_mul, map_pow]
    exact mul_right_cancel₀ (pow_ne_zero a hdw0) h1
  have hint : IsIntegral (monomialCurveRing k a b) z := by
    refine ⟨Polynomial.X ^ a - Polynomial.C c, ?_, ?_⟩
    · exact (Polynomial.monic_X_pow a).sub_of_left (by
        refine lt_of_le_of_lt Polynomial.degree_C_le ?_
        simpa using ha0)
    · simp [hza]
  obtain ⟨r, hr⟩ := (IsIntegrallyClosed.isIntegral_iff (R := monomialCurveRing k a b)
    (K := FractionRing (monomialCurveRing k a b))).1 hint
  have hmul : algebraMap (monomialCurveRing k a b) (FractionRing (monomialCurveRing k a b))
        (r * d ^ w)
      = algebraMap (monomialCurveRing k a b) (FractionRing (monomialCurveRing k a b)) (c ^ u) := by
    rw [map_mul, hr, hz, div_mul_cancel₀ _ hdw0]
  have hRr : r * d ^ w = c ^ u := hinj hmul
  have hco : (r : k[X]) * (X : k[X]) ^ (b * w) = (X : k[X]) ^ (a * u) := by
    have h2 := congrArg (Subtype.val) hRr
    push_cast at h2
    rw [← pow_mul, ← pow_mul] at h2
    exact h2
  have hrx : (r : k[X]) = X := by
    have hx : (r : k[X]) * (X : k[X]) ^ (b * w) = X * (X : k[X]) ^ (b * w) := by
      rw [hco, huw, pow_add, pow_one]
    exact mul_right_cancel₀ (pow_ne_zero _ (Polynomial.X_ne_zero (R := k))) hx
  exact hXnot (hrx ▸ r.2)

/-- **Resolution of singularities for monomial curve singularities** (a complete special case of
Hironaka's theorem, in characteristic zero).

Let `k` be a field of characteristic zero and let `a, b ≥ 2` be coprime.  Consider the singular
affine curve `C_{a,b} : y^a = x^b`, whose coordinate ring is the monomial subalgebra
`R = k[t^a, t^b] ⊆ k[t]`.  Then the affine line `Spec k[t]` resolves its singularities:

1. `k[t]` is a smooth `k`-algebra, i.e. the resolving variety `Spec k[t]` is smooth;
2. `k[t]` is a finite `R`-module, i.e. the resolving morphism `Spec k[t] → C_{a,b}` is finite,
   in particular proper and surjective;
3. the subfield of `k(t)` generated by the image of `R` is all of `k(t)`, i.e. the morphism is
   birational;
4. the curve is genuinely singular: `t` is integral over `R` but is not an element of `R`, and
   consequently `R` is not integrally closed in its fraction field, i.e. `C_{a,b}` is not normal
   and hence (being a curve) not regular; in particular the resolution is not an isomorphism.

The characteristic zero assumption is the one appearing in Hironaka's theorem; this particular
case holds over an arbitrary field. -/
theorem hironaka_resolution (k : Type u) [Field k] [CharZero k] (a b : ℕ)
    (ha : 2 ≤ a) (hb : 2 ≤ b) (hab : Nat.Coprime a b) :
    Algebra.Smooth k k[X]
      ∧ Module.Finite (monomialCurveRing k a b) k[X]
      ∧ IntermediateField.adjoin k
          ((algebraMap k[X] (RatFunc k)) '' (monomialCurveRing k a b : Set k[X])) = ⊤
      ∧ IsIntegral (monomialCurveRing k a b) (X : k[X])
      ∧ (X : k[X]) ∉ monomialCurveRing k a b
      ∧ ¬ IsIntegrallyClosed (monomialCurveRing k a b) := by
  have ha0 : 0 < a := lt_of_lt_of_le (by norm_num) ha
  refine ⟨smooth_polynomial k, finite_monomialCurveRing k a b ha0, ?_,
    X_isIntegral_monomialCurveRing k a b ha0, X_notMem_monomialCurveRing k a b ha hb,
    not_isIntegrallyClosed_monomialCurveRing k a b ha hb hab⟩
  rw [eq_top_iff, ← adjoin_pow_eq_top k a b ha0 hab, IntermediateField.adjoin_le_iff]
  rintro x (rfl | rfl)
  · exact IntermediateField.subset_adjoin _ _
      ⟨(X : k[X]) ^ a, Algebra.subset_adjoin (by simp), by simp⟩
  · exact IntermediateField.subset_adjoin _ _
      ⟨(X : k[X]) ^ b, Algebra.subset_adjoin (by simp), by simp⟩

end Math2

