/-
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true

set_option grind.warning false

namespace Frontier

/-- `IsBurnsideQuotient m n G` says that the group `G` is generated by `m` elements and has
exponent dividing `n`. -/
def IsBurnsideQuotient (m n : ℕ) (G : Type) [Group G] : Prop :=
  (∀ g : G, g ^ n = 1) ∧ ∃ f : Fin m → G, Subgroup.closure (Set.range f) = ⊤

/-- The restricted Burnside property for the pair `(m, n)`: the orders of the finite groups
with `m` generators and exponent dividing `n` are bounded. -/
def RestrictedBurnside (m n : ℕ) : Prop :=
  ∃ B : ℕ, ∀ (G : Type) [Group G] [Finite G], IsBurnsideQuotient m n G → Nat.card G ≤ B

/-- A normal subgroup of the free group on `m` generators, of finite index, containing all
`n`-th powers: equivalently, the kernel of a map onto a finite `m`-generated group of
exponent dividing `n`. -/
structure IsBurnsideKernel (m n : ℕ) (N : Subgroup (FreeGroup (Fin m))) : Prop where
  normal : N.Normal
  index_ne_zero : N.index ≠ 0
  pow_mem : ∀ g : FreeGroup (Fin m), g ^ n ∈ N

/-- The free Burnside group `B(m, n)` has a largest finite quotient: there is a smallest
`Burnside kernel`, contained in all the others. -/
def HasUniversalFiniteQuotient (m n : ℕ) : Prop :=
  ∃ N : Subgroup (FreeGroup (Fin m)),
    IsBurnsideKernel m n N ∧ ∀ M : Subgroup (FreeGroup (Fin m)), IsBurnsideKernel m n M → N ≤ M

/-- The restricted Burnside property, for commutative groups. -/
def RestrictedBurnsideComm (m n : ℕ) : Prop :=
  ∀ (G : Type) [CommGroup G], IsBurnsideQuotient m n G → Nat.card G ≤ n ^ m

section Reduction

variable {m n : ℕ}

/-- The quotient of the free group by a normal subgroup containing all `n`-th powers is an
`m`-generated group of exponent dividing `n`. -/
theorem isBurnsideQuotient_quotient {N : Subgroup (FreeGroup (Fin m))} [N.Normal]
    (hpow : ∀ g : FreeGroup (Fin m), g ^ n ∈ N) :
    IsBurnsideQuotient m n (FreeGroup (Fin m) ⧸ N) := by
  constructor
  · intro q
    induction q using QuotientGroup.induction_on with
    | _ g =>
      rw [← QuotientGroup.mk_pow]
      exact (QuotientGroup.eq_one_iff _).mpr (hpow g)
  · refine ⟨fun i => QuotientGroup.mk (FreeGroup.of i), ?_⟩
    have h1 : Subgroup.map (QuotientGroup.mk' N)
        (Subgroup.closure (Set.range (FreeGroup.of : Fin m → FreeGroup (Fin m)))) =
        Subgroup.closure
          (Set.range fun i => (QuotientGroup.mk (FreeGroup.of i) : FreeGroup (Fin m) ⧸ N)) := by
      rw [MonoidHom.map_closure, ← Set.range_comp]
      rfl
    rw [FreeGroup.closure_range_of] at h1
    rw [← h1, Subgroup.map_top_of_surjective]
    exact QuotientGroup.mk'_surjective N

/-- A normal subgroup of finite index has a finite quotient. -/
theorem finite_quotient_of_index_ne_zero {N : Subgroup (FreeGroup (Fin m))} [N.Normal]
    (h : N.index ≠ 0) : Finite (FreeGroup (Fin m) ⧸ N) :=
  Nat.finite_of_card_ne_zero (by rwa [← Subgroup.index_eq_card])

/-- Conversely, any finite `m`-generated group of exponent dividing `n` gives a Burnside
kernel, namely the kernel of the corresponding surjection from the free group, whose index
is the order of the group. -/
theorem exists_kernel_of_isBurnsideQuotient (G : Type) [Group G] [Finite G]
    (hG : IsBurnsideQuotient m n G) :
    ∃ N : Subgroup (FreeGroup (Fin m)), IsBurnsideKernel m n N ∧ N.index = Nat.card G := by
  obtain ⟨hexp, f, hf⟩ := hG
  set phi := FreeGroup.lift f with hphi
  have hrange : phi.range = ⊤ := by rw [hphi, FreeGroup.range_lift_eq_closure, hf]
  have hidx : phi.ker.index = Nat.card G := by
    rw [Subgroup.index_ker, hrange, Subgroup.card_top]
  refine ⟨phi.ker, ⟨inferInstance, ?_, ?_⟩, hidx⟩
  · rw [hidx]
    exact Nat.card_pos.ne'
  · intro g
    simp [MonoidHom.mem_ker, hphi, hexp]

/-- Every Burnside kernel is the kernel of a map onto a finite `m`-generated group of
exponent dividing `n`, so under the restricted Burnside property its index is bounded. -/
theorem index_le_of_isBurnsideKernel {B : ℕ}
    (hB : ∀ (G : Type) [Group G] [Finite G], IsBurnsideQuotient m n G → Nat.card G ≤ B)
    {N : Subgroup (FreeGroup (Fin m))} (hN : IsBurnsideKernel m n N) : N.index ≤ B := by
  haveI := hN.normal
  haveI := finite_quotient_of_index_ne_zero hN.index_ne_zero
  have h := hB (FreeGroup (Fin m) ⧸ N) (isBurnsideQuotient_quotient hN.pow_mem)
  rwa [← Subgroup.index_eq_card] at h

/-- If the restricted Burnside property holds for exponent `n`, it holds for every divisor
of `n`. -/
theorem restrictedBurnside_of_dvd {d : ℕ} (hdvd : d ∣ n) (h : RestrictedBurnside m n) :
    RestrictedBurnside m d := by
  obtain ⟨B, hB⟩ := h
  obtain ⟨c, rfl⟩ := hdvd
  refine ⟨B, ?_⟩
  rintro G _ _ ⟨hexp, hgen⟩
  exact hB G ⟨fun g => by rw [pow_mul, hexp g, one_pow], hgen⟩

/-- If the restricted Burnside property holds for `m` generators, it holds for fewer
generators. -/
theorem restrictedBurnside_of_le {k : ℕ} (hk : k ≤ m) (h : RestrictedBurnside m n) :
    RestrictedBurnside k n := by
  obtain ⟨B, hB⟩ := h
  refine ⟨B, ?_⟩
  rintro G _ _ ⟨hexp, f, hf⟩
  classical
  refine hB G ⟨hexp, fun i : Fin m => if h : (i : ℕ) < k then f ⟨i, h⟩ else 1, ?_⟩
  have hsub : Set.range f ⊆
      Set.range (fun i : Fin m => if h : (i : ℕ) < k then f ⟨i, h⟩ else 1) := by
    rintro x ⟨j, rfl⟩
    refine ⟨⟨j, lt_of_lt_of_le j.2 hk⟩, ?_⟩
    simp [j.2]
  refine eq_top_iff.mpr ?_
  rw [← hf]
  exact Subgroup.closure_mono hsub

/-- **Reduction step.** The restricted Burnside property for `(m, n)` is equivalent to the
existence of a largest finite quotient of the free Burnside group `B(m, n)`. -/
theorem restrictedBurnside_iff_hasUniversalFiniteQuotient (m n : ℕ) :
    RestrictedBurnside m n ↔ HasUniversalFiniteQuotient m n := by
  constructor
  · rintro ⟨B, hB⟩
    set S : Set ℕ :=
      {k | ∃ N : Subgroup (FreeGroup (Fin m)), IsBurnsideKernel m n N ∧ N.index = k}
    have htop : IsBurnsideKernel m n (⊤ : Subgroup (FreeGroup (Fin m))) :=
      ⟨inferInstance, by simp, fun g => trivial⟩
    have hne : S.Nonempty := ⟨(⊤ : Subgroup (FreeGroup (Fin m))).index, ⟨⊤, htop, rfl⟩⟩
    have hbdd : BddAbove S := by
      refine ⟨B, ?_⟩
      rintro k ⟨N, hN, rfl⟩
      exact index_le_of_isBurnsideKernel hB hN
    obtain ⟨N, hN, hNk⟩ : sSup S ∈ S := Nat.sSup_mem hne hbdd
    refine ⟨N, hN, ?_⟩
    intro M hM
    haveI := hN.normal
    haveI := hM.normal
    have hinf : IsBurnsideKernel m n (N ⊓ M) :=
      ⟨inferInstance, Subgroup.index_inf_ne_zero hN.index_ne_zero hM.index_ne_zero,
        fun g => ⟨hN.pow_mem g, hM.pow_mem g⟩⟩
    have h1 : (N ⊓ M).index ≤ N.index := by
      rw [hNk]
      exact le_csSup hbdd ⟨N ⊓ M, hinf, rfl⟩
    have h2 : (N ⊓ M).relIndex N * N.index = (N ⊓ M).index :=
      Subgroup.relIndex_mul_index inf_le_left
    have hipos : 0 < N.index := Nat.pos_of_ne_zero hN.index_ne_zero
    have h3 : (N ⊓ M).relIndex N = 1 := by
      rcases Nat.lt_or_ge ((N ⊓ M).relIndex N) 2 with h | h
      · interval_cases hr : (N ⊓ M).relIndex N
        · exact absurd (by rw [← h2, zero_mul]) hinf.index_ne_zero
        · rfl
      · exfalso
        have hlt : N.index < N.index :=
          calc N.index < 2 * N.index := by omega
            _ ≤ (N ⊓ M).relIndex N * N.index := Nat.mul_le_mul_right _ h
            _ = (N ⊓ M).index := h2
            _ ≤ N.index := h1
        exact lt_irrefl _ hlt
    exact le_trans (Subgroup.relIndex_eq_one.mp h3) inf_le_right
  · rintro ⟨N, hN, hmin⟩
    refine ⟨N.index, ?_⟩
    intro G _ _ hG
    obtain ⟨K, hK, hKcard⟩ := exists_kernel_of_isBurnsideQuotient G hG
    have hdvd : K.index ∣ N.index := Subgroup.index_dvd_of_le (hmin K hK)
    have hle := Nat.le_of_dvd (Nat.pos_of_ne_zero hN.index_ne_zero) hdvd
    omega

end Reduction

section BaseCases

/-- **Base case: abelian groups.** An `m`-generated abelian group of exponent dividing `n`
has order at most `n ^ m`. -/
theorem restrictedBurnsideComm (m n : ℕ) (hn : 0 < n) : RestrictedBurnsideComm m n := by
  intro G _ hG
  obtain ⟨hexp, f, hf⟩ := hG
  haveI : NeZero n := ⟨hn.ne'⟩
  haveI : Module (ZMod n) (Additive G) :=
    AddCommGroup.zmodModule (fun x => by
      simpa [← ofMul_pow] using congrArg Additive.ofMul (hexp (Additive.toMul x)))
  set v : Fin m → Additive G := fun i => Additive.ofMul (f i)
  have key : ∀ g : G, (Additive.ofMul g) ∈ Submodule.span (ZMod n) (Set.range v) := by
    intro g
    have hg : g ∈ Subgroup.closure (Set.range f) := by rw [hf]; trivial
    induction hg using Subgroup.closure_induction with
    | mem y hy =>
        obtain ⟨i, rfl⟩ := hy
        exact Submodule.subset_span (show Additive.ofMul (f i) ∈ Set.range v from ⟨i, rfl⟩)
    | one => exact Submodule.zero_mem _
    | mul y z _ _ ihy ihz => exact Submodule.add_mem _ ihy ihz
    | inv y _ ihy => exact Submodule.neg_mem _ ihy
  have hspan : Submodule.span (ZMod n) (Set.range v) = ⊤ := by
    rw [Submodule.eq_top_iff']
    exact fun x => key (Additive.toMul x)
  have hsurj : Function.Surjective ⇑(Fintype.linearCombination (ZMod n) v) := by
    rw [← LinearMap.range_eq_top, Fintype.range_linearCombination, hspan]
  calc Nat.card G = Nat.card (Additive G) := rfl
    _ ≤ Nat.card (Fin m → ZMod n) := Nat.card_le_card_of_surjective _ hsurj
    _ = n ^ m := by simp

/-- **Base case `n = 1`.** -/
theorem restrictedBurnside_one (m : ℕ) : RestrictedBurnside m 1 := by
  refine ⟨1, ?_⟩
  intro G _ _ hG
  have h : ∀ g : G, g = 1 := fun g => by simpa using hG.1 g
  haveI : Subsingleton G := ⟨fun a b => by rw [h a, h b]⟩
  simp

/-- **Base case `m = 0`.** -/
theorem restrictedBurnside_zero_gen (n : ℕ) : RestrictedBurnside 0 n := by
  refine ⟨1, ?_⟩
  intro G _ _ hG
  obtain ⟨-, f, hf⟩ := hG
  have hbot : (⊥ : Subgroup G) = ⊤ := by
    rw [← hf, Set.range_eq_empty f, Subgroup.closure_empty]
  have h : ∀ g : G, g = 1 := by
    intro g
    have : g ∈ (⊥ : Subgroup G) := by rw [hbot]; trivial
    simpa using this
  haveI : Subsingleton G := ⟨fun a b => by rw [h a, h b]⟩
  simp

/-- **Base case `m = 1`.** A cyclic group of exponent dividing `n` has order at most `n`. -/
theorem restrictedBurnside_one_gen (n : ℕ) (hn : 0 < n) : RestrictedBurnside 1 n := by
  refine ⟨n, ?_⟩
  intro G _ _ hG
  obtain ⟨hexp, f, hf⟩ := hG
  have hrange : Set.range f = {f 0} := by
    ext x
    constructor
    · rintro ⟨i, rfl⟩; simp [Subsingleton.elim i 0]
    · rintro rfl; exact ⟨0, rfl⟩
  have htop : Subgroup.zpowers (f 0) = ⊤ := by
    rw [Subgroup.zpowers_eq_closure, ← hrange, hf]
  have hcard : Nat.card G = orderOf (f 0) := by
    rw [← Nat.card_zpowers, htop, Subgroup.card_top]
  rw [hcard]
  exact orderOf_le_of_pow_eq_one hn (hexp (f 0))

/-- **Base case `n = 2`** (Burnside): a group of exponent `2` is abelian, so an
`m`-generated group of exponent dividing `2` has order at most `2 ^ m`. -/
theorem restrictedBurnside_two (m : ℕ) : RestrictedBurnside m 2 := by
  refine ⟨2 ^ m, ?_⟩
  intro G _ _ hG
  have hinv : ∀ g : G, g⁻¹ = g := by
    intro g
    have : g * g = 1 := by simpa [pow_two] using hG.1 g
    exact inv_eq_of_mul_eq_one_left this
  letI : CommGroup G :=
    { (inferInstance : Group G) with
      mul_comm := by
        intro a b
        calc a * b = (a * b)⁻¹ := (hinv _).symm
          _ = b⁻¹ * a⁻¹ := mul_inv_rev a b
          _ = b * a := by rw [hinv, hinv] }
  exact restrictedBurnsideComm m 2 (by norm_num) G hG

/-- **Sharpness of the hypothesis `0 < n`.** For exponent `n = 0` the condition `g ^ n = 1` is
vacuous, and the restricted Burnside property fails as soon as there is at least one
generator: the cyclic groups of all orders are generated by one element. -/
theorem not_restrictedBurnside_exponent_zero (m : ℕ) (hm : 0 < m) :
    ¬ RestrictedBurnside m 0 := by
  rintro ⟨B, hB⟩
  have hgen : Subgroup.closure
      (Set.range (fun _ : Fin m => Multiplicative.ofAdd (1 : ZMod (B + 1)))) = ⊤ := by
    rw [Subgroup.eq_top_iff']
    intro x
    have hx : x = (Multiplicative.ofAdd (1 : ZMod (B + 1))) ^ ((Multiplicative.toAdd x).val) := by
      rw [← ofAdd_nsmul]
      simp [nsmul_eq_mul, ZMod.natCast_val, ZMod.cast_id]
    rw [hx]
    refine Subgroup.pow_mem _ (Subgroup.subset_closure ?_) _
    exact Set.mem_range_self ⟨0, hm⟩
  have h := hB (Multiplicative (ZMod (B + 1))) ⟨fun g => pow_zero g, _, hgen⟩
  simp at h

end BaseCases

/-- **Zelmanov's restricted Burnside theorem** (formalized statement, together with the
Lean-checked reduction and the base cases proved here).

The full positive solution of the restricted Burnside problem — `RestrictedBurnside m n` for
all `m` and all `n ≥ 1` — is Zelmanov's theorem. What is proved here is:

* the standard reduction: `RestrictedBurnside m n` holds if and only if the free Burnside
  group `B(m, n)` admits a largest finite quotient;
* the base cases: exponent `1`, exponent `2` (Burnside), `0` or `1` generators, and the
  abelian case for every exponent `n ≥ 1`.
-/
theorem zelmanov_restricted_burnside :
    (∀ m n : ℕ, RestrictedBurnside m n ↔ HasUniversalFiniteQuotient m n) ∧
      (∀ m n : ℕ, 0 < n → RestrictedBurnsideComm m n) ∧
        (∀ m : ℕ, RestrictedBurnside m 1) ∧
          (∀ m : ℕ, RestrictedBurnside m 2) ∧
            (∀ n : ℕ, RestrictedBurnside 0 n) ∧ (∀ n : ℕ, 0 < n → RestrictedBurnside 1 n) :=
  ⟨restrictedBurnside_iff_hasUniversalFiniteQuotient, restrictedBurnsideComm,
    restrictedBurnside_one, restrictedBurnside_two, restrictedBurnside_zero_gen,
    restrictedBurnside_one_gen⟩

end Frontier

