import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

/-!
# Pólya / Burnside counting of substitution isomers

A *skeleton* is a finite set of substitution positions `P` carrying an action of the
symmetry group `G` of the molecule.  A *substitution pattern* (a labelling of every
position by one of the available substituents, drawn from a finite set `S`) is a function
`P → S`, and two patterns describe the *same isomer* exactly when they differ by a symmetry
of the skeleton, i.e. when they lie in the same orbit of the induced action
`(g • c) p = c (g⁻¹ • p)` of `G` on `P → S`.

The main result `Chem.polya_isomer_count` says that the number of isomers is the
Burnside/Pólya cycle-index average

`#isomers = (1 / |G|) * ∑_{g ∈ G} |S| ^ (number of cycles of g on P)`,

stated in the division-free form `#isomers * |G| = ∑_{g ∈ G} |S| ^ c(g)`; the version with
an honest average over `ℚ` is `Chem.polya_isomer_count_average`.

Here the number of cycles of `g` acting on the positions is, as usual, the number of orbits
of the cyclic group `⟨g⟩` generated by `g` (`Chem.cycleCount`).
-/

namespace Chem

-- The action of `G` on substitution patterns: `(g • c) p = c (g⁻¹ • p)`.
attribute [local instance] arrowAction

variable {G P S : Type*} [Group G] [MulAction G P]

/-- The number of cycles of the symmetry `g` acting on the set of positions `P`, i.e. the
number of orbits of the cyclic group generated by `g`.  This is the exponent occurring in
the Pólya cycle index. -/
noncomputable def cycleCount (g : G) (P : Type*) [MulAction G P] : ℕ :=
  Nat.card (MulAction.orbitRel.Quotient (Subgroup.zpowers g) P)

/-- A substitution pattern fixed by `g` is constant along the `⟨g⟩`-orbits of the positions. -/
lemma apply_smul_eq_of_mem_zpowers {g : G} {c : P → S} (hc : c ∈ MulAction.fixedBy (P → S) g)
    {h : G} (hh : h ∈ Subgroup.zpowers g) (a : P) : c (h • a) = c a := by
  have hg : g ∈ MulAction.stabilizer G c := hc
  have hmem : h ∈ MulAction.stabilizer G c :=
    (Subgroup.zpowers_le (H := MulAction.stabilizer G c)).2 hg hh
  have h2 : h • c = c := hmem
  have h3 := congrFun h2 (h • a)
  change c (h⁻¹ • h • a) = c (h • a) at h3
  rw [inv_smul_smul] at h3
  exact h3.symm

/-- The substitution patterns fixed by a symmetry `g` correspond exactly to the arbitrary
labellings of the cycles of `g`. -/
noncomputable def fixedByEquiv (g : G) :
    (MulAction.fixedBy (P → S) g) ≃ (MulAction.orbitRel.Quotient (Subgroup.zpowers g) P → S) where
  toFun c := Quotient.lift c.1 (by
    rintro a b hab
    obtain ⟨h, rfl⟩ := (hab : a ∈ MulAction.orbit (Subgroup.zpowers g) b)
    exact apply_smul_eq_of_mem_zpowers c.2 h.2 b)
  invFun F := ⟨fun a => F (Quotient.mk'' a), by
    funext a
    change F (Quotient.mk'' (g⁻¹ • a)) = F (Quotient.mk'' a)
    congr 1
    exact Quotient.sound ⟨⟨g⁻¹, Subgroup.inv_mem _ (Subgroup.mem_zpowers g)⟩, rfl⟩⟩
  left_inv _ := rfl
  right_inv F := by
    funext q
    induction q using Quotient.inductionOn' with
    | h a => rfl

/-- The number of substitution patterns fixed by a symmetry `g` is `|S| ^ (cycles of g)`. -/
lemma card_fixedBy (g : G) [Finite P] :
    Nat.card (MulAction.fixedBy (P → S) g) = Nat.card S ^ cycleCount g P := by
  rw [Nat.card_congr (fixedByEquiv (S := S) g), Nat.card_fun]
  rfl

/-- **Pólya's enumeration / Burnside's lemma for substitution isomers.**

Let a finite symmetry group `G` act on the finite set `P` of substitution positions of a
molecular skeleton, and let `S` be the finite set of available substituents.  Two labellings
`P → S` give the same isomer iff they lie in the same `G`-orbit (for the action
`(g • c) p = c (g⁻¹ • p)`).  Then the number of isomers, multiplied by the order of the
symmetry group, equals the Pólya cycle-index sum `∑_{g ∈ G} |S| ^ c(g)`, where `c(g)` is the
number of cycles of `g` on the positions. -/
theorem polya_isomer_count [Fintype G] [Finite P] [Finite S] :
    Nat.card (MulAction.orbitRel.Quotient G (P → S)) * Nat.card G
      = ∑ g : G, Nat.card S ^ cycleCount g P := by
  classical
  letI : Fintype (P → S) := Fintype.ofFinite _
  letI : ∀ a : G, Fintype (MulAction.fixedBy (P → S) a) := fun a => Fintype.ofFinite _
  letI : Fintype (MulAction.orbitRel.Quotient G (P → S)) := Fintype.ofFinite _
  have hb := MulAction.sum_card_fixedBy_eq_card_orbits_mul_card_group G (P → S)
  rw [← Nat.card_eq_fintype_card (α := MulAction.orbitRel.Quotient G (P → S)),
      ← Nat.card_eq_fintype_card (α := G)] at hb
  rw [← hb]
  exact Finset.sum_congr rfl fun g _ => by
    rw [← Nat.card_eq_fintype_card]; exact card_fixedBy (S := S) g

/-- The averaged form of `Chem.polya_isomer_count`: the number of substitution isomers is the
average, over the symmetry group, of `|S|` raised to the number of cycles of each symmetry. -/
theorem polya_isomer_count_average [Fintype G] [Finite P] [Finite S] :
    (Nat.card (MulAction.orbitRel.Quotient G (P → S)) : ℚ)
      = (1 / (Nat.card G : ℚ)) * ∑ g : G, (Nat.card S : ℚ) ^ cycleCount g P := by
  have hG : (Nat.card G : ℚ) ≠ 0 := by
    have : 0 < Nat.card G := Nat.card_pos
    positivity
  have h := polya_isomer_count (G := G) (P := P) (S := S)
  have h' : ((Nat.card (MulAction.orbitRel.Quotient G (P → S)) * Nat.card G : ℕ) : ℚ)
      = ((∑ g : G, Nat.card S ^ cycleCount g P : ℕ) : ℚ) := congrArg (fun n : ℕ => (n : ℚ)) h
  push_cast at h'
  field_simp
  linarith [h']

end Chem

