import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

/-
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

-- (Lean 4 rejects a `/-!` module docstring before `import`; the header is reproduced
-- verbatim as the module docstring immediately after the imports.)

import Mathlib

/-!
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace PCA.Cert

/-!
## The algebraic model of Ed25519

We model the Ed25519 signature scheme over its prime-order subgroup.  The subgroup is an
abelian group `G` on which the scalars `ZMod L` act (`L` is the prime group order, i.e. the
order `ℓ` of the base point in the real scheme); the base point is a point `B : G` whose
*annihilator is trivial*, i.e. `k • B = 0 → k = 0`, which is exactly the statement that `B`
generates a subgroup of order `L`.

The scheme itself is then:

* public key  `A = a • B`  for a secret scalar `a`;
* signature of `m` with nonce `r`:  `R = r • B`, `S = r + H R A m * a`;
* verification of `(R, S)` against `A`:  `S • B = R + (H R A m) • A`.

`ed25519_verify_sound` states the exact soundness (and completeness) characterisation of the
verification equation: an alleged signature `(R, S)` with `R = r • B` is accepted **iff** the
scalar `S` is precisely the honest response `r + H R A m * a`.  In contrapositive form: any
`S` that differs from the honest response is rejected — verification cannot be fooled.
-/

section Model

variable {L : ℕ} {G : Type*} {Msg : Type*} [AddCommGroup G] [Module (ZMod L) G]

/-- The Ed25519 verification predicate: the signature `(R, S)` on message `m` is accepted
under public key `A` (with base point `B` and hash function `H`) when `S • B = R + h • A`,
where `h = H R A m` is the challenge scalar. -/
def Verify (B : G) (H : G → G → Msg → ZMod L) (A : G) (m : Msg) (R : G) (S : ZMod L) : Prop :=
  S • B = R + (H R A m) • A

/-- The Ed25519 signing algorithm (in its algebraic, deterministic-nonce-free form):
with secret scalar `a` and nonce `r`, the signature of `m` is `(r • B, r + H R A m * a)`. -/
def Sign (B : G) (H : G → G → Msg → ZMod L) (a : ZMod L) (m : Msg) (r : ZMod L) : G × ZMod L :=
  (r • B, r + H (r • B) (a • B) m * a)

/-- `B` generates a subgroup of order exactly `L`: only the zero scalar annihilates `B`. -/
def IsBasePoint (B : G) : Prop := ∀ k : ZMod L, k • B = 0 → k = 0

/-- Scalar multiples of the base point are distinct for distinct scalars. -/
theorem smul_left_injective_of_isBasePoint {B : G} (hB : IsBasePoint (L := L) B)
    {k k' : ZMod L} (hk : k • B = k' • B) : k = k' := by
  have : (k - k') • B = 0 := by
    rw [sub_smul, hk, sub_self]
  have := hB _ this
  exact sub_eq_zero.mp this

end Model

/-- **Soundness (and completeness) of Ed25519 verification.**

Work in the prime-order subgroup generated by the base point `B` (`hB` says that `B` really
has order `L`, i.e. only the zero scalar kills it).  Let `A = a • B` be the public key of the
secret scalar `a`, and let `R = r • B` be the announced nonce point of an alleged signature
`(R, S)` on the message `m`.

Then the verification equation `S • B = R + (H R A m) • A` holds **iff** `S` is exactly the
honest response `r + H R A m * a`.

Equivalently (contrapositive): if `S ≠ r + H R A m * a`, verification rejects.  Thus the
verifier accepts no signature other than the one the legitimate signer would have produced
for that nonce, and it always accepts that one. -/
theorem ed25519_verify_sound {L : ℕ} {G : Type*} {Msg : Type*} [AddCommGroup G]
    [Module (ZMod L) G] {B : G} (hB : IsBasePoint (L := L) B)
    (H : G → G → Msg → ZMod L) (a r S : ZMod L) (m : Msg) :
    Verify B H (a • B) m (r • B) S ↔ S = r + H (r • B) (a • B) m * a := by
  unfold Verify
  constructor
  · intro hv
    refine smul_left_injective_of_isBasePoint hB ?_
    rw [hv, add_smul, mul_smul]
  · intro hS
    rw [hS, add_smul, mul_smul]

/-- **Completeness.** An honestly produced signature always verifies. -/
theorem ed25519_sign_verify {L : ℕ} {G : Type*} {Msg : Type*} [AddCommGroup G]
    [Module (ZMod L) G] (B : G) (H : G → G → Msg → ZMod L) (a r : ZMod L) (m : Msg) :
    Verify B H (a • B) m (Sign B H a m r).1 (Sign B H a m r).2 := by
  simp only [Sign, Verify, add_smul, mul_smul]

/-- **Key extraction / unforgeability core.** If a signature `(r • B, S)` with a nonzero
challenge is accepted under the public key `a • B`, then the secret scalar `a` is completely
determined by the signature: `a = (S - r) / h`.  Producing an accepting signature for a known
nonce therefore amounts to knowing the secret key. -/
theorem ed25519_verify_extracts_key {L : ℕ} [Fact (Nat.Prime L)] {G : Type*} {Msg : Type*}
    [AddCommGroup G] [Module (ZMod L) G] {B : G} (hB : IsBasePoint (L := L) B)
    (H : G → G → Msg → ZMod L) (a r S : ZMod L) (m : Msg)
    (hh : H (r • B) (a • B) m ≠ 0)
    (hv : Verify B H (a • B) m (r • B) S) :
    a = (S - r) / H (r • B) (a • B) m := by
  have hS := (ed25519_verify_sound hB H a r S m).mp hv
  rw [hS]
  field_simp
  ring

/-- **Rejection of forgeries (contrapositive form).** Any response scalar different from the
honest one is rejected by the verifier. -/
theorem ed25519_verify_reject {L : ℕ} {G : Type*} {Msg : Type*} [AddCommGroup G]
    [Module (ZMod L) G] {B : G} (hB : IsBasePoint (L := L) B)
    (H : G → G → Msg → ZMod L) (a r S : ZMod L) (m : Msg)
    (hS : S ≠ r + H (r • B) (a • B) m * a) :
    ¬ Verify B H (a • B) m (r • B) S :=
  fun hv => hS ((ed25519_verify_sound hB H a r S m).mp hv)

/-- The model is non-vacuous: for any prime `L` the group `ZMod L` with base point `1`
satisfies all the hypotheses. -/
theorem isBasePoint_one (L : ℕ) [NeZero L] : IsBasePoint (G := ZMod L) (L := L) 1 := by
  intro k hk
  simpa using hk

/-- The order `ℓ = 2^252 + 27742317777372353535851937790883648493` of the Ed25519 base
point, i.e. the size of the prime-order subgroup used by the scheme. -/
def ed25519GroupOrder : ℕ := 2 ^ 252 + 27742317777372353535851937790883648493

instance : NeZero ed25519GroupOrder := ⟨by unfold ed25519GroupOrder; positivity⟩

/-- The soundness theorem instantiated at a concrete, non-degenerate model with the genuine
Ed25519 group order: nothing above is vacuous. -/
theorem ed25519_verify_sound_concrete {Msg : Type*}
    (H : ZMod ed25519GroupOrder → ZMod ed25519GroupOrder → Msg → ZMod ed25519GroupOrder)
    (a r S : ZMod ed25519GroupOrder) (m : Msg) :
    Verify (1 : ZMod ed25519GroupOrder) H (a • (1 : ZMod ed25519GroupOrder)) m
        (r • (1 : ZMod ed25519GroupOrder)) S ↔
      S = r + H (r • (1 : ZMod ed25519GroupOrder)) (a • (1 : ZMod ed25519GroupOrder)) m * a :=
  ed25519_verify_sound (isBasePoint_one ed25519GroupOrder) H a r S m

end PCA.Cert

