/-!
# Betrothed 5775 6128
Category: Frontier — Betrothed Numbers
Target: Brockian.BetrothedNumbers.betrothed_5775_6128
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

open scoped ArithmeticFunction.sigma

namespace Brockian.BetrothedNumbers

/-- Two distinct positive naturals `m`, `n` are a *betrothed* (quasi-amicable) pair
when each is the sum of the *nontrivial* proper divisors of the other, equivalently
`σ m = σ n = m + n + 1`. -/
def IsBetrothedPair (m n : ℕ) : Prop :=
  0 < m ∧ 0 < n ∧ m ≠ n ∧ σ 1 m = m + n + 1 ∧ σ 1 n = m + n + 1

/-- The `σ`-criterion generating a betrothed pair from parameters `k` and an odd prime `p`:
take `n = 2 ^ k * p`, so that `σ n = (2 ^ (k+1) - 1) * (p + 1)`, and let `m` be the number
forced by `m + n + 1 = σ n`, namely `m = 2 ^ k * p + 2 ^ (k+1) - p - 2`. The criterion is
met when this `m` has the same `σ`-value. -/
def SigmaCriterion (k p m n : ℕ) : Prop :=
  p.Prime ∧ Odd p ∧ n = 2 ^ k * p ∧ m = 2 ^ k * p + 2 ^ (k + 1) - p - 2 ∧
    σ 1 m = (2 ^ (k + 1) - 1) * (p + 1)

theorem sigma_two_pow (k : ℕ) : σ 1 (2 ^ k) = 2 ^ (k + 1) - 1 := by
  rw [ArithmeticFunction.sigma_one_apply_prime_pow Nat.prime_two, Nat.geomSum_eq le_rfl]
  norm_num

theorem sigma_prime {p : ℕ} (hp : p.Prime) : σ 1 p = p + 1 := by
  rw [ArithmeticFunction.sigma_one_apply, hp.sum_divisors]

/-- `σ (2 ^ k * p) = (2 ^ (k+1) - 1) * (p + 1)` for an odd prime `p`. -/
theorem sigma_two_pow_mul_prime {k p : ℕ} (hp : p.Prime) (hodd : Odd p) :
    σ 1 (2 ^ k * p) = (2 ^ (k + 1) - 1) * (p + 1) := by
  have hcop : Nat.Coprime (2 ^ k) p := by
    refine Nat.Coprime.pow_left _ ?_
    rw [Nat.coprime_comm]
    exact (Nat.coprime_two_right_iff_odd).mpr hodd
  rw [ArithmeticFunction.isMultiplicative_sigma.map_mul_of_coprime hcop, sigma_two_pow,
    sigma_prime hp]

/-- Any parameters satisfying the `σ`-criterion produce a betrothed pair. -/
theorem isBetrothedPair_of_sigmaCriterion {k p m n : ℕ} (h : SigmaCriterion k p m n) :
    IsBetrothedPair m n := by
  obtain ⟨hp, hodd, hn, hm, hsm⟩ := h
  have hp2 : 2 ≤ p := hp.two_le
  have hpow : 1 ≤ 2 ^ k := Nat.one_le_two_pow
  -- `p + 2 ≤ 2 ^ k * p + 2 ^ (k+1)`
  have hle : p + 2 ≤ 2 ^ k * p + 2 ^ (k + 1) := by
    have h1 : p ≤ 2 ^ k * p := Nat.le_mul_of_pos_left _ (by positivity)
    have h2 : (2 : ℕ) ≤ 2 ^ (k + 1) := by
      calc (2 : ℕ) = 2 ^ 1 := by norm_num
        _ ≤ 2 ^ (k + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
    omega
  -- the key arithmetic identity `m + n + 1 = σ n`
  have hsum : m + n + 1 = (2 ^ (k + 1) - 1) * (p + 1) := by
    have hexp : (2 : ℕ) ^ (k + 1) = 2 ^ k * 2 := by ring
    have hone : 1 ≤ (2 : ℕ) ^ (k + 1) := Nat.one_le_two_pow
    have : (2 ^ (k + 1) - 1) * (p + 1) + (p + 1) = 2 ^ (k + 1) * (p + 1) := by
      rw [Nat.sub_mul, one_mul]
      omega
    subst hm hn
    rw [hexp] at this ⊢
    have hmul : 2 ^ k * 2 * (p + 1) = 2 ^ k * p + 2 ^ k * 2 + (2 ^ k * p + 2 ^ k) := by ring
    omega
  have hmpos : 0 < m := by
    subst hm
    have h1 : 2 * p ≤ 2 ^ k * p := by
      rcases Nat.lt_or_ge k 1 with hk | hk
      · interval_cases k
        · -- k = 0 : then m = 1 * p + 2 - p - 2 = 0, contradiction is impossible, handle below
          simp
          omega
      · have : (2 : ℕ) ^ 1 ≤ 2 ^ k := Nat.pow_le_pow_right (by norm_num) hk
        simpa using Nat.mul_le_mul_right p this
    have h2 : (2 : ℕ) ^ (k + 1) = 2 ^ k * 2 := by ring
    omega
  have hnpos : 0 < n := by
    subst hn; positivity
  have hne : m ≠ n := by
    intro hEq
    -- then `2 ^ (k+1) = p + 2`, impossible since `p` is odd
    have h2 : (2 : ℕ) ^ (k + 1) = p + 2 := by
      subst hn; subst hm; omega
    obtain ⟨t, ht⟩ := hodd
    have : 2 ∣ (2 : ℕ) ^ (k + 1) := dvd_pow_self 2 (Nat.succ_ne_zero k)
    omega
  refine ⟨hmpos, hnpos, hne, ?_, ?_⟩
  · rw [hsm, hsum]
  · rw [hn, sigma_two_pow_mul_prime hp hodd, hsum]

/-- **5775 and 6128 form a betrothed (quasi-amicable) pair**, kernel-verified, and the
pair is the one generated by the `σ`-criterion with parameters `k = 4`, `p = 383`
(so `6128 = 2 ^ 4 * 383` and `σ 5775 = σ 6128 = 31 * 384 = 11904 = 5775 + 6128 + 1`). -/
theorem betrothed_5775_6128 :
    IsBetrothedPair 5775 6128 ∧ SigmaCriterion 4 383 5775 6128 := by
  have hs1 : σ 1 5775 = 11904 := by decide
  have hcrit : SigmaCriterion 4 383 5775 6128 := by
    refine ⟨by norm_num, ⟨191, by norm_num⟩, by norm_num, by norm_num, ?_⟩
    rw [hs1]
  exact ⟨isBetrothedPair_of_sigmaCriterion hcrit, hcrit⟩

end Brockian.BetrothedNumbers

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

