import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Chem

attribute [local instance] arrowAction

variable {G P C : Type*} [Group G] [MulAction G P]

/-- A *substitution pattern* on a molecular skeleton with positions `P` and possible
substituents `C` is a labelling of every position by a substituent.  The symmetry group of
the skeleton acts on such labellings by `(g • c) p = c (g⁻¹ • p)`. -/
abbrev Coloring (P C : Type*) : Type _ := P → C

/-- Two substitution patterns describe the same *isomer* when they differ by a symmetry of the
skeleton; the isomers are therefore the orbits of the symmetry group `G` acting on colorings. -/
abbrev Isomer (G P C : Type*) [Group G] [MulAction G P] : Type _ :=
  MulAction.orbitRel.Quotient G (Coloring P C)

/-- The number of cycles of the symmetry `g` acting on the positions of the skeleton, i.e. the
number of orbits of the cyclic group generated by `g`.  This is the exponent appearing in the
Pólya cycle index. -/
noncomputable def numCycles (g : G) : ℕ :=
  Nat.card (MulAction.orbitRel.Quotient (Subgroup.zpowers g) P)

/-- The identity symmetry has one cycle per position. -/
lemma numCycles_one : numCycles (G := G) (P := P) (1 : G) = Nat.card P := by
  refine Nat.card_congr ?_
  refine ⟨Quotient.lift id ?_, fun p => Quotient.mk _ p, ?_, ?_⟩
  · rintro a b ⟨x, hx⟩
    obtain ⟨x, hxmem⟩ := x
    rw [Subgroup.zpowers_one_eq_bot, Subgroup.mem_bot] at hxmem
    subst hxmem
    simpa using hx.symm
  · intro q
    induction q using Quotient.inductionOn with
    | _ p => rfl
  · intro p; rfl

lemma smul_coloring_apply (g : G) (c : Coloring P C) (p : P) :
    (g • c) p = c (g⁻¹ • p) := rfl

/-- A coloring is fixed by `g` precisely when it is invariant under `g` on positions. -/
lemma smul_eq_self_iff (g : G) (c : Coloring P C) :
    g • c = c ↔ ∀ p : P, c (g • p) = c p := by
  constructor
  · intro h p
    have h' : (g • c) (g • p) = c (g • p) := by rw [h]
    rw [smul_coloring_apply, inv_smul_smul] at h'
    exact h'.symm
  · intro h
    funext p
    have h' := h (g⁻¹ • p)
    rw [smul_inv_smul] at h'
    rw [smul_coloring_apply]
    exact h'.symm

lemma coloring_zpow_smul {g : G} {c : Coloring P C}
    (hc : ∀ p : P, c (g • p) = c p) (n : ℤ) : ∀ p : P, c (g ^ n • p) = c p := by
  induction n using Int.induction_on with
  | zero => intro p; simp
  | succ k ih =>
      intro p
      have hstep : g ^ ((k : ℤ) + 1) • p = g ^ (k : ℤ) • (g • p) := by
        rw [smul_smul, zpow_add_one]
      rw [hstep, ih (g • p), hc]
  | pred k ih =>
      intro p
      have hstep : g ^ (-(k : ℤ) - 1) • p = g ^ (-(k : ℤ)) • (g⁻¹ • p) := by
        rw [smul_smul, zpow_sub_one]
      have h' := hc (g⁻¹ • p)
      rw [smul_inv_smul] at h'
      rw [hstep, ih (g⁻¹ • p), ← h']

lemma coloring_const_on_zpowers_orbit {g : G} {c : Coloring P C}
    (hc : ∀ p : P, c (g • p) = c p) (x : Subgroup.zpowers g) (p : P) :
    c ((x : G) • p) = c p := by
  obtain ⟨x, hx⟩ := x
  obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
  exact coloring_zpow_smul hc n p

/-- The colorings fixed by a symmetry `g` are exactly the functions on the set of `⟨g⟩`-orbits
of positions; hence there are `|C| ^ (number of cycles of g)` of them. -/
noncomputable def fixedByEquiv (g : G) :
    MulAction.fixedBy (Coloring P C) g ≃
      (MulAction.orbitRel.Quotient (Subgroup.zpowers g) P → C) where
  toFun := fun c =>
    Quotient.lift (fun p => (c : Coloring P C) p) (by
      rintro a b ⟨x, hx⟩
      have hc : ∀ p : P, (c : Coloring P C) (g • p) = (c : Coloring P C) p :=
        (smul_eq_self_iff g (c : Coloring P C)).mp c.2
      have h := coloring_const_on_zpowers_orbit hc x b
      rw [show (x : G) • b = a from hx] at h
      exact h)
  invFun := fun f => ⟨fun p => f (Quotient.mk _ p), by
    show g • (fun p : P => f (Quotient.mk _ p)) = _
    refine (smul_eq_self_iff g _).mpr ?_
    intro p
    exact congrArg f (Quotient.sound ⟨⟨g, Subgroup.mem_zpowers g⟩, rfl⟩)⟩
  left_inv := by intro c; ext p; rfl
  right_inv := by
    intro f
    funext q
    induction q using Quotient.inductionOn with
    | _ p => rfl

/-- **Pólya / Burnside enumeration of substitution isomers.**
For a finite symmetry group `G` acting on the finitely many positions `P` of a molecular
skeleton, with finitely many possible substituents `C`, the number of substitution isomers
(orbits of colorings) times the order of the symmetry group equals the sum over the group of
`|C|` raised to the number of cycles of each symmetry — that is, the number of isomers is the
average of the cycle-index terms, `(1/|G|) ∑_{g ∈ G} |C| ^ c(g)`. -/
theorem polya_isomer_count [Fintype G] [Fintype P] [Fintype C] :
    Nat.card (Isomer G P C) * Nat.card G
      = ∑ g : G, Nat.card C ^ numCycles (P := P) g := by
  classical
  have hburn :
      (∑ g : G, Nat.card (MulAction.fixedBy (Coloring P C) g))
        = Nat.card (Isomer G P C) * Nat.card G := by
    have h := MulAction.sum_card_fixedBy_eq_card_orbits_mul_card_group
      (α := G) (β := Coloring P C)
    simpa [Nat.card_eq_fintype_card] using h
  rw [← hburn]
  refine Finset.sum_congr rfl fun g _ => ?_
  rw [Nat.card_congr (fixedByEquiv (C := C) g), Nat.card_fun, numCycles]

/-- The averaged form of the Pólya enumeration theorem: the number of substitution isomers is
the cycle-index average `(1/|G|) ∑_{g ∈ G} |C| ^ c(g)`. -/
theorem polya_isomer_count_average [Fintype G] [Fintype P] [Fintype C] :
    (Nat.card (Isomer G P C) : ℚ)
      = (∑ g : G, (Nat.card C : ℚ) ^ numCycles (P := P) g) / (Nat.card G : ℚ) := by
  have hG : (Nat.card G : ℚ) ≠ 0 := by
    have : 0 < Nat.card G := Nat.card_pos
    positivity
  rw [eq_div_iff hG]
  have h := polya_isomer_count (G := G) (P := P) (C := C)
  calc (Nat.card (Isomer G P C) : ℚ) * (Nat.card G : ℚ)
      = ((Nat.card (Isomer G P C) * Nat.card G : ℕ) : ℚ) := by push_cast; ring
    _ = ((∑ g : G, Nat.card C ^ numCycles (P := P) g : ℕ) : ℚ) := by rw [h]
    _ = ((∑ g : G, (Nat.card C : ℚ) ^ numCycles (P := P) g)) := by push_cast; ring

/-! ### A concrete skeleton: the benzene ring -/

/-- For the regular action of a group on itself (e.g. the rotation group of a ring skeleton
acting on its positions), the number of cycles of `g` is `|G| / orderOf g`. -/
lemma numCycles_regular {H : Type*} [Group H] [Fintype H] (g : H) :
    numCycles (G := H) (P := H) g = Nat.card H / orderOf g := by
  rw [numCycles, Nat.card_congr
    (MulAction.equivSubgroupOrbitsQuotientGroup (α := H) (β := H) (1 : H) (Subgroup.zpowers g)),
    ← Subgroup.index]
  have h := Subgroup.card_mul_index (Subgroup.zpowers g)
  rw [Nat.card_zpowers] at h
  rw [← h, Nat.mul_div_cancel_left _ (orderOf_pos g)]

/-- The additive order of an element of `ZMod 6`, computed from its representative. -/
lemma addOrderOf_zmod_six (a : ZMod 6) : addOrderOf a = 6 / Nat.gcd 6 a.val := by
  conv_lhs => rw [show a = ((a.val : ℕ) : ZMod 6) by simp]
  exact ZMod.addOrderOf_coe a.val (by norm_num)

/-- **Benzene.** The six positions of the benzene ring, acted on by the cyclic rotation group
`C₆` (acting regularly on the positions), with two possible substituents at each position
(say H or Cl): there are exactly `14` substitution patterns up to rotation, in agreement with
the Pólya cycle-index average `(2⁶ + 2 + 2² + 2³ + 2² + 2)/6 = 84/6 = 14`. -/
theorem benzene_rotation_isomer_count :
    Nat.card (Isomer (Multiplicative (ZMod 6)) (Multiplicative (ZMod 6)) (Fin 2)) = 14 := by
  have hcard : Nat.card (Multiplicative (ZMod 6)) = 6 := by
    simp [Nat.card_eq_fintype_card]
  have hC : Nat.card (Fin 2) = 2 := by simp
  have key := polya_isomer_count (G := Multiplicative (ZMod 6))
    (P := Multiplicative (ZMod 6)) (C := Fin 2)
  have hsum : (∑ g : Multiplicative (ZMod 6),
      Nat.card (Fin 2) ^ numCycles (P := Multiplicative (ZMod 6)) g) = 84 := by
    have hterm : ∀ g : Multiplicative (ZMod 6),
        Nat.card (Fin 2) ^ numCycles (P := Multiplicative (ZMod 6)) g
          = 2 ^ (6 / (6 / Nat.gcd 6 (Multiplicative.toAdd g).val)) := by
      intro g
      have hord : orderOf g = addOrderOf (Multiplicative.toAdd g) := rfl
      rw [hC, numCycles_regular g, hcard, hord, addOrderOf_zmod_six]
    rw [Finset.sum_congr rfl fun g _ => hterm g]
    show (∑ a : ZMod 6, 2 ^ (6 / (6 / Nat.gcd 6 a.val))) = 84
    decide
  rw [hsum, hcard] at key
  omega

end Chem

