import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 40000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

/-!
## The point group of benzene

Benzene has molecular point group `D₆ₕ`, which is the direct product of the dihedral
group `D₆` (of order `12`, the symmetries of the hexagonal carbon skeleton in its own
plane) with the two element group `{E, i}` generated by the inversion centre.  Thus
`D₆ₕ ≅ D₆ × C₂` has order `24`.
-/

/-- The point group `D₆ₕ` of benzene, realised as `D₆ × C₂`. -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- The nontrivial element of the `C₂` factor, i.e. the inversion `i`. -/
def inv2 : Multiplicative (ZMod 2) := Multiplicative.ofAdd (1 : ZMod 2)

/-!
## The twelve conjugacy classes

Representatives of the twelve conjugacy classes of `D₆ₕ`, in the standard
chemists' ordering

`E, C₂, 2C₆, 2C₃, 3C₂', 3C₂''` (gerade part) and
`i, σ_h, 2S₃, 2S₆, 3σ_d, 3σ_v` (ungerade part),

each of the second six being the product of the corresponding element of the first
six with the inversion `i`.
-/
def classRep : Fin 12 → D6h :=
  ![(DihedralGroup.r 0, 1), (DihedralGroup.r 3, 1), (DihedralGroup.r 1, 1),
    (DihedralGroup.r 2, 1), (DihedralGroup.sr 0, 1), (DihedralGroup.sr 1, 1),
    (DihedralGroup.r 0, inv2), (DihedralGroup.r 3, inv2), (DihedralGroup.r 1, inv2),
    (DihedralGroup.r 2, inv2), (DihedralGroup.sr 0, inv2), (DihedralGroup.sr 1, inv2)]

/-- The sizes of the twelve conjugacy classes, in the same ordering. -/
def classSize : Fin 12 → ℕ := ![1, 1, 2, 2, 3, 3, 1, 1, 2, 2, 3, 3]

/-!
## The character table

The rows are the twelve irreducible characters
`A₁g, A₂g, B₁g, B₂g, E₁g, E₂g, A₁u, A₂u, B₁u, B₂u, E₁u, E₂u`
and the columns are the twelve conjugacy classes listed above.  All entries are
integers.  The table is the tensor product of the character table of `D₆` with that
of `C₂`.
-/
def charTable : Fin 12 → Fin 12 → ℤ :=
  ![-- A₁g
    ![1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    -- A₂g
    ![1, 1, 1, 1, -1, -1, 1, 1, 1, 1, -1, -1],
    -- B₁g
    ![1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, -1],
    -- B₂g
    ![1, -1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1],
    -- E₁g
    ![2, -2, 1, -1, 0, 0, 2, -2, 1, -1, 0, 0],
    -- E₂g
    ![2, 2, -1, -1, 0, 0, 2, 2, -1, -1, 0, 0],
    -- A₁u
    ![1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1],
    -- A₂u
    ![1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1],
    -- B₁u
    ![1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1],
    -- B₂u
    ![1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1],
    -- E₁u
    ![2, -2, 1, -1, 0, 0, -2, 2, -1, 1, 0, 0],
    -- E₂u
    ![2, 2, -1, -1, 0, 0, -2, -2, 1, 1, 0, 0]]

/-!
## Basic facts about the group and its classes
-/

/-- `D₆ₕ` has order `24`. -/
theorem card_D6h : Nat.card D6h = 24 := by
  rw [Nat.card_eq_fintype_card]; decide

/-- `D₆ₕ` has exactly `12` conjugacy classes. -/
theorem card_conjClasses_D6h : Nat.card (ConjClasses D6h) = 12 := by
  rw [Nat.card_eq_fintype_card]; decide

/-- The chosen class representatives are pairwise non-conjugate. -/
theorem classRep_not_conj {i j : Fin 12} (h : IsConj (classRep i) (classRep j)) : i = j := by
  revert h; revert i j; decide

/-- Every element of `D₆ₕ` is conjugate to one of the chosen representatives. -/
theorem exists_classRep_conj (x : D6h) : ∃ i : Fin 12, IsConj (classRep i) x := by
  revert x; decide

/-- The conjugacy class of the `i`-th representative has size `classSize i`. -/
theorem card_conjClass (i : Fin 12) :
    ({x : D6h | IsConj (classRep i) x} : Finset D6h).card = classSize i := by
  revert i; decide

/-!
## Orthogonality of the rows of the character table
-/

/-- The rows of the character table are orthogonal, with squared norm `|G| = 24`,
with respect to the class-size weighted inner product. -/
theorem charTable_orthogonal (i j : Fin 12) :
    ∑ k : Fin 12, (classSize k : ℤ) * charTable i k * charTable j k
      = if i = j then 24 else 0 := by
  revert i j; decide

/-- The sum of the squares of the degrees (the entries in the column of the identity)
of the twelve characters is the order of the group. -/
theorem sum_sq_degrees : ∑ i : Fin 12, (charTable i 0) ^ 2 = 24 := by decide

/-!
## The main statement

The character table of `D₆ₕ` has the correct number of irreducible representations:
its twelve rows are orthonormal class functions (with respect to the genuine conjugacy
class data of the group) whose degrees satisfy `∑ dᵢ² = |G|`, hence they are exactly the
irreducible characters, and their number `12` equals the number of conjugacy classes of
`D₆ₕ`.
-/
theorem benzene_D6h_irreps :
    -- the group has order 24
    Nat.card D6h = 24 ∧
    -- the twelve chosen representatives really are a complete, irredundant list of
    -- conjugacy class representatives, with the stated class sizes
    (∀ i j : Fin 12, IsConj (classRep i) (classRep j) → i = j) ∧
    (∀ x : D6h, ∃ i : Fin 12, IsConj (classRep i) x) ∧
    (∀ i : Fin 12, ({x : D6h | IsConj (classRep i) x} : Finset D6h).card = classSize i) ∧
    -- so the number of conjugacy classes, i.e. of columns of the table, is 12
    Nat.card (ConjClasses D6h) = 12 ∧
    -- the twelve rows of the table are orthonormal class functions ...
    (∀ i j : Fin 12, ∑ k : Fin 12, (classSize k : ℤ) * charTable i k * charTable j k
        = if i = j then 24 else 0) ∧
    -- ... whose degrees satisfy the Burnside relation `∑ dᵢ² = |G|`,
    -- so they are precisely all the irreducible characters
    (∑ i : Fin 12, (charTable i 0) ^ 2 = 24) ∧
    -- number of irreducible representations = number of conjugacy classes
    (12 : ℕ) = Nat.card (ConjClasses D6h) := by
  refine ⟨card_D6h, ?_, exists_classRep_conj, card_conjClass, card_conjClasses_D6h,
    charTable_orthogonal, sum_sq_degrees, card_conjClasses_D6h.symm⟩
  intro i j h
  exact classRep_not_conj h

end Chem

