import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Pointwise

set_option maxHeartbeats 1000000

namespace Frontier

/-- `IsGeneratedBy G n` says that the group `G` can be generated by at most `n` elements. -/
def IsGeneratedBy (G : Type) [Group G] (n : ℕ) : Prop :=
  ∃ S : Finset G, S.card ≤ n ∧ Subgroup.closure (S : Set G) = ⊤

/-- `RestrictedBurnside n e` is the statement of the restricted Burnside problem for rank `n`
and exponent `e`: there is a uniform bound `N` on the order of every finite group with at most
`n` generators all of whose elements satisfy `g ^ e = 1`. -/
def RestrictedBurnside (n e : ℕ) : Prop :=
  ∃ N : ℕ, ∀ (G : Type) [Group G] [Fintype G],
    (∀ g : G, g ^ e = 1) → IsGeneratedBy G n → Fintype.card G ≤ N

/-- The full restricted Burnside problem, solved positively by Zelmanov. -/
def RestrictedBurnsideProblem : Prop := ∀ n e : ℕ, 0 < e → RestrictedBurnside n e

/-! ## Elementary reductions -/

/-- Monotonicity in the rank: a bound for rank `n` gives a bound for any smaller rank. -/
theorem RestrictedBurnside.mono_rank {n m e : ℕ} (hmn : m ≤ n) (h : RestrictedBurnside n e) :
    RestrictedBurnside m e := by
  obtain ⟨N, hN⟩ := h
  refine ⟨N, fun G _ _ hexp hgen => hN G hexp ?_⟩
  obtain ⟨S, hS, hSgen⟩ := hgen
  exact ⟨S, hS.trans hmn, hSgen⟩

/-- Divisibility reduction in the exponent: a bound for exponent `e` gives a bound for every
divisor `d` of `e`. -/
theorem RestrictedBurnside.of_dvd {n d e : ℕ} (hde : d ∣ e) (h : RestrictedBurnside n e) :
    RestrictedBurnside n d := by
  obtain ⟨N, hN⟩ := h
  obtain ⟨k, rfl⟩ := hde
  refine ⟨N, fun G _ _ hexp hgen => hN G (fun g => ?_) hgen⟩
  rw [pow_mul, hexp g, one_pow]

/-! ## The base cases -/

/-- A group of exponent dividing `2` is commutative. -/
theorem mul_comm_of_exponent_two {G : Type} [Group G] (h2 : ∀ g : G, g ^ 2 = 1) (a b : G) :
    a * b = b * a := by
  have hinv : ∀ g : G, g⁻¹ = g := by
    intro g
    have : g * g = 1 := by rw [← pow_two]; exact h2 g
    exact inv_eq_of_mul_eq_one_right this
  calc a * b = (a * b)⁻¹ := (hinv _).symm
    _ = b⁻¹ * a⁻¹ := mul_inv_rev a b
    _ = b * a := by rw [hinv, hinv]

/-- In a finite group of exponent dividing `2` generated by a finite set `S`, every element is
the product of a subset of `S`; hence the order of the group is at most `2 ^ S.card`. -/
theorem card_le_two_pow_of_exponent_two {G : Type} [Group G] [Fintype G]
    (h2 : ∀ g : G, g ^ 2 = 1) (S : Finset G) (hS : Subgroup.closure (S : Set G) = ⊤) :
    Fintype.card G ≤ 2 ^ S.card := by
  classical
  letI : CommGroup G := { (inferInstance : Group G) with
    mul_comm := mul_comm_of_exponent_two h2 }
  have hinv : ∀ g : G, g⁻¹ = g := by
    intro g
    have : g * g = 1 := by rw [← pow_two]; exact h2 g
    exact inv_eq_of_mul_eq_one_right this
  -- the set of subset-products of `S`
  set H : Subgroup G :=
    { carrier := {g : G | ∃ T ⊆ S, ∏ t ∈ T, t = g}
      one_mem' := ⟨∅, Finset.empty_subset _, Finset.prod_empty⟩
      mul_mem' := by
        rintro a b ⟨T₁, hT₁, rfl⟩ ⟨T₂, hT₂, rfl⟩
        refine ⟨symmDiff T₁ T₂, ?_, ?_⟩
        · intro x hx
          rcases Finset.mem_symmDiff.1 hx with ⟨hx, -⟩ | ⟨hx, -⟩
          · exact hT₁ hx
          · exact hT₂ hx
        · have hsub : T₁ ∩ T₂ ⊆ T₁ ∪ T₂ := Finset.inter_subset_union
          have hsd : symmDiff T₁ T₂ = (T₁ ∪ T₂) \ (T₁ ∩ T₂) := by
            ext x
            simp only [Finset.mem_symmDiff, Finset.mem_sdiff, Finset.mem_union, Finset.mem_inter]
            tauto
          have h1 : (∏ t ∈ (T₁ ∪ T₂) \ (T₁ ∩ T₂), t) * (∏ t ∈ T₁ ∩ T₂, t)
              = ∏ t ∈ T₁ ∪ T₂, t := Finset.prod_sdiff hsub
          have h2' : (∏ t ∈ T₁ ∪ T₂, t) * (∏ t ∈ T₁ ∩ T₂, t) = (∏ t ∈ T₁, t) * ∏ t ∈ T₂, t :=
            Finset.prod_union_inter
          have hsq : ((∏ t ∈ T₁ ∩ T₂, t) : G) ^ 2 = 1 := h2 _
          calc (∏ t ∈ symmDiff T₁ T₂, t)
              = (∏ t ∈ (T₁ ∪ T₂) \ (T₁ ∩ T₂), t) * ((∏ t ∈ T₁ ∩ T₂, t) ^ 2) := by
                rw [hsq, mul_one, hsd]
            _ = ((∏ t ∈ (T₁ ∪ T₂) \ (T₁ ∩ T₂), t) * ∏ t ∈ T₁ ∩ T₂, t) * ∏ t ∈ T₁ ∩ T₂, t := by
                rw [sq, mul_assoc]
            _ = (∏ t ∈ T₁ ∪ T₂, t) * (∏ t ∈ T₁ ∩ T₂, t) := by rw [h1]
            _ = (∏ t ∈ T₁, t) * ∏ t ∈ T₂, t := h2'
      inv_mem' := by
        rintro a ⟨T, hT, rfl⟩
        exact ⟨T, hT, by rw [hinv]⟩ } with hHdef
  have hSH : (S : Set G) ⊆ (H : Set G) := by
    intro s hs
    exact ⟨{s}, by simpa using hs, by simp⟩
  have htop : H = ⊤ := by
    rw [eq_top_iff, ← hS]
    exact Subgroup.closure_le H |>.2 hSH
  have hmem : ∀ g : G, ∃ T ⊆ S, ∏ t ∈ T, t = g := by
    intro g
    have : g ∈ H := by rw [htop]; trivial
    exact this
  have hcard : (Finset.univ : Finset G) ⊆ S.powerset.image (fun T => ∏ t ∈ T, t) := by
    intro g _
    obtain ⟨T, hT, hTg⟩ := hmem g
    exact Finset.mem_image.2 ⟨T, Finset.mem_powerset.2 hT, hTg⟩
  calc Fintype.card G = (Finset.univ : Finset G).card := rfl
    _ ≤ (S.powerset.image (fun T => ∏ t ∈ T, t)).card := Finset.card_le_card hcard
    _ ≤ S.powerset.card := Finset.card_image_le
    _ = 2 ^ S.card := Finset.card_powerset S

/-- **Base case, exponent 1**: the only group of exponent `1` is trivial. -/
theorem restrictedBurnside_one (n : ℕ) : RestrictedBurnside n 1 := by
  refine ⟨1, fun G _ _ hexp _ => ?_⟩
  have : ∀ g : G, g = 1 := by simpa using hexp
  have : Subsingleton G := ⟨fun a b => by rw [this a, this b]⟩
  simpa using Fintype.card_le_one_iff_subsingleton.2 this

/-- **Base case, exponent 2** (Burnside): a group of exponent `2` with `n` generators is an
elementary abelian `2`-group of order at most `2 ^ n`. -/
theorem restrictedBurnside_two (n : ℕ) : RestrictedBurnside n 2 := by
  refine ⟨2 ^ n, fun G _ _ hexp hgen => ?_⟩
  obtain ⟨S, hS, hSgen⟩ := hgen
  exact (card_le_two_pow_of_exponent_two hexp S hSgen).trans (Nat.pow_le_pow_right (by norm_num) hS)

/-- **Base case, rank 1**: a cyclic group of exponent `e ≥ 1` has order at most `e`. -/
theorem restrictedBurnside_rank_one {e : ℕ} (he : 0 < e) : RestrictedBurnside 1 e := by
  refine ⟨e, fun G _ _ hexp hgen => ?_⟩
  classical
  obtain ⟨S, hS, hSgen⟩ := hgen
  -- `S` has at most one element; the group is generated by a single element `g`
  obtain ⟨g, hg⟩ : ∃ g : G, Subgroup.closure ({g} : Set G) = ⊤ := by
    rcases Finset.card_le_one.1 hS with h
    rcases S.eq_empty_or_nonempty with rfl | ⟨s, hs⟩
    · refine ⟨1, ?_⟩
      rw [← hSgen]
      simp
    · refine ⟨s, ?_⟩
      rw [← hSgen]
      congr 1
      ext x
      constructor
      · intro hx
        simp only [Set.mem_singleton_iff] at hx
        subst hx
        exact hs
      · intro hx
        simp only [Finset.mem_coe] at hx
        simp [h x hx s hs]
  -- every element is a power of `g`
  have hmem : ∀ x : G, ∃ k : ℕ, k < e ∧ g ^ k = x := by
    intro x
    have hx : x ∈ Subgroup.closure ({g} : Set G) := by rw [hg]; trivial
    rw [Subgroup.mem_closure_singleton] at hx
    obtain ⟨k, hk⟩ := hx
    refine ⟨(k % e).toNat, ?_, ?_⟩
    · have : k % (e : ℤ) < e := Int.emod_lt_of_pos k (by exact_mod_cast he)
      omega
    · have hz : g ^ (k % (e : ℤ)) = g ^ k := by
        conv_rhs => rw [← Int.ediv_add_emod k e]
        rw [zpow_add, zpow_mul]
        have : g ^ (e : ℤ) = 1 := by
          rw [zpow_natCast]
          exact hexp g
        rw [this, one_zpow, one_mul]
      have hnn : (0 : ℤ) ≤ k % e := Int.emod_nonneg k (by exact_mod_cast he.ne')
      have hcast : g ^ ((k % (e : ℤ)).toNat) = g ^ (k % (e : ℤ)) := by
        rw [← zpow_natCast, Int.toNat_of_nonneg hnn]
      rw [hcast, hz, hk]
  have hsurj : (Finset.univ : Finset G) ⊆ (Finset.range e).image (fun k => g ^ k) := by
    intro x _
    obtain ⟨k, hk, hkx⟩ := hmem x
    exact Finset.mem_image.2 ⟨k, Finset.mem_range.2 hk, hkx⟩
  calc Fintype.card G = (Finset.univ : Finset G).card := rfl
    _ ≤ ((Finset.range e).image (fun k => g ^ k)).card := Finset.card_le_card hsurj
    _ ≤ (Finset.range e).card := Finset.card_image_le
    _ = e := Finset.card_range e

/-- The exponent `0` case is genuinely false: cyclic groups of arbitrarily large order are
generated by one element and satisfy `g ^ 0 = 1` vacuously. -/
theorem not_restrictedBurnside_zero : ¬ RestrictedBurnside 1 0 := by
  rintro ⟨N, hN⟩
  have key := hN (Multiplicative (ZMod (N + 1))) (fun g => pow_zero g) ?_
  · have hc : Fintype.card (Multiplicative (ZMod (N + 1))) = N + 1 := by simp
    omega
  · refine ⟨{Multiplicative.ofAdd 1}, by simp, ?_⟩
    rw [eq_top_iff]
    rintro x -
    have : x ∈ Subgroup.closure ({Multiplicative.ofAdd (1 : ZMod (N + 1))} : Set _) := by
      rw [Subgroup.mem_closure_singleton]
      refine ⟨((Multiplicative.toAdd x).val : ℤ), ?_⟩
      rw [zpow_natCast, ← ofAdd_nsmul]
      simp [nsmul_eq_mul, ZMod.natCast_val, ZMod.cast_id]
    simpa using this

/-- **Zelmanov's restricted Burnside theorem** (formalized statement, with the base cases and
elementary reductions proved).

`RestrictedBurnsideProblem` is the full statement: for every rank `n` and every exponent `e ≥ 1`
there is a uniform bound on the order of the finite `n`-generated groups of exponent dividing `e`.
The theorem below records the Lean-checked content: the statement of the problem, the base cases
`e = 1` (trivial), `e = 2` (Burnside's elementary abelian bound `2 ^ n`) and `n = 1` (cyclic
groups, bound `e`), the reductions in the rank and along divisors of the exponent, and the
necessity of the hypothesis `0 < e`. -/
theorem zelmanov_restricted_burnside :
    (∀ n : ℕ, RestrictedBurnside n 1) ∧
    (∀ n : ℕ, RestrictedBurnside n 2) ∧
    (∀ e : ℕ, 0 < e → RestrictedBurnside 1 e) ∧
    (∀ n m e : ℕ, m ≤ n → RestrictedBurnside n e → RestrictedBurnside m e) ∧
    (∀ n d e : ℕ, d ∣ e → RestrictedBurnside n e → RestrictedBurnside n d) ∧
    ¬ RestrictedBurnside 1 0 :=
  ⟨restrictedBurnside_one, restrictedBurnside_two, fun _ he => restrictedBurnside_rank_one he,
    fun _ _ _ hmn h => h.mono_rank hmn, fun _ _ _ hde h => h.of_dvd hde,
    not_restrictedBurnside_zero⟩

end Frontier

