/-
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace PCA.Cert

/-- The order `ℓ = 2^252 + 27742317777372353535851937790883648493` of the prime-order
subgroup of the Ed25519 curve group generated by the standard base point. -/
def ed25519Order : ℕ := 2 ^ 252 + 27742317777372353535851937790883648493

/-- Scalars of the Ed25519 signature scheme: residues modulo the group order `ℓ`. -/
abbrev Scalar : Type := ZMod ed25519Order

/-- Parameters of the Ed25519 verification engine: a carrier group `G` of exponent `ℓ`
(so that it is a `ZMod ed25519Order`-module) together with a base point that
generates it faithfully, i.e. `c ↦ c • base` is a bijection from `Scalar` onto `G`.
This is exactly the abstract model of the prime-order subgroup that the isolation
engine's certificate checker reasons about. -/
structure Params (G : Type*) [AddCommGroup G] [Module Scalar G] where
  /-- The standard base point `B`. -/
  base : G
  /-- The base point has exact order `ℓ`: no nonzero scalar annihilates it. -/
  base_faithful : ∀ c : Scalar, c • base = 0 → c = 0
  /-- The base point generates the whole carrier group. -/
  base_generates : ∀ Q : G, ∃ c : Scalar, Q = c • base

variable {G : Type*} [AddCommGroup G] [Module Scalar G]

/-- A signature is a group element `R` together with a scalar `S`. -/
structure Sig (G : Type*) where
  /-- The commitment point `R`. -/
  R : G
  /-- The response scalar `S`. -/
  S : Scalar

/-- The public key associated with a secret scalar `a` is `A = a • B`. -/
def publicKey (P : Params G) (a : Scalar) : G := a • P.base

/-- Ed25519 signing (with hash oracle `H`, nonce `r`, message `m`):
`R = r • B` and `S = r + H(R, A, m) * a`. -/
def sign {M : Type*} (P : Params G) (H : G → G → M → Scalar) (a r : Scalar) (m : M) :
    Sig G :=
  { R := r • P.base
    S := r + H (r • P.base) (publicKey P a) m * a }

/-- The Ed25519 verification equation: `S • B = R + H(R, A, m) • A`. -/
def verify {M : Type*} (P : Params G) (H : G → G → M → Scalar) (A : G) (m : M)
    (sig : Sig G) : Prop :=
  sig.S • P.base = sig.R + H sig.R A m • A

/-- Faithfulness of the base point, in the convenient "cancellation" form. -/
theorem smul_base_inj (P : Params G) {c d : Scalar} (h : c • P.base = d • P.base) :
    c = d := by
  have : (c - d) • P.base = 0 := by
    rw [sub_smul, h, sub_self]
  have := P.base_faithful _ this
  exact sub_eq_zero.mp this

/-- **Soundness and completeness of the Ed25519 verification engine.**
A candidate signature `sig` passes the verification equation against the public key
`A = a • B` if and only if it is *the* honestly generated signature for a unique nonce
`r`: namely `sig.R = r • B` and `sig.S = r + H(sig.R, A, m) * a`.

The forward direction is soundness (anything the checker accepts really is the honest
Schnorr/EdDSA response for the committed nonce, so accepting a signature extracts a
witness for the key relation); the backward direction is completeness (honest
signatures are always accepted). -/
theorem ed25519_verify_sound {M : Type*} (P : Params G) (H : G → G → M → Scalar)
    (a : Scalar) (m : M) (sig : Sig G) :
    verify P H (publicKey P a) m sig ↔
      ∃! r : Scalar, sig.R = r • P.base ∧
        sig.S = r + H sig.R (publicKey P a) m * a := by
  obtain ⟨r, hr⟩ := P.base_generates sig.R
  constructor
  · intro hv
    refine ⟨r, ⟨hr, ?_⟩, ?_⟩
    · have hv' : sig.S • P.base
          = (r + H sig.R (publicKey P a) m * a) • P.base := by
        rw [add_smul, mul_smul, ← publicKey, ← hr]
        exact hv
      exact smul_base_inj P hv'
    · rintro r' ⟨hr', -⟩
      exact smul_base_inj P (hr' ▸ hr ▸ rfl : r' • P.base = r • P.base)
  · rintro ⟨r', ⟨hr', hs'⟩, -⟩
    rw [verify, hs', hr', publicKey, add_smul, mul_smul]

/-- Completeness, stated directly for the signing algorithm: an honestly produced
signature always verifies. -/
theorem ed25519_sign_verify {M : Type*} (P : Params G) (H : G → G → M → Scalar)
    (a r : Scalar) (m : M) :
    verify P H (publicKey P a) m (sign P H a r m) := by
  rw [verify, sign, publicKey, add_smul, mul_smul]

/-- Determinism / isolation: verification depends only on the certificate data
`(A, m, sig)` and on the hash value at that data, never on any hidden state. -/
theorem verify_congr {M : Type*} (P : Params G) (H H' : G → G → M → Scalar) (A : G)
    (m : M) (sig : Sig G) (hH : H sig.R A m = H' sig.R A m) :
    verify P H A m sig ↔ verify P H' A m sig := by
  rw [verify, verify, hH]

/-- **Key extraction from a nonce reuse.** If two signatures with the same commitment
`R` but distinct challenges both verify against `A = a • B`, then the secret scalar is
recovered as `(S₁ - S₂) / (h₁ - h₂)`. This is the formal statement that the engine's
accept predicate leaks the whole secret under nonce reuse. -/
theorem ed25519_extract_secret [Fact (Nat.Prime ed25519Order)] (P : Params G)
    (a S₁ S₂ h₁ h₂ : Scalar) (R : G)
    (hne : h₁ ≠ h₂)
    (hv₁ : S₁ • P.base = R + h₁ • publicKey P a)
    (hv₂ : S₂ • P.base = R + h₂ • publicKey P a) :
    a = (S₁ - S₂) / (h₁ - h₂) := by
  have hkey : (S₁ - S₂) • P.base = ((h₁ - h₂) * a) • P.base := by
    rw [sub_smul, hv₁, hv₂, publicKey, sub_mul, sub_smul, mul_smul, mul_smul]
    abel
  have h1 : S₁ - S₂ = (h₁ - h₂) * a := smul_base_inj P hkey
  have h2 : h₁ - h₂ ≠ 0 := sub_ne_zero.mpr hne
  rw [eq_div_iff h2, h1]
  ring

/-- The model is non-vacuous: the cyclic group `ZMod ed25519Order` with base point `1`
is a legitimate instance of `Params`, so the theorems above are not vacuously true. -/
def standardParams : Params Scalar where
  base := 1
  base_faithful := by
    intro c hc
    simpa using hc
  base_generates := by
    intro Q
    exact ⟨Q, by simp⟩

end PCA.Cert

#print axioms PCA.Cert.ed25519_verify_sound
#print axioms PCA.Cert.ed25519_sign_verify
#print axioms PCA.Cert.ed25519_extract_secret
#print axioms PCA.Cert.verify_congr

