import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

/-! ## The molecular point group of benzene

Benzene (C₆H₆) is a planar regular hexagon, whose point group is `D₆ₕ`.
As an abstract group `D₆ₕ ≅ D₆ × Cᵢ`, i.e. the dihedral group of order `12`
(the symmetries of the hexagon) times the two-element group generated by the
inversion centre `i`. -/

/-- The point group `D₆ₕ`, realized as `D₆ × Cᵢ` (a group of order `24`). -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- The order of `D₆ₕ` is `24`. -/
theorem card_D6h : Fintype.card D6h = 24 := by decide

/-- `D₆ₕ` has exactly `12` conjugacy classes:
`E, 2C₆, 2C₃, C₂, 3C₂', 3C₂''` and their products with the inversion `i`
(namely `i, 2S₃, 2S₆, σₕ, 3σ_d, 3σ_v`). -/
theorem card_conjClasses_D6h : Fintype.card (ConjClasses D6h) = 12 := by decide

/-- The sizes of the twelve conjugacy classes of `D₆ₕ`, in the standard order
`E, 2C₆, 2C₃, C₂, 3C₂', 3C₂'', i, 2S₃, 2S₆, σₕ, 3σ_d, 3σ_v`. -/
def d6hClassSize : Fin 12 → ℕ := ![1, 2, 2, 1, 3, 3, 1, 2, 2, 1, 3, 3]

/-- The character table of `D₆ₕ`.

Rows are the twelve irreducible representations
`A₁g, A₂g, B₁g, B₂g, E₁g, E₂g, A₁u, A₂u, B₁u, B₂u, E₁u, E₂u`
and columns are the twelve conjugacy classes
`E, 2C₆, 2C₃, C₂, 3C₂', 3C₂'', i, 2S₃, 2S₆, σₕ, 3σ_d, 3σ_v`.
All characters of `D₆ₕ` are rational integers, so the table is `ℤ`-valued. -/
def d6hCharTable : Fin 12 → Fin 12 → ℤ :=
  ![ ![ 1,  1,  1,  1,  1,  1,   1,  1,  1,  1,  1,  1],   -- A₁g
     ![ 1,  1,  1,  1, -1, -1,   1,  1,  1,  1, -1, -1],   -- A₂g
     ![ 1, -1,  1, -1,  1, -1,   1, -1,  1, -1,  1, -1],   -- B₁g
     ![ 1, -1,  1, -1, -1,  1,   1, -1,  1, -1, -1,  1],   -- B₂g
     ![ 2,  1, -1, -2,  0,  0,   2,  1, -1, -2,  0,  0],   -- E₁g
     ![ 2, -1, -1,  2,  0,  0,   2, -1, -1,  2,  0,  0],   -- E₂g
     ![ 1,  1,  1,  1,  1,  1,  -1, -1, -1, -1, -1, -1],   -- A₁u
     ![ 1,  1,  1,  1, -1, -1,  -1, -1, -1, -1,  1,  1],   -- A₂u
     ![ 1, -1,  1, -1,  1, -1,  -1,  1, -1,  1, -1,  1],   -- B₁u
     ![ 1, -1,  1, -1, -1,  1,  -1,  1, -1,  1,  1, -1],   -- B₂u
     ![ 2,  1, -1, -2,  0,  0,  -2, -1,  1,  2,  0,  0],   -- E₁u
     ![ 2, -1, -1,  2,  0,  0,  -2,  1,  1, -2,  0,  0]]   -- E₂u

/-- The dimension of the `i`-th irreducible representation, i.e. its character
at the identity class. -/
def d6hDim (i : Fin 12) : ℤ := d6hCharTable i 0

/-- The listed class sizes are the genuine conjugacy class sizes of `D₆ₕ`:
the multiset of cardinalities of the conjugacy classes of `D₆ₕ` agrees with
`d6hClassSize`. -/
theorem d6hClassSize_eq :
    ((Finset.univ : Finset (ConjClasses D6h)).val.map
        (fun c => (Finset.univ.filter (fun x : D6h => ConjClasses.mk x = c)).card))
      = (Multiset.ofList (List.ofFn d6hClassSize)) := by
  decide

/-- The class sizes add up to the group order. -/
theorem sum_d6hClassSize : ∑ c : Fin 12, d6hClassSize c = 24 := by decide

/-- **Row orthonormality** of the character table of `D₆ₕ`:
`(1/|G|) ∑_classes |class| · χᵢ · χⱼ = δᵢⱼ` (all characters here are real). -/
theorem d6h_row_orthogonality (i j : Fin 12) :
    (∑ c : Fin 12, (d6hClassSize c : ℤ) * d6hCharTable i c * d6hCharTable j c)
      = if i = j then 24 else 0 := by
  revert i j; decide

/-- **Column orthogonality** of the character table of `D₆ₕ`:
`∑_irreps χᵢ(c) · χᵢ(d) = δ_{cd} · |G| / |class c|`. -/
theorem d6h_column_orthogonality (c d : Fin 12) :
    (d6hClassSize c : ℤ) * (∑ i : Fin 12, d6hCharTable i c * d6hCharTable i d)
      = if c = d then 24 else 0 := by
  revert c d; decide

/-- The rows of the table are pairwise distinct characters. -/
theorem d6hCharTable_injective : Function.Injective d6hCharTable := by
  decide

/-- The dimensions of the twelve irreducible representations are
`1,1,1,1,2,2,1,1,1,1,2,2`, and the sum of their squares is the group order `24`. -/
theorem sum_sq_d6hDim : ∑ i : Fin 12, d6hDim i ^ 2 = 24 := by decide

/-- **Benzene / `D₆ₕ` irreducible representations.**

The character table of the benzene point group `D₆ₕ` (`≅ D₆ × Cᵢ`, of order `24`)
has the correct number of irreducible representations: there are exactly `12`
rows, matching the `12` conjugacy classes of `D₆ₕ`.  Moreover the tabulated data
really is a complete character table:

* the tabulated class sizes are the true conjugacy class sizes of `D₆ₕ`, and sum
  to the group order `24`;
* the rows are orthonormal with respect to the class-weighted inner product
  (row orthogonality), hence pairwise distinct;
* the columns satisfy the dual (column) orthogonality relations;
* the dimensions `1,1,1,1,2,2,1,1,1,1,2,2` satisfy `∑ dᵢ² = |D₆ₕ| = 24`. -/
theorem benzene_D6h_irreps :
    Fintype.card D6h = 24 ∧
    Fintype.card (ConjClasses D6h) = 12 ∧
    Fintype.card (Fin 12) = Fintype.card (ConjClasses D6h) ∧
    ((Finset.univ : Finset (ConjClasses D6h)).val.map
        (fun c => (Finset.univ.filter (fun x : D6h => ConjClasses.mk x = c)).card))
      = (Multiset.ofList (List.ofFn d6hClassSize)) ∧
    (∑ c : Fin 12, d6hClassSize c) = Fintype.card D6h ∧
    (∀ i j : Fin 12,
      (∑ c : Fin 12, (d6hClassSize c : ℤ) * d6hCharTable i c * d6hCharTable j c)
        = if i = j then 24 else 0) ∧
    (∀ c d : Fin 12,
      (d6hClassSize c : ℤ) * (∑ i : Fin 12, d6hCharTable i c * d6hCharTable i d)
        = if c = d then 24 else 0) ∧
    Function.Injective d6hCharTable ∧
    (∑ i : Fin 12, d6hDim i ^ 2) = (Fintype.card D6h : ℤ) := by
  refine ⟨card_D6h, card_conjClasses_D6h, ?_, d6hClassSize_eq, ?_,
    d6h_row_orthogonality, d6h_column_orthogonality, d6hCharTable_injective, ?_⟩
  · rw [card_conjClasses_D6h, Fintype.card_fin]
  · rw [card_D6h, sum_d6hClassSize]
  · rw [card_D6h, sum_sq_d6hDim]
    norm_num

end Chem

