import Mathlib

/-!
# Higgs Mass Toy
Category: Frontier Physics
Target: Frontier.higgs_mass_toy
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-- Mexican-hat (abelian Higgs) potential for a radial scalar field profile `r = |φ|`,
with quartic coupling `lam` and symmetry-breaking scale `v`:
`V(r) = lam * (r² - v²)²`. -/
noncomputable def higgsPotential (lam v r : ℝ) : ℝ := lam * (r ^ 2 - v ^ 2) ^ 2

/-- Squared mass of the abelian gauge boson generated by a scalar background of
modulus `r` through the covariant kinetic term `|(∂ - i e A) φ|²`:
`m_A² = e² r²`. -/
noncomputable def gaugeMassSq (e r : ℝ) : ℝ := e ^ 2 * r ^ 2

/-- The gauge boson mass itself, `m_A = |e| * r` for `r ≥ 0`. -/
noncomputable def gaugeMass (e r : ℝ) : ℝ := |e| * r

lemma gaugeMass_sq (e r : ℝ) :
    gaugeMass e r ^ 2 = gaugeMassSq e r := by
  unfold gaugeMass gaugeMassSq
  rw [mul_pow, sq_abs]

/-- **Key intermediate lemma.** For a positive quartic coupling the Mexican-hat potential
is minimized exactly on the circle of vacua `r² = v²`: the value at `r = v` is a global
minimum, and any configuration attaining it has `r² = v²`. -/
lemma higgsPotential_min (lam v : ℝ) (hlam : 0 < lam) :
    (∀ r : ℝ, higgsPotential lam v v ≤ higgsPotential lam v r) ∧
      ∀ r : ℝ, higgsPotential lam v r = higgsPotential lam v v → r ^ 2 = v ^ 2 := by
  have hv : higgsPotential lam v v = 0 := by
    unfold higgsPotential; ring
  constructor
  · intro r
    rw [hv]
    unfold higgsPotential
    positivity
  · intro r hr
    rw [hv] at hr
    unfold higgsPotential at hr
    have h : (r ^ 2 - v ^ 2) ^ 2 = 0 := by
      rcases mul_eq_zero.mp hr with h | h
      · exact absurd h (ne_of_gt hlam)
      · exact h
    have := pow_eq_zero_iff (n := 2) (by norm_num) |>.mp h
    linarith

/-- **Abelian Higgs toy model: spontaneous symmetry breaking gives the gauge boson a mass.**

With quartic coupling `lam > 0`, symmetry-breaking scale `v > 0` and gauge coupling `e ≠ 0`:

1. the symmetric configuration `r = 0` is *not* a minimum of the potential (the potential
   is strictly lower at `r = v`), and there the gauge boson is massless;
2. `r = v` is a global minimum of the potential;
3. every global minimum `r` produces the same, strictly positive gauge boson mass squared
   `e² v²`, realized by the mass `m_A = |e| v > 0`.
-/
theorem higgs_mass_toy (lam v e : ℝ) (hlam : 0 < lam) (hv : 0 < v) (he : e ≠ 0) :
    gaugeMassSq e 0 = 0 ∧
    higgsPotential lam v v < higgsPotential lam v 0 ∧
    (∀ r : ℝ, higgsPotential lam v v ≤ higgsPotential lam v r) ∧
    (∀ r : ℝ, higgsPotential lam v r = higgsPotential lam v v →
      gaugeMassSq e r = e ^ 2 * v ^ 2) ∧
    0 < gaugeMassSq e v ∧
    gaugeMass e v ^ 2 = gaugeMassSq e v ∧
    0 < gaugeMass e v := by
  obtain ⟨hmin, hvac⟩ := higgsPotential_min lam v hlam
  refine ⟨by simp [gaugeMassSq], ?_, hmin, ?_, ?_, gaugeMass_sq e v, ?_⟩
  · unfold higgsPotential
    have h1 : (v : ℝ) ^ 2 - v ^ 2 = 0 := by ring
    have h2 : ((0 : ℝ) ^ 2 - v ^ 2) ^ 2 = v ^ 4 := by ring
    rw [h1, h2]
    have : 0 < v ^ 4 := by positivity
    nlinarith
  · intro r hr
    unfold gaugeMassSq
    rw [hvac r hr]
  · unfold gaugeMassSq
    have : 0 < e ^ 2 := by positivity
    positivity
  · unfold gaugeMass
    have : 0 < |e| := abs_pos.mpr he
    positivity

end Frontier

