import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/


open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames false

namespace Chem

attribute [local instance] arrowAction

variable {G : Type*} [Group G] {P : Type*} [MulAction G P] {C : Type*}

/-- The number of cycles of the skeleton symmetry `g` acting on the substitution sites `P`:
the number of orbits of the cyclic group generated by `g`. -/
noncomputable def cycleCount (P : Type*) [MulAction G P] (g : G) : ℕ :=
  Nat.card (MulAction.orbitRel.Quotient (Subgroup.zpowers g) P)

/-- A coloring fixed by `g` is constant along the `⟨g⟩`-orbits. -/
lemma fixed_coloring_const_of_zpowers {g : G} {f : P → C}
    (hf : g • f = f) {p : P} {h : G} (hh : h ∈ Subgroup.zpowers g) :
    f (h • p) = f p := by
  have hstep : ∀ q : P, f (g • q) = f q := by
    intro q
    have h1 : (g • f) (g • q) = f (g • q) := by rw [hf]
    have h2 : (g • f) (g • q) = f q := by
      show f (g⁻¹ • (g • q)) = f q
      rw [inv_smul_smul]
    rw [← h1, h2]
  have hstep' : ∀ q : P, f (g⁻¹ • q) = f q := by
    intro q
    have := hstep (g⁻¹ • q)
    simpa [smul_inv_smul] using this.symm
  obtain ⟨n, rfl⟩ := hh
  induction n using Int.induction_on with
  | zero => simp
  | succ n ih =>
      have : (g ^ (n + 1 : ℤ)) • p = g • ((g ^ (n : ℤ)) • p) := by
        rw [add_comm, zpow_one_add, mul_smul]
      rw [this, hstep, ih]
  | pred n ih =>
      have : (g ^ (-(n : ℤ) - 1)) • p = g⁻¹ • ((g ^ (-(n : ℤ))) • p) := by
        rw [show (-(n : ℤ) - 1) = -1 + -(n : ℤ) by ring, zpow_add, mul_smul, zpow_neg_one]
      rw [this, hstep', ih]

/-- The identity symmetry has one cycle per site. -/
lemma cycleCount_one : cycleCount P (1 : G) = Nat.card P := by
  refine Nat.card_congr ?_
  refine
    { toFun := fun q => Quotient.liftOn q id ?_
      invFun := fun p => Quotient.mk _ p
      left_inv := ?_
      right_inv := fun p => rfl }
  · rintro a b ⟨⟨h, hh⟩, rfl⟩
    have : h = 1 := by
      simpa [Subgroup.zpowers_one_eq_bot, Subgroup.mem_bot] using hh
    subst this
    simp
  · intro q
    induction q using Quotient.inductionOn with
    | _ p => rfl

/-- Colorings of the skeleton fixed by `g` correspond exactly to colorings of the set of
`⟨g⟩`-orbits (cycles) of `g`. -/
noncomputable def fixedByEquivCycleColorings (g : G) :
    MulAction.fixedBy (P → C) g ≃ (MulAction.orbitRel.Quotient (Subgroup.zpowers g) P → C) where
  toFun f := fun q => Quotient.liftOn q (fun p => (f : P → C) p) (by
    rintro a b hab
    obtain ⟨h, rfl⟩ := hab
    exact fixed_coloring_const_of_zpowers f.2 h.2)
  invFun F := ⟨fun p => F (Quotient.mk _ p), by
    have : ∀ p : P, F (Quotient.mk (MulAction.orbitRel (Subgroup.zpowers g) P) (g⁻¹ • p))
        = F (Quotient.mk (MulAction.orbitRel (Subgroup.zpowers g) P) p) := by
      intro p
      congr 1
      exact Quotient.sound ⟨⟨g⁻¹, Subgroup.inv_mem _ (Subgroup.mem_zpowers g)⟩, rfl⟩
    funext p
    simpa [arrowAction] using this p⟩
  left_inv f := by ext p; rfl
  right_inv F := by
    funext q
    induction q using Quotient.inductionOn with
    | _ p => rfl

lemma card_fixedBy_colorings (g : G) [Finite P] :
    Nat.card (MulAction.fixedBy (P → C) g) = Nat.card C ^ cycleCount P g := by
  rw [Nat.card_congr (fixedByEquivCycleColorings (C := C) g), cycleCount,
    Nat.card_fun]

/-- **Pólya / Burnside isomer count.**
Let a finite symmetry group `G` act on the set `P` of substitution sites of a molecular
skeleton, and let `C` be the finite set of substituents.  Substitution isomers are the orbits
of `G` on the colorings `P → C` (with `(g • f) p = f (g⁻¹ • p)`).  Then the number of isomers,
multiplied by the order of the symmetry group, equals the sum over group elements of
`|C| ^ (number of cycles of g)`, i.e. the number of isomers is the Pólya cycle-index average
`(1/|G|) ∑_{g ∈ G} |C| ^ c(g)`. -/
theorem polya_isomer_count (G : Type*) [Group G] [Fintype G]
    (P : Type*) [Finite P] [MulAction G P] (C : Type*) [Finite C] :
    Nat.card (MulAction.orbitRel.Quotient G (P → C)) * Nat.card G
      = ∑ g : G, Nat.card C ^ cycleCount P g := by
  classical
  haveI : Fintype P := Fintype.ofFinite P
  haveI : Fintype C := Fintype.ofFinite C
  haveI : ∀ g : G, Fintype (MulAction.fixedBy (P → C) g) := fun _ => Fintype.ofFinite _
  haveI : Fintype (MulAction.orbitRel.Quotient G (P → C)) := Fintype.ofFinite _
  have burnside :
      (∑ g : G, Fintype.card (MulAction.fixedBy (P → C) g))
        = Fintype.card (MulAction.orbitRel.Quotient G (P → C)) * Fintype.card G :=
    MulAction.sum_card_fixedBy_eq_card_orbits_mul_card_group G (P → C)
  calc Nat.card (MulAction.orbitRel.Quotient G (P → C)) * Nat.card G
      = Fintype.card (MulAction.orbitRel.Quotient G (P → C)) * Fintype.card G := by
        simp [Nat.card_eq_fintype_card]
    _ = ∑ g : G, Fintype.card (MulAction.fixedBy (P → C) g) := burnside.symm
    _ = ∑ g : G, Nat.card C ^ cycleCount P g := by
        refine Finset.sum_congr rfl fun g _ => ?_
        rw [← Nat.card_eq_fintype_card]
        exact card_fixedBy_colorings g

/-- **Pólya cycle-index average form.**  The number of substitution isomers is the average,
over the symmetry group, of `|C| ^ (number of cycles of g)`. -/
theorem polya_isomer_count_average (G : Type*) [Group G] [Fintype G]
    (P : Type*) [Finite P] [MulAction G P] (C : Type*) [Finite C] :
    (Nat.card (MulAction.orbitRel.Quotient G (P → C)) : ℚ)
      = (1 / (Nat.card G : ℚ)) * ∑ g : G, (Nat.card C : ℚ) ^ cycleCount P g := by
  have hG : (Nat.card G : ℚ) ≠ 0 := by
    exact_mod_cast Nat.card_pos.ne'
  have h := polya_isomer_count G P C
  have h' : (Nat.card (MulAction.orbitRel.Quotient G (P → C)) : ℚ) * (Nat.card G : ℚ)
      = ∑ g : G, (Nat.card C : ℚ) ^ cycleCount P g := by
    have := congrArg (fun n : ℕ => (n : ℚ)) h
    push_cast at this
    simpa using this
  field_simp
  exact h'

end Chem

