/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 94620ec8-a686-4424-95ac-3eee4b447437

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat Classical

/-!
# COMPLETE BROCKIAN MAGNUM OPUS - ULTIMATE IMPLEMENTATION
This version provides complete proofs for all missing components
-/

/-!
# Tier I: Golden Ratio - Complete Algebraic Structure (PROVEN)
-/
noncomputable def phi : ℝ := (1 + Real.sqrt 5) / 2
noncomputable def psi : ℝ := (1 - Real.sqrt 5) / 2

lemma phi_pos : 0 < phi := by
  -- Since $\phi = \frac{1 + \sqrt{5}}{2}$, we know that $\phi > 0$.
  apply div_pos; apply add_pos_of_nonneg_of_pos; norm_num; apply Real.sqrt_pos.mpr; norm_num; norm_num

lemma phi_gt_one : 1 < phi := by
  -- By definition of phi, we know that phi = (1 + Real.sqrt 5) / 2.
  have h_phi_def : phi = (1 + Real.sqrt 5) / 2 := by
    -- By definition of phi, we know that phi = (1 + Real.sqrt 5) / 2.
    rw [show phi = (1 + Real.sqrt 5) / 2 from rfl]
  rw [h_phi_def]
  skip
  skip
  skip
  skip
  exact by nlinarith [Real.sqrt_nonneg 5, Real.sq_sqrt (show 0 ≤ 5 by norm_num)] ;

theorem golden_identity : phi ^ 2 = phi + 1 := by
  -- By definition of phi, we know that phi^2 = phi + 1.
  rw [show phi = (1 + Real.sqrt 5) / 2 from rfl]
  field_simp
  ring;
  -- Simplify the expression $1 + \sqrt{5} * 2 + (\sqrt{5})^2$ to get $6 + \sqrt{5} * 2$.
  norm_num
  ring

theorem golden_reciprocal : 1 / phi = phi - 1 := by
  -- By definition of phi, we have phi = (1 + Real.sqrt 5) / 2.
  have h_phi_def : phi = (1 + Real.sqrt 5) / 2 := by
    -- By definition of phi, we know that phi = (1 + Real.sqrt 5) / 2.
    rw [show phi = (1 + Real.sqrt 5) / 2 from rfl];
  rw [ h_phi_def, div_eq_iff ] <;> nlinarith [ Real.sq_sqrt ( show 0 ≤ 5 by norm_num ) ]

theorem golden_vieta : phi * psi = -1 ∧ phi + psi = 1 := by
  -- Let's calculate $\varphi \psi$ and $\varphi + \psi$ using the definitions of $\varphi$ and $\psi$.
  field_simp [phi, psi]
  ring_nf
  norm_num [phi, psi] at *

noncomputable def pentagonVertex (k : Fin 5) : ℂ :=
  Complex.exp (2 * Real.pi * Complex.I * (k : ℝ) / 5)

#check Real.sqrt
#check Complex.normSq

noncomputable def pentagonDistance (j k : Fin 5) : ℝ :=
  Real.sqrt (Complex.normSq (pentagonVertex j - pentagonVertex k))

noncomputable def Complex.abs (z : ℂ) : ℝ := Real.sqrt (Complex.normSq z)

lemma pentagonVertex_abs (k : Fin 5) : Complex.abs (pentagonVertex k) = 1 := by
  -- The absolute value of the exponential of a purely imaginary number is 1.
  have h_exp_abs : ∀ θ : ℝ, Complex.abs (Complex.exp (θ * Complex.I)) = 1 := by
    -- Apply the lemma that states the absolute value of the exponential of a purely imaginary number is 1.
    intros θ
    apply Complex.norm_exp_ofReal_mul_I;
  -- Apply the fact that the absolute value of the exponential of a purely imaginary number is 1.
  convert h_exp_abs (2 * Real.pi * k / 5) using 1;
  -- Since the exponent is purely imaginary, the absolute value of the exponential is 1.
  simp [pentagonVertex, Complex.norm_exp];
  -- The exponents are identical, so their absolute values are equal.
  ring_nf at *

lemma Complex.abs_normSq (z : ℂ) : Complex.abs z ^ 2 = Complex.normSq z := by
  -- By definition of absolute value, we know that $|z|^2 = z \cdot \overline{z}$.
  simp [Complex.normSq_eq_norm_sq];
  -- Since the norm and the absolute value are the same thing here, the equality holds trivially.
  apply Eq.refl

lemma Complex.abs_exp (z : ℂ) : Complex.abs (Complex.exp z) = Real.exp z.re := by
  -- The absolute value of the exponential of a complex number $z$ is the exponential of the real part of $z$. This follows from the definition of the exponential function for complex numbers.
  apply Complex.norm_exp

lemma Complex.normSq_exp (z : ℂ) : Complex.normSq (Complex.exp z) = (Real.exp z.re) ^ 2 := by
  -- By definition of exponentiation, we know that Complex.normSq (Complex.exp z) = |Complex.exp z|^2. Since Complex.exp z = e^(z.re + z.im * Complex.I), we have |Complex.exp z| = e^(z.re).
  simp [Complex.normSq_eq_norm_sq, Complex.norm_exp]

#check Real.sin_eq_sqrt_one_sub_cos_sq

/-- **COMPLETE PROOF**: Pentagon has exactly two distinct distances
This is a classical geometric result - sides and diagonals -/
lemma pentagon_two_distances :
    ∃! p : ℝ × ℝ, p.1 < p.2 ∧ p.1 > 0 ∧ p.2 > 0 ∧
      (∀ j k : Fin 5, j ≠ k →
        pentagonDistance j k = p.1 ∨ pentagonDistance j k = p.2) := by
          -- Let's first show that the distances between vertices are indeed two distinct values.
          have h_distinct : ∀ j k : Fin 5, j ≠ k → Real.sqrt (Complex.normSq (pentagonVertex j - pentagonVertex k)) = 2 * Real.sin (Real.pi / 5) ∨ Real.sqrt (Complex.normSq (pentagonVertex j - pentagonVertex k)) = 2 * Real.sin (2 * Real.pi / 5) := by
            -- By definition of pentagonVertex, we can express the distance between any two vertices using the chord length formula.
            have h_dist_formula : ∀ j k : Fin 5, j ≠ k → Real.sqrt (Complex.normSq (pentagonVertex j - pentagonVertex k)) = 2 * Real.sin (Real.pi * |(j : ℝ) - k| / 5) := by
              intros j k hjk;
              rw [ Real.sqrt_eq_iff_mul_self_eq ] <;> norm_num [ Complex.normSq, Complex.exp_re, Complex.exp_im ] <;> ring;
              · unfold pentagonVertex; norm_num [ Complex.exp_re, Complex.exp_im, Real.sin_sq, Real.cos_sq ] ; ring;
                rw [ abs_eq_max_neg ] ; rw [ max_def ] ; split_ifs <;> ring;
                · norm_num [ Real.cos_add, Real.sin_add ] ; ring;
                · norm_num [ Real.cos_add, Real.sin_add ] ; ring;
              · nlinarith [ sq_nonneg ( ( pentagonVertex j |> Complex.re ) - ( pentagonVertex k |> Complex.re ) ), sq_nonneg ( ( pentagonVertex j |> Complex.im ) - ( pentagonVertex k |> Complex.im ) ) ];
              · exact Real.sin_nonneg_of_nonneg_of_le_pi ( by positivity ) ( by fin_cases j <;> fin_cases k <;> norm_num <;> linarith [ Real.pi_pos ] );
            -- By examining the possible values of |(j : ℝ) - k|, we can see that the distances are either 2*sin(π/5) or 2*sin(2π/5).
            intros j k hjk
            have h_abs : |(j : ℝ) - k| = 1 ∨ |(j : ℝ) - k| = 2 ∨ |(j : ℝ) - k| = 3 ∨ |(j : ℝ) - k| = 4 := by
              fin_cases j <;> fin_cases k <;> norm_cast;
            rcases h_abs with ( h | h | h | h ) <;> rw [ h_dist_formula j k hjk, h ] <;> ring_nf <;> norm_num;
            · exact Or.inr ( by rw [ ← Real.sin_pi_sub ] ; ring );
            · exact Or.inl ( by rw [ ← Real.sin_pi_sub ] ; ring );
          -- Now let's show that these are the only two distances.
          have h_unique : ∀ p : ℝ × ℝ, p.1 < p.2 ∧ p.1 > 0 ∧ p.2 > 0 ∧ (∀ j k : Fin 5, j ≠ k → Real.sqrt (Complex.normSq (pentagonVertex j - pentagonVertex k)) = p.1 ∨ Real.sqrt (Complex.normSq (pentagonVertex j - pentagonVertex k)) = p.2) → p = (2 * Real.sin (Real.pi / 5), 2 * Real.sin (2 * Real.pi / 5)) := by
            intros p hp
            obtain ⟨hp1, hp2, hp3, hp4⟩ := hp
            have h_distinct : ∃ j k : Fin 5, j ≠ k ∧ Real.sqrt (Complex.normSq (pentagonVertex j - pentagonVertex k)) = 2 * Real.sin (Real.pi / 5) ∧ ∃ j k : Fin 5, j ≠ k ∧ Real.sqrt (Complex.normSq (pentagonVertex j - pentagonVertex k)) = 2 * Real.sin (2 * Real.pi / 5) := by
              refine' ⟨ 0, 1, _, _, 0, 2, _, _ ⟩ <;> norm_num [ Fin.ext_iff, Complex.normSq, Complex.exp_re, Complex.exp_im, pentagonVertex ];
              · rw [ Real.sqrt_eq_iff_mul_self_eq_of_pos ] <;> ring_nf <;> norm_num [ Real.sin_sq, Real.cos_sq ] <;> ring_nf;
                exact Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by linarith [ Real.pi_pos ] );
              · rw [ Real.sqrt_eq_iff_mul_self_eq ] <;> ring_nf <;> norm_num [ Real.sin_sq, Real.cos_sq ] <;> ring;
                · nlinarith [ Real.cos_sq' ( Real.pi * ( 4 / 5 ) ) ];
                · exact Real.sin_nonneg_of_mem_Icc ⟨ by linarith [ Real.pi_pos ], by linarith [ Real.pi_pos ] ⟩;
            have h_unique : 2 * Real.sin (Real.pi / 5) < 2 * Real.sin (2 * Real.pi / 5) := by
              exact mul_lt_mul_of_pos_left ( by rw [ ← Real.cos_pi_div_two_sub, ← Real.cos_pi_div_two_sub ] ; exact Real.cos_lt_cos_of_nonneg_of_le_pi ( by linarith [ Real.pi_pos ] ) ( by linarith [ Real.pi_pos ] ) ( by linarith [ Real.pi_pos ] ) ) zero_lt_two;
            grind;
          -- Therefore, the pair $(2 * \sin(\pi/5), 2 * \sin(2\pi/5))$ is the unique solution.
          use (2 * Real.sin (Real.pi / 5), 2 * Real.sin (2 * Real.pi / 5));
          refine' ⟨ ⟨ _, _, _, h_distinct ⟩, h_unique ⟩;
          · exact mul_lt_mul_of_pos_left ( by rw [ ← Real.cos_pi_div_two_sub, ← Real.cos_pi_div_two_sub ] ; exact Real.cos_lt_cos_of_nonneg_of_le_pi ( by linarith [ Real.pi_pos ] ) ( by linarith [ Real.pi_pos ] ) ( by linarith [ Real.pi_pos ] ) ) zero_lt_two;
          · exact mul_pos zero_lt_two ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by linarith [ Real.pi_pos ] ) );
          · exact mul_pos zero_lt_two ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by linarith [ Real.pi_pos ] ) )

/-- **KEY GEOMETRIC THEOREM**: Diagonal-to-side ratio equals φ -/
theorem pentagon_golden_ratio :
    ∃ (d_diag d_side : ℝ), 0 < d_side ∧
      (∀ j k : Fin 5, (k : ℕ) = ((j : ℕ) + 2) % 5 →
        pentagonDistance j k = d_diag) ∧
      (∀ j k : Fin 5, (k : ℕ) = ((j : ℕ) + 1) % 5 →
        pentagonDistance j k = d_side) ∧
      d_diag / d_side = phi := by
        -- Let's choose the side length $s = 1$.
        use 2 * Real.sin (2 * Real.pi / 5), 2 * Real.sin (Real.pi / 5);
        -- Now let's verify the distances and the ratio.
        apply And.intro;
        · exact mul_pos zero_lt_two ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by linarith [ Real.pi_pos ] ) );
        · -- Now let's verify the distances and the ratio for the pentagon.
          apply And.intro;
          · unfold pentagonDistance
            intro j k hk
            simp [pentagonVertex];
            norm_num [ Complex.normSq, Complex.exp_re, Complex.exp_im ] ; ring_nf ; norm_num;
            rw [ Real.sqrt_eq_iff_mul_self_eq_of_pos ] <;> norm_num [ Real.sin_sq, Real.cos_sq ] <;> ring;
            · fin_cases j <;> fin_cases k <;> norm_num [ hk ] at *;
              · rw [ Real.sin_sq, Real.cos_sq ] ; ring;
              · rw [ ← Complex.ofReal_inj ] ; norm_num [ Complex.sin, Complex.cos, Complex.exp_re, Complex.exp_im ] ; ring;
                norm_num [ sq, ← Complex.exp_add ] ; ring;
              · rw [ show Real.pi * 4 * ( 2 / 5 ) = 2 * ( Real.pi * 2 * ( 2 / 5 ) ) by ring, Real.sin_two_mul, Real.cos_two_mul ] ; ring;
                rw [ Real.sin_sq, Real.sin_sq ] ; ring;
                rw [ Real.cos_sq ] ; ring;
              · rw [ Real.sin_sq, Real.cos_sq ] ; ring;
                rw [ ← Real.cos_two_pi_sub ] ; ring;
              · rw [ Real.sin_sq, Real.cos_sq ] ; ring;
                rw [ show Real.pi * ( 8 / 5 ) = Real.pi * ( 3 / 5 ) + Real.pi by ring, show Real.pi * ( 2 / 5 ) = Real.pi - Real.pi * ( 3 / 5 ) by ring ] ; norm_num [ Real.sin_add, Real.sin_sub, Real.cos_add, Real.cos_sub ] ; ring;
                rw [ Real.sin_sq, Real.cos_sq ] ; ring;
                rw [ show Real.pi * ( 4 / 5 ) = Real.pi - Real.pi * ( 1 / 5 ) by ring, show Real.pi * ( 6 / 5 ) = Real.pi + Real.pi * ( 1 / 5 ) by ring, Real.cos_sub, Real.cos_add ] ; norm_num;
            · exact Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by linarith [ Real.pi_pos ] );
          · constructor;
            · -- By definition of pentagonDistance, we have:
              have h_dist : ∀ j k : Fin 5, pentagonDistance j k = 2 * |Real.sin ((j - k : ℝ) * Real.pi / 5)| := by
                unfold pentagonDistance;
                unfold pentagonVertex; norm_num [ Complex.normSq, Complex.exp_re, Complex.exp_im ] ; ring;
                intro j k; rw [ Real.sqrt_eq_iff_mul_self_eq ] <;> norm_num <;> ring <;> norm_num [ Real.sin_sq, Real.cos_sq ] <;> ring;
                · norm_num [ Real.cos_add, Real.sin_add ] ; ring;
                · nlinarith [ sq_nonneg ( Real.cos ( Real.pi * j * ( 2 / 5 ) ) - Real.cos ( Real.pi * k * ( 2 / 5 ) ) ), sq_nonneg ( Real.sin ( Real.pi * j * ( 2 / 5 ) ) - Real.sin ( Real.pi * k * ( 2 / 5 ) ) ), Real.cos_sq' ( Real.pi * j * ( 2 / 5 ) ), Real.cos_sq' ( Real.pi * k * ( 2 / 5 ) ) ];
              simp_all +decide [ Fin.forall_fin_succ ];
              norm_num [ neg_div, show 4 * Real.pi / 5 = Real.pi - Real.pi / 5 by ring ];
              exact Real.sin_nonneg_of_mem_Icc ⟨ by linarith [ Real.pi_pos ], by linarith [ Real.pi_pos ] ⟩;
            · rw [ div_eq_iff ] <;> norm_num [ Real.sin_two_mul, mul_div_assoc ];
              · unfold phi; ring;
              · exact ne_of_gt ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by linarith [ Real.pi_pos ] ) )

def goldbachPairs (n : ℕ) : Finset ℕ :=
  (Finset.range (n / 2 + 1)).filter (fun p => Nat.Prime p ∧ Nat.Prime (n - p))

def goldbachReps (n : ℕ) : ℕ := (goldbachPairs n).card

lemma goldbach_rep_exists {n : ℕ} (h : goldbachReps n ≥ 1) :
    ∃ p q, Nat.Prime p ∧ Nat.Prime q ∧ p + q = n := by
      -- By definition of `goldbachReps`, if `goldbachReps n ≥ 1`, then there exists at least one pair `(p, q)` in `goldbachPairs n`.
      obtain ⟨p, hp⟩ : ∃ p ∈ goldbachPairs n, True := by
        -- Since the cardinality of `goldbachPairs n` is at least 1, the set is non-empty.
        have h_nonempty : goldbachPairs n ≠ ∅ := by
          exact Finset.Nonempty.ne_empty ( Finset.card_pos.mp h );
        exact Exists.elim ( Finset.nonempty_of_ne_empty h_nonempty ) fun x hx => ⟨ x, hx, trivial ⟩;
      -- By definition of `goldbachPairs`, if `p ∈ goldbachPairs n`, then `p` is a prime and `n - p` is also a prime.
      obtain ⟨hp_prime, hq_prime⟩ : Nat.Prime p ∧ Nat.Prime (n - p) := by
        exact Finset.mem_filter.mp hp.1 |>.2;
      -- By definition of `goldbachPairs`, if `p ∈ goldbachPairs n`, then `p` is a prime and `n - p` is also a prime. Therefore, we can take `q = n - p`.
      use p, n - p;
      exact ⟨ hp_prime, hq_prime, Nat.add_sub_of_le <| le_of_not_gt fun h => by { rw [ tsub_eq_zero_iff_le.mpr h.le ] at hq_prime; norm_num at hq_prime } ⟩

#check Even

structure SpectralModel where
  mainTerm : ℕ → ℝ
  errTerm  : ℕ → ℝ
  err_nonneg : ∀ n, 0 ≤ errTerm n
  approx : ∀ n, n > 2 → Even n →
    |(goldbachReps n : ℝ) - mainTerm n| ≤ errTerm n
  N₀ : ℕ
  main_dominates : ∀ n, n > N₀ →
    (1/2 : ℝ) ≤ mainTerm n - errTerm n

structure EnhancedSpectralModel extends SpectralModel where
  singularSeries : ℕ → ℝ
  main_asymptotic : ∀ n, n > 2 → Even n →
    ∃ δ : ℝ, |δ| < 1 ∧
      mainTerm n = singularSeries n * (n : ℝ) / (Real.log n) ^ 2 * (1 + δ / Real.log n)
  singular_series_pos : ∃ c : ℝ, c > 0 ∧
    ∀ n, Even n → n > 2 → c ≤ singularSeries n

lemma le_of_abs_sub_le {x m e : ℝ} (h : |x - m| ≤ e) : m - e ≤ x := by
  rw [abs_sub_le_iff] at h
  linarith [h.1]

lemma le_of_abs_sub_le' {x m e : ℝ} (h : |x - m| ≤ e) : x ≤ m + e := by
  rw [abs_sub_le_iff] at h
  linarith [h.2]

lemma nat_cast_ge_one {n : ℕ} (h : n ≥ 1) : (n : ℝ) ≥ 1 := by
  exact Nat.one_le_cast.mpr h

/-- **MAIN CONDITIONAL THEOREM**: Complete proof -/
theorem goldbachReps_ge_one_of_model (M : SpectralModel) :
    ∀ n, n > max 2 M.N₀ → Even n → goldbachReps n ≥ 1 := by
  intro n hn hEven
  have hn_gt_2 : n > 2 := by
    calc n > max 2 M.N₀     := hn
         _ ≥ 2              := Nat.le_max_left 2 M.N₀
  have hn_gt_N₀ : n > M.N₀ := by
    calc n > max 2 M.N₀     := hn
         _ ≥ M.N₀           := Nat.le_max_right 2 M.N₀
  
  have h_approx := M.approx n hn_gt_2 hEven
  have h_lower : M.mainTerm n - M.errTerm n ≤ (goldbachReps n : ℝ) :=
    le_of_abs_sub_le h_approx
  have h_margin : (1/2 : ℝ) ≤ M.mainTerm n - M.errTerm n :=
    M.main_dominates n hn_gt_N₀
  have h_half : (1/2 : ℝ) ≤ (goldbachReps n : ℝ) :=
    le_trans h_margin h_lower
  
  by_contra hnot
  have hlt1 : goldbachReps n < 1 := Nat.lt_of_not_ge hnot
  have hz : goldbachReps n = 0 := Nat.lt_one_iff.mp hlt1
  have : (goldbachReps n : ℝ) = 0 := by simp [hz]
  linarith

lemma SpectralModel.mainTerm_eventually_pos (M : SpectralModel) : ∀ n, n > M.N₀ → 0 < M.mainTerm n := by
  intro n hn
  have h_margin := M.main_dominates n hn
  have h_err := M.err_nonneg n
  linarith

lemma SpectralModel.errTerm_eventually_dominated (M : SpectralModel) : ∀ n, n > M.N₀ →
    M.errTerm n < M.mainTerm n := by
  intro n hn
  have h_margin := M.main_dominates n hn
  linarith

def Goldbach (n : ℕ) : Prop :=
  ∃ p q, Nat.Prime p ∧ Nat.Prime q ∧ p + q = n

/-- **COMPLETE CONDITIONAL THEOREM** -/
theorem goldbach_from_spectral_model
    (M : SpectralModel)
    (h_small : ∀ n, n ≤ max 2 M.N₀ → n > 2 → Even n → Goldbach n) :
    ∀ n, n > 2 → Even n → Goldbach n := by
  intro n hn_gt_2 hEven
  by_cases hcase : n ≤ max 2 M.N₀
  · exact h_small n hcase hn_gt_2 hEven
  · push_neg at hcase
    have hn_large : n > max 2 M.N₀ := hcase
    have h_reps : goldbachReps n ≥ 1 :=
      goldbachReps_ge_one_of_model M n hn_large hEven
    obtain ⟨p, q, hp, hq, hsum⟩ := goldbach_rep_exists h_reps
    exact ⟨p, q, hp, hq, hsum⟩

/-- **COMPLETE INCREMENTAL THEOREM** -/
theorem goldbach_incremental
    (T : ℕ)
    (h_verified : ∀ n, 2 < n ∧ n ≤ T → Even n → Goldbach n)
    (M : SpectralModel)
    (h_threshold : M.N₀ ≤ T) :
    ∀ n, n > 2 → Even n → Goldbach n := by
  apply goldbach_from_spectral_model M
  intro n hn_le hn_gt_2 hEven
  apply h_verified n ⟨hn_gt_2, ?_⟩
  · exact hEven
  calc n ≤ max 2 M.N₀  := hn_le
       _ ≤ max 2 T     := by omega
       _ = T           := by omega

/-- The golden convolution operator incorporating D₅ symmetry -/
noncomputable def goldenConvolution (f : ℕ → ℝ) (n : ℕ) : ℝ :=
  ∑ d ∈ Nat.divisors n, phi^(-((Nat.divisors n).card : ℝ)) * f d * f (n / d)

/-- **GOLDEN CONVOLUTION THEOREM**: Complete proof -/
theorem golden_convolution_theorem {f g : ℕ → ℝ} (n : ℕ)
    (hf : ∀ d ∈ Nat.divisors n, f d = ∑ k ∈ Nat.divisors d, phi^(-((Nat.divisors d).card : ℝ)) * g k * g (d / k)) :
    goldenConvolution f n = ∑ d ∈ Nat.divisors n, phi^(-((Nat.divisors n).card : ℝ)) *
      (∑ k ∈ Nat.divisors d, phi^(-((Nat.divisors d).card : ℝ)) * g k * g (d / k)) *
      (∑ l ∈ Nat.divisors (n / d), phi^(-((Nat.divisors (n / d)).card : ℝ)) * g l * g ((n / d) / l)) := by
        -- Apply the definition of `goldenConvolution` and substitute `f` with the sums from `hf`.
        apply Finset.sum_congr rfl;
        -- Apply the hypothesis `hf` to both `f x` and `f (n / x)` since `x` and `n / x` are divisors of `n`.
        intros x hx
        rw [hf x hx, hf (n / x) (Nat.mem_divisors.mpr ⟨Nat.div_dvd_of_dvd (Nat.dvd_of_mem_divisors hx), by
          -- Since $x$ is a divisor of $n$, $n$ cannot be zero.
          aesop⟩)]

#check Matrix.of

noncomputable def hardyLittlewoodSingularSeries (n : ℕ) : ℝ :=
  if n % 2 = 0 then
    2 * ∏ p ∈ (Nat.primeFactors n \ {2}), (1 - 1 / ((p : ℝ) - 1)^2)
  else 0

lemma singular_series_lower_bound :
  ∃ c : ℝ, c > 0 ∧ ∀ n, Even n → n > 2 →
    c ≤ hardyLittlewoodSingularSeries n := by
      -- Let's choose any $c > 0$ and show that the singular series is bounded below by $c$ for sufficiently large $n$.
      use 1 / 4; norm_num;
      -- For even n > 2, the singular series is at least 1/4 because the product over the odd primes is at least 1/2.
      intros n hn_even hn_gt2
      have h_prod : ∏ p ∈ (Nat.primeFactors n \ {2}), (1 - 1 / ((p : ℝ) - 1)^2) ≥ 1 / 2 := by
        -- Since the product of terms of the form $(1 - 1 / (p - 1)^2)$ is greater than or equal to $1/2$ for any finite set of primes $p$, we can conclude that the singular series is bounded below by $1/2$.
        have h_prod_bound : ∀ {S : Finset ℕ}, (∀ p ∈ S, Nat.Prime p ∧ p > 2) → (∏ p ∈ S, (1 - 1 / ((p - 1) ^ 2 : ℝ))) ≥ 1 / 2 := by
          intros S hS
          have h_prod_bound : (∏ p ∈ S, (1 - 1 / ((p - 1) ^ 2 : ℝ))) ≥ (∏ p ∈ Finset.Icc 3 (Finset.sup S id), (1 - 1 / ((p - 1) ^ 2 : ℝ))) := by
            rw [ ← Finset.prod_sdiff ( show S ⊆ Finset.Icc 3 ( Finset.sup S id ) from fun p hp => Finset.mem_Icc.mpr ⟨ by linarith [ hS p hp ], Finset.le_sup ( f := id ) hp ⟩ ) ];
            refine' mul_le_of_le_one_left ( Finset.prod_nonneg fun x hx => sub_nonneg.mpr <| div_le_self zero_le_one <| one_le_pow₀ <| by linarith [ show ( x : ℝ ) ≥ 3 by norm_cast; linarith [ hS x hx ] ] ) _;
            exact Finset.prod_le_one ( fun x hx => sub_nonneg.mpr <| div_le_self zero_le_one <| one_le_pow₀ <| by linarith [ show ( x : ℝ ) ≥ 3 by norm_cast; linarith [ Finset.mem_Icc.mp <| Finset.mem_sdiff.mp hx |>.1 ] ] ) fun x hx => sub_le_self _ <| by positivity;
          -- Notice that $\prod_{p=3}^{m} (1 - 1 / (p - 1)^2) = \frac{m}{2(m - 1)}$ for any $m \geq 3$.
          have h_prod_formula : ∀ m : ℕ, 3 ≤ m → (∏ p ∈ Finset.Icc 3 m, (1 - 1 / ((p - 1) ^ 2 : ℝ))) = (m : ℝ) / (2 * (m - 1)) := by
            intro m hm
            induction' m, hm using Nat.le_induction with m ih;
            · norm_num;
            · erw [ Finset.prod_Ioc_succ_top ( by linarith ), ‹∏ p ∈ Finset.Icc 3 m, _ = _› ] ; push_cast ; ring;
              -- Combine and simplify the terms on the left-hand side.
              field_simp
              ring;
              nlinarith only [ inv_mul_cancel₀ ( by linarith [ ( by norm_cast : ( 3 : ℝ ) ≤ m ) ] : ( -1 + m : ℝ ) ≠ 0 ), ( by norm_cast : ( 3 : ℝ ) ≤ m ) ];
          by_cases hS_empty : S = ∅;
          · norm_num [ hS_empty ];
          · refine le_trans ?_ h_prod_bound;
            rw [ h_prod_formula _ ( Nat.succ_le_of_lt ( show 2 < S.sup id from lt_of_lt_of_le ( hS _ ( Classical.choose_spec ( Finset.nonempty_of_ne_empty hS_empty ) ) |>.2 ) ( Finset.le_sup ( f := id ) ( Classical.choose_spec ( Finset.nonempty_of_ne_empty hS_empty ) ) ) ) ) ];
            -- Since $m \geq 3$, we have $1/2 \leq m / (2(m-1))$.
            have h_ineq : ∀ m : ℕ, 3 ≤ m → 1 / 2 ≤ (m : ℝ) / (2 * (m - 1)) := by
              exact fun m hm => by rw [ div_le_div_iff₀ ] <;> linarith [ show ( m : ℝ ) ≥ 3 by norm_cast ] ;
            exact h_ineq _ ( Nat.succ_le_of_lt ( show 2 < S.sup id from lt_of_lt_of_le ( hS _ ( Classical.choose_spec ( Finset.nonempty_of_ne_empty hS_empty ) ) |>.2 ) ( Finset.le_sup ( f := id ) ( Classical.choose_spec ( Finset.nonempty_of_ne_empty hS_empty ) ) ) ) );
        exact h_prod_bound fun p hp => ⟨ Nat.prime_of_mem_primeFactors <| Finset.mem_sdiff.mp hp |>.1, Nat.lt_of_le_of_ne ( Nat.Prime.two_le <| Nat.prime_of_mem_primeFactors <| Finset.mem_sdiff.mp hp |>.1 ) <| Ne.symm <| by aesop ⟩;
      unfold hardyLittlewoodSingularSeries;
      rw [ if_pos ( Nat.even_iff.mp hn_even ) ] ; linarith

noncomputable def hardyLittlewoodMain (n : ℕ) : ℝ :=
  hardyLittlewoodSingularSeries n * (n : ℝ) / (Real.log n) ^ 2

noncomputable def hardyLittlewoodError (n : ℕ) : ℝ :=
  if n ≤ 100 then 0 else 100 * (n : ℝ) / (Real.log n) ^ 3

noncomputable def hardyLittlewoodError' (n : ℕ) : ℝ :=
  if n ≤ 1 then 100 else 100 * (n : ℝ) / (Real.log n) ^ 3

lemma hardyLittlewoodError_nonneg' : ∀ n, 0 ≤ hardyLittlewoodError' n := by
  intro n
  unfold hardyLittlewoodError'
  split
  · norm_num
  · apply div_nonneg (by positivity) (by positivity)

def HardyLittlewoodApproximationStmt : Prop :=
  ∀ n, n > 2 → Even n →
    |(goldbachReps n : ℝ) - hardyLittlewoodMain n| ≤ hardyLittlewoodError' n

noncomputable def hardyLittlewoodMainCorrected (n : ℕ) : ℝ :=
  if Even n then hardyLittlewoodMain n else 1

noncomputable def hardyLittlewoodErrorCorrected (n : ℕ) : ℝ :=
  if Even n then hardyLittlewoodError' n else 0

lemma hardyLittlewoodErrorCorrected_nonneg : ∀ n, 0 ≤ hardyLittlewoodErrorCorrected n := by
  intro n
  unfold hardyLittlewoodErrorCorrected
  split_ifs
  · exact hardyLittlewoodError_nonneg' n
  · norm_num
