/-
# Betrothed 5775 6128
Category: Frontier — Betrothed Numbers
Target: Brockian.BetrothedNumbers.betrothed_5775_6128
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

namespace Brockian.BetrothedNumbers

open Finset

/-- The sum-of-divisors function `σ₁ n = ∑_{d ∣ n} d`. -/
def sigmaOne (n : ℕ) : ℕ := ∑ d ∈ n.divisors, d

/-- Two distinct positive numbers `m` and `n` are a *betrothed* (quasi-amicable) pair when
each is the sum of the nontrivial proper divisors of the other, i.e.
`σ(m) = σ(n) = m + n + 1`. -/
def IsBetrothedPair (m n : ℕ) : Prop :=
  0 < m ∧ 0 < n ∧ m ≠ n ∧ sigmaOne m = m + n + 1 ∧ sigmaOne n = m + n + 1

/-- `σ` of a power of two. -/
lemma sigmaOne_two_pow (k : ℕ) : sigmaOne (2 ^ k) = 2 ^ (k + 1) - 1 := by
  rw [sigmaOne, Nat.sum_divisors_prime_pow Nat.prime_two]
  simp [Nat.geomSum_eq]

/-- `σ` of a prime. -/
lemma sigmaOne_prime {p : ℕ} (hp : p.Prime) : sigmaOne p = p + 1 := by
  have : sigmaOne (p ^ 1) = p + 1 := by
    rw [sigmaOne, Nat.sum_divisors_prime_pow hp]
    simp [Finset.sum_range_succ, add_comm]
  simpa using this

/-- The sigma value of `2 ^ k * p` for an odd prime `p`. -/
lemma sigmaOne_two_pow_mul_prime {k p : ℕ} (hp : p.Prime) (hp2 : p ≠ 2) :
    sigmaOne (2 ^ k * p) = (2 ^ (k + 1) - 1) * (p + 1) := by
  have hcop : Nat.Coprime (2 ^ k) p := by
    refine Nat.Coprime.pow_left _ ?_
    exact (Nat.coprime_primes Nat.prime_two hp).mpr (fun h => hp2 h.symm)
  rw [sigmaOne, hcop.sum_divisors_mul, ← sigmaOne, ← sigmaOne, sigmaOne_two_pow,
    sigmaOne_prime hp]

/-- The **sigma criterion** for generating a betrothed pair from parameters `k` and an odd
prime `p`: the second member is `n = 2 ^ k * p`, whose sigma value is forced to be
`(2 ^ (k+1) - 1) * (p + 1)`; if the number `m` determined by `m + n + 1 = σ(n)` is positive,
distinct from `n`, and has the same sigma value, then `(m, n)` is a betrothed pair. -/
def GeneratedBySigmaCriterion (k p m n : ℕ) : Prop :=
  p.Prime ∧ p ≠ 2 ∧ n = 2 ^ k * p ∧ 0 < m ∧ m ≠ n ∧
    m + n + 1 = (2 ^ (k + 1) - 1) * (p + 1) ∧ sigmaOne m = (2 ^ (k + 1) - 1) * (p + 1)

/-- Any pair produced by the sigma criterion is indeed a betrothed pair. -/
theorem isBetrothedPair_of_sigmaCriterion {k p m n : ℕ}
    (h : GeneratedBySigmaCriterion k p m n) : IsBetrothedPair m n := by
  obtain ⟨hp, hp2, hn, hm, hmn, hsum, hsig⟩ := h
  have hσn : sigmaOne n = (2 ^ (k + 1) - 1) * (p + 1) := by
    rw [hn]; exact sigmaOne_two_pow_mul_prime hp hp2
  refine ⟨hm, ?_, hmn, ?_, ?_⟩
  · subst hn
    exact Nat.mul_pos (Nat.two_pow_pos k) hp.pos
  · rw [hsig, hsum]
  · rw [hσn, hsum]

set_option maxRecDepth 100000

lemma sigmaOne_5775 : sigmaOne 5775 = 11904 := by
  unfold sigmaOne
  decide

lemma sigmaOne_6128 : sigmaOne 6128 = 11904 := by
  unfold sigmaOne
  decide

/-- `(5775, 6128)` is generated by the sigma criterion with `k = 4`, `p = 383`. -/
theorem generated_5775_6128 : GeneratedBySigmaCriterion 4 383 5775 6128 := by
  refine ⟨by norm_num, by norm_num, by norm_num, by norm_num, by norm_num, by norm_num, ?_⟩
  rw [sigmaOne_5775]
  norm_num

/-- **Main result.** `(5775, 6128)` is a betrothed (quasi-amicable) pair, obtained from the
sigma criterion with `k = 4`, `p = 383`. -/
theorem betrothed_5775_6128 : IsBetrothedPair 5775 6128 :=
  isBetrothedPair_of_sigmaCriterion generated_5775_6128

/-- The same fact, verified directly from the kernel computations of `σ 5775` and `σ 6128`. -/
theorem betrothed_5775_6128_direct : IsBetrothedPair 5775 6128 :=
  ⟨by norm_num, by norm_num, by norm_num, by rw [sigmaOne_5775], by rw [sigmaOne_6128]⟩

end Brockian.BetrothedNumbers

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

