/-
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
-- (The requested header is reproduced verbatim above as a plain block comment:
-- Lean 4 rejects a module doc comment `/-! ... -/` placed before the `import` line.)

import Mathlib

/-!
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)

## A model of Ed25519 (Schnorr-style) signature verification

Ed25519 works in the prime-order subgroup generated by a fixed base point `B` of a
twisted Edwards curve.  We model that subgroup abstractly: `G` is an additive
commutative group which is a module over `ZMod p` for a prime `p` (this is exactly
the situation for a group of prime exponent `p`, e.g. the order-`ℓ` subgroup of the
Ed25519 curve, where `ℓ = 2^252 + 27742317777372353535851937790883648493`).

* the secret key is a scalar `a : ZMod p`, the public key is `A = a • B`;
* a signature is a pair `(R, s)` with `R : G` and `s : ZMod p`;
* the challenge is `h = H R A m` for a hash function `H` (modelled as an arbitrary
  function — no property of `H` is needed for the statements below);
* verification checks `s • B = R + h • A`;
* honest signing with nonce `r` produces `R = r • B` and `s = r + h * a`.

The target theorem `PCA.Cert.ed25519_verify_sound` states that, for a signature whose
commitment `R` is a known multiple `r • B` of the base point, verification under the
public key `a • B` succeeds *exactly* for the honestly generated signature.  This gives
both soundness (a verifying signature must be the honest one, i.e. `s` is the correct
Schnorr response for the nonce `r` and the secret key `a`) and completeness (the honest
signature always verifies).

The key Mathlib ingredient is `smul_eq_zero` (available here because a module over the
field `ZMod p` has `NoZeroSMulDivisors`), which turns `c • B = 0` with `B ≠ 0` into
`c = 0`.
-/

namespace PCA.Cert

/-- A signature: a curve point `R` together with a scalar response `s`. -/
structure Signature (G : Type*) (p : ℕ) where
  /-- The commitment point. -/
  R : G
  /-- The scalar response. -/
  s : ZMod p

variable {G : Type*} {M : Type*} {p : ℕ}

section Defs

variable [AddCommGroup G] [Module (ZMod p) G]

/-- The public key associated to the secret scalar `a` and base point `B`. -/
def publicKey (B : G) (a : ZMod p) : G := a • B

/-- The verification equation `s • B = R + (H R A m) • A`. -/
def verify (B A : G) (H : G → G → M → ZMod p) (m : M) (sig : Signature G p) : Prop :=
  sig.s • B = sig.R + (H sig.R A m) • A

/-- Honest signing with secret key `a` and nonce `r`. -/
def sign (B : G) (H : G → G → M → ZMod p) (a r : ZMod p) (m : M) : Signature G p :=
  { R := r • B
    s := r + (H (r • B) (publicKey B a) m) * a }

end Defs

variable [Fact p.Prime] [AddCommGroup G] [Module (ZMod p) G]

/-- In a module over the field `ZMod p`, a nonzero base point `B` is cancellable:
`x • B = y • B` forces `x = y`. -/
theorem smul_left_cancel_of_ne_zero {B : G} (hB : B ≠ 0) {x y : ZMod p}
    (hxy : x • B = y • B) : x = y := by
  have h0 : (x - y) • B = 0 := by rw [sub_smul, hxy, sub_self]
  rcases smul_eq_zero.1 h0 with h1 | h1
  · exact sub_eq_zero.1 h1
  · exact absurd h1 hB

/-- **Ed25519 verification is sound (and complete).**

For a public key `A = a • B` with base point `B ≠ 0` in a prime-order group, and a
candidate signature `sig` whose commitment is `sig.R = r • B`, the verification
equation `sig.s • B = sig.R + (H sig.R A m) • A` holds **iff** `sig` is exactly the
honest signature produced by signing `m` with secret key `a` and nonce `r`, namely
`(r • B, r + H(R, A, m) * a)`.

Soundness (`→`): only the correctly computed Schnorr response passes verification.
Completeness (`←`): the honestly produced signature always passes verification. -/
theorem ed25519_verify_sound {B : G} (hB : B ≠ 0) (H : G → G → M → ZMod p) (m : M)
    (a r : ZMod p) (sig : Signature G p) (hR : sig.R = r • B) :
    verify B (publicKey B a) H m sig ↔ sig = sign B H a r m := by
  constructor
  · intro hv
    have hs : sig.s • B = (r + (H sig.R (publicKey B a) m) * a) • B := by
      rw [add_smul, mul_smul, ← hR]
      simpa [publicKey, verify] using hv
    have hs' : sig.s = r + (H sig.R (publicKey B a) m) * a :=
      smul_left_cancel_of_ne_zero hB hs
    cases sig with
    | mk R s =>
      simp only at hR hs'
      subst hR
      simp [sign, hs']
  · rintro rfl
    simp only [verify, sign, publicKey, add_smul, mul_smul]

/-- Completeness, stated separately: an honestly generated signature always verifies. -/
theorem ed25519_verify_honest {B : G} (H : G → G → M → ZMod p) (m : M) (a r : ZMod p) :
    verify B (publicKey B a) H m (sign B H a r m) := by
  simp only [verify, sign, publicKey, add_smul, mul_smul]

/-- Soundness in extraction form: if a signature with commitment `r • B` verifies under
the public key `a • B`, then its scalar is the Schnorr response `r + h * a`. -/
theorem ed25519_response_eq {B : G} (hB : B ≠ 0) (H : G → G → M → ZMod p) (m : M)
    (a r : ZMod p) (sig : Signature G p) (hR : sig.R = r • B)
    (hv : verify B (publicKey B a) H m sig) :
    sig.s = r + (H sig.R (publicKey B a) m) * a := by
  have hsig := (ed25519_verify_sound hB H m a r sig hR).1 hv
  rw [hsig]
  simp [sign]

end PCA.Cert

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

