import Mathlib

/-!
# Betrothed 5775 6128
Category: Frontier — Betrothed Numbers
Target: Brockian.BetrothedNumbers.betrothed_5775_6128
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/


namespace Brockian.BetrothedNumbers

open Finset

set_option maxRecDepth 100000

/-- The sum-of-divisors function `σ₁ n = ∑_{d ∣ n} d`. -/
def sigma1 (n : ℕ) : ℕ := ∑ d ∈ n.divisors, d

theorem sigma1_eq_arithmeticFunction_sigma (n : ℕ) :
    sigma1 n = ArithmeticFunction.sigma 1 n := by
  simp [sigma1, ArithmeticFunction.sigma_apply]

/-- `a` and `b` form a **betrothed** (quasi-amicable) pair: they are distinct positive
integers, each of which is the sum of the nontrivial proper divisors of the other,
equivalently `σ₁ a = σ₁ b = a + b + 1`. -/
def IsBetrothedPair (a b : ℕ) : Prop :=
  0 < a ∧ 0 < b ∧ a ≠ b ∧ sigma1 a = a + b + 1 ∧ sigma1 b = a + b + 1

instance (a b : ℕ) : Decidable (IsBetrothedPair a b) := by
  unfold IsBetrothedPair sigma1; infer_instance

/-- **The betrothed pair (5775, 6128)**, verified by kernel computation. -/
theorem betrothed_5775_6128 : IsBetrothedPair 5775 6128 := by decide

theorem sigma1_5775 : sigma1 5775 = 11904 := by decide

theorem sigma1_6128 : sigma1 6128 = 11904 := by decide

private theorem sum_range_two_pow (n : ℕ) : (∑ i ∈ Finset.range n, 2 ^ i) + 1 = 2 ^ n := by
  induction n with
  | zero => simp
  | succ n ih => rw [Finset.sum_range_succ]; omega

/-- The sigma value of `2 ^ k * p` for an odd prime `p`. -/
theorem sigma1_two_pow_mul_prime {k p : ℕ} (hp : p.Prime) (hp2 : p ≠ 2) :
    sigma1 (2 ^ k * p) + (p + 1) = 2 ^ (k + 1) * (p + 1) := by
  have hcop : Nat.Coprime (2 ^ k) p := by
    refine Nat.Coprime.pow_left _ ?_
    rw [Nat.coprime_primes Nat.prime_two hp]
    exact fun h => hp2 h.symm
  have h1 : sigma1 (2 ^ k * p) = (∑ i ∈ Finset.range (k + 1), 2 ^ i) * (p + 1) := by
    unfold sigma1
    have hpd : ∑ d ∈ p.divisors, d = p + 1 := by
      rw [hp.divisors, Finset.sum_pair hp.ne_one.symm]; omega
    rw [hcop.sum_divisors_mul, Nat.sum_divisors_prime_pow Nat.prime_two, hpd]
  rw [h1, ← sum_range_two_pow (k + 1)]
  ring

/-- **The sigma criterion.** If `p` is an odd prime and `a` is a positive integer, distinct
from `b = 2 ^ k * p`, such that both `σ₁ a` and `a + b + 1` equal
`σ₁ b = (2 ^ (k+1) - 1) * (p + 1)`, then `(a, 2 ^ k * p)` is a betrothed pair.
(The equalities are written in the subtraction-free form `x + (p + 1) = 2 ^ (k+1) * (p + 1)`.) -/
theorem isBetrothedPair_of_sigma_criterion {k p a : ℕ} (hp : p.Prime) (hp2 : p ≠ 2)
    (ha : 0 < a) (hne : a ≠ 2 ^ k * p)
    (hsum : a + 2 ^ k * p + 1 + (p + 1) = 2 ^ (k + 1) * (p + 1))
    (hsa : sigma1 a + (p + 1) = 2 ^ (k + 1) * (p + 1)) :
    IsBetrothedPair a (2 ^ k * p) := by
  have hb : 0 < 2 ^ k * p := Nat.mul_pos (by positivity) hp.pos
  have hsb := sigma1_two_pow_mul_prime (k := k) hp hp2
  exact ⟨ha, hb, hne, by omega, by omega⟩

/-- **(5775, 6128) is generated by the sigma criterion with `k = 4`, `p = 383`:**
`6128 = 2 ^ 4 * 383` with `383` prime, `σ₁ (2 ^ 4 * 383) = (2 ^ 5 - 1) * 384 = 11904`,
and the partner is `5775 = 11904 - 6128 - 1`. -/
theorem betrothed_5775_6128_via_criterion :
    Nat.Prime 383 ∧ (6128 : ℕ) = 2 ^ 4 * 383 ∧ IsBetrothedPair 5775 (2 ^ 4 * 383) := by
  refine ⟨by norm_num, by norm_num, ?_⟩
  refine isBetrothedPair_of_sigma_criterion (k := 4) (p := 383) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_
  rw [sigma1_5775]
  norm_num

end Brockian.BetrothedNumbers

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

