import Mathlib

/-!
# Goldstone
Category: Frontier Phys
Target: Phys.goldstone
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.letVarTypes true
set_option pp.funBinderTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Phys

open NormedSpace

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- **Infinitesimal (Noether) form of a continuous symmetry.**
If `V` is differentiable and invariant under a one-parameter family of transformations
`Φ t` with `Φ 0 = id` whose velocity field at `t = 0` is `A`, then the gradient of `V`
annihilates the symmetry direction `A x` at every field configuration `x`. -/
theorem fderiv_apply_generator_eq_zero {V : E → ℝ} {A : E → E} {Φ : ℝ → E → E}
    (hV : ∀ x : E, DifferentiableAt ℝ V x)
    (h0 : ∀ x : E, Φ 0 x = x)
    (hflow : ∀ x : E, HasDerivAt (fun t : ℝ => Φ t x) (A x) 0)
    (hinv : ∀ (t : ℝ) (x : E), V (Φ t x) = V x) (x : E) :
    fderiv ℝ V x (A x) = 0 := by
  have hcomp : HasDerivAt (fun t : ℝ => V (Φ t x)) (fderiv ℝ V x (A x)) 0 := by
    have h1 : HasFDerivAt V (fderiv ℝ V (Φ 0 x)) (Φ 0 x) := (hV (Φ 0 x)).hasFDerivAt
    have h2 := h1.comp_hasDerivAt (0 : ℝ) (hflow x)
    rw [h0 x] at h2
    exact h2
  have hconst : HasDerivAt (fun t : ℝ => V (Φ t x)) 0 0 := by
    simpa [hinv] using (hasDerivAt_const (0 : ℝ) (V x))
  exact hcomp.unique hconst

/-- **The Hessian of an invariant potential annihilates the symmetry direction at a
stationary point.**  This is the core algebraic content of Goldstone's theorem. -/
theorem hessian_apply_generator_eq_zero {A : E →L[ℝ] E} {x₀ : E}
    {D : E → (E →L[ℝ] ℝ)} {B : E →L[ℝ] (E →L[ℝ] ℝ)} (hB : HasFDerivAt D B x₀)
    (hinv : ∀ x : E, D x (A x) = 0) (hstat : D x₀ = 0) (w : E) :
    B w (A x₀) = 0 := by
  -- The function `g x = D x (A x)` is identically zero, so its derivative vanishes.
  have hbil : HasFDerivAt (fun x : E => D x (A x))
      ((D x₀).comp (A : E →L[ℝ] E) + B.flip (A x₀)) x₀ :=
    hB.clm_apply (A.hasFDerivAt (x := x₀))
  have hzero : HasFDerivAt (fun x : E => D x (A x)) (0 : E →L[ℝ] ℝ) x₀ := by
    simpa [hinv] using (hasFDerivAt_const (0 : ℝ) x₀)
  have hEq := hbil.unique hzero
  rw [hstat] at hEq
  have := congrArg (fun L : E →L[ℝ] ℝ => L w) hEq
  simpa using this


section Flow

variable [CompleteSpace E]

/-- The one-parameter group of symmetries generated by a bounded operator `A` moves the
field configuration `x` with velocity `A x` at `t = 0`. -/
theorem hasDerivAt_exp_smul_apply (A : E →L[ℝ] E) (x : E) (s : ℝ) :
    HasDerivAt (fun t : ℝ => exp (t • A) x) (exp (s • A) (A x)) s := by
  have h := (ContinuousLinearMap.apply ℝ E x).hasFDerivAt.comp_hasDerivAt s
    (hasDerivAt_exp_smul_const (𝕂 := ℝ) A s)
  simpa using h

/-- If the generator annihilates a configuration, that configuration is a fixed point of
the whole symmetry group: the symmetry is *unbroken* at `x₀`. -/
theorem exp_smul_apply_eq_self_of_generator_eq_zero {A : E →L[ℝ] E} {x₀ : E}
    (h : A x₀ = 0) (t : ℝ) : exp (t • A) x₀ = x₀ := by
  have key : ∀ s : ℝ, HasDerivAt (fun u : ℝ => exp (u • A) x₀) 0 s := by
    intro s
    simpa [h] using hasDerivAt_exp_smul_apply A x₀ s
  have hdiff : Differentiable ℝ (fun u : ℝ => exp (u • A) x₀) :=
    fun s => (key s).differentiableAt
  have h0 := is_const_of_deriv_eq_zero hdiff (fun s => (key s).deriv) t 0
  simpa using h0

/-- **Spontaneous symmetry breaking**: if the vacuum `x₀` is not invariant under the
symmetry group, then the generator does not annihilate it, i.e. `A x₀ ≠ 0` is a genuine
direction along the (broken) symmetry orbit. -/
theorem generator_ne_zero_of_not_invariant {A : E →L[ℝ] E} {x₀ : E}
    (hbroken : ∃ t : ℝ, exp (t • A) x₀ ≠ x₀) : A x₀ ≠ 0 := by
  obtain ⟨t, ht⟩ := hbroken
  intro h
  exact ht (exp_smul_apply_eq_self_of_generator_eq_zero h t)

/-- The vacuum is invariant under the whole symmetry group iff the generator annihilates
it: "spontaneously broken symmetry" is equivalent to `A x₀ ≠ 0`. -/
theorem not_invariant_iff_generator_ne_zero {A : E →L[ℝ] E} {x₀ : E} :
    (∃ t : ℝ, exp (t • A) x₀ ≠ x₀) ↔ A x₀ ≠ 0 := by
  refine ⟨generator_ne_zero_of_not_invariant, fun hne => ?_⟩
  by_contra hcon
  push_neg at hcon
  refine hne ?_
  have key : ∀ s : ℝ, HasDerivAt (fun u : ℝ => exp (u • A) x₀) (exp (s • A) (A x₀)) s :=
    hasDerivAt_exp_smul_apply A x₀
  have hzero : HasDerivAt (fun u : ℝ => exp (u • A) x₀) 0 0 := by
    simpa [hcon] using hasDerivAt_const (0 : ℝ) x₀
  have h := (key 0).unique hzero
  simpa using h

end Flow

/-- **Goldstone's theorem, infinitesimal form.**

If the gradient `D` of the potential annihilates the symmetry direction `A x` at every
configuration `x` (the Noether identity for a continuous symmetry), and `x₀` is a vacuum
(local minimum) at which the symmetry is broken (`A x₀ ≠ 0`), then the mass matrix `B`
(the Hessian of `V` at `x₀`) has the nonzero vector `A x₀` in its kernel: a massless
mode. -/
theorem goldstone_of_infinitesimal_invariance {V : E → ℝ} {A : E →L[ℝ] E} {x₀ : E}
    {D : E → (E →L[ℝ] ℝ)} {B : E →L[ℝ] (E →L[ℝ] ℝ)}
    (hD : ∀ x : E, HasFDerivAt V (D x) x) (hB : HasFDerivAt D B x₀)
    (hinv : ∀ x : E, D x (A x) = 0) (hvac : IsLocalMin V x₀) (hne : A x₀ ≠ 0) :
    ∃ v : E, v ≠ 0 ∧ (∀ w : E, B v w = 0) ∧ (∀ w : E, B w v = 0) := by
  -- The vacuum is a stationary point of the potential.
  have hstat : D x₀ = 0 := by
    have h := hvac.fderiv_eq_zero
    rwa [(hD x₀).fderiv] at h
  refine ⟨A x₀, hne, ?_, fun w => hessian_apply_generator_eq_zero hB hinv hstat w⟩
  intro w
  rw [second_derivative_symmetric (f := V) (f' := D) (f'' := B) hD hB (A x₀) w]
  exact hessian_apply_generator_eq_zero hB hinv hstat w

/-- **Goldstone's theorem (classical / effective-potential form).**

Let `V` be a twice-differentiable potential on a real Banach space of field
configurations (`D` is its gradient field and `B` its Hessian, i.e. mass matrix, at `x₀`),
invariant under the continuous one-parameter group of global symmetries
`x ↦ exp (t • A) x` generated by the bounded operator `A`.  Suppose `x₀` is a vacuum
(a local minimum of `V`) which is *not* invariant under the symmetry, i.e. the symmetry
is spontaneously broken.

Then the mass matrix has a nonzero vector in its kernel: the direction `A x₀` along the
broken symmetry orbit is a massless mode — the Goldstone boson. -/
theorem goldstone [CompleteSpace E] {V : E → ℝ} {A : E →L[ℝ] E} {x₀ : E}
    {D : E → (E →L[ℝ] ℝ)} {B : E →L[ℝ] (E →L[ℝ] ℝ)}
    (hD : ∀ x : E, HasFDerivAt V (D x) x) (hB : HasFDerivAt D B x₀)
    (hsym : ∀ (t : ℝ) (x : E), V (exp (t • A) x) = V x)
    (hvac : IsLocalMin V x₀)
    (hbroken : ∃ t : ℝ, exp (t • A) x₀ ≠ x₀) :
    ∃ v : E, v ≠ 0 ∧ (∀ w : E, B v w = 0) ∧ (∀ w : E, B w v = 0) := by
  -- Infinitesimal invariance: the gradient annihilates the symmetry direction everywhere.
  have hinv : ∀ x : E, D x (A x) = 0 := by
    intro x
    have hgen : fderiv ℝ V x (A x) = 0 :=
      fderiv_apply_generator_eq_zero (V := V) (A := fun y : E => A y)
        (Φ := fun t : ℝ => fun y : E => exp (t • A) y)
        (fun y => (hD y).differentiableAt)
        (fun y => by simp)
        (fun y => by simpa using hasDerivAt_exp_smul_apply A y 0)
        hsym x
    rwa [(hD x).fderiv] at hgen
  exact goldstone_of_infinitesimal_invariance hD hB hinv hvac
    (generator_ne_zero_of_not_invariant hbroken)

section MexicanHat

/-! ### A concrete model: the "Mexican hat" potential on `ℝ × ℝ`

`V (x, y) = (x² + y² - 1)²` is invariant under the rotation group generated by
`J (x, y) = (-y, x)`, its vacuum manifold is the unit circle, and at the vacuum `(1, 0)`
the mass matrix is nonzero, yet it annihilates the Goldstone direction `J (1,0) = (0,1)`.
This shows that the hypotheses of Goldstone's theorem above are not vacuous. -/

open ContinuousLinearMap

/-- The Mexican-hat potential `V (x, y) = (x² + y² - 1)²`. -/
noncomputable def mexHatPotential : ℝ × ℝ → ℝ := fun p => (p.1 ^ 2 + p.2 ^ 2 - 1) ^ 2

/-- The gradient (as a linear functional) of the Mexican-hat potential. -/
noncomputable def mexHatGrad : ℝ × ℝ → ((ℝ × ℝ) →L[ℝ] ℝ) := fun p =>
  (2 * (p.1 ^ 2 + p.2 ^ 2 - 1)) • ((2 * p.1) • (fst ℝ ℝ ℝ) + (2 * p.2) • (snd ℝ ℝ ℝ))

/-- The mass matrix (Hessian) of the Mexican-hat potential at the vacuum `(1, 0)`:
`B v w = 8 * v.1 * w.1`. -/
noncomputable def mexHatHessian : (ℝ × ℝ) →L[ℝ] ((ℝ × ℝ) →L[ℝ] ℝ) :=
  ((8 : ℝ) • (fst ℝ ℝ ℝ)).smulRight (fst ℝ ℝ ℝ)

/-- Auxiliary linear map `p ↦ 2 p.1 • fst + 2 p.2 • snd`. -/
noncomputable def mexHatGradAux : (ℝ × ℝ) →L[ℝ] ((ℝ × ℝ) →L[ℝ] ℝ) :=
  ((2 : ℝ) • (fst ℝ ℝ ℝ)).smulRight (fst ℝ ℝ ℝ) + ((2 : ℝ) • (snd ℝ ℝ ℝ)).smulRight (snd ℝ ℝ ℝ)

/-- The generator of the rotation symmetry: `J (x, y) = (-y, x)`. -/
noncomputable def mexHatGen : (ℝ × ℝ) →L[ℝ] (ℝ × ℝ) := (-(snd ℝ ℝ ℝ)).prod (fst ℝ ℝ ℝ)

theorem hasFDerivAt_mexHatPotential (p : ℝ × ℝ) :
    HasFDerivAt mexHatPotential (mexHatGrad p) p := by
  have h1 : HasFDerivAt (fun q : ℝ × ℝ => q.1) (fst ℝ ℝ ℝ) p := (fst ℝ ℝ ℝ).hasFDerivAt
  have h2 : HasFDerivAt (fun q : ℝ × ℝ => q.2) (snd ℝ ℝ ℝ) p := (snd ℝ ℝ ℝ).hasFDerivAt
  have hq : HasFDerivAt (fun q : ℝ × ℝ => q.1 ^ 2 + q.2 ^ 2 - 1)
      ((2 * p.1) • (fst ℝ ℝ ℝ) + (2 * p.2) • (snd ℝ ℝ ℝ)) p := by
    simpa using ((h1.pow 2).add (h2.pow 2)).sub_const 1
  simpa [mexHatPotential, mexHatGrad] using hq.pow 2

theorem hasFDerivAt_mexHatGrad :
    HasFDerivAt mexHatGrad mexHatHessian ((1 : ℝ), (0 : ℝ)) := by
  set x₀ : ℝ × ℝ := ((1 : ℝ), (0 : ℝ)) with hx₀
  have h1 : HasFDerivAt (fun q : ℝ × ℝ => q.1) (fst ℝ ℝ ℝ) x₀ := (fst ℝ ℝ ℝ).hasFDerivAt
  have h2 : HasFDerivAt (fun q : ℝ × ℝ => q.2) (snd ℝ ℝ ℝ) x₀ := (snd ℝ ℝ ℝ).hasFDerivAt
  have hc : HasFDerivAt (fun q : ℝ × ℝ => 2 * (q.1 ^ 2 + q.2 ^ 2 - 1))
      ((4 * x₀.1) • (fst ℝ ℝ ℝ) + (4 * x₀.2) • (snd ℝ ℝ ℝ)) x₀ := by
    have hq : HasFDerivAt (fun q : ℝ × ℝ => q.1 ^ 2 + q.2 ^ 2 - 1)
        ((2 * x₀.1) • (fst ℝ ℝ ℝ) + (2 * x₀.2) • (snd ℝ ℝ ℝ)) x₀ := by
      simpa using ((h1.pow 2).add (h2.pow 2)).sub_const 1
    refine (hq.const_mul (2 : ℝ)).congr_fderiv (ContinuousLinearMap.ext fun v => ?_)
    simp
    ring
  have hfun : (fun q : ℝ × ℝ => (2 * q.1) • (fst ℝ ℝ ℝ) + (2 * q.2) • (snd ℝ ℝ ℝ))
      = ⇑mexHatGradAux := by
    funext q
    exact ContinuousLinearMap.ext fun v => by simp [mexHatGradAux]
  have hL : HasFDerivAt (fun q : ℝ × ℝ => (2 * q.1) • (fst ℝ ℝ ℝ) + (2 * q.2) • (snd ℝ ℝ ℝ))
      mexHatGradAux x₀ := by
    rw [hfun]; exact mexHatGradAux.hasFDerivAt
  have key : HasFDerivAt mexHatGrad _ x₀ := hc.smul hL
  refine key.congr_fderiv
    (ContinuousLinearMap.ext fun v => ContinuousLinearMap.ext fun w => ?_)
  simp [mexHatHessian, hx₀, mexHatGradAux]
  ring

/-- The Mexican-hat potential is (infinitesimally) invariant under rotations. -/
theorem mexHat_infinitesimal_invariance (p : ℝ × ℝ) : mexHatGrad p (mexHatGen p) = 0 := by
  simp [mexHatGrad, mexHatGen]
  ring

/-- `(1, 0)` is a global (hence local) minimum of the Mexican-hat potential. -/
theorem mexHat_isLocalMin : IsLocalMin mexHatPotential ((1 : ℝ), (0 : ℝ)) :=
  Filter.Eventually.of_forall fun q => by
    have : (0 : ℝ) ≤ (q.1 ^ 2 + q.2 ^ 2 - 1) ^ 2 := sq_nonneg _
    simpa [mexHatPotential] using this

/-- The mass matrix at the vacuum is *not* identically zero (the radial mode is massive):
`B (1,0) (1,0) = 8`. -/
theorem mexHatHessian_radial : mexHatHessian ((1 : ℝ), (0 : ℝ)) ((1 : ℝ), (0 : ℝ)) = 8 := by
  simp [mexHatHessian]

/-- **Non-vacuity of Goldstone's theorem.**  For the Mexican-hat model, the hypotheses of
`Phys.goldstone_of_infinitesimal_invariance` hold, so the mass matrix at the vacuum
`(1,0)` annihilates the Goldstone direction `(0,1)`, even though the mass matrix itself is
nonzero (the radial mode is massive with `B (1,0) (1,0) = 8`). -/
theorem mexHat_goldstone :
    ∃ v : ℝ × ℝ, v ≠ 0 ∧ (∀ w : ℝ × ℝ, mexHatHessian v w = 0) ∧
      (∀ w : ℝ × ℝ, mexHatHessian w v = 0) := by
  refine goldstone_of_infinitesimal_invariance (V := mexHatPotential) (A := mexHatGen)
    (x₀ := ((1 : ℝ), (0 : ℝ))) hasFDerivAt_mexHatPotential hasFDerivAt_mexHatGrad
    mexHat_infinitesimal_invariance mexHat_isLocalMin ?_
  simp [mexHatGen, Prod.ext_iff]

/-- In the Mexican-hat model the Goldstone direction is the tangent `(0, 1)` to the vacuum
circle, and it is indeed a zero mode of the mass matrix. -/
theorem mexHat_goldstone_direction (w : ℝ × ℝ) :
    mexHatHessian ((0 : ℝ), (1 : ℝ)) w = 0 ∧ mexHatHessian w ((0 : ℝ), (1 : ℝ)) = 0 := by
  have h : mexHatGen ((1 : ℝ), (0 : ℝ)) = ((0 : ℝ), (1 : ℝ)) := by simp [mexHatGen]
  constructor
  · simp [mexHatHessian]
  · rw [← h]
    exact hessian_apply_generator_eq_zero hasFDerivAt_mexHatGrad
      mexHat_infinitesimal_invariance
      (by
        have hstat := mexHat_isLocalMin.fderiv_eq_zero
        rwa [(hasFDerivAt_mexHatPotential ((1 : ℝ), (0 : ℝ))).fderiv] at hstat) w

end MexicanHat

end Phys

