/-
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Unitary time evolution

For a self-adjoint (Hermitian) Hamiltonian `H` acting on a finite-dimensional complex
Hilbert space, the time-evolution operator

  `U t = exp (-(I * t / ℏ) • H)`

is unitary for every real time `t`.  The proof observes that `-(I * t / ℏ) • H` is a
skew-adjoint element of the (Banach) star algebra of matrices, and that the exponential
of a skew-adjoint element is unitary.

We also record the two defining identities `U(t)ᴴ * U(t) = 1`, `U(t) * U(t)ᴴ = 1`, together
with the one-parameter group law `U(s + t) = U(s) * U(t)` and `U 0 = 1`.
-/

namespace QPhys

open scoped Matrix

attribute [local instance] Matrix.linftyOpNormedRing Matrix.linftyOpNormedAlgebra

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- The time-evolution operator `U t = exp (-i H t / ℏ)` generated by a Hamiltonian `H`
(with reduced Planck constant `ℏ`). -/
noncomputable def timeEvolution (hbar : ℝ) (H : Matrix n n ℂ) (t : ℝ) : Matrix n n ℂ :=
  NormedSpace.exp ((-(Complex.I * ((t : ℂ) / hbar))) • H)

omit [Fintype n] [DecidableEq n] in
/-- If `H` is Hermitian then `-(i t / ℏ) • H` is skew-adjoint. -/
lemma smul_mem_skewAdjoint {H : Matrix n n ℂ} (hH : H.IsHermitian) (hbar t : ℝ) :
    (-(Complex.I * ((t : ℂ) / hbar))) • H ∈ skewAdjoint (Matrix n n ℂ) := by
  rw [skewAdjoint.mem_iff, star_smul, Matrix.star_eq_conjTranspose, hH.eq, ← neg_smul]
  congr 1
  simp

/-- **Unitary time evolution.**  For a self-adjoint Hamiltonian `H`, the operator
`U t = exp (-i H t / ℏ)` is unitary for every real time `t`. -/
theorem unitary_time_evolution (hbar : ℝ) {H : Matrix n n ℂ} (hH : H.IsHermitian) (t : ℝ) :
    timeEvolution hbar H t ∈ Matrix.unitaryGroup n ℂ :=
  NormedSpace.exp_mem_unitary_of_mem_skewAdjoint (smul_mem_skewAdjoint hH hbar t)

/-- Explicit form of unitarity: `U(t)ᴴ * U(t) = 1` and `U(t) * U(t)ᴴ = 1`. -/
theorem conjTranspose_mul_self_and_self_mul_conjTranspose (hbar : ℝ) {H : Matrix n n ℂ}
    (hH : H.IsHermitian) (t : ℝ) :
    (timeEvolution hbar H t)ᴴ * timeEvolution hbar H t = 1 ∧
      timeEvolution hbar H t * (timeEvolution hbar H t)ᴴ = 1 :=
  unitary_time_evolution hbar hH t

/-- The time-evolution operator at time `0` is the identity. -/
@[simp] theorem timeEvolution_zero (hbar : ℝ) (H : Matrix n n ℂ) :
    timeEvolution hbar H 0 = 1 := by
  simp [timeEvolution]

/-- The one-parameter group law `U(s + t) = U(s) * U(t)`. -/
theorem timeEvolution_add (hbar : ℝ) (H : Matrix n n ℂ) (s t : ℝ) :
    timeEvolution hbar H (s + t) = timeEvolution hbar H s * timeEvolution hbar H t := by
  have hs : (-(Complex.I * (((s + t : ℝ) : ℂ) / (hbar : ℂ))))
      = (-(Complex.I * ((s : ℂ) / hbar))) + (-(Complex.I * ((t : ℂ) / hbar))) := by
    push_cast; ring
  rw [timeEvolution, timeEvolution, timeEvolution, hs, add_smul,
    NormedSpace.exp_add_of_commute ((Commute.refl H).smul_left _ |>.smul_right _)]

end QPhys

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

