/-
# Lieb Robinson
Category: Frontier Physics
Target: Frontier.lieb_robinson
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-- The support of a nearest-neighbour bond gate sitting on the bond `i` of the
spin chain `ℤ`: the two sites `i` and `i + 1`. -/
def edge (i : ℤ) : Set ℤ := {i, i + 1}

/-- A net of local observable algebras over the one dimensional spin chain `ℤ`.

`loc S` is the set of observables supported in the region `S`.  The axioms are the
defining features of a quantum spin system: locality is monotone in the region,
each local set is closed under products and contains the identity, and observables
supported in disjoint regions commute. -/
structure LocalNet (A : Type*) [Ring A] where
  /-- The observables supported in a region. -/
  loc : Set ℤ → Set A
  one_mem : ∀ S : Set ℤ, (1 : A) ∈ loc S
  mul_mem : ∀ {S : Set ℤ} {x y : A}, x ∈ loc S → y ∈ loc S → x * y ∈ loc S
  mono : ∀ {S T : Set ℤ}, S ⊆ T → loc S ⊆ loc T
  commute_of_disjoint :
    ∀ {S T : Set ℤ} {x y : A}, Disjoint S T → x ∈ loc S → y ∈ loc T → x * y = y * x

variable {A : Type*} [Ring A]

/-- A nearest-neighbour gate: an invertible observable `u` (with inverse `v`)
supported on a single bond of the chain.  Conjugation by such a gate is an
elementary step of a local discrete-time dynamics. -/
structure Gate (N : LocalNet A) where
  /-- The bond on which the gate acts. -/
  bond : ℤ
  /-- The gate. -/
  u : A
  /-- Its inverse. -/
  v : A
  u_mem : u ∈ N.loc (edge bond)
  v_mem : v ∈ N.loc (edge bond)
  uv : u * v = 1
  vu : v * u = 1

variable {N : LocalNet A}

/-- Conjugation of an observable by a list of gates. -/
def conjList : List (Gate N) → A → A
  | [], x => x
  | g :: gs, x => g.u * conjList gs x * g.v

/-- One time step of the dynamics is conjugation by a *layer* of gates, i.e. a
list of gates with pairwise disjoint supports. -/
def IsLayer (gs : List (Gate N)) : Prop :=
  gs.Pairwise fun g h => Disjoint (edge g.bond) (edge h.bond)

/-- The discrete-time dynamics generated by a list of layers: the observable is
conjugated by each layer in turn. -/
def evolve : List (List (Gate N)) → A → A
  | [], x => x
  | l :: ls, x => evolve ls (conjList l x)

/-- The region reached from `S` by a list of gates: `S` together with the supports
of those gates whose support already meets `S`. -/
def reach (gs : List (Gate N)) (S : Set ℤ) : Set ℤ :=
  S ∪ {p | ∃ g ∈ gs, ¬ Disjoint (edge g.bond) S ∧ p ∈ edge g.bond}

/-- The light cone of radius `r` around a region `S`. -/
def cone (r : ℕ) (S : Set ℤ) : Set ℤ := {p | ∃ s ∈ S, |p - s| ≤ (r : ℤ)}

lemma subset_reach (gs : List (Gate N)) (S : Set ℤ) : S ⊆ reach gs S :=
  Set.subset_union_left

lemma reach_mono_cons (g : Gate N) (gs : List (Gate N)) (S : Set ℤ) :
    reach gs S ⊆ reach (g :: gs) S := by
  rintro p (hp | ⟨h, hh, hd, hp⟩)
  · exact Or.inl hp
  · exact Or.inr ⟨h, List.mem_cons_of_mem _ hh, hd, hp⟩

lemma edge_subset_reach_cons {g : Gate N} {gs : List (Gate N)} {S : Set ℤ}
    (hd : ¬ Disjoint (edge g.bond) S) : edge g.bond ⊆ reach (g :: gs) S := by
  intro p hp
  exact Or.inr ⟨g, List.mem_cons_self, hd, hp⟩

/-- Conjugating an observable supported in `S` by a layer of gates keeps it
supported in the region reached from `S`. -/
theorem conjList_mem {gs : List (Gate N)} (hp : IsLayer gs) {S : Set ℤ} {x : A}
    (hx : x ∈ N.loc S) : conjList gs x ∈ N.loc (reach gs S) := by
  induction gs with
  | nil =>
      refine N.mono ?_ hx
      exact subset_reach _ _
  | cons g gs ih =>
      obtain ⟨hg, hp'⟩ := List.pairwise_cons.mp hp
      have hz : conjList gs x ∈ N.loc (reach gs S) := ih hp'
      by_cases hd : Disjoint (edge g.bond) (reach gs S)
      · have h1 : g.u * conjList gs x = conjList gs x * g.u :=
          N.commute_of_disjoint hd g.u_mem hz
        have h2 : conjList (g :: gs) x = conjList gs x := by
          show g.u * conjList gs x * g.v = conjList gs x
          rw [h1, mul_assoc, g.uv, mul_one]
        rw [h2]
        exact N.mono (reach_mono_cons g gs S) hz
      · -- the gate's support must already meet `S`
        have hmeet : ¬ Disjoint (edge g.bond) S := by
          intro hSd
          apply hd
          rw [Set.disjoint_left]
          rintro p hpg (hpS | ⟨h, hh, _, hph⟩)
          · exact (Set.disjoint_left.mp hSd hpg) hpS
          · exact (Set.disjoint_left.mp (hg h hh) hpg) hph
        have hu : g.u ∈ N.loc (reach (g :: gs) S) :=
          N.mono (edge_subset_reach_cons hmeet) g.u_mem
        have hv : g.v ∈ N.loc (reach (g :: gs) S) :=
          N.mono (edge_subset_reach_cons hmeet) g.v_mem
        have hz' : conjList gs x ∈ N.loc (reach (g :: gs) S) :=
          N.mono (reach_mono_cons g gs S) hz
        exact N.mul_mem (N.mul_mem hu hz') hv

lemma reach_subset_cone_succ (gs : List (Gate N)) (S : Set ℤ) (r : ℕ) :
    reach gs (cone r S) ⊆ cone (r + 1) S := by
  rintro p (hp | ⟨g, _, hd, hp⟩)
  · obtain ⟨s, hs, hps⟩ := hp
    exact ⟨s, hs, by push_cast; omega⟩
  · -- the gate touches the cone, so its two sites are within distance one of it
    obtain ⟨q, hqg, hq⟩ := Set.not_disjoint_iff.mp hd
    obtain ⟨s, hs, hqs⟩ := hq
    refine ⟨s, hs, ?_⟩
    have h1 : p = g.bond ∨ p = g.bond + 1 := hp
    have h2 : q = g.bond ∨ q = g.bond + 1 := hqg
    have : |q - s| ≤ (r : ℤ) := hqs
    push_cast
    rcases h1 with h1 | h1 <;> rcases h2 with h2 | h2 <;>
      subst h1 <;> subst h2 <;> rw [abs_le] at * <;> omega

lemma cone_mono_radius {r r' : ℕ} (h : r ≤ r') (S : Set ℤ) : cone r S ⊆ cone r' S := by
  rintro p ⟨s, hs, hps⟩
  exact ⟨s, hs, le_trans hps (by exact_mod_cast h)⟩

lemma subset_cone (r : ℕ) (S : Set ℤ) : S ⊆ cone r S := by
  intro s hs
  exact ⟨s, hs, by simp⟩

/-- **Light cone for the discrete-time dynamics.**  After `L.length` layers, an
observable supported in `S` is supported in the light cone of radius `L.length`
around `S`: information propagates at speed at most one site per time step. -/
theorem evolve_mem_cone (L : List (List (Gate N))) (hL : ∀ l ∈ L, IsLayer l)
    {S : Set ℤ} {x : A} (hx : x ∈ N.loc S) :
    evolve L x ∈ N.loc (cone L.length S) := by
  induction L generalizing S x with
  | nil => exact N.mono (subset_cone 0 S) hx
  | cons l ls ih =>
      have hl : IsLayer l := hL l List.mem_cons_self
      have h1 : conjList l x ∈ N.loc (reach l S) := conjList_mem hl hx
      have h2 : evolve ls (conjList l x) ∈ N.loc (cone ls.length (reach l S)) :=
        ih (fun m hm => hL m (List.mem_cons_of_mem _ hm)) h1
      refine N.mono ?_ h2
      -- `reach l S ⊆ cone 1 S`, and cones compose
      have hr : reach l S ⊆ cone 1 S := by
        have := reach_subset_cone_succ (N := N) l S 0
        intro p hp
        exact this (by
          rcases hp with hp | ⟨g, hg, hd, hpg⟩
          · exact Or.inl (subset_cone 0 S hp)
          · refine Or.inr ⟨g, hg, ?_, hpg⟩
            intro hcon
            exact hd (hcon.mono_right (subset_cone 0 S)))
      intro p hp
      obtain ⟨q, hq, hpq⟩ := hp
      obtain ⟨s, hs, hqs⟩ := hr hq
      refine ⟨s, hs, ?_⟩
      simp only [List.length_cons]
      push_cast
      rw [abs_le] at *
      omega

/-- **Lieb–Robinson bound (finite propagation speed / light cone form).**

For a quantum spin chain with a discrete-time dynamics given by `L.length` layers
of nearest-neighbour gates, an observable `x` supported in a region `S` evolves
into an observable supported within distance `L.length` of `S`.  Consequently, if
every site of `S` is at distance strictly greater than `L.length` from every site
of a region `T`, then the evolved observable commutes exactly with every
observable `y` supported in `T`: outside the light cone the commutator vanishes. -/
theorem lieb_robinson (N : LocalNet A) (L : List (List (Gate N)))
    (hL : ∀ l ∈ L, IsLayer l) {S T : Set ℤ} {x y : A}
    (hx : x ∈ N.loc S) (hy : y ∈ N.loc T)
    (hdist : ∀ s ∈ S, ∀ t ∈ T, (L.length : ℤ) < |s - t|) :
    ⁅evolve L x, y⁆ = 0 := by
  have hmem : evolve L x ∈ N.loc (cone L.length S) := evolve_mem_cone L hL hx
  have hdisj : Disjoint (cone L.length S) T := by
    rw [Set.disjoint_left]
    rintro p ⟨s, hs, hps⟩ hpT
    have := hdist s hs p hpT
    rw [abs_le] at hps
    rw [lt_abs] at this
    omega
  have := N.commute_of_disjoint hdisj hmem hy
  rw [Ring.lie_def, this, sub_self]

/-! ### A concrete, genuinely noncommutative model

To see that the hypotheses above are not vacuous we exhibit a two-site spin system:
the algebra of `4 × 4` matrices viewed as `2 × 2` matrices on site `0` tensored with
`2 × 2` matrices on site `1`, with `loc S` the elementary tensors that act as the
identity on the sites outside `S`. -/

open scoped Kronecker

/-- Two-by-two real matrices: the observables of a single spin. -/
abbrev SpinMat := Matrix (Fin 2) (Fin 2) ℝ

/-- The observables of a pair of spins. -/
abbrev SpinPairMat := Matrix (Fin 2 × Fin 2) (Fin 2 × Fin 2) ℝ

/-- Elementary tensors acting as the identity outside the region `S ∩ {0, 1}`. -/
def locPair (S : Set ℤ) : Set SpinPairMat :=
  {M | ∃ a b : SpinMat, M = a ⊗ₖ b ∧ (0 ∉ S → a = 1) ∧ (1 ∉ S → b = 1)}

/-- The two-site spin system is a local net in the sense of `Frontier.LocalNet`. -/
def twoSiteNet : LocalNet SpinPairMat where
  loc := locPair
  one_mem := fun _ => ⟨1, 1, by simp, fun _ => rfl, fun _ => rfl⟩
  mul_mem := by
    rintro S x y ⟨a, b, rfl, ha, hb⟩ ⟨c, d, rfl, hc, hd⟩
    exact ⟨a * c, b * d, (Matrix.mul_kronecker_mul a c b d).symm,
      fun h => by rw [ha h, hc h, mul_one], fun h => by rw [hb h, hd h, mul_one]⟩
  mono := by
    rintro S T hST x ⟨a, b, rfl, ha, hb⟩
    exact ⟨a, b, rfl, fun h => ha fun h' => h (hST h'), fun h => hb fun h' => h (hST h')⟩
  commute_of_disjoint := by
    rintro S T x y h ⟨a, b, rfl, ha, hb⟩ ⟨c, d, rfl, hc, hd⟩
    have h0 : a * c = c * a := by
      by_cases h0 : (0 : ℤ) ∈ S
      · rw [hc fun hT => (Set.disjoint_left.mp h h0) hT]; simp
      · rw [ha h0]; simp
    have h1 : b * d = d * b := by
      by_cases h1 : (1 : ℤ) ∈ S
      · rw [hd fun hT => (Set.disjoint_left.mp h h1) hT]; simp
      · rw [hb h1]; simp
    rw [← Matrix.mul_kronecker_mul a c b d, ← Matrix.mul_kronecker_mul c a d b, h0, h1]

/-- The two-site net really is noncommutative: observables on the *same* site need
not commute, so the vanishing of commutators in `Frontier.lieb_robinson` is not
automatic. -/
theorem twoSiteNet_not_commutative :
    ∃ x y : SpinPairMat, x ∈ twoSiteNet.loc {0} ∧ y ∈ twoSiteNet.loc {0} ∧ x * y ≠ y * x := by
  refine ⟨(!![0, 1; 0, 0] : SpinMat) ⊗ₖ 1, (!![0, 0; 1, 0] : SpinMat) ⊗ₖ 1,
    ⟨_, _, rfl, fun h => absurd rfl h, fun _ => rfl⟩,
    ⟨_, _, rfl, fun h => absurd rfl h, fun _ => rfl⟩, ?_⟩
  rw [← Matrix.mul_kronecker_mul, ← Matrix.mul_kronecker_mul]
  intro h
  have := congrFun (congrFun h (0, 0)) (0, 0)
  simp [Matrix.kroneckerMap, Matrix.mul_apply, Fin.sum_univ_succ] at this

end Frontier

