/-
/-!
# Noether Conservation
Category: Frontier Physics
Target: Frontier.noether_conservation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
-/
-- (The header above is wrapped in a plain block comment because Lean 4 requires
-- `import` commands to precede any module docstring `/-! ... -/`.)

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-!
## Setting

We work with a one–dimensional mechanical system with Lagrangian `L : ℝ → ℝ → ℝ`,
written `L x v` (position `x`, velocity `v`).  Its partial derivatives are given by
functions `L₁` (w.r.t. position) and `L₂` (w.r.t. velocity).

A *path* is `q : ℝ → ℝ` with velocity `v : ℝ → ℝ`, i.e. `q' = v`.
The path is a *stationary point of the action* iff it satisfies the Euler–Lagrange
equation
  `d/dt (L₂ (q t) (v t)) = L₁ (q t) (v t)`.

An infinitesimal (smooth) symmetry is a vector field `X : ℝ → ℝ` on configuration
space, with derivative `X'`.  It acts on curves by `q ↦ q + s • X ∘ q`, hence on the
velocity by `v ↦ v + s • (X' ∘ q) * v`.  Invariance of the action to first order in
`s` is exactly the pointwise identity

  `L₁ x v * X x + L₂ x v * (X' x * v) = 0`.

Noether's theorem: the *current* `J t = L₂ (q t) (v t) * X (q t)` is conserved.
-/

/-- The Noether current attached to a Lagrangian `L` (with velocity–partial `L₂`),
a path `q` with velocity `v`, and an infinitesimal symmetry `X`:
`J t = L₂ (q t) (v t) * X (q t)`, i.e. momentum times the symmetry generator. -/
noncomputable def noetherCurrent (L₂ : ℝ → ℝ → ℝ) (q v X : ℝ → ℝ) (t : ℝ) : ℝ :=
  L₂ (q t) (v t) * X (q t)

/-- **Noether's theorem (1D case).**

If

* `q` is a path with velocity `v` (`hq`),
* `X` is a smooth vector field on configuration space with derivative `X'` (`hX`),
* the path satisfies the Euler–Lagrange equation for `L`, i.e. the momentum
  `t ↦ L₂ (q t) (v t)` has derivative `L₁ (q t) (v t)` (`hEL`),
* the Lagrangian is infinitesimally invariant under the symmetry generated by `X`
  (`hinv`),

then the Noether current `t ↦ L₂ (q t) (v t) * X (q t)` has vanishing derivative at
every time, and is therefore constant: it is a conserved quantity. -/
theorem noether_conservation
    (L₁ L₂ : ℝ → ℝ → ℝ) (q v X X' : ℝ → ℝ)
    (hq : ∀ t : ℝ, HasDerivAt q (v t) t)
    (hX : ∀ x : ℝ, HasDerivAt X (X' x) x)
    (hEL : ∀ t : ℝ, HasDerivAt (fun s : ℝ => L₂ (q s) (v s)) (L₁ (q t) (v t)) t)
    (hinv : ∀ x u : ℝ, L₁ x u * X x + L₂ x u * (X' x * u) = 0) :
    (∀ t : ℝ, HasDerivAt (noetherCurrent L₂ q v X) 0 t) ∧
      ∀ t₀ t₁ : ℝ, noetherCurrent L₂ q v X t₁ = noetherCurrent L₂ q v X t₀ := by
  have hderiv : ∀ t : ℝ, HasDerivAt (noetherCurrent L₂ q v X) 0 t := by
    intro t
    have hXq : HasDerivAt (fun s : ℝ => X (q s)) (X' (q t) * v t) t :=
      HasDerivAt.comp t (hX (q t)) (hq t)
    have h := (hEL t).mul hXq
    have hzero : L₁ (q t) (v t) * X (q t) + L₂ (q t) (v t) * (X' (q t) * v t) = 0 :=
      hinv (q t) (v t)
    have h' :
        HasDerivAt (fun s : ℝ => L₂ (q s) (v s) * X (q s))
          (L₁ (q t) (v t) * X (q t) + L₂ (q t) (v t) * (X' (q t) * v t)) t := by
      simpa [add_comm, add_left_comm, add_assoc, mul_comm, mul_left_comm, mul_assoc]
        using h
    simpa [noetherCurrent, hzero] using h'
  refine ⟨hderiv, ?_⟩
  intro t₀ t₁
  have : ∀ t : ℝ, deriv (noetherCurrent L₂ q v X) t = 0 := fun t => (hderiv t).deriv
  have hdiff : Differentiable ℝ (noetherCurrent L₂ q v X) := fun t => (hderiv t).differentiableAt
  exact is_const_of_deriv_eq_zero hdiff this t₁ t₀

/-- A genuine (finite) one–parameter symmetry of the Lagrangian yields the
infinitesimal invariance identity used in `noether_conservation`.

Here `hL` says that `L`, viewed as a function of the pair `(position, velocity)`,
is differentiable with partial derivatives `L₁` and `L₂`, and `hsym` says that for
every parameter `s` the transformation `x ↦ x + s * X x`, `u ↦ u + s * (X' x * u)`
(the lift of the flow of `X` to velocities, to first order) leaves `L` unchanged. -/
theorem infinitesimal_invariance_of_symmetry
    (L L₁ L₂ : ℝ → ℝ → ℝ) (X X' : ℝ → ℝ)
    (hL : ∀ x u : ℝ, HasFDerivAt (fun p : ℝ × ℝ => L p.1 p.2)
      (L₁ x u • (ContinuousLinearMap.fst ℝ ℝ ℝ) + L₂ x u • (ContinuousLinearMap.snd ℝ ℝ ℝ)) (x, u))
    (hsym : ∀ s x u : ℝ, L (x + s * X x) (u + s * (X' x * u)) = L x u) :
    ∀ x u : ℝ, L₁ x u * X x + L₂ x u * (X' x * u) = 0 := by
  intro x u
  have hg : HasDerivAt (fun s : ℝ => ((x + s * X x, u + s * (X' x * u)) : ℝ × ℝ))
      (X x, X' x * u) 0 := by
    have h1 : HasDerivAt (fun s : ℝ => x + s * X x) (X x) 0 := by
      simpa using ((hasDerivAt_id (0 : ℝ)).mul_const (X x)).const_add x
    have h2 : HasDerivAt (fun s : ℝ => u + s * (X' x * u)) (X' x * u) 0 := by
      simpa using ((hasDerivAt_id (0 : ℝ)).mul_const (X' x * u)).const_add u
    exact h1.prodMk h2
  have hL0 : HasFDerivAt (fun p : ℝ × ℝ => L p.1 p.2)
      (L₁ x u • (ContinuousLinearMap.fst ℝ ℝ ℝ) + L₂ x u • (ContinuousLinearMap.snd ℝ ℝ ℝ))
      ((fun s : ℝ => ((x + s * X x, u + s * (X' x * u)) : ℝ × ℝ)) 0) := by
    simpa using hL x u
  have hcomp := hL0.comp_hasDerivAt 0 hg
  have hconst : HasDerivAt (fun s : ℝ => L (x + s * X x) (u + s * (X' x * u))) 0 0 := by
    simpa [hsym] using (hasDerivAt_const (0 : ℝ) (L x u))
  have huniq := hcomp.unique hconst
  simpa [eq_comm] using huniq.symm

/-- **Noether's theorem from a finite symmetry (1D case).**

Same conclusion as `noether_conservation`, but with the infinitesimal invariance
hypothesis replaced by invariance of the Lagrangian under the one–parameter family
of transformations generated by the vector field `X`. -/
theorem noether_conservation_of_symmetry
    (L L₁ L₂ : ℝ → ℝ → ℝ) (q v X X' : ℝ → ℝ)
    (hq : ∀ t : ℝ, HasDerivAt q (v t) t)
    (hX : ∀ x : ℝ, HasDerivAt X (X' x) x)
    (hEL : ∀ t : ℝ, HasDerivAt (fun s : ℝ => L₂ (q s) (v s)) (L₁ (q t) (v t)) t)
    (hL : ∀ x u : ℝ, HasFDerivAt (fun p : ℝ × ℝ => L p.1 p.2)
      (L₁ x u • (ContinuousLinearMap.fst ℝ ℝ ℝ) + L₂ x u • (ContinuousLinearMap.snd ℝ ℝ ℝ)) (x, u))
    (hsym : ∀ s x u : ℝ, L (x + s * X x) (u + s * (X' x * u)) = L x u) :
    (∀ t : ℝ, HasDerivAt (noetherCurrent L₂ q v X) 0 t) ∧
      ∀ t₀ t₁ : ℝ, noetherCurrent L₂ q v X t₁ = noetherCurrent L₂ q v X t₀ :=
  noether_conservation L₁ L₂ q v X X' hq hX hEL
    (infinitesimal_invariance_of_symmetry L L₁ L₂ X X' hL hsym)

/-!
## A concrete instance: the free particle

Lagrangian `L x u = u ^ 2 / 2`, translation symmetry `x ↦ x + s` (generator `X = 1`).
The Noether current is the momentum `u`, and along the straight-line solutions
`q t = a + b * t` it is conserved (and equal to `b`).  This checks that the
hypotheses of `noether_conservation_of_symmetry` are satisfiable. -/
theorem free_particle_momentum_conserved (a b : ℝ) :
    (∀ t₀ t₁ : ℝ,
        noetherCurrent (fun _ u : ℝ => u) (fun t : ℝ => a + b * t) (fun _ : ℝ => b)
            (fun _ : ℝ => 1) t₁ =
          noetherCurrent (fun _ u : ℝ => u) (fun t : ℝ => a + b * t) (fun _ : ℝ => b)
            (fun _ : ℝ => 1) t₀) ∧
      ∀ t : ℝ,
        noetherCurrent (fun _ u : ℝ => u) (fun t : ℝ => a + b * t) (fun _ : ℝ => b)
          (fun _ : ℝ => 1) t = b := by
  refine ⟨?_, by intro t; simp [noetherCurrent]⟩
  refine (noether_conservation_of_symmetry (fun _ u : ℝ => u ^ 2 / 2) (fun _ _ : ℝ => 0)
    (fun _ u : ℝ => u) (fun t : ℝ => a + b * t) (fun _ : ℝ => b) (fun _ : ℝ => 1)
    (fun _ : ℝ => 0) ?_ ?_ ?_ ?_ ?_).2
  · intro t
    simpa using ((hasDerivAt_id t).const_mul b).const_add a
  · intro x
    simpa using hasDerivAt_const x (1 : ℝ)
  · intro t
    simpa using hasDerivAt_const t b
  · intro x u
    have h : HasFDerivAt (fun p : ℝ × ℝ => p.2) (ContinuousLinearMap.snd ℝ ℝ ℝ) (x, u) :=
      (ContinuousLinearMap.snd ℝ ℝ ℝ).hasFDerivAt
    have hp : HasFDerivAt (fun p : ℝ × ℝ => p.2 ^ 2)
        ((2 * u) • (ContinuousLinearMap.snd ℝ ℝ ℝ)) (x, u) := by
      simpa [nsmul_eq_mul] using h.pow 2
    have h2 : HasFDerivAt (fun p : ℝ × ℝ => p.2 ^ 2 / 2)
        (u • (ContinuousLinearMap.snd ℝ ℝ ℝ)) (x, u) := by
      simpa [smul_smul, Pi.smul_def, smul_eq_mul, div_eq_inv_mul, mul_comm, mul_assoc,
        mul_left_comm] using hp.const_smul ((2 : ℝ)⁻¹)
    have hclm :
        ((0 : ℝ) • (ContinuousLinearMap.fst ℝ ℝ ℝ) + u • (ContinuousLinearMap.snd ℝ ℝ ℝ)) =
          u • (ContinuousLinearMap.snd ℝ ℝ ℝ) := by
      ext <;> simp
    simpa [hclm] using h2
  · intro s x u
    simp

end Frontier

