import Mathlib
/-!
# Lieb Robinson
Category: Frontier Physics
Target: Frontier.lieb_robinson
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

section Basic

variable {A : Type*} [NormedRing A] [NormedAlgebra ℝ A]

/-- The inner derivation (adjoint action) `ad H x = H * x - x * H`. -/
def ad (H : A) (x : A) : A := H * x - x * H

/-- Heisenberg time evolution generated by `H`, defined as the exponential of the
derivation `ad H`:  `tau H t a = exp (t • ad H) a = ∑' n, (tⁿ / n !) • (ad H)^[n] a`.
(For a spin system with Hamiltonian `Ĥ` one takes `H = i Ĥ`, so that `tau H t a`
is the usual Heisenberg evolved observable `e^{i t Ĥ} a e^{-i t Ĥ}`.) -/
noncomputable def tau (H : A) (t : ℝ) (a : A) : A :=
  ∑' n : ℕ, (t ^ n / (n ! : ℝ)) • (ad H)^[n] a

omit [NormedAlgebra ℝ A] in
lemma norm_ad_le (H x : A) : ‖ad H x‖ ≤ 2 * ‖H‖ * ‖x‖ := by
  have h1 : ‖H * x‖ ≤ ‖H‖ * ‖x‖ := norm_mul_le _ _
  have h2 : ‖x * H‖ ≤ ‖x‖ * ‖H‖ := norm_mul_le _ _
  calc ‖ad H x‖ ≤ ‖H * x‖ + ‖x * H‖ := norm_sub_le _ _
    _ ≤ ‖H‖ * ‖x‖ + ‖x‖ * ‖H‖ := add_le_add h1 h2
    _ = 2 * ‖H‖ * ‖x‖ := by ring

omit [NormedAlgebra ℝ A] in
/-- Each application of the derivation `ad H` costs at most a factor `2‖H‖`. -/
lemma norm_adPow_le (H : A) (n : ℕ) (a : A) :
    ‖(ad H)^[n] a‖ ≤ (2 * ‖H‖) ^ n * ‖a‖ := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply']
      calc ‖ad H ((ad H)^[n] a)‖ ≤ 2 * ‖H‖ * ‖(ad H)^[n] a‖ := norm_ad_le _ _
        _ ≤ 2 * ‖H‖ * ((2 * ‖H‖) ^ n * ‖a‖) :=
            mul_le_mul_of_nonneg_left ih (by positivity)
        _ = (2 * ‖H‖) ^ (n + 1) * ‖a‖ := by ring

/-- Norm bound on the `n`-th term of the commutator expansion. -/
lemma norm_term_le (H : A) (t : ℝ) (a b : A) (n : ℕ) :
    ‖(t ^ n / (n ! : ℝ)) • ((ad H)^[n] a * b - b * (ad H)^[n] a)‖
      ≤ 2 * ‖a‖ * ‖b‖ * ((2 * ‖H‖ * |t|) ^ n / (n ! : ℝ)) := by
  have hK : ‖(ad H)^[n] a * b - b * (ad H)^[n] a‖ ≤ 2 * ((2 * ‖H‖) ^ n * ‖a‖) * ‖b‖ := by
    calc ‖(ad H)^[n] a * b - b * (ad H)^[n] a‖
        ≤ ‖(ad H)^[n] a * b‖ + ‖b * (ad H)^[n] a‖ := norm_sub_le _ _
      _ ≤ ‖(ad H)^[n] a‖ * ‖b‖ + ‖b‖ * ‖(ad H)^[n] a‖ :=
          add_le_add (norm_mul_le _ _) (norm_mul_le _ _)
      _ = 2 * ‖(ad H)^[n] a‖ * ‖b‖ := by ring
      _ ≤ 2 * ((2 * ‖H‖) ^ n * ‖a‖) * ‖b‖ := by
          have := norm_adPow_le H n a
          nlinarith [norm_nonneg b, norm_nonneg ((ad H)^[n] a)]
  rw [norm_smul]
  have h1 : ‖(t ^ n / (n ! : ℝ))‖ = |t| ^ n / (n ! : ℝ) := by
    rw [Real.norm_eq_abs, abs_div, abs_pow, abs_of_nonneg (by positivity : (0:ℝ) ≤ (n ! : ℝ))]
  rw [h1]
  calc |t| ^ n / (n ! : ℝ) * ‖(ad H)^[n] a * b - b * (ad H)^[n] a‖
      ≤ |t| ^ n / (n ! : ℝ) * (2 * ((2 * ‖H‖) ^ n * ‖a‖) * ‖b‖) :=
        mul_le_mul_of_nonneg_left hK (by positivity)
    _ = 2 * ‖a‖ * ‖b‖ * ((2 * ‖H‖ * |t|) ^ n / (n ! : ℝ)) := by rw [mul_pow]; ring

/-- The defining series of `tau` is absolutely convergent. -/
lemma summable_tau_series [CompleteSpace A] (H : A) (t : ℝ) (a : A) :
    Summable (fun n : ℕ => (t ^ n / (n ! : ℝ)) • (ad H)^[n] a) := by
  apply Summable.of_norm
  have hs : Summable (fun n : ℕ => ((2 * ‖H‖ * |t|) ^ n / (n ! : ℝ)) * ‖a‖) :=
    (Real.summable_pow_div_factorial _).mul_right _
  refine hs.of_nonneg_of_le (fun n => norm_nonneg _) (fun n => ?_)
  rw [norm_smul]
  have h1 : ‖(t ^ n / (n ! : ℝ))‖ = |t| ^ n / (n ! : ℝ) := by
    rw [Real.norm_eq_abs, abs_div, abs_pow, abs_of_nonneg (by positivity : (0:ℝ) ≤ (n ! : ℝ))]
  rw [h1]
  calc |t| ^ n / (n ! : ℝ) * ‖(ad H)^[n] a‖
      ≤ |t| ^ n / (n ! : ℝ) * ((2 * ‖H‖) ^ n * ‖a‖) :=
        mul_le_mul_of_nonneg_left (norm_adPow_le H n a) (by positivity)
    _ = ((2 * ‖H‖ * |t|) ^ n / (n ! : ℝ)) * ‖a‖ := by rw [mul_pow]; ring

/-- The commutator of the evolved observable with `b`, expanded term by term. -/
lemma tau_commutator_eq [CompleteSpace A] (H : A) (t : ℝ) (a b : A) :
    tau H t a * b - b * tau H t a
      = ∑' n : ℕ, (t ^ n / (n ! : ℝ)) • ((ad H)^[n] a * b - b * (ad H)^[n] a) := by
  have hsum := summable_tau_series H t a
  rw [tau, ← hsum.tsum_mul_right b, ← hsum.tsum_mul_left b,
    ← (hsum.mul_right b).tsum_sub (hsum.mul_left b)]
  refine tsum_congr (fun n => ?_)
  rw [smul_mul_assoc, mul_smul_comm, ← smul_sub]

end Basic

/-- Tail bound for the exponential series: `∑_{n ≥ d} xⁿ/n ! ≤ (x^d/d !) e^x`. -/
lemma tsum_exp_tail_le {x : ℝ} (hx : 0 ≤ x) (d : ℕ) :
    ∑' k : ℕ, x ^ (k + d) / ((k + d)! : ℝ) ≤ (x ^ d / (d ! : ℝ)) * Real.exp x := by
  have hbase : Summable (fun n : ℕ => x ^ n / (n ! : ℝ)) := Real.summable_pow_div_factorial x
  have hL : Summable (fun k : ℕ => x ^ (k + d) / ((k + d)! : ℝ)) :=
    (summable_nat_add_iff d).2 hbase
  have hR : Summable (fun k : ℕ => (x ^ d / (d ! : ℝ)) * (x ^ k / (k ! : ℝ))) :=
    hbase.mul_left _
  have hterm : ∀ k : ℕ,
      x ^ (k + d) / ((k + d)! : ℝ) ≤ (x ^ d / (d ! : ℝ)) * (x ^ k / (k ! : ℝ)) := by
    intro k
    have hfac : (k ! : ℝ) * (d ! : ℝ) ≤ ((k + d)! : ℝ) := by
      have h2 : k ! * d ! ≤ (k + d)! :=
        Nat.le_of_dvd (Nat.factorial_pos _) (Nat.factorial_mul_factorial_dvd_factorial_add k d)
      exact_mod_cast h2
    have hpos : (0:ℝ) < (k ! : ℝ) * (d ! : ℝ) := by positivity
    have hle : x ^ (k + d) / ((k + d)! : ℝ) ≤ x ^ (k + d) / ((k ! : ℝ) * (d ! : ℝ)) :=
      div_le_div_of_nonneg_left (by positivity) hpos hfac
    refine hle.trans_eq ?_
    rw [pow_add]
    field_simp
  calc ∑' k : ℕ, x ^ (k + d) / ((k + d)! : ℝ)
      ≤ ∑' k : ℕ, (x ^ d / (d ! : ℝ)) * (x ^ k / (k ! : ℝ)) := hL.tsum_le_tsum hterm hR
    _ = (x ^ d / (d ! : ℝ)) * Real.exp x := by
        rw [hbase.tsum_mul_left, Real.exp_eq_exp_ℝ, NormedSpace.exp_eq_tsum_div]

section Locality

variable {A : Type*} [NormedRing A] [NormedAlgebra ℝ A]

variable (loc : ℤ → ℤ → A → Prop)

omit [NormedAlgebra ℝ A] in
/-- One step of support growth: the derivation `ad H` generated by a nearest–neighbour
Hamiltonian enlarges the support of a local observable by one site on each side. -/
lemma ad_loc
    (loc_mono : ∀ {p q p' q' : ℤ} {x : A}, p' ≤ p → q ≤ q' → loc p q x → loc p' q' x)
    (loc_comm : ∀ {p q p' q' : ℤ} {x y : A}, q < p' → loc p q x → loc p' q' y → x * y = y * x)
    (loc_zero : ∀ p q : ℤ, loc p q 0)
    (loc_add : ∀ {p q : ℤ} {x y : A}, loc p q x → loc p q y → loc p q (x + y))
    (loc_neg : ∀ {p q : ℤ} {x : A}, loc p q x → loc p q (-x))
    (loc_mul : ∀ {p q : ℤ} {x y : A}, loc p q x → loc p q y → loc p q (x * y))
    (Λ : Finset ℤ) (hh : ℤ → A) (H : A) (hH : H = ∑ z ∈ Λ, hh z)
    (hhloc : ∀ z ∈ Λ, loc z (z + 1) (hh z))
    {p q : ℤ} {x : A} (hx : loc p q x) :
    loc (p - 1) (q + 1) (ad H x) := by
  have hsplit : ad H x = ∑ z ∈ Λ, ad (hh z) x := by
    simp only [ad, hH, Finset.sum_mul, Finset.mul_sum, ← Finset.sum_sub_distrib]
  rw [hsplit]
  refine Finset.sum_induction _ (loc (p - 1) (q + 1)) (fun u v hu hv => loc_add hu hv)
    (loc_zero _ _) (fun z hz => ?_)
  rcases lt_or_ge (z + 1) p with hlt | hge
  · have hc : hh z * x = x * hh z := loc_comm hlt (hhloc z hz) hx
    simp [ad, hc, loc_zero]
  · rcases lt_or_ge q z with hgt | hle
    · have hc : x * hh z = hh z * x := loc_comm hgt hx (hhloc z hz)
      simp [ad, hc, loc_zero]
    · have h1 : loc (p - 1) (q + 1) (hh z) := loc_mono (by omega) (by omega) (hhloc z hz)
      have h2 : loc (p - 1) (q + 1) x := loc_mono (by omega) (by omega) hx
      have he : ad (hh z) x = hh z * x + -(x * hh z) := by rw [ad, sub_eq_add_neg]
      rw [he]
      exact loc_add (loc_mul h1 h2) (loc_neg (loc_mul h2 h1))

omit [NormedAlgebra ℝ A] in
/-- Support growth after `n` steps of the derivation: the support of `(ad H)^[n] x`
is contained in the `n`-neighbourhood of the support of `x`. -/
lemma adPow_loc
    (loc_mono : ∀ {p q p' q' : ℤ} {x : A}, p' ≤ p → q ≤ q' → loc p q x → loc p' q' x)
    (loc_comm : ∀ {p q p' q' : ℤ} {x y : A}, q < p' → loc p q x → loc p' q' y → x * y = y * x)
    (loc_zero : ∀ p q : ℤ, loc p q 0)
    (loc_add : ∀ {p q : ℤ} {x y : A}, loc p q x → loc p q y → loc p q (x + y))
    (loc_neg : ∀ {p q : ℤ} {x : A}, loc p q x → loc p q (-x))
    (loc_mul : ∀ {p q : ℤ} {x y : A}, loc p q x → loc p q y → loc p q (x * y))
    (Λ : Finset ℤ) (hh : ℤ → A) (H : A) (hH : H = ∑ z ∈ Λ, hh z)
    (hhloc : ∀ z ∈ Λ, loc z (z + 1) (hh z))
    {p q : ℤ} {x : A} (hx : loc p q x) (n : ℕ) :
    loc (p - n) (q + n) ((ad H)^[n] x) := by
  induction n with
  | zero => simpa using hx
  | succ n ih =>
      rw [Function.iterate_succ_apply']
      have hstep := ad_loc loc loc_mono loc_comm loc_zero loc_add loc_neg loc_mul Λ hh H hH
        hhloc ih
      have e1 : p - ((n : ℤ) + 1) = (p - n) - 1 := by ring
      have e2 : q + ((n : ℤ) + 1) = (q + n) + 1 := by ring
      simpa [e1, e2] using hstep

end Locality

/-- **Lieb–Robinson bound** (base case: nearest–neighbour interactions on a chain,
with the light-cone velocity governed by the total interaction strength `‖H‖`).

`loc p q x` means "the observable `x` is supported in the interval of sites `[p, q]`";
the hypotheses on `loc` are the standard quasi-locality axioms of a spin chain:
supports may be enlarged, observables with disjoint supports commute, and the
observables supported in a fixed interval form a subalgebra.

`H = ∑ z ∈ Λ, hh z` is a nearest–neighbour Hamiltonian, `hh z` being supported on the
bond `[z, z + 1]`, and `tau H t a` is the Heisenberg evolution of `a` generated by `H`.

If `a` is supported in `[pa, qa]`, `b` is supported in `[pb, qb]` and the two supports
are separated by a distance at least `d`, then the commutator of the evolved observable
with `b` obeys

`‖[tau H t a, b]‖ ≤ 2 ‖a‖ ‖b‖ (2‖H‖|t|)^d / d ! * exp (2‖H‖|t|)`,

which is super-exponentially small in `d` once `d ≫ e · 2‖H‖|t|`: an effective light cone
with velocity proportional to `‖H‖`. -/
theorem lieb_robinson
    {A : Type*} [NormedRing A] [NormedAlgebra ℝ A] [CompleteSpace A]
    (loc : ℤ → ℤ → A → Prop)
    (loc_mono : ∀ {p q p' q' : ℤ} {x : A}, p' ≤ p → q ≤ q' → loc p q x → loc p' q' x)
    (loc_comm : ∀ {p q p' q' : ℤ} {x y : A}, q < p' → loc p q x → loc p' q' y → x * y = y * x)
    (loc_zero : ∀ p q : ℤ, loc p q 0)
    (loc_add : ∀ {p q : ℤ} {x y : A}, loc p q x → loc p q y → loc p q (x + y))
    (loc_neg : ∀ {p q : ℤ} {x : A}, loc p q x → loc p q (-x))
    (loc_mul : ∀ {p q : ℤ} {x y : A}, loc p q x → loc p q y → loc p q (x * y))
    (Λ : Finset ℤ) (hh : ℤ → A) (H : A) (hH : H = ∑ z ∈ Λ, hh z)
    (hhloc : ∀ z ∈ Λ, loc z (z + 1) (hh z))
    (a b : A) (pa qa pb qb : ℤ) (d : ℕ)
    (ha : loc pa qa a) (hb : loc pb qb b) (hd : qa + d ≤ pb) (t : ℝ) :
    ‖tau H t a * b - b * tau H t a‖
      ≤ 2 * ‖a‖ * ‖b‖ * ((2 * ‖H‖ * |t|) ^ d / (d ! : ℝ)) * Real.exp (2 * ‖H‖ * |t|) := by
  rw [tau_commutator_eq H t a b]
  set x : ℝ := 2 * ‖H‖ * |t| with hxdef
  set C : ℝ := 2 * ‖a‖ * ‖b‖ with hCdef
  have hx0 : (0:ℝ) ≤ x := by rw [hxdef]; positivity
  have hC0 : (0:ℝ) ≤ C := by rw [hCdef]; positivity
  set g : ℕ → A := fun n => (t ^ n / (n ! : ℝ)) • ((ad H)^[n] a * b - b * (ad H)^[n] a)
    with hgdef
  set M : ℕ → ℝ := fun n => if n < d then 0 else C * (x ^ n / (n ! : ℝ)) with hMdef
  have hgle : ∀ n : ℕ, ‖g n‖ ≤ C * (x ^ n / (n ! : ℝ)) := fun n => norm_term_le H t a b n
  have hgzero : ∀ n : ℕ, n < d → g n = 0 := by
    intro n hn
    have hloc := adPow_loc loc loc_mono loc_comm loc_zero loc_add loc_neg loc_mul Λ hh H hH
      hhloc ha n
    have hlt : qa + (n : ℤ) < pb := by
      have hnd : (n : ℤ) < (d : ℤ) := by exact_mod_cast hn
      omega
    have hcomm := loc_comm hlt hloc hb
    simp [hgdef, hcomm]
  have hMle : ∀ n : ℕ, ‖g n‖ ≤ M n := by
    intro n
    by_cases hn : n < d
    · simp [hMdef, hn, hgzero n hn]
    · simpa [hMdef, hn] using hgle n
  have hMsummable : Summable M := by
    refine Summable.of_nonneg_of_le (fun n => ?_) (fun n => ?_)
      ((Real.summable_pow_div_factorial x).mul_left C)
    · by_cases hn : n < d
      · simp [hMdef, hn]
      · simp only [hMdef, hn, if_false]
        positivity
    · by_cases hn : n < d
      · simp only [hMdef, hn, if_true]
        positivity
      · simp [hMdef, hn]
  have hgsummable : Summable (fun n : ℕ => ‖g n‖) :=
    Summable.of_nonneg_of_le (fun n => norm_nonneg _) hMle hMsummable
  have hMsum : ∑' n : ℕ, M n ≤ C * ((x ^ d / (d ! : ℝ)) * Real.exp x) := by
    have hsplit := hMsummable.sum_add_tsum_nat_add d
    have hz : ∑ i ∈ Finset.range d, M i = 0 := by
      refine Finset.sum_eq_zero (fun i hi => ?_)
      simp [hMdef, Finset.mem_range.mp hi]
    have hshift : (fun k : ℕ => M (k + d)) = fun k : ℕ => C * (x ^ (k + d) / (((k + d)!) : ℝ)) := by
      funext k
      simp [hMdef]
    rw [← hsplit, hz, zero_add, hshift, tsum_mul_left]
    exact mul_le_mul_of_nonneg_left (tsum_exp_tail_le hx0 d) hC0
  calc ‖∑' n : ℕ, g n‖
      ≤ ∑' n : ℕ, ‖g n‖ := norm_tsum_le_tsum_norm hgsummable
    _ ≤ ∑' n : ℕ, M n := hgsummable.tsum_le_tsum hMle hMsummable
    _ ≤ C * ((x ^ d / (d ! : ℝ)) * Real.exp x) := hMsum
    _ = C * (x ^ d / (d ! : ℝ)) * Real.exp x := by ring

end Frontier

