/-
# Noether Conservation
Category: Frontier Physics
Target: Frontier.noether_conservation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Noether Conservation
Category: Frontier Physics
Target: Frontier.noether_conservation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-- The partial derivative `∂L/∂q` of a one–dimensional Lagrangian
`L : ℝ × ℝ → ℝ` (first slot: position, second slot: velocity). -/
noncomputable def Lpos (L : ℝ × ℝ → ℝ) (x v : ℝ) : ℝ := fderiv ℝ L (x, v) (1, 0)

/-- The partial derivative `∂L/∂q̇` of a one–dimensional Lagrangian
`L : ℝ × ℝ → ℝ`, i.e. the canonical momentum. -/
noncomputable def Lvel (L : ℝ × ℝ → ℝ) (x v : ℝ) : ℝ := fderiv ℝ L (x, v) (0, 1)

/-- The Noether current associated with the infinitesimal symmetry generated by the
vector field `X` along the trajectory `q` with velocity `q'`:
`J(t) = (∂L/∂q̇)(q t, q' t) · X (q t)`. -/
noncomputable def noetherCurrent (L : ℝ × ℝ → ℝ) (X q q' : ℝ → ℝ) (t : ℝ) : ℝ :=
  Lvel L (q t) (q' t) * X (q t)

/-- Directional derivatives of `L` decompose into the two partial derivatives. -/
lemma fderiv_apply_eq (L : ℝ × ℝ → ℝ) (x v a b : ℝ) :
    fderiv ℝ L (x, v) (a, b) = a * Lpos L x v + b * Lvel L x v := by
  have h : ((a, b) : ℝ × ℝ) = a • ((1, 0) : ℝ × ℝ) + b • ((0, 1) : ℝ × ℝ) := by
    simp
  rw [h, map_add, map_smul, map_smul]
  simp [Lpos, Lvel, smul_eq_mul]

/-- **Infinitesimal invariance implies the Noether identity.**
If `L` is invariant to first order under the flow `q ↦ q + s X(q)` (with the induced
action `v ↦ v + s X'(q) v` on velocities), then the pointwise Noether identity
`(∂L/∂q) X + (∂L/∂q̇) X' v = 0` holds. -/
lemma noether_identity (L : ℝ × ℝ → ℝ) (hL : Differentiable ℝ L) (X X' : ℝ → ℝ)
    (hsym : ∀ x v : ℝ, HasDerivAt (fun s : ℝ => L (x + s * X x, v + s * (X' x * v))) 0 0)
    (x v : ℝ) :
    Lpos L x v * X x + Lvel L x v * (X' x * v) = 0 := by
  have hg : HasDerivAt (fun s : ℝ => (x + s * X x, v + s * (X' x * v)))
      ((X x, X' x * v) : ℝ × ℝ) 0 := by
    have h1 : HasDerivAt (fun s : ℝ => x + s * X x) (X x) 0 := by
      simpa using ((hasDerivAt_id (0 : ℝ)).mul_const (X x)).const_add x
    have h2 : HasDerivAt (fun s : ℝ => v + s * (X' x * v)) (X' x * v) 0 := by
      simpa using ((hasDerivAt_id (0 : ℝ)).mul_const (X' x * v)).const_add v
    exact h1.prodMk h2
  have hcomp : HasDerivAt (fun s : ℝ => L (x + s * X x, v + s * (X' x * v)))
      (fderiv ℝ L (x, v) (X x, X' x * v)) 0 := by
    have hLfd : HasFDerivAt L (fderiv ℝ L (x, v))
        (x + (0 : ℝ) * X x, v + (0 : ℝ) * (X' x * v)) := by
      simpa using (hL (x, v)).hasFDerivAt
    exact hLfd.comp_hasDerivAt (0 : ℝ) hg
  have h0 : fderiv ℝ L (x, v) (X x, X' x * v) = 0 :=
    (hcomp.unique (hsym x v))
  rw [fderiv_apply_eq L] at h0
  linarith [h0]

/-- **Noether's theorem, one–dimensional case.**
Let `L : ℝ × ℝ → ℝ` be a differentiable Lagrangian, and let `X` be a smooth vector field
on configuration space generating a one–parameter family of transformations
`q ↦ q + s X(q)` under which `L` is invariant to first order (`hsym`).
If `q` is a trajectory with velocity `q'` satisfying the Euler–Lagrange equation
`d/dt (∂L/∂q̇)(q, q') = (∂L/∂q)(q, q')`, then the Noether current
`J(t) = (∂L/∂q̇)(q t, q' t) · X (q t)` is conserved. -/
theorem noether_conservation
    (L : ℝ × ℝ → ℝ) (hL : Differentiable ℝ L)
    (X X' : ℝ → ℝ) (hX : ∀ x, HasDerivAt X (X' x) x)
    (hsym : ∀ x v : ℝ, HasDerivAt (fun s : ℝ => L (x + s * X x, v + s * (X' x * v))) 0 0)
    (q q' : ℝ → ℝ) (hq : ∀ t, HasDerivAt q (q' t) t)
    (hEL : ∀ t, HasDerivAt (fun s : ℝ => Lvel L (q s) (q' s)) (Lpos L (q t) (q' t)) t) :
    ∀ t₁ t₂ : ℝ, noetherCurrent L X q q' t₁ = noetherCurrent L X q q' t₂ := by
  have hJ : ∀ t : ℝ, HasDerivAt (noetherCurrent L X q q') 0 t := by
    intro t
    have hXq : HasDerivAt (fun s : ℝ => X (q s)) (X' (q t) * q' t) t :=
      (hX (q t)).comp t (hq t)
    have h := (hEL t).mul hXq
    have hz : Lpos L (q t) (q' t) * X (q t)
        + Lvel L (q t) (q' t) * (X' (q t) * q' t) = 0 :=
      noether_identity L hL X X' hsym (q t) (q' t)
    simpa [noetherCurrent, hz] using h
  intro t₁ t₂
  exact is_const_of_deriv_eq_zero (fun t => (hJ t).differentiableAt)
    (fun t => (hJ t).deriv) t₁ t₂

/-! ### A concrete instance: the free particle and conservation of momentum -/

/-- The free-particle Lagrangian `L (q, q̇) = q̇ ^ 2 / 2`. -/
noncomputable def freeL : ℝ × ℝ → ℝ := fun p => p.2 ^ 2 / 2

lemma freeL_differentiable : Differentiable ℝ freeL := by
  unfold freeL; fun_prop

lemma freeL_hasFDerivAt (x v : ℝ) :
    HasFDerivAt freeL (v • (ContinuousLinearMap.snd ℝ ℝ ℝ)) (x, v) := by
  have h1 : HasDerivAt (fun w : ℝ => w ^ 2 / 2) v v := by
    simpa using ((hasDerivAt_pow 2 v).div_const 2)
  have hs : HasFDerivAt (fun p : ℝ × ℝ => p.2) (ContinuousLinearMap.snd ℝ ℝ ℝ) (x, v) :=
    hasFDerivAt_snd
  have h := h1.comp_hasFDerivAt (x, v) hs
  simp only [Function.comp_def] at h
  exact h

@[simp] lemma freeL_Lvel (x v : ℝ) : Lvel freeL x v = v := by
  unfold Lvel; rw [(freeL_hasFDerivAt x v).fderiv]; simp

@[simp] lemma freeL_Lpos (x v : ℝ) : Lpos freeL x v = 0 := by
  unfold Lpos; rw [(freeL_hasFDerivAt x v).fderiv]; simp

/-- The hypotheses of `Frontier.noether_conservation` are satisfiable: for a free particle
with the translation symmetry `q ↦ q + s`, the Noether current is the momentum, and it is
constant along the uniform motion `q t = t`. -/
theorem noether_conservation_free_particle :
    (Differentiable ℝ freeL) ∧
    (∀ x, HasDerivAt (fun _ : ℝ => (1 : ℝ)) ((fun _ : ℝ => (0 : ℝ)) x) x) ∧
    (∀ x v : ℝ, HasDerivAt
      (fun s : ℝ => freeL (x + s * (fun _ : ℝ => (1 : ℝ)) x,
        v + s * ((fun _ : ℝ => (0 : ℝ)) x * v))) 0 0) ∧
    (∀ t : ℝ, HasDerivAt (fun t : ℝ => t) ((fun _ : ℝ => (1 : ℝ)) t) t) ∧
    (∀ t : ℝ, HasDerivAt
      (fun s : ℝ => Lvel freeL ((fun t : ℝ => t) s) ((fun _ : ℝ => (1 : ℝ)) s))
      (Lpos freeL ((fun t : ℝ => t) t) ((fun _ : ℝ => (1 : ℝ)) t)) t) ∧
    (∀ t : ℝ, noetherCurrent freeL (fun _ : ℝ => (1 : ℝ)) (fun t : ℝ => t)
      (fun _ : ℝ => (1 : ℝ)) t = 1) := by
  refine ⟨freeL_differentiable, fun x => hasDerivAt_const _ _, ?_, fun t => hasDerivAt_id t,
    ?_, ?_⟩
  · intro x v
    simpa [freeL] using (hasDerivAt_const (0 : ℝ) (v ^ 2 / 2))
  · intro t
    simp only [freeL_Lvel, freeL_Lpos]
    exact hasDerivAt_const t (1 : ℝ)
  · intro t
    simp [noetherCurrent]


end Frontier

