import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-! ### An abelian Higgs toy model

We model a `U(1)` gauge theory coupled to a complex scalar `φ` with charge `q`.
Everything is reduced to its algebraic content:

* the scalar potential only depends on the modulus `r = ‖φ‖` and is the standard
  "mexican hat" `V(r) = lam * (r ^ 2 - v ^ 2) ^ 2`;
* the gauge field enters through the covariant derivative `D φ = dφ - i q A φ`;
* a constant scalar background of modulus `r` therefore contributes a term
  `q ^ 2 * r ^ 2 * A ^ 2` to `‖D φ‖ ^ 2`, i.e. a mass term for `A` with
  mass squared `q ^ 2 * r ^ 2`.

Spontaneous symmetry breaking is the statement that the potential is minimised at
`r = v ≠ 0` rather than at the symmetric point `r = 0`, and hence that the gauge
boson acquires a strictly positive mass `|q| * v`. -/

/-- The Higgs ("mexican hat") potential, as a function of the modulus `r = ‖φ‖`. -/
noncomputable def higgsPotential (lam v r : ℝ) : ℝ := lam * (r ^ 2 - v ^ 2) ^ 2

/-- The covariant derivative `D φ = dφ - i q A φ` of a charge-`q` scalar in the
background of a gauge potential `A` (here `dφ` is the ordinary derivative). -/
noncomputable def covDeriv (q A : ℝ) (dphi phi : ℂ) : ℂ :=
  dphi - Complex.I * (q * A) * phi

/-- The gauge boson mass squared generated by a scalar condensate of modulus `r`. -/
noncomputable def gaugeMassSq (q r : ℝ) : ℝ := q ^ 2 * r ^ 2

/-- For a constant scalar background of modulus `r`, the covariant kinetic term
`‖D φ‖ ^ 2` is exactly the mass term `gaugeMassSq q r * A ^ 2` for the gauge field. -/
theorem normSq_covDeriv_const (q A r : ℝ) :
    Complex.normSq (covDeriv q A 0 (r : ℂ)) = gaugeMassSq q r * A ^ 2 := by
  simp [covDeriv, gaugeMassSq, Complex.normSq_apply]
  ring

/-- **Spontaneous symmetry breaking gives the gauge boson a mass.**

For a mexican-hat potential with coupling `lam > 0` and vacuum expectation value
`v > 0`, and a scalar of nonzero charge `q`:

* the potential is minimised at `r = v` (indeed the set of minimisers is
  `{r | r ^ 2 = v ^ 2}`, the vacuum manifold);
* the symmetric point `r = 0` is *not* a minimum;
* at the symmetric point the gauge field is massless, while in the broken vacuum
  its mass squared `q ^ 2 v ^ 2` is strictly positive, i.e. the gauge boson has
  mass `|q| * v`. -/
theorem higgs_mass_toy (lam v q : ℝ) (hlam : 0 < lam) (hv : 0 < v) (hq : q ≠ 0) :
    (∀ r : ℝ, higgsPotential lam v v ≤ higgsPotential lam v r) ∧
    {r : ℝ | ∀ s : ℝ, higgsPotential lam v r ≤ higgsPotential lam v s} =
      {r : ℝ | r ^ 2 = v ^ 2} ∧
    higgsPotential lam v v < higgsPotential lam v 0 ∧
    gaugeMassSq q 0 = 0 ∧
    0 < gaugeMassSq q v ∧
    Real.sqrt (gaugeMassSq q v) = |q| * v := by
  have hmin : higgsPotential lam v v = 0 := by simp [higgsPotential]
  have hnonneg : ∀ r : ℝ, 0 ≤ higgsPotential lam v r := by
    intro r; simp only [higgsPotential]; positivity
  refine ⟨fun r => by rw [hmin]; exact hnonneg r, ?_, ?_, ?_, ?_, ?_⟩
  · ext r
    simp only [Set.mem_setOf_eq]
    constructor
    · intro h
      have h0 : higgsPotential lam v r ≤ 0 := by
        simpa [hmin] using h v
      have : higgsPotential lam v r = 0 := le_antisymm h0 (hnonneg r)
      have := mul_eq_zero.1 this
      rcases this with h1 | h1
      · exact absurd h1 (ne_of_gt hlam)
      · have := pow_eq_zero_iff (n := 2) (by norm_num) |>.1 h1
        linarith
    · intro h r'
      have : higgsPotential lam v r = 0 := by
        simp [higgsPotential, h]
      rw [this]
      exact hnonneg r'
  · rw [hmin]
    have : higgsPotential lam v 0 = lam * v ^ 4 := by
      simp only [higgsPotential]; ring
    rw [this]
    positivity
  · simp [gaugeMassSq]
  · have hq2 : 0 < q ^ 2 := lt_of_le_of_ne (sq_nonneg q) (Ne.symm (pow_ne_zero 2 hq))
    have : gaugeMassSq q v = q ^ 2 * v ^ 2 := rfl
    rw [this]
    exact mul_pos hq2 (by positivity)
  · have : gaugeMassSq q v = (|q| * v) ^ 2 := by
      simp [gaugeMassSq, mul_pow, sq_abs]
    rw [this, Real.sqrt_sq (by positivity)]

end Frontier

#print axioms Frontier.higgs_mass_toy
#print axioms Frontier.normSq_covDeriv_const

