/-
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

namespace QPhys

open Matrix NormedSpace

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- The time-evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`. -/
noncomputable def timeEvolution (H : Matrix n n ℂ) (hbar t : ℝ) : Matrix n n ℂ :=
  exp ((-Complex.I * (t : ℂ) / (hbar : ℂ)) • H)

/-- The conjugate transpose of `exp (c • A)` is `exp (conj c • Aᴴ)`. -/
lemma conjTranspose_exp_smul (c : ℂ) (A : Matrix n n ℂ) :
    (exp (c • A))ᴴ = exp ((starRingEnd ℂ c) • Aᴴ) := by
  rw [← Matrix.exp_conjTranspose]
  congr 1
  ext i j
  simp [Matrix.conjTranspose_apply]

/-- **Unitary time evolution.** If `H` is self-adjoint (Hermitian), then for every real time `t`
the operator `U(t) = exp(-i H t / ℏ)` is unitary. -/
theorem unitary_time_evolution (H : Matrix n n ℂ) (hH : H.IsHermitian) (hbar t : ℝ) :
    timeEvolution H hbar t ∈ Matrix.unitaryGroup n ℂ := by
  set c : ℂ := -Complex.I * (t : ℂ) / (hbar : ℂ) with hc
  have hstar : (starRingEnd ℂ) c = -c := by
    rw [hc]
    simp [div_eq_mul_inv]
  have hconj : (timeEvolution H hbar t)ᴴ = exp ((-c) • H) := by
    rw [timeEvolution, conjTranspose_exp_smul, hH.eq, hstar]
  have hcomm : Commute ((-c) • H) (c • H) := by
    simp only [Commute, SemiconjBy, Matrix.smul_mul, Matrix.mul_smul, smul_smul]
    rw [mul_comm]
  have key : (timeEvolution H hbar t)ᴴ * timeEvolution H hbar t = 1 := by
    rw [hconj, timeEvolution, ← Matrix.exp_add_of_commute _ _ hcomm, ← add_smul]
    simp
  have key' : timeEvolution H hbar t * (timeEvolution H hbar t)ᴴ = 1 := by
    rw [hconj, timeEvolution, ← Matrix.exp_add_of_commute _ _ hcomm.symm, ← add_smul]
    simp
  exact ⟨key, key'⟩

/-- Explicit form of unitarity: `U(t)ᴴ * U(t) = 1`. -/
theorem conjTranspose_timeEvolution_mul_self (H : Matrix n n ℂ) (hH : H.IsHermitian)
    (hbar t : ℝ) : (timeEvolution H hbar t)ᴴ * timeEvolution H hbar t = 1 :=
  (unitary_time_evolution H hH hbar t).1

/-- Explicit form of unitarity: `U(t) * U(t)ᴴ = 1`. -/
theorem timeEvolution_mul_conjTranspose_self (H : Matrix n n ℂ) (hH : H.IsHermitian)
    (hbar t : ℝ) : timeEvolution H hbar t * (timeEvolution H hbar t)ᴴ = 1 :=
  (unitary_time_evolution H hH hbar t).2

/-- Unitary evolution preserves the Euclidean norm of state vectors:
`‖U(t) v‖ = ‖v‖` (stated as equality of the squared norms via the dot product). -/
theorem timeEvolution_norm_preserving (H : Matrix n n ℂ) (hH : H.IsHermitian) (hbar t : ℝ)
    (v : n → ℂ) :
    star (timeEvolution H hbar t *ᵥ v) ⬝ᵥ (timeEvolution H hbar t *ᵥ v) = star v ⬝ᵥ v := by
  have h := conjTranspose_timeEvolution_mul_self H hH hbar t
  set U := timeEvolution H hbar t
  have : star (U *ᵥ v) ⬝ᵥ (U *ᵥ v) = star v ⬝ᵥ ((Uᴴ * U) *ᵥ v) := by
    simp [Matrix.star_mulVec, Matrix.dotProduct_mulVec, Matrix.vecMul_vecMul]
  rw [this, h, Matrix.one_mulVec]

end QPhys

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

