import Mathlib
/-!
# Iit Phi Partition
Category: Frontier Mind
Target: Frontier.iit_phi_partition
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-! ## A finite-sum Gibbs inequality

The nonnegativity of a Kullback–Leibler divergence between two finitely supported
probability distributions. -/

/-- One term of Gibbs' inequality: `p - q ≤ p * log (p / q)`, under the absolute
continuity assumption `q = 0 → p = 0`. -/
theorem gibbs_term {p q : ℝ} (hp : 0 ≤ p) (hq : 0 ≤ q) (hac : q = 0 → p = 0) :
    p - q ≤ p * Real.log (p / q) := by
  rcases eq_or_lt_of_le hp with hp0 | hp0
  · simp [← hp0]
    linarith
  · have hq0 : 0 < q := by
      rcases eq_or_lt_of_le hq with h | h
      · exact absurd (hac h.symm) (by linarith)
      · exact h
    have hlog : Real.log (q / p) ≤ q / p - 1 :=
      Real.log_le_sub_one_of_pos (by positivity)
    have hinv : Real.log (p / q) = -Real.log (q / p) := by
      rw [← Real.log_inv]
      congr 1
      field_simp
    rw [hinv]
    have hmul : p * (q / p - 1) = q - p := by field_simp
    nlinarith [hlog, hp0]

/-- Gibbs' inequality (nonnegativity of the discrete Kullback–Leibler divergence). -/
theorem gibbs_sum_nonneg {ι : Type} [Fintype ι] (p q : ι → ℝ)
    (hp : ∀ i, 0 ≤ p i) (hq : ∀ i, 0 ≤ q i)
    (hac : ∀ i, q i = 0 → p i = 0)
    (hsp : ∑ i, p i = 1) (hsq : ∑ i, q i = 1) :
    0 ≤ ∑ i, p i * Real.log (p i / q i) := by
  have h := Finset.sum_le_sum (f := fun i => p i - q i)
      (g := fun i => p i * Real.log (p i / q i))
      (s := Finset.univ) (fun i _ => gibbs_term (hp i) (hq i) (hac i))
  simpa [Finset.sum_sub_distrib, hsp, hsq] using h

/-! ## Systems, bipartitions and effective information -/

variable {V S : Type} [Fintype V] [DecidableEq V] [Fintype S] [DecidableEq S]

/-- A finite discrete dynamical system: `V` is the set of elements, each carrying a
state in `S`, and `tpm` is the transition probability matrix on global states. -/
structure System (V S : Type) [Fintype V] [DecidableEq V] [Fintype S] where
  /-- transition probability from a global state to a global state -/
  tpm : (V → S) → (V → S) → ℝ
  tpm_nonneg : ∀ x y, 0 ≤ tpm x y
  tpm_sum : ∀ x, ∑ y, tpm x y = 1

/-- The part of a global state living on `A`. -/
def resIn (A : Finset V) (x : V → S) : {i // i ∈ A} → S := fun i => x i.1

/-- The part of a global state living on the complement of `A`. -/
def resOut (A : Finset V) (x : V → S) : {i // i ∉ A} → S := fun i => x i.1

/-- Assemble a global state out of its two halves. -/
def combine (A : Finset V) (u : {i // i ∈ A} → S) (v : {i // i ∉ A} → S) : V → S :=
  fun i => if h : i ∈ A then u ⟨i, h⟩ else v ⟨i, h⟩

/-- Splitting a global state along a bipartition is a bijection onto the product of
the two local state spaces. -/
def splitEquiv (A : Finset V) : (V → S) ≃ (({i // i ∈ A} → S) × ({i // i ∉ A} → S)) where
  toFun x := (resIn A x, resOut A x)
  invFun p := combine A p.1 p.2
  left_inv := by
    intro x
    funext i
    simp only [combine, resIn, resOut]
    by_cases h : i ∈ A <;> simp [h]
  right_inv := by
    rintro ⟨u, v⟩
    ext i
    · simp [resIn, combine, i.2]
    · simp [resOut, combine, i.2]

/-- The marginal probability that the next state restricted to `A` equals `u`. -/
noncomputable def margIn (sys : System V S) (A : Finset V) (x : V → S)
    (u : {i // i ∈ A} → S) : ℝ :=
  ∑ y : V → S, if resIn A y = u then sys.tpm x y else 0

/-- The marginal probability that the next state restricted to the complement of `A`
equals `v`. -/
noncomputable def margOut (sys : System V S) (A : Finset V) (x : V → S)
    (v : {i // i ∉ A} → S) : ℝ :=
  ∑ y : V → S, if resOut A y = v then sys.tpm x y else 0

/-- The effective information generated by the state `x`, relative to the cut `A`:
the KL divergence between the true distribution of next states and the product of the
distributions of the two parts taken independently. -/
noncomputable def eiAt (sys : System V S) (A : Finset V) (x : V → S) : ℝ :=
  ∑ y : V → S, sys.tpm x y *
    Real.log (sys.tpm x y / (margIn sys A x (resIn A y) * margOut sys A x (resOut A y)))

/-- The effective information across the cut `A`, averaged over a uniform
(interventional) distribution of current states. -/
noncomputable def EI (sys : System V S) (A : Finset V) : ℝ :=
  (Fintype.card (V → S) : ℝ)⁻¹ * ∑ x : V → S, eiAt sys A x

/-- A bipartition of the set of elements is given by a nonempty proper subset `A`. -/
def IsBipartition (A : Finset V) : Prop := A.Nonempty ∧ A ≠ Finset.univ

/-- Integrated information `Φ`: the minimum of the effective information over all
bipartitions of the system. -/
noncomputable def phi (sys : System V S) : ℝ :=
  sInf {r : ℝ | ∃ A : Finset V, IsBipartition A ∧ r = EI sys A}

/-- A system is disconnected when some bipartition splits its dynamics into two
independent transition matrices. -/
def Disconnected (sys : System V S) : Prop :=
  ∃ A : Finset V, IsBipartition A ∧
    ∃ f : ({i // i ∈ A} → S) → ({i // i ∈ A} → S) → ℝ,
    ∃ g : ({i // i ∉ A} → S) → ({i // i ∉ A} → S) → ℝ,
      (∀ a, ∑ b, f a b = 1) ∧ (∀ a, ∑ b, g a b = 1) ∧
      (∀ x y, sys.tpm x y = f (resIn A x) (resIn A y) * g (resOut A x) (resOut A y))

/-! ## Basic properties of the marginals -/

theorem margIn_nonneg (sys : System V S) (A : Finset V) (x : V → S)
    (u : {i // i ∈ A} → S) : 0 ≤ margIn sys A x u := by
  refine Finset.sum_nonneg fun y _ => ?_
  split_ifs
  · exact sys.tpm_nonneg _ _
  · exact le_rfl

theorem margOut_nonneg (sys : System V S) (A : Finset V) (x : V → S)
    (v : {i // i ∉ A} → S) : 0 ≤ margOut sys A x v := by
  refine Finset.sum_nonneg fun y _ => ?_
  split_ifs
  · exact sys.tpm_nonneg _ _
  · exact le_rfl

theorem tpm_le_margIn (sys : System V S) (A : Finset V) (x y : V → S) :
    sys.tpm x y ≤ margIn sys A x (resIn A y) := by
  have := Finset.single_le_sum (f := fun y' : V → S =>
      if resIn A y' = resIn A y then sys.tpm x y' else 0)
    (fun y' _ => by dsimp only; split_ifs <;> [exact sys.tpm_nonneg _ _; exact le_rfl])
    (Finset.mem_univ y)
  simpa [margIn] using this

theorem tpm_le_margOut (sys : System V S) (A : Finset V) (x y : V → S) :
    sys.tpm x y ≤ margOut sys A x (resOut A y) := by
  have := Finset.single_le_sum (f := fun y' : V → S =>
      if resOut A y' = resOut A y then sys.tpm x y' else 0)
    (fun y' _ => by dsimp only; split_ifs <;> [exact sys.tpm_nonneg _ _; exact le_rfl])
    (Finset.mem_univ y)
  simpa [margOut] using this

theorem sum_margIn (sys : System V S) (A : Finset V) (x : V → S) :
    ∑ u : {i // i ∈ A} → S, margIn sys A x u = 1 := by
  simp only [margIn]
  rw [Finset.sum_comm]
  simp only [Finset.sum_ite_eq, Finset.mem_univ, if_true]
  exact sys.tpm_sum x

theorem sum_margOut (sys : System V S) (A : Finset V) (x : V → S) :
    ∑ v : {i // i ∉ A} → S, margOut sys A x v = 1 := by
  simp only [margOut]
  rw [Finset.sum_comm]
  simp only [Finset.sum_ite_eq, Finset.mem_univ, if_true]
  exact sys.tpm_sum x

omit [DecidableEq S] in
/-- Summing a product of a function of the `A`-part and a function of the
complementary part factorises. -/
theorem sum_split_mul (A : Finset V) (F : ({i // i ∈ A} → S) → ℝ)
    (G : ({i // i ∉ A} → S) → ℝ) :
    ∑ y : V → S, F (resIn A y) * G (resOut A y) = (∑ u, F u) * (∑ v, G v) := by
  rw [Fintype.sum_equiv (splitEquiv A) (fun y => F (resIn A y) * G (resOut A y))
      (fun z => F z.1 * G z.2) (fun _ => rfl), Fintype.sum_prod_type, Finset.sum_mul]
  exact Finset.sum_congr rfl fun u _ => by rw [Finset.mul_sum]

/-! ## Nonnegativity of effective information -/

theorem eiAt_nonneg (sys : System V S) (A : Finset V) (x : V → S) : 0 ≤ eiAt sys A x := by
  simp only [eiAt]
  refine gibbs_sum_nonneg (fun y => sys.tpm x y)
    (fun y => margIn sys A x (resIn A y) * margOut sys A x (resOut A y))
    (fun y => sys.tpm_nonneg x y)
    (fun y => mul_nonneg (margIn_nonneg sys A x _) (margOut_nonneg sys A x _)) ?_
    (sys.tpm_sum x) ?_
  · intro y hy
    rcases mul_eq_zero.1 hy with hz | hz
    · exact le_antisymm (hz ▸ tpm_le_margIn sys A x y) (sys.tpm_nonneg x y)
    · exact le_antisymm (hz ▸ tpm_le_margOut sys A x y) (sys.tpm_nonneg x y)
  · rw [sum_split_mul A (margIn sys A x) (margOut sys A x), sum_margIn, sum_margOut, mul_one]

theorem EI_nonneg (sys : System V S) (A : Finset V) : 0 ≤ EI sys A := by
  refine mul_nonneg (by positivity) (Finset.sum_nonneg fun x _ => eiAt_nonneg sys A x)

/-! ## A disconnected cut carries no effective information -/

theorem margIn_of_factor (sys : System V S) (A : Finset V)
    (f : ({i // i ∈ A} → S) → ({i // i ∈ A} → S) → ℝ)
    (g : ({i // i ∉ A} → S) → ({i // i ∉ A} → S) → ℝ)
    (hg : ∀ a, ∑ b, g a b = 1)
    (hfac : ∀ x y, sys.tpm x y = f (resIn A x) (resIn A y) * g (resOut A x) (resOut A y))
    (x : V → S) (u : {i // i ∈ A} → S) :
    margIn sys A x u = f (resIn A x) u := by
  have key : ∀ y : V → S, (if resIn A y = u then sys.tpm x y else 0)
      = (fun u' => if u' = u then f (resIn A x) u' else 0) (resIn A y)
        * g (resOut A x) (resOut A y) := by
    intro y
    by_cases h : resIn A y = u <;> simp [h, hfac x y]
  simp only [margIn]
  rw [Finset.sum_congr rfl (fun y _ => key y),
    sum_split_mul A (fun u' => if u' = u then f (resIn A x) u' else 0) (g (resOut A x)), hg]
  simp

theorem margOut_of_factor (sys : System V S) (A : Finset V)
    (f : ({i // i ∈ A} → S) → ({i // i ∈ A} → S) → ℝ)
    (g : ({i // i ∉ A} → S) → ({i // i ∉ A} → S) → ℝ)
    (hf : ∀ a, ∑ b, f a b = 1)
    (hfac : ∀ x y, sys.tpm x y = f (resIn A x) (resIn A y) * g (resOut A x) (resOut A y))
    (x : V → S) (v : {i // i ∉ A} → S) :
    margOut sys A x v = g (resOut A x) v := by
  have key : ∀ y : V → S, (if resOut A y = v then sys.tpm x y else 0)
      = f (resIn A x) (resIn A y)
        * (fun v' => if v' = v then g (resOut A x) v' else 0) (resOut A y) := by
    intro y
    by_cases h : resOut A y = v <;> simp [h, hfac x y]
  simp only [margOut]
  rw [Finset.sum_congr rfl (fun y _ => key y),
    sum_split_mul A (f (resIn A x)) (fun v' => if v' = v then g (resOut A x) v' else 0), hf]
  simp

theorem EI_eq_zero_of_factor (sys : System V S) (A : Finset V)
    (f : ({i // i ∈ A} → S) → ({i // i ∈ A} → S) → ℝ)
    (g : ({i // i ∉ A} → S) → ({i // i ∉ A} → S) → ℝ)
    (hf : ∀ a, ∑ b, f a b = 1) (hg : ∀ a, ∑ b, g a b = 1)
    (hfac : ∀ x y, sys.tpm x y = f (resIn A x) (resIn A y) * g (resOut A x) (resOut A y)) :
    EI sys A = 0 := by
  have hzero : ∀ x : V → S, eiAt sys A x = 0 := by
    intro x
    simp only [eiAt]
    refine Finset.sum_eq_zero fun y _ => ?_
    rw [margIn_of_factor sys A f g hg hfac, margOut_of_factor sys A f g hf hfac, ← hfac x y]
    rcases eq_or_ne (sys.tpm x y) 0 with h | h
    · simp [h]
    · rw [div_self h, Real.log_one, mul_zero]
  simp [EI, hzero]

/-! ## Main theorem -/

/-- **Integrated information vanishes for a disconnected system.**
If some bipartition of the elements splits the dynamics into two independent
subsystems, then `Φ`, defined as the minimum of the effective information over all
bipartitions, is zero. -/
theorem iit_phi_partition (sys : System V S) (h : Disconnected sys) : phi sys = 0 := by
  obtain ⟨A, hA, f, g, hf, hg, hfac⟩ := h
  have hzero : EI sys A = 0 := EI_eq_zero_of_factor sys A f g hf hg hfac
  have hmem : (0 : ℝ) ∈ {r : ℝ | ∃ B : Finset V, IsBipartition B ∧ r = EI sys B} :=
    ⟨A, hA, hzero.symm⟩
  have hbdd : BddBelow {r : ℝ | ∃ B : Finset V, IsBipartition B ∧ r = EI sys B} := by
    refine ⟨0, ?_⟩
    rintro r ⟨B, -, rfl⟩
    exact EI_nonneg sys B
  refine le_antisymm (csInf_le hbdd hmem) (le_csInf ⟨0, hmem⟩ ?_)
  rintro r ⟨B, -, rfl⟩
  exact EI_nonneg sys B

/-! ## A concrete instance, showing the hypotheses are satisfiable -/

/-- Two binary elements evolving independently and uniformly. -/
noncomputable def uniformPair : System Bool Bool where
  tpm := fun _ _ => (1 / 4 : ℝ)
  tpm_nonneg := by intro x y; norm_num
  tpm_sum := by intro x; rw [Finset.sum_const]; simp

theorem uniformPair_disconnected : Disconnected uniformPair := by
  refine ⟨{true}, ⟨⟨true, by simp⟩, by decide⟩, (fun _ _ => 1 / 2), (fun _ _ => 1 / 2),
    ?_, ?_, ?_⟩
  · intro a; rw [Finset.sum_const]; simp
  · intro a; rw [Finset.sum_const]; simp
  · intro x y; norm_num [uniformPair]

/-- The uniform pair of independent binary elements has zero integrated information. -/
theorem phi_uniformPair : phi uniformPair = 0 :=
  iit_phi_partition uniformPair uniformPair_disconnected

end Frontier

