/-!
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

/-
## Overview

This file formalises the algebraic core of Ed25519 signature verification, as used by a
proof-carrying-application *isolation engine*: the engine admits a payload only when the
attached certificate carries an Ed25519 signature that verifies against the enclave's
public key.

The concrete twisted-Edwards curve is abstracted to exactly the structure the argument
uses: a type `G` of curve points with an addition `add`, an integer scalar multiplication
`smul`, a base point `B`, and the order `L` of `B` (for Ed25519,
`L = 2 ^ 252 + 27742317777372353535851937790883648493`).  The three laws recorded in
`PCA.Cert.EdModel` are:

* `smul_add_base` : `[x]B + [y]B = [x + y]B`   (the group law on the cyclic subgroup `⟨B⟩`);
* `smul_smul_base` : `[x]([y]B) = [x * y]B`     (associativity of scalar multiplication);
* `base_eq_iff`   : `[x]B = [y]B ↔ L ∣ x - y`   (`B` has order exactly `L`).

`PCA.Cert.EdModel.ofOrder` builds such a model for every `L > 1`, so the axiomatisation is
consistent and the results below are not vacuous; `PCA.Cert.ed25519Model` instantiates it at
the true Ed25519 group order.  A Mathlib-idiomatic restatement over an arbitrary
`AddCommGroup` with a point of order `L`, together with the bridge to the results proved
here, lives in `RequestProject.Ed25519Mathlib`.

Key generation, signing and verification are modelled by

* secret scalar `s`, public key `A = [s]B`                          (`pubKey`),
* per-message nonce `r`, commitment `R = [r]B`                      (`commit`),
* challenge `h` (the integer `H(R ‖ A ‖ M)`),
* response `S = (r + h * s) mod L`                                  (`respond`),
* verification `[S]B = R + [h]A`                                    (`Verify`).

Main results:

* `ed25519_verify_sound` — **soundness**: whenever verification accepts a signature
  `(R, S)` under a public key `A = [s]B` with commitment `R = [r]B`, the response `S` is
  forced to be congruent mod `L` to the honest Schnorr response `r + h * s`.  No accepted
  signature can deviate from what the signing algorithm produces.
* `ed25519_verify_complete` — **completeness**: honestly generated signatures always verify.
* `ed25519_verify_iff` — soundness and completeness combined into a characterisation.
* `ed25519_response_unique` — the accepted response is unique modulo `L`.
* `ed25519_extract_secret_key` — special soundness: two accepting transcripts that share a
  commitment but use different challenges determine the secret key.
* `ed25519_engine_sound` — the isolation-engine reading: an admitted certificate carries
  precisely the honest signature of its payload under the enclave key.

The development is self-contained: it uses no imports beyond Lean's core `Init`, hence no
axioms beyond `propext`, `Classical.choice`, `Quot.sound`.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

universe u

namespace PCA.Cert

/-! ## The model -/

/-- An Ed25519-style signature model: a type of curve points `G` with addition `add`,
integer scalar multiplication `smul`, base point `B`, and group order `L` of `B`.

Only the behaviour of the operations on the cyclic subgroup generated by `B` is recorded,
since verification never leaves that subgroup. -/
structure EdModel (G : Type u) where
  /-- Addition of curve points. -/
  add : G → G → G
  /-- Integer scalar multiplication of curve points. -/
  smul : Int → G → G
  /-- The base point. -/
  B : G
  /-- The order of the base point (a prime, for Ed25519). -/
  L : Int
  /-- The order exceeds `1`. -/
  one_lt_L : 1 < L
  /-- Group law on `⟨B⟩`: `[x]B + [y]B = [x + y]B`. -/
  smul_add_base : ∀ x y : Int, add (smul x B) (smul y B) = smul (x + y) B
  /-- Associativity of scalar multiplication on `⟨B⟩`: `[x]([y]B) = [x * y]B`. -/
  smul_smul_base : ∀ x y : Int, smul x (smul y B) = smul (x * y) B
  /-- `B` has order exactly `L`: `[x]B = [y]B` iff `L` divides `x - y`. -/
  base_eq_iff : ∀ x y : Int, smul x B = smul y B ↔ L ∣ (x - y)

namespace EdModel

variable {G : Type u} (M : EdModel G)

/-- The public key belonging to the secret scalar `s`, namely `A = [s]B`. -/
def pubKey (s : Int) : G := M.smul s M.B

/-- The commitment (the `R` component of a signature) for the nonce `r`, namely `R = [r]B`. -/
def commit (r : Int) : G := M.smul r M.B

/-- The response (the `S` component of a signature): `S = (r + h * s) mod L`. -/
def respond (r h s : Int) : Int := (r + h * s) % M.L

/-- The Ed25519 verification equation `[S]B = R + [h]A`. -/
def Verify (A R : G) (h S : Int) : Prop :=
  M.smul S M.B = M.add R (M.smul h A)

end EdModel

/-! ## Basic arithmetic facts -/

/-- Reduction mod `L` changes a scalar only by a multiple of `L`. -/
theorem dvd_emod_sub_self (a L : Int) : L ∣ (a % L - a) :=
  ⟨-(a / L), by
    have h := Int.emod_add_mul_ediv a L
    rw [Int.mul_neg]
    omega⟩

/-- Two integers have the same residue mod `L` exactly when `L` divides their difference. -/
theorem emod_eq_iff_dvd_sub (x y L : Int) : x % L = y % L ↔ L ∣ (x - y) := by
  constructor
  · intro h
    exact Int.dvd_of_emod_eq_zero (by rw [Int.sub_emod, h, Int.sub_self, Int.zero_emod])
  · intro h
    obtain ⟨k, hk⟩ := h
    have hx : x = y + L * k := by omega
    subst hx
    simp [Int.add_mul_emod_self_left]

/-! ## Soundness and completeness of verification -/

variable {G : Type u} {M : EdModel G}

/-- On the subgroup generated by `B`, the verification equation `[S]B = [r]B + [h]([s]B)`
collapses to the scalar equation `[S]B = [r + h * s]B`. -/
theorem verify_iff_base_eq (s r h S : Int) :
    M.Verify (M.pubKey s) (M.commit r) h S ↔ M.smul S M.B = M.smul (r + h * s) M.B := by
  unfold EdModel.Verify EdModel.pubKey EdModel.commit
  rw [M.smul_smul_base, M.smul_add_base]

/-- **Soundness of Ed25519 verification.**

If the verification equation `[S]B = R + [h]A` holds for a public key `A = [s]B` and a
commitment `R = [r]B`, then the response `S` is congruent modulo the group order `L` to the
honest Schnorr response `r + h * s`.

Consequently an isolation engine that accepts a certificate only when this equation holds
can accept nothing other than a signature the legitimate signer would have produced: the
accepted `S` is determined, mod `L`, by the secret key `s`, the nonce `r` and the challenge
`h`. -/
theorem ed25519_verify_sound {s r h S : Int}
    (hver : M.Verify (M.pubKey s) (M.commit r) h S) :
    M.L ∣ (S - (r + h * s)) :=
  (M.base_eq_iff _ _).1 ((verify_iff_base_eq s r h S).1 hver)

/-- **Completeness of Ed25519 verification.**

The honestly generated signature `(R, S) = ([r]B, (r + h * s) mod L)` always verifies
against the public key `A = [s]B`. -/
theorem ed25519_verify_complete (s r h : Int) :
    M.Verify (M.pubKey s) (M.commit r) h (M.respond r h s) := by
  rw [verify_iff_base_eq]
  exact (M.base_eq_iff _ _).2 (dvd_emod_sub_self (r + h * s) M.L)

/-- Soundness and completeness combined: verification succeeds **iff** the response is the
honest Schnorr response modulo the group order. -/
theorem ed25519_verify_iff (s r h S : Int) :
    M.Verify (M.pubKey s) (M.commit r) h S ↔ S % M.L = (r + h * s) % M.L := by
  constructor
  · intro hver
    exact (emod_eq_iff_dvd_sub _ _ _).2 (ed25519_verify_sound hver)
  · intro hS
    rw [verify_iff_base_eq]
    exact (M.base_eq_iff _ _).2 ((emod_eq_iff_dvd_sub _ _ _).1 hS)

/-- Verification accepts exactly one response modulo `L`: the accepted `S` is the reduced
honest response `respond r h s`, up to congruence. -/
theorem ed25519_response_canonical {s r h S : Int}
    (hver : M.Verify (M.pubKey s) (M.commit r) h S) :
    S % M.L = M.respond r h s := by
  have h1 : S % M.L = (r + h * s) % M.L := (ed25519_verify_iff s r h S).1 hver
  simpa [EdModel.respond] using h1

/-- Determinism: two responses accepted for the same public key, commitment and challenge
agree modulo the group order. -/
theorem ed25519_response_unique {s r h S₁ S₂ : Int}
    (h₁ : M.Verify (M.pubKey s) (M.commit r) h S₁)
    (h₂ : M.Verify (M.pubKey s) (M.commit r) h S₂) :
    S₁ % M.L = S₂ % M.L := by
  rw [(ed25519_verify_iff s r h S₁).1 h₁, (ed25519_verify_iff s r h S₂).1 h₂]

/-- **Special soundness / key extraction.**

Two accepting transcripts that share the commitment `R = [r]B` but use distinct challenges
`h₁`, `h₂` pin the secret key down: `(h₁ - h₂) * s ≡ S₁ - S₂ (mod L)`.  When `L` is prime
and `h₁ ≢ h₂ (mod L)` the factor `h₁ - h₂` is invertible mod `L`, so `s` is recovered from
the transcripts — the standard extractor behind Ed25519's unforgeability argument. -/
theorem ed25519_extract_secret_key {s r h₁ h₂ S₁ S₂ : Int}
    (hv₁ : M.Verify (M.pubKey s) (M.commit r) h₁ S₁)
    (hv₂ : M.Verify (M.pubKey s) (M.commit r) h₂ S₂) :
    M.L ∣ ((h₁ - h₂) * s - (S₁ - S₂)) := by
  obtain ⟨k₁, hk₁⟩ := ed25519_verify_sound hv₁
  obtain ⟨k₂, hk₂⟩ := ed25519_verify_sound hv₂
  refine ⟨-(k₁ - k₂), ?_⟩
  have hexp : (h₁ - h₂) * s = h₁ * s - h₂ * s := by
    rw [Int.sub_mul]
  rw [hexp, Int.mul_neg, Int.mul_sub]
  omega

/-! ## The isolation-engine reading -/

/-- A certificate as carried by a proof-carrying application: the enclave public key, the
signature `(R, S)` and the challenge `h = H(R ‖ A ‖ M)` computed from the payload. -/
structure Cert (G : Type u) where
  /-- The public key the signature is checked against. -/
  pk : G
  /-- The `R` component of the signature. -/
  R : G
  /-- The `S` component of the signature. -/
  S : Int
  /-- The challenge, i.e. the hash of commitment, public key and payload. -/
  chal : Int

/-- The isolation engine admits a certificate exactly when its Ed25519 signature verifies. -/
def EdModel.admits (M : EdModel G) (c : Cert G) : Prop :=
  M.Verify c.pk c.R c.chal c.S

/-- **Soundness of the isolation engine.**

If the engine admits a certificate whose public key and commitment are honest curve points
`[s]B` and `[r]B`, then the certificate's response is exactly the response the holder of the
secret key `s` would have produced for nonce `r` and challenge `chal`.  Nothing else is ever
admitted. -/
theorem ed25519_engine_sound {M : EdModel G} {c : Cert G} {s r : Int}
    (hpk : c.pk = M.pubKey s) (hR : c.R = M.commit r) (hadm : M.admits c) :
    c.S % M.L = M.respond r c.chal s := by
  have hver : M.Verify (M.pubKey s) (M.commit r) c.chal c.S := by
    rw [← hpk, ← hR]; exact hadm
  exact ed25519_response_canonical hver

/-- **Completeness of the isolation engine**: a certificate assembled by the honest signer is
always admitted. -/
theorem ed25519_engine_complete (M : EdModel G) (s r h : Int) :
    M.admits ⟨M.pubKey s, M.commit r, M.respond r h s, h⟩ :=
  ed25519_verify_complete s r h

/-! ## Non-vacuity: a model exists for every order `L > 1` -/

/-- The residue model `ℤ / Lℤ`, presented by canonical representatives, is an `EdModel` with
base point `1` of order `L`.  Its existence shows the axioms of `EdModel` are consistent, so
none of the theorems above is vacuous. -/
def EdModel.ofOrder (L : Int) (hL : 1 < L) : EdModel Int where
  add x y := (x + y) % L
  smul n x := (n * x) % L
  B := 1
  L := L
  one_lt_L := hL
  smul_add_base x y := by
    simp only [Int.mul_one]
    rw [← Int.add_emod]
  smul_smul_base x y := by
    simp only [Int.mul_one]
    rw [Int.mul_emod, Int.emod_emod_of_dvd _ (Int.dvd_refl L), ← Int.mul_emod]
  base_eq_iff x y := by
    simp only [Int.mul_one]
    exact emod_eq_iff_dvd_sub x y L

/-- The order of the Ed25519 base point,
`L = 2 ^ 252 + 27742317777372353535851937790883648493`. -/
def ed25519Order : Int := 2 ^ 252 + 27742317777372353535851937790883648493

/-- A concrete model at the true Ed25519 group order. -/
def ed25519Model : EdModel Int :=
  EdModel.ofOrder ed25519Order (by decide)

/-- Instance of soundness at the concrete Ed25519 order: an accepted signature is the honest
one, modulo `2 ^ 252 + 27742317777372353535851937790883648493`. -/
theorem ed25519_verify_sound_concrete {s r h S : Int}
    (hver : ed25519Model.Verify (ed25519Model.pubKey s) (ed25519Model.commit r) h S) :
    ed25519Order ∣ (S - (r + h * s)) :=
  ed25519_verify_sound hver

end PCA.Cert

import Mathlib
import RequestProject.Ed25519VerifySound

/-!
# Ed25519 verification soundness over an arbitrary abelian group (Mathlib restatement)

`RequestProject.Ed25519VerifySound` proves soundness and completeness of Ed25519 signature
verification for the abstract model `PCA.Cert.EdModel`, using nothing but Lean's core
library (so that the required header comment can be the very first thing in that file).

Here we connect that development to Mathlib: every additive commutative group `G` with a
point `B` of order `L` — in particular the Ed25519 twisted-Edwards curve group with its
standard base point — yields an `EdModel`, and the soundness and completeness statements
take their familiar form

  `[S]B = R + [h]A`  with  `A = [s]B`, `R = [r]B`  ⟺  `S ≡ r + h * s [ZMOD L]`.

`PCA.Cert.edModel_zmod` records the non-vacuity witness `G = ZMod p`, `B = 1`.
-/

set_option autoImplicit false

namespace PCA.Cert

variable {G : Type*} [AddCommGroup G]

/-- Every abelian group `G` with a point `B` of order exactly `L > 1` gives an `EdModel`.
The Ed25519 curve group with its standard base point is such a group, with
`L = 2 ^ 252 + 27742317777372353535851937790883648493`. -/
def EdModel.ofAddCommGroup (B : G) (L : ℕ) (hL : 1 < L)
    (hord : ∀ n : ℤ, n • B = 0 ↔ (L : ℤ) ∣ n) : EdModel G where
  add := (· + ·)
  smul := (· • ·)
  B := B
  L := (L : ℤ)
  one_lt_L := by exact_mod_cast hL
  smul_add_base x y := (add_smul x y B).symm
  smul_smul_base x y := smul_smul x y B
  base_eq_iff x y := by
    constructor
    · intro hxy
      refine (hord (x - y)).1 ?_
      rw [sub_smul, hxy, sub_self]
    · intro hdvd
      have h0 : (x - y) • B = 0 := (hord (x - y)).2 hdvd
      rw [sub_smul, sub_eq_zero] at h0
      exact h0

/-- **Soundness of Ed25519 verification, stated over an arbitrary abelian group.**

If the verification equation `[S]B = R + [h]A` holds, where the public key is `A = [s]B` and
the commitment is `R = [r]B` for a base point `B` of order `L`, then the response `S` is
congruent modulo `L` to the honest Schnorr response `r + h * s`. -/
theorem ed25519_verify_sound_group {B : G} {L : ℕ} (hL : 1 < L)
    (hord : ∀ n : ℤ, n • B = 0 ↔ (L : ℤ) ∣ n) {s r h S : ℤ}
    (hver : S • B = r • B + h • (s • B)) :
    S ≡ r + h * s [ZMOD (L : ℤ)] := by
  have hdvd : ((L : ℤ)) ∣ (S - (r + h * s)) :=
    ed25519_verify_sound (M := EdModel.ofAddCommGroup B L hL hord) hver
  exact (Int.modEq_iff_dvd.2 hdvd).symm

/-- **Completeness of Ed25519 verification, stated over an arbitrary abelian group.**
Honestly produced signatures verify. -/
theorem ed25519_verify_complete_group {B : G} {L : ℕ} (hL : 1 < L)
    (hord : ∀ n : ℤ, n • B = 0 ↔ (L : ℤ) ∣ n) (s r h S : ℤ)
    (hS : S ≡ r + h * s [ZMOD (L : ℤ)]) :
    S • B = r • B + h • (s • B) := by
  have hdvd : ((L : ℤ)) ∣ (S - (r + h * s)) := Int.ModEq.dvd hS.symm
  have := (EdModel.ofAddCommGroup B L hL hord).base_eq_iff S (r + h * s)
  have hbase : S • B = (r + h * s) • B := this.2 hdvd
  rw [hbase, add_smul, smul_smul]

/-- Verification succeeds **iff** the response is the honest one modulo the group order. -/
theorem ed25519_verify_iff_group {B : G} {L : ℕ} (hL : 1 < L)
    (hord : ∀ n : ℤ, n • B = 0 ↔ (L : ℤ) ∣ n) (s r h S : ℤ) :
    S • B = r • B + h • (s • B) ↔ S ≡ r + h * s [ZMOD (L : ℤ)] :=
  ⟨ed25519_verify_sound_group hL hord, ed25519_verify_complete_group hL hord s r h S⟩

/-- Non-vacuity witness in Mathlib terms: `ZMod p` with base point `1` is a model of order
`p` for every prime `p`. -/
def edModel_zmod (p : ℕ) [Fact (Nat.Prime p)] : EdModel (ZMod p) :=
  EdModel.ofAddCommGroup (1 : ZMod p) p (Fact.out (p := Nat.Prime p)).one_lt (by
    intro n
    have : n • (1 : ZMod p) = ((n : ZMod p)) := by
      simp
    rw [this, ZMod.intCast_zmod_eq_zero_iff_dvd])

end PCA.Cert

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

