-- Header (Lean requires `import` to precede any module docstring):
/-
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib
/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace QPhys

open NormedSpace Complex

section Algebra

variable {A : Type*} [NormedRing A] [NormedAlgebra ℂ A] [StarRing A] [ContinuousStar A]
  [CompleteSpace A] [StarModule ℂ A]

/-- The time-evolution operator `U t = exp (-i H t / ℏ)` generated by a Hamiltonian `H`. -/
noncomputable def timeEvolution (H : A) (hbar t : ℝ) : A :=
  exp ((-(I * (t : ℂ) / (hbar : ℂ))) • H)

/-- **Unitary time evolution.** If `H` is self-adjoint, then for every real time `t`
the operator `U t = exp (-i H t / ℏ)` is unitary. -/
theorem unitary_time_evolution (H : A) (hH : IsSelfAdjoint H) (hbar t : ℝ) :
    timeEvolution H hbar t ∈ unitary A := by
  have : NormedAlgebra ℚ A := NormedAlgebra.restrictScalars ℚ ℂ A
  refine exp_mem_unitary_of_mem_skewAdjoint ?_
  rw [skewAdjoint.mem_iff, star_smul, hH.star_eq, ← neg_smul]
  congr 1
  simp [Complex.ext_iff]
  ring

/-- Explicit form of unitarity: `U(t)† U(t) = 1` and `U(t) U(t)† = 1`. -/
theorem star_timeEvolution_mul_self (H : A) (hH : IsSelfAdjoint H) (hbar t : ℝ) :
    star (timeEvolution H hbar t) * timeEvolution H hbar t = 1 ∧
      timeEvolution H hbar t * star (timeEvolution H hbar t) = 1 :=
  unitary_time_evolution H hH hbar t

end Algebra

section HilbertSpace

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E] [CompleteSpace E]

/-- **Unitary time evolution on a Hilbert space.** For a bounded self-adjoint Hamiltonian
`H : E →L[ℂ] E` on a complex Hilbert space `E`, the evolution operator
`U t = exp (-i H t / ℏ)` is unitary for every real time `t`. -/
theorem unitary_time_evolution_hilbert (H : E →L[ℂ] E) (hH : IsSelfAdjoint H) (hbar t : ℝ) :
    timeEvolution H hbar t ∈ unitary (E →L[ℂ] E) :=
  unitary_time_evolution H hH hbar t

/-- Time evolution preserves inner products: `⟪U t x, U t y⟫ = ⟪x, y⟫`. -/
theorem inner_timeEvolution_hilbert (H : E →L[ℂ] E) (hH : IsSelfAdjoint H) (hbar t : ℝ)
    (x y : E) :
    inner ℂ (timeEvolution H hbar t x) (timeEvolution H hbar t y) = inner ℂ x y := by
  have h := (unitary_time_evolution_hilbert H hH hbar t).1
  have : ((star (timeEvolution H hbar t) * timeEvolution H hbar t : E →L[ℂ] E)) y = y := by
    rw [h]; simp
  calc inner ℂ (timeEvolution H hbar t x) (timeEvolution H hbar t y)
      = inner ℂ x ((star (timeEvolution H hbar t) * timeEvolution H hbar t : E →L[ℂ] E) y) := by
        simp [ContinuousLinearMap.star_eq_adjoint, ContinuousLinearMap.adjoint_inner_right]
    _ = inner ℂ x y := by rw [this]

end HilbertSpace

end QPhys

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

