/-
# Iit Phi Partition
Category: Frontier Mind
Target: Frontier.iit_phi_partition
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

/-!
# Iit Phi Partition
Category: Frontier Mind
Target: Frontier.iit_phi_partition
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Frontier

/-! ## Systems

A (discrete, finite) system consists of a finite set `ι` of elements, each of which can be
in one of finitely many states `Q`; a global state of the system is a function `ι → Q`.
The dynamics are given by a transition probability matrix (TPM): for every current global
state `s`, a probability distribution `prob s` over next global states. -/

/-- A transition probability matrix on the global state space `ι → Q`. -/
structure TPM (ι Q : Type) [Fintype ι] [DecidableEq ι] [Fintype Q] where
  /-- `prob s u` is the probability that the system moves from state `s` to state `u`. -/
  prob : (ι → Q) → (ι → Q) → ℝ
  /-- Probabilities are nonnegative. -/
  nonneg : ∀ s u, 0 ≤ prob s u
  /-- For each current state, the next-state probabilities sum to one. -/
  normalized : ∀ s, ∑ u, prob s u = 1

variable {ι Q : Type} [Fintype ι] [DecidableEq ι] [Fintype Q]

/-- The elements on one side of the bipartition determined by `S`. -/
abbrev Part (S : Finset ι) : Type := {i : ι // i ∈ S}

/-- The elements on the other side of the bipartition determined by `S`. -/
abbrev CoPart (S : Finset ι) : Type := {i : ι // i ∉ S}

/-- Restriction of a global state to the `S`-part of the system. -/
def restA (S : Finset ι) (s : ι → Q) : Part S → Q := fun i => s i.1

/-- Restriction of a global state to the complement of the `S`-part of the system. -/
def restB (S : Finset ι) (s : ι → Q) : CoPart S → Q := fun i => s i.1

/-- A global state is the same data as a pair of states of the two sides of a bipartition. -/
def splitEquiv (S : Finset ι) : (ι → Q) ≃ ((Part S → Q) × (CoPart S → Q)) :=
  Equiv.piEquivPiSubtypeProd (fun i => i ∈ S) (fun _ => Q)

/-- The next-state distribution, read as a distribution on pairs
`(state of the S-part, state of the complementary part)`. -/
def joint (T : TPM ι Q) (S : Finset ι) (s : ι → Q) (a : Part S → Q) (b : CoPart S → Q) : ℝ :=
  T.prob s ((splitEquiv S).symm (a, b))

/-- The marginal distribution of the next state of the `S`-part. -/
def margA (T : TPM ι Q) (S : Finset ι) (s : ι → Q) (a : Part S → Q) : ℝ :=
  ∑ b : CoPart S → Q, joint T S s a b

/-- The marginal distribution of the next state of the complementary part. -/
def margB (T : TPM ι Q) (S : Finset ι) (s : ι → Q) (b : CoPart S → Q) : ℝ :=
  ∑ a : Part S → Q, joint T S s a b

/-- The effective information generated by the system in state `s` across the bipartition
`(S, Sᶜ)`: the Kullback–Leibler divergence of the actual next-state distribution from the
product of the next-state distributions of the two parts taken independently. -/
noncomputable def ei (T : TPM ι Q) (S : Finset ι) (s : ι → Q) : ℝ :=
  ∑ a : Part S → Q, ∑ b : CoPart S → Q,
    joint T S s a b * Real.log (joint T S s a b / (margA T S s a * margB T S s b))

/-- The effective information across the bipartition `(S, Sᶜ)`, averaged over current states
with respect to the uniform (maximum entropy) prior. -/
noncomputable def EI (T : TPM ι Q) (S : Finset ι) : ℝ :=
  (∑ s : ι → Q, ei T S s) / (Fintype.card (ι → Q) : ℝ)

/-- The set of nontrivial bipartitions of the system. -/
def Bipartitions (ι : Type) [Fintype ι] : Set (Finset ι) :=
  {S : Finset ι | S.Nonempty ∧ S ≠ Finset.univ}

/-- **Integrated information** `Φ`: the effective information across the bipartition that
is least able to distinguish the system from its parts (the "minimum information partition"). -/
noncomputable def Phi (T : TPM ι Q) : ℝ :=
  sInf ((fun S => EI T S) '' Bipartitions ι)

/-- The system is *disconnected* along `S` if its dynamics factorize: the next state of the
`S`-part depends stochastically only on the current state of the `S`-part, the next state of
the complementary part depends only on the current state of the complementary part, and the
two are independent. -/
def Disconnected (T : TPM ι Q) (S : Finset ι) : Prop :=
  ∃ (f : (Part S → Q) → (Part S → Q) → ℝ) (g : (CoPart S → Q) → (CoPart S → Q) → ℝ),
    ∀ s u : ι → Q,
      T.prob s u = f (restA S s) (restA S u) * g (restB S s) (restB S u)

/-! ## Basic properties -/

lemma joint_nonneg (T : TPM ι Q) (S : Finset ι) (s : ι → Q) (a : Part S → Q)
    (b : CoPart S → Q) : 0 ≤ joint T S s a b := T.nonneg _ _

lemma sum_joint (T : TPM ι Q) (S : Finset ι) (s : ι → Q) :
    ∑ a : Part S → Q, ∑ b : CoPart S → Q, joint T S s a b = 1 := by
  have h : ∑ ab : (Part S → Q) × (CoPart S → Q), T.prob s ((splitEquiv S).symm ab) = 1 := by
    rw [Equiv.sum_comp (splitEquiv S).symm (T.prob s)]
    exact T.normalized s
  rw [Fintype.sum_prod_type] at h
  exact h

lemma margA_nonneg (T : TPM ι Q) (S : Finset ι) (s : ι → Q) (a : Part S → Q) :
    0 ≤ margA T S s a :=
  Finset.sum_nonneg fun _ _ => joint_nonneg T S s _ _

lemma margB_nonneg (T : TPM ι Q) (S : Finset ι) (s : ι → Q) (b : CoPart S → Q) :
    0 ≤ margB T S s b :=
  Finset.sum_nonneg fun _ _ => joint_nonneg T S s _ _

lemma sum_margA (T : TPM ι Q) (S : Finset ι) (s : ι → Q) :
    ∑ a : Part S → Q, margA T S s a = 1 := by
  simpa [margA] using sum_joint T S s

lemma sum_margB (T : TPM ι Q) (S : Finset ι) (s : ι → Q) :
    ∑ b : CoPart S → Q, margB T S s b = 1 := by
  simp only [margB]
  rw [Finset.sum_comm]
  simpa using sum_joint T S s

lemma le_margA (T : TPM ι Q) (S : Finset ι) (s : ι → Q) (a : Part S → Q) (b : CoPart S → Q) :
    joint T S s a b ≤ margA T S s a :=
  Finset.single_le_sum (f := fun b => joint T S s a b)
    (fun _ _ => joint_nonneg T S s _ _) (Finset.mem_univ b)

lemma le_margB (T : TPM ι Q) (S : Finset ι) (s : ι → Q) (a : Part S → Q) (b : CoPart S → Q) :
    joint T S s a b ≤ margB T S s b :=
  Finset.single_le_sum (f := fun a => joint T S s a b)
    (fun _ _ => joint_nonneg T S s _ _) (Finset.mem_univ a)

/-- The product distribution of the two marginals is itself normalized. -/
lemma sum_prod_marg (T : TPM ι Q) (S : Finset ι) (s : ι → Q) :
    ∑ a : Part S → Q, ∑ b : CoPart S → Q, margA T S s a * margB T S s b = 1 := by
  have : ∑ a : Part S → Q, ∑ b : CoPart S → Q, margA T S s a * margB T S s b
      = (∑ a : Part S → Q, margA T S s a) * (∑ b : CoPart S → Q, margB T S s b) := by
    rw [Finset.sum_mul]
    exact Finset.sum_congr rfl fun a _ => by rw [Finset.mul_sum]
  rw [this, sum_margA, sum_margB, mul_one]

/-- Pointwise Gibbs inequality: `p * log (p / q) ≥ p - q`. -/
lemma gibbs_pointwise {p q : ℝ} (hp : 0 ≤ p) (hq : 0 ≤ q) (hpq : 0 < p → 0 < q) :
    p - q ≤ p * Real.log (p / q) := by
  rcases eq_or_lt_of_le hp with hp0 | hp0
  · simp [← hp0, hq]
  · have hq0 : 0 < q := hpq hp0
    have hlog : Real.log (q / p) ≤ q / p - 1 :=
      Real.log_le_sub_one_of_pos (div_pos hq0 hp0)
    have hrw : Real.log (q / p) = -Real.log (p / q) := by
      rw [← Real.log_inv]
      congr 1
      field_simp
    rw [hrw] at hlog
    have h := mul_le_mul_of_nonneg_left hlog (le_of_lt hp0)
    have hpq' : p * (q / p - 1) = q - p := by field_simp
    rw [hpq'] at h
    linarith

/-! ## Effective information is nonnegative, and vanishes for disconnected systems -/

lemma ei_nonneg (T : TPM ι Q) (S : Finset ι) (s : ι → Q) : 0 ≤ ei T S s := by
  have key : ∀ a : Part S → Q, ∀ b : CoPart S → Q,
      joint T S s a b - margA T S s a * margB T S s b
        ≤ joint T S s a b * Real.log (joint T S s a b / (margA T S s a * margB T S s b)) := by
    intro a b
    refine gibbs_pointwise (joint_nonneg T S s a b)
      (mul_nonneg (margA_nonneg T S s a) (margB_nonneg T S s b)) ?_
    intro hpos
    exact mul_pos (lt_of_lt_of_le hpos (le_margA T S s a b))
      (lt_of_lt_of_le hpos (le_margB T S s a b))
  have hsum : ∑ a : Part S → Q, ∑ b : CoPart S → Q,
      (joint T S s a b - margA T S s a * margB T S s b) ≤ ei T S s := by
    refine Finset.sum_le_sum fun a _ => Finset.sum_le_sum fun b _ => key a b
  have hzero : ∑ a : Part S → Q, ∑ b : CoPart S → Q,
      (joint T S s a b - margA T S s a * margB T S s b) = 0 := by
    simp only [Finset.sum_sub_distrib]
    rw [sum_joint, sum_prod_marg, sub_self]
  linarith [hsum, hzero.symm.le, hzero.le]

lemma ei_eq_zero_of_disconnected (T : TPM ι Q) (S : Finset ι) (h : Disconnected T S)
    (s : ι → Q) : ei T S s = 0 := by
  obtain ⟨f, g, hfg⟩ := h
  -- the joint distribution factorizes
  have hj : ∀ (a : Part S → Q) (b : CoPart S → Q),
      joint T S s a b = f (restA S s) a * g (restB S s) b := by
    intro a b
    have := hfg s ((splitEquiv S).symm (a, b))
    have ha : restA S ((splitEquiv S).symm (a, b)) = a := by
      funext i; simp [restA, splitEquiv, Equiv.piEquivPiSubtypeProd, i.2]
    have hb : restB S ((splitEquiv S).symm (a, b)) = b := by
      funext i; simp [restB, splitEquiv, Equiv.piEquivPiSubtypeProd, i.2]
    rw [joint, this, ha, hb]
  set F : (Part S → Q) → ℝ := fun a => f (restA S s) a with hF
  set G : (CoPart S → Q) → ℝ := fun b => g (restB S s) b with hG
  have hsumF : ∑ a : Part S → Q, F a * (∑ b : CoPart S → Q, G b) = 1 := by
    have := sum_joint T S s
    rw [← this]
    refine Finset.sum_congr rfl fun a _ => ?_
    rw [Finset.mul_sum]
    exact Finset.sum_congr rfl fun b _ => by rw [hj a b]
  have hFG : (∑ a : Part S → Q, F a) * (∑ b : CoPart S → Q, G b) = 1 := by
    rw [Finset.sum_mul]
    simpa using hsumF
  have hmA : ∀ a, margA T S s a = F a * (∑ b : CoPart S → Q, G b) := by
    intro a
    rw [margA, Finset.mul_sum]
    exact Finset.sum_congr rfl fun b _ => by rw [hj a b]
  have hmB : ∀ b, margB T S s b = (∑ a : Part S → Q, F a) * G b := by
    intro b
    rw [margB, Finset.sum_mul]
    exact Finset.sum_congr rfl fun a _ => by rw [hj a b]
  have hprod : ∀ a b, margA T S s a * margB T S s b = joint T S s a b := by
    intro a b
    rw [hmA a, hmB b, hj a b]
    calc F a * (∑ b : CoPart S → Q, G b) * ((∑ a : Part S → Q, F a) * G b)
        = (F a * G b) * ((∑ a : Part S → Q, F a) * (∑ b : CoPart S → Q, G b)) := by ring
      _ = F a * G b := by rw [hFG, mul_one]
  rw [ei]
  refine Finset.sum_eq_zero fun a _ => Finset.sum_eq_zero fun b _ => ?_
  rw [hprod a b]
  rcases eq_or_ne (joint T S s a b) 0 with h0 | h0
  · rw [h0, zero_mul]
  · rw [div_self h0, Real.log_one, mul_zero]

lemma EI_nonneg (T : TPM ι Q) (S : Finset ι) : 0 ≤ EI T S := by
  refine div_nonneg (Finset.sum_nonneg fun s _ => ei_nonneg T S s) ?_
  positivity

lemma EI_eq_zero_of_disconnected (T : TPM ι Q) (S : Finset ι) (h : Disconnected T S) :
    EI T S = 0 := by
  rw [EI]
  rw [Finset.sum_congr rfl fun s _ => ei_eq_zero_of_disconnected T S h s]
  simp

/-! ## Main theorem -/

/-- **Integrated information vanishes for a disconnected system.**

`Φ` is defined as the minimum, over all nontrivial bipartitions `(S, Sᶜ)` of the system, of the
effective information `EI` generated across that bipartition — the Kullback–Leibler divergence
between the system's actual next-state distribution and the product of the next-state
distributions of the two parts, averaged over current states with the uniform prior.

If the system is disconnected, i.e. there is a nontrivial bipartition along which its dynamics
factorize (neither side has any causal influence on the other), then `Φ = 0`. -/
theorem iit_phi_partition (T : TPM ι Q) (S : Finset ι)
    (hS : S.Nonempty) (hSne : S ≠ Finset.univ) (hdis : Disconnected T S) :
    Phi T = 0 := by
  have hmem : (0 : ℝ) ∈ (fun S => EI T S) '' Bipartitions ι :=
    ⟨S, ⟨hS, hSne⟩, EI_eq_zero_of_disconnected T S hdis⟩
  have hbdd : BddBelow ((fun S => EI T S) '' Bipartitions ι) := by
    refine ⟨0, ?_⟩
    rintro x ⟨S', -, rfl⟩
    exact EI_nonneg T S'
  refine le_antisymm (csInf_le hbdd hmem) ?_
  refine le_csInf ⟨0, hmem⟩ ?_
  rintro x ⟨S', -, rfl⟩
  exact EI_nonneg T S'

/-! ## Strict positivity: `Φ` detects genuine integration -/

/-- Strict pointwise Gibbs inequality. -/
lemma gibbs_pointwise_strict {p q : ℝ} (hp : 0 ≤ p) (hq : 0 ≤ q) (hpq : 0 < p → 0 < q)
    (hne : p ≠ q) : p - q < p * Real.log (p / q) := by
  rcases eq_or_lt_of_le hp with hp0 | hp0
  · have hq0 : 0 < q := lt_of_le_of_ne hq (by simpa [← hp0, eq_comm] using hne)
    simp [← hp0, hq0]
  · have hq0 : 0 < q := hpq hp0
    have hx : q / p ≠ 1 := by
      intro hx
      rw [div_eq_one_iff_eq (ne_of_gt hp0)] at hx
      exact hne hx.symm
    have hlog : Real.log (q / p) < q / p - 1 :=
      Real.log_lt_sub_one_of_pos (div_pos hq0 hp0) hx
    have hrw : Real.log (q / p) = -Real.log (p / q) := by
      rw [← Real.log_inv]
      congr 1
      field_simp
    rw [hrw] at hlog
    have h := mul_lt_mul_of_pos_left hlog hp0
    have hpq' : p * (q / p - 1) = q - p := by field_simp
    rw [hpq'] at h
    linarith

/-- If the actual next-state distribution differs from the product of the two parts'
next-state distributions, the effective information across that bipartition is positive. -/
lemma ei_pos_of_ne (T : TPM ι Q) (S : Finset ι) (s : ι → Q)
    (a₀ : Part S → Q) (b₀ : CoPart S → Q)
    (hne : joint T S s a₀ b₀ ≠ margA T S s a₀ * margB T S s b₀) : 0 < ei T S s := by
  have hle : ∀ (a : Part S → Q) (b : CoPart S → Q),
      joint T S s a b - margA T S s a * margB T S s b
        ≤ joint T S s a b * Real.log (joint T S s a b / (margA T S s a * margB T S s b)) := by
    intro a b
    refine gibbs_pointwise (joint_nonneg T S s a b)
      (mul_nonneg (margA_nonneg T S s a) (margB_nonneg T S s b)) ?_
    intro hpos
    exact mul_pos (lt_of_lt_of_le hpos (le_margA T S s a b))
      (lt_of_lt_of_le hpos (le_margB T S s a b))
  have hlt : joint T S s a₀ b₀ - margA T S s a₀ * margB T S s b₀
      < joint T S s a₀ b₀ *
        Real.log (joint T S s a₀ b₀ / (margA T S s a₀ * margB T S s b₀)) := by
    refine gibbs_pointwise_strict (joint_nonneg T S s a₀ b₀)
      (mul_nonneg (margA_nonneg T S s a₀) (margB_nonneg T S s b₀)) ?_ hne
    intro hpos
    exact mul_pos (lt_of_lt_of_le hpos (le_margA T S s a₀ b₀))
      (lt_of_lt_of_le hpos (le_margB T S s a₀ b₀))
  have hinner : ∀ a : Part S → Q,
      ∑ b : CoPart S → Q, (joint T S s a b - margA T S s a * margB T S s b)
        ≤ ∑ b : CoPart S → Q,
            joint T S s a b * Real.log (joint T S s a b / (margA T S s a * margB T S s b)) :=
    fun a => Finset.sum_le_sum fun b _ => hle a b
  have hinner0 :
      ∑ b : CoPart S → Q, (joint T S s a₀ b - margA T S s a₀ * margB T S s b)
        < ∑ b : CoPart S → Q,
            joint T S s a₀ b * Real.log (joint T S s a₀ b / (margA T S s a₀ * margB T S s b)) :=
    Finset.sum_lt_sum (fun b _ => hle a₀ b) ⟨b₀, Finset.mem_univ b₀, hlt⟩
  have hsum : ∑ a : Part S → Q, ∑ b : CoPart S → Q,
      (joint T S s a b - margA T S s a * margB T S s b) < ei T S s :=
    Finset.sum_lt_sum (fun a _ => hinner a) ⟨a₀, Finset.mem_univ a₀, hinner0⟩
  have hzero : ∑ a : Part S → Q, ∑ b : CoPart S → Q,
      (joint T S s a b - margA T S s a * margB T S s b) = 0 := by
    simp only [Finset.sum_sub_distrib]
    rw [sum_joint, sum_prod_marg, sub_self]
  linarith [hsum, hzero.le, hzero.ge]

lemma EI_pos_of_ne (T : TPM ι Q) (S : Finset ι) (s : ι → Q)
    (a₀ : Part S → Q) (b₀ : CoPart S → Q)
    (hne : joint T S s a₀ b₀ ≠ margA T S s a₀ * margB T S s b₀) : 0 < EI T S := by
  have hcard : (0 : ℝ) < (Fintype.card (ι → Q) : ℝ) := by
    have h0 : 0 < Fintype.card (ι → Q) := Fintype.card_pos_iff.mpr ⟨s⟩
    exact_mod_cast h0
  refine div_pos (Finset.sum_pos' (fun t _ => ei_nonneg T S t)
    ⟨s, Finset.mem_univ s, ei_pos_of_ne T S s a₀ b₀ hne⟩) hcard

/-- **Integrated information is positive for a genuinely integrated system.** If across every
nontrivial bipartition the system's dynamics fail to factorize at some state, then `Φ > 0`. -/
theorem phi_pos_of_irreducible (T : TPM ι Q) (hbip : (Bipartitions ι).Nonempty)
    (h : ∀ S ∈ Bipartitions ι, ∃ (s : ι → Q) (a : Part S → Q) (b : CoPart S → Q),
      joint T S s a b ≠ margA T S s a * margB T S s b) : 0 < Phi T := by
  have hmem : sInf ((fun S => EI T S) '' Bipartitions ι) ∈ (fun S => EI T S) '' Bipartitions ι :=
    Set.Nonempty.csInf_mem (hbip.image _) (Set.toFinite _ |>.image _)
  obtain ⟨S, hS, hEq⟩ := hmem
  obtain ⟨s, a, b, hne⟩ := h S hS
  rw [Phi, ← hEq]
  exact EI_pos_of_ne T S s a b hne

/-! ## A concrete instance, showing the hypotheses are satisfiable -/

/-- Two elements, two states each, evolving independently and uniformly at random:
a disconnected system. -/
noncomputable def uniformPairSystem : TPM (Fin 2) Bool where
  prob _ _ := 1 / 4
  nonneg := by intro s u; norm_num
  normalized := by
    intro s
    simp [Finset.sum_const, Finset.card_univ]

example : Phi uniformPairSystem = 0 := by
  refine iit_phi_partition uniformPairSystem {0} ⟨0, by simp⟩ ?_
    ⟨fun _ _ => 1 / 2, fun _ _ => 1 / 2, by intro s u; norm_num [uniformPairSystem]⟩
  intro h
  have h1 : (1 : Fin 2) ∈ ({0} : Finset (Fin 2)) := by rw [h]; exact Finset.mem_univ 1
  simp at h1

end Frontier

