import Mathlib

/-!
# Ratner
Category: Frontier Math
Target: Math2.ratner
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 400000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Math2

open MeasureTheory Topology

/-!
## Setting

We formalise Ratner's orbit-closure and (homogeneous) invariant-measure statements for
one-parameter unipotent flows in the **abelian** case, i.e. for a linear flow
`t ↦ x + f t` on a compact homogeneous space `X` of a connected abelian Lie group.
The model case is the linear flow with direction `v` on the torus `ℝⁿ / ℤⁿ`, which is
recorded below as `Math2.ratner_torus`.

The conclusions are exactly the conclusions of Ratner's theorems in this case:

* the closure of every orbit is the coset `x + H` of a **closed connected** subgroup `H`
  which contains the flow (orbit-closure theorem);
* the orbit closure carries an `H`-invariant, hence flow-invariant, probability measure,
  namely the image of the Haar probability measure of the compact group `H` (homogeneity
  of the natural invariant measure).
-/

section Abstract

variable {X : Type*} [TopologicalSpace X] [AddCommGroup X] [IsTopologicalAddGroup X]

/-- The orbit of `x` under the one-parameter flow `t ↦ x + f t`. -/
def flowOrbit (f : ℝ →+ X) (x : X) : Set X := {y | ∃ t : ℝ, y = x + f t}

/-- The group appearing in the orbit-closure theorem: the closed subgroup generated by the
one-parameter flow `f`. -/
def flowGroup (f : ℝ →+ X) : AddSubgroup X := (AddMonoidHom.range f).topologicalClosure

theorem flowGroup_isClosed (f : ℝ →+ X) : IsClosed (flowGroup f : Set X) :=
  AddSubgroup.isClosed_topologicalClosure _

theorem mem_flowGroup (f : ℝ →+ X) (t : ℝ) : f t ∈ flowGroup f :=
  AddSubgroup.le_topologicalClosure _ ⟨t, rfl⟩

theorem flowGroup_isConnected (f : ℝ →+ X) (hf : Continuous f) :
    IsConnected (flowGroup f : Set X) := by
  rw [flowGroup, AddSubgroup.topologicalClosure_coe]
  exact (isConnected_range hf).closure

/-- Orbit-closure statement: the closure of the orbit of `x` is the coset `x + H` of the
closed subgroup `H` generated by the flow. -/
theorem closure_flowOrbit (f : ℝ →+ X) (x : X) :
    closure (flowOrbit f x) = (fun h => x + h) '' (flowGroup f : Set X) := by
  have h1 :
      flowOrbit f x = (fun h => x + h) '' ((AddMonoidHom.range f : AddSubgroup X) : Set X) := by
    ext y
    constructor
    · rintro ⟨t, rfl⟩
      exact ⟨f t, ⟨t, rfl⟩, rfl⟩
    · rintro ⟨h, ⟨t, rfl⟩, rfl⟩
      exact ⟨t, rfl⟩
  rw [h1, flowGroup, AddSubgroup.topologicalClosure_coe]
  exact ((Homeomorph.addLeft x).image_closure _).symm

/-- Every coset of a closed subgroup `H` of a compact group carries an `H`-invariant
probability measure, obtained by transporting the Haar probability measure of `H`. -/
theorem exists_invariant_probabilityMeasure_of_isClosed [CompactSpace X] [MeasurableSpace X]
    [BorelSpace X] (H : AddSubgroup X) (hH : IsClosed (H : Set X)) (x : X) :
    ∃ μ : Measure X, IsProbabilityMeasure μ ∧
      μ ((fun h => x + h) '' (H : Set X)) = 1 ∧
      ∀ h ∈ H, μ.map (fun y => y + h) = μ := by
  haveI : CompactSpace ↥H := isCompact_iff_compactSpace.mp hH.isCompact
  set ν : Measure ↥H := Measure.addHaarMeasure ⊤ with hν
  have hνuniv : ν Set.univ = 1 := by
    have h := MeasureTheory.Measure.addHaarMeasure_self (G := ↥H) (K₀ := ⊤)
    simpa using h
  set tmap : ↥H → X := fun h => x + (h : X) with htmap
  have htmapm : Measurable tmap := (continuous_const.add continuous_subtype_val).measurable
  refine ⟨ν.map tmap, ⟨?_⟩, ?_, ?_⟩
  · rw [Measure.map_apply htmapm MeasurableSet.univ]
    simpa using hνuniv
  · refine le_antisymm ?_ ?_
    · calc (ν.map tmap) ((fun h => x + h) '' (H : Set X)) ≤ (ν.map tmap) Set.univ :=
            measure_mono (Set.subset_univ _)
        _ = 1 := by rw [Measure.map_apply htmapm MeasurableSet.univ]; simpa using hνuniv
    · have hpre : tmap ⁻¹' ((fun h => x + h) '' (H : Set X)) = Set.univ := by
        ext a
        simp only [Set.mem_preimage, Set.mem_univ, iff_true, htmap]
        exact ⟨(a : X), a.2, rfl⟩
      calc (1 : ENNReal) = ν (tmap ⁻¹' ((fun h => x + h) '' (H : Set X))) := by rw [hpre, hνuniv]
        _ ≤ (ν.map tmap) _ := Measure.le_map_apply htmapm.aemeasurable _
  · intro h hh
    have hmap : Measurable fun y : X => y + h := (continuous_id.add continuous_const).measurable
    have hshift : Measurable fun a : ↥H => a + (⟨h, hh⟩ : ↥H) :=
      (continuous_id.add continuous_const).measurable
    rw [Measure.map_map hmap htmapm]
    have hcomp : (fun y : X => y + h) ∘ tmap = tmap ∘ (fun a : ↥H => a + ⟨h, hh⟩) := by
      funext a
      simp [htmap, add_assoc]
    rw [hcomp, ← Measure.map_map htmapm hshift]
    congr 1
    exact map_add_right_eq_self ν _

end Abstract

/-- **Ratner's theorems, abelian case.**

Let `t ↦ x + f t` be a one-parameter (unipotent) flow on a compact homogeneous space `X`
of a connected abelian Lie group — the model case being a linear flow on a torus `ℝⁿ / L`,
see `Math2.ratner_torus`. Then there is a *closed connected* subgroup `H ≤ X` containing the
whole flow such that:

* the orbit closure of `x` is the coset `x + H` (orbit-closure theorem), and
* the orbit closure carries an `H`-invariant — in particular flow-invariant — probability
  measure `μ`, i.e. the invariant measure of the flow on the orbit closure is the
  homogeneous (Haar) measure of `x + H` (measure classification in this setting). -/
theorem ratner {X : Type*} [TopologicalSpace X] [AddCommGroup X] [IsTopologicalAddGroup X]
    [CompactSpace X] [MeasurableSpace X] [BorelSpace X] (f : ℝ →+ X) (hf : Continuous f) (x : X) :
    ∃ H : AddSubgroup X,
      IsClosed (H : Set X) ∧ IsConnected (H : Set X) ∧ (∀ t : ℝ, f t ∈ H) ∧
      closure (flowOrbit f x) = (fun h => x + h) '' (H : Set X) ∧
      ∃ μ : Measure X, IsProbabilityMeasure μ ∧
        μ (closure (flowOrbit f x)) = 1 ∧
        (∀ h ∈ H, μ.map (fun y => y + h) = μ) ∧
        (∀ t : ℝ, μ.map (fun y => y + f t) = μ) := by
  obtain ⟨μ, hμ, hμ1, hμinv⟩ :=
    exists_invariant_probabilityMeasure_of_isClosed (flowGroup f) (flowGroup_isClosed f) x
  refine ⟨flowGroup f, flowGroup_isClosed f, flowGroup_isConnected f hf, mem_flowGroup f,
    closure_flowOrbit f x, μ, hμ, ?_, hμinv, fun t => hμinv _ (mem_flowGroup f t)⟩
  rw [closure_flowOrbit f x]
  exact hμ1

/-- The `n`-dimensional torus `ℝⁿ / ℤⁿ`, written as a product of circles `ℝ / ℤ`. -/
abbrev Torus (n : ℕ) : Type := Fin n → AddCircle (1 : ℝ)

/-- The linear (unipotent) flow on the torus `ℝⁿ / ℤⁿ` with direction vector `v`. -/
noncomputable def torusFlow {n : ℕ} (v : Fin n → ℝ) : ℝ →+ Torus n where
  toFun := fun t i => ((t * v i : ℝ) : AddCircle (1 : ℝ))
  map_zero' := by funext i; simp
  map_add' := by
    intro a b
    funext i
    simp [add_mul]

theorem torusFlow_continuous {n : ℕ} (v : Fin n → ℝ) : Continuous (torusFlow v) := by
  apply continuous_pi
  intro i
  exact (AddCircle.continuous_mk' (1 : ℝ)).comp (by fun_prop)

/-- **Ratner's theorems for a linear flow on the torus `ℝⁿ / ℤⁿ`.**

The closure of the orbit `{x + t·v mod ℤⁿ : t ∈ ℝ}` is the coset `x + H` of a closed
connected subgroup `H` of the torus containing the flow, and it carries an `H`-invariant
(hence flow-invariant) probability measure. -/
theorem ratner_torus {n : ℕ} (v : Fin n → ℝ) (x : Torus n) :
    ∃ H : AddSubgroup (Torus n),
      IsClosed (H : Set (Torus n)) ∧ IsConnected (H : Set (Torus n)) ∧
      (∀ t : ℝ, torusFlow v t ∈ H) ∧
      closure (flowOrbit (torusFlow v) x) = (fun h => x + h) '' (H : Set (Torus n)) ∧
      ∃ μ : Measure (Torus n), IsProbabilityMeasure μ ∧
        μ (closure (flowOrbit (torusFlow v) x)) = 1 ∧
        (∀ h ∈ H, μ.map (fun y => y + h) = μ) ∧
        (∀ t : ℝ, μ.map (fun y => y + torusFlow v t) = μ) :=
  ratner (torusFlow v) (torusFlow_continuous v) x

end Math2

