import Mathlib

/-!
# Mordell Finite Generation
Category: Frontier — Prime Numbers
Target: Frontier.Mordell_finite_generation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Frontier

open scoped Classical

/-- Multiplication by `m : ℕ` on an additive commutative group, as a group homomorphism. -/
def nsmulHom (A : Type*) [AddCommGroup A] (m : ℕ) : A →+ A :=
  AddMonoidHom.mk' (fun a => m • a) (fun a b => smul_add m a b)

@[simp] lemma nsmulHom_apply {A : Type*} [AddCommGroup A] (m : ℕ) (a : A) :
    nsmulHom A m a = m • a := rfl

/-- The subgroup `mA` of `m`-th multiples of elements of `A`. -/
def multiples (A : Type*) [AddCommGroup A] (m : ℕ) : AddSubgroup A :=
  (nsmulHom A m).range

lemma mem_multiples_iff {A : Type*} [AddCommGroup A] {m : ℕ} {a : A} :
    a ∈ multiples A m ↔ ∃ b : A, m • b = a := Iff.rfl

/-! ## Coset representatives coming from finiteness of `A / mA` -/

/-- If `A / mA` is finite, then there is a finite set of coset representatives: every `P ∈ A` can
be written as `P = m • P' + Q` with `Q` in a fixed finite set. -/
lemma exists_finite_representatives {A : Type*} [AddCommGroup A] (m : ℕ)
    (hquot : Finite (A ⧸ multiples A m)) :
    ∃ R : Set A, R.Finite ∧ ∀ P : A, ∃ Q ∈ R, ∃ P' : A, P = m • P' + Q := by
  classical
  refine ⟨Set.range (fun q : A ⧸ multiples A m => Quotient.out q), Set.finite_range _, ?_⟩
  intro P
  refine ⟨Quotient.out (QuotientAddGroup.mk' (multiples A m) P), ⟨_, rfl⟩, ?_⟩
  set Q : A := Quotient.out (QuotientAddGroup.mk' (multiples A m) P) with hQ
  have hmk : (QuotientAddGroup.mk' (multiples A m)) Q
      = (QuotientAddGroup.mk' (multiples A m)) P := by
    rw [hQ]
    exact Quotient.out_eq _
  have : P - Q ∈ multiples A m := by
    have : (QuotientAddGroup.mk' (multiples A m)) (P - Q) = 0 := by
      rw [map_sub, hmk, sub_self]
    exact (QuotientAddGroup.eq_zero_iff _).mp this
  obtain ⟨P', hP'⟩ := this
  exact ⟨P', by rw [show m • P' = P - Q from hP']; abel⟩

/-! ## The descent theorem -/

/-- **Descent theorem** (Silverman, *The Arithmetic of Elliptic Curves*, VIII.3.1).
Let `A` be an abelian group equipped with a "height" function `h : A → ℝ` such that

* for every `Q : A` there is a constant `C` with `h (P + Q) ≤ 2 * h P + C` for all `P`;
* there is `m ≥ 2` and a constant `C` with `m ^ 2 * h P - C ≤ h (m • P)` for all `P`;
* for every bound `C` the set `{P | h P ≤ C}` is finite;

and such that the quotient `A / mA` is finite. Then `A` is a finitely generated group. -/
theorem fg_of_descent {A : Type*} [AddCommGroup A] (m : ℕ) (hm : 2 ≤ m)
    (hquot : Finite (A ⧸ multiples A m))
    (h : A → ℝ)
    (hadd : ∀ Q : A, ∃ C : ℝ, ∀ P : A, h (P + Q) ≤ 2 * h P + C)
    (hmul : ∃ C : ℝ, ∀ P : A, (m : ℝ) ^ 2 * h P - C ≤ h (m • P))
    (hbdd : ∀ C : ℝ, {P : A | h P ≤ C}.Finite) :
    AddGroup.FG A := by
  classical
  obtain ⟨R, hRfin, hR⟩ := exists_finite_representatives m hquot
  obtain ⟨C₂, hC₂⟩ := hmul
  -- a uniform constant `C₁` working for all the (negatives of the) representatives
  choose g hg using hadd
  have hbddA : BddAbove ((fun Q => g (-Q)) '' R) := (hRfin.image _).bddAbove
  obtain ⟨C₁, hC₁⟩ := hbddA
  set C : ℝ := max 0 (C₁ + C₂) with hC
  have hC0 : 0 ≤ C := le_max_left _ _
  have hCle : C₁ + C₂ ≤ C := le_max_right _ _
  set B : ℝ := C + 3 with hB
  -- the finite generating set
  set S : Set A := R ∪ {P : A | h P ≤ B} with hS
  have hSfin : S.Finite := hRfin.union (hbdd B)
  -- the key descent step
  have key : ∀ P : A, 0 ≤ h P → ∃ Q ∈ R, ∃ P' : A, P = m • P' + Q ∧ h P' ≤ h P / 2 + C / 4 := by
    intro P hP0
    obtain ⟨Q, hQR, P', hP'⟩ := hR P
    refine ⟨Q, hQR, P', hP', ?_⟩
    have h1 : h (m • P') ≤ 2 * h P + g (-Q) := by
      have : m • P' = P + -Q := by rw [hP']; abel
      rw [this]
      exact hg (-Q) P
    have h2 : g (-Q) ≤ C₁ := hC₁ ⟨Q, hQR, rfl⟩
    have h3 : (m : ℝ) ^ 2 * h P' - C₂ ≤ h (m • P') := hC₂ P'
    have h4 : (m : ℝ) ^ 2 * h P' ≤ 2 * h P + (C₁ + C₂) := by linarith
    have hm4 : (4 : ℝ) ≤ (m : ℝ) ^ 2 := by
      have : (2 : ℝ) ≤ (m : ℝ) := by exact_mod_cast hm
      nlinarith
    rcases le_or_gt (h P') 0 with hneg | hpos
    · nlinarith
    · nlinarith
  -- every point lies in the subgroup generated by `S`
  have main : ∀ n : ℕ, ∀ P : A, h P ≤ (n : ℝ) → P ∈ AddSubgroup.closure S := by
    intro n
    induction n using Nat.strong_induction_on with
    | _ n ih =>
      intro P hPn
      rcases le_or_gt (h P) B with hle | hgt
      · exact AddSubgroup.subset_closure (Or.inr hle)
      · have hP0 : 0 ≤ h P := by simp only [hB] at hgt; linarith
        obtain ⟨Q, hQR, P', hPeq, hP'le⟩ := key P hP0
        have hn2 : (2 : ℝ) + C / 2 ≤ (n : ℝ) := by
          simp only [hB] at hgt
          linarith
        have hn1 : 1 ≤ n := by
          have h1 : (1 : ℝ) ≤ (n : ℝ) := by linarith
          exact_mod_cast h1
        set k : ℕ := n - 1 with hk
        have hkn : k < n := by omega
        have hkcast : (k : ℝ) = (n : ℝ) - 1 := by
          have : (k : ℕ) + 1 = n := by omega
          have := congrArg (fun t : ℕ => (t : ℝ)) this
          push_cast at this
          linarith
        have hP'k : h P' ≤ (k : ℝ) := by
          rw [hkcast]
          linarith
        have := ih k hkn P' hP'k
        rw [hPeq]
        exact AddSubgroup.add_mem _ (AddSubgroup.nsmul_mem _ this m)
          (AddSubgroup.subset_closure (Or.inl hQR))
  rw [AddGroup.fg_iff]
  refine ⟨S, ?_, hSfin⟩
  rw [eq_top_iff]
  intro P _
  exact main ⌈h P⌉₊ P (Nat.le_ceil _)

/-! ## Non-vacuity: the descent hypotheses are satisfiable

The hypotheses of `Frontier.fg_of_descent` are not vacuous: they hold, for instance, for the group
`ℤ` with the height `h n = n ^ 2` and `m = 2`, and the descent theorem then recovers the
(independently obvious) fact that `ℤ` is finitely generated. -/

lemma finite_quotient_int_two : Finite (ℤ ⧸ multiples ℤ 2) := by
  have hsurj : Function.Surjective
      (fun i : Fin 2 => (QuotientAddGroup.mk' (multiples ℤ 2)) (i : ℤ)) := by
    intro q
    induction q using QuotientAddGroup.induction_on with
    | _ n =>
      rcases Int.even_or_odd n with ⟨k, hk⟩ | ⟨k, hk⟩
      · refine ⟨0, ?_⟩
        simp only [QuotientAddGroup.mk'_apply]
        rw [QuotientAddGroup.eq_iff_sub_mem]
        exact ⟨-k, by simp [nsmulHom]; omega⟩
      · refine ⟨1, ?_⟩
        simp only [QuotientAddGroup.mk'_apply]
        rw [QuotientAddGroup.eq_iff_sub_mem]
        exact ⟨-k, by simp [nsmulHom]; omega⟩
  exact Finite.of_surjective _ hsurj

lemma finite_sublevel_int_sq (C : ℝ) : {n : ℤ | ((n : ℝ)) ^ 2 ≤ C}.Finite := by
  apply Set.Finite.subset (Set.finite_Icc (-⌈max 1 C⌉) ⌈max 1 C⌉)
  intro n hn
  simp only [Set.mem_setOf_eq] at hn
  have habs : |(n : ℝ)| ≤ (n : ℝ) ^ 2 ∨ |(n : ℝ)| ≤ 1 := by
    rcases le_or_gt |(n : ℝ)| 1 with h | h
    · exact Or.inr h
    · exact Or.inl (by nlinarith [sq_abs ((n : ℝ))])
  have h1 : |(n : ℝ)| ≤ max 1 C := by
    rcases habs with h | h
    · exact (h.trans hn).trans (le_max_right _ _)
    · exact h.trans (le_max_left _ _)
  have h2 : (|n| : ℝ) ≤ ((⌈max 1 C⌉ : ℤ) : ℝ) := le_trans h1 (Int.le_ceil _)
  have h3 : |n| ≤ (⌈max 1 C⌉ : ℤ) := by exact_mod_cast h2
  rw [abs_le] at h3
  exact Set.mem_Icc.mpr ⟨h3.1, h3.2⟩

/-- A concrete instance of the descent theorem: `ℤ`, with height `n ↦ n ^ 2` and `m = 2`,
satisfies all the hypotheses of `Frontier.fg_of_descent`. -/
theorem fg_int_of_descent : AddGroup.FG ℤ := by
  refine fg_of_descent 2 le_rfl finite_quotient_int_two (fun n => ((n : ℝ)) ^ 2)
    (fun Q => ⟨2 * ((Q : ℝ)) ^ 2, fun P => by push_cast; nlinarith [sq_nonneg ((P : ℝ) - Q)]⟩)
    ⟨0, fun P => by
      have h : (((2 : ℕ) • P : ℤ) : ℝ) = 2 * (P : ℝ) := by simp
      show ((2 : ℕ) : ℝ) ^ 2 * ((P : ℝ)) ^ 2 - 0 ≤ (((2 : ℕ) • P : ℤ) : ℝ) ^ 2
      rw [h]; norm_num; nlinarith [sq_nonneg ((P : ℝ))]⟩ finite_sublevel_int_sq

/-! ## Mordell's theorem for elliptic curves over `ℚ` -/

/-- **Mordell's theorem** (reduction to the weak Mordell–Weil theorem and the theory of heights).

Let `W` be an elliptic curve over `ℚ` and let `W.toAffine.Point` be its group of rational points.
Assume:

* (weak Mordell–Weil) the quotient `E(ℚ) / m E(ℚ)` is finite for some `m ≥ 2`;
* there is a height function `h` on `E(ℚ)` satisfying the standard estimates: it is quasi-quadratic
  under translation by a fixed point and under multiplication by `m`, and has finite sublevel sets.

Then `E(ℚ)` is a finitely generated abelian group.

(The `W.IsElliptic` hypothesis is part of the statement of Mordell's theorem, even though the
descent argument below only uses the group structure on `W.toAffine.Point`, which Mathlib provides
for any Weierstrass curve over a field.) -/
theorem Mordell_finite_generation (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (m : ℕ) (hm : 2 ≤ m)
    (hweak : Finite (W.toAffine.Point ⧸ multiples W.toAffine.Point m))
    (h : W.toAffine.Point → ℝ)
    (hadd : ∀ Q : W.toAffine.Point, ∃ C : ℝ, ∀ P : W.toAffine.Point, h (P + Q) ≤ 2 * h P + C)
    (hmul : ∃ C : ℝ, ∀ P : W.toAffine.Point, (m : ℝ) ^ 2 * h P - C ≤ h (m • P))
    (hbdd : ∀ C : ℝ, {P : W.toAffine.Point | h P ≤ C}.Finite) :
    AddGroup.FG W.toAffine.Point :=
  fg_of_descent m hm hweak h hadd hmul hbdd

end Frontier

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

