/-
# Adiabatic Theorem
Category: Frontier Phys
Target: Phys.adiabatic_theorem
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise
open scoped NNReal

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 40000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Phys

open Set

/-- **Uniqueness for a linear ODE in a Banach algebra.**
If `X : ℝ → F` solves the linear differential equation `X' t = A t * X t` with continuous
coefficient `A` and vanishing initial datum, then `X` vanishes identically. -/
theorem linear_ode_eq_zero {F : Type*} [NormedRing F] [NormedAlgebra ℝ F]
    {A : ℝ → F} (hA : Continuous A) {X : ℝ → F}
    (hX : ∀ t, HasDerivAt X (A t * X t) t) (h0 : X 0 = 0) :
    ∀ t, X t = 0 := by
  intro t
  set b : ℝ := |t| + 1 with hb
  set a : ℝ := -b with ha
  have habs : |t| < b := by simp [hb]
  have ht : t ∈ Ioo a b := by
    constructor
    · have := neg_abs_le t
      have : -b < -|t| := by simpa using habs
      linarith [neg_abs_le t]
    · exact lt_of_le_of_lt (le_abs_self t) habs
  have ht0 : (0 : ℝ) ∈ Ioo a b := by
    have h1 : (0 : ℝ) < b := by positivity
    exact ⟨by simpa [ha] using h1, h1⟩
  -- a uniform bound for `‖A ·‖` on the compact interval `[a, b]`
  obtain ⟨x₀, -, hx₀⟩ : ∃ x ∈ Icc a b, ∀ y ∈ Icc a b, ‖A y‖ ≤ ‖A x‖ :=
    let ⟨x, hx, hmax⟩ := IsCompact.exists_isMaxOn (isCompact_Icc (a := a) (b := b))
      ⟨0, ht0.1.le, ht0.2.le⟩ hA.norm.continuousOn
    ⟨x, hx, fun y hy => hmax hy⟩
  set C : ℝ≥0 := ⟨‖A x₀‖, norm_nonneg _⟩ with hC
  have hlip : ∀ s ∈ Ioo a b, LipschitzOnWith C (fun x : F => A s * x) (univ : Set F) := by
    intro s hs
    refine (LipschitzWith.of_dist_le_mul ?_).lipschitzOnWith
    intro x y
    have h1 : ‖A s * x - A s * y‖ ≤ ‖A s‖ * ‖x - y‖ := by
      rw [← mul_sub]; exact norm_mul_le _ _
    have h2 : ‖A s‖ ≤ (C : ℝ) := hx₀ s ⟨hs.1.le, hs.2.le⟩
    calc dist (A s * x) (A s * y) = ‖A s * x - A s * y‖ := dist_eq_norm _ _
      _ ≤ ‖A s‖ * ‖x - y‖ := h1
      _ ≤ (C : ℝ) * ‖x - y‖ := by
          exact mul_le_mul_of_nonneg_right h2 (norm_nonneg _)
      _ = (C : ℝ) * dist x y := by rw [dist_eq_norm]
  have key : EqOn X (fun _ : ℝ => (0 : F)) (Ioo a b) := by
    refine ODE_solution_unique_of_mem_Ioo (v := fun s x => A s * x) (s := fun _ => univ)
      hlip ht0 (fun s _ => ⟨hX s, mem_univ _⟩) (fun s _ => ⟨?_, mem_univ _⟩) (by simpa using h0)
    simpa using (hasDerivAt_const s (0 : F))
  simpa using key ht

/-- If `p` is an idempotent in a ring and `d` satisfies the Leibniz identity coming from
differentiating `p * p = p`, then `p * d * p = 0`. -/
theorem idem_deriv_sandwich {R : Type*} [Ring R] {p d : R} (hp : p * p = p)
    (hd : d * p + p * d = d) : p * d * p = 0 := by
  have h := congrArg (fun x => p * x) hd
  simp only [mul_add, ← mul_assoc, hp] at h
  simpa using h

/-- The defining algebraic property of **Kato's generator** `[d, p] = d * p - p * d`:
its commutator with `p` reproduces `-d`. -/
theorem kato_commutator {R : Type*} [Ring R] {p d : R} (hp : p * p = p)
    (hd : d * p + p * d = d) :
    p * (d * p - p * d) - (d * p - p * d) * p = -d := by
  have h0 : p * d * p = 0 := idem_deriv_sandwich hp hd
  calc p * (d * p - p * d) - (d * p - p * d) * p
      = p * d * p + p * d * p - p * p * d - d * (p * p) := by noncomm_ring
    _ = -(d * p + p * d) := by rw [h0, hp]; abel
    _ = -d := by rw [hd]

section

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]

/-- **Adiabatic theorem (Kato).**

Set-up.  `H s` is a time-dependent Hamiltonian on a complex Banach space `E`, and `P s` is the
spectral projection onto a *nondegenerate* (one-dimensional) instantaneous eigenspace of `H s`
with instantaneous eigenvalue `e s`; this is expressed by `H s * P s = e s • P s`,
`P s * H s = e s • P s`, `P s * P s = P s` and the nondegeneracy hypothesis `hnondeg`.
The projection family is assumed to be continuously differentiable, with derivative `dP`.

The adiabatic (slow) dynamics with adiabaticity parameter `ε > 0` is the evolution `U`
generated by the Schrödinger term `-(I/ε) • H s` together with Kato's geometric term
`[dP s, P s] = dP s * P s - P s * dP s`, which is precisely the generator obtained in the
slow (adiabatic) limit of the Schrödinger equation `i ε ψ' = H ψ`.

Conclusion.  A state `ψ₀` that starts in the eigenspace (`P 0 ψ₀ = ψ₀`) stays in the
instantaneous eigenspace for all times: `P s (U s ψ₀) = U s ψ₀`, and consequently it remains an
instantaneous eigenvector of `H s` with the instantaneous eigenvalue `e s`.

(The nondegeneracy hypothesis `hnondeg` and the positivity `hε` of the adiabaticity parameter are
stated because they are part of the physical statement, but they are not needed for the proof:
the conclusion holds for a spectral projection of any rank and for every nonzero `ε`.) -/
theorem adiabatic_theorem
    (H P dP : ℝ → (E →L[ℂ] E)) (e : ℝ → ℂ) (U : ℝ → (E →L[ℂ] E)) (ε : ℝ) (ψ₀ : E)
    (hH : Continuous H) (hdP : Continuous dP)
    (hP : ∀ s, HasDerivAt P (dP s) s)
    (hproj : ∀ s, P s * P s = P s)
    (heig : ∀ s, H s * P s = e s • P s)
    (heig' : ∀ s, P s * H s = e s • P s)
    (hnondeg : ∀ s, ∃ v : E, v ≠ 0 ∧ LinearMap.range (P s).toLinearMap = Submodule.span ℂ {v})
    (hε : 0 < ε)
    (hU0 : U 0 = 1)
    (hU : ∀ s, HasDerivAt U
      (((-(Complex.I / ε)) • H s + (dP s * P s - P s * dP s)) * U s) s)
    (hψ₀ : P 0 ψ₀ = ψ₀) :
    ∀ s, P s (U s ψ₀) = U s ψ₀ ∧ H s (U s ψ₀) = e s • U s ψ₀ := by
  -- the generator of the adiabatic evolution
  obtain ⟨A, hAdef⟩ : ∃ A : ℝ → (E →L[ℂ] E),
      ∀ s, A s = (-(Complex.I / ε)) • H s + (dP s * P s - P s * dP s) := ⟨_, fun _ => rfl⟩
  have hU' : ∀ s, HasDerivAt U (A s * U s) s := fun s => by rw [hAdef]; exact hU s
  have hPcont : Continuous P :=
    continuous_iff_continuousAt.mpr fun s => (hP s).continuousAt
  have hAcont : Continuous A := by
    have : A = fun s => (-(Complex.I / ε)) • H s + (dP s * P s - P s * dP s) := funext hAdef
    rw [this]
    exact (hH.const_smul _).add ((hdP.mul hPcont).sub (hPcont.mul hdP))
  -- Leibniz rule obtained by differentiating `P * P = P`
  have hPP : ∀ s, dP s * P s + P s * dP s = dP s := by
    intro s
    have h1 : HasDerivAt (fun u => P u * P u) (dP s * P s + P s * dP s) s := (hP s).mul (hP s)
    have hfun : (fun u => P u * P u) = P := funext hproj
    rw [hfun] at h1
    exact h1.unique (hP s)
  -- the Hamiltonian commutes with its spectral projection
  have hHcomm : ∀ s, P s * ((-(Complex.I / ε)) • H s) - ((-(Complex.I / ε)) • H s) * P s = 0 := by
    intro s
    rw [mul_smul_comm, smul_mul_assoc, heig' s, heig s, sub_self]
  -- the key identity `P' + [P, A] = 0`
  have hkey : ∀ s, P s * A s - A s * P s = -dP s := by
    intro s
    have expand : P s * A s - A s * P s
        = (P s * ((-(Complex.I / ε)) • H s) - ((-(Complex.I / ε)) • H s) * P s)
          + (P s * (dP s * P s - P s * dP s) - (dP s * P s - P s * dP s) * P s) := by
      rw [hAdef]; simp only [mul_add, add_mul]; abel
    rw [expand, hHcomm s, kato_commutator (hproj s) (hPP s), zero_add]
  -- the intertwiner defect solves a linear ODE with vanishing initial datum
  have hXderiv : ∀ s, HasDerivAt (fun u => P u * U u - U u * P 0)
      (A s * (P s * U s - U s * P 0)) s := by
    intro s
    have h1 : HasDerivAt (fun u => P u * U u) (dP s * U s + P s * (A s * U s)) s :=
      (hP s).mul (hU' s)
    have h2 : HasDerivAt (fun u => U u * P 0) ((A s * U s) * P 0 + U s * 0) s :=
      (hU' s).mul (hasDerivAt_const s (P 0))
    have h3 := h1.sub h2
    have halg : dP s * U s + P s * (A s * U s) - ((A s * U s) * P 0 + U s * 0)
        = A s * (P s * U s - U s * P 0) := by
      have hk := hkey s
      calc dP s * U s + P s * (A s * U s) - ((A s * U s) * P 0 + U s * 0)
          = A s * (P s * U s - U s * P 0) + (P s * A s - A s * P s + dP s) * U s := by
            noncomm_ring
        _ = A s * (P s * U s - U s * P 0) := by
            rw [hk, neg_add_cancel, zero_mul, add_zero]
    rwa [halg] at h3
  have hX0 : (fun u => P u * U u - U u * P 0) 0 = 0 := by simp [hU0]
  have hXzero := linear_ode_eq_zero hAcont hXderiv hX0
  have hPU : ∀ s, P s * U s = U s * P 0 := fun s => sub_eq_zero.mp (hXzero s)
  intro s
  have h1 : P s (U s ψ₀) = U s ψ₀ := by
    have h := congrArg (fun T : E →L[ℂ] E => T ψ₀) (hPU s)
    simpa [ContinuousLinearMap.mul_apply, hψ₀] using h
  refine ⟨h1, ?_⟩
  conv_lhs => rw [← h1]
  have h := congrArg (fun T : E →L[ℂ] E => T (U s ψ₀)) (heig s)
  simpa [ContinuousLinearMap.mul_apply, h1] using h

/-- **Adiabatic theorem, eigenvector form.**  In the setting of `Phys.adiabatic_theorem`, if
`v s` spans the one-dimensional instantaneous eigenspace at time `s`, then the adiabatically
evolved state is at all times a scalar multiple of `v s`: the state follows the instantaneous
nondegenerate eigenstate. -/
theorem adiabatic_theorem_eigenvector
    (H P dP : ℝ → (E →L[ℂ] E)) (e : ℝ → ℂ) (U : ℝ → (E →L[ℂ] E)) (ε : ℝ) (ψ₀ : E)
    (v : ℝ → E)
    (hH : Continuous H) (hdP : Continuous dP)
    (hP : ∀ s, HasDerivAt P (dP s) s)
    (hproj : ∀ s, P s * P s = P s)
    (heig : ∀ s, H s * P s = e s • P s)
    (heig' : ∀ s, P s * H s = e s • P s)
    (hnondeg : ∀ s, v s ≠ 0 ∧ LinearMap.range (P s).toLinearMap = Submodule.span ℂ {v s})
    (hε : 0 < ε)
    (hU0 : U 0 = 1)
    (hU : ∀ s, HasDerivAt U
      (((-(Complex.I / ε)) • H s + (dP s * P s - P s * dP s)) * U s) s)
    (hψ₀ : P 0 ψ₀ = ψ₀) :
    ∀ s, ∃ z : ℂ, U s ψ₀ = z • v s := by
  intro s
  have hmain := adiabatic_theorem H P dP e U ε ψ₀ hH hdP hP hproj heig heig'
    (fun s => ⟨v s, (hnondeg s).1, (hnondeg s).2⟩) hε hU0 hU hψ₀ s
  have hmem : U s ψ₀ ∈ LinearMap.range (P s).toLinearMap := ⟨U s ψ₀, hmain.1⟩
  rw [(hnondeg s).2, Submodule.mem_span_singleton] at hmem
  obtain ⟨z, hz⟩ := hmem
  exact ⟨z, hz.symm⟩

end

/-- A consistency (non-vacuity) check: the hypotheses of `Phys.adiabatic_theorem_eigenvector`
are satisfiable, here by the one-dimensional system with vanishing Hamiltonian. -/
example : ∀ s : ℝ, ∃ z : ℂ, (fun _ : ℝ => (1 : ℂ →L[ℂ] ℂ)) s (1 : ℂ) = z • (fun _ : ℝ => (1 : ℂ)) s := by
  refine adiabatic_theorem_eigenvector (fun _ => 0) (fun _ => 1) (fun _ => 0) (fun _ => 0)
    (fun _ => 1) 1 1 (fun _ => 1) continuous_const continuous_const
    (fun s => hasDerivAt_const s _) (fun s => by simp) (fun s => by simp) (fun s => by simp)
    (fun s => ⟨one_ne_zero, ?_⟩) one_pos rfl
    (fun s => by simpa using hasDerivAt_const s (1 : ℂ →L[ℂ] ℂ)) (by simp)
  exact le_antisymm (fun x _ => Submodule.mem_span_singleton.mpr ⟨x, by simp⟩)
    (fun x _ => ⟨x, by simp⟩)

end Phys

