import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

/-!
# Steane Code
Category: Frontier Qi
Target: QI.steane_code
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

/-
Formalization notes.

The 7-qubit Steane code is the CSS code built from the `[7,4,3]` Hamming code: its
stabilizer group is generated by three `X`-type generators and three `Z`-type
generators, whose supports are the rows of the Hamming parity-check matrix `H`.

A Pauli error on 7 qubits is described, up to an irrelevant global phase, by its
symplectic representation `(x, z) : Bits 7 × Bits 7`: qubit `i` carries an `X`
factor iff `x i = true` and a `Z` factor iff `z i = true` (so `x i = z i = true`
means a `Y` factor).  The error syndrome is the list of commutation relations of
the error with the stabilizer generators, which for a CSS code is exactly the pair
of Hamming syndromes `(H·x, H·z)`.

A stabilizer code corrects a set of errors precisely when the error is uniquely
determined by its syndrome (up to a stabilizer element, of which there are none of
weight `≤ 2` for the Steane code).  Accordingly, the theorem below exhibits an
explicit decoder `steaneDecode` and proves that it recovers *every* single-qubit
Pauli error `E` (arbitrary `X`, `Y`, `Z` or no error, on an arbitrary qubit) from
its syndrome, and that distinct single-qubit errors have distinct syndromes.

Everything is stated over `Bool` (the field with two elements), since the file is
required to begin with the header comment above and hence cannot carry an
`import` line.
-/

namespace QI

/-- Bit strings of length `n`, i.e. vectors over the two-element field. -/
abbrev Bits (n : Nat) := Fin n → Bool

/-- The parity-check matrix of the `[7,4,3]` Hamming code: the `q`-th column is
the binary expansion of `q + 1`. -/

theorem steane_decode_syndrome (E : PauliError) (hE : IsSingleQubitError E) :
    steaneDecode (steaneSyndrome E) = E := by
  obtain ⟨q, hq⟩ := hE
  have hEq := single_qubit_error_eq hq
  rw [hEq]
  exact Prod.ext (locate_parity_single q (E.1 q)) (locate_parity_single q (E.2 q))

/--
**The 7-qubit Steane code corrects any single-qubit error.**

For Pauli errors on 7 qubits, written in symplectic form `(x, z)`:

* the explicit syndrome decoder `steaneDecode` recovers every single-qubit error
  (an arbitrary `X`, `Y`, `Z`, or no error at all, on an arbitrary one of the seven
  qubits) from its stabilizer syndrome; consequently
* distinct single-qubit errors have distinct syndromes, which is exactly the
  Knill–Laflamme correctability condition for the (nondegenerate) stabilizer code
  with respect to the set of single-qubit errors.
-/
