/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1910ecc3-86ee-4c19-9869-d41f767f1221

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Complex Real

open scoped BigOperators

@[simp] def φ : ℝ := (1 + √5) / 2

@[simp] def ψ : ℝ := (1 - √5) / 2


theorem spiralPrime_norm (p : Nat.Primes) :
    ‖spiralPrime p‖ = p.val := by
      -- The norm of a complex exponential is 1 because it lies on the unit circle in the complex plane.
      have h_norm : ∀ t : ℝ, ‖Complex.exp (t * (1 + φ * Complex.I))‖ = Real.exp t := by
        norm_num [ Complex.norm_exp ];
      -- Substitute $t = \log p$ into the norm function.
      have h_subst : ‖spiralPrime p‖ = Real.exp (Real.log p.val) := by
        apply h_norm;
      -- Apply the fact that Real.exp (Real.log x) = x for any positive x.
      rw [h_subst, Real.exp_log (Nat.cast_pos.mpr p.prop.pos)]

