/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f0b78bcf-274f-436f-bbff-082df0f6c960
-/

/-
Formalization of the Partition Hilbert Space, D5 action, Prime Detector Operator, and Brockian System.

We define the Hilbert Space of Partitions `PartitionSpace` as a complex Euclidean space with dimension equal to the number of partitions of `n`.
We define a trivial action of the Dihedral Group `D5` on the set of partitions `d5PartitionPerm`.
We implement the Prime Detector Operator `primeDetectorOperator` as a rank-one operator scaled by the algebraic detector `F₂ n`.
We prove the Trace-Prime Identity `trace_prime_identity`, showing that `n` is prime if and only if the trace of the Prime Detector Operator is zero, assuming the Ono-MacMahon axioms.
Finally, we integrate this into a `BrockianSystem` and show that the Golden Projector filters the potential in `golden_projector_filters`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat
open Nat ArithmeticFunction Complex


theorem golden_projector_filters (n : ℕ) :
  let BS := brockianSystem n
  let P_phi := BS.projectors.projector .golden
  P_phi * BS.V * P_phi = 0 := by
  intro BS P_phi
  have : P_phi = 0 := rfl
  rw [this]
  simp
