/-
# Hironaka Resolution
Category: Frontier Math
Target: Math2.hironaka_resolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
-- (The header above uses `/-` rather than `/-!` only because Lean 4 does not permit a module
-- docstring to precede the `import` command; the same text is repeated as the module docstring
-- immediately after the imports below.)

import Mathlib

/-!
# Hironaka Resolution
Category: Frontier Math
Target: Math2.hironaka_resolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/


open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

universe u

namespace Math2

open Polynomial

/-!
## Resolution of singularities for monomial curve singularities

Full Hironaka resolution of singularities in characteristic zero is not formalized here (it is
not available in Mathlib in any form).  What is proved below is a genuine, complete special case
of it, in the classical dimension-one situation where resolution is achieved by normalization:

for coprime exponents `a, b ≥ 2` over a field `k` of characteristic zero, the affine monomial
curve `C_{a,b}` with coordinate ring `R = k[t^a, t^b] ⊆ k[t]` (the image of the parametrization
`t ↦ (t^a, t^b)`, i.e. the curve `y^a = x^b`) is singular, and the affine line `Spec k[t]`, which
is a *smooth* `k`-variety, together with the finite (hence proper) birational morphism
`Spec k[t] → C_{a,b}` dual to the inclusion `R ↪ k[t]`, is a resolution of its singularities.

The defining features of a resolution are recorded in `Math2.hironaka_resolution`:

* the resolving variety `Spec k[t]` is smooth over `k` (`Algebra.Smooth k k[X]`);
* the resolving morphism is finite, hence proper (`Module.Finite R k[X]`);
* it is birational: the subfield of `k(t)` generated by (the image of) `R` is all of `k(t)`;
* it is a nontrivial resolution: the curve really is singular.  This is witnessed both concretely
  (`t` is integral over `R` but does not lie in `R`) and abstractly: `R` is not integrally closed
  in its fraction field (`¬ IsIntegrallyClosed R`), i.e. the curve is not normal, hence not
  regular.

The characteristic zero hypothesis is part of the statement of Hironaka's theorem and is kept,
although this special case in fact holds over any field.
-/

/-- The coordinate ring `k[t^a, t^b] ⊆ k[t]` of the affine monomial curve `y^a = x^b`, i.e. the
image of the parametrization `t ↦ (t^a, t^b)`. -/

theorem adjoin_pow_eq_top (k : Type u) [Field k] (a b : ℕ) (ha : 0 < a) (hab : Nat.Coprime a b) :
    IntermediateField.adjoin k {(RatFunc.X : RatFunc k) ^ a, (RatFunc.X : RatFunc k) ^ b} = ⊤ := by
  obtain ⟨u, w, huw⟩ := exists_bezout_nat a b ha hab
  set F := IntermediateField.adjoin k {(RatFunc.X : RatFunc k) ^ a, (RatFunc.X : RatFunc k) ^ b}
    with hF
  have hXa : (RatFunc.X : RatFunc k) ^ a ∈ F := IntermediateField.subset_adjoin _ _ (by simp)
  have hXb : (RatFunc.X : RatFunc k) ^ b ∈ F := IntermediateField.subset_adjoin _ _ (by simp)
  have hX0 : (RatFunc.X : RatFunc k) ≠ 0 := RatFunc.X_ne_zero
  have hXmem : (RatFunc.X : RatFunc k) ∈ F := by
    have h1 : ((RatFunc.X : RatFunc k) ^ a) ^ u
        = RatFunc.X * ((RatFunc.X : RatFunc k) ^ b) ^ w := by
      rw [← pow_mul, ← pow_mul, huw, pow_add, pow_one]
    have h2 : ((RatFunc.X : RatFunc k) ^ b) ^ w ≠ 0 := pow_ne_zero _ (pow_ne_zero _ hX0)
    have h3 : (RatFunc.X : RatFunc k)
        = ((RatFunc.X : RatFunc k) ^ a) ^ u * (((RatFunc.X : RatFunc k) ^ b) ^ w)⁻¹ := by
      field_simp
      exact h1.symm
    rw [h3]
    exact F.mul_mem (F.pow_mem hXa u) (F.inv_mem (F.pow_mem hXb w))
  have hpoly : ∀ p : k[X], algebraMap k[X] (RatFunc k) p ∈ F := by
    intro p
    have hle : Algebra.adjoin k {(Polynomial.X : k[X])} ≤ Subalgebra.comap
        (IsScalarTower.toAlgHom k k[X] (RatFunc k)) F.toSubalgebra := by
      apply Algebra.adjoin_le
      rintro x rfl
      simpa [Subalgebra.mem_comap] using hXmem
    have hp : p ∈ Algebra.adjoin k {(Polynomial.X : k[X])} := by
      rw [Polynomial.adjoin_X]; trivial
    simpa [Subalgebra.mem_comap] using hle hp
  rw [eq_top_iff]
  rintro f -
  obtain ⟨x, y, -, rfl⟩ := IsFractionRing.div_surjective (A := k[X]) (K := RatFunc k) f
  exact F.div_mem (hpoly x) (hpoly y)

set_option synthInstance.maxHeartbeats 400000 in
/-- The coordinate ring `k[t^a, t^b]` of the monomial curve is **not** integrally closed in its
fraction field, when `a, b ≥ 2` are coprime: the element corresponding to `t` is integral over it
but does not belong to it.  Hence the curve `C_{a,b}` is not normal, and in particular (being a
one-dimensional variety) it is singular. -/
