/-
# Hironaka Resolution
Category: Frontier Math
Target: Math2.hironaka_resolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
-- (The header above uses `/-` rather than `/-!` only because Lean 4 does not permit a module
-- docstring to precede the `import` command; the same text is repeated as the module docstring
-- immediately after the imports below.)

import Mathlib

/-!
# Hironaka Resolution
Category: Frontier Math
Target: Math2.hironaka_resolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/


open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

universe u

namespace Math2

open Polynomial

/-!
## Resolution of singularities for monomial curve singularities

Full Hironaka resolution of singularities in characteristic zero is not formalized here (it is
not available in Mathlib in any form).  What is proved below is a genuine, complete special case
of it, in the classical dimension-one situation where resolution is achieved by normalization:

for coprime exponents `a, b ≥ 2` over a field `k` of characteristic zero, the affine monomial
curve `C_{a,b}` with coordinate ring `R = k[t^a, t^b] ⊆ k[t]` (the image of the parametrization
`t ↦ (t^a, t^b)`, i.e. the curve `y^a = x^b`) is singular, and the affine line `Spec k[t]`, which
is a *smooth* `k`-variety, together with the finite (hence proper) birational morphism
`Spec k[t] → C_{a,b}` dual to the inclusion `R ↪ k[t]`, is a resolution of its singularities.

The defining features of a resolution are recorded in `Math2.hironaka_resolution`:

* the resolving variety `Spec k[t]` is smooth over `k` (`Algebra.Smooth k k[X]`);
* the resolving morphism is finite, hence proper (`Module.Finite R k[X]`);
* it is birational: the subfield of `k(t)` generated by (the image of) `R` is all of `k(t)`;
* it is a nontrivial resolution: the curve really is singular.  This is witnessed both concretely
  (`t` is integral over `R` but does not lie in `R`) and abstractly: `R` is not integrally closed
  in its fraction field (`¬ IsIntegrallyClosed R`), i.e. the curve is not normal, hence not
  regular.

The characteristic zero hypothesis is part of the statement of Hironaka's theorem and is kept,
although this special case in fact holds over any field.
-/

/-- The coordinate ring `k[t^a, t^b] ⊆ k[t]` of the affine monomial curve `y^a = x^b`, i.e. the
image of the parametrization `t ↦ (t^a, t^b)`. -/

theorem exists_bezout_nat (a b : ℕ) (ha : 0 < a) (hab : Nat.Coprime a b) :
    ∃ u w : ℕ, a * u = 1 + b * w := by
  rcases Nat.eq_zero_or_pos b with rfl | hb
  · exact ⟨1, 0, by simpa using (Nat.coprime_zero_right a).1 hab⟩
  · have hbez : (1 : ℤ) = a * Nat.gcdA a b + b * Nat.gcdB a b := by
      have h := Nat.gcd_eq_gcd_ab a b
      rw [hab] at h
      exact_mod_cast h
    set s := Nat.gcdA a b
    set t := Nat.gcdB a b
    set N : ℤ := |s| + |t| + 1 with hN
    have hb' : (1 : ℤ) ≤ b := by exact_mod_cast hb
    have ha' : (1 : ℤ) ≤ a := by exact_mod_cast ha
    have hu : 0 ≤ s + b * N := by
      nlinarith [abs_nonneg s, abs_nonneg t, le_abs_self s, neg_abs_le s]
    have hw : 0 ≤ a * N - t := by
      nlinarith [abs_nonneg s, abs_nonneg t, le_abs_self t, neg_abs_le t]
    refine ⟨(s + b * N).toNat, (a * N - t).toNat, ?_⟩
    have hmain : (a : ℤ) * (s + b * N) = 1 + b * (a * N - t) := by ring_nf; linarith [hbez]
    zify [hu, hw]
    simpa [Int.toNat_of_nonneg hu, Int.toNat_of_nonneg hw] using hmain

/-- Birationality: the subfield of `k(t)` generated by `t^a` and `t^b` is all of `k(t)` when
`a` and `b` are coprime. -/
