/-!
# Hironaka Resolution
Category: Frontier Math
Target: Math2.hironaka_resolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

/-
## Toric principalization in two variables

Hironaka's theorem on resolution of singularities in characteristic zero contains, as its
combinatorial core, the *principalization* statement: after a finite tree of blowups an ideal
becomes locally principal, i.e. generated by a single monomial in every chart of every leaf of
the tree.

Here we formalize and prove this statement in the toric setting of monomial ideals in two
variables.  A monomial ideal is recorded by the finite list of exponent vectors of its monomial
generators (the monomial `x ^ a * y ^ b` is recorded by `(a, b)`), and the two standard charts of
the blowup of the origin act on exponent vectors by

* `chart1 (a, b) = (a + b, b)`   (the substitution `x = x'`, `y = x' * y'`),
* `chart2 (a, b) = (a, a + b)`   (the substitution `x = x' * y'`, `y = y'`).

`Principalizable` is the inductive predicate "some finite blowup tree principalizes", where a
node may be declared resolved as soon as one of its monomials divides all the others, and
otherwise must be resolved in *both* charts of the blowup.  The main theorem
`Math2.hironaka_resolution` states that every nonempty monomial ideal in two variables is
principalizable.  The proof is by strong induction on an explicit obstruction `mu`, the sum over
all pairs of generators of the `ℓ¹`-distance between incomparable exponent vectors; this measure
drops strictly in both charts of a blowup as long as the ideal is not already principal.

The development is self-contained: it uses only the Lean 4 core library.
-/

namespace Math2

/-- Exponent vector of a monomial `x ^ a * y ^ b` in two variables. -/
abbrev Exp : Type := Nat × Nat

/-- Divisibility of monomials, read off from exponent vectors. -/
abbrev Divides (p q : Exp) : Prop := p.1 ≤ q.1 ∧ p.2 ≤ q.2

/-- First blowup chart, acting on exponents: it records the substitution `x = x'`,
`y = x' * y'`, under which `x ^ a * y ^ b` becomes `x' ^ (a + b) * y' ^ b`. -/

def IsPrincipal (l : List Exp) : Prop := ∃ p ∈ l, ∀ q ∈ l, Divides p q

/-- `Principalizable l` holds when a finite tree of blowups of the origin makes the monomial
ideal recorded by `l` principal in every chart of every leaf of the tree. -/
inductive Principalizable : List Exp → Prop
  | base {l : List Exp} : IsPrincipal l → Principalizable l
  | blowup {l : List Exp} :
      Principalizable (l.map chart1) → Principalizable (l.map chart2) → Principalizable l

/-! ### The obstruction measure -/

/-- Sum of a list of natural numbers. -/
