/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 81c97b9e-4f0b-45bd-a0f4-aeb5fdb9a26d
-/

/-
This module formalizes geometric arithmetic on the natural numbers.
It establishes the canonical ray partition of ℕ modulo a prime p, proves its preservation under additive automorphisms,
defines the dihedral group action on ZMod p, demonstrates the appearance of the golden ratio in the spectral theory for p=5,
and proves the universal p-2 law for configuration counting.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-- A ray modulo p is the set of natural numbers congruent to i modulo p -/

def Ray (p : ℕ) (i : ZMod p) : Set ℕ :=
  {n : ℕ | (n : ZMod p) = i}

/-- The ray partition of ℕ for a given prime p -/

theorem mem_ray_iff (p : ℕ) (i : ZMod p) (n : ℕ) :
    n ∈ Ray p i ↔ (n : ZMod p) = i := Iff.rfl
