/-!
# Tightened Predicate Refines Original
Category: Proof-Carrying Apps
Target: PCA.Isolation.tightened_predicate_refines_original
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace PCA.Isolation

/-- Syntax of the isolation engine's guard predicates over atomic capability
checks drawn from `α`.  The language is the positive (negation-free) fragment
generated by `⊤`, `⊥`, atoms, conjunction and disjunction: this is exactly the
fragment the engine uses to describe which requests a sandboxed component may
perform. -/
inductive Pred (α : Type u) where
  | tru : Pred α
  | fls : Pred α
  | atom : α → Pred α
  | and : Pred α → Pred α → Pred α
  | or : Pred α → Pred α → Pred α
  deriving DecidableEq

namespace Pred

/-- Semantics of a guard predicate relative to an environment `env` assigning a
truth value to every atomic capability check. -/

def Accepts {α : Type u} (p : Pred α) (env : α → Bool) : Prop := eval env p = true

/-- Tightening a guard predicate by an extra side condition `g`: every leaf of
the predicate is guarded by `g`.  This is the operation the isolation engine
performs when it installs an additional policy constraint. -/
