import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

import RequestProject.AKS.Algorithm

/-!
# Correctness of the AKS primality test

The main result of this file is `AKS.aksTest_iff_prime`:
the decision procedure `AKS.aksTest` returns `true` exactly on the primes.
-/

namespace AKS

open Polynomial Finset


def aksTest (n : ℕ) : Bool :=
  if n < 2 then false
  else if isPerfectPower n then false
  else
    let r := findR n
    if gcdOK n r = false then false
    else if n ≤ r then true
    else (List.range (ell n r + 1)).all fun a => polyOK n r a

end AKS

import Mathlib

/-!
# Numeric estimates used in the AKS argument

Throughout, `B` plays the role of a bound on the bit length of `n` (so `n < 2 ^ B`),
`t` is the size of the monoid generated by `n` and `p` modulo `r`, `s = ⌊√t⌋` and
`d = 2 (s+1) B`.
-/

namespace AKS

