/-!
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verified: AXLE cloud (Lean 4.32.0, Mathlib), axiom-clean
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

/-!
# A formal model of a certificate-checking isolation engine

This file develops a self-contained mathematical model of the certificate layer of an
isolation engine ("PCA"): an engine that admits an isolation *claim* (a principal being
attached to an isolation domain for a given epoch) only if the claim is accompanied by a
certificate whose Ed25519-style signature verifies against a fixed trusted authority key.

The signature scheme is modelled at the level at which Ed25519 verification is actually a
mathematical statement: a prime-order additive group `G` generated by a base point `B`,
scalars living in `ZMod L` (`L` the group order), public key `A = s • B`, and the
Schnorr/Ed25519 verification equation

  `S • B = R + H(R, A, m) • A`.

The hash function `H` is an arbitrary function; no assumption whatsoever is made about it,
so all results below hold for every instantiation.

## Main results

* `PCA.Cert.ed25519_verify_complete` — honestly produced signatures always verify.
* `PCA.Cert.ed25519_verify_sound` — **the target theorem**: a signature accepted under the
  public key `A = s • B` is *exactly* an honest signature produced with the secret key `s`,
  i.e. there is a nonce `r` with `sig = sign s r c`.  Together with completeness this makes
  the accepted set of the verifier equal to the image of the signing algorithm.
* `PCA.Cert.ed25519_verify_iff` — the resulting characterisation (soundness ∧ completeness).
* `PCA.Cert.ed25519_sig_unique` — for a fixed commitment `R` at most one scalar `S` is
  accepted.
* `PCA.Cert.engine_sound`, `PCA.Cert.engine_complete` — soundness and completeness of the
  engine's admission relation along an arbitrary trace of presented certificates.
* `PCA.Cert.engine_isolation` — the isolation guarantee: against an adversary that can only
  replay certificates issued by the authority, every admitted claim satisfies the
  authority's policy.
-/

namespace PCA.Cert

/-- An isolation claim: `principal` is bound to isolation `domain` during `epoch`. -/
structure Claim where
  principal : ℕ
  domain : ℕ
  epoch : ℕ
  deriving DecidableEq

/-- An Ed25519-style signature: a group commitment `R` and a scalar response `S`. -/
@[ext]
structure Sig (L : ℕ) (G : Type*) where
  R : G
  S : ZMod L
  deriving DecidableEq

variable {L : ℕ} {G : Type*} [AddCommGroup G] [Module (ZMod L) G]

/-- The algebraic data of the signature scheme: a base point `B` generating a group in which
scalar multiplication by `ZMod L` is a bijection onto `G` (a cyclic group of order `L`),
together with an arbitrary hash function used for challenge derivation. -/
structure Scheme (L : ℕ) (G : Type*) [AddCommGroup G] [Module (ZMod L) G] where
  /-- The base point. -/
  B : G
  /-- The challenge hash, applied to the commitment, the public key and the claim. -/
  hash : G → G → Claim → ZMod L
  /-- Every group element is a multiple of the base point. -/
  smul_surjective : ∀ P : G, ∃ a : ZMod L, P = a • B
  /-- Distinct scalars give distinct multiples of the base point. -/
  smul_injective : Function.Injective (fun a : ZMod L => a • B)

/-- The public key associated with the secret scalar `s`. -/
def pub (sch : Scheme L G) (s : ZMod L) : G := s • sch.B

/-- The signing algorithm: with secret key `s` and nonce `r`, the signature of the claim `c`
is `(r • B, r + H(r • B, s • B, c) * s)`. -/
def sign (sch : Scheme L G) (s r : ZMod L) (c : Claim) : Sig L G where
  R := r • sch.B
  S := r + sch.hash (r • sch.B) (pub sch s) c * s

/-- The Ed25519 verification equation, as a decidable predicate. -/
def verify [DecidableEq G] (sch : Scheme L G) (A : G) (c : Claim) (sig : Sig L G) : Bool :=
  sig.S • sch.B == sig.R + sch.hash sig.R A c • A

@[simp] theorem verify_eq_true_iff [DecidableEq G] (sch : Scheme L G) (A : G) (c : Claim)
    (sig : Sig L G) :
    verify sch A c sig = true ↔ sig.S • sch.B = sig.R + sch.hash sig.R A c • A := by
  simp [verify]

/-- The model is non-vacuous: for any `L` and any hash function, `ZMod L` with base point `1`
is a scheme in the above sense. -/
def stdScheme (L : ℕ) (H : ZMod L → ZMod L → Claim → ZMod L) : Scheme L (ZMod L) where
  B := 1
  hash := H
  smul_surjective := fun P => ⟨P, by simp⟩
  smul_injective := by
    intro a b h
    simpa using h

/-! ### Completeness and soundness of Ed25519 verification -/

/-- **Completeness.** Every honestly produced signature is accepted. -/
theorem ed25519_verify_complete [DecidableEq G] (sch : Scheme L G) (s r : ZMod L) (c : Claim) :
    verify sch (pub sch s) c (sign sch s r c) = true := by
  rw [verify_eq_true_iff]
  show (r + sch.hash (r • sch.B) (pub sch s) c * s) • sch.B
      = r • sch.B + sch.hash (r • sch.B) (pub sch s) c • pub sch s
  rw [add_smul, pub, smul_smul]

/-- **Soundness (target theorem).**  If a signature is accepted under the public key
`pub sch s = s • B`, then it is an honest signature produced with the secret key `s`:
there is a nonce `r` for which the signature is literally `sign sch s r c`.

Consequently the verifier accepts nothing beyond the image of the signing algorithm; no
signature can be accepted unless it satisfies the exact algebraic relation that possession
of the secret key `s` produces. -/
theorem ed25519_verify_sound [DecidableEq G] (sch : Scheme L G) (s : ZMod L) (c : Claim)
    (sig : Sig L G) (h : verify sch (pub sch s) c sig = true) :
    ∃ r : ZMod L, sig = sign sch s r c := by
  rw [verify_eq_true_iff] at h
  obtain ⟨r, hr⟩ := sch.smul_surjective sig.R
  refine ⟨r, ?_⟩
  rw [hr] at h
  have hS : sig.S • sch.B = (r + sch.hash (r • sch.B) (pub sch s) c * s) • sch.B := by
    rw [add_smul, mul_smul, h]
    rfl
  have hSval : sig.S = r + sch.hash (r • sch.B) (pub sch s) c * s := sch.smul_injective hS
  exact Sig.ext hr hSval

/-- Soundness and completeness combined: the accepted signatures for the claim `c` under the
public key `pub sch s` are exactly the honest signatures on `c` under the secret key `s`. -/
theorem ed25519_verify_iff [DecidableEq G] (sch : Scheme L G) (s : ZMod L) (c : Claim)
    (sig : Sig L G) :
    verify sch (pub sch s) c sig = true ↔ ∃ r : ZMod L, sig = sign sch s r c := by
  refine ⟨ed25519_verify_sound sch s c sig, ?_⟩
  rintro ⟨r, rfl⟩
  exact ed25519_verify_complete sch s r c

/-- The scalar part of an accepted signature is determined by its commitment: for a fixed
`R`, at most one response `S` is accepted. -/
theorem ed25519_sig_unique [DecidableEq G] (sch : Scheme L G) (A : G) (c : Claim)
    (sig₁ sig₂ : Sig L G) (hR : sig₁.R = sig₂.R)
    (h₁ : verify sch A c sig₁ = true) (h₂ : verify sch A c sig₂ = true) :
    sig₁ = sig₂ := by
  rw [verify_eq_true_iff] at h₁ h₂
  have hS : sig₁.S = sig₂.S := by
    apply sch.smul_injective
    show sig₁.S • sch.B = sig₂.S • sch.B
    rw [h₁, h₂, hR]
  exact Sig.ext hR hS

/-! ### The isolation engine -/

/-- The engine state reached after processing a trace of presented certificates: the set of
claims that were admitted.  A presented pair `(c, sig)` is admitted iff its signature
verifies against the trusted authority key `A`. -/
def run [DecidableEq G] (sch : Scheme L G) (A : G) :
    List (Claim × Sig L G) → Set Claim
  | [] => ∅
  | (c, sig) :: t =>
      if verify sch A c sig = true then insert c (run sch A t) else run sch A t

@[simp] theorem run_nil [DecidableEq G] (sch : Scheme L G) (A : G) :
    run sch A [] = (∅ : Set Claim) := rfl

@[simp] theorem run_cons [DecidableEq G] (sch : Scheme L G) (A : G) (c : Claim)
    (sig : Sig L G) (t : List (Claim × Sig L G)) :
    run sch A ((c, sig) :: t)
      = if verify sch A c sig = true then insert c (run sch A t) else run sch A t := rfl

/-- **Engine soundness.**  Every claim admitted by the engine was presented together with a
signature that the authority (the holder of the secret key `s`) could have produced: an
honest signature on that very claim. -/
theorem engine_sound [DecidableEq G] (sch : Scheme L G) (s : ZMod L)
    (tr : List (Claim × Sig L G)) {c : Claim} (hc : c ∈ run sch (pub sch s) tr) :
    ∃ r : ZMod L, (c, sign sch s r c) ∈ tr := by
  induction tr with
  | nil => simp at hc
  | cons hd t ih =>
      obtain ⟨c₀, sig₀⟩ := hd
      rw [run_cons] at hc
      by_cases hv : verify sch (pub sch s) c₀ sig₀ = true
      · rw [if_pos hv] at hc
        rcases hc with hc | hc
        · subst hc
          obtain ⟨r, hr⟩ := ed25519_verify_sound sch s c sig₀ hv
          exact ⟨r, by simp [hr]⟩
        · obtain ⟨r, hr⟩ := ih hc
          exact ⟨r, List.mem_cons_of_mem _ hr⟩
      · rw [if_neg hv] at hc
        obtain ⟨r, hr⟩ := ih hc
        exact ⟨r, List.mem_cons_of_mem _ hr⟩

/-- **Engine completeness.**  Any claim presented with an honest certificate is admitted. -/
theorem engine_complete [DecidableEq G] (sch : Scheme L G) (s r : ZMod L)
    (tr : List (Claim × Sig L G)) {c : Claim} (hc : (c, sign sch s r c) ∈ tr) :
    c ∈ run sch (pub sch s) tr := by
  induction tr with
  | nil => simp at hc
  | cons hd t ih =>
      obtain ⟨c₀, sig₀⟩ := hd
      rw [run_cons]
      rcases List.mem_cons.1 hc with h | h
      · have hc₀ : c₀ = c := congrArg Prod.fst h.symm
        have hsig : sig₀ = sign sch s r c := congrArg Prod.snd h.symm
        subst hc₀
        rw [if_pos (by rw [hsig]; exact ed25519_verify_complete sch s r c₀)]
        exact Set.mem_insert _ _
      · split
        · exact Set.mem_insert_of_mem _ (ih h)
        · exact ih h

/-- **Isolation.**  Model of an adversary that can only replay certificates issued by the
authority: every pair appearing in the trace is (a copy of) an authority-issued certificate,
and the authority only issues certificates for claims satisfying its policy `P`.  Then every
claim admitted by the engine satisfies `P`; in particular no principal is ever attached to a
domain the policy forbids. -/
theorem engine_isolation [DecidableEq G] (sch : Scheme L G) (s : ZMod L) (P : Claim → Prop)
    (tr : List (Claim × Sig L G))
    (htr : ∀ x ∈ tr, (∃ r : ZMod L, x.2 = sign sch s r x.1) → P x.1)
    {c : Claim} (hc : c ∈ run sch (pub sch s) tr) : P c := by
  obtain ⟨r, hr⟩ := engine_sound sch s tr hc
  exact htr (c, sign sch s r c) hr ⟨r, rfl⟩

end PCA.Cert

