/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 93fa049e-81ca-4d65-a2af-f38be27e7672
-/

/-
Formalization of Prime k-Tuple Structure Theory.

This module contains:
1. Definitions of the Hardy-Littlewood singular series and local factors.
2. Proof of convergence of the singular series for admissible tuples.
3. Definitions of admissibility and proofs of its necessity for infinite prime tuples.
4. The Universal q-2 Theorem for prime pairs (formalized as `k_tuple_pairs_theorem_correct`).
5. Connection between residue cardinality and principal k-tuple counts.
6. Computational tools for nu_p and local factors.

Note: The following conjectures from the original text were disproven and thus not added as theorems:
- `singular_series_finite_antitone`: Disproven by counterexample {0, 2}.
- `admissible_iff_nu_less_than_p`: Disproven (definitions of admissibility differ).
- `admissible_iff_positive_count`: Disproven (local vs global admissibility).
- `local_factor_le_one`: Disproven.

All other main results have been formally verified.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of nu_p and nu_p'
-/
open scoped BigOperators
open Real

/-- The number of distinct residues of a finite set modulo p -/

theorem card_principal_eq_q_sub_image (p : ℕ) (g : ℕ → ℕ) (k : ℕ)
    [Fact (Nat.Prime p)] (hga : AdmissibleTuple p g k) :
    (PrincipalKTuples p g k).card = p - (Finset.image (fun i => (g i) % p) (Finset.range k)).card := by
  -- The set of principal k-tuples is exactly the set of numbers in the range 0 to p-1 that are not congruent to any of the g_i modulo p.
  have h_principal_set : Finset.filter (fun n => ∀ i ∈ Finset.range k, ¬(n + g i) % p = 0) (Finset.range p) = Finset.range p \ Finset.image (fun i => (p - g i % p) % p) (Finset.range k) := by
    ext n;
    simp +decide [ ← ZMod.val_natCast, Nat.add_mod ];
    intro hn; constructor <;> intro h i hi <;> specialize h i hi <;> simp_all +decide [ ← eq_sub_iff_add_eq', ZMod.natCast_zmod_val ] ;
    · contrapose! h;
      simp +decide [ ← h, Nat.cast_sub ( show g i % p ≤ p from Nat.le_of_lt ( Nat.mod_lt _ ( Nat.Prime.pos Fact.out ) ) ) ];
    · contrapose! h;
      rw [ Nat.ModEq.symm ];
      exact Nat.mod_eq_of_lt hn;
      simp_all +decide [ ← ZMod.natCast_eq_natCast_iff, Nat.cast_sub ( show g i % p ≤ p from Nat.le_of_lt <| Nat.mod_lt _ <| Nat.Prime.pos Fact.out ) ];
  -- The cardinality of the difference of two sets is the difference of their cardinalities.
  have h_card_diff : Finset.card (Finset.range p \ Finset.image (fun i => (p - g i % p) % p) (Finset.range k)) = p - Finset.card (Finset.image (fun i => (p - g i % p) % p) (Finset.range k)) := by
    rw [ Finset.card_sdiff ] ; norm_num;
    rw [ Finset.inter_eq_left.mpr ];
    exact Finset.image_subset_iff.mpr fun i hi => Finset.mem_range.mpr <| Nat.mod_lt _ <| Nat.Prime.pos Fact.out;
  convert h_card_diff using 2;
  refine' Finset.card_bij ( fun x hx => ( p - x ) % p ) _ _ _ <;> simp +contextual;
  · exact fun i hi => ⟨ i, hi, rfl ⟩;
  · intro i hi j hj h; have := Nat.modEq_iff_dvd.mp h.symm; simp_all +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd, Nat.cast_sub ( show g i % p ≤ p from Nat.le_of_lt <| Nat.mod_lt _ <| Nat.Prime.pos Fact.out ), Nat.cast_sub ( show g j % p ≤ p from Nat.le_of_lt <| Nat.mod_lt _ <| Nat.Prime.pos Fact.out ) ] ;
    simp_all +decide [ sub_eq_zero, ← ZMod.natCast_eq_natCast_iff' ]

/-
If nu_p = p, then some shift is always divisible by p
-/
open scoped BigOperators
open Real

/-- If nu_p = p, then some shift is always divisible by p -/
