/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 93fa049e-81ca-4d65-a2af-f38be27e7672
-/

/-
Formalization of Prime k-Tuple Structure Theory.

This module contains:
1. Definitions of the Hardy-Littlewood singular series and local factors.
2. Proof of convergence of the singular series for admissible tuples.
3. Definitions of admissibility and proofs of its necessity for infinite prime tuples.
4. The Universal q-2 Theorem for prime pairs (formalized as `k_tuple_pairs_theorem_correct`).
5. Connection between residue cardinality and principal k-tuple counts.
6. Computational tools for nu_p and local factors.

Note: The following conjectures from the original text were disproven and thus not added as theorems:
- `singular_series_finite_antitone`: Disproven by counterexample {0, 2}.
- `admissible_iff_nu_less_than_p`: Disproven (definitions of admissibility differ).
- `admissible_iff_positive_count`: Disproven (local vs global admissibility).
- `local_factor_le_one`: Disproven.

All other main results have been formally verified.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of nu_p and nu_p'
-/
open scoped BigOperators
open Real

/-- The number of distinct residues of a finite set modulo p -/

theorem non_admissible_implies_finite (G : Finset ℕ)
    (h : ¬IsAdmissibleAlt G)
    (h_nonempty : G.Nonempty)
    (h_zero : 0 ∈ G) :
    Set.Finite {n : ℕ | ∀ g ∈ G, Nat.Prime (n + g)} := by
      -- If $0 \in G$, then for any $n$, $n + 0 = n$ must be prime. The only primes are $2, 3, 5, \ldots$, but the set of primes is infinite. However, the problem states that the set of prime tuples is finite. There must be a mistake here.
      by_contra h_contra;
      have h_inf : Set.Infinite {n : ℕ | ∀ g ∈ G, Nat.Prime (n + g)} := by
        exact h_contra;
      -- Let $p$ be a prime such that $\nu_p(G) = p$.
      obtain ⟨p, hp_prime, hp_eq⟩ : ∃ p, Nat.Prime p ∧ nu_p G p = p := by
        contrapose! h;
        exact fun p hp => lt_of_le_of_ne ( nu_p_le_p G p hp.ne_zero ) ( h p hp );
      -- By definition of $nu_p$, if $\nu_p(G) = p$, then for every $n$, there exists $g \in G$ such that $p \mid (n + g)$.
      have h_div : ∀ n : ℕ, ∃ g ∈ G, p ∣ (n + g) := by
        haveI := Fact.mk hp_prime; exact?;
      exact h_inf <| Set.finite_iff_bddAbove.mpr ⟨ p, fun n hn => not_lt.mp fun contra => by obtain ⟨ g, hg₁, hg₂ ⟩ := h_div n; have := Nat.dvd_of_mod_eq_zero ( show ( n + g ) % p = 0 from Nat.mod_eq_zero_of_dvd hg₂ ) ; exact absurd this ( by rw [ Nat.dvd_prime ( hn g hg₁ ) ] ; aesop ) ⟩

/-
Admissibility is necessary for infinitely many primes (using IsAdmissibleAlt)
-/
open scoped BigOperators
open Real

/-- Admissibility is necessary for infinitely many primes -/
