/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 93fa049e-81ca-4d65-a2af-f38be27e7672
-/

/-
Formalization of Prime k-Tuple Structure Theory.

This module contains:
1. Definitions of the Hardy-Littlewood singular series and local factors.
2. Proof of convergence of the singular series for admissible tuples.
3. Definitions of admissibility and proofs of its necessity for infinite prime tuples.
4. The Universal q-2 Theorem for prime pairs (formalized as `k_tuple_pairs_theorem_correct`).
5. Connection between residue cardinality and principal k-tuple counts.
6. Computational tools for nu_p and local factors.

Note: The following conjectures from the original text were disproven and thus not added as theorems:
- `singular_series_finite_antitone`: Disproven by counterexample {0, 2}.
- `admissible_iff_nu_less_than_p`: Disproven (definitions of admissibility differ).
- `admissible_iff_positive_count`: Disproven (local vs global admissibility).
- `local_factor_le_one`: Disproven.

All other main results have been formally verified.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of nu_p and nu_p'
-/
open scoped BigOperators
open Real

/-- The number of distinct residues of a finite set modulo p -/

lemma nu_p_le_p (G : Finset ℕ) (p : ℕ) (hp : p ≠ 0) : nu_p G p ≤ p := by
  exact le_trans ( Finset.card_le_card <| Finset.image_subset_iff.2 fun i hi => Finset.mem_range.2 <| Nat.mod_lt i <| Nat.pos_of_ne_zero hp ) <| by aesop;

/-
Non-admissible tuples have finitely many prime instances (using helper lemmas)
-/
open scoped BigOperators
open Real

/-- Main theorem: Non-admissible tuples have finitely many prime instances -/
