/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

/-! ## The point group D₆ₕ

The molecular point group of benzene is `D₆ₕ ≅ D₆ × {E, i}`, the direct product of the
dihedral group of order 12 with the two-element group generated by the inversion centre.
-/

/-- The point group `D₆ₕ` of benzene, realised as `D₆ × C_i`. -/
abbrev D6h := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- The parity (`g`/`u`) sign attached to the inversion factor of `D₆ₕ`. -/

def altv (n : ℕ) : ℤ := if n % 2 = 0 then 1 else -1

/-- The six irreducible characters of the dihedral group `D₆`, in the order
`A₁, A₂, B₁, B₂, E₁, E₂`. -/
