/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

/-! ## The molecular symmetry group of benzene

Benzene has point group `D₆ₕ`, which is the direct product of the dihedral group of order 12
(the symmetries of the regular hexagon) with the two-element group generated by the inversion
`i` (equivalently, `D₆ₕ ≅ D₆ × Cᵢ`, of order 24). -/

/-- The point group `D₆ₕ` of benzene, realized as `D₆ × C₂`. -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- Index type used both for the conjugacy classes (columns) and for the irreducible
characters (rows) of the character table of `D₆ₕ`.  The first component indexes the six
classes/irreps of `D₆`, the second the two of `Cᵢ` (gerade `g` = `0`, ungerade `u` = `1`). -/
abbrev Idx : Type := Fin 6 × Fin 2

/-- Representatives of the twelve conjugacy classes of `D₆ₕ`.  In chemical notation the
`D₆`-part runs through `E, 2C₆, 2C₃, C₂, 3C₂', 3C₂''` and the `Cᵢ`-part through `1, i`, giving
`E, 2C₆, 2C₃, C₂, 3C₂', 3C₂'', i, 2S₃, 2S₆, σ_h, 3σ_d, 3σ_v`. -/

theorem benzene_D6h_irreps :
    Fintype.card (ConjClasses D6h) = 12 ∧
    Fintype.card Idx = 12 ∧
    Function.Bijective (fun i : Idx => ConjClasses.mk (classRep i)) ∧
    (∀ c : Idx, ((Finset.univ.filter fun x : D6h => IsConj (classRep c) x).card : ℤ)
      = classSize c) ∧
    (∑ c : Idx, classSize c = 24) ∧
    (∀ i j : Idx,
      ∑ c : Idx, classSize c * charTable i c * charTable j c = if i = j then 24 else 0) ∧
    (∀ c c' : Idx,
      classSize c * ∑ i : Idx, charTable i c * charTable i c' = if c = c' then 24 else 0) ∧
    (∑ i : Idx, (charTable i (0, 0)) ^ 2 = 24) ∧
    LinearIndependent ℚ (fun i : Idx => (fun c : Idx => (charTable i c : ℚ))) :=
  ⟨card_conjClasses_D6h, by decide, classRep_bijective, classSize_eq, sum_classSize,
    row_orthogonality, col_orthogonality, sum_sq_degrees, charTable_linearIndependent⟩

end Chem

