/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

/-! ## The molecular symmetry group of benzene

Benzene has point group `D₆ₕ`, which is the direct product of the dihedral group of order 12
(the symmetries of the regular hexagon) with the two-element group generated by the inversion
`i` (equivalently, `D₆ₕ ≅ D₆ × Cᵢ`, of order 24). -/

/-- The point group `D₆ₕ` of benzene, realized as `D₆ × C₂`. -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- Index type used both for the conjugacy classes (columns) and for the irreducible
characters (rows) of the character table of `D₆ₕ`.  The first component indexes the six
classes/irreps of `D₆`, the second the two of `Cᵢ` (gerade `g` = `0`, ungerade `u` = `1`). -/
abbrev Idx : Type := Fin 6 × Fin 2

/-- Representatives of the twelve conjugacy classes of `D₆ₕ`.  In chemical notation the
`D₆`-part runs through `E, 2C₆, 2C₃, C₂, 3C₂', 3C₂''` and the `Cᵢ`-part through `1, i`, giving
`E, 2C₆, 2C₃, C₂, 3C₂', 3C₂'', i, 2S₃, 2S₆, σ_h, 3σ_d, 3σ_v`. -/

theorem charTable_linearIndependent :
    LinearIndependent ℚ (fun i : Idx => (fun c : Idx => (charTable i c : ℚ))) := by
  rw [Fintype.linearIndependent_iff]
  intro g hg j
  have hzero : ∀ c : Idx, (∑ i : Idx, g i * (charTable i c : ℚ)) = 0 := by
    intro c
    have h := congrFun hg c
    simpa [Finset.sum_apply] using h
  have key : ∑ i : Idx, g i * (∑ c : Idx, (classSize c : ℚ) * charTable i c * charTable j c)
      = 0 := by
    calc ∑ i : Idx, g i * (∑ c : Idx, (classSize c : ℚ) * charTable i c * charTable j c)
        = ∑ i : Idx, ∑ c : Idx, g i * ((classSize c : ℚ) * charTable i c * charTable j c) := by
          simp only [Finset.mul_sum]
      _ = ∑ c : Idx, ∑ i : Idx, g i * ((classSize c : ℚ) * charTable i c * charTable j c) :=
          Finset.sum_comm
      _ = ∑ c : Idx, (classSize c : ℚ) * (∑ i : Idx, g i * (charTable i c : ℚ))
            * charTable j c := by
          refine Finset.sum_congr rfl fun c _ => ?_
          rw [Finset.mul_sum, Finset.sum_mul]
          exact Finset.sum_congr rfl fun i _ => by ring
      _ = 0 := by simp [hzero]
  have hrow : ∀ i : Idx, (∑ c : Idx, (classSize c : ℚ) * charTable i c * charTable j c)
      = if i = j then (24 : ℚ) else 0 := by
    intro i
    have h := row_orthogonality i j
    split_ifs at h ⊢
    · exact_mod_cast h
    · exact_mod_cast h
  simp only [hrow] at key
  rw [Finset.sum_eq_single j (fun b _ hb => by simp [hb]) (by simp)] at key
  simpa using key

/-! ## The twelve characters are genuinely characters of representations of `D₆ₕ`

The eight one-dimensional rows are realized by group homomorphisms `D₆ₕ → ℤ`, and the four
two-dimensional rows by integral matrix representations. -/

/-- The four linear characters of `D₆` (`A₁, A₂, B₁, B₂`). -/
