import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 10000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

open Matrix CategoryTheory

/-! ## The point group `D₆ₕ`

The molecular point group of benzene, `D₆ₕ`, is the direct product of the dihedral group `D₆`
(of order 12: six rotations `Cₙ` about the principal axis together with six twofold axes)
with the two element group generated by the inversion centre `i`.  It has order 24. -/

/-- The point group `D₆ₕ = D₆ × Cᵢ`, of order `24`. -/
abbrev D6h := DihedralGroup 6 × Multiplicative (ZMod 2)

instance : Fintype D6h := inferInstanceAs (Fintype (DihedralGroup 6 × Multiplicative (ZMod 2)))


lemma character_irrep_r (i : Fin 12) (j : ZMod 6) (u : Multiplicative (ZMod 2)) :
    (irrep i).character (DihedralGroup.r j, u) = (chiZ i (DihedralGroup.r j, u) : ℂ) := by
  rw [show (irrep i).character (DihedralGroup.r j, u) =
      (irrData i).e ^ (Multiplicative.toAdd u).val * ((irrData i).R ^ j.val).trace from
    IrrData.character_r (irrData i) j u]
  rcases zmod6_cases j with rfl | rfl | rfl | rfl | rfl | rfl <;>
    rcases zmod2_cases (Multiplicative.toAdd u) with h | h <;>
    rcases fin12_cases i with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl |
      rfl <;>
      simp [irrep, irrData, IrrData.character_r, chiZ, rotRow, refRow, baseIdx, zval, invSign, h,
        Mp, Mm, ER1, ER2, ES, ZMod.val, pow_succ, Matrix.mul_fin_two, Matrix.trace, Matrix.diag,
        Fin.sum_univ_succ]

end Chem

