import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 10000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

open Matrix CategoryTheory

/-! ## The point group `D₆ₕ`

The molecular point group of benzene, `D₆ₕ`, is the direct product of the dihedral group `D₆`
(of order 12: six rotations `Cₙ` about the principal axis together with six twofold axes)
with the two element group generated by the inversion centre `i`.  It has order 24. -/

/-- The point group `D₆ₕ = D₆ × Cᵢ`, of order `24`. -/
abbrev D6h := DihedralGroup 6 × Multiplicative (ZMod 2)

instance : Fintype D6h := inferInstanceAs (Fintype (DihedralGroup 6 × Multiplicative (ZMod 2)))


lemma character_sr (j : ZMod 6) (u : Multiplicative (ZMod 2)) :
    D.fdRep.character (DihedralGroup.sr j, u) =
      D.e ^ (Multiplicative.toAdd u).val * (D.S * D.R ^ j.val).trace := by
  rw [character_eq]
  show (zmodPow D.e (Multiplicative.toAdd u) • dihMap D.R D.S (DihedralGroup.sr j)).trace = _
  rw [Matrix.trace_smul]
  rfl

end IrrData

/-! ## The twelve irreducible representations of `D₆ₕ`

`D₆` has six irreducible complex representations: four of dimension one (`A₁`, `A₂`, `B₁`, `B₂`)
and two of dimension two (`E₁`, `E₂`).  Each of them can be combined with either of the two
characters of the inversion group, giving the twelve `gerade`/`ungerade` representations
`A₁g, A₂g, B₁g, B₂g, E₁g, E₂g, A₁u, A₂u, B₁u, B₂u, E₁u, E₂u` of `D₆ₕ`. -/

/-- The `1 × 1` identity block. -/
