/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

set_option maxRecDepth 100000

namespace Chem

/-! ## The point group -/

/-- The molecular point group `D₆ₕ` of benzene, realized abstractly as the direct product
of the dihedral group `D₆` (of order 12: the rotations `C₆ⁿ` together with the six in-plane
`C₂` axes) with the order-two group generated by the inversion centre `i`. -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- `D₆ₕ` has order 24. -/

theorem chi_identity (x : D6hIrrep) : chi x 0 = (x.dim : ℤ) := by
  cases x <;> rfl

/-- **Row orthogonality for the `D₆ₕ` character table.** Weighting each column by the size of
its conjugacy class, distinct rows are orthogonal and each row has squared norm `|D₆ₕ| = 24`.
In particular the twelve rows are pairwise distinct irreducible characters. -/
