/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

set_option maxRecDepth 100000

namespace Chem

/-! ## The point group -/

/-- The molecular point group `D₆ₕ` of benzene, realized abstractly as the direct product
of the dihedral group `D₆` (of order 12: the rotations `C₆ⁿ` together with the six in-plane
`C₂` axes) with the order-two group generated by the inversion centre `i`. -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- `D₆ₕ` has order 24. -/

theorem chi_orthogonality : ∀ x y : D6hIrrep,
    ∑ c : Fin 12, classSize c * chi x c * chi y c = if x = y then 24 else 0 := by
  decide

/-- **The `D₆ₕ` character table of benzene has the correct number of irreducible
representations.** The twelve Mulliken labels `A₁g, A₂g, B₁g, B₂g, E₁g, E₂g,
A₁u, A₂u, B₁u, B₂u, E₁u, E₂u` are equinumerous with the twelve conjugacy classes of the
point group `D₆ₕ`; the sum of the squares of their dimensions `8 · 1² + 4 · 2² = 24` equals
the group order, as required by the completeness relation; and the twelve rows of the
character table are pairwise orthogonal of squared norm `|D₆ₕ|`, hence genuinely distinct
irreducible characters. -/
