/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

/-! ## The point group D₆ₕ

The molecular point group of benzene is `D₆ₕ ≅ D₆ × {E, i}`, the direct product of the
dihedral group of order 12 with the two-element group generated by the inversion centre.
-/

/-- The point group `D₆ₕ` of benzene, realised as `D₆ × C_i`. -/
abbrev D6h := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- The parity (`g`/`u`) sign attached to the inversion factor of `D₆ₕ`. -/

theorem chi_injective : Function.Injective chi := by
  intro a b hab
  by_contra hne
  have h := chi_orthogonal a b
  rw [if_neg hne, ← hab] at h
  have h' := chi_orthogonal a a
  rw [if_pos rfl] at h'
  omega

/-- The dimensions of the irreps of `D₆ₕ` are `1,1,1,1,2,2` for the gerade set and the same for
the ungerade set. -/
