import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 40000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

/-!
## The point group of benzene

Benzene has molecular point group `D₆ₕ`, which is the direct product of the dihedral
group `D₆` (of order `12`, the symmetries of the hexagonal carbon skeleton in its own
plane) with the two element group `{E, i}` generated by the inversion centre.  Thus
`D₆ₕ ≅ D₆ × C₂` has order `24`.
-/

/-- The point group `D₆ₕ` of benzene, realised as `D₆ × C₂`. -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- The nontrivial element of the `C₂` factor, i.e. the inversion `i`. -/

theorem classRep_not_conj {i j : Fin 12} (h : IsConj (classRep i) (classRep j)) : i = j := by
  revert h; revert i j; decide

/-- Every element of `D₆ₕ` is conjugate to one of the chosen representatives. -/
