/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

set_option maxRecDepth 100000

namespace Chem

/-! ## The point group -/

/-- The molecular point group `D₆ₕ` of benzene, realized abstractly as the direct product
of the dihedral group `D₆` (of order 12: the rotations `C₆ⁿ` together with the six in-plane
`C₂` axes) with the order-two group generated by the inversion centre `i`. -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- `D₆ₕ` has order 24. -/

theorem classSizes_D6h :
    (Finset.univ : Finset (ConjClasses D6h)).val.map (fun c => c.carrier.toFinset.card)
      = ({1, 2, 2, 1, 3, 3, 1, 2, 2, 1, 3, 3} : Multiset ℕ) := by
  decide

/-- The `D₆ₕ` character table. All entries are integers; the columns are the conjugacy classes
in the order `E, 2C₆, 2C₃, C₂, 3C₂', 3C₂'', i, 2S₃, 2S₆, σ_h, 3σ_d, 3σ_v`, so that the
`u` (ungerade) rows are the `g` (gerade) rows with the second half of the entries negated. -/
