/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

-- (In this Lean/Mathlib version a module docstring `/-! ... -/` may not precede the
-- `import` line, so the header above is a plain block comment and is repeated here.)
/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace Chem

/-!
## Setup

Benzene (C₆H₆) has molecular point group `D₆ₕ`, which is the direct product of the
dihedral group `D₆` (order `12`, the rotations and in-plane `C₂` axes of the hexagon)
with the order-two group `{E, i}` generated by the inversion centre.  We model it as
`DihedralGroup 6 × Multiplicative (ZMod 2)`, a group of order `24`.

Mathlib knows the number of conjugacy classes of `DihedralGroup n` only for odd `n`
(`DihedralGroup.card_conjClasses_odd`), and it has no lemma about direct products of
conjugacy-class counts, so the count below is obtained by kernel evaluation (`decide`)
after supplying the (missing) computable `Fintype`/`DecidableEq` instances on
`ConjClasses`.
-/

/-- The point group of benzene: `D₆ₕ ≅ D₆ × Cᵢ`. -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

instance decIsConjD6h : DecidableRel (IsConj : D6h → D6h → Prop) :=
  fun a b => decidable_of_iff _ (isConj_iff (a := a) (b := b)).symm

instance decEqConjClassesD6h : DecidableEq (ConjClasses D6h) :=
  @Quotient.decidableEq D6h (IsConj.setoid D6h) fun a b => decIsConjD6h a b

instance fintypeConjClassesD6h : Fintype (ConjClasses D6h) :=
  @Quotient.fintype D6h _ (IsConj.setoid D6h) fun a b => decIsConjD6h a b

/-- The dimensions of the twelve irreducible representations of `D₆ₕ`, listed in the
standard (Mulliken) order of the character table:
`A₁g, A₂g, B₁g, B₂g, E₁g, E₂g, A₁u, A₂u, B₁u, B₂u, E₁u, E₂u`. -/

theorem d6h_irrep_dims_unique (M : Multiset ℕ) (hpos : ∀ d ∈ M, 0 < d)
    (hcard : Multiset.card M = 12) (hsq : (M.map fun d => d ^ 2).sum = 24) :
    M = (d6hIrrepDims : Multiset ℕ) := by
  have hle : ∀ d ∈ M, d ≤ 4 := by
    intro d hd
    have h1 : d ^ 2 ≤ (M.map fun d => d ^ 2).sum :=
      Multiset.single_le_sum (fun x _ => Nat.zero_le x) _ (Multiset.mem_map_of_mem _ hd)
    rw [hsq] at h1
    nlinarith [h1]
  have hsub : M.toFinset ⊆ ({1, 2, 3, 4} : Finset ℕ) := by
    intro d hd
    simp only [Multiset.mem_toFinset] at hd
    have h1 := hpos d hd
    have h2 := hle d hd
    simp only [Finset.mem_insert, Finset.mem_singleton]
    omega
  have hc : ∑ v ∈ ({1, 2, 3, 4} : Finset ℕ), Multiset.count v M = 12 := by
    rw [← hcard, ← Multiset.toFinset_sum_count_eq]
    exact (Finset.sum_subset hsub fun x _ hx => by
      simpa using Multiset.count_eq_zero.mpr (by simpa using hx)).symm
  have hs : ∑ v ∈ ({1, 2, 3, 4} : Finset ℕ), Multiset.count v M • v ^ 2 = 24 := by
    rw [← hsq, Finset.sum_multiset_map_count]
    exact (Finset.sum_subset hsub fun x _ hx => by
      simp [Multiset.count_eq_zero.mpr (by simpa using hx)]).symm
  simp only [smul_eq_mul] at hs
  norm_num at hc hs
  have key : 3 * Multiset.count 2 M + 8 * Multiset.count 3 M + 15 * Multiset.count 4 M = 12 := by
    omega
  have h4 : Multiset.count 4 M = 0 := by omega
  have h3 : Multiset.count 3 M = 0 := by
    rcases Nat.lt_or_ge (Multiset.count 3 M) 2 with h | h
    · interval_cases h' : Multiset.count 3 M <;> omega
    · omega
  have h1 : Multiset.count 1 M = 8 := by omega
  have h2 : Multiset.count 2 M = 4 := by omega
  refine Multiset.ext.mpr fun a => ?_
  by_cases ha1 : a = 1
  · subst ha1; rw [h1]; decide
  by_cases ha2 : a = 2
  · subst ha2; rw [h2]; decide
  have hM : Multiset.count a M = 0 := by
    by_contra h
    have hmem : a ∈ M := Multiset.count_ne_zero.mp h
    have hmem' := hsub (Multiset.mem_toFinset.mpr hmem)
    simp only [Finset.mem_insert, Finset.mem_singleton] at hmem'
    rcases hmem' with h' | h' | h' | h' <;> subst h' <;> omega
  rw [hM]
  refine (Multiset.count_eq_zero.mpr ?_).symm
  simp [d6hIrrepDims]
  omega

end Chem

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

