import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

/-! ## The molecular point group of benzene

Benzene (C₆H₆) is a planar regular hexagon, whose point group is `D₆ₕ`.
As an abstract group `D₆ₕ ≅ D₆ × Cᵢ`, i.e. the dihedral group of order `12`
(the symmetries of the hexagon) times the two-element group generated by the
inversion centre `i`. -/

/-- The point group `D₆ₕ`, realized as `D₆ × Cᵢ` (a group of order `24`). -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- The order of `D₆ₕ` is `24`. -/

def d6hClassSize : Fin 12 → ℕ := ![1, 2, 2, 1, 3, 3, 1, 2, 2, 1, 3, 3]

/-- The character table of `D₆ₕ`.

Rows are the twelve irreducible representations
`A₁g, A₂g, B₁g, B₂g, E₁g, E₂g, A₁u, A₂u, B₁u, B₂u, E₁u, E₂u`
and columns are the twelve conjugacy classes
`E, 2C₆, 2C₃, C₂, 3C₂', 3C₂'', i, 2S₃, 2S₆, σₕ, 3σ_d, 3σ_v`.
All characters of `D₆ₕ` are rational integers, so the table is `ℤ`-valued. -/
