/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

namespace Chem

/-- The molecular point group of benzene, `D₆ₕ`, realised concretely as the direct
product of the dihedral group of order 12 (the rotations/reflections `D₆` acting on the
carbon hexagon) with the two–element group generated by the inversion centre `i`.
It has order 24. -/
abbrev D6h := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- The 12 irreducible representations of `D₆ₕ` appearing in its character table. -/
inductive D6hIrrep
  | A1g | A2g | B1g | B2g | E1g | E2g
  | A1u | A2u | B1u | B2u | E1u | E2u
  deriving DecidableEq, Fintype, Repr

/-- The dimension (degeneracy) of each irreducible representation of `D₆ₕ`:
the `A` and `B` species are one–dimensional, the `E` species are two–dimensional. -/

def D6hIrrep.dim : D6hIrrep → ℕ
  | .A1g | .A2g | .B1g | .B2g | .A1u | .A2u | .B1u | .B2u => 1
  | .E1g | .E2g | .E1u | .E2u => 2

/-- **Benzene (`D₆ₕ`) character table: correct number of irreducible representations.**

The number of irreducible representations listed in the `D₆ₕ` character table (the 12
Mulliken symbols `A₁g, A₂g, B₁g, B₂g, E₁g, E₂g, A₁u, A₂u, B₁u, B₂u, E₁u, E₂u`) equals the
number of conjugacy classes of the group `D₆ₕ`, namely 12
(`E, 2C₆, 2C₃, C₂, 3C₂', 3C₂'', i, 2S₃, 2S₆, σ_h, 3σ_d, 3σ_v`).

Additionally the dimension theorem holds: the sum of the squares of the dimensions of the
irreducible representations equals the order 24 of the group. -/
