/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

set_option maxRecDepth 100000

namespace Chem

/-! ## The point group -/

/-- The molecular point group `D₆ₕ` of benzene, realized abstractly as the direct product
of the dihedral group `D₆` (of order 12: the rotations `C₆ⁿ` together with the six in-plane
`C₂` axes) with the order-two group generated by the inversion centre `i`. -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- `D₆ₕ` has order 24. -/

def D6hIrrep.dim : D6hIrrep → ℕ
  | .A1g | .A2g | .B1g | .B2g | .A1u | .A2u | .B1u | .B2u => 1
  | .E1g | .E2g | .E1u | .E2u => 2

/-- The sizes of the twelve conjugacy classes of `D₆ₕ`, in the conventional order
`E, 2C₆, 2C₃, C₂, 3C₂', 3C₂'', i, 2S₃, 2S₆, σ_h, 3σ_d, 3σ_v`. -/
