import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 10000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

open Matrix CategoryTheory

/-! ## The point group `D₆ₕ`

The molecular point group of benzene, `D₆ₕ`, is the direct product of the dihedral group `D₆`
(of order 12: six rotations `Cₙ` about the principal axis together with six twofold axes)
with the two element group generated by the inversion centre `i`.  It has order 24. -/

/-- The point group `D₆ₕ = D₆ × Cᵢ`, of order `24`. -/
abbrev D6h := DihedralGroup 6 × Multiplicative (ZMod 2)

instance : Fintype D6h := inferInstanceAs (Fintype (DihedralGroup 6 × Multiplicative (ZMod 2)))


def dihHom {R S : M} (h6 : R ^ 6 = 1) (hS : S * S = 1) (hrel : S * R * S = R ^ 5) :
    DihedralGroup 6 →* M where
  toFun := dihMap R S
  map_one' := by show zmodPow R 0 = 1; simp
  map_mul' := by
    rintro (i | i) (j | j) <;> simp only [DihedralGroup.r_mul_r, DihedralGroup.r_mul_sr,
      DihedralGroup.sr_mul_r, DihedralGroup.sr_mul_sr, dihMap]
    · exact zmodPow_mul h6 i j
    · rw [sub_eq_neg_add, zmodPow_mul h6, ← mul_assoc, ← zmodPow_S h6 hS hrel, mul_assoc]
    · rw [zmodPow_mul h6, mul_assoc]
    · rw [sub_eq_neg_add, zmodPow_mul h6, ← S_zmodPow_S h6 hS hrel i]
      noncomm_ring

end Monoids

/-- The data of a matrix representation of `D₆ₕ`: the images `R` of the basic rotation,
`S` of a reflection and `e` of the inversion (a sign), subject to the defining relations
of the group. -/
structure IrrData where
  /-- the dimension -/
  d : ℕ
  /-- image of the basic rotation -/
  R : Matrix (Fin d) (Fin d) ℂ
  /-- image of the basic reflection -/
  S : Matrix (Fin d) (Fin d) ℂ
  /-- image of the inversion (a sign) -/
  e : ℂ
  /-- the rotation has order dividing 6 -/
  h6 : R ^ 6 = 1
  /-- the reflection is an involution -/
  hS : S * S = 1
  /-- the dihedral relation -/
  hrel : S * R * S = R ^ 5
  /-- the inversion is an involution -/
  he : e ^ 2 = 1

namespace IrrData

variable (D : IrrData)

/-- The matrix valued homomorphism attached to the data `D`. -/
