import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 10000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

open Matrix CategoryTheory

/-! ## The point group `D₆ₕ`

The molecular point group of benzene, `D₆ₕ`, is the direct product of the dihedral group `D₆`
(of order 12: six rotations `Cₙ` about the principal axis together with six twofold axes)
with the two element group generated by the inversion centre `i`.  It has order 24. -/

/-- The point group `D₆ₕ = D₆ × Cᵢ`, of order `24`. -/
abbrev D6h := DihedralGroup 6 × Multiplicative (ZMod 2)

instance : Fintype D6h := inferInstanceAs (Fintype (DihedralGroup 6 × Multiplicative (ZMod 2)))


def hom : D6h →* Matrix (Fin D.d) (Fin D.d) ℂ where
  toFun := fun p => zmodPowHom D.he p.2 • dihHom D.h6 D.hS D.hrel p.1
  map_one' := by simp
  map_mul' := by
    rintro ⟨g, u⟩ ⟨g', u'⟩
    simp only [Prod.fst_mul, Prod.snd_mul, map_mul, ← mul_smul_mul_comm]

/-- The representation of `D₆ₕ` on `ℂ^d` attached to the data `D`. -/
