/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

/-! ## The molecular symmetry group of benzene

Benzene has point group `D₆ₕ`, which is the direct product of the dihedral group of order 12
(the symmetries of the regular hexagon) with the two-element group generated by the inversion
`i` (equivalently, `D₆ₕ ≅ D₆ × Cᵢ`, of order 24). -/

/-- The point group `D₆ₕ` of benzene, realized as `D₆ × C₂`. -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- Index type used both for the conjugacy classes (columns) and for the irreducible
characters (rows) of the character table of `D₆ₕ`.  The first component indexes the six
classes/irreps of `D₆`, the second the two of `Cᵢ` (gerade `g` = `0`, ungerade `u` = `1`). -/
abbrev Idx : Type := Fin 6 × Fin 2

/-- Representatives of the twelve conjugacy classes of `D₆ₕ`.  In chemical notation the
`D₆`-part runs through `E, 2C₆, 2C₃, C₂, 3C₂', 3C₂''` and the `Cᵢ`-part through `1, i`, giving
`E, 2C₆, 2C₃, C₂, 3C₂', 3C₂'', i, 2S₃, 2S₆, σ_h, 3σ_d, 3σ_v`. -/

theorem rho2_trace_eq_charTable (m : Fin 2) (e : Fin 2) (c : Idx) :
    (rho2 (m.val + 1) e (classRep c)).trace = charTable (⟨m.val + 4, by omega⟩, e) c := by
  revert m e c; decide

/-! ## Main theorem -/

/-- **The character table of `D₆ₕ` (benzene) has the correct number of irreducible
representations, namely the number of conjugacy classes.**

Concretely we prove, for `D₆ₕ = D₆ × Cᵢ` of order `24`:

* `D₆ₕ` has exactly `12` conjugacy classes, and the listed representatives `classRep`
  biject with them, with the listed class sizes;
* the tabulated character table has exactly `12` rows, one for each class;
* the rows satisfy the first and second orthogonality relations, hence are linearly
  independent, so no further irreducible character can exist;
* the degrees `1,1,1,1,1,1,1,1,2,2,2,2` satisfy `∑ dᵢ² = 24 = |D₆ₕ|`. -/
