/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

/-! ## The point group D₆ₕ

The molecular point group of benzene is `D₆ₕ ≅ D₆ × {E, i}`, the direct product of the
dihedral group of order 12 with the two-element group generated by the inversion centre.
-/

/-- The point group `D₆ₕ` of benzene, realised as `D₆ × C_i`. -/
abbrev D6h := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- The parity (`g`/`u`) sign attached to the inversion factor of `D₆ₕ`. -/

theorem sum_dim_sq : (∑ a : Fin 12, dim a ^ 2) = 24 := by decide

/-! ## Main theorem -/

/-- **Character table of D₆ₕ (benzene).**

The data `chi : Fin 12 → D6h → ℤ` is a genuine character table for the point group `D₆ₕ` of
benzene, and it has the correct number of rows:

* the number of irreducible representations listed (12) equals the number of conjugacy
  classes of `D₆ₕ`;
* each listed character is a class function;
* the listed characters satisfy the first orthogonality relation, hence they are irreducible
  and pairwise inequivalent;
* the sum of the squares of their dimensions equals `|D₆ₕ| = 24`, so the list is complete.
-/
