import Mathlib

/-!
# Goldstone
Category: Frontier Phys
Target: Phys.goldstone
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.letVarTypes true
set_option pp.funBinderTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Phys

open NormedSpace

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- **Infinitesimal (Noether) form of a continuous symmetry.**
If `V` is differentiable and invariant under a one-parameter family of transformations
`Φ t` with `Φ 0 = id` whose velocity field at `t = 0` is `A`, then the gradient of `V`
annihilates the symmetry direction `A x` at every field configuration `x`. -/

theorem goldstone_of_infinitesimal_invariance {V : E → ℝ} {A : E →L[ℝ] E} {x₀ : E}
    {D : E → (E →L[ℝ] ℝ)} {B : E →L[ℝ] (E →L[ℝ] ℝ)}
    (hD : ∀ x : E, HasFDerivAt V (D x) x) (hB : HasFDerivAt D B x₀)
    (hinv : ∀ x : E, D x (A x) = 0) (hvac : IsLocalMin V x₀) (hne : A x₀ ≠ 0) :
    ∃ v : E, v ≠ 0 ∧ (∀ w : E, B v w = 0) ∧ (∀ w : E, B w v = 0) := by
  -- The vacuum is a stationary point of the potential.
  have hstat : D x₀ = 0 := by
    have h := hvac.fderiv_eq_zero
    rwa [(hD x₀).fderiv] at h
  refine ⟨A x₀, hne, ?_, fun w => hessian_apply_generator_eq_zero hB hinv hstat w⟩
  intro w
  rw [second_derivative_symmetric (f := V) (f' := D) (f'' := B) hD hB (A x₀) w]
  exact hessian_apply_generator_eq_zero hB hinv hstat w

/-- **Goldstone's theorem (classical / effective-potential form).**

Let `V` be a twice-differentiable potential on a real Banach space of field
configurations (`D` is its gradient field and `B` its Hessian, i.e. mass matrix, at `x₀`),
invariant under the continuous one-parameter group of global symmetries
`x ↦ exp (t • A) x` generated by the bounded operator `A`.  Suppose `x₀` is a vacuum
(a local minimum of `V`) which is *not* invariant under the symmetry, i.e. the symmetry
is spontaneously broken.

Then the mass matrix has a nonzero vector in its kernel: the direction `A x₀` along the
broken symmetry orbit is a massless mode — the Goldstone boson. -/
