/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4070a4e0-fcbb-4af0-b685-6c0f1b3d72a5

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Matrix Classical
open Finset Matrix SimpleGraph Real

variable {V : Type*} [Fintype V] [DecidableEq V]

/-! ## Part 1: Graph Laplacian - Using Mathlib Built-ins -/

/-- Laplacian matrix (using Mathlib's built-in) -/
abbrev laplacianMatrix (G : SimpleGraph V) : Matrix V V ℝ :=
  G.lapMatrix ℝ

/-- Laplacian is symmetric -/

theorem edge_bound_of_epsilon_light (G : SimpleGraph V) (S : Finset V) (ε : ℝ)
    (h : IsEpsilonLight G S ε) :
    2 * (internalEdges G S : ℝ) ≤ ε * (boundaryEdges G S : ℝ) := by
      -- Substitute the expressions for the quadratic forms into the inequality using the theorems `indicator_laplacian_internal` and `indicator_laplacian_full`.
      have h_subst : (indicatorVec S) ⬝ᵥ ((ε • laplacianMatrix G - inducedLaplacian G S) *ᵥ (indicatorVec S)) ≥ 0 := by
        -- By definition of IsEpsilonLight, we know that the quadratic form is non-negative for any vector.
        apply h.2;
      -- Apply the theorems that relate the quadratic forms to the number of internal and boundary edges.
      have h_quad_forms : (indicatorVec S) ⬝ᵥ ((ε • laplacianMatrix G - inducedLaplacian G S) *ᵥ (indicatorVec S)) = ε * (boundaryEdges G S : ℝ) - 2 * (internalEdges G S : ℝ) := by
        have h_quad_forms : (indicatorVec S) ⬝ᵥ ((ε • laplacianMatrix G - inducedLaplacian G S) *ᵥ (indicatorVec S)) = ε * ((indicatorVec S) ⬝ᵥ ((laplacianMatrix G) *ᵥ (indicatorVec S))) - ((indicatorVec S) ⬝ᵥ ((inducedLaplacian G S) *ᵥ (indicatorVec S))) := by
          simp +decide [ Matrix.sub_mulVec, Matrix.smul_eq_diagonal_mul ];
          simp +decide [ Matrix.mulVec, dotProduct ];
          simp +decide only [mul_assoc, Finset.mul_sum _ _ _, mul_left_comm];
        rw [ h_quad_forms, indicator_laplacian_full, indicator_laplacian_internal ];
      linarith

/-! ## Part 5: The Golden Ratio -/

/-- The golden ratio φ = (1 + sqrt 5) / 2 ≈ 1.618034 -/
noncomputable def φ : ℝ := (1 + sqrt 5) / 2

