/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4070a4e0-fcbb-4af0-b685-6c0f1b3d72a5

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Matrix Classical
open Finset Matrix SimpleGraph Real

variable {V : Type*} [Fintype V] [DecidableEq V]

/-! ## Part 1: Graph Laplacian - Using Mathlib Built-ins -/

/-- Laplacian matrix (using Mathlib's built-in) -/
abbrev laplacianMatrix (G : SimpleGraph V) : Matrix V V ℝ :=
  G.lapMatrix ℝ

/-- Laplacian is symmetric -/

theorem laplacian_quadratic_form_edges (G : SimpleGraph V) (x : V → ℝ) :
    x ⬝ᵥ (laplacianMatrix G *ᵥ x) =
    ∑ e ∈ G.edgeFinset, Sym2.lift ⟨fun u v => (x u - x v)^2, by intro; ring_nf; (
    exact?)⟩ e := by
  simp [dotProduct, laplacianMatrix, SimpleGraph.lapMatrix, Matrix.mulVec]
  simp [SimpleGraph.degMatrix, SimpleGraph.adjMatrix]
  -- Expand degree matrix contribution
  have deg_contrib : ∑ v, (G.degree v : ℝ) * x v^2 =
                     ∑ v, ∑ u ∈ G.neighborFinset v, x v^2 := by
    congr 1
    ext v
    simp [SimpleGraph.degree, SimpleGraph.neighborFinset]
  -- Expand adjacency matrix contribution
  have adj_contrib : ∑ v, ∑ u, (if G.Adj v u then x v * x u else 0) =
                     ∑ e ∈ G.edgeFinset, 2 * (Sym2.lift ⟨fun u v => x u * x v, by intro; ring_nf; (
                     -- The goal is trivially true since True is always true.
                     simp [True])⟩ e) := by
    have h_double_count : ∑ v : V, ∑ u ∈ G.neighborFinset v, x v * x u = ∑ e ∈ G.edgeFinset, 2 * (Sym2.lift ⟨fun u v => x u * x v, fun u v => by simp +decide [ mul_comm ]⟩ e) := by
      have h_double_count : ∑ v : V, ∑ u ∈ G.neighborFinset v, x v * x u = ∑ e ∈ G.edgeFinset, (x (e.out.1) * x (e.out.2) + x (e.out.2) * x (e.out.1)) := by
        have h_double_count : ∀ v : V, ∑ u ∈ G.neighborFinset v, x v * x u = ∑ e ∈ G.edgeFinset, (if e.out.1 = v then x v * x e.out.2 else if e.out.2 = v then x v * x e.out.1 else 0) := by
          intro v
          have h_double_count : ∑ u ∈ G.neighborFinset v, x v * x u = ∑ e ∈ G.edgeFinset, (if e.out.1 = v then x v * x e.out.2 else if e.out.2 = v then x v * x e.out.1 else 0) := by
            have h_neighbor : G.neighborFinset v = Finset.image (fun e => if e.out.1 = v then e.out.2 else e.out.1) (Finset.filter (fun e => e.out.1 = v ∨ e.out.2 = v) G.edgeFinset) := by
              ext u; simp [SimpleGraph.neighborFinset];
              constructor <;> intro h;
              · use Sym2.mk (v, u);
                have := Quot.out_eq ( s(v, u) );
                rcases h : Quot.out ( s(v, u) ) with ⟨ a, b ⟩ ; aesop;
              · -- Since $a$ is in the edge set of $G$, we have $G.Adj (Quot.out a).1 (Quot.out a).2$.
                obtain ⟨a, ha₁, ha₂⟩ := h;
                have h_adj : G.Adj (Quot.out a).1 (Quot.out a).2 := by
                  rw [ ← SimpleGraph.mem_edgeSet ] ; aesop;
                split_ifs at ha₂ <;> simp_all +decide [ SimpleGraph.adj_comm ]
            rw [ h_neighbor, Finset.sum_image ];
            · rw [ Finset.sum_filter ] ; congr ; ext ; aesop;
            · -- To prove injectivity, assume two edges $e$ and $f$ map to the same vertex. We need to show $e = f$.
              intro e he f hf h_eq
              have h_cases : e.out.1 = v ∧ f.out.1 = v ∨ e.out.2 = v ∧ f.out.2 = v := by
                -- Since $e$ and $f$ are edges in the graph, and their out components are equal, this implies that $e$ and $f$ are the same edge.
                have h_eq_edge : e = f := by
                  rw [ ← Quot.out_eq e, ← Quot.out_eq f ];
                  exact Quot.sound ( by aesop );
                grind +ring;
              cases h_cases <;> simp_all +decide [ Sym2.eq ];
              · rw [ ← Quot.out_eq e, ← Quot.out_eq f ];
                exact Quot.sound ( by aesop );
              · -- Since $e$ and $f$ are both in the edge set and their second components are $v$, they must be the same edge.
                have h_eq_edges : e = Sym2.mk (v, (Quot.out e).1) ∧ f = Sym2.mk (v, (Quot.out f).1) := by
                  exact ⟨ by rw [ ← Quot.out_eq e ] ; exact Quot.sound ( by aesop ), by rw [ ← Quot.out_eq f ] ; exact Quot.sound ( by aesop ) ⟩;
                grind +ring;
          convert h_double_count using 1;
        rw [ Finset.sum_congr rfl fun v hv => h_double_count v, Finset.sum_comm ];
        refine' Finset.sum_congr rfl fun e he => _;
        rw [ Finset.sum_eq_add ( Quot.out e |>.1 ) ( Quot.out e |>.2 ) ] <;> simp +decide [ mul_comm ];
        · exact fun h => Or.inl ( by rw [ h ] );
        · convert G.ne_of_adj _;
          convert G.mem_edgeFinset.mp he;
          rw [ ← SimpleGraph.mem_edgeSet ];
          simp +decide [ Sym2.eq_swap ];
        · grind +ring;
      convert h_double_count using 2 ; simp +decide [ two_mul, Sym2.lift ];
      rename_i e he;
      rw [ ← Quot.out_eq e ] ; simp +decide [ mul_comm ] ;
      rfl;
    convert h_double_count using 1;
    simp +decide [ Finset.sum_ite, SimpleGraph.neighborFinset ];
    simp +decide [ SimpleGraph.neighborSet ] -- Edge enumeration
  -- Combine using (x_v - x_u)^2 = x_v^2 + x_u^2 - 2x_v*x_u
  convert congr_arg₂ ( · - · ) deg_contrib adj_contrib using 1 <;> simp +decide [ Finset.sum_ite, Finset.filter_ne, Finset.filter_congr, Finset.mul_sum _ _ _, mul_assoc, mul_comm, mul_left_comm, sub_mul, Finset.sum_mul, sq ] ; ring!;
  · -- By definition of matrix multiplication and the properties of the diagonal matrix, we can split the sum into two parts: one involving the degree matrix and one involving the adjacency matrix.
    simp [Matrix.diagonal] at *;
    simp +decide [ sq, Finset.sum_ite ];
  · have h_deg : ∑ v, x v ^ 2 * (G.degree v : ℝ) = ∑ e ∈ G.edgeFinset, (Sym2.lift ⟨fun u v => x u ^ 2 + x v ^ 2, fun u v => by ring⟩ e) := by
      have h_deg : ∑ v, x v ^ 2 * (G.degree v : ℝ) = ∑ e ∈ G.edgeFinset, (Sym2.lift ⟨fun u v => x u ^ 2 + x v ^ 2, fun u v => by ring⟩ e) := by
        have h_deg : ∀ v, x v ^ 2 * (G.degree v : ℝ) = ∑ e ∈ G.incidenceFinset v, x v ^ 2 := by
          simp +decide [ mul_comm, SimpleGraph.incidenceSet ]
        simp +decide only [h_deg];
        have h_deg : ∑ v, ∑ e ∈ G.incidenceFinset v, x v ^ 2 = ∑ e ∈ G.edgeFinset, ∑ v ∈ e.toFinset, x v ^ 2 := by
          rw [ Finset.sum_sigma', Finset.sum_sigma' ];
          refine' Finset.sum_bij ( fun e _ => ⟨ e.2, e.1 ⟩ ) _ _ _ _ <;> simp +decide [ SimpleGraph.incidenceSet ];
          · bound;
          · exact fun b hb hb' => ⟨ _, _, ⟨ hb, hb' ⟩, rfl ⟩;
        convert h_deg using 2;
        rename_i e he; rcases e with ⟨ u, v ⟩ ; simp +decide [ Finset.sum_pair, Sym2.lift ] ; ring;
        rw [ Finset.sum_eq_add ] <;> aesop;
      convert h_deg using 1;
    convert congr_arg₂ ( · - · ) h_deg adj_contrib using 1 <;> ring!;
    · rw [ h_deg, adj_contrib ] ; ring!;
      rw [ ← Finset.sum_sub_distrib ] ; congr ; ext ; ring;
      rename_i e; induction e using Sym2.inductionOn; norm_num; ring;
    · rw [ h_deg, neg_add_eq_sub ]

/-- Induced Laplacian on subset S (Corrected to Adjacency for consistency with theorems) -/
