/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f54d6b76-2372-4f3c-b43a-e2db433bc48b

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Matrix
open Finset Matrix SimpleGraph Real


theorem pentagon_is_regular : IsRegularGraph pentagon 2 := by
  intro v
  -- We need to show vertexDegree pentagon v = 2
  -- vertexDegree is count of neighbors.
  -- Neighbors of v are (v+1)%5 and (v-1)%5.
  -- Since 5 > 2, these are distinct.
  rw [vertexDegree]
  have : (Finset.univ.filter (fun u => pentagon.Adj v u)).card = 2 := by
    -- By definition of the pentagon graph, each vertex has exactly two neighbors.
    have h_deg : ∀ v : Fin 5, Finset.card (Finset.filter (fun u => pentagon.Adj v u) Finset.univ) = 2 := by
      -- By definition of the pentagon graph, each vertex has exactly two neighbors. We can verify this by checking each vertex individually.
      intro v
      fin_cases v <;> simp +decide [pentagon];
      · simp +decide [ SimpleGraph.cycleGraph ];
      · simp +decide [ SimpleGraph.cycleGraph ];
      · simp +decide [ SimpleGraph.cycleGraph ];
      · simp +decide [ SimpleGraph.cycleGraph ];
      · simp +decide [ SimpleGraph.cycleGraph ];
    exact h_deg v
  exact this

