/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 0618081f-b038-4d49-bb66-f719db93b30b

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Classical Pointwise

/-
The primitive 5th root of unity: ζ₅ = exp(2πi/5)
-/

lemma degree_bound (gamma : Fin 5 → ℝ) (u : PenroseTilingVertices gamma) :
    (PenroseGraph gamma).degree u ≤ 10 := by
  have h_degree_le_10 : ∀ u : PenroseTilingVertices gamma, 
      (PenroseGraph gamma).degree u ≤ (potentialNeighbors u.1).ncard := by
    intro u
    have h_subset : (PenroseGraph gamma).neighborSet u ⊆ 
        {v : PenroseTilingVertices gamma | v.1 ∈ potentialNeighbors u.1} := by
      exact neighbor_subset_potential gamma u
    have h_card : (Set.ncard {v : PenroseTilingVertices gamma | v.1 ∈ potentialNeighbors u.1}) ≤ 
        (potentialNeighbors u.1).ncard := by
      have h_card : (Set.ncard (Set.image (fun v : PenroseTilingVertices gamma => v.1) 
          {v : PenroseTilingVertices gamma | v.1 ∈ potentialNeighbors u.1})) ≤ 
          (potentialNeighbors u.1).ncard := by
        apply Set.ncard_le_ncard
        · aesop_cat
        · exact potentialNeighbors_finite _
      rwa [Set.ncard_image_of_injective _ fun x y hxy => by aesop] at h_card
    refine le_trans ?_ h_card
    rw [Set.ncard_def, Set.encard, ENat.card, SimpleGraph.degree, ← Set.ncard_coe_finset]
    rw [Set.ncard_def, Set.encard, ENat.card]
    gcongr
    · simp +zetaDelta at *
      exact Set.Finite.subset (Set.Finite.preimage (fun x => by aesop) 
        (potentialNeighbors_finite u.1)) fun x hx => hx
    · exact Cardinal.mk_le_mk_of_subset fun x hx => h_subset <| by simpa using hx
  exact le_trans (h_degree_le_10 u) (potentialNeighbors_card_le_10 u.1)

/-
Raw adjacency operator: sum over neighbors
-/
