/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-!
## Formalizing the restricted Burnside problem

The *restricted Burnside problem* for parameters `m n : ℕ` asks whether there is a uniform bound
on the order of the finite groups that are generated by `m` elements and have exponent dividing
`n`.  Zelmanov's theorem (Fields Medal 1994) says that the answer is positive for all `m` and `n`.

Below we

* formalize the statement, `Frontier.RestrictedBurnside`;
* build the relevant universal object, the free Burnside group `Frontier.BurnsideGroup m n`,
  and prove the standard reduction of the problem to a statement about the finite quotients of
  that single group (`Frontier.restrictedBurnside_iff_boundedBurnsideQuotients`);
* prove the elementary base cases `n ≤ 2`, `m ≤ 1`.

The full theorem of Zelmanov (all `m`, `n`) is *not* proved here; the target theorem
`Frontier.zelmanov_restricted_burnside` collects the reduction together with the base cases.
-/

/-- `G` is generated by (at most) `m` elements. -/

def burnsideRels (m n : ℕ) : Set (FreeGroup (Fin m)) :=
  Set.range fun x : FreeGroup (Fin m) => x ^ n

/-- The free Burnside group `B(m, n)`: the free group on `m` generators modulo the normal closure
of all `n`-th powers. -/
abbrev BurnsideGroup (m n : ℕ) : Type := PresentedGroup (burnsideRels m n)

/-- Uniform bound on the finite quotients of the free Burnside group `B(m, n)`. -/
