import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Frontier

/-- `RestrictedBurnside m n` is the statement of the *restricted Burnside problem* for
`m` generators and exponent `n`: there is a uniform bound `N` on the order of every finite
group that is generated by `m` elements and has exponent dividing `n`.

(Equivalently, there are only finitely many isomorphism classes of such groups.)
Zelmanov's theorem asserts that `RestrictedBurnside m n` holds for all `m` and all `n ≥ 1`. -/

theorem card_commutator_le {m n : ℕ} (hn : 0 < n) (g : Fin m → G)
    (hgen : Subgroup.closure (Set.range g) = ⊤) (hexp : ∀ x : G, x ^ n = 1)
    (hcent : commutator G ≤ Subgroup.center G) :
    Nat.card (commutator G) ≤ n ^ (m * m) := by
  have hc : ∀ a b : G, ⁅a, b⁆ ∈ Subgroup.center G := fun a b =>
    hcent (Subgroup.commutator_mem_commutator (Subgroup.mem_top a) (Subgroup.mem_top b))
  set c : Fin m × Fin m → G := fun p => ⁅g p.1, g p.2⁆ with hcdef
  have hset : {x : G | ∃ s ∈ Set.range g, ∃ t ∈ Set.range g, ⁅s, t⁆ = x} = Set.range c := by
    ext x
    constructor
    · rintro ⟨s, ⟨i, rfl⟩, t, ⟨j, rfl⟩, rfl⟩
      exact ⟨(i, j), rfl⟩
    · rintro ⟨p, rfl⟩
      exact ⟨g p.1, ⟨p.1, rfl⟩, g p.2, ⟨p.2, rfl⟩, rfl⟩
  have hK : commutator G = Subgroup.closure (Set.range c) := by
    refine le_antisymm ?_ ?_
    · have := commutator_le_closure_of_central hgen hc
      rwa [hset] at this
    · rw [Subgroup.closure_le]
      rintro x ⟨p, rfl⟩
      exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)
  set K := Subgroup.closure (Set.range c) with hKdef
  have hKcent : (K : Set G) ⊆ Subgroup.center G := fun x hx => hcent (hK ▸ hx)
  letI : CommGroup K := { (inferInstance : Group K) with
    mul_comm := by
      intro a b
      refine Subtype.ext ?_
      push_cast
      exact (Subgroup.mem_center_iff.mp (hKcent a.2) b).symm }
  let v : Fin m × Fin m → K := fun p => ⟨c p, Subgroup.subset_closure ⟨p, rfl⟩⟩
  have hgenK : Subgroup.closure (Set.range v) = ⊤ := by
    have h := Subgroup.closure_closure_coe_preimage (k := Set.range c)
    rwa [show (Subtype.val ⁻¹' Set.range c : Set K) = Set.range v by
      ext x
      constructor
      · rintro ⟨p, hp⟩
        exact ⟨p, Subtype.ext hp⟩
      · rintro ⟨p, rfl⟩
        exact ⟨p, rfl⟩] at h
  have hexpK : ∀ x : K, x ^ n = 1 := fun x => Subtype.ext (by simpa using hexp (x : G))
  have hcard := card_le_of_commGroup (G := K) hn v hgenK hexpK
  rw [hK]
  simpa using hcard

/-- An `m`-generated group of exponent dividing `n > 0` and nilpotency class at most `2` has
order at most `n ^ m * n ^ (m * m)`. -/
