import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Frontier

/-- `RestrictedBurnside m n` is the statement of the *restricted Burnside problem* for
`m` generators and exponent `n`: there is a uniform bound `N` on the order of every finite
group that is generated by `m` elements and has exponent dividing `n`.

(Equivalently, there are only finitely many isomorphism classes of such groups.)
Zelmanov's theorem asserts that `RestrictedBurnside m n` holds for all `m` and all `n ≥ 1`. -/

theorem card_le_of_commGroup {G : Type} [CommGroup G] {ι : Type} [Finite ι] {n : ℕ} (hn : 0 < n)
    (g : ι → G) (hgen : Subgroup.closure (Set.range g) = ⊤)
    (hexp : ∀ x : G, x ^ n = 1) : Nat.card G ≤ n ^ Nat.card ι := by
  haveI : NeZero n := ⟨hn.ne'⟩
  haveI : Fintype ι := Fintype.ofFinite ι
  have hnsmul : ∀ x : Additive G, n • x = 0 := fun x => by simpa using hexp (Additive.toMul x)
  haveI : Module (ZMod n) (Additive G) := AddCommGroup.zmodModule hnsmul
  let v : ι → Additive G := fun i => Additive.ofMul (g i)
  have hclos : AddSubgroup.closure (Set.range v) = ⊤ := by
    have := congrArg Subgroup.toAddSubgroup hgen
    rw [Subgroup.toAddSubgroup_closure] at this
    simpa [v, Set.ext_iff] using this
  have hspan : Submodule.span (ZMod n) (Set.range v) = ⊤ := by
    rw [Submodule.eq_top_iff']
    intro x
    have hle : AddSubgroup.closure (Set.range v) ≤
        (Submodule.span (ZMod n) (Set.range v)).toAddSubgroup :=
      AddSubgroup.closure_le _ |>.mpr Submodule.subset_span
    rw [hclos] at hle
    exact hle (AddSubgroup.mem_top x)
  have hsurj : Function.Surjective ⇑(Fintype.linearCombination (ZMod n) v) := by
    rw [← LinearMap.range_eq_top, Fintype.range_linearCombination, hspan]
  have h1 := Nat.card_le_card_of_surjective _ hsurj
  rwa [Nat.card_fun, Nat.card_eq_fintype_card (α := ZMod n), ZMod.card,
    Nat.card_congr (Additive.toMul)] at h1

/-- A group of exponent `2` is commutative. -/
