import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Frontier

/-- `RestrictedBurnside m n` is the statement of the *restricted Burnside problem* for
`m` generators and exponent `n`: there is a uniform bound `N` on the order of every finite
group that is generated by `m` elements and has exponent dividing `n`.

(Equivalently, there are only finitely many isomorphism classes of such groups.)
Zelmanov's theorem asserts that `RestrictedBurnside m n` holds for all `m` and all `n ≥ 1`. -/

theorem card_abelianization_le {m n : ℕ} (hn : 0 < n) (g : Fin m → G)
    (hgen : Subgroup.closure (Set.range g) = ⊤) (hexp : ∀ x : G, x ^ n = 1) :
    Nat.card (Abelianization G) ≤ n ^ m := by
  have hsurj : Function.Surjective (Abelianization.of (G := G)) :=
    fun y => Quot.inductionOn y fun x => ⟨x, rfl⟩
  have hgen' : Subgroup.closure (Set.range fun i => Abelianization.of (g i)) = ⊤ := by
    rw [show (Set.range fun i => Abelianization.of (g i))
        = (Abelianization.of (G := G)) '' Set.range g by rw [← Set.range_comp]; rfl,
      ← MonoidHom.map_closure, hgen, Subgroup.map_top_of_surjective _ hsurj]
  have hexp' : ∀ y : Abelianization G, y ^ n = 1 := by
    intro y
    obtain ⟨x, rfl⟩ := hsurj y
    rw [← map_pow, hexp x, map_one]
  simpa using card_le_of_commGroup hn (fun i => Abelianization.of (g i)) hgen' hexp'

/-- In an `m`-generated group of exponent dividing `n > 0` and nilpotency class at most `2`, the
commutator subgroup has order at most `n ^ (m * m)`. -/
