/-
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-!
## The restricted Burnside property

`RestrictedBurnside m n` is the statement that the orders of the finite groups which are
generated by at most `m` elements and satisfy the identity `g ^ n = 1` are bounded by a
single constant `N = N (m, n)`.

Zelmanov's theorem (the positive solution of the restricted Burnside problem) asserts that
`RestrictedBurnside m n` holds for every `m` and every `n ≥ 1`.  Below we formalise the
statement and prove, in a fully checked way:

* the base cases `n = 1` and `n = 2` (for every number `m` of generators),
* the one-generator case `m = 1` (for every exponent `n ≥ 1`),
* the abelian case, in the sharp form `|G| ≤ n ^ m`,
* the standard reductions (monotonicity in the number of generators, and passage to a
  divisor of the exponent),
* the fact that the hypothesis `n ≥ 1` cannot be dropped, i.e. `RestrictedBurnside 1 0`
  is false, which in particular shows that the property is not vacuous.
-/

/-- The restricted Burnside property for `m` generators and exponent `n`: the orders of all
finite groups generated by at most `m` elements and of exponent dividing `n` are bounded by a
uniform constant. -/

theorem card_le_two_pow_of_exponent_two {G : Type} [Group G] [Fintype G] {m : ℕ}
    (hgen : ∃ S : Finset G, S.card ≤ m ∧ Subgroup.closure (S : Set G) = ⊤)
    (hexp : ∀ g : G, g ^ 2 = 1) : Fintype.card G ≤ 2 ^ m := by
  have hcomm : ∀ a b : G, a * b = b * a := by
    intro a b
    exact Commute.of_orderOf_dvd_two (fun g => orderOf_dvd_of_pow_eq_one (hexp g)) a b
  letI : CommGroup G := { (inferInstance : Group G) with mul_comm := hcomm }
  exact card_le_pow_of_abelian (by norm_num) hgen hexp

/-- Exponent `2`, uniform version. -/
