import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Frontier

/-- `RestrictedBurnside m n` is the statement of the *restricted Burnside problem* for
`m` generators and exponent `n`: there is a uniform bound `N` on the order of every finite
group that is generated by `m` elements and has exponent dividing `n`.

(Equivalently, there are only finitely many isomorphism classes of such groups.)
Zelmanov's theorem asserts that `RestrictedBurnside m n` holds for all `m` and all `n ≥ 1`. -/

theorem commutatorElement_inv_left_of_central
    (hc : ∀ a b : G, ⁅a, b⁆ ∈ Subgroup.center G) (x z : G) : ⁅x⁻¹, z⁆ = ⁅x, z⁆⁻¹ := by
  have h := commutatorElement_mul_left_of_central hc x x⁻¹ z
  rw [mul_inv_cancel, commutatorElement_one_left] at h
  exact eq_inv_of_mul_eq_one_right h.symm

/-- In a group of nilpotency class at most `2` generated by a set `S`, the commutator subgroup is
generated by the commutators of the generators. -/
