/-
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true

set_option grind.warning false

namespace Frontier

/-- `IsBurnsideQuotient m n G` says that the group `G` is generated by `m` elements and has
exponent dividing `n`. -/

theorem exists_kernel_of_isBurnsideQuotient (G : Type) [Group G] [Finite G]
    (hG : IsBurnsideQuotient m n G) :
    ∃ N : Subgroup (FreeGroup (Fin m)), IsBurnsideKernel m n N ∧ N.index = Nat.card G := by
  obtain ⟨hexp, f, hf⟩ := hG
  set phi := FreeGroup.lift f with hphi
  have hrange : phi.range = ⊤ := by rw [hphi, FreeGroup.range_lift_eq_closure, hf]
  have hidx : phi.ker.index = Nat.card G := by
    rw [Subgroup.index_ker, hrange, Subgroup.card_top]
  refine ⟨phi.ker, ⟨inferInstance, ?_, ?_⟩, hidx⟩
  · rw [hidx]
    exact Nat.card_pos.ne'
  · intro g
    simp [MonoidHom.mem_ker, hphi, hexp]

/-- Every Burnside kernel is the kernel of a map onto a finite `m`-generated group of
exponent dividing `n`, so under the restricted Burnside property its index is bounded. -/
