/-
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true

set_option grind.warning false

namespace Frontier

/-- `IsBurnsideQuotient m n G` says that the group `G` is generated by `m` elements and has
exponent dividing `n`. -/

def HasUniversalFiniteQuotient (m n : ℕ) : Prop :=
  ∃ N : Subgroup (FreeGroup (Fin m)),
    IsBurnsideKernel m n N ∧ ∀ M : Subgroup (FreeGroup (Fin m)), IsBurnsideKernel m n M → N ≤ M

/-- The restricted Burnside property, for commutative groups. -/
