/-
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true

set_option grind.warning false

namespace Frontier

/-- `IsBurnsideQuotient m n G` says that the group `G` is generated by `m` elements and has
exponent dividing `n`. -/

theorem isBurnsideQuotient_quotient {N : Subgroup (FreeGroup (Fin m))} [N.Normal]
    (hpow : ∀ g : FreeGroup (Fin m), g ^ n ∈ N) :
    IsBurnsideQuotient m n (FreeGroup (Fin m) ⧸ N) := by
  constructor
  · intro q
    induction q using QuotientGroup.induction_on with
    | _ g =>
      rw [← QuotientGroup.mk_pow]
      exact (QuotientGroup.eq_one_iff _).mpr (hpow g)
  · refine ⟨fun i => QuotientGroup.mk (FreeGroup.of i), ?_⟩
    have h1 : Subgroup.map (QuotientGroup.mk' N)
        (Subgroup.closure (Set.range (FreeGroup.of : Fin m → FreeGroup (Fin m)))) =
        Subgroup.closure
          (Set.range fun i => (QuotientGroup.mk (FreeGroup.of i) : FreeGroup (Fin m) ⧸ N)) := by
      rw [MonoidHom.map_closure, ← Set.range_comp]
      rfl
    rw [FreeGroup.closure_range_of] at h1
    rw [← h1, Subgroup.map_top_of_surjective]
    exact QuotientGroup.mk'_surjective N

/-- A normal subgroup of finite index has a finite quotient. -/
