import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

/-
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

set_option autoImplicit false

namespace Frontier

/-!
## The restricted Burnside problem

The restricted Burnside problem asks: for fixed `m` and `n`, is there a common bound on the
order of every finite group that is generated by `m` elements and has exponent dividing `n`?
Equivalently, are there only finitely many isomorphism classes of such groups?  Zelmanov's
theorem (Fields Medal, 1994), building on the Hall–Higman reduction to prime powers and the
classification of finite simple groups, answers this affirmatively.

Below, `RestrictedBurnsideBounded m n` is the order-bound formulation for the pair `(m, n)`,
`RestrictedBurnsideBoundedComm m n` is its restriction to abelian groups, and
`RestrictedBurnsideProblem` is the full statement.  Mathlib contains no form of the restricted
Burnside problem (a search for `Burnside` turns up only unrelated material, such as the
orbit-counting lemma), so the notions are set up here from scratch.

The target theorem `Frontier.zelmanov_restricted_burnside` collects what is proved here in
full, without any appeal to Zelmanov's theorem:

* the base case `n = 1` (trivial groups),
* the base case `m = 1` (cyclic groups: the bound is `n` itself),
* the **abelian case in full generality**: an abelian group generated by `m` elements and of
  exponent dividing `n > 0` has order at most `n ^ m`,
* the base case `n = 2` (elementary abelian `2`-groups: the bound is `2 ^ m`, Burnside's
  original observation),
* the reduction in the number of generators (`m' ≤ m`),
* the reduction along divisors of the exponent (`d ∣ n`).

Proving `RestrictedBurnsideProblem` in general would require formalizing Zelmanov's proof; it
is stated here as a definition, and deliberately not asserted.
-/

/-- `RestrictedBurnsideBounded m n` : there is a bound `B` such that every finite group
generated by at most `m` elements, all of whose elements satisfy `g ^ n = 1`, has order at
most `B`.  (Quantifying over groups in `Type` is no loss of generality: every finite group is
isomorphic to one carried by a type in `Type 0`.) -/

theorem mul_comm_of_exponent_two {G : Type} [Group G] (h2 : ∀ g : G, g ^ 2 = 1) (a b : G) :
    a * b = b * a := by
  have hinv : ∀ g : G, g⁻¹ = g := by
    intro g
    have := h2 g
    rw [pow_two] at this
    exact inv_eq_of_mul_eq_one_right this
  have := hinv (a * b)
  rw [mul_inv_rev, hinv a, hinv b] at this
  exact this.symm

/-- Burnside's base case: `m`-generated groups of exponent `2` are elementary abelian, hence
have order at most `2 ^ m`. -/
