import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Pointwise

set_option maxHeartbeats 1000000

namespace Frontier

/-- `IsGeneratedBy G n` says that the group `G` can be generated by at most `n` elements. -/

theorem not_restrictedBurnside_zero : ¬ RestrictedBurnside 1 0 := by
  rintro ⟨N, hN⟩
  have key := hN (Multiplicative (ZMod (N + 1))) (fun g => pow_zero g) ?_
  · have hc : Fintype.card (Multiplicative (ZMod (N + 1))) = N + 1 := by simp
    omega
  · refine ⟨{Multiplicative.ofAdd 1}, by simp, ?_⟩
    rw [eq_top_iff]
    rintro x -
    have : x ∈ Subgroup.closure ({Multiplicative.ofAdd (1 : ZMod (N + 1))} : Set _) := by
      rw [Subgroup.mem_closure_singleton]
      refine ⟨((Multiplicative.toAdd x).val : ℤ), ?_⟩
      rw [zpow_natCast, ← ofAdd_nsmul]
      simp [nsmul_eq_mul, ZMod.natCast_val, ZMod.cast_id]
    simpa using this

/-- **Zelmanov's restricted Burnside theorem** (formalized statement, with the base cases and
elementary reductions proved).

`RestrictedBurnsideProblem` is the full statement: for every rank `n` and every exponent `e ≥ 1`
there is a uniform bound on the order of the finite `n`-generated groups of exponent dividing `e`.
The theorem below records the Lean-checked content: the statement of the problem, the base cases
`e = 1` (trivial), `e = 2` (Burnside's elementary abelian bound `2 ^ n`) and `n = 1` (cyclic
groups, bound `e`), the reductions in the rank and along divisors of the exponent, and the
necessity of the hypothesis `0 < e`. -/
