/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-!
## Formalizing the restricted Burnside problem

The *restricted Burnside problem* for parameters `m n : ℕ` asks whether there is a uniform bound
on the order of the finite groups that are generated by `m` elements and have exponent dividing
`n`.  Zelmanov's theorem (Fields Medal 1994) says that the answer is positive for all `m` and `n`.

Below we

* formalize the statement, `Frontier.RestrictedBurnside`;
* build the relevant universal object, the free Burnside group `Frontier.BurnsideGroup m n`,
  and prove the standard reduction of the problem to a statement about the finite quotients of
  that single group (`Frontier.restrictedBurnside_iff_boundedBurnsideQuotients`);
* prove the elementary base cases `n ≤ 2`, `m ≤ 1`.

The full theorem of Zelmanov (all `m`, `n`) is *not* proved here; the target theorem
`Frontier.zelmanov_restricted_burnside` collects the reduction together with the base cases.
-/

/-- `G` is generated by (at most) `m` elements. -/

theorem restrictedBurnside_exponent_two (m : ℕ) : RestrictedBurnside m 2 := by
  refine ⟨2 ^ m, fun G _ _ hgen hexp => ?_⟩
  obtain ⟨s, hs⟩ := hgen
  letI : CommGroup G :=
    { (inferInstance : Group G) with mul_comm := mul_comm_of_sq G hexp }
  classical
  have hsurj : Function.Surjective fun T : Finset (Fin m) => ∏ i ∈ T, s i := by
    intro g
    have hg : g ∈ Subgroup.closure (Set.range s) := hs ▸ Subgroup.mem_top g
    induction hg using Subgroup.closure_induction with
    | mem x hx =>
        obtain ⟨i, rfl⟩ := hx
        exact ⟨{i}, by simp⟩
    | one => exact ⟨∅, by simp⟩
    | mul x y _ _ hx hy =>
        obtain ⟨T, hT⟩ := hx
        obtain ⟨U, hU⟩ := hy
        refine ⟨T \ U ∪ U \ T, ?_⟩
        have hc : (∏ i ∈ T ∩ U, s i) * ∏ i ∈ T ∩ U, s i = 1 := by
          have := hexp (∏ i ∈ T ∩ U, s i)
          rwa [pow_two] at this
        simp only at hT hU ⊢
        rw [Finset.prod_union Finset.disjoint_sdiff_sdiff, ← hT, ← hU,
          ← Finset.prod_inter_mul_prod_diff T U s, ← Finset.prod_inter_mul_prod_diff U T s,
          Finset.inter_comm U T, mul_mul_mul_comm, hc, one_mul]
    | inv x _ hx =>
        obtain ⟨T, hT⟩ := hx
        exact ⟨T, by simp only at hT ⊢; rw [hT, inv_eq_self_of_sq G hexp]⟩
  calc Nat.card G ≤ Nat.card (Finset (Fin m)) := Nat.card_le_card_of_surjective _ hsurj
    _ = 2 ^ m := by simp [Nat.card_eq_fintype_card]

/-! ### The target statement -/

/-- **Restricted Burnside (Zelmanov), formalized statement together with a Lean-checked
reduction and the elementary base cases.**

The four components are:

1. the reduction of the restricted Burnside problem for `(m, n)` to a uniform bound on the finite
   quotients of the single free Burnside group `B(m, n)`;
2. the base case of exponent `1`;
3. the base case of rank `0` and the base case of rank `1` (cyclic groups);
4. the base case of exponent `2`, where the bound is `2 ^ m`.

Zelmanov's full theorem — `RestrictedBurnside m n` for *all* `m` and `n` — is not proved here. -/
