/-
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true

set_option grind.warning false

namespace Frontier

/-- `IsBurnsideQuotient m n G` says that the group `G` is generated by `m` elements and has
exponent dividing `n`. -/

theorem restrictedBurnside_of_le {k : ℕ} (hk : k ≤ m) (h : RestrictedBurnside m n) :
    RestrictedBurnside k n := by
  obtain ⟨B, hB⟩ := h
  refine ⟨B, ?_⟩
  rintro G _ _ ⟨hexp, f, hf⟩
  classical
  refine hB G ⟨hexp, fun i : Fin m => if h : (i : ℕ) < k then f ⟨i, h⟩ else 1, ?_⟩
  have hsub : Set.range f ⊆
      Set.range (fun i : Fin m => if h : (i : ℕ) < k then f ⟨i, h⟩ else 1) := by
    rintro x ⟨j, rfl⟩
    refine ⟨⟨j, lt_of_lt_of_le j.2 hk⟩, ?_⟩
    simp [j.2]
  refine eq_top_iff.mpr ?_
  rw [← hf]
  exact Subgroup.closure_mono hsub

/-- **Reduction step.** The restricted Burnside property for `(m, n)` is equivalent to the
existence of a largest finite quotient of the free Burnside group `B(m, n)`. -/
