/-
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true

set_option grind.warning false

namespace Frontier

/-- `IsBurnsideQuotient m n G` says that the group `G` is generated by `m` elements and has
exponent dividing `n`. -/

theorem restrictedBurnside_one_gen (n : ℕ) (hn : 0 < n) : RestrictedBurnside 1 n := by
  refine ⟨n, ?_⟩
  intro G _ _ hG
  obtain ⟨hexp, f, hf⟩ := hG
  have hrange : Set.range f = {f 0} := by
    ext x
    constructor
    · rintro ⟨i, rfl⟩; simp [Subsingleton.elim i 0]
    · rintro rfl; exact ⟨0, rfl⟩
  have htop : Subgroup.zpowers (f 0) = ⊤ := by
    rw [Subgroup.zpowers_eq_closure, ← hrange, hf]
  have hcard : Nat.card G = orderOf (f 0) := by
    rw [← Nat.card_zpowers, htop, Subgroup.card_top]
  rw [hcard]
  exact orderOf_le_of_pow_eq_one hn (hexp (f 0))

/-- **Base case `n = 2`** (Burnside): a group of exponent `2` is abelian, so an
`m`-generated group of exponent dividing `2` has order at most `2 ^ m`. -/
