/-
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true

set_option grind.warning false

namespace Frontier

/-- `IsBurnsideQuotient m n G` says that the group `G` is generated by `m` elements and has
exponent dividing `n`. -/

theorem restrictedBurnsideComm (m n : ℕ) (hn : 0 < n) : RestrictedBurnsideComm m n := by
  intro G _ hG
  obtain ⟨hexp, f, hf⟩ := hG
  haveI : NeZero n := ⟨hn.ne'⟩
  haveI : Module (ZMod n) (Additive G) :=
    AddCommGroup.zmodModule (fun x => by
      simpa [← ofMul_pow] using congrArg Additive.ofMul (hexp (Additive.toMul x)))
  set v : Fin m → Additive G := fun i => Additive.ofMul (f i)
  have key : ∀ g : G, (Additive.ofMul g) ∈ Submodule.span (ZMod n) (Set.range v) := by
    intro g
    have hg : g ∈ Subgroup.closure (Set.range f) := by rw [hf]; trivial
    induction hg using Subgroup.closure_induction with
    | mem y hy =>
        obtain ⟨i, rfl⟩ := hy
        exact Submodule.subset_span (show Additive.ofMul (f i) ∈ Set.range v from ⟨i, rfl⟩)
    | one => exact Submodule.zero_mem _
    | mul y z _ _ ihy ihz => exact Submodule.add_mem _ ihy ihz
    | inv y _ ihy => exact Submodule.neg_mem _ ihy
  have hspan : Submodule.span (ZMod n) (Set.range v) = ⊤ := by
    rw [Submodule.eq_top_iff']
    exact fun x => key (Additive.toMul x)
  have hsurj : Function.Surjective ⇑(Fintype.linearCombination (ZMod n) v) := by
    rw [← LinearMap.range_eq_top, Fintype.range_linearCombination, hspan]
  calc Nat.card G = Nat.card (Additive G) := rfl
    _ ≤ Nat.card (Fin m → ZMod n) := Nat.card_le_card_of_surjective _ hsurj
    _ = n ^ m := by simp

/-- **Base case `n = 1`.** -/
