import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Frontier

/-- `RestrictedBurnside m n` is the statement of the *restricted Burnside problem* for
`m` generators and exponent `n`: there is a uniform bound `N` on the order of every finite
group that is generated by `m` elements and has exponent dividing `n`.

(Equivalently, there are only finitely many isomorphism classes of such groups.)
Zelmanov's theorem asserts that `RestrictedBurnside m n` holds for all `m` and all `n ≥ 1`. -/

theorem restrictedBurnside_zero_generators (n : ℕ) : RestrictedBurnside 0 n := by
  refine ⟨1, fun G _ _ g hgen _ => ?_⟩
  have hg : Set.range g = ∅ := by
    simp [Set.range_eq_empty]
  rw [hg, Subgroup.closure_empty] at hgen
  rw [Fintype.card_le_one_iff]
  intro a b
  have ha : a ∈ (⊥ : Subgroup G) := hgen ▸ Subgroup.mem_top a
  have hb : b ∈ (⊥ : Subgroup G) := hgen ▸ Subgroup.mem_top b
  rw [Subgroup.mem_bot] at ha hb
  rw [ha, hb]

/-- Base case: exponent `2`, with the sharp bound `2 ^ m`. -/
