import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Frontier

/-- `RestrictedBurnside m n` is the statement of the *restricted Burnside problem* for
`m` generators and exponent `n`: there is a uniform bound `N` on the order of every finite
group that is generated by `m` elements and has exponent dividing `n`.

(Equivalently, there are only finitely many isomorphism classes of such groups.)
Zelmanov's theorem asserts that `RestrictedBurnside m n` holds for all `m` and all `n ≥ 1`. -/

theorem restrictedBurnsideClassTwo_of_pos {m n : ℕ} (hn : 0 < n) :
    RestrictedBurnsideClassTwo m n := by
  refine ⟨n ^ m * n ^ (m * m), fun G _ _ g hgen hexp hcent => ?_⟩
  rw [← Nat.card_eq_fintype_card]
  exact card_le_of_commutator_le_center hn g hgen hexp hcent

/-- **Restricted Burnside problem** (Zelmanov).  The predicate `RestrictedBurnside m n` is the
formalization of the restricted Burnside problem: finite `m`-generated groups of exponent
dividing `n` have uniformly bounded order.  Zelmanov's theorem states that this holds for all `m`
and all `n ≥ 1` (recorded as `ZelmanovConjecture`).

This theorem records a Lean-checked package around that formalization: the base cases (exponent
`1`, exponent `2` with the sharp bound `2 ^ m`, no generators, one generator with the sharp bound
`n`), the two reductions (in the exponent and in the number of generators), the positive solution
for groups of nilpotency class at most `2`, and the sharpness of the hypothesis `n ≥ 1`. -/
