import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Frontier

/-- `RestrictedBurnside m n` is the statement of the *restricted Burnside problem* for
`m` generators and exponent `n`: there is a uniform bound `N` on the order of every finite
group that is generated by `m` elements and has exponent dividing `n`.

(Equivalently, there are only finitely many isomorphism classes of such groups.)
Zelmanov's theorem asserts that `RestrictedBurnside m n` holds for all `m` and all `n ≥ 1`. -/

theorem zelmanov_restricted_burnside :
    (∀ m : ℕ, RestrictedBurnside m 1) ∧
    (∀ n : ℕ, RestrictedBurnside 0 n) ∧
    (∀ n : ℕ, 0 < n → RestrictedBurnside 1 n) ∧
    (∀ m : ℕ, RestrictedBurnside m 2) ∧
    (∀ m n : ℕ, 0 < n → RestrictedBurnsideClassTwo m n) ∧
    (∀ m n k : ℕ, n ∣ k → RestrictedBurnside m k → RestrictedBurnside m n) ∧
    (∀ m m' n : ℕ, m' ≤ m → RestrictedBurnside m n → RestrictedBurnside m' n) ∧
    ¬ RestrictedBurnside 1 0 :=
  ⟨restrictedBurnside_exponent_one, restrictedBurnside_zero_generators,
    fun _ hn => restrictedBurnside_one_generator hn, restrictedBurnside_exponent_two,
    fun _ _ hn => restrictedBurnsideClassTwo_of_pos hn,
    fun _ _ _ hdvd h => restrictedBurnside_of_dvd hdvd h,
    fun _ _ _ hm h => restrictedBurnside_of_le_generators hm h,
    not_restrictedBurnside_exponent_zero⟩

end Frontier

