/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem alpha_sameCycle_iff {z x : M.D} : M.α.SameCycle z x ↔ z = x ∨ z = M.α x := by
  have hsq : M.α * M.α = 1 := Equiv.ext (fun y => M.α_inv y)
  have hsq2 : M.α ^ (2 : ℤ) = 1 := by
    rw [show (2 : ℤ) = ((2 : ℕ) : ℤ) from rfl, zpow_natCast, pow_two, hsq]
  have hα2 : ∀ i : ℤ, M.α ^ i = 1 ∨ M.α ^ i = M.α := by
    intro i
    rcases Int.even_or_odd i with ⟨k, hk⟩ | ⟨k, hk⟩
    · left
      rw [hk, show k + k = 2 * k by ring, zpow_mul, hsq2, one_zpow]
    · right
      rw [hk, zpow_add, zpow_mul, hsq2, one_zpow, one_mul, zpow_one]
  constructor
  · rintro ⟨i, hi⟩
    rcases hα2 i with h | h <;> rw [h] at hi
    · left; simpa using hi
    · right; rw [← hi, M.α_inv]
  · rintro (rfl | rfl)
    · exact SameCycle.rfl
    · exact ⟨1, by simp [M.α_inv]⟩

