/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem card_darts_eq : Fintype.card M.D = 2 * numCycles M.α := by
  classical
  have hfib : ∀ x : M.D, cycFiber M.α x = {x, M.α x} := by
    intro x
    ext z
    simp only [mem_cycFiber, Finset.mem_insert, Finset.mem_singleton]
    exact M.alpha_sameCycle_iff
  have hcard : ∀ x : M.D, (cycFiber M.α x).card = 2 := by
    intro x
    rw [hfib x, Finset.card_insert_of_notMem (by simp [Ne.symm (M.α_ne x)]),
      Finset.card_singleton]
  exact le_antisymm (card_le_mul_numCycles M.α 2 (fun x => (hcard x).le))
    (mul_numCycles_le_card M.α 2 (fun x => (hcard x).ge))

