/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem card_le_mul_numCycles (π : Perm D) (k : ℕ)
    (h : ∀ x : D, (cycFiber π x).card ≤ k) : Fintype.card D ≤ k * numCycles π := by
  classical
  letI : Fintype (Quotient (SameCycle.setoid π)) := Fintype.ofFinite _
  rw [card_fiberwise π]
  calc ∑ c : Quotient (SameCycle.setoid π), (cycFiber π c.out).card
      ≤ ∑ _c : Quotient (SameCycle.setoid π), k := Finset.sum_le_sum (fun c _ => h c.out)
    _ = k * numCycles π := by
        rw [Finset.sum_const, Finset.card_univ, smul_eq_mul, mul_comm]
        congr 1
        simp [numCycles, Nat.card_eq_fintype_card]

