/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem del_face_cycle_meets (x : M.D) :
    ∃ y, (M.σ * M.α * Equiv.swap d₀ (M.α d₀)).SameCycle x y ∧ y ∉ M.edgePair d₀ := by
  set ψ := M.σ * M.α * Equiv.swap d₀ (M.α d₀) with hψ
  by_cases hx : x ∈ M.edgePair d₀
  · rcases mem_edgePair.1 hx with rfl | rfl
    · refine ⟨ψ x, ⟨1, by simp⟩, ?_⟩
      have : ψ x = M.σ x := by
        simp [hψ, M.α_inv]
      rw [this]
      exact del_sigma_d₀_notMem hfne hfw hfa
    · refine ⟨ψ (M.α d₀), ⟨1, by simp⟩, ?_⟩
      have : ψ (M.α d₀) = M.σ (M.α d₀) := by
        simp [hψ, Equiv.swap_apply_right]
      rw [this]
      exact del_sigma_alpha_d₀_notMem hfne hfw hfa
  · exact ⟨x, SameCycle.rfl, hx⟩

/-- The face permutation of the map with an edge deleted. -/
