/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem del_face_eq :
    skip M.σ (M.edgePair d₀) * skip M.α (M.edgePair d₀) =
      skip (M.σ * M.α * Equiv.swap d₀ (M.α d₀)) (M.edgePair d₀) := by
  refine Equiv.ext (fun z => Subtype.ext ?_)
  obtain ⟨x, hx⟩ := z
  have h1 : ∀ x, x ∉ M.edgePair d₀ →
      M.σ (M.α x) = (M.σ * M.α * Equiv.swap d₀ (M.α d₀)) x := by
    intro x hx
    have hne1 : x ≠ d₀ := fun h => hx (mem_edgePair.2 (Or.inl h))
    have hne2 : x ≠ M.α d₀ := fun h => hx (mem_edgePair.2 (Or.inr h))
    simp [Equiv.swap_apply_of_ne_of_ne hne1 hne2]
  have h2 : ∀ z, z ∈ M.edgePair d₀ →
      M.σ z = (M.σ * M.α * Equiv.swap d₀ (M.α d₀)) z := by
    intro z hz
    rcases mem_edgePair.1 hz with rfl | rfl
    · simp [M.α_inv]
    · simp [Equiv.swap_apply_right]
  have := skip_comp_eq (π := M.σ) (ρ := M.σ * M.α * Equiv.swap d₀ (M.α d₀)) (β := M.α)
    (S := M.edgePair d₀) h1 h2 (fun x hx => alpha_notMem_edgePair hx) hx
  simp only [Perm.mul_apply]
  rw [show (skip M.α (M.edgePair d₀) ⟨x, hx⟩) = ⟨M.α x, alpha_notMem_edgePair hx⟩ from
    Subtype.ext (skip_alpha_apply ⟨x, hx⟩)]
  exact this

/-- The retraction of darts used to transfer connectivity through a deletion. -/
