/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem del_sigma_alpha_d₀_notMem : M.σ (M.α d₀) ∉ M.edgePair d₀ := by
  intro h
  rcases mem_edgePair.1 h with h | h
  · refine M.noloop d₀ ?_
    have hw : M.w (M.σ (M.α d₀)) = M.w (M.α d₀) := M.w_sigma _
    rw [h] at hw
    exact hw.symm
  · have hne : M.α f ≠ M.α d₀ := fun hc => hfne (by
      have := congrArg M.α hc
      rwa [M.α_inv, M.α_inv] at this)
    exact hne ((M.w_cycle (M.α f) (M.α d₀) hfa).eq_of_right (h : M.σ (M.α d₀) = M.α d₀))

/-- Every cycle of `σ` meets the complement of the deleted edge. -/
