/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem deleteEdge_card_lt :
    Fintype.card (deleteEdge hfne hfw hfa).D < Fintype.card M.D := by
  classical
  show Fintype.card {z : M.D // z ∉ M.edgePair d₀} < Fintype.card M.D
  have h1 : Fintype.card {z : M.D // z ∉ M.edgePair d₀}
      = Fintype.card M.D - Fintype.card {z : M.D // z ∈ M.edgePair d₀} := by
    simp [Fintype.card_subtype_compl (p := fun z : M.D => z ∈ M.edgePair d₀)]
  have h2 : Fintype.card {z : M.D // z ∈ M.edgePair d₀} = (M.edgePair d₀).card :=
    Fintype.card_coe _
  have h3 : Fintype.card {z : M.D // z ∈ M.edgePair d₀} ≤ Fintype.card M.D :=
    Fintype.card_subtype_le _
  have h4 : 0 < (M.edgePair d₀).card :=
    Finset.card_pos.2 ⟨d₀, mem_edgePair.2 (Or.inl rfl)⟩
  omega

end Delete

/-- Every map can be turned into a simple map with at least the same graph, by
repeatedly deleting parallel edges. -/
