/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

noncomputable def deleteEdge : Rot V where
  D := {z : M.D // z ∉ M.edgePair d₀}
  σ := skip M.σ (M.edgePair d₀)
  α := skip M.α (M.edgePair d₀)
  w := fun z => M.w z.1
  α_inv := fun z => Subtype.ext (by rw [skip_alpha_apply, skip_alpha_apply, M.α_inv])
  w_sigma := fun z => M.w_of_sameCycle (sameCycle_skip_sigma z)
  w_surj := by
    intro u
    obtain ⟨d, rfl⟩ := M.w_surj u
    by_cases hd : d ∈ M.edgePair d₀
    · rcases mem_edgePair.1 hd with rfl | rfl
      · exact ⟨⟨f, del_f_notMem hfne hfw hfa⟩, hfw⟩
      · exact ⟨⟨M.α f, del_alpha_f_notMem hfne hfw hfa⟩, hfa⟩
    · exact ⟨⟨d, hd⟩, rfl⟩
  w_cycle := fun d e h => skip_sameCycle _ _ (M.w_cycle _ _ h)
  noloop := fun d => by
    show M.w ((skip M.α (M.edgePair d₀) d).1) ≠ M.w d.1
    rw [skip_alpha_apply]
    exact M.noloop d.1
  conn := by
    classical
    refine conn_transfer M _ _ (delT hfne hfw hfa) ?_ ?_ (delT_surjective hfne hfw hfa)
    · -- σ-steps
      intro z
      refine reflTransGen_of_sameCycle' (skip_sameCycle M.σ _ ?_)
      refine M.w_cycle _ _ ?_
      rw [w_delT, w_delT, M.w_sigma]
    · -- α-steps
      intro z
      refine Relation.ReflTransGen.single (Or.inr ?_)
      by_cases hz : z ∈ M.edgePair d₀
      · rcases mem_edgePair.1 hz with rfl | rfl
        · rw [delT_d₀, delT_alpha_d₀]
          refine Subtype.ext ?_
          rw [skip_alpha_apply]
        · rw [delT_alpha_d₀, M.α_inv, delT_d₀]
          refine Subtype.ext ?_
          rw [skip_alpha_apply, M.α_inv]
      · rw [delT_of_notMem hfne hfw hfa hz,
          delT_of_notMem hfne hfw hfa (alpha_notMem_edgePair hz)]
        refine Subtype.ext ?_
        rw [skip_alpha_apply]
  euler := by
    have hE := numCycles_skip_alpha_lt (M := M) d₀
    have hV : numCycles M.σ ≤ numCycles (skip M.σ (M.edgePair d₀)) :=
      numCycles_le_skip _ _ (del_sigma_cycle_meets hfne hfw hfa)
    have hF : numCycles (M.σ * M.α * Equiv.swap d₀ (M.α d₀)) ≤
        numCycles (skip (M.σ * M.α * Equiv.swap d₀ (M.α d₀)) (M.edgePair d₀)) :=
      numCycles_le_skip _ _ (del_face_cycle_meets hfne hfw hfa)
    have hF2 := numCycles_sub_one_le_mul_swap (M.σ * M.α) d₀ (M.α d₀)
    have he := M.euler
    rw [del_face_eq hfne hfw hfa]
    omega

