/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem edge_bound (hs : M.Simple) (hdeg : ∀ d, M.σ d ≠ d) :
    numCycles M.α + 6 ≤ 3 * numCycles M.σ := by
  have hF : 3 * numCycles (M.σ * M.α) ≤ Fintype.card M.D :=
    mul_numCycles_le_card _ 3 (M.three_le_face_card hs hdeg)
  have hE := M.card_darts_eq
  have he := M.euler
  omega

end Rot

section Degrees

variable {V : Type*} [Fintype V]

open scoped Classical in
/-- The neighbourhood of a vertex, as a `Finset`. -/
