/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem exists_low_degree (hs : M.Simple) : ∃ u : V, (nbrs M.graph u).card ≤ 5 := by
  classical
  by_contra hc
  push_neg at hc
  have hfib : ∀ x : M.D, 6 ≤ (cycFiber M.σ x).card :=
    fun x => le_trans (hc (M.w x)) (M.card_nbrs_le_fiber x)
  have hdeg : ∀ d, M.σ d ≠ d := by
    intro d hd
    have h := hfib d
    rw [cycFiber_of_fixed hd] at h
    simp at h
  have h1 : 6 * numCycles M.σ ≤ Fintype.card M.D := mul_numCycles_le_card _ 6 hfib
  have h2 := M.card_darts_eq
  have h3 := M.edge_bound hs hdeg
  omega

end Rot

end Degrees

end FiveColor

/-
Surgery on combinatorial maps: deleting an edge and contracting an edge.

Both operations remove the two darts of one edge from the map; the rotation is
adjusted using `skip` (and, for a contraction, a transposition which merges the
two vertex cycles).  In both cases the Euler characteristic does not decrease,
so genus zero is preserved.
-/
import RequestProject.Map

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

namespace Rot

variable {V : Type*}

/-- The pair of darts of the edge through `d₀`. -/
