/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem numCycles_sigma : numCycles M.σ = Nat.card V := by
  classical
  refine Nat.card_eq_of_bijective
    (f := fun c : Quotient (SameCycle.setoid M.σ) =>
      Quotient.liftOn c M.w (fun a b h => M.w_of_sameCycle h)) ⟨?_, ?_⟩
  · intro c₁ c₂ h
    induction c₁ using Quotient.inductionOn with
    | _ x =>
      induction c₂ using Quotient.inductionOn with
      | _ y =>
        simp only [Quotient.liftOn_mk] at h
        exact Quotient.sound (M.w_cycle x y h)
  · intro u
    obtain ⟨d, rfl⟩ := M.w_surj u
    exact ⟨cyc M.σ d, rfl⟩

/-- The cycles of `α` are the pairs `{d, α d}`. -/
