/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem numCycles_le_skip (h : ∀ x : D, ∃ y, π.SameCycle x y ∧ y ∉ S) :
    numCycles π ≤ numCycles (skip π S) := by
  refine Nat.card_le_card_of_surjective
    (f := fun c : Quotient (SameCycle.setoid (skip π S)) =>
      Quotient.liftOn c (fun x => cyc π x.1)
        (fun x y hxy => cyc_eq_iff.2 (sameCycle_of_skip π S hxy))) ?_
  intro c
  obtain ⟨x, rfl⟩ := cyc_surjective π c
  obtain ⟨y, hxy, hy⟩ := h x
  exact ⟨Quotient.mk _ ⟨y, hy⟩, by simpa using cyc_eq_iff.2 hxy.symm⟩

