/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem reflTransGen_of_sameCycle' {D' : Type} [Fintype D'] [DecidableEq D']
    {σ' α' : Perm D'} {a b : D'} (h : σ'.SameCycle a b) :
    Relation.ReflTransGen (fun x y => y = σ' x ∨ y = α' x) a b :=
  Relation.ReflTransGen.mono (fun _ _ h => Or.inl h) (reflTransGen_of_sameCycle h)

section Delete

variable {d₀ f : M.D} (hfne : f ≠ d₀) (hfw : M.w f = M.w d₀) (hfa : M.w (M.α f) = M.w (M.α d₀))

include hfne hfw hfa

