/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem reflTransGen_of_sameCycle {π : Perm D} {x y : D} (h : π.SameCycle x y) :
    Relation.ReflTransGen (fun a b => b = π a) x y := by
  obtain ⟨n, hn⟩ := h.exists_nat_pow_eq
  subst hn
  clear h
  induction n with
  | zero => exact Relation.ReflTransGen.refl
  | succ n ih =>
      refine ih.tail ?_
      rw [pow_succ']
      rfl

section Skip

