/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem sameCycle_mul_swap {π : Perm D} {a b : D} (hab : ¬ π.SameCycle a b) {x y : D}
    (h : π.SameCycle x y) : (π * Equiv.swap a b).SameCycle x y := by
  classical
  set ρ := π * Equiv.swap a b with hρ
  have hab' : ρ.SameCycle a b := sameCycle_mul_swap_self hab
  refine sameCycle_of_forall_step (π := π) (ρ := ρ) ?_ x y h
  intro z
  by_cases hza : z = a
  · rw [hza]
    have hb : ρ b = π a := by simp [hρ]
    have h2 : ρ.SameCycle b (π a) := hb ▸ (⟨1, by simp⟩ : ρ.SameCycle b (ρ b))
    exact hab'.trans h2
  · by_cases hzb : z = b
    · rw [hzb]
      have ha : ρ a = π b := by simp [hρ]
      have h2 : ρ.SameCycle a (π b) := ha ▸ (⟨1, by simp⟩ : ρ.SameCycle a (ρ a))
      exact hab'.symm.trans h2
    · have h1 : ρ z = π z := by simp [hρ, Equiv.swap_apply_of_ne_of_ne hza hzb]
      exact ⟨1, by simp [h1]⟩

end Transposition

end FiveColor

