/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem sameCycle_skip_sigma {d₀ : M.D} (z : {z : M.D // z ∉ M.edgePair d₀}) :
    M.σ.SameCycle (skip M.σ (M.edgePair d₀) z).1 z.1 :=
  sameCycle_of_skip M.σ _ (show (skip M.σ (M.edgePair d₀)).SameCycle
    (skip M.σ (M.edgePair d₀) z) z from ⟨-1, by simp⟩)

/-- Number of edges drops when an edge is removed. -/
