/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem skipIdx_eq_of_chain {π : Perm D} {S : Finset D} {x : D} (hx : x ∉ S) {k : ℕ} (hk : 1 ≤ k)
    (hout : (π ^ k) x ∉ S) (hmid : ∀ j, 1 ≤ j → j < k → (π ^ j) x ∈ S) :
    skipIdx π S ⟨x, hx⟩ = k := by
  have hle : skipIdx π S ⟨x, hx⟩ ≤ k := Nat.find_min' _ ⟨hk, hout⟩
  by_contra hne
  have hlt : skipIdx π S ⟨x, hx⟩ < k := by omega
  exact (skipIdx_not_mem π S ⟨x, hx⟩) (hmid _ (skipIdx_pos π S ⟨x, hx⟩) hlt)

