/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem skip_exists (π : Perm D) (S : Finset D) (x : D) (hx : x ∉ S) :
    ∃ k : ℕ, 1 ≤ k ∧ (π ^ k) x ∉ S := by
  refine ⟨orderOf π, orderOf_pos π, ?_⟩
  rw [pow_orderOf_eq_one]
  simpa using hx

variable (π : Perm D) (S : Finset D)

/-- The number of steps needed to skip out of `S`. -/
