/-
Combinatorial maps (rotation systems) of genus zero, and Euler's formula.

A *combinatorial map* consists of a finite set `D` of darts, a permutation `σ`
whose cycles are the vertices, and a fixed-point-free involution `α` pairing the
two darts of each edge.  The cycles of `σ * α` are the faces.  A map is
*connected* when the group generated by `σ` and `α` acts transitively, and it has
*genus zero* (i.e. it is a plane map) when `V - E + F = 2`.

Here the vertices are labelled by a type `V` via a map `w : D → V` whose fibres
are exactly the cycles of `σ`.
-/
import RequestProject.CycleCount

namespace FiveColor

open Equiv Equiv.Perm SimpleGraph

section Counting

variable {D : Type*} [Fintype D] [DecidableEq D]

open scoped Classical in
/-- The cycle of `x` under `π`, as a `Finset`. -/

theorem w_delT (z : M.D) : M.w (delT hfne hfw hfa z).1 = M.w z := by
  by_cases hz : z ∈ M.edgePair d₀
  · rcases mem_edgePair.1 hz with rfl | rfl
    · rw [delT_d₀]; exact hfw
    · rw [delT_alpha_d₀]; exact hfa
  · rw [delT_of_notMem hfne hfw hfa hz]

