/-!
# Higgs Mass Toy
Category: Frontier Physics
Target: Frontier.higgs_mass_toy
Statement: In an abelian Higgs toy model, spontaneous symmetry breaking gives the gauge boson a mass.
Verified: AXLE cloud (Lean 4.32.0, Mathlib), axiom-clean
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-- The "Mexican hat" scalar potential of the abelian Higgs toy model,
`V(φ) = lam * (‖φ‖² - v²)²`, for a complex scalar field value `φ`. -/
noncomputable def higgsPotential (lam v : ℝ) (phi : ℂ) : ℝ :=
  lam * (‖phi‖ ^ 2 - v ^ 2) ^ 2

/-- The gauge-boson mass squared generated by the Higgs field value `phi` through the
covariant derivative `Dφ = (∂ - i g A) φ`: the quadratic term in `A` is `g² ‖φ‖² A²`. -/
noncomputable def gaugeBosonMassSq (g : ℝ) (phi : ℂ) : ℝ :=
  g ^ 2 * ‖phi‖ ^ 2

/-- **Spontaneous symmetry breaking gives the gauge boson a mass** (abelian Higgs toy model).

For a Mexican-hat potential `V(φ) = lam (‖φ‖² - v²)²` with `lam > 0` and `v > 0`:

* `V` is nonnegative, so its vacua are exactly its zeros;
* the vacua are exactly the field values on the circle `‖φ‖ = v`, i.e. the symmetric
  point `φ = 0` is *not* a vacuum;
* at every vacuum the gauge boson mass squared equals `g² v²`, which is strictly positive
  for `g ≠ 0`;
* at the symmetric (unbroken) point `φ = 0` the gauge boson is massless.
-/
theorem higgs_mass_toy {lam v g : ℝ} (hlam : 0 < lam) (hv : 0 < v) (hg : g ≠ 0) :
    (∀ phi : ℂ, 0 ≤ higgsPotential lam v phi) ∧
    (∀ phi : ℂ, higgsPotential lam v phi = 0 ↔ ‖phi‖ = v) ∧
    (∀ phi : ℂ, higgsPotential lam v phi = 0 →
      gaugeBosonMassSq g phi = g ^ 2 * v ^ 2 ∧ 0 < gaugeBosonMassSq g phi) ∧
    gaugeBosonMassSq g 0 = 0 := by
  have hzero : ∀ phi : ℂ, higgsPotential lam v phi = 0 ↔ ‖phi‖ = v := by
    intro phi
    have hnn : (0 : ℝ) ≤ ‖phi‖ := norm_nonneg phi
    constructor
    · intro h
      rw [higgsPotential] at h
      have h2 : (‖phi‖ ^ 2 - v ^ 2) ^ 2 = 0 := by
        rcases mul_eq_zero.mp h with h' | h'
        · exact absurd h' hlam.ne'
        · exact h'
      have h3 : ‖phi‖ ^ 2 = v ^ 2 := by
        have := pow_eq_zero_iff (n := 2) (by norm_num) |>.mp h2
        linarith
      nlinarith
    · intro h
      simp [higgsPotential, h]
  refine ⟨?_, hzero, ?_, ?_⟩
  · intro phi
    have : (0 : ℝ) ≤ (‖phi‖ ^ 2 - v ^ 2) ^ 2 := sq_nonneg _
    exact mul_nonneg hlam.le this
  · intro phi h
    have hnorm : ‖phi‖ = v := (hzero phi).mp h
    refine ⟨by simp [gaugeBosonMassSq, hnorm], ?_⟩
    simp only [gaugeBosonMassSq, hnorm]
    positivity
  · simp [gaugeBosonMassSq]

end Frontier

