/-
  Refutation certificate (finite countermodel) — generated by scripts/refute.py
  Claim refuted:  (x*y = y*x)  ⊬  (x*(y*z) = (x*y)*z)
  A magma of order 2 satisfies A but not B, so A does not entail B.
  Proof is by kernel `decide` on the explicit multiplication table (COMPUTATION).
-/
import Mathlib

namespace Brockian.Refute.CommNotAssoc

/-- The countermodel: an order-2 magma satisfying `x*y = y*x` but not `x*(y*z) = (x*y)*z`. -/
def op : Fin 2 → Fin 2 → Fin 2 := ![![(1 : Fin 2),(0 : Fin 2)],![(0 : Fin 2),(0 : Fin 2)]]

/-- Kernel-checked: the table satisfies A and violates B. -/
theorem countermodel : (∀ x y z : Fin 2, op (x) (y) = op (y) (x)) ∧ ¬ (∀ x y z : Fin 2, op (x) (op (y) (z)) = op (op (x) (y)) (z)) := by decide

/-- Hence A does not entail B over magmas of order 2. -/
theorem not_entails :
    ¬ ∀ (m : Fin 2 → Fin 2 → Fin 2), (∀ x y z : Fin 2, m (x) (y) = m (y) (x)) → (∀ x y z : Fin 2, m (x) (m (y) (z)) = m (m (x) (y)) (z)) :=
  fun h => countermodel.2 (h op countermodel.1)

end Brockian.Refute.CommNotAssoc
