import Mathlib

/-!
# Penrose Singularity
Category: Frontier Physics
Target: Frontier.penrose_singularity
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

-- (Lean requires `import` lines to precede every other command, so the header comment
-- above is placed immediately after the single `import Mathlib` line.)

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames false
set_option pp.structureInstances true
set_option pp.coercions.types false
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-!
## The analytic core: Raychaudhuri focusing

For a null geodesic congruence with vanishing shear and rotation (as holds for the
generators of the boundary of the causal future of a surface), the Raychaudhuri equation
together with the null energy condition `Ric(k,k) ≥ 0` gives the differential inequality

  `θ' ≤ - θ² / 2`

for the expansion `θ` as a function of the affine parameter. The following theorem is the
exact analytic content of the focusing argument: a solution of this inequality with
`θ 0 < 0` blows up (i.e. cannot be continued) before affine parameter `2 / |θ 0|`.
-/

/-- **Raychaudhuri focusing theorem.**  If `θ` satisfies the null-energy-condition
inequality `θ' ≤ -θ²/2` on `[0, L]` and starts out converging, `θ 0 < 0`, then
`L < 2 / (-θ 0)`.  Equivalently: a congruence with initially negative expansion develops a
focal point within affine parameter `2 / |θ 0|`. -/

theorem as a structure whose fields are exactly the standard hypotheses of the theorem,
transported to the null generators of the boundary `∂J⁺(S)` of the causal future of a
trapped surface `S`:

* `Gen` is the (nonempty) set of null generators of `∂J⁺(S)` issuing from the trapped
  surface `S`, parametrised by affine parameter `t ≥ 0`;
* `Extends s T` says that the generator `s`, as a generator of the boundary, extends to
  affine parameter `T`;
* `theta s` is the expansion of the congruence along the generator `s`, with derivative
  `dtheta s` with respect to the affine parameter;
* `trapped` is the *trapped surface* hypothesis: the expansion of the outgoing null
  congruence is uniformly negative on the (compact) surface `S`, `θ ≤ -c < 0`;
* `nec` is the Raychaudhuri equation combined with the *null energy condition*
  `Ric(k,k) ≥ 0` (and vanishing rotation for hypersurface-orthogonal generators):
  `θ' = -θ²/2 - σ² - Ric(k,k) ≤ -θ²/2`.

Null geodesic completeness of the spacetime means that every generator can be extended to
arbitrarily large affine parameter while remaining a generator of the achronal boundary
(no generator meets a focal point, since a generator leaves the boundary at a focal point,
and the boundary is generated by inextendible null geodesics as long as they exist).
-/

/-- Abstract data of the null generators of the boundary of the causal future of a
trapped surface in a spacetime satisfying the null energy condition. -/
structure TrappedSurfaceCongruence where
  /-- The null generators of `∂J⁺(S)` emanating from the trapped surface `S`. -/
  Gen : Type
  /-- A trapped surface is nonempty. -/
  gen_nonempty : Nonempty Gen
  /-- `Extends s T` : the generator `s` extends (as a null geodesic generator of the
  boundary) to affine parameter `T`. -/
  Extends : Gen → ℝ → Prop
  /-- The expansion of the congruence along a generator, as a function of the affine
  parameter. -/
  theta : Gen → ℝ → ℝ
  /-- The affine-parameter derivative of the expansion. -/
  dtheta : Gen → ℝ → ℝ
  /-- The expansion is differentiable along the part of a generator that exists. -/
  hasDerivAt_theta : ∀ (s : Gen) (T : ℝ), Extends s T →
    ∀ t ∈ Set.Icc (0 : ℝ) T, HasDerivAt (theta s) (dtheta s t) t
  /-- The uniform bound on the expansion of the trapped surface. -/
  focusConst : ℝ
  /-- Compactness of the trapped surface makes the bound on its expansion uniform. -/
  focusConst_pos : 0 < focusConst
  /-- **Trapped surface hypothesis**: the outgoing null expansion is negative on `S`. -/
  trapped : ∀ s : Gen, theta s 0 ≤ -focusConst
  /-- **Null energy condition** via the Raychaudhuri equation. -/
  nec : ∀ (s : Gen) (T : ℝ), Extends s T →
    ∀ t ∈ Set.Icc (0 : ℝ) T, dtheta s t ≤ -(theta s t) ^ 2 / 2

/-- Null geodesic completeness: every generator of the boundary extends to every
nonnegative affine parameter. -/
