/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 3e63c0bb-3912-4be8-b92e-c880a4bc2d64
-/

/-
This module formalizes the structure of prime pairs modulo 5. It defines rays (residues mod 5), ray pairs, and principal ray pairs. It proves that for any gap g coprime to 5, there are exactly 3 principal ray pairs. It also provides explicit structures for twin primes (g=2), cousin primes (g=4), sexy primes (g=6), and gap 8. Note that the user's original statement for gap 8 was incorrect and has been corrected to match the comments and mathematical reality.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-! ## Ray Partition -/

/-- The five rays partition natural numbers by residue modulo 5.
    E = multiples of 5
    A = residue 1 mod 5
    B = residue 2 mod 5
    C = residue 3 mod 5
    D = residue 4 mod 5 -/
inductive Ray : Type
  | E : Ray  -- Residue 0
  | A : Ray  -- Residue 1
  | B : Ray  -- Residue 2
  | C : Ray  -- Residue 3
  | D : Ray  -- Residue 4
  deriving DecidableEq, Repr


def principalPairs (g : ℕ) : Finset RayPair :=
  Finset.univ.filter fun p =>
    RayPair.isPrincipal p ∧ RayPair.satisfiesGapConstraint p g

/-- Helper: For each principal ray, compute its pair under gap g -/
