import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

/-!
# Isotypic decomposition of the vertex representation of a regular `n`-gon

The dihedral group `D_n` acts on the vertices of a regular `n`-gon, hence on the space
`ZMod n → ℂ` of complex functions on the vertices.  The action is generated by the rotation
`rotOp n` (`f ↦ f (· + 1)`) and by the reflection `reflOp n` (`f ↦ f (-·)`).

For every "frequency" `k : ZMod n`, the character `chi n k : j ↦ e(k * j)` is an eigenvector of
the rotation, and the reflection interchanges `chi n k` and `chi n (-k)`.  Consequently the plane
`isotypic n k = span {chi n k, chi n (-k)}` is invariant under the whole dihedral action; it is
a line exactly when `k = -k`, and a genuine plane otherwise.  These isotypic pieces together span
the whole vertex space.

This generalises to arbitrary `n` the familiar pentagon (`n = 5`) picture, in which the
`5`-dimensional vertex representation of `D_5` splits as the trivial line `k = 0` plus the two
planes `k ∈ {1,4}` and `k ∈ {2,3}`.
-/

namespace Brockian

open ZMod Complex

variable (n : ℕ)

/-- The rotation of the regular `n`-gon acting on complex functions on the vertices,
`(rotOp n f) j = f (j + 1)`. -/

lemma finrank_isotypic (k : ZMod n) :
    Module.finrank ℂ (isotypic n k) = if k = -k then 1 else 2 := by
  by_cases hk : k = -k
  · rw [if_pos hk, isotypic, ← hk]
    have : ({chi n k, chi n k} : Set (ZMod n → ℂ)) = {chi n k} := by simp
    rw [this]
    exact finrank_span_singleton (chi_ne_zero n k)
  · rw [if_neg hk, isotypic]
    have hinj : Function.Injective (![k, -k] : Fin 2 → ZMod n) := by
      intro a b hab
      fin_cases a <;> fin_cases b <;> simp_all
    have hli : LinearIndependent ℂ (fun i : Fin 2 => chi n (![k, -k] i)) :=
      (linearIndependent_chi n).comp _ hinj
    have hrange : Set.range (fun i : Fin 2 => chi n (![k, -k] i))
        = ({chi n k, chi n (-k)} : Set (ZMod n → ℂ)) := by
      ext x
      constructor
      · rintro ⟨i, rfl⟩
        fin_cases i <;> simp
      · rintro (rfl | rfl)
        · exact ⟨0, by simp⟩
        · exact ⟨1, by simp⟩
    have := finrank_span_eq_card hli
    rw [hrange] at this
    simpa using this

/-- The isotypic pieces span the whole vertex space. -/
