import Mathlib

/-!
# Isotypic decomposition of the regular `n`-gon representations

This file generalizes the `D₅` ("pentagon") representation results to arbitrary `n`-gons.

Vertices of a regular `n`-gon are indexed by `ZMod n`, and the space of complex-valued
"vertex configurations" is `ZMod n → ℂ`, carrying the natural action of the dihedral group
`D_n` generated by the rotation `rot` and the reflection `refl`.

For `m : ZMod n` the *`m`-th star polygon* `ngon n m` is the configuration
`k ↦ exp (2 π i m k / n)`; for `n = 5`, `m = 1` is the pentagon and `m = 2` the pentagram.

The main results say that `ngon n m` is a rotation eigenvector, that reflection exchanges
`ngon n m` and `ngon n (-m)`, that the plane `isotypic n m` they span is a `D_n`-subrepresentation,
and that distinct isotypic components are orthogonal for the Hermitian pairing.
-/

open scoped BigOperators Real
open Complex (I)

namespace Brockian

variable {n : ℕ} [NeZero n]

/-- The `m`-th star polygon inscribed in the regular `n`-gon: the vertex configuration
`k ↦ exp (2 π i m k / n)`. For `n = 5` this is the pentagon (`m = 1`) or the pentagram
(`m = 2`). -/

theorem pairing_eq_zero_of_isotypic {m m' : ZMod n} (h1 : m' ≠ m) (h2 : m' ≠ -m)
    {f g : ZMod n → ℂ} (hf : f ∈ isotypic n m) (hg : g ∈ isotypic n m') :
    pairing f g = 0 := by
  rw [isotypic, Submodule.mem_span_pair] at hf hg
  obtain ⟨a, b, rfl⟩ := hf
  obtain ⟨c, d, rfl⟩ := hg
  have e1 : m ≠ m' := fun h => h1 h.symm
  have e2 : m ≠ -m' := fun h => h2 (by rw [h, neg_neg])
  have e3 : -m ≠ m' := fun h => h2 h.symm
  have e4 : -m ≠ -m' := fun h => e1 (neg_injective h)
  rw [pairing_left_smul_add, pairing_right_smul_add, pairing_right_smul_add,
    pairing_ngon, pairing_ngon, pairing_ngon, pairing_ngon]
  simp [e1, e2, e3, e4]

/-! ### Invariance of the isotypic planes -/

