/-
# Adiabatic Theorem
Category: Frontier Phys
Target: Phys.adiabatic_theorem
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise
open scoped NNReal

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 40000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Phys

open Set

/-- **Uniqueness for a linear ODE in a Banach algebra.**
If `X : ℝ → F` solves the linear differential equation `X' t = A t * X t` with continuous
coefficient `A` and vanishing initial datum, then `X` vanishes identically. -/

theorem kato_commutator {R : Type*} [Ring R] {p d : R} (hp : p * p = p)
    (hd : d * p + p * d = d) :
    p * (d * p - p * d) - (d * p - p * d) * p = -d := by
  have h0 : p * d * p = 0 := idem_deriv_sandwich hp hd
  calc p * (d * p - p * d) - (d * p - p * d) * p
      = p * d * p + p * d * p - p * p * d - d * (p * p) := by noncomm_ring
    _ = -(d * p + p * d) := by rw [h0, hp]; abel
    _ = -d := by rw [hd]

section

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]

/-- **Adiabatic theorem (Kato).**

Set-up.  `H s` is a time-dependent Hamiltonian on a complex Banach space `E`, and `P s` is the
spectral projection onto a *nondegenerate* (one-dimensional) instantaneous eigenspace of `H s`
with instantaneous eigenvalue `e s`; this is expressed by `H s * P s = e s • P s`,
`P s * H s = e s • P s`, `P s * P s = P s` and the nondegeneracy hypothesis `hnondeg`.
The projection family is assumed to be continuously differentiable, with derivative `dP`.

The adiabatic (slow) dynamics with adiabaticity parameter `ε > 0` is the evolution `U`
generated by the Schrödinger term `-(I/ε) • H s` together with Kato's geometric term
`[dP s, P s] = dP s * P s - P s * dP s`, which is precisely the generator obtained in the
slow (adiabatic) limit of the Schrödinger equation `i ε ψ' = H ψ`.

Conclusion.  A state `ψ₀` that starts in the eigenspace (`P 0 ψ₀ = ψ₀`) stays in the
instantaneous eigenspace for all times: `P s (U s ψ₀) = U s ψ₀`, and consequently it remains an
instantaneous eigenvector of `H s` with the instantaneous eigenvalue `e s`.

(The nondegeneracy hypothesis `hnondeg` and the positivity `hε` of the adiabaticity parameter are
stated because they are part of the physical statement, but they are not needed for the proof:
the conclusion holds for a spectral projection of any rank and for every nonzero `ε`.) -/
