/-
# Noether Conservation
Category: Frontier Physics
Target: Frontier.noether_conservation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

-- (Lean requires `import` lines to precede every command, including module docstrings,
-- so the requested header is repeated verbatim as a module docstring just below.)

import Mathlib

/-!
# Noether Conservation
Category: Frontier Physics
Target: Frontier.noether_conservation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-!
## Setting

We treat the one–dimensional case of Noether's theorem.  The configuration space is `ℝ`, a *path*
is a function `q : ℝ → ℝ` of time with velocity `q'`, and the dynamics comes from a Lagrangian
`L : ℝ → ℝ → ℝ`, written `L x v` for position `x` and velocity `v`, with action
`S[q] = ∫ L (q t) (q' t) dt`.

The two partial derivatives of `L` are carried as data, `L₁ = ∂L/∂x` and `L₂ = ∂L/∂v`
(the momentum); the hypothesis `HasPartials L L₁ L₂` says exactly that `L` is differentiable
with those partial derivatives.

A **smooth symmetry** is generated by a smooth vector field `X : ℝ → ℝ` on configuration space:
the flow moves positions by `x ↦ x + s * X x + o(s)` and hence velocities by
`v ↦ v + s * (X' x * v) + o(s)`.  Invariance of the action under this flow, to first order in the
flow parameter `s`, is the statement `IsFlowSymmetry`:
`(d/ds)|₀ L (x + s * X x) (v + s * (X' x * v)) = 0` for all `x, v`.

**Noether's theorem (1D).**  Along any solution of the Euler–Lagrange equation
`(d/dt) (L₂ (q t) (q' t)) = L₁ (q t) (q' t)` the *Noether current*
`J t = L₂ (q t) (q' t) * X (q t)` is conserved.
-/

/-- The Noether current attached to a Lagrangian momentum `L₂ = ∂L/∂v`, a path `q` with velocity
`q'`, and an infinitesimal symmetry `X`: `J t = (∂L/∂v) (q t, q' t) * X (q t)`. -/

theorem freeParticle_hasPartials :
    HasPartials (fun _ v : ℝ => v ^ 2 / 2) (fun _ _ => 0) (fun _ v => v) ∧
      IsFlowSymmetry (fun _ v : ℝ => v ^ 2 / 2) (fun _ => 1) (fun _ => 0) := by
  constructor
  · intro x v
    have hg : HasDerivAt (fun w : ℝ => w ^ 2 / 2) v v := by
      simpa using ((hasDerivAt_id v).pow 2).div_const 2
    have h := hg.comp_hasFDerivAt (x, v) (hasFDerivAt_snd (𝕜 := ℝ) (p := (x, v)))
    refine h.congr_fderiv (ContinuousLinearMap.ext fun p => ?_)
    simp [lagrangianDeriv]
  · intro x v
    simpa using hasDerivAt_const (0 : ℝ) (v ^ 2 / 2)

/-- Non-vacuity check: all the hypotheses of `noether_conservation` are simultaneously satisfiable,
and the resulting conserved current can be any prescribed nonzero value.  Here the system is the
free particle `L x v = v ^ 2 / 2`, the path is the uniform motion `q t = c * t + b`, the symmetry is
the translation `X = 1`, and the Noether current is the (constant) momentum `c`. -/
