/-
/-!
# Noether Conservation
Category: Frontier Physics
Target: Frontier.noether_conservation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
-/
-- (The header above is wrapped in a plain block comment because Lean 4 requires
-- `import` commands to precede any module docstring `/-! ... -/`.)

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-!
## Setting

We work with a one–dimensional mechanical system with Lagrangian `L : ℝ → ℝ → ℝ`,
written `L x v` (position `x`, velocity `v`).  Its partial derivatives are given by
functions `L₁` (w.r.t. position) and `L₂` (w.r.t. velocity).

A *path* is `q : ℝ → ℝ` with velocity `v : ℝ → ℝ`, i.e. `q' = v`.
The path is a *stationary point of the action* iff it satisfies the Euler–Lagrange
equation
  `d/dt (L₂ (q t) (v t)) = L₁ (q t) (v t)`.

An infinitesimal (smooth) symmetry is a vector field `X : ℝ → ℝ` on configuration
space, with derivative `X'`.  It acts on curves by `q ↦ q + s • X ∘ q`, hence on the
velocity by `v ↦ v + s • (X' ∘ q) * v`.  Invariance of the action to first order in
`s` is exactly the pointwise identity

  `L₁ x v * X x + L₂ x v * (X' x * v) = 0`.

Noether's theorem: the *current* `J t = L₂ (q t) (v t) * X (q t)` is conserved.
-/

/-- The Noether current attached to a Lagrangian `L` (with velocity–partial `L₂`),
a path `q` with velocity `v`, and an infinitesimal symmetry `X`:
`J t = L₂ (q t) (v t) * X (q t)`, i.e. momentum times the symmetry generator. -/

theorem infinitesimal_invariance_of_symmetry
    (L L₁ L₂ : ℝ → ℝ → ℝ) (X X' : ℝ → ℝ)
    (hL : ∀ x u : ℝ, HasFDerivAt (fun p : ℝ × ℝ => L p.1 p.2)
      (L₁ x u • (ContinuousLinearMap.fst ℝ ℝ ℝ) + L₂ x u • (ContinuousLinearMap.snd ℝ ℝ ℝ)) (x, u))
    (hsym : ∀ s x u : ℝ, L (x + s * X x) (u + s * (X' x * u)) = L x u) :
    ∀ x u : ℝ, L₁ x u * X x + L₂ x u * (X' x * u) = 0 := by
  intro x u
  have hg : HasDerivAt (fun s : ℝ => ((x + s * X x, u + s * (X' x * u)) : ℝ × ℝ))
      (X x, X' x * u) 0 := by
    have h1 : HasDerivAt (fun s : ℝ => x + s * X x) (X x) 0 := by
      simpa using ((hasDerivAt_id (0 : ℝ)).mul_const (X x)).const_add x
    have h2 : HasDerivAt (fun s : ℝ => u + s * (X' x * u)) (X' x * u) 0 := by
      simpa using ((hasDerivAt_id (0 : ℝ)).mul_const (X' x * u)).const_add u
    exact h1.prodMk h2
  have hL0 : HasFDerivAt (fun p : ℝ × ℝ => L p.1 p.2)
      (L₁ x u • (ContinuousLinearMap.fst ℝ ℝ ℝ) + L₂ x u • (ContinuousLinearMap.snd ℝ ℝ ℝ))
      ((fun s : ℝ => ((x + s * X x, u + s * (X' x * u)) : ℝ × ℝ)) 0) := by
    simpa using hL x u
  have hcomp := hL0.comp_hasDerivAt 0 hg
  have hconst : HasDerivAt (fun s : ℝ => L (x + s * X x) (u + s * (X' x * u))) 0 0 := by
    simpa [hsym] using (hasDerivAt_const (0 : ℝ) (L x u))
  have huniq := hcomp.unique hconst
  simpa [eq_comm] using huniq.symm

/-- **Noether's theorem from a finite symmetry (1D case).**

Same conclusion as `noether_conservation`, but with the infinitesimal invariance
hypothesis replaced by invariance of the Lagrangian under the one–parameter family
of transformations generated by the vector field `X`. -/
