import Mathlib
-- (Lean 4 requires `import` lines to precede any module docstring; the requested header
-- follows verbatim immediately below.)
/-!
# Noether Conservation
Category: Frontier Physics
Target: Frontier.noether_conservation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Frontier

/-- **Infinitesimal invariance in coordinates.**

If the Lagrangian `L : ℝ × ℝ → ℝ` (position, velocity) has total derivative described by the
partials `Lq` (with respect to position) and `Lv` (with respect to velocity), and if `L` is
invariant to first order under the one-parameter family of transformations
`(x, y) ↦ (x + ε X x, y + ε X' x * y)` generated by the vector field `X` (with derivative `X'`),
then the pointwise identity `Lq * X + Lv * (X' * y) = 0` holds. -/

theorem noether_symmetry_identity
    (L Lq Lv : ℝ × ℝ → ℝ)
    (hL : ∀ p : ℝ × ℝ, HasFDerivAt L
      (Lq p • ContinuousLinearMap.fst ℝ ℝ ℝ + Lv p • ContinuousLinearMap.snd ℝ ℝ ℝ) p)
    (X X' : ℝ → ℝ) (x y : ℝ)
    (hsym : HasDerivAt (fun e : ℝ => L (x + e * X x, y + e * (X' x * y))) 0 0) :
    Lq (x, y) * X x + Lv (x, y) * (X' x * y) = 0 := by
  have hc : HasDerivAt (fun e : ℝ => (x + e * X x, y + e * (X' x * y))) (X x, X' x * y) 0 := by
    have h1 : HasDerivAt (fun e : ℝ => x + e * X x) (X x) 0 := by
      simpa using ((hasDerivAt_id (0:ℝ)).mul_const (X x)).const_add x
    have h2 : HasDerivAt (fun e : ℝ => y + e * (X' x * y)) (X' x * y) 0 := by
      simpa using ((hasDerivAt_id (0:ℝ)).mul_const (X' x * y)).const_add y
    exact h1.prodMk h2
  have hcomp := (hL ((fun e : ℝ => (x + e * X x, y + e * (X' x * y))) 0)).comp_hasDerivAt (0:ℝ) hc
  simp only [zero_mul, add_zero] at hcomp
  have h0 := hcomp.unique hsym
  simp only [ContinuousLinearMap.add_apply, ContinuousLinearMap.smul_apply,
    ContinuousLinearMap.coe_fst', ContinuousLinearMap.coe_snd', smul_eq_mul] at h0
  linarith [h0]

/-- **The Noether current has vanishing derivative.**

Along a solution `q` of the Euler–Lagrange equation, the Noether current
`J t = Lv (q t, q' t) * X (q t)` has derivative `Lq * X + Lv * (X' * q')`, which vanishes by
infinitesimal invariance. -/
