/-
# Noether Conservation
Category: Frontier Physics
Target: Frontier.noether_conservation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

-- (Lean requires `import` lines to precede every command, including module docstrings,
-- so the requested header is repeated verbatim as a module docstring just below.)

import Mathlib

/-!
# Noether Conservation
Category: Frontier Physics
Target: Frontier.noether_conservation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-!
## Setting

We treat the one–dimensional case of Noether's theorem.  The configuration space is `ℝ`, a *path*
is a function `q : ℝ → ℝ` of time with velocity `q'`, and the dynamics comes from a Lagrangian
`L : ℝ → ℝ → ℝ`, written `L x v` for position `x` and velocity `v`, with action
`S[q] = ∫ L (q t) (q' t) dt`.

The two partial derivatives of `L` are carried as data, `L₁ = ∂L/∂x` and `L₂ = ∂L/∂v`
(the momentum); the hypothesis `HasPartials L L₁ L₂` says exactly that `L` is differentiable
with those partial derivatives.

A **smooth symmetry** is generated by a smooth vector field `X : ℝ → ℝ` on configuration space:
the flow moves positions by `x ↦ x + s * X x + o(s)` and hence velocities by
`v ↦ v + s * (X' x * v) + o(s)`.  Invariance of the action under this flow, to first order in the
flow parameter `s`, is the statement `IsFlowSymmetry`:
`(d/ds)|₀ L (x + s * X x) (v + s * (X' x * v)) = 0` for all `x, v`.

**Noether's theorem (1D).**  Along any solution of the Euler–Lagrange equation
`(d/dt) (L₂ (q t) (q' t)) = L₁ (q t) (q' t)` the *Noether current*
`J t = L₂ (q t) (q' t) * X (q t)` is conserved.
-/

/-- The Noether current attached to a Lagrangian momentum `L₂ = ∂L/∂v`, a path `q` with velocity
`q'`, and an infinitesimal symmetry `X`: `J t = (∂L/∂v) (q t, q' t) * X (q t)`. -/

theorem noether_conservation_of_infinitesimalSymmetry
    (L₁ L₂ : ℝ → ℝ → ℝ) (q q' X X' : ℝ → ℝ)
    (hq : ∀ t : ℝ, HasDerivAt q (q' t) t)
    (hX : ∀ x : ℝ, HasDerivAt X (X' x) x)
    (hEL : SatisfiesEulerLagrange L₁ L₂ q q')
    (hsym : IsInfinitesimalSymmetry L₁ L₂ X X') :
    ∀ t₀ t₁ : ℝ, noetherCurrent L₂ q q' X t₀ = noetherCurrent L₂ q q' X t₁ := by
  have hd : ∀ t : ℝ, HasDerivAt (noetherCurrent L₂ q q' X) 0 t := fun t =>
    hasDerivAt_noetherCurrent_zero L₁ L₂ q q' X X' hq hX hEL hsym t
  have hdiff : Differentiable ℝ (noetherCurrent L₂ q q' X) := fun t => (hd t).differentiableAt
  have hderiv : ∀ t : ℝ, deriv (noetherCurrent L₂ q q' X) t = 0 := fun t => (hd t).deriv
  exact fun t₀ t₁ => is_const_of_deriv_eq_zero hdiff hderiv t₀ t₁

/-- **Noether's theorem, one–dimensional case.**

Let `L : ℝ → ℝ → ℝ` be a Lagrangian, differentiable with partial derivatives `L₁ = ∂L/∂x` and
`L₂ = ∂L/∂v`, and let `X : ℝ → ℝ` be a smooth vector field on the configuration space with
derivative `X'`.  Assume `X` generates a symmetry of the action: the Lagrangian is invariant, to
first order, along the prolonged flow `(x, v) ↦ (x + s * X x, v + s * (X' x * v))`.

Then along every solution `q` (with velocity `q'`) of the Euler–Lagrange equation, the associated
Noether current `J t = L₂ (q t) (q' t) * X (q t)` is a conserved quantity: it takes the same value
at all times. -/
