import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Chem

attribute [local instance] arrowAction

variable {G P C : Type*} [Group G] [MulAction G P]

/-- A *substitution pattern* on a molecular skeleton with positions `P` and possible
substituents `C` is a labelling of every position by a substituent.  The symmetry group of
the skeleton acts on such labellings by `(g • c) p = c (g⁻¹ • p)`. -/
abbrev Coloring (P C : Type*) : Type _ := P → C

/-- Two substitution patterns describe the same *isomer* when they differ by a symmetry of the
skeleton; the isomers are therefore the orbits of the symmetry group `G` acting on colorings. -/
abbrev Isomer (G P C : Type*) [Group G] [MulAction G P] : Type _ :=
  MulAction.orbitRel.Quotient G (Coloring P C)

/-- The number of cycles of the symmetry `g` acting on the positions of the skeleton, i.e. the
number of orbits of the cyclic group generated by `g`.  This is the exponent appearing in the
Pólya cycle index. -/

lemma addOrderOf_zmod_six (a : ZMod 6) : addOrderOf a = 6 / Nat.gcd 6 a.val := by
  conv_lhs => rw [show a = ((a.val : ℕ) : ZMod 6) by simp]
  exact ZMod.addOrderOf_coe a.val (by norm_num)

/-- **Benzene.** The six positions of the benzene ring, acted on by the cyclic rotation group
`C₆` (acting regularly on the positions), with two possible substituents at each position
(say H or Cl): there are exactly `14` substitution patterns up to rotation, in agreement with
the Pólya cycle-index average `(2⁶ + 2 + 2² + 2³ + 2² + 2)/6 = 84/6 = 14`. -/
