import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)

(Note: Lean 4 requires `import` commands to precede any other command, including module
docstrings, so the header block appears immediately after the import.)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

open MulAction

/- The symmetry group `G` of a skeleton acts on the substituted molecules (colourings of the
positions `P` by substituents `C`) by `(g • f) p = f (g⁻¹ • p)`. -/
attribute [local instance] arrowAction

variable {G P C : Type*} [Group G] [MulAction G P]

/-- A colouring fixed by `g` is constant along the orbits of the cyclic group generated by `g`. -/

theorem card_fixedBy_colorings (g : G) [Finite P] :
    Nat.card (MulAction.fixedBy (P → C) g)
      = Nat.card C ^ Nat.card (MulAction.orbitRel.Quotient (Subgroup.zpowers g) P) := by
  rw [Nat.card_congr (fixedColoringsEquiv (C := C) g), Nat.card_fun]

/-- **Pólya / Burnside isomer count.**  Let a finite symmetry group `G` act on the positions `P`
of a molecular skeleton, and let `C` be a finite set of substituents.  Substitution isomers are
the orbits of `G` on the colourings `P → C`.  Their number, multiplied by `|G|`, equals the sum
over the symmetries `g ∈ G` of `|C|` raised to the number of cycles of `g` on the positions,
i.e. the isomer count is the Pólya cycle-index average
`(1/|G|) ∑_{g ∈ G} |C| ^ (number of cycles of g)`. -/
