import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)

(Note: Lean 4 requires `import` commands to precede any other command, including module
docstrings, so the header block appears immediately after the import.)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

open MulAction

/- The symmetry group `G` of a skeleton acts on the substituted molecules (colourings of the
positions `P` by substituents `C`) by `(g • f) p = f (g⁻¹ • p)`. -/
attribute [local instance] arrowAction

variable {G P C : Type*} [Group G] [MulAction G P]

/-- A colouring fixed by `g` is constant along the orbits of the cyclic group generated by `g`. -/

theorem coloring_invariant_of_fixed {g : G} {f : P → C} (hf : g • f = f) {h : G}
    (hh : h ∈ Subgroup.zpowers g) (p : P) : f (h • p) = f p := by
  have hs : h • f = f := (Subgroup.zpowers_le (H := MulAction.stabilizer G f)).mpr hf hh
  calc f (h • p) = (h • f) (h • p) := by rw [hs]
    _ = f (h⁻¹ • h • p) := rfl
    _ = f p := by simp

/-- The colourings of the positions `P` by substituents `C` that are fixed by a symmetry `g`
are exactly the colourings that are constant on the cycles of `g`, i.e. they correspond to
arbitrary colourings of the orbit set of `⟨g⟩` acting on `P`. -/
