import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/


open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames false

namespace Chem

attribute [local instance] arrowAction

variable {G : Type*} [Group G] {P : Type*} [MulAction G P] {C : Type*}

/-- The number of cycles of the skeleton symmetry `g` acting on the substitution sites `P`:
the number of orbits of the cyclic group generated by `g`. -/

lemma cycleCount_one : cycleCount P (1 : G) = Nat.card P := by
  refine Nat.card_congr ?_
  refine
    { toFun := fun q => Quotient.liftOn q id ?_
      invFun := fun p => Quotient.mk _ p
      left_inv := ?_
      right_inv := fun p => rfl }
  · rintro a b ⟨⟨h, hh⟩, rfl⟩
    have : h = 1 := by
      simpa [Subgroup.zpowers_one_eq_bot, Subgroup.mem_bot] using hh
    subst this
    simp
  · intro q
    induction q using Quotient.inductionOn with
    | _ p => rfl

/-- Colorings of the skeleton fixed by `g` correspond exactly to colorings of the set of
`⟨g⟩`-orbits (cycles) of `g`. -/
