import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

/-!
# Pólya / Burnside counting of substitution isomers

A *skeleton* is a finite set of substitution positions `P` carrying an action of the
symmetry group `G` of the molecule.  A *substitution pattern* (a labelling of every
position by one of the available substituents, drawn from a finite set `S`) is a function
`P → S`, and two patterns describe the *same isomer* exactly when they differ by a symmetry
of the skeleton, i.e. when they lie in the same orbit of the induced action
`(g • c) p = c (g⁻¹ • p)` of `G` on `P → S`.

The main result `Chem.polya_isomer_count` says that the number of isomers is the
Burnside/Pólya cycle-index average

`#isomers = (1 / |G|) * ∑_{g ∈ G} |S| ^ (number of cycles of g on P)`,

stated in the division-free form `#isomers * |G| = ∑_{g ∈ G} |S| ^ c(g)`; the version with
an honest average over `ℚ` is `Chem.polya_isomer_count_average`.

Here the number of cycles of `g` acting on the positions is, as usual, the number of orbits
of the cyclic group `⟨g⟩` generated by `g` (`Chem.cycleCount`).
-/

namespace Chem

-- The action of `G` on substitution patterns: `(g • c) p = c (g⁻¹ • p)`.
attribute [local instance] arrowAction

variable {G P S : Type*} [Group G] [MulAction G P]

/-- The number of cycles of the symmetry `g` acting on the set of positions `P`, i.e. the
number of orbits of the cyclic group generated by `g`.  This is the exponent occurring in
the Pólya cycle index. -/

noncomputable def cycleCount (g : G) (P : Type*) [MulAction G P] : ℕ :=
  Nat.card (MulAction.orbitRel.Quotient (Subgroup.zpowers g) P)

/-- A substitution pattern fixed by `g` is constant along the `⟨g⟩`-orbits of the positions. -/
