import Mathlib

/-!
# Yang Mills Mass Gap
Category: Frontier — Moonshot
Target: Frontier.yang_mills_mass_gap
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 1000000
set_option maxRecDepth 4000

set_option relaxedAutoImplicit false
set_option autoImplicit false

namespace Frontier

open scoped InnerProductSpace

/-! ## The vacuum sector of a Euclidean (Osterwalder–Schrader) quantum field theory -/

/-- The Hilbert-space data of the vacuum sector of a quantum field theory:
a complex Hilbert space `Hilb`, a distinguished unit vector `vac` (the vacuum),
and the Euclidean-time semigroup `P t = e^{-tH}` generated by the Hamiltonian `H`.
The axioms say that `P` is a strongly-continuity-free, self-adjoint, contractive
one-parameter semigroup fixing the vacuum; equivalently `H` is a positive
self-adjoint operator annihilating the vacuum. -/
structure QFT where
  /-- The Hilbert space of states. -/
  Hilb : Type
  [instNormed : NormedAddCommGroup Hilb]
  [instInner : InnerProductSpace ℂ Hilb]
  [instComplete : CompleteSpace Hilb]
  /-- The Euclidean-time semigroup `P t = e^{-t H}`. -/
  P : ℝ → Hilb →L[ℂ] Hilb
  /-- The vacuum vector. -/
  vac : Hilb
  vac_norm : ‖vac‖ = 1
  P_zero : ∀ x, P 0 x = x
  P_add : ∀ s t, 0 ≤ s → 0 ≤ t → ∀ x, P (s + t) x = P s (P t x)
  /-- Each `P t` is self-adjoint (`H` is self-adjoint). -/
  P_symm : ∀ t, 0 ≤ t → ∀ x y, ⟪P t x, y⟫_ℂ = ⟪x, P t y⟫_ℂ
  /-- Each `P t` is a contraction (`H ≥ 0`, the spectrum condition). -/
  P_contract : ∀ t, 0 ≤ t → ∀ x, ‖P t x‖ ≤ ‖x‖
  /-- The vacuum has zero energy. -/
  P_vac : ∀ t, 0 ≤ t → P t vac = vac

attribute [instance] QFT.instNormed QFT.instInner QFT.instComplete

namespace QFT

variable (T : QFT)

/-- The states orthogonal to the vacuum, i.e. the physical excitations. -/

theorem le_of_pow_two_pow_le {a b K : ℝ} (hb : 0 ≤ b) (hK : 0 < K)
    (h : ∀ k : ℕ, a ^ (2 ^ k) ≤ K * b ^ (2 ^ k)) : a ≤ b := by
  by_contra hlt
  push_neg at hlt
  rcases eq_or_lt_of_le hb with hb0 | hb0
  · have h1 := h 1
    rw [← hb0] at h1
    norm_num at h1
    nlinarith
  · have hr : 1 < a / b := (one_lt_div hb0).mpr hlt
    obtain ⟨n, hn⟩ := pow_unbounded_of_one_lt K hr
    have h2 : (a / b) ^ n ≤ (a / b) ^ (2 ^ n) :=
      pow_le_pow_right₀ hr.le (Nat.lt_two_pow_self).le
    have h3 : (a / b) ^ (2 ^ n) ≤ K := by
      rw [div_pow, div_le_iff₀ (by positivity)]
      linarith [h n]
    linarith

namespace QFT

variable {T : QFT}

/-- Euclidean time evolution preserves the orthogonal complement of the vacuum. -/
