import Mathlib

/-!
# Yang Mills Mass Gap
Category: Frontier — Moonshot
Target: Frontier.yang_mills_mass_gap
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 1000000
set_option maxRecDepth 4000

set_option relaxedAutoImplicit false
set_option autoImplicit false

namespace Frontier

open scoped InnerProductSpace

/-! ## The vacuum sector of a Euclidean (Osterwalder–Schrader) quantum field theory -/

/-- The Hilbert-space data of the vacuum sector of a quantum field theory:
a complex Hilbert space `Hilb`, a distinguished unit vector `vac` (the vacuum),
and the Euclidean-time semigroup `P t = e^{-tH}` generated by the Hamiltonian `H`.
The axioms say that `P` is a strongly-continuity-free, self-adjoint, contractive
one-parameter semigroup fixing the vacuum; equivalently `H` is a positive
self-adjoint operator annihilating the vacuum. -/
structure QFT where
  /-- The Hilbert space of states. -/
  Hilb : Type
  [instNormed : NormedAddCommGroup Hilb]
  [instInner : InnerProductSpace ℂ Hilb]
  [instComplete : CompleteSpace Hilb]
  /-- The Euclidean-time semigroup `P t = e^{-t H}`. -/
  P : ℝ → Hilb →L[ℂ] Hilb
  /-- The vacuum vector. -/
  vac : Hilb
  vac_norm : ‖vac‖ = 1
  P_zero : ∀ x, P 0 x = x
  P_add : ∀ s t, 0 ≤ s → 0 ≤ t → ∀ x, P (s + t) x = P s (P t x)
  /-- Each `P t` is self-adjoint (`H` is self-adjoint). -/
  P_symm : ∀ t, 0 ≤ t → ∀ x y, ⟪P t x, y⟫_ℂ = ⟪x, P t y⟫_ℂ
  /-- Each `P t` is a contraction (`H ≥ 0`, the spectrum condition). -/
  P_contract : ∀ t, 0 ≤ t → ∀ x, ‖P t x‖ ≤ ‖x‖
  /-- The vacuum has zero energy. -/
  P_vac : ∀ t, 0 ≤ t → P t vac = vac

attribute [instance] QFT.instNormed QFT.instInner QFT.instComplete

namespace QFT

variable (T : QFT)

/-- The states orthogonal to the vacuum, i.e. the physical excitations. -/

def YangMillsMassGapStatement (G : Type) [Group G] [TopologicalSpace G] [CompactSpace G] :
    Prop :=
  ∃ T : YangMillsTheory G, ∃ Δ : ℝ, 0 < Δ ∧ T.toQFT.HasMassGap Δ

/-! ## The reduction: a single-time contraction bound implies a mass gap -/

/-- An elementary real-analysis lemma: if `a ^ (2 ^ k) ≤ K * b ^ (2 ^ k)` for every `k`
with a fixed constant `K > 0`, then `a ≤ b`.  This is what removes the constant from a
"exponential decay up to a constant" bound. -/
