/-
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

namespace PCA.Cert

/-!
## An abstract model of Ed25519 signature verification

We model the group-theoretic core of Ed25519 (the part an isolation engine's
certificate checker relies upon):

* `G` is the prime-order subgroup generated by the base point `B`, written
  additively, and equipped with a scalar action of `ZMod L` (`L` being the group
  order, i.e. the order of the base point).
* A secret key is a scalar `s : ZMod L`; the corresponding public key is
  `A = s • B`.
* A signature on a message `m` with nonce `r` is the pair `(R, S)` where
  `R = r • B` and `S = r + H(R, A, m) * s`.
* Verification of `(R, S)` against `A` checks the standard equation
  `S • B = R + H(R, A, m) • A`.

The hash function `H` is left completely abstract (an arbitrary function), so no
property of SHA-512 is assumed anywhere.
-/

variable {L : ℕ} {G : Type*} {Msg : Type*}

/-- The public key associated with the secret scalar `s`. -/

theorem ed25519_verify_sound [AddCommGroup G] [Module (ZMod L) G] {B : G}
    (hB : Function.Injective (fun x : ZMod L => x • B))
    (H : G → G → Msg → ZMod L) (s r S : ZMod L) (m : Msg) :
    Verify B H (pubKey B s) (r • B) S m ↔
      S = r + H (r • B) (pubKey B s) m * s := by
  unfold Verify pubKey
  rw [smul_smul, ← add_smul]
  exact hB.eq_iff

/-- Completeness: an honestly generated Ed25519 signature always verifies. -/
