/-
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/
-- (The requested header is reproduced verbatim above as a plain block comment:
-- Lean 4 rejects a module doc comment `/-! ... -/` placed before the `import` line.)

import Mathlib

/-!
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)

## A model of Ed25519 (Schnorr-style) signature verification

Ed25519 works in the prime-order subgroup generated by a fixed base point `B` of a
twisted Edwards curve.  We model that subgroup abstractly: `G` is an additive
commutative group which is a module over `ZMod p` for a prime `p` (this is exactly
the situation for a group of prime exponent `p`, e.g. the order-`ℓ` subgroup of the
Ed25519 curve, where `ℓ = 2^252 + 27742317777372353535851937790883648493`).

* the secret key is a scalar `a : ZMod p`, the public key is `A = a • B`;
* a signature is a pair `(R, s)` with `R : G` and `s : ZMod p`;
* the challenge is `h = H R A m` for a hash function `H` (modelled as an arbitrary
  function — no property of `H` is needed for the statements below);
* verification checks `s • B = R + h • A`;
* honest signing with nonce `r` produces `R = r • B` and `s = r + h * a`.

The target theorem `PCA.Cert.ed25519_verify_sound` states that, for a signature whose
commitment `R` is a known multiple `r • B` of the base point, verification under the
public key `a • B` succeeds *exactly* for the honestly generated signature.  This gives
both soundness (a verifying signature must be the honest one, i.e. `s` is the correct
Schnorr response for the nonce `r` and the secret key `a`) and completeness (the honest
signature always verifies).

The key Mathlib ingredient is `smul_eq_zero` (available here because a module over the
field `ZMod p` has `NoZeroSMulDivisors`), which turns `c • B = 0` with `B ≠ 0` into
`c = 0`.
-/

namespace PCA.Cert

/-- A signature: a curve point `R` together with a scalar response `s`. -/
structure Signature (G : Type*) (p : ℕ) where
  /-- The commitment point. -/
  R : G
  /-- The scalar response. -/
  s : ZMod p

variable {G : Type*} {M : Type*} {p : ℕ}

section Defs

variable [AddCommGroup G] [Module (ZMod p) G]

/-- The public key associated to the secret scalar `a` and base point `B`. -/

theorem ed25519_response_eq {B : G} (hB : B ≠ 0) (H : G → G → M → ZMod p) (m : M)
    (a r : ZMod p) (sig : Signature G p) (hR : sig.R = r • B)
    (hv : verify B (publicKey B a) H m sig) :
    sig.s = r + (H sig.R (publicKey B a) m) * a := by
  have hsig := (ed25519_verify_sound hB H m a r sig hR).1 hv
  rw [hsig]
  simp [sign]

end PCA.Cert

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

