/-
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace PCA.Cert

/-- The order `ℓ = 2^252 + 27742317777372353535851937790883648493` of the prime-order
subgroup of the Ed25519 curve group generated by the standard base point. -/

def ed25519Order : ℕ := 2 ^ 252 + 27742317777372353535851937790883648493

/-- Scalars of the Ed25519 signature scheme: residues modulo the group order `ℓ`. -/
abbrev Scalar : Type := ZMod ed25519Order

/-- Parameters of the Ed25519 verification engine: a carrier group `G` of exponent `ℓ`
(so that it is a `ZMod ed25519Order`-module) together with a base point that
generates it faithfully, i.e. `c ↦ c • base` is a bijection from `Scalar` onto `G`.
This is exactly the abstract model of the prime-order subgroup that the isolation
engine's certificate checker reasons about. -/
structure Params (G : Type*) [AddCommGroup G] [Module Scalar G] where
  /-- The standard base point `B`. -/
  base : G
  /-- The base point has exact order `ℓ`: no nonzero scalar annihilates it. -/
  base_faithful : ∀ c : Scalar, c • base = 0 → c = 0
  /-- The base point generates the whole carrier group. -/
  base_generates : ∀ Q : G, ∃ c : Scalar, Q = c • base

variable {G : Type*} [AddCommGroup G] [Module Scalar G]

/-- A signature is a group element `R` together with a scalar `S`. -/
structure Sig (G : Type*) where
  /-- The commitment point `R`. -/
  R : G
  /-- The response scalar `S`. -/
  S : Scalar

/-- The public key associated with a secret scalar `a` is `A = a • B`. -/
