/-
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace PCA.Cert

/-- The order `ℓ = 2^252 + 27742317777372353535851937790883648493` of the prime-order
subgroup of the Ed25519 curve group generated by the standard base point. -/

theorem ed25519_extract_secret [Fact (Nat.Prime ed25519Order)] (P : Params G)
    (a S₁ S₂ h₁ h₂ : Scalar) (R : G)
    (hne : h₁ ≠ h₂)
    (hv₁ : S₁ • P.base = R + h₁ • publicKey P a)
    (hv₂ : S₂ • P.base = R + h₂ • publicKey P a) :
    a = (S₁ - S₂) / (h₁ - h₂) := by
  have hkey : (S₁ - S₂) • P.base = ((h₁ - h₂) * a) • P.base := by
    rw [sub_smul, hv₁, hv₂, publicKey, sub_mul, sub_smul, mul_smul, mul_smul]
    abel
  have h1 : S₁ - S₂ = (h₁ - h₂) * a := smul_base_inj P hkey
  have h2 : h₁ - h₂ ≠ 0 := sub_ne_zero.mpr hne
  rw [eq_div_iff h2, h1]
  ring

/-- The model is non-vacuous: the cyclic group `ZMod ed25519Order` with base point `1`
is a legitimate instance of `Params`, so the theorems above are not vacuously true. -/
