/-!
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

/-
## Overview

This file formalises the algebraic core of Ed25519 signature verification, as used by a
proof-carrying-application *isolation engine*: the engine admits a payload only when the
attached certificate carries an Ed25519 signature that verifies against the enclave's
public key.

The concrete twisted-Edwards curve is abstracted to exactly the structure the argument
uses: a type `G` of curve points with an addition `add`, an integer scalar multiplication
`smul`, a base point `B`, and the order `L` of `B` (for Ed25519,
`L = 2 ^ 252 + 27742317777372353535851937790883648493`).  The three laws recorded in
`PCA.Cert.EdModel` are:

* `smul_add_base` : `[x]B + [y]B = [x + y]B`   (the group law on the cyclic subgroup `⟨B⟩`);
* `smul_smul_base` : `[x]([y]B) = [x * y]B`     (associativity of scalar multiplication);
* `base_eq_iff`   : `[x]B = [y]B ↔ L ∣ x - y`   (`B` has order exactly `L`).

`PCA.Cert.EdModel.ofOrder` builds such a model for every `L > 1`, so the axiomatisation is
consistent and the results below are not vacuous; `PCA.Cert.ed25519Model` instantiates it at
the true Ed25519 group order.  A Mathlib-idiomatic restatement over an arbitrary
`AddCommGroup` with a point of order `L`, together with the bridge to the results proved
here, lives in `RequestProject.Ed25519Mathlib`.

Key generation, signing and verification are modelled by

* secret scalar `s`, public key `A = [s]B`                          (`pubKey`),
* per-message nonce `r`, commitment `R = [r]B`                      (`commit`),
* challenge `h` (the integer `H(R ‖ A ‖ M)`),
* response `S = (r + h * s) mod L`                                  (`respond`),
* verification `[S]B = R + [h]A`                                    (`Verify`).

Main results:

* `ed25519_verify_sound` — **soundness**: whenever verification accepts a signature
  `(R, S)` under a public key `A = [s]B` with commitment `R = [r]B`, the response `S` is
  forced to be congruent mod `L` to the honest Schnorr response `r + h * s`.  No accepted
  signature can deviate from what the signing algorithm produces.
* `ed25519_verify_complete` — **completeness**: honestly generated signatures always verify.
* `ed25519_verify_iff` — soundness and completeness combined into a characterisation.
* `ed25519_response_unique` — the accepted response is unique modulo `L`.
* `ed25519_extract_secret_key` — special soundness: two accepting transcripts that share a
  commitment but use different challenges determine the secret key.
* `ed25519_engine_sound` — the isolation-engine reading: an admitted certificate carries
  precisely the honest signature of its payload under the enclave key.

The development is self-contained: it uses no imports beyond Lean's core `Init`, hence no
axioms beyond `propext`, `Classical.choice`, `Quot.sound`.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

universe u

namespace PCA.Cert

/-! ## The model -/

/-- An Ed25519-style signature model: a type of curve points `G` with addition `add`,
integer scalar multiplication `smul`, base point `B`, and group order `L` of `B`.

Only the behaviour of the operations on the cyclic subgroup generated by `B` is recorded,
since verification never leaves that subgroup. -/
structure EdModel (G : Type u) where
  /-- Addition of curve points. -/
  add : G → G → G
  /-- Integer scalar multiplication of curve points. -/
  smul : Int → G → G
  /-- The base point. -/
  B : G
  /-- The order of the base point (a prime, for Ed25519). -/
  L : Int
  /-- The order exceeds `1`. -/
  one_lt_L : 1 < L
  /-- Group law on `⟨B⟩`: `[x]B + [y]B = [x + y]B`. -/
  smul_add_base : ∀ x y : Int, add (smul x B) (smul y B) = smul (x + y) B
  /-- Associativity of scalar multiplication on `⟨B⟩`: `[x]([y]B) = [x * y]B`. -/
  smul_smul_base : ∀ x y : Int, smul x (smul y B) = smul (x * y) B
  /-- `B` has order exactly `L`: `[x]B = [y]B` iff `L` divides `x - y`. -/
  base_eq_iff : ∀ x y : Int, smul x B = smul y B ↔ L ∣ (x - y)

namespace EdModel

variable {G : Type u} (M : EdModel G)

/-- The public key belonging to the secret scalar `s`, namely `A = [s]B`. -/

theorem ed25519_extract_secret_key {s r h₁ h₂ S₁ S₂ : Int}
    (hv₁ : M.Verify (M.pubKey s) (M.commit r) h₁ S₁)
    (hv₂ : M.Verify (M.pubKey s) (M.commit r) h₂ S₂) :
    M.L ∣ ((h₁ - h₂) * s - (S₁ - S₂)) := by
  obtain ⟨k₁, hk₁⟩ := ed25519_verify_sound hv₁
  obtain ⟨k₂, hk₂⟩ := ed25519_verify_sound hv₂
  refine ⟨-(k₁ - k₂), ?_⟩
  have hexp : (h₁ - h₂) * s = h₁ * s - h₂ * s := by
    rw [Int.sub_mul]
  rw [hexp, Int.mul_neg, Int.mul_sub]
  omega

/-! ## The isolation-engine reading -/

/-- A certificate as carried by a proof-carrying application: the enclave public key, the
signature `(R, S)` and the challenge `h = H(R ‖ A ‖ M)` computed from the payload. -/
structure Cert (G : Type u) where
  /-- The public key the signature is checked against. -/
  pk : G
  /-- The `R` component of the signature. -/
  R : G
  /-- The `S` component of the signature. -/
  S : Int
  /-- The challenge, i.e. the hash of commitment, public key and payload. -/
  chal : Int

/-- The isolation engine admits a certificate exactly when its Ed25519 signature verifies. -/
