/-
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

namespace PCA.Cert

/-!
## An abstract model of Ed25519 signature verification

We model the group-theoretic core of Ed25519 (the part an isolation engine's
certificate checker relies upon):

* `G` is the prime-order subgroup generated by the base point `B`, written
  additively, and equipped with a scalar action of `ZMod L` (`L` being the group
  order, i.e. the order of the base point).
* A secret key is a scalar `s : ZMod L`; the corresponding public key is
  `A = s • B`.
* A signature on a message `m` with nonce `r` is the pair `(R, S)` where
  `R = r • B` and `S = r + H(R, A, m) * s`.
* Verification of `(R, S)` against `A` checks the standard equation
  `S • B = R + H(R, A, m) • A`.

The hash function `H` is left completely abstract (an arbitrary function), so no
property of SHA-512 is assumed anywhere.
-/

variable {L : ℕ} {G : Type*} {Msg : Type*}

/-- The public key associated with the secret scalar `s`. -/

def pubKey [AddCommGroup G] [Module (ZMod L) G] (B : G) (s : ZMod L) : G := s • B

/-- The Ed25519 verification equation for the signature `(R, S)` on message `m`
under public key `A`, with challenge hash `H`. -/
