/-
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace PCA.Cert

/-- The order `ℓ = 2^252 + 27742317777372353535851937790883648493` of the prime-order
subgroup of the Ed25519 curve group generated by the standard base point. -/

theorem smul_base_inj (P : Params G) {c d : Scalar} (h : c • P.base = d • P.base) :
    c = d := by
  have : (c - d) • P.base = 0 := by
    rw [sub_smul, h, sub_self]
  have := P.base_faithful _ this
  exact sub_eq_zero.mp this

/-- **Soundness and completeness of the Ed25519 verification engine.**
A candidate signature `sig` passes the verification equation against the public key
`A = a • B` if and only if it is *the* honestly generated signature for a unique nonce
`r`: namely `sig.R = r • B` and `sig.S = r + H(sig.R, A, m) * a`.

The forward direction is soundness (anything the checker accepts really is the honest
Schnorr/EdDSA response for the committed nonce, so accepting a signature extracts a
witness for the key relation); the backward direction is completeness (honest
signatures are always accepted). -/
