/-
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace PCA.Cert

/-- The order `ℓ = 2^252 + 27742317777372353535851937790883648493` of the prime-order
subgroup of the Ed25519 curve group generated by the standard base point. -/

theorem verify_congr {M : Type*} (P : Params G) (H H' : G → G → M → Scalar) (A : G)
    (m : M) (sig : Sig G) (hH : H sig.R A m = H' sig.R A m) :
    verify P H A m sig ↔ verify P H' A m sig := by
  rw [verify, verify, hH]

/-- **Key extraction from a nonce reuse.** If two signatures with the same commitment
`R` but distinct challenges both verify against `A = a • B`, then the secret scalar is
recovered as `(S₁ - S₂) / (h₁ - h₂)`. This is the formal statement that the engine's
accept predicate leaks the whole secret under nonce reuse. -/
