/-!
# Ed 25519 Verify Sound
Category: Proof-Carrying Apps
Target: PCA.Cert.ed25519_verify_sound
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

/-
## Overview

This file formalises the algebraic core of Ed25519 signature verification, as used by a
proof-carrying-application *isolation engine*: the engine admits a payload only when the
attached certificate carries an Ed25519 signature that verifies against the enclave's
public key.

The concrete twisted-Edwards curve is abstracted to exactly the structure the argument
uses: a type `G` of curve points with an addition `add`, an integer scalar multiplication
`smul`, a base point `B`, and the order `L` of `B` (for Ed25519,
`L = 2 ^ 252 + 27742317777372353535851937790883648493`).  The three laws recorded in
`PCA.Cert.EdModel` are:

* `smul_add_base` : `[x]B + [y]B = [x + y]B`   (the group law on the cyclic subgroup `⟨B⟩`);
* `smul_smul_base` : `[x]([y]B) = [x * y]B`     (associativity of scalar multiplication);
* `base_eq_iff`   : `[x]B = [y]B ↔ L ∣ x - y`   (`B` has order exactly `L`).

`PCA.Cert.EdModel.ofOrder` builds such a model for every `L > 1`, so the axiomatisation is
consistent and the results below are not vacuous; `PCA.Cert.ed25519Model` instantiates it at
the true Ed25519 group order.  A Mathlib-idiomatic restatement over an arbitrary
`AddCommGroup` with a point of order `L`, together with the bridge to the results proved
here, lives in `RequestProject.Ed25519Mathlib`.

Key generation, signing and verification are modelled by

* secret scalar `s`, public key `A = [s]B`                          (`pubKey`),
* per-message nonce `r`, commitment `R = [r]B`                      (`commit`),
* challenge `h` (the integer `H(R ‖ A ‖ M)`),
* response `S = (r + h * s) mod L`                                  (`respond`),
* verification `[S]B = R + [h]A`                                    (`Verify`).

Main results:

* `ed25519_verify_sound` — **soundness**: whenever verification accepts a signature
  `(R, S)` under a public key `A = [s]B` with commitment `R = [r]B`, the response `S` is
  forced to be congruent mod `L` to the honest Schnorr response `r + h * s`.  No accepted
  signature can deviate from what the signing algorithm produces.
* `ed25519_verify_complete` — **completeness**: honestly generated signatures always verify.
* `ed25519_verify_iff` — soundness and completeness combined into a characterisation.
* `ed25519_response_unique` — the accepted response is unique modulo `L`.
* `ed25519_extract_secret_key` — special soundness: two accepting transcripts that share a
  commitment but use different challenges determine the secret key.
* `ed25519_engine_sound` — the isolation-engine reading: an admitted certificate carries
  precisely the honest signature of its payload under the enclave key.

The development is self-contained: it uses no imports beyond Lean's core `Init`, hence no
axioms beyond `propext`, `Classical.choice`, `Quot.sound`.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

universe u

namespace PCA.Cert

/-! ## The model -/

/-- An Ed25519-style signature model: a type of curve points `G` with addition `add`,
integer scalar multiplication `smul`, base point `B`, and group order `L` of `B`.

Only the behaviour of the operations on the cyclic subgroup generated by `B` is recorded,
since verification never leaves that subgroup. -/
structure EdModel (G : Type u) where
  /-- Addition of curve points. -/
  add : G → G → G
  /-- Integer scalar multiplication of curve points. -/
  smul : Int → G → G
  /-- The base point. -/
  B : G
  /-- The order of the base point (a prime, for Ed25519). -/
  L : Int
  /-- The order exceeds `1`. -/
  one_lt_L : 1 < L
  /-- Group law on `⟨B⟩`: `[x]B + [y]B = [x + y]B`. -/
  smul_add_base : ∀ x y : Int, add (smul x B) (smul y B) = smul (x + y) B
  /-- Associativity of scalar multiplication on `⟨B⟩`: `[x]([y]B) = [x * y]B`. -/
  smul_smul_base : ∀ x y : Int, smul x (smul y B) = smul (x * y) B
  /-- `B` has order exactly `L`: `[x]B = [y]B` iff `L` divides `x - y`. -/
  base_eq_iff : ∀ x y : Int, smul x B = smul y B ↔ L ∣ (x - y)

namespace EdModel

variable {G : Type u} (M : EdModel G)

/-- The public key belonging to the secret scalar `s`, namely `A = [s]B`. -/

theorem verify_iff_base_eq (s r h S : Int) :
    M.Verify (M.pubKey s) (M.commit r) h S ↔ M.smul S M.B = M.smul (r + h * s) M.B := by
  unfold EdModel.Verify EdModel.pubKey EdModel.commit
  rw [M.smul_smul_base, M.smul_add_base]

/-- **Soundness of Ed25519 verification.**

If the verification equation `[S]B = R + [h]A` holds for a public key `A = [s]B` and a
commitment `R = [r]B`, then the response `S` is congruent modulo the group order `L` to the
honest Schnorr response `r + h * s`.

Consequently an isolation engine that accepts a certificate only when this equation holds
can accept nothing other than a signature the legitimate signer would have produced: the
accepted `S` is determined, mod `L`, by the secret key `s`, the nonce `r` and the challenge
`h`. -/
