import Mathlib

/-!
# Mod-2 Milnor K-theory of a field

We define, for a field `F` and `n : ℕ`, the group `k^M_n(F) = K^M_n(F)/2`, the `n`-th mod-2
Milnor K-theory group, as the quotient of the free `𝔽₂`-vector space on `n`-tuples of units of
`F` by the submodule generated by

* multiplicativity in each slot: `{…, ab, …} = {…, a, …} + {…, b, …}`, and
* the Steinberg relation: `{a₁, …, aₙ} = 0` whenever `aᵢ + aⱼ = 1` for some `i ≠ j`.

Since the coefficients are `𝔽₂`, this is exactly `K^M_n(F) ⊗ 𝔽₂ = K^M_n(F)/2`.
-/

open scoped Classical

namespace Frontier

universe u

variable (F : Type u) [Field F]

/-- The set of defining relations for mod-2 Milnor K-theory in degree `n`. -/

theorem symbol_update_mul {n : ℕ} (i : Fin n) (a b : Fˣ) (t : Fin n → Fˣ) :
    symbol (F := F) (Function.update t i (a * b))
      = symbol (Function.update t i a) + symbol (Function.update t i b) := by
  have hmem : (Finsupp.single (Function.update t i (a * b)) 1
      - Finsupp.single (Function.update t i a) 1
      - Finsupp.single (Function.update t i b) (1 : ZMod 2)) ∈ milnorRelations F n :=
    Submodule.subset_span (Or.inl ⟨i, a, b, t, rfl⟩)
  have := (Submodule.Quotient.mk_eq_zero (milnorRelations F n)).2 hmem
  simp only [symbol]
  have h : (Submodule.Quotient.mk (Finsupp.single (Function.update t i (a * b)) (1 : ZMod 2))
      - Submodule.Quotient.mk (Finsupp.single (Function.update t i a) (1 : ZMod 2))
      - Submodule.Quotient.mk (Finsupp.single (Function.update t i b) (1 : ZMod 2))
      : MilnorK2 F n) = 0 := by
    rw [← Submodule.Quotient.mk_sub, ← Submodule.Quotient.mk_sub]; exact this
  linear_combination (norm := module) h

/-- The Steinberg relation. -/
