import Mathlib

/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace QPhys

open Matrix

/-- The time-evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`. -/

lemma conjTranspose_smul_of_isHermitian {n : Type*} [Fintype n] [DecidableEq n]
    {H : Matrix n n ℂ} (hH : H.IsHermitian) (hbar t : ℝ) :
    ((-Complex.I * (t / hbar)) • H)ᴴ = -((-Complex.I * (t / hbar)) • H) := by
  rw [Matrix.conjTranspose_smul, hH.eq]
  rw [← neg_smul]
  congr 1
  simp

/-- **Unitary time evolution.** For a self-adjoint Hamiltonian `H`, the operator
`U(t) = exp(-i H t / ℏ)` is unitary for every real time `t`. -/
