import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Brockian

/-! ## Goldbach representations on the `K = 2` wheel

The `K = 2` wheel is the wheel generated by the first two primes, so its modulus is
`2 * 3 = 6` and its spokes are the residues `1` and `5` modulo `6`.

`GoldbachWheelK2 m` says that every even number `n` with `10 ≤ n ≤ m` is a sum of two
primes **both of which lie on the wheel**, i.e. both are coprime to `6` (equivalently,
both are at least `5`). The lower bound `10` is sharp for this strengthened form: `6`
and `8` are sums of two primes only by using the off-wheel prime `3`.

The family is indexed by the bound `m`; this file adds the new member `m = 1051`.
-/

/-- The modulus of the `K = 2` wheel: the product of the first two primes. -/

private theorem primeB_spec {n : ℕ} (hn : n ≤ 1051) (h : primeB n = true) : Nat.Prime n := by
  unfold primeB at h
  simp [smallDivs] at h
  obtain ⟨h2, hd⟩ := h
  by_contra hp
  have h0 : 0 < n := by omega
  have hsq := Nat.minFac_sq_le_self h0 hp
  have hple : n.minFac ≤ 32 := by nlinarith
  have hpr : (n.minFac).Prime := Nat.minFac_prime (by omega)
  have hdvd : n.minFac ∣ n := Nat.minFac_dvd n
  have h2' : 2 ≤ n.minFac := hpr.two_le
  interval_cases h : n.minFac <;> simp_all [Nat.dvd_iff_mod_eq_zero] <;> omega

/-- A prime `≥ 5` lies on the `K = 2` wheel. -/
