import Mathlib

/-!
# Goldbach Wheel K 2 1153
Category: Brockian Corpus
Target: Brockian.GoldbachWheelK2_1153
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

set_option maxHeartbeats 4000000

namespace Brockian

/-- Goldbach's binary (`K = 2`) partition property, verified for every even number
up to the wheel modulus `1153`: every even `n` with `4 ≤ n ≤ 1153` is a sum of two primes.
Stated in the equivalent halved form `n = 2 * k` with `2 ≤ k ≤ 576`. -/

lemma goldbach_two_mul_le_576 :
    ∀ k : ℕ, 2 ≤ k → k ≤ 576 → ∃ p q : ℕ, p.Prime ∧ q.Prime ∧ p + q = 2 * k := by
  intro k h1 h2
  interval_cases k
  · exact ⟨2, 2, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 3, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 5, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 7, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 7, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 11, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 13, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 13, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 17, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 19, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 19, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 23, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 23, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 23, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 29, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 31, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 31, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 31, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 37, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 37, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 41, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 43, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 43, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 47, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 47, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 47, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 53, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 53, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 53, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 59, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 61, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 61, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 61, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 67, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 67, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 71, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 73, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 73, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 73, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 79, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 79, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 83, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 83, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 83, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 89, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 89, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 89, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 79, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 97, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 97, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 101, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 107, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 113, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 127, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 127, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 131, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 131, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 131, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 137, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 139, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 139, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 139, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 137, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 139, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 149, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 151, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 151, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 151, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 157, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 157, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 157, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 163, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 163, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 167, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 167, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 167, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 173, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 173, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 173, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 179, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 181, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 191, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 193, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 193, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 197, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 197, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 199, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 197, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 211, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 223, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 223, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 227, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 229, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 229, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 233, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 233, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 233, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 239, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 241, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 241, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 241, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 239, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 241, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 251, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 257, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 257, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 257, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 263, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 263, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 263, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 269, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 271, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 271, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 271, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 277, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 277, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 281, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 281, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 283, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 293, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 277, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 307, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 307, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 311, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 313, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 313, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 313, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 313, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 331, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 331, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 331, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 337, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 337, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 337, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨29, 317, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 337, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 347, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 349, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 349, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 353, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 353, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 353, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 359, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 359, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 359, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 349, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 367, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 373, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 379, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 379, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 383, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 383, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 383, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 389, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 379, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 397, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 397, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 401, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 401, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 401, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 397, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 401, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 409, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 419, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 421, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 421, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 421, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 419, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 421, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 431, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 433, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 433, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 433, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 439, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 439, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 443, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 443, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 443, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 449, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 449, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 449, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 439, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 457, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 457, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 461, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 463, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 463, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 463, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 467, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 479, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 479, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 479, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 457, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 487, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 487, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 491, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 491, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 491, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 487, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 503, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 499, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 521, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 523, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 541, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 541, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 541, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 547, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 547, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 547, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨47, 509, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 547, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 557, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 563, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 563, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 563, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 569, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 571, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 571, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 571, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 577, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 577, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 577, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 569, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 577, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 587, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 587, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 587, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 593, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 599, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 601, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 601, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 601, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 607, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 607, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 607, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 613, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 613, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 617, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 617, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 619, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 631, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 631, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 631, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 617, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 631, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 641, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 643, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 643, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 647, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 647, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 647, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 653, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 653, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 653, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 659, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 661, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 661, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 661, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 659, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 661, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 661, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 673, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 673, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 677, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 677, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 677, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 683, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 683, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 683, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 673, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 691, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 691, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 691, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 683, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 691, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 701, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 701, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 701, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 691, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 701, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 719, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 719, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 719, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 709, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 727, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 727, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 727, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 733, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 733, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 733, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 739, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 739, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 743, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 743, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 743, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 739, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 751, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 751, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 751, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 757, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 757, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 761, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 761, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 761, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 757, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 769, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 769, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 773, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 773, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 773, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 769, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 773, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 773, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 769, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 773, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 797, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 797, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 797, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 787, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 797, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 797, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 809, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 809, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 811, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 821, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 823, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 823, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 827, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 829, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 829, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 829, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 827, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 829, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 839, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 839, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 839, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 829, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 839, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 839, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 823, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 853, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 853, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 857, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 859, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 859, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 863, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 863, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 863, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 859, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 863, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 863, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 859, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 877, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 877, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 881, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 883, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 883, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 883, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 883, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 887, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 877, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 907, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 907, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 911, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 911, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 911, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 907, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 911, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 929, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 929, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 929, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 937, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 937, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 941, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 941, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 941, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 947, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 947, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 947, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 953, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 953, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 953, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨43, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 953, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 953, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 937, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 967, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 967, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 971, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 971, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 971, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 977, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 977, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 977, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 983, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 983, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 983, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨73, 919, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 991, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 991, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 991, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 997, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 997, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 997, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 983, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 997, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 997, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1009, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1009, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1013, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1013, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1013, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1019, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1021, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1021, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1021, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1019, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1021, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1031, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1033, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1033, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1033, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1031, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1039, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1049, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1051, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1051, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1051, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1049, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1051, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1061, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1063, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1063, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1063, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1061, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1061, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1069, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1087, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1087, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1091, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1093, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1093, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1097, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1097, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1097, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨31, 1087, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1117, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1117, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1117, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1123, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1123, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1123, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨3, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨5, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨7, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨29, 1109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨11, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨13, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨41, 1103, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨17, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨19, 1129, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨41, 1109, by norm_num, by norm_num, by norm_num⟩
  · exact ⟨23, 1129, by norm_num, by norm_num, by norm_num⟩
/-- **Goldbach wheel, `K = 2`, modulus `1153`.**

`1153` is prime (so it is admissible as a new wheel modulus), and the binary Goldbach
property holds throughout the whole wheel span: every even `n` with `4 ≤ n ≤ 1153`
is the sum of two primes. -/
