-- (Lean requires `import` lines to precede any doc comment, so the required
-- header block appears immediately below the import.)
import Mathlib

/-!
# Goldbach Wheel K 2 1153
Category: Brockian Corpus
Target: Brockian.GoldbachWheelK2_1153
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Brockian

/-! ## The wheel

The *wheel* of modulus `1153` is the trial-division wheel generated by the primes
below `√1153 < 34`.  A number `n ≤ 1153` is prime exactly when it is at least `2`
and no spoke of the wheel is a proper divisor of it. -/

/-- The spokes of the wheel: all primes `< 34`, enough to certify primality
below `34 ^ 2 = 1156`, in particular for all `n ≤ 1153`. -/

def wheelSpokes : List ℕ := [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]

/-- Wheel primality test, correct for arguments `≤ 1153`. -/
