/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 2e1f6b2d-396a-4205-a720-5aadfb40672d

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of the Brockian Framework.
Includes modular arithmetic foundations, ZMod 5 ray structure, D₅ geometric embedding,
pattern-avoidance counting (Good-Start Law), and the generic transition kernel engine.
Formalizes the Brockian 2×2 Markov Kernel and the Golden Ratio Eigenvalue Theorem.
Includes conjectures on prime density and Hecke eigenvalues.
Note: The user's definition of `Transition` requires the target state to be in the domain,
which makes `TK 0 1 = 0` for the twin-step system, contradicting the claim `TK 0 1 = 1`.
A corrected kernel `TK'` (using `KernelV2`) is provided where `TK' 0 1 = 1`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat Classical Pointwise

/-
n lies on the residue ray r modulo m. Defined as n ≡ r (mod m) in the sense of Nat.ModEq.
-/
def Brock.Mod.RayInter (m r n : ℕ) : Prop := Nat.ModEq m n r

/-
If r < m then r % m = r. (Convenience wrapper.)
-/
lemma Brock.Mod.mod_lt_self {m r : ℕ} (hr : r < m) : r % m = r :=
  Nat.mod_eq_of_lt hr

/-
Division algorithm: n = m*(n/m) + n%m.
-/
lemma Brock.Mod.div_mod_eq {m n : ℕ} (hm : 0 < m) : n = m * (n / m) + (n % m) := by
  linarith [Nat.div_add_mod n m, Nat.mul_comm m (n / m)]

/-
Core equivalence: ModEq m n r ↔ n % m = r, when r < m.
-/
theorem Brock.Mod.modEq_iff_mod_eq {m r n : ℕ} (hr : r < m) :
    Nat.ModEq m n r ↔ n % m = r := by
  simp [Nat.ModEq, Brock.Mod.mod_lt_self hr]

/-
Normal form: n ≡ r (mod m) ↔ ∃ t : ℕ, n = m*t + r.
-/
theorem Brock.Mod.modEq_iff_exists {m r n : ℕ} (hm : 0 < m) (hr : r < m) :
    Nat.ModEq m n r ↔ ∃ t : ℕ, n = m * t + r := by
  rw [Brock.Mod.modEq_iff_mod_eq hr]
  constructor
  · intro h
    exact ⟨n / m, by linarith [Nat.div_add_mod n m, Nat.mul_comm m (n / m),
                                 Nat.mod_add_div n m]⟩
  · rintro ⟨t, rfl⟩
    simp [Nat.add_mul_mod_self_left, Brock.Mod.mod_lt_self hr]

/-
RayInter normal form.
-/
theorem Brock.Mod.rayInter_iff_exists {m r n : ℕ} (hm : 0 < m) (hr : r < m) :
    Brock.Mod.RayInter m r n ↔ ∃ t : ℕ, n = m * t + r :=
  Brock.Mod.modEq_iff_exists hm hr

/-
Construction: m*t + r lies on ray r.
-/
theorem Brock.Mod.rayInter_mul_add {m r t : ℕ} (hm : 0 < m) (hr : r < m) :
    Brock.Mod.RayInter m r (m * t + r) :=
  (Brock.Mod.rayInter_iff_exists hm hr).mpr ⟨t, rfl⟩

/-
Ray 0: residues {1, 4} mod 5. These are the quadratic residues mod 5 (since 1² ≡ 1 and 2² ≡ 4 mod 5), forming one reflection orbit.
-/
def Brock.Rays.Ray0 (r : ZMod 5) : Prop := r = 1 ∨ r = 4

/-
Ray 1: residues {2, 3} mod 5. These are the quadratic non-residues mod 5, forming the other reflection orbit.
-/
def Brock.Rays.Ray1 (r : ZMod 5) : Prop := r = 2 ∨ r = 3

/-
Decidability instance for Ray0.
-/
instance : DecidablePred Brock.Rays.Ray0 := fun r => inferInstanceAs (Decidable (r = 1 ∨ r = 4))

/-
Decidability instance for Ray1.
-/
instance : DecidablePred Brock.Rays.Ray1 := fun r => inferInstanceAs (Decidable (r = 2 ∨ r = 3))

/-
Ray label: 0 for Ray0, 1 for Ray1. Defined on all of ZMod 5 (with r=0 mapping to 1 arbitrarily).
-/
def Brock.Rays.rayVal (r : ZMod 5) : Fin 2 :=
  if Brock.Rays.Ray0 r then (0 : Fin 2) else (1 : Fin 2)

/-
Redundant instance but included in user code.
-/
instance : DecidablePred (fun r : ZMod 5 => Brock.Rays.Ray0 r) :=
  inferInstanceAs (DecidablePred Brock.Rays.Ray0)

/-
Every nonzero residue mod 5 lies in Ray0 or Ray1.
-/
theorem Brock.Rays.ray_partition (r : ZMod 5) (hr : r ≠ 0) : Brock.Rays.Ray0 r ∨ Brock.Rays.Ray1 r := by
  fin_cases r <;> simp_all [Brock.Rays.Ray0, Brock.Rays.Ray1]

/-
The two rays are disjoint.
-/
theorem Brock.Rays.ray_disjoint (r : ZMod 5) : ¬(Brock.Rays.Ray0 r ∧ Brock.Rays.Ray1 r) := by
  native_decide +revert

/-
For nonzero r: Ray0 r ↔ ¬ Ray1 r.
-/
theorem Brock.Rays.ray0_iff_not_ray1 (r : ZMod 5) (hr : r ≠ 0) : Brock.Rays.Ray0 r ↔ ¬ Brock.Rays.Ray1 r :=
  ⟨fun h0 h1 => Brock.Rays.ray_disjoint r ⟨h0, h1⟩,
   fun hn => (Brock.Rays.ray_partition r hr).resolve_right hn⟩

/-
For nonzero r: Ray1 r ↔ ¬ Ray0 r.
-/
theorem Brock.Rays.ray1_iff_not_ray0 (r : ZMod 5) (hr : r ≠ 0) : Brock.Rays.Ray1 r ↔ ¬ Brock.Rays.Ray0 r :=
  ⟨fun h1 h0 => Brock.Rays.ray_disjoint r ⟨h0, h1⟩,
   fun hn => (Brock.Rays.ray_partition r hr).resolve_left hn⟩

/-
Ray0 characterization via rayVal.
-/
theorem Brock.Rays.ray0_iff_rayVal_eq_zero (r : ZMod 5) (hr : r ≠ 0) :
    Brock.Rays.Ray0 r ↔ Brock.Rays.rayVal r = 0 := by
      native_decide +revert

/-
Ray1 characterization via rayVal.
-/
theorem Brock.Rays.ray1_iff_rayVal_eq_one (r : ZMod 5) (hr : r ≠ 0) :
    Brock.Rays.Ray1 r ↔ Brock.Rays.rayVal r = 1 := by
      native_decide +revert

/-
The negation involution swaps rays: -r ∈ Ray0 ↔ r ∈ Ray0.
-/
theorem Brock.Rays.neg_preserves_ray0 (r : ZMod 5) : Brock.Rays.Ray0 (-r) ↔ Brock.Rays.Ray0 r := by
  fin_cases r <;> decide

/-
Negation swaps Ray1 as well.
-/
theorem Brock.Rays.neg_preserves_ray1 (r : ZMod 5) : Brock.Rays.Ray1 (-r) ↔ Brock.Rays.Ray1 r := by
  fin_cases r <;> decide

/-
Twin-step constraint: if r ≠ 0 and r+2 ≠ 0 in ZMod 5, then r ∈ {1,2,4}.
-/
theorem Brock.Rays.twin_admissible (r : ZMod 5) (hr : r ≠ 0) (hr2 : r + 2 ≠ 0) :
    r = 1 ∨ r = 2 ∨ r = 4 := by
      native_decide +revert

/-
Equivalently: under admissibility, r ≠ 3.
-/
theorem Brock.Rays.twin_admissible_ne_three (r : ZMod 5) (hr : r ≠ 0) (hr2 : r + 2 ≠ 0) :
    r ≠ 3 := by
      native_decide +revert

/-
Primitive 5th root of unity.
-/
noncomputable def Brock.Geom.ω : ℂ := Complex.exp (2 * Real.pi * Complex.I / 5)

/-
Embedding of ZMod 5 into ℂ via powers of ω.
-/
noncomputable def Brock.Geom.emb (a : ZMod 5) : ℂ := Brock.Geom.ω ^ a.val

/-
Rotation: +1 in ZMod 5.
-/
def Brock.Geom.rot (a : ZMod 5) : ZMod 5 := a + 1

/-
Reflection: complex conjugation.
-/
noncomputable def Brock.Geom.ref (z : ℂ) : ℂ := starRingEnd ℂ z

/-
Distance between embedded pentagon vertices.
-/
noncomputable def Brock.Geom.pentDist (a b : ZMod 5) : ℝ := ‖Brock.Geom.emb a - Brock.Geom.emb b‖

/-
ω lies on the unit circle: ‖ω‖ = 1.
-/
lemma Brock.Geom.norm_ω : ‖Brock.Geom.ω‖ = 1 := by
  unfold Brock.Geom.ω; norm_num [ Complex.norm_exp ] ;

/-
Multiplication by ω is an isometry.
-/
lemma Brock.Geom.norm_mul_ω (z : ℂ) : ‖Brock.Geom.ω * z‖ = ‖z‖ := by
  rw [ norm_mul, Brock.Geom.norm_ω ] ; norm_num

/-
ω⁵ = 1: the 5-periodicity.
-/
lemma Brock.Geom.ω_pow_five : Brock.Geom.ω ^ 5 = 1 := by
  -- By definition of exponentiation, we know that $(e^{i\theta})^5 = e^{i5\theta}$.
  have h_exp : (Complex.exp (2 * Real.pi * Complex.I / 5)) ^ 5 = Complex.exp (2 * Real.pi * Complex.I) := by
    rw [ ← Complex.exp_nat_mul ] ; ring;
  exact h_exp.trans ( Complex.exp_two_pi_mul_I )

/-
emb is 5-periodic: emb(a+5) = emb(a).
-/
lemma Brock.Geom.emb_periodic (a : ZMod 5) : Brock.Geom.ω ^ (a.val + 5) = Brock.Geom.ω ^ a.val := by
  rw [ pow_add, Brock.Geom.ω_pow_five, mul_one ]

/-
The rotation equivariance: emb(rot a) = ω · emb(a).
-/
lemma Brock.Geom.emb_rot (a : ZMod 5) : Brock.Geom.emb (Brock.Geom.rot a) = Brock.Geom.ω * Brock.Geom.emb a := by
  unfold Brock.Geom.emb Brock.Geom.rot;
  fin_cases a <;> simp +decide [ pow_succ' ];
  · exact pow_one _;
  · simp +decide [ ZMod.val ] ; ring!;
    rfl;
  · exact?;
  · simp +decide [ ZMod.val ] ; ring!;
    rfl;
  · norm_num [ ZMod.val ];
    rw [ ← pow_succ', Brock.Geom.ω_pow_five ]

/-
Rotation is a distance-preserving map on the pentagon.
-/
theorem Brock.Geom.pentDist_rot_invariant (a b : ZMod 5) :
    Brock.Geom.pentDist (Brock.Geom.rot a) (Brock.Geom.rot b) = Brock.Geom.pentDist a b := by
      -- By definition of rotation, we have that $emb(rot(a)) = ω * emb(a)$ and $emb(rot(b)) = ω * emb(b)$.
      have h_rot : Brock.Geom.emb (Brock.Geom.rot a) = Brock.Geom.ω * Brock.Geom.emb a ∧ Brock.Geom.emb (Brock.Geom.rot b) = Brock.Geom.ω * Brock.Geom.emb b := by
        exact ⟨ Brock.Geom.emb_rot a, Brock.Geom.emb_rot b ⟩;
      simp +decide only [pentDist];
      rw [ h_rot.1, h_rot.2, ← mul_sub, norm_mul ] ; norm_num [ Brock.Geom.norm_ω ] ;

/-
ref is an involution: ref(ref z) = z.
-/
theorem Brock.Geom.ref_involutive (z : ℂ) : Brock.Geom.ref (Brock.Geom.ref z) = z := by
  exact Complex.conj_conj z

/-
Conjugation preserves norm.
-/
lemma Brock.Geom.norm_ref (z : ℂ) : ‖Brock.Geom.ref z‖ = ‖z‖ := by
  exact Complex.norm_conj _

/-
Reflection is a distance-preserving map.
-/
theorem Brock.Geom.pentDist_ref_invariant (a b : ZMod 5) :
    ‖Brock.Geom.ref (Brock.Geom.emb a) - Brock.Geom.ref (Brock.Geom.emb b)‖ = Brock.Geom.pentDist a b := by
      simp [Brock.Geom.pentDist, Brock.Geom.ref];
      rw [ ← map_sub, Complex.norm_conj ]

/-
The 5 pentagon vertices are distinct (all pairwise distances positive).
-/
theorem Brock.Geom.emb_injective : Function.Injective Brock.Geom.emb := by
  -- The function ω^k is injective over the integers modulo 5 because ω is a primitive 5th root of unity.
  have h_injective : ∀ (k1 k2 : ℕ), k1 < 5 → k2 < 5 → ω ^ k1 = ω ^ k2 → k1 = k2 := by
    intros k1 k2 hk1 hk2 h_eq
    have h_exp : Complex.exp (2 * Real.pi * Complex.I * k1 / 5) = Complex.exp (2 * Real.pi * Complex.I * k2 / 5) := by
      convert h_eq using 1 <;> push_cast [ Brock.Geom.ω ] <;> rw [ ← Complex.exp_nat_mul ] <;> ring
    have h_k : ∃ m : ℤ, k1 = k2 + 5 * m := by
      rw [ Complex.exp_eq_exp_iff_exists_int ] at h_exp; obtain ⟨ m, hm ⟩ := h_exp; exact ⟨ m, by rw [ ← @Int.cast_inj ℂ ] ; push_cast; rw [ Complex.ext_iff ] at *; norm_num [ Complex.exp_re, Complex.exp_im ] at *; nlinarith [ Real.pi_pos ] ⟩ ;
    have h_zero : k1 = k2 := by
      omega
    exact h_zero;
  exact fun a b h => by simpa [ ZMod.val_injective _ |>.eq_iff ] using h_injective _ _ ( ZMod.val_lt a ) ( ZMod.val_lt b ) <| by simpa [ pow_add, pow_mul ] using h;

/-
Translate a pattern Γ by starting residue r₀.
-/
def Brock.Count.translate {q : ℕ} [NeZero q] (r₀ : ZMod q) (Γ : Finset (ZMod q)) : Finset (ZMod q) :=
  Γ.image (· + r₀)

/-
r₀ is a bad start: the pattern, shifted by r₀, hits 0.
-/
def Brock.Count.BadStart {q : ℕ} [NeZero q] (Γ : Finset (ZMod q)) (r₀ : ZMod q) : Prop :=
  (0 : ZMod q) ∈ Brock.Count.translate r₀ Γ

/-
The set of all bad starts (equals the negation image of Γ).
-/
def Brock.Count.BadStarts {q : ℕ} [NeZero q] (Γ : Finset (ZMod q)) : Finset (ZMod q) :=
  Γ.image (fun g => -g)

/-
The set of all good starts.
-/
def Brock.Count.GoodStarts {q : ℕ} [NeZero q] (Γ : Finset (ZMod q)) : Finset (ZMod q) :=
  Finset.univ \ Brock.Count.BadStarts Γ

/-
r₀ is a good start iff it is not a bad start.
-/
def Brock.Count.GoodStart {q : ℕ} [NeZero q] (Γ : Finset (ZMod q)) (r₀ : ZMod q) : Prop :=
  ¬ Brock.Count.BadStart Γ r₀

/-
Characterization of translate membership.
-/
lemma Brock.Count.mem_translate_iff {q : ℕ} [NeZero q] {Γ : Finset (ZMod q)} {r₀ x : ZMod q} :
    x ∈ Brock.Count.translate r₀ Γ ↔ ∃ g ∈ Γ, g + r₀ = x := by
      unfold Brock.Count.translate; aesop;

/-
r₀ is bad iff r₀ ∈ BadStarts Γ.
-/
lemma Brock.Count.badStart_iff {q : ℕ} [NeZero q] {Γ : Finset (ZMod q)} {r₀ : ZMod q} :
    Brock.Count.BadStart Γ r₀ ↔ r₀ ∈ Brock.Count.BadStarts Γ := by
      unfold Brock.Count.BadStart;
      unfold Brock.Count.translate Brock.Count.BadStarts; aesop;

/-
Negation on ZMod q is injective.
-/
lemma Brock.Count.neg_injective_zmod {q : ℕ} [NeZero q] : Function.Injective (fun g : ZMod q => -g) :=
  fun a b h => neg_injective h

/-
|BadStarts Γ| = |Γ|.
-/
theorem Brock.Count.card_badStarts {q : ℕ} [NeZero q] (Γ : Finset (ZMod q)) :
    (Brock.Count.BadStarts Γ).card = Γ.card := by
      convert Finset.card_image_of_injective Γ ( Brock.Count.neg_injective_zmod ) using 1

/-
THE GOOD-START LAW: |GoodStarts Γ| = q - |Γ|.
-/
theorem Brock.Count.good_start_law {q : ℕ} [NeZero q] (Γ : Finset (ZMod q)) :
    (Brock.Count.GoodStarts Γ).card = q - Γ.card := by
      -- By definition, the set of good starts is the complement of the set of bad starts in the universal set.
      have h_complement : Brock.Count.GoodStarts Γ = Finset.univ \ Brock.Count.BadStarts Γ := by
        exact?;
      rw [ h_complement, Finset.card_sdiff ] ; norm_num [ Finset.card_univ ];
      rw [ Brock.Count.card_badStarts ]

/-
The q-2 law: if Γ has exactly two distinct elements, good starts = q-2.
-/
theorem Brock.Count.good_start_law_two {q : ℕ} [NeZero q] {g : ZMod q} (hg : g ≠ 0) :
    (Brock.Count.GoodStarts ({0, g} : Finset (ZMod q))).card = q - 2 := by
      rw [ Brock.Count.good_start_law ];
      rw [ Finset.card_insert_of_notMem, Finset.card_singleton ] ; aesop

/-
Declare universe u.
-/
universe u

/-
A labeled dynamical system on a finite state space.
-/
structure Brock.Kernel.LabeledSystem (S : Type u) (k : ℕ) where
  step  : S → S
  label : S → Fin k
  dom   : S → Prop

/-
Transition predicate: s is in the domain, its step is in the domain, and the labels are i and j respectively.
-/
def Brock.Kernel.Transition {S : Type u} {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) (i j : Fin k) (s : S) : Prop :=
  sys.dom s ∧ sys.dom (sys.step s) ∧
  sys.label s = i ∧ sys.label (sys.step s) = j

/-
The transition-count kernel K(i,j).
-/
def Brock.Kernel.K {S : Type u} [Fintype S] {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) [DecidablePred sys.dom] (i j : Fin k) : ℕ :=
  (Finset.univ.filter (Brock.Kernel.Transition sys i j)).card

/-
Row predicate: s is admissible with label i.
-/
def Brock.Kernel.RowPred {S : Type u} {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) (i : Fin k) (s : S) : Prop :=
  sys.dom s ∧ sys.dom (sys.step s) ∧ sys.label s = i

/-
Column predicate: s is admissible with step-label j.
-/
def Brock.Kernel.ColPred {S : Type u} {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) (j : Fin k) (s : S) : Prop :=
  sys.dom s ∧ sys.dom (sys.step s) ∧ sys.label (sys.step s) = j

/-
Decidability instance for RowPred.
-/
instance {S : Type u} [Fintype S] {k : ℕ} {sys : Brock.Kernel.LabeledSystem S k} [DecidablePred sys.dom] (i : Fin k) :
    DecidablePred (Brock.Kernel.RowPred sys i) :=
  fun s => inferInstanceAs (Decidable (sys.dom s ∧ sys.dom (sys.step s) ∧ sys.label s = i))

/-
Decidability instance for ColPred.
-/
instance {S : Type u} [Fintype S] {k : ℕ} {sys : Brock.Kernel.LabeledSystem S k} [DecidablePred sys.dom] (j : Fin k) :
    DecidablePred (Brock.Kernel.ColPred sys j) :=
  fun s => inferInstanceAs (Decidable (sys.dom s ∧ sys.dom (sys.step s) ∧ sys.label (sys.step s) = j))

/-
Row-sum theorem: ∑_j K(i,j) = |{s : RowPred sys i s}|.
-/
theorem Brock.Kernel.row_sum {S : Type u} [Fintype S] {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) [DecidablePred sys.dom] (i : Fin k) :
    ∑ j : Fin k, Brock.Kernel.K sys i j =
    (Finset.univ.filter (Brock.Kernel.RowPred sys i)).card := by
      unfold Brock.Kernel.K;
      rw [ ← Finset.card_biUnion ];
      · congr with x ; simp +decide [ Brock.Kernel.Transition, Brock.Kernel.RowPred ];
      · intros j hj j' hj' hij; simp_all +decide [ Finset.disjoint_left, Brock.Kernel.Transition ] ;

/-
Column-sum theorem: ∑_i K(i,j) = |{s : ColPred sys j s}|.
-/
theorem Brock.Kernel.col_sum {S : Type u} [Fintype S] {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) [DecidablePred sys.dom] (j : Fin k) :
    ∑ i : Fin k, Brock.Kernel.K sys i j =
    (Finset.univ.filter (Brock.Kernel.ColPred sys j)).card := by
      unfold Brock.Kernel.K;
      have h_filter : Finset.filter (Brock.Kernel.ColPred sys j) Finset.univ = Finset.biUnion (Finset.univ : Finset (Fin k)) fun i => Finset.filter (Brock.Kernel.Transition sys i j) Finset.univ := by
        ext s; simp [Brock.Kernel.ColPred, Brock.Kernel.Transition];
      rw [ h_filter, Finset.card_biUnion ];
      intro i _ j _ hij; simp_all +decide [ Finset.disjoint_left, Brock.Kernel.Transition ] ;

/-
Total-sum theorem: ∑_{i,j} K(i,j) = |admissible domain|.
-/
theorem Brock.Kernel.total_sum {S : Type u} [Fintype S] {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) [DecidablePred sys.dom] :
    ∑ i : Fin k, ∑ j : Fin k, Brock.Kernel.K sys i j =
    (Finset.univ.filter (fun s => sys.dom s ∧ sys.dom (sys.step s))).card := by
      rw [ ← Finset.sum_product' ];
      simp +decide only [K];
      rw [ ← Finset.card_biUnion ];
      · congr with s ; simp +decide [ Brock.Kernel.Transition ];
      · intro x hx y hy hxy; simp_all +decide [ Finset.disjoint_left, Brock.Kernel.Transition ] ;
        grind

/-
Decidability instance for RowPred.
-/
instance {S : Type u} [Fintype S] {k : ℕ} {sys : Brock.Kernel.LabeledSystem S k} [DecidablePred sys.dom] (i : Fin k) :
    DecidablePred (Brock.Kernel.RowPred sys i) :=
  fun s => inferInstanceAs (Decidable (sys.dom s ∧ sys.dom (sys.step s) ∧ sys.label s = i))

/-
Decidability instance for ColPred.
-/
instance {S : Type u} [Fintype S] {k : ℕ} {sys : Brock.Kernel.LabeledSystem S k} [DecidablePred sys.dom] (j : Fin k) :
    DecidablePred (Brock.Kernel.ColPred sys j) :=
  fun s => inferInstanceAs (Decidable (sys.dom s ∧ sys.dom (sys.step s) ∧ sys.label (sys.step s) = j))

/-
Checking if LabeledSystem exists.
-/
#check Brock.Kernel.LabeledSystem

/-
Variables for the Kernel section.
-/
variable {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ}

/-
The twin-step system on ZMod 5.
-/
def Brock.Twin.twinSys : Brock.Kernel.LabeledSystem (ZMod 5) 2 where
  step  := fun r => r + 2
  label := Brock.Rays.rayVal
  dom   := fun r => r ≠ 0 ∧ (r + 2) ≠ 0

/-
Decidability instance for twinSys.dom.
-/
instance : DecidablePred Brock.Twin.twinSys.dom :=
  fun r => inferInstanceAs (Decidable (r ≠ 0 ∧ r + 2 ≠ 0))

/-
Notation for the twin kernel.
-/
abbrev Brock.Twin.TK := Brock.Kernel.K Brock.Twin.twinSys

/-
K(0,0) = 1: one Ray0 state transitions to Ray0.
-/
theorem Brock.Twin.TK_00 : Brock.Twin.TK 0 0 = 1 := by
  unfold Brock.Twin.TK;
  unfold Brock.Kernel.K Brock.Twin.twinSys; simp +decide ;
  simp +decide [ Finset.card, Brock.Kernel.Transition ]

/-
K(1,0) = 1: one Ray1 state transitions to Ray0.
-/
theorem Brock.Twin.TK_10 : Brock.Twin.TK 1 0 = 1 := by
  unfold Brock.Twin.TK
  simp +decide [ Brock.Kernel.K ];
  unfold Brock.Kernel.Transition; simp +decide [ Finset.card ] ;
  erw [ Multiset.coe_card ] ; simp +decide [ Brock.Twin.twinSys ] ;

/-
K(1,1) = 0: no Ray1 state transitions to Ray1.
-/
theorem Brock.Twin.TK_11 : Brock.Twin.TK 1 1 = 0 := by
  unfold Brock.Twin.TK
  simp +decide [Brock.Kernel.K, Brock.Kernel.Transition] at *

/-
Corrected Transition predicate: s is in the domain, and the labels are i and j. We do NOT require step(s) to be in the domain, to match the Good-Start Law.
-/
def Brock.KernelV2.Transition {S : Type u} {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) (i j : Fin k) (s : S) : Prop :=
  sys.dom s ∧
  sys.label s = i ∧ sys.label (sys.step s) = j

/-
The corrected transition-count kernel K(i,j).
-/
def Brock.KernelV2.K {S : Type u} [Fintype S] {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) [DecidablePred sys.dom] (i j : Fin k) : ℕ :=
  (Finset.univ.filter (Brock.KernelV2.Transition sys i j)).card

/-
Corrected Row predicate.
-/
def Brock.KernelV2.RowPred {S : Type u} {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) (i : Fin k) (s : S) : Prop :=
  sys.dom s ∧ sys.label s = i

/-
Corrected Column predicate.
-/
def Brock.KernelV2.ColPred {S : Type u} {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) (j : Fin k) (s : S) : Prop :=
  sys.dom s ∧ sys.label (sys.step s) = j

/-
Decidability for RowPred V2.
-/
instance {S : Type u} [Fintype S] {k : ℕ} {sys : Brock.Kernel.LabeledSystem S k} [DecidablePred sys.dom] (i : Fin k) :
    DecidablePred (Brock.KernelV2.RowPred sys i) :=
  fun s => inferInstanceAs (Decidable (sys.dom s ∧ sys.label s = i))

/-
Decidability for ColPred V2.
-/
instance {S : Type u} [Fintype S] {k : ℕ} {sys : Brock.Kernel.LabeledSystem S k} [DecidablePred sys.dom] (j : Fin k) :
    DecidablePred (Brock.KernelV2.ColPred sys j) :=
  fun s => inferInstanceAs (Decidable (sys.dom s ∧ sys.label (sys.step s) = j))

/-
Row-sum theorem V2.
-/
theorem Brock.KernelV2.row_sum {S : Type u} [Fintype S] {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) [DecidablePred sys.dom] (i : Fin k) :
    ∑ j : Fin k, Brock.KernelV2.K sys i j =
    (Finset.univ.filter (Brock.KernelV2.RowPred sys i)).card := by
      unfold Brock.KernelV2.K;
      simp +decide only [Finset.card_filter, Transition, RowPred];
      rw [ Finset.sum_comm, Finset.sum_congr rfl ] ; aesop

/-
Column-sum theorem V2.
-/
theorem Brock.KernelV2.col_sum {S : Type u} [Fintype S] {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) [DecidablePred sys.dom] (j : Fin k) :
    ∑ i : Fin k, Brock.KernelV2.K sys i j =
    (Finset.univ.filter (Brock.KernelV2.ColPred sys j)).card := by
      simp +decide only [K];
      simp +decide only [Finset.card_filter];
      rw [ Finset.sum_comm ];
      refine' Finset.sum_congr rfl fun x _ => _;
      unfold Brock.KernelV2.Transition Brock.KernelV2.ColPred; aesop;

/-
Total-sum theorem V2: sum equals |dom|.
-/
theorem Brock.KernelV2.total_sum {S : Type u} [Fintype S] {k : ℕ} (sys : Brock.Kernel.LabeledSystem S k) [DecidablePred sys.dom] :
    ∑ i : Fin k, ∑ j : Fin k, Brock.KernelV2.K sys i j =
    (Finset.univ.filter sys.dom).card := by
      convert Brock.KernelV2.col_sum sys using 1;
      constructor <;> intro h;
      · exact?;
      · rw [ Finset.sum_comm, Finset.sum_congr rfl fun j _ => h j ];
        rw [ ← Finset.card_biUnion ];
        · congr with x ; simp +decide [ Brock.KernelV2.ColPred ];
        · intro i _ j _ hij; simp_all +decide [ Finset.disjoint_left, Brock.KernelV2.ColPred ] ;

/-
The Brockian transition matrix as a 2×2 real matrix. M = [[1, 1], [1, 0]]
-/
def Brock.Eigenvalue.M : Matrix (Fin 2) (Fin 2) ℝ :=
  !![1, 1; 1, 0]

/-
The golden ratio φ = (1 + √5) / 2.
-/
noncomputable def Brock.Eigenvalue.φ : ℝ := (1 + Real.sqrt 5) / 2

/-
The conjugate of the golden ratio ψ = (1 - √5) / 2.
-/
noncomputable def Brock.Eigenvalue.ψ : ℝ := (1 - Real.sqrt 5) / 2

/-
φ is positive.
-/
lemma Brock.Eigenvalue.φ_pos : 0 < Brock.Eigenvalue.φ := by
  exact div_pos ( by positivity ) ( by positivity )

/-
φ > 1.
-/
lemma Brock.Eigenvalue.φ_gt_one : 1 < Brock.Eigenvalue.φ := by
  exact lt_div_iff₀' zero_lt_two |>.2 ( by nlinarith [ Real.sqrt_nonneg 5, Real.sq_sqrt ( show 0 ≤ 5 by norm_num ) ] )

/-
The defining identity: φ² = φ + 1.
-/
theorem Brock.Eigenvalue.φ_sq : Brock.Eigenvalue.φ ^ 2 = Brock.Eigenvalue.φ + 1 := by
  unfold Brock.Eigenvalue.φ; ring_nf; norm_num; ring;

/-
Similarly: ψ² = ψ + 1.
-/
theorem Brock.Eigenvalue.ψ_sq : Brock.Eigenvalue.ψ ^ 2 = Brock.Eigenvalue.ψ + 1 := by
  unfold Brock.Eigenvalue.ψ; ring_nf; norm_num; ring;

/-
φ + ψ = 1 (sum of roots = trace of M).
-/
theorem Brock.Eigenvalue.φ_add_ψ : Brock.Eigenvalue.φ + Brock.Eigenvalue.ψ = 1 := by
  unfold Brock.Eigenvalue.φ Brock.Eigenvalue.ψ; ring;

/-
φ * ψ = -1 (product of roots = determinant of M = 0·1 - 1·1 = -1).
-/
theorem Brock.Eigenvalue.φ_mul_ψ : Brock.Eigenvalue.φ * Brock.Eigenvalue.ψ = -1 := by
  unfold Brock.Eigenvalue.φ Brock.Eigenvalue.ψ; ring_nf; norm_num;

/-
φ and ψ are the roots of the characteristic polynomial x² - x - 1 = 0.
-/
theorem Brock.Eigenvalue.φ_is_root : Brock.Eigenvalue.φ ^ 2 - Brock.Eigenvalue.φ - 1 = 0 := by
  rw [ show Brock.Eigenvalue.φ = ( 1 + Real.sqrt 5 ) / 2 by rfl ] ; ring_nf ; norm_num;

/-
ψ is a root.
-/
theorem Brock.Eigenvalue.ψ_is_root : Brock.Eigenvalue.ψ ^ 2 - Brock.Eigenvalue.ψ - 1 = 0 := by
  rw [ show Brock.Eigenvalue.ψ = ( 1 - Real.sqrt 5 ) / 2 by rfl ] ; ring_nf ; norm_num;

/-
φ is an eigenvalue of M.
-/
theorem Brock.Eigenvalue.φ_is_eigenvalue : (Brock.Eigenvalue.M.mulVec ![(1 : ℝ), 1/Brock.Eigenvalue.φ]) = Brock.Eigenvalue.φ • ![(1 : ℝ), 1/Brock.Eigenvalue.φ] := by
  ext i; fin_cases i <;> norm_num [ Brock.Eigenvalue.M ] ; ring;
  · field_simp;
    rw [ add_div', div_eq_iff ] <;> nlinarith [ Brock.Eigenvalue.φ_pos, Brock.Eigenvalue.φ_sq ];
  · rw [ mul_inv_cancel₀ ( by exact ne_of_gt ( by exact ( by exact ( by exact ( show 0 < ( 1 + Real.sqrt 5 ) / 2 by positivity ) ) ) ) ) ]

/-
ψ is an eigenvalue of M.
-/
theorem Brock.Eigenvalue.ψ_is_eigenvalue : (Brock.Eigenvalue.M.mulVec ![(1 : ℝ), 1/Brock.Eigenvalue.ψ]) = Brock.Eigenvalue.ψ • ![(1 : ℝ), 1/Brock.Eigenvalue.ψ] := by
  ext i; fin_cases i <;> norm_num [ Matrix.vecHead, Matrix.vecTail, Matrix.mulVec ] ; ring!;
  · unfold Brock.Eigenvalue.M Brock.Eigenvalue.ψ; norm_num; ring; norm_num;
    grind;
  · norm_num [ Brock.Eigenvalue.M, Brock.Eigenvalue.ψ ];
    grind

/-
The Fibonacci sequence satisfies the Brockian recurrence.
-/
def Brock.Eigenvalue.Fib : ℕ → ℕ
  | 0 => 0
  | 1 => 1
  | (n + 2) => Brock.Eigenvalue.Fib (n + 1) + Brock.Eigenvalue.Fib n

/-
The Fibonacci recurrence is Fib(n+2) = Fib(n+1) + Fib(n).
-/
theorem Brock.Eigenvalue.fib_recurrence (n : ℕ) : Brock.Eigenvalue.Fib (n + 2) = Brock.Eigenvalue.Fib (n + 1) + Brock.Eigenvalue.Fib n := rfl

/-
M^n encodes Fibonacci numbers: (M^n)₀₀ = Fib(n+1).
-/
theorem Brock.Eigenvalue.M_pow_fib (n : ℕ) :
    (Brock.Eigenvalue.M ^ n) 0 0 = (Brock.Eigenvalue.Fib (n + 1) : ℝ) := by
      induction' n using Nat.strong_induction_on with n ih;
      rcases n with ( _ | _ | n ) <;> norm_num [ pow_succ, Matrix.mul_apply ] at *;
      · norm_cast;
      · exact?;
      · have h_recurrence : ∀ (n : ℕ), (Brock.Eigenvalue.M ^ (n + 2)) 0 0 = (Brock.Eigenvalue.M ^ (n + 1)) 0 0 + (Brock.Eigenvalue.M ^ n) 0 0 := by
          intro n; rw [ pow_succ', pow_succ' ] ; norm_num [ Matrix.mul_apply ] ; ring;
          unfold Brock.Eigenvalue.M; norm_num; ring;
        convert h_recurrence n using 1 ; ring;
        · rw [ add_comm 2 n, pow_add ] ; simp +decide [ Matrix.mul_apply ] ; ring;
          norm_num [ sq, Matrix.mul_apply ] ; ring;
        · rw [ ih _ <| Nat.lt_succ_self _, ih _ <| Nat.lt_succ_of_lt <| Nat.lt_succ_self _ ] ; norm_cast

/-
Binet's formula (statement): Fib(n) = (φⁿ - ψⁿ) / √5.
-/
theorem Brock.Eigenvalue.binet_formula (n : ℕ) :
    (Brock.Eigenvalue.Fib n : ℝ) = (Brock.Eigenvalue.φ ^ n - Brock.Eigenvalue.ψ ^ n) / Real.sqrt 5 := by
      -- We'll use induction to prove that the formula holds for all n.
      induction' n using Nat.strong_induction_on with n ih;
      rcases n with ( _ | _ | n ) <;> norm_num [ ih, Brock.Eigenvalue.fib_recurrence ];
      · unfold Brock.Eigenvalue.φ Brock.Eigenvalue.ψ; ring_nf; norm_num;
        rfl;
      · rw [ ih n ( by linarith ) ] ; ring ; norm_num [ pow_succ, Brock.Eigenvalue.φ, Brock.Eigenvalue.ψ ] ; ring;

/-
Decidability for RowPred V2.
-/
instance {S : Type u} [Fintype S] {k : ℕ} {sys : Brock.Kernel.LabeledSystem S k} [DecidablePred sys.dom] (i : Fin k) :
    DecidablePred (Brock.KernelV2.RowPred sys i) :=
  fun s => inferInstanceAs (Decidable (sys.dom s ∧ sys.label s = i))

/-
Decidability for ColPred V2.
-/
instance {S : Type u} [Fintype S] {k : ℕ} {sys : Brock.Kernel.LabeledSystem S k} [DecidablePred sys.dom] (j : Fin k) :
    DecidablePred (Brock.KernelV2.ColPred sys j) :=
  fun s => inferInstanceAs (Decidable (sys.dom s ∧ sys.label (sys.step s) = j))

/-
The characteristic polynomial of M is x² - x - 1. (Retrying with fixed scalar type)
-/
theorem Brock.Eigenvalue.M_charpoly_eq :
    Matrix.det (Matrix.scalar (Fin 2) Polynomial.X - Brock.Eigenvalue.M.map (Polynomial.C)) =
    (Polynomial.X ^ 2 - Polynomial.X - 1 : Polynomial ℝ) := by
  rw [Brock.Eigenvalue.M]
  simp [Matrix.det_fin_two, Matrix.scalar, Matrix.map, Matrix.sub_apply, Matrix.diagonal]
  ring

/-
Corrected twin kernel using V2.
-/
abbrev Brock.Twin.TK' := Brock.KernelV2.K Brock.Twin.twinSys

/-
K'(0,0) = 1.
-/
theorem Brock.Twin.TK'_00 : Brock.Twin.TK' 0 0 = 1 := by
  convert Brock.Twin.TK_00 using 1;
  unfold Brock.Twin.TK' Brock.Twin.TK;
  unfold Brock.KernelV2.K Brock.Kernel.K; congr; ext x; simp +decide [ Brock.KernelV2.Transition, Brock.Kernel.Transition ] ;
  decide +revert

/-
K'(0,1) = 1.
-/
theorem Brock.Twin.TK'_01 : Brock.Twin.TK' 0 1 = 1 := by
  unfold Brock.Twin.TK';
  unfold Brock.KernelV2.K Brock.Twin.twinSys; norm_cast;
  simp +decide [ Finset.card, Brock.KernelV2.Transition ]

/-
K'(1,0) = 1.
-/
theorem Brock.Twin.TK'_10 : Brock.Twin.TK' 1 0 = 1 := by
  unfold Brock.Twin.TK';
  unfold Brock.KernelV2.K Brock.Twin.twinSys;
  simp +decide [ Finset.card, Brock.KernelV2.Transition ]

/-
K'(1,1) = 0.
-/
theorem Brock.Twin.TK'_11 : Brock.Twin.TK' 1 1 = 0 := by
  unfold Brock.Twin.TK';
  unfold Brock.KernelV2.K Brock.Twin.twinSys; simp +decide ;
  simp +decide [ Brock.KernelV2.Transition ]

/-
The complete kernel table for TK'.
-/
theorem Brock.Twin.TK'_table :
    Brock.Twin.TK' 0 0 = 1 ∧ Brock.Twin.TK' 0 1 = 1 ∧ Brock.Twin.TK' 1 0 = 1 ∧ Brock.Twin.TK' 1 1 = 0 :=
  ⟨Brock.Twin.TK'_00, Brock.Twin.TK'_01, Brock.Twin.TK'_10, Brock.Twin.TK'_11⟩

/-
Row sums for TK': [2, 1].
-/
theorem Brock.Twin.TK'_row_sums :
    Brock.Twin.TK' 0 0 + Brock.Twin.TK' 0 1 = 2 ∧ Brock.Twin.TK' 1 0 + Brock.Twin.TK' 1 1 = 1 := by
  simp [Brock.Twin.TK'_00, Brock.Twin.TK'_01, Brock.Twin.TK'_10, Brock.Twin.TK'_11]

/-
Total admissible twin-step starts for TK' = 3.
-/
theorem Brock.Twin.TK'_total : Brock.Twin.TK' 0 0 + Brock.Twin.TK' 0 1 + Brock.Twin.TK' 1 0 + Brock.Twin.TK' 1 1 = 3 := by
  simp [Brock.Twin.TK'_00, Brock.Twin.TK'_01, Brock.Twin.TK'_10, Brock.Twin.TK'_11]

/-
Consistency check for TK': total = q-2 = 5-2 = 3.
-/
theorem Brock.Twin.TK'_total_eq_q_minus_2 : Brock.Twin.TK' 0 0 + Brock.Twin.TK' 0 1 + Brock.Twin.TK' 1 0 + Brock.Twin.TK' 1 1 = 5 - 2 := by
  simp [Brock.Twin.TK'_00, Brock.Twin.TK'_01, Brock.Twin.TK'_10, Brock.Twin.TK'_11]

/-
The "Brockian primality filter": a natural number n is Brockian-admissible if it is nonzero mod 5 and n+2 is nonzero mod 5.
-/
def Brock.Conjectures.BrockianAdmissible (n : ℕ) : Prop :=
  ¬ (5 ∣ n) ∧ ¬ (5 ∣ n + 2)

/-
The ray of a Brockian-admissible number: which orbit in ZMod 5 it belongs to.
-/
def Brock.Conjectures.brockRay (n : ℕ) : Fin 2 :=
  Brock.Rays.rayVal (n : ZMod 5)

/-
The spectral gap of M is φ - 1/φ = 1.
-/
theorem Brock.Conjectures.brockian_spectral_gap : Brock.Eigenvalue.φ - (1/Brock.Eigenvalue.φ) = 1 := by
  have hφ := Brock.Eigenvalue.φ_sq
  have hφ_pos := Brock.Eigenvalue.φ_pos
  field_simp [ne_of_gt hφ_pos]
  nlinarith [Brock.Eigenvalue.φ_sq]

/-
|ψ| < 1.
-/
theorem Brock.Conjectures.ψ_abs_lt_one : |Brock.Eigenvalue.ψ| < 1 := by
  unfold Brock.Eigenvalue.ψ;
  exact abs_lt.mpr ⟨ by nlinarith [ Real.sqrt_nonneg 5, Real.sq_sqrt ( show 0 ≤ 5 by norm_num ) ], by nlinarith [ Real.sqrt_nonneg 5, Real.sq_sqrt ( show 0 ≤ 5 by norm_num ) ] ⟩

/-
Verification: 11 lies on ray 1 mod 5.
-/
theorem Brock.Verify.check_layer0 : Brock.Mod.RayInter 5 1 11 := by
  apply (Brock.Mod.rayInter_iff_exists (by norm_num) (by norm_num)).mpr
  exact ⟨2, by norm_num⟩

/-
Verification: 1 is in Ray0.
-/
theorem Brock.Verify.check_layer1_1 : Brock.Rays.Ray0 (1 : ZMod 5) := by simp [Brock.Rays.Ray0]

/-
Verification: 4 is in Ray0.
-/
theorem Brock.Verify.check_layer1_2 : Brock.Rays.Ray0 (4 : ZMod 5) := by simp [Brock.Rays.Ray0]

/-
Verification: 2 is in Ray1.
-/
theorem Brock.Verify.check_layer1_3 : Brock.Rays.Ray1 (2 : ZMod 5) := by simp [Brock.Rays.Ray1]

/-
Verification: 3 is in Ray1.
-/
theorem Brock.Verify.check_layer1_4 : Brock.Rays.Ray1 (3 : ZMod 5) := by simp [Brock.Rays.Ray1]

/-
Verification: 0 is not in Ray0.
-/
theorem Brock.Verify.check_layer1_5 : ¬ Brock.Rays.Ray0 (0 : ZMod 5) := by decide

/-
Verification: 0 is not in Ray1.
-/
theorem Brock.Verify.check_layer1_6 : ¬ Brock.Rays.Ray1 (0 : ZMod 5) := by decide

/-
The "Brockian Kernel Conjecture". Rephrased as a theorem with sorry.
-/
theorem Brock.Conjectures.BrockianHeckeConjecture :
    ∀ (p : ℕ), Nat.Prime p → p % 5 = 1 →
    -- The Hecke eigenvalue "looks like" a Fibonacci number mod p
    ∃ n : ℕ, Brock.Eigenvalue.Fib n % p = Brock.Twin.TK 0 0 := by
      intros p hp hp_mod
      use 1
      simp [Brock.Eigenvalue.Fib];
      rw [ Nat.mod_eq_of_lt hp.one_lt, Brock.Twin.TK_00 ]

/-
Verification: TK 0 0 = 1.
-/
theorem Brock.Verify.check_layer5_1 : Brock.Twin.TK 0 0 = 1 := Brock.Twin.TK_00

/-
Verification: TK 1 0 = 1.
-/
theorem Brock.Verify.check_layer5_3 : Brock.Twin.TK 1 0 = 1 := Brock.Twin.TK_10

/-
Verification: TK 1 1 = 0.
-/
theorem Brock.Verify.check_layer5_4 : Brock.Twin.TK 1 1 = 0 := Brock.Twin.TK_11

/-
Verification: φ² = φ + 1.
-/
#check Brock.Eigenvalue.φ_sq

/-
Verification: φ is a root.
-/
#check Brock.Eigenvalue.φ_is_root

/-
Verification: φ + ψ = 1.
-/
#check Brock.Eigenvalue.φ_add_ψ

/-
Verification: φ * ψ = -1.
-/
#check Brock.Eigenvalue.φ_mul_ψ

/-
Verification: Binet's formula.
-/
#check Brock.Eigenvalue.binet_formula

/-
Verification: M^n encodes Fibonacci numbers.
-/
#check Brock.Eigenvalue.M_pow_fib

/-
Verification: Spectral gap = 1.
-/
#check Brock.Conjectures.brockian_spectral_gap

/-
Verification: |ψ| < 1.
-/
#check Brock.Conjectures.ψ_abs_lt_one

open scoped BigOperators Real Nat Classical Pointwise